- include/aspect/boundary_composition/interface.h
- source/boundary_composition/interface.cc
- source/simulator/core.cc
This is an improvement we need for #240 . So far boundary conditions for compositions had no update() function in their interface. This is necessary for loading new data or implementing complex time-dependent boundary conditions. 
At the same time I noticed that the boundary  condition for composition is handled differently than the one for temperature in core.cc. So far, if one prescribes no composition boundary condition we do not care and just make sure to not try to access it. But if one prescribes no fixed temperature boundary condition, simulator tries to access a null pointer and crashes without useful error messages. I see a few options to improve this:
1. I unified the handling of the two in the second patch. Boundary temperature will not longer be constructed and not longer …
> Update composition boundaries

- source/initial_conditions/adiabatic.cc
- source/initial_conditions/solidus.cc
- source/initial_conditions/spherical_shell.cc
- source/postprocess/basic_statistics.cc
- source/postprocess/table_heat_flux_statistics.cc
- source/postprocess/table_velocity_statistics.cc
- tests/no_adiabatic_heating_02/screen-output
- tests/stokes/screen-output
This should fix the broken tests introduced in #243 . Some of the plugins now require a boundary temperature to be prescribed, some can guess reasonable values if none is prescribed. Some test output changed, but it was actually wrong or at least meaningless before.
Since I changed the output of the basic_statistics slightly (there was a missing space beforehand) I expect other testcases to fail as well. I will update them accordingly later.
> Fix tests and allow for no prescribed boundary temperature.

- source/simulator/solver.cc
Using the change, we can also catch exceptions that do not just
indicate that the solver has run out of iterations, but also
exceptions that state that the underlying AztecOO solver from
Trilinos has failed with this matrix.
> Be less strict in which types of exceptions we catch.

- source/simulator/solver.cc
These places were written with ExcNoConvergence in mind, but if the underlying
Trilinos solver fails, we get an ExcMessage that was not printed.
> Adjust a few more places where we can produce better error messages.

- source/mesh_refinement/density.cc
- source/mesh_refinement/nonadiabatic_temperature.cc
- source/mesh_refinement/thermal_energy_density.cc
- source/mesh_refinement/viscosity.cc
Several of the mesh refinement modules were not working when Aspect is compiled with PETSc.  This fixes them.
> Fix petsc calls

- .gitattributes
- doc/Makefile
- doc/release-tasklist
- Use gitattributes to exclude files from the release tarball: scripts
and doc/manual/, which is used to generate manual.pdf.
- Update release tasks.- Use gitattributes to exclude files from the release tarball: scripts
and doc/manual/, which is used to generate manual.pdf.
- Update release tasks.
- doc/Makefile: better default target, cleanup, and nice error message if manual/ is missing.
> [WIP] update gitattributes and release tasklist

- doc/modules/changes.h
- source/material_model/steinberger.cc
What a tricky bug. It was in there since over two years and was never catched, because the tests unfortunately use tables with numtemp == numpress. I am a bit hesitant to create another test for this material model though, because it is so sensitive and already the existing tests are causing quite some trouble. Maybe this class can be at some time replaced by an AsciiDataLookup class from #240, when it is finished, so for now I would just fix the bug.
> Fix pressure bounds of steinberger material model.

- cookbooks/latent-heat.prm
- doc/manual/cookbooks/benchmarks/latent-heat/material.part.prm
- doc/manual/cookbooks/benchmarks/latent-heat/material.part.prm.out
- doc/modules/changes.h
- include/aspect/material_model/latent_heat.h
- source/material_model/latent_heat.cc
- tests/direct_solver_1.prm
- tests/direct_solver_2.prm
- tests/latent_heat.prm
This parameter is never used anywhere, and in fact there is another parameter who does, what this one suggests to do. The test results should not change (they pass on my machine), but there is a part in the manual that cites the cookbook parameter file. @tjhei: is the doc/manual/cookbooks/benchmarks/latent-heat/material.part.prm file updated automatically by some script, or should I update it manually?
> Remove unused parameter.

- source/initial_conditions/adiabatic.cc
Very small change, but it skips the unnecessary viscosity calculation for the IC, which is useful in some cases (e.g. when the viscosity depends on the lateral average of temperature). There is no effect  on model inputs or outputs so I guess an entry in changes.h is not needed?
> Skip viscosity calculation for adiabatic IC.

- doc/modules/changes.h
- source/material_model/latent_heat_melt.cc
The sign of the default value for the entropy change of melting in the latent_heat_melt material model is wrong. Apparently, when the signs of the latent heat terms in the equations were changed, the tests were updated (compare `tests/upwelling_melting_peridotite.prm`), but the default values were forgotten. The current formulation leads to heat release on melting, which causes more melting and more heat release ... .
> Fix sign of default entropy change of melting.

- include/aspect/global.h
- source/simulator/core.cc
- LinearAlgebraPETSc::MPI::CompressedBlockSparsityPattern got renamed
- Directly use BlockCompressedSimpleSparsityPattern for PETSc instead
- some cleanup
- this now compiles with Trilinos/PETSc in 8.2.1 and 8.3.pre again
> deal 8.3.pre linear algebra fixes

- CMakeLists.txt
QtCreator uses the cmake output to generate the project file and doesn't
list the headers unless we add them as "source files" inside cmake. It
looks like compilation is not affected by this change.
> include headers for QtCreator

- doc/modules/changes.h
- source/simulator/assembly.cc
- source/simulator/helper_functions.cc
- source/simulator/solver.cc
This should fix #298 . Lets see what the tester says about the changes. On my machine all of the iterated IMPES tests are working, and I also saw quite a speed-up compared to the old version, although the iteration count stayed constant. I am testing on battery though, so it might be related to throttling.
> Move pressure correction into the assembly.

- include/aspect/postprocess/visualization.h
- source/postprocess/visualization.cc
- tests/parallel_output_group_0/solution-00000.pvtu
- tests/parallel_output_group_0/solution-00001.pvtu
- tests/parallel_output_group_1/solution-00000.pvtu
- tests/parallel_output_group_1/solution-00001.pvtu
- tests/parallel_output_group_2/solution-00000.pvtu
- tests/parallel_output_group_2/solution-00001.pvtu
It turns out we need the current DataOut object for writing pvtu files
so we can write out the names of the fields.
> Fix data out

- doc/modules/changes.h
- include/aspect/boundary_composition/ascii_data.h
- include/aspect/boundary_composition/box.h
- include/aspect/boundary_composition/initial_composition.h
- include/aspect/boundary_composition/interface.h
- include/aspect/boundary_composition/spherical_constant.h
- include/aspect/boundary_temperature/ascii_data.h
- include/aspect/boundary_temperature/box.h
- include/aspect/boundary_temperature/constant.h
- include/aspect/boundary_temperature/function.h
- include/aspect/boundary_temperature/initial_temperature.h
- include/aspect/boundary_temperature/interface.h
- include/aspect/boundary_temperature/spherical_constant.h
- source/boundary_composition/ascii_data.cc
- source/boundary_composition/box.cc
- source/boundary_composition/initial_composition.cc
- source/boundary_composition/spherical_constant.cc
- source/boundary_temperature/ascii_data.cc
- source/boundary_temperature/box.cc
- source/boundary_temperature/constant.cc
- source/boundary_temperature/function.cc
- source/boundary_temperature/initial_temperature.cc
- source/boundary_temperature/spherical_constant.cc
- tests/tangurnis.cc
- tests/time-dependent-temperature-bc.cc
> Correct the type used to indicator boundary_ids.

- tests/blankenbach.prm
- tests/blankenbach/screen-output
- tests/blankenbach/statistics
This a test case that exactly resembles the case 1a of the blankenbach 1989 benchmark paper. @jdannberg is currently doing some work with extensions of this benchmark (so this setup is entirely her work), and they will eventually end up in the benchmark folder as well, but in the meantime I thought it might be nice to have one of them as tests to ensure the results do not change during the development. Since this benchmark is often used (and the parameter file we have in cookbooks/future is apparently broken), this might be a way to provide new users a way to reproduce this benchmark results. By the way, does someone remember what the cookbooks/future/blankenbach.prm file was supposed to do? There is no documentation in there and it triggers an assertion about negative density_cp values.
> Add blankenbach test

- include/aspect/compat.h
The implementation was missing a memory allocation.
> fix MPI::min

- tests/CMakeLists.txt
When I ran ctest on my computer it was passing some test even though the statistics files were different.  Upon investigation, Timo and I believe we found a bug in the CMakeLists.txt file in the test directory.
> Potential bug in CMakeList.txt in test folder

- tests/CMakeLists.txt
Reverts geodynamics/aspect#333
I think this was a mistake. Nearly all test are failing on mainline now, see [1]. The reason is that there is no target to generate ${_output}. If we depend on screen-output on the other hand, we will run the test and therefore generate ${_output}.
[1]: http://www.math.clemson.edu/~heister/aspect-logs/bf886f8e63f43dbac73899f346454ca807013884/
> Revert "Potential bug in CMakeList.txt in test folder"

- doc/modules/changes.h
- include/aspect/mesh_refinement/boundary.h
- source/mesh_refinement/boundary.cc
- tests/refinement_boundary.prm
- tests/refinement_boundary/screen-output
Similar to the topography refinement strategy, but the user gives a list of boundary indicators for refinement.  Sometimes the user may want refinement at the boundaries, even if there are no strong gradients there to trip other refinement criteria.
> Add refinement critereon based on boundary indicator

- AspectConfig.cmake.in
The marker made sense when we still used svn, but is no longer relevant with git.
> Remove a marker that still dates to subversion times.

- source/simulator/checkpoint_restart.cc
- source/simulator/parameters.cc
This is better than creating the link-time error that a bunch of symbols are undefined.
> Produce a compile time error if libz was not detected.

- AspectConfig.cmake.in
Plugins need to have the same CMAKE_BUILD_TYPE as ASPECT has. This patch
grabs the current ASPECT configuration during configure time.
Also print some more helpful information.
> detect plugin build type

- include/aspect/material_model/simpler.h
As reported by Rene at the hackathon, this #include file is not actually necessary.
> Remove an unnecessary include file.

- doc/modules/changes.h
- include/aspect/heating_model/interface.h
- include/aspect/simulator.h
- source/heating_model/interface.cc
- source/postprocess/internal_heating_statistics.cc
- source/postprocess/visualization/internal_heating.cc
- source/simulator/assembly.cc
Change the interface of the heating model plugin so that it gets the material model inputs and outputs. 
This is a first step towards moving all of the heating terms into the heating model.
> change heating interface

- source/material_model/interface.cc
Trivial error message improvements, specifically including the type of dependence lacking partial derivatives.
> Improved material model interface error messages

- tests/CMakeLists.txt
- tests/diff_test.sh
This is similar to how we do it in deal.II. The advantage is that the
output is a lot cleaner because cmake reports the whole command that
fails (which is now just referencing the shell script).
Also remove some weird logic and an unused target.
> [WIP] testing: move diff reporting to shell script

- include/aspect/simulator.h
- source/simulator/core.cc
- source/simulator/freesurface.cc
The idea here is that the internal manifolds are not necessarily a good way to refine cells when there is a free surface.  For significant deformations, the calculation of new mesh points could be very wrong.  However, the calculation of a nice starting mesh, as is done with the spherical shells model, is still nice.  So here I allow the initial refinements to happen as usual, but then detach the manifold indicators when the timestepping starts.
> Detach manifolds for free surface computations

- source/simulator/assembly.cc
Switched a term in the assembly to match how Wolfgang said it should be.
> Switched i and j in assembly

- source/boundary_composition/interface.cc
- source/boundary_temperature/interface.cc
- source/geometry_model/interface.cc
- source/gravity_model/interface.cc
- source/initial_conditions/interface.cc
- source/material_model/interface.cc
The default values for geometry/gravity/material/... model are "", which
creates a rather long and unhelpful error message from deal.II. Catch
this case earlier and provide a helpful error.
> improve error if no model selected

- source/simulator/assembly.cc
this is closer to the mathematical notation and will make the 3 tests
work again that broke with PR #388.
> reorder assembly terms again

- include/aspect/material_model/interface.h
- include/aspect/simulator.h
- source/adiabatic_conditions/initial_profile.cc
- source/initial_conditions/adiabatic.cc
- source/material_model/interface.cc
- source/mesh_refinement/density.cc
- source/mesh_refinement/thermal_energy_density.cc
- source/mesh_refinement/viscosity.cc
- source/postprocess/dynamic_topography.cc
- source/postprocess/heat_flux_statistics.cc
- source/postprocess/internal_heating_statistics.cc
- source/postprocess/mass_flux_statistics.cc
- source/postprocess/table_heat_flux_statistics.cc
- source/postprocess/viscous_dissipation_statistics.cc
- source/postprocess/visualization/density.cc
- source/postprocess/visualization/dynamic_topography.cc
- source/postprocess/visualization/friction_heating.cc
- source/postprocess/visualization/material_properties.cc
- source/postprocess/visualization/specific_heat.cc
- source/postprocess/visualization/thermal_expansivity.cc
- source/postprocess/visualization/viscosity.cc
- source/simulator/assembly.cc
- source/simulator/helper_functions.cc
- source/simulator/nullspace.cc
- tests/cell_reference.cc
- tests/cell_reference.prm
- tests/cell_reference/screen-output
- tests/cell_reference/statistics
This pull request adds a velocity and a cell reference to the material model inputs. The cell reference is useful for evaluating material properties at points different from the quadrature points (e.g. the cell midpoint), and we use the velocity to determine if material has crossed a certain region. Additionally, the velocity is needed for the extended heating model (to compute the adiabatic heating).
If you prefer, I can keep the huge test out of the PR, this is just exactly what we used the cell reference for, so I will keep it on a private branch for myself then. Unfortunately for this purpose the testdata can not be smaller than this.
> Velocity and Cell Reference in material interface

- source/simulator/assembly.cc
Fixed the order of terms in the RHS so that it follows our idea of multiplying with the test function on the left (This will also eventually match the weak form I am putting in the manual).
(Wait to see if this breaks anything.)
> Fixed order of RHS terms

- include/aspect/material_model/interface.h
- source/material_model/interface.cc
- source/simulator/assembly.cc
and passes the position to the specific average function. This is a step towards being able to have weighted averages for the materials. 
It seems to think a lot line are changed, but that is probably due to astyle.
> Added the material inputs variable to the general average function,

- CMakeLists.txt
- tests/CTestCustom.ctest.in
- tests/print_test_info.sh
It turns out cmake 2.8.11 can not deal with function arguments in CTestCustom.ctest so ```echo 'bla'``` doesn't work. :-(
> fix quick test with old cmake versions

- CMakeLists.txt
- source/main.cc
Do a configure check to ensure we have feenableexcept. Also switch to
the c version of the header because the cxx version would require c++11.
> harden floating point exception check

- doc/modules/changes.h
- include/aspect/postprocess/interface.h
- include/aspect/postprocess/visualization.h
- include/aspect/simulator_access.h
- source/postprocess/interface.cc
- source/postprocess/visualization.cc
- tests/plugin_dependency.cc
- tests/plugin_dependency.prm
- tests/plugin_dependency/screen-output
- tests/plugin_dependency_redundant.cc
- tests/plugin_dependency_redundant.prm
- tests/plugin_dependency_redundant/screen-output
- tests/plugin_dependency_redundant_02.cc
- tests/plugin_dependency_redundant_02.prm
- tests/plugin_dependency_redundant_02/screen-output
- tests/viz_plugin_dependency.cc
- tests/viz_plugin_dependency.prm
- tests/viz_plugin_dependency/screen-output
Using this, postprocessors can say that they want other postprocessors to run as well, for example because they want to reuse information these other postprocessors have already computed.
Fixes #460
> Add dependencies in postprocessors

- cookbooks/latent-heat.prm
- cookbooks/shell_simple_3d.prm
- cookbooks/stokes.prm
For reasons that are beyond a solid understanding, the function parser
thinks that 4 or more digits are not a number on some Mac OS X
systems. The problem is that it thinks that the locale *requires*,
not just allows, the use of commas as thousands separators. It then
thinks that such numbers are obviously names, and complains that
the symbol has not been assigned a numerical value. Very awkward to
make sense of.
This only appears to be a problem inside the function parser. All other
parameters that are not treated as function expressions are ok.
> Fix cookbooks so they can run on odd Macs as well.

- tests/terminate_user_request.cc
- tests/terminate_user_request/screen-output
The test terminate_user_request terminates when finding the file
restart.mesh which is generated after a couple of time steps. If this
test is run again from a directory that is not clean, it will fail if
restart.mesh still exists. Fix this deleting this file by loading a
plugin upon loading.
> fix tests/terminate_user_request

- include/aspect/material_model/interface.h
- source/material_model/interface.cc
- source/simulator/assembly.cc
into the interface of the averaging of the material model interface.
Because the new averaging schemes are implemented as material models,
these interfaces are not required anymore.
> Revert part of the changes which included MaterialModelInputs<dim>

- include/aspect/postprocess/interface.h
- source/postprocess/interface.cc
- tests/plugin_dependency/screen-output
- tests/plugin_dependency_redundant/screen-output
- tests/viz_plugin_dependency/screen-output
This requires building a list that orders postprocessors so that dependencies come before
dependents.
> Implement that postprocessor plugins are run in proper order.

- doc/modules/groups.h
The documentation confused me because it does not mention the term
'material model', which I have become accustomed to when looking
for the description of the material properties.
This fixes #410.
> Update group text for the material model.

- CMakeLists.txt
intel compiler <15 is not handling FP exceptions well, so disable them.
> disable FPE only on old intel

- include/aspect/geometry_model/chunk.h
- source/geometry_model/chunk.cc
Intel doesn't like separating declaration and definition of ChunkGeometry
inside an anonymous namespace. Having an anonymous namespace in a .h is weird
anyway, so move it.
Also fix doxygen documentation.
> Fix Chunk GeometryModel

- tests/CMakeLists.txt
This patch forces a test <testname> to be run even if the directory
<testname>/ does not contain any reference files. This is useful when creating
a new test, because you can run it to generate reference data.
Addresses #449
> run tests even if folder is empty

- source/postprocess/visualization.cc
Bug reported by Siqi Zhang on the ASPECT mailing list. HDF5 output might
be corrupted after resuming from a snapshot when the mesh file is not
written. This is likely happening because the ordering of vertices or
some other data structure can be different when we reconstruct the mesh
after resuming.
Fix this by writing the mesh data after we resume from a snapshot.
> fix hdf5 output after resume

- source/simulator/assembly.cc
This allows us to catch cases where we forget to initialize certain
variables by using FPEs.
> initialize fe scratch data to nan

- source/simulator/helper_functions.cc
This can happen if the gravity model happens to return a zero vector at some points.
> Avoid a division by zero.

- CMakeLists.txt
- cmake/fpe_check.cmake
Note that some library we link with in ASPECT on some platforms will
trigger floating point exceptions when converting
-numeric_limits<double>::max to a string. The only thing we can do is a
configure check and disable the exceptions.
> rework floating point exception configure

- tests/cmake/diff_test.sh
It has always bothered me that it was hard to tell how much of an actual diff I get
to see, since (i) we only ever print the first 50 lines, but (ii) we don't say how
many lines are actually shown. Improve this.
> Describe better how much of the diff output is actually shown.

- source/simulator/initial_conditions.cc
At `source/simulator/initial_conditions.cc:117` there is an assert that checks that all compositional fields are initialized to positive values. There are cases where I'd like to use compositional fields to track things (like vector components) where negative values are permissible.
Is there a fundamental reason why this assert is necessary, or is it only there on the assumption that a negative value must be a mistake on the users part?
Would anyone be opposed to removing this assert?
> Do not check that compositions are initialized to positive values.

- source/material_model/simple.cc
Another manual typo I forgot telling Ryan in the Hackathon. There should be a negative sign before thermal viscosity exponent \beta in the temperature pre-factor for the viscosity formula in the simple model.
> Omit "-" sign in the simple material model

- tests/CMakeLists.txt
If a test .prm ends without a newline, the "output directory" line we
add before running won't take effect. This causes weird test failures
about missing output files. Work around this by inserting a newline.
> fix bug if test .prm does not end with newline

- CMakeLists.txt
- cmake/generate_reference_output.sh
- tests/cmake/diff_test.sh
- add environment variable ASPECT_GENERATE_REFERENCE_OUTPUT to change
ctest to copy failed test output to the reference directory instead
- add script to run ctest this way and generate a patch file
- add generate_reference_output make target to do this in a user-friendly way
> new generate_reference_output target

- tests/cmake/diff_test.sh
The bash script was broken because it used integer comparison with a
potentially empty string.
> fix test diffing

- source/simulator/helper_functions.cc
- tests/no-conduction-timestep.prm
- tests/no-conduction-timestep/screen-output
- tests/no-conduction-timestep/statistics
If we calculate the conduction timestep, but the conductivity is set to zero we currently produce a division-by-zero floating point exception. This change prevents this, and also updates some outdated comments.
Now, the logic for cases with a velocity and conduction of 0 is also handling this case correctly.
The problem should only happen in artificial testcases, therefore I do not think anybody will ever notice this change (apart from the cleaner code).
> Secure timestep calculation

- include/aspect/material_model/averaging.h
- include/aspect/material_model/interface.h
- source/material_model/averaging.cc
- source/material_model/interface.cc
- tests/average-log.prm
- tests/average-log/screen-output
The log material averaging option is added. Similar to other averaging options, the test results have a narrower pressure range than no averaging. The pressure range of log averaging is also close to those of other averaging.
> add a new log material averaging option

- include/aspect/parameters.h
- include/aspect/simulator.h
- source/simulator/checkpoint_restart.cc
- source/simulator/core.cc
- source/simulator/parameters.cc
For the model I use it is usually unnecessary to calculate the stokes solution (in much detail) for the pre-refinment steps (the steps before the last timestep 0). These changes allow you to set the amount of nonlinear iterations of these pre-refinment steps. The default value (-1) means that the value is set to be the same as the Max nonlinear iterations parameter. These changes have been implemented in all the solvers which support nonlinear iterations: stokes only, iterated IMPES and iterated stokes.
> Add maximum nonlinear iterations for the prerefinement

- source/material_model/interface.cc
Log averaging generates FPE when encountering 0 values. We can not get
rid of all of them (compressibilities, entropy_derivative_pressure,
...), so handle 0 appropriately here.
> fix log_average FPE

- source/material_model/averaging.cc
- tests/average-nwd-arithmetic/screen-output
- tests/average-nwd-geometric/screen-output
- tests/average-nwd-harmonic/screen-output
I think we do not need this loop (as we already do the loop over all quadrature points within the individual averaging functions), and in the case of the averaging schemes that do not generate one average for all of the points in one cell, but calculate position-dependent, different values for every point, this even generates different results (because we average several times). 
Please correct me if I am wrong!
> remove an unwanted loop

- include/aspect/prescribed_stokes_solution/interface.h
- source/prescribed_stokes_solution/interface.cc
- source/simulator/core.cc
This allows time-dependent prescribed stokes solutions. The prescribed_stokes_solution/function plugin allows this already (copy-paste from another function plugin), but we never prepared core.cc and the interface class for this behaviour. We currently want to use this feature to make convergence tests for particle integrators.
> Add an update() function for prescribed stokes solution

- cookbooks/crustal_model_2D.prm
- cookbooks/crustal_model_3D.prm
- doc/manual/cookbooks/crustal_deformation/crustal_model_2D_part3.prm
- doc/manual/cookbooks/crustal_deformation/crustal_model_2D_part3.prm.out
- doc/manual/cookbooks/crustal_deformation/crustal_model_2D_part4.prm
- doc/manual/manual.tex
I believe this goes a long way towards addressing #526.  The fix was introduced in #537, but I am now applying it to the cookbook.
For large deformations advection of the free surface in the surface-normal direction can go unstable. Advecting in the direction of the local vertical seems to do a better job.  Here are some images of the 2D crustal deformation cookbook after 1 Myr:
Before:
Note the instabilities forming where there are changes in slope.
After:
Much more stable, it seems.
> Advect in the vertical direction for this cookbook

- doc/modules/changes.h
This is a correction for the changes.h entry of #565. User-written models do not need to change anything, because all dependencies are initialized to `Dependence::uninitialized`, but the stokes_matrix_depends_on_solution() checks for `Dependence::none`. Therefore not setting the viscosity dependence is interpreted as having a dependence, which is a good default value (some user models might now rebuild the preconditioner, although they dont need to, but that is better than not rebuilding, when it is needed).
> Correct changes.h

- doc/manual/manual.tex
Previously, section links and URLs in the manual were printed in blue, 
but references in light green. This is neither readable, nor conforming
to widely used styles. Change the color to blue also in that case.
> Change color of references to blue.

- source/simulator/core.cc
When either prescribed velocity or prescribed traction boundary indicators were given in the input file, the prescribed boundary indicators were not compared against the other given velocity boundary indicators. Now all traction or velocity boundary conditions indicators that are listed twice should throw.
> Add check prescribed BI when only vel or traction is prescribed

- source/simulator/simulator_access.cc
I ran into a case the other day where I wanted to access the FiniteElement object from a material model, and found out that there are cases where the material model is evaluated before the dof_handler object has been initialized (called from AdiabaticConditions::InitialProfile::initialize()). I would have benefited from a more specific error message than the one I got from deal.II.
> Improve debugging.

- source/simulator/checkpoint_restart.cc
It seems weird to add a comment on a sort of basic object orientated construct like this, but because that variable looks local I found it nonintuitive that the function doesn't overwrite it every time it executes.
> Augment comment for checkpoint resume function

- source/mesh_refinement/nonadiabatic_temperature.cc
- source/mesh_refinement/viscosity.cc
- source/simulator/freesurface.cc
- source/simulator/helper_functions.cc
This should address #611. It compiles and tests seem to run fine (except for the usual deviations in number of iterations, etc.). I stumbled over this, because I think we can use the same typedef for the tracer indices in #411. The number of tracers will likely reach similar number as the number of dofs, so using the same type seems reasonable to me.
> Replace unsigned ints with types::global_dof_index

- doc/modules/changes.h
- source/simulator/parameters.cc
This patch adds the ability to set "Resume computation = auto" which checks on startup whether a resume file exists, and uses it if so. Otherwise it starts the model from scratch. "true" and "false" are still valid options, and the default behavior is unchanged. I don't know if the ParameterHandler::get_bool() function handles other inputs (like "yes"/"no"). If so, those cases will not work with this patch.
> Add option to auto resume models

- doc/modules/changes.h
- source/simulator/freesurface.cc
This is an attempt to fix #612.
This was a difficult bug to reproduce and track down, so I'd appreciate it if @MFraters could check if this fixes the problem he was seeing. The basic problem was that we are rebuilding the constraints on the mesh motion at every time-step, but only setting up the sparsity pattern for the remeshing matrix after redistributing the mesh. In certain difficult-to-predict cases (especially when tangential constraints are involved) the sparsity pattern can be no longer valid for the computed constraints.
The fix here is just to rebuild the sparsity pattern after rebuilding the constraints object. This should be somewhat less efficient, but I don't think that this step was very expensive to begin with.
Thoughts?
> Rebuild sparsity pattern after rebuilding constraints

- source/main.cc
If you try to re-run aspect from one of the automatically generated prms you run in to some problems. This patch fixes one of them.
> Strip comments from Additional shared libraries parameter

- doc/manual/manual.tex
- had no line breaks and went off the page
- tex listing environment is not as pretty as a fancybox with shadows
> manual: fix CIG acknowledgement

- include/aspect/material_model/diffusion_dislocation.h
- source/material_model/diffusion_dislocation.cc
- source/material_model/drucker_prager.cc
- tests/diffusion_dislocation/screen-output
- tests/diffusion_dislocation/statistics
I tried to combine these two material models into a new one for a different purpose. During that I noticed that they are extremely unstable, throwing floating-point exceptions in many models. Additionally, they do more or less the same thing, but it is quite differently implemented. So I tried to unify the look, and make them more robust. The tests change marginally, but I think the new version is preferable.
I have a question for @anne-glerum and @bobmyhill, before merging: Drucker-prager currently uses the second invariant of the deviatoric strain rate, while diffusion-dislocation uses the second invariant of the full strain rate. Is this correct, or should we look into unifying this?
> Avoid floating point problems

- include/aspect/simulator_access.h
This includes forward declaration. Fixes a warning posted by Luca Heltai.
> Use 'struct' consistently for all declarations.

- doc/manual/manual.tex
- include/aspect/material_model/interface.h
- source/heating_model/shear_heating.cc
- source/material_model/interface.cc
- source/simulator/assembly.cc
- tests/anisotropic_viscosity.cc
- tests/anisotropic_viscosity.prm
- tests/anisotropic_viscosity/screen-output
- tests/anisotropic_viscosity/statistics
Still a work in progress.
Is backwards compatible with isotropic material models: per Timo's suggestion the original viscosity paramter is still used and the optional viscosity tensor is set to the identity by default.
Also, could someone clarify to me how the divergence of u term for the compressible case works in the bilinear form? Does it need to get multiplied by the trace of the viscosity tensor? I think this happens implicitly when viscosity is isotropic, but I've managed to confuse myself about it.
> Generalize constitutive law with optional tensor

- doc/astyle.rc
It looks like somebody ran astyle on the astyle.rc file, which messed up
indentation. Revert that.
> Revert astyle.rc changes in 784b7df

- doc/manual/manual.tex
- doc/modules/changes.h
- include/aspect/parameters.h
- source/simulator/parameters.cc
- source/simulator/solver.cc
This pull request makes the preconditioning tolerances of the A and S block available as parameters and add a section in the manual in the section on make aspect run faster where advice is given on how to use these parameters.
> Make the preconditioning tolerances of the A and S block available as parameters.

- include/aspect/compat.h
- include/aspect/compositional_initial_conditions/function.h
- include/aspect/initial_conditions/adiabatic.h
- include/aspect/simulator.h
- include/aspect/simulator_access.h
- source/simulator/checkpoint_restart.cc
- source/simulator/core.cc
While recompiling aspect with gcc5.1 (our cluster switched its default compilers) I got a lot of deprecation warnings for the use of `auto_ptr`. Since it will be removed in C++17, maybe we can replace it by `unique_ptr` anyway?
Also I got hundreds of warnings for including `deal.II/base/multithread_info.h:64` in `aspect/global.h` that I did not get before (e.g. gcc 4.8 did not output them). Is this an issue in deal.II, or do we have to live with that until this line gets removed (after the release of deal.II 8.4?)?
> Fix warnings gcc 51

- doc/modules/changes.h
- source/material_model/averaging.cc
- source/material_model/depth_dependent.cc
This fixes the fact that compositing material models (specifically the depth dependent
and averaging material models) held pointers to base models that may need to access
the simulator, but never initialized these base models' pointers to the Simulator
object. This patch fixes this by intercepting the initializing call.
> Initialize SimulatorAccess object for compositing material models.

- source/initial_conditions/S40RTS_perturbation.cc
- source/initial_conditions/SAVANI_perturbation.cc
- source/material_model/depth_dependent.cc
- source/material_model/steinberger.cc
- source/particle/generator.cc
- source/simulator/core.cc
- source/utilities.cc
- source/velocity_boundary_conditions/gplates.cc
Specifically, in error messages that report about files that can't be opened, do
(i) use the words 'could not' instead of 'couldn't', and (ii) do not forget to
close the '>' tag after the name of the file that could not be opened.
> Fix grammar and style of a number of error messages.

- include/aspect/heating_model/constant_heating.h
- include/aspect/heating_model/function.h
- include/aspect/heating_model/radioactive_decay.h
- source/heating_model/constant_heating.cc
- source/heating_model/function.cc
- source/heating_model/radioactive_decay.cc
This patch was my attempt to fix the remaining deprecation warnings in the heating model with gcc 5.1 (mentioned in #668). It will replace the implementation of the specific_heating_rate function by the new evaluate function in all plugins that still use it. Unfortunately it did not fulfill its purpose, I guess because of the following bug in gcc 5.1: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=65974. It seems like we have to live with deprecation warnings, for everybody using gcc 5.1 and 5.2 for now. Still the patch itself is valid and improves the code, so we should merge it anyway.
> Fix heating deprecation warnings

- doc/manual/manual.tex
It turns out that using 23255...23255 is apparently one of the cardinal sins in latex
because it is a plain TeX command that can not be overridden by the latex styles.
Thus, avoid it in the one place where we use it.
> Avoid 23255...23255 in latex.

- source/initial_conditions/S40RTS_perturbation.cc
- source/initial_conditions/SAVANI_perturbation.cc
It only makes sense in 3d, but produces compiler warnings when compiled in 2d.
> Disable the S40RTS model for 2d.

- doc/manual/manual.tex
I really only wanted to change the one line where unicode chars appear (line 5997) but then my emacs decided to also change all tabs to spaces -- well, that's probably not terrible either.
> Avoid the use of unicode characters in the manual.

- doc/modules/changes.h
- include/aspect/mesh_refinement/particle_density.h
- source/mesh_refinement/particle_density.cc
- tests/particle_load_balancing_refinement.prm
- tests/particle_load_balancing_refinement/screen-output
- tests/particle_load_balancing_refinement/statistics
The entry in changes.h says it all. This PR adds a mesh refinement plugin that refines cells based on the density of tracers in that cell. It can be used to balance the load between cells and particles more effectively, as long as one is fine with synchronizing particle density and cell size.
> Add tracer refinement criterion

- doc/modules/changes.h
- include/aspect/simulator.h
- source/simulator/freesurface.cc
- tests/free_surface_tangential_mesh_velocity.prm
- tests/free_surface_tangential_mesh_velocity/screen-output
- tests/free_surface_tangential_mesh_velocity/statistics
I think this supersedes #642. I have worked a bit more with Sascha these days and this solution seems to fit our needs best (@anne-glerum you solution was already working for him, but only for box models as we discussed in #642). This PR introduces a new parameter in the Free Surface section called `Additional tangential mesh velocity boundary indicators`, which can be set by the user to allow the mesh to change tangential to the boundary at boundaries where tractions or velocities are prescribed. If anyone has a nicer name for the parameter let me know, I am not quite happy with it.
> Allow tangential mesh movement at boundaries were velocity is prescribed orthogonal

- doc/modules/changes.h
- source/geometry_model/box.cc
- source/geometry_model/two_merged_boxes.cc
This addresses #702 and unifies the depth() function boundary handling of the box geometries with the other geometry models that also do a truncation instead of throwing an exception. 
I do not think this will change any behaviour, because previously the cases that are now truncated were throwing exceptions, so there are no models that now behave differently.
> Allow free surfaces with positive topography in the box geometry model

- source/material_model/interface.cc
Rather than initialize vectors to zero size and then resize them
in the constructor body, initialize them to the right size right away.
> Initialize member variables right away.

- source/material_model/interface.cc
They were initialized in an order different from their declaration,
leading to warnings. Fix this.
> Reorder initialization of variables.

- include/aspect/simulator.h
- source/simulator/assembly.cc
@rrgrove6's patch in #425 move computations from local_assemble_advection_system()
to the calling function, making a number of function arguments obsolete. The
compiler then warns about these.
This patch removes them from the interface. It also simplifies the code
and calls a fair bit.
> Remove unused function arguments.

- source/simulator/assembly.cc
- tests/cell_reference/screen-output
We computed the material model inputs and outputs in the `get_artificial_viscosity()` function in the `assembly.cc`, but they weren't used anywhere.
> remove some lines that are not needed anywhere

- include/aspect/simulator.h
- source/simulator/assembly.cc
- source/simulator/core.cc
This is my second try, following #695.
The idea here is to introduce a structure that contains signals that point to functions that do the actual assembly loop. The setup of scratch objects etc continues to happen at an outer level, but on every cell we then simply call each slot in the signal, and thereby add up terms as appropriate for an equation or approximation.
The current patch is simply a strawman that just does this for the Stokes preconditioner and assembly. It seems to pass the first few tests on my machine, but that's not the point right now. 
Points to discuss:
* Right now, the assembler functions are free functions in a namespace. This makes it relatively easy to add other, similar implementations. It has the disadvantage that the functions do not readily have access to …
> [WIP] Modularize assembly

- include/aspect/simulator.h
- source/simulator/assembly.cc
This PR adds a bit of documentation in the first commit, relative to the splitting of assemblers developed in #718.
The second patch splits the assembly of Stokes domain and boundary terms into separate signals. This allows the implementation of individual boundary terms to only deal with one face at a time, rather than having to loop over all faces of a cell. I do this for two reasons:
* If we have multiple slots to this signal, then they will all work on the first face, then all on the second face, rather than interleaving their work. This should make data locality better.
* More importantly, if we these face assemblers need an initialized `MaterialModelOutputs` for each face, we want to reuse this for *all* assemblers on one face before moving to the next face, rather than have each …
> Add documentation & split domain and boundary integration

- include/aspect/simulator.h
- source/simulator/assembly.cc
This isn't used right now, but it will enable us to define things only
some of the assemblers require.
This patch is on top of what's already proposed in #722. The only commit relevant for now is the last one (the first two are duplicated from #722).
@jdannberg -- would something like this allow you to determine in `local_assemble_stokes_system` that one needs to initialize face material outputs? I don't currently do that because I don't know what fields you need in the scratch data.
> Add assembler properties

- source/simulator/freesurface.cc
Aspect doesn't build in Xcode 7.0.1 (Clang-700.0.72) using deal 8.3.0 MacOSX package unless this include is added.
>  Include vector_tools.templates.h for deal.II 8.3.0 support

- include/aspect/adiabatic_conditions/initial_profile.h
- include/aspect/gravity_model/radial.h
- include/aspect/initial_conditions/adiabatic.h
- include/aspect/initial_conditions/box.h
- include/aspect/initial_conditions/harmonic_perturbation.h
- include/aspect/initial_conditions/solidus.h
- include/aspect/initial_conditions/spherical_shell.h
- include/aspect/postprocess/topography.h
- include/aspect/termination_criteria/end_step.h
- include/aspect/termination_criteria/end_time.h
- include/aspect/termination_criteria/steady_rms_velocity.h
- include/aspect/termination_criteria/user_request.h
No plugin should ever need to #include <simulator.h>. Rather, all of them should
be content with just knowing about the <simulator_access.h> class. Replacing
these includes therefore increases modularity, and decreases compile
time. It also makes it a lot simpler to make changes to simulator.h
itself, because it vastly reduces the number of files affected by such
changes.
> Replace #include to <simulator.h> with <simulator_access.h>.

- include/aspect/assembly.h
- include/aspect/simulator.h
- source/simulator/assembly.cc
- source/simulator/core.cc
This will make adding functionality later much simpler because it allows me to make changes in this file without touching the global `simulator.h`.
There is really no new functionality in this patch, just separating pieces from different files and refactoring.
> Separate everything assembly related into a .h file of its own.

- source/simulator/assembly.cc
- source/simulator/core.cc
This way, whoever comes along can already subscribe their own assembler
contribution. This way it doesn't all have to happen in set_assemblers().
> Create the assembler object early.

- include/aspect/assembly.h
- source/simulator/assembly.cc
This allows the use of these classes in other files than just assembly.cc.
In reference to #733 .
> Move Scratch/CopyData class declarations into assembly.h

- include/aspect/simulator.h
- source/simulator/assembly.cc
A unique_ptr (or boost::scoped_ptr, which is used if we don't have
c++11) can only be placed into std::vector if we have c++11. Instead,
use a shared_ptr for now.
> Assembler unique ptr

- include/aspect/simulator.h
- source/simulator/assembly.cc
- source/simulator/freesurface.cc
This PR simplifies code in that it lets the `FreeSurfaceHandler` class add its assembler itself, rather than putting this into `Simulator::set_assemblers()`. It also removes, in the process, a helper function.
> More assembly work

- source/simulator/helper_functions.cc
I stumbled over the `compute_time_step` function while investigating #293. The logic at the end did throw a floating point exception when `max_global_speed_over_meshsize == 0 && min_conduction_timestep < std::numeric_limits<double>::max()`. Additionally filling the material model inputs was inefficient and creating FEValues did not follow our usual line break convention. This PR should fix these minor things, it does not fix #293 however.
> Improve timestep logic

- doc/modules/changes.h
- include/aspect/utilities.h
- source/postprocess/visualization.cc
- source/simulator/checkpoint_restart.cc
- source/simulator/parameters.cc
- source/utilities.cc
A set of patches that should work around some issues that occur, if `system()` (to do something on the command line) does not work for some reason. This is the case for compute nodes on IBM's BlueGene/Q architecture.
The inclusion of the different namespace in Utilities is only coarsely related. It would be nice, if I would not need to rename every `Utilities::something` function into `dealii::Utilities::something` just because I include the `aspect::Utilities` header file. Is this solution ok?
> Provide fallbacks for command line

- doc/modules/changes.h
- source/postprocess/visualization.cc
This improves output quality of the interpolated output mesh. So far the 'real' mesh cells followed the mapping, but the additional interpolated output cells used a Q1 mapping, which puzzled me a bit when looking at the output in detail. It is not affecting any solution, but this new way looks nicer and creates a more consistent mesh.
> Use mapping for output interpolation

- include/aspect/initial_conditions/solidus.h
- include/aspect/material_model/depth_dependent.h
- include/aspect/utilities.h
- include/aspect/velocity_boundary_conditions/gplates.h
- source/initial_conditions/S40RTS_perturbation.cc
- source/initial_conditions/SAVANI_perturbation.cc
- source/initial_conditions/solidus.cc
- source/material_model/depth_dependent.cc
- source/material_model/steinberger.cc
- source/particle/generator/ascii_file.cc
- source/utilities.cc
- source/velocity_boundary_conditions/gplates.cc
While working on #752 I noticed that there was an issue with the file input in ASPECT that I wanted to address since my last computing time proposal: We handle file output very carefully in terms of avoiding unnecessary IO accesses and slowdowns, but every file input is handled very simple and duplicated by letting every MPI process read a file from disk. While input files are usually smaller than output files they can still reach several MB size, and I even had some models with a one GB material table once. This way, even with small input data files, models with several hundreds to a thousand processes can generate as much input file traffic (with many accesses in very short time) as output traffic.
We should handle this more elegantly and with this PR, all file input operations are …
> Use MPI_Bcast for input data

- include/aspect/assembly.h
- include/aspect/material_model/interface.h
- include/aspect/simulator.h
- include/aspect/simulator_signals.h
- source/material_model/interface.cc
- source/simulator/assembly.cc
- source/simulator/core.cc
- tests/additional_outputs_02.cc
- tests/additional_outputs_02.prm
- tests/additional_outputs_02/screen-output
- tests/additional_outputs_03.cc
- tests/additional_outputs_03.prm
- tests/additional_outputs_03/screen-output
Allow averaging of ``AdditionalMaterialOutputs``. This is based on @jdannberg's work. This branch is based off of #751, which should be merged first.
> Material output averaging

- source/boundary_temperature/function.cc
- source/compositional_initial_conditions/function.cc
- source/gravity_model/function.cc
- source/heating_model/function.cc
- source/initial_conditions/adiabatic.cc
- source/initial_conditions/function.cc
- source/mesh_refinement/maximum_refinement_function.cc
- source/mesh_refinement/minimum_refinement_function.cc
- source/prescribed_stokes_solution/function.cc
- source/traction_boundary_conditions/function.cc
- source/velocity_boundary_conditions/function.cc
If we can't parse a function expression provided in the input file, the
previous error message simply said that there was an error but nothing
more. What was easy to miss was that there is actually more below, since
we re-throw the original error message. The improvement made here simply
points out that there is more about what caused the error below the first
error message. This now looks like this:
```
ERROR: FunctionParser failed to parse
'Compositional initial conditions.Function'
with expression
'1'
More information about the cause of the parse error 
is shown below.
----------------------------------------------------
Exception on processing: 
--------------------------------------------------------
An error occurred in line <76> of file …
```
> Improve an error message.

- source/simulator/assembly.cc
It doesn't make sense to initialize an array of indices with a NaN
double. In fact, it throws a floating point exception on my machine.
> fix FPE in vector construction

- source/simulator/assembly.cc
I forgot to add an explicit instantiation of local_assemble_advection_face_terms in #661. This fixes that.
> Add explicit instantiation of local_assemble_advection_face_terms().

- doc/modules/changes.h
- source/material_model/depth_dependent.cc
- source/material_model/simpler.cc
- tests/simpler_composition.prm
- tests/simpler_composition/screen-output
- tests/simpler_composition/statistics
The 'Simpler' material model used to throw floating point exceptions, because it did not set the reaction_terms to zero and therefore they were used uninitialized in the assembly. This PR fixes this behaviour.
> Make 'Simpler' material model work with compositions

- source/simulator/core.cc
I realized that this is not obvious after talking to Alberto Sartori.
> Explain how a statement works.

- source/utilities.cc
I repeatedly created data files that do not work with the current Ascii data plugin, and in its current form this does only create completely uninformative floating point exceptions. This PR at least improves the error message.
> Add a read check for the Ascii data plugin

- include/aspect/simulator.h
- include/aspect/simulator_signals.h
- source/particle/world.cc
- source/simulator/core.cc
- source/simulator/simulator_signals.cc
- tests/additional_outputs_02.cc
- tests/additional_outputs_02/screen-output
- tests/additional_outputs_03.cc
- tests/additional_outputs_03/screen-output
This patch moves the creation of the ``signals`` object closer to the top of the simulator and call the connector functions as soon as possible (instead of at the end of the initialization). In the future, this will allow us to fire new signals during introspection construction for example. Right now this doesn't do anything exciting.
- connect signals earlier in the program
- catch when you try to register after connector functions have already been called
- update tests
> Earlier signal creation

- include/aspect/material_model/interface.h
- include/aspect/velocity_boundary_conditions/ascii_data.h
- include/aspect/velocity_boundary_conditions/function.h
- include/aspect/velocity_boundary_conditions/gplates.h
- include/aspect/velocity_boundary_conditions/zero_velocity.h
- source/velocity_boundary_conditions/interface.cc
This PR silences a number of warnings (gcc 4.8.4) that have annoyed me in the last time, but I never found the time to actually fix them :smile:
> Silence overloaded-virtual and deprecation warnings

- doc/modules/changes.h
- include/aspect/postprocess/tracers.h
- source/postprocess/tracers.cc
- source/simulator/initial_conditions.cc
- tests/particle_initial_adaptive_refinement.prm
- tests/particle_initial_adaptive_refinement/screen-output
- tests/particle_initial_adaptive_refinement/statistics
The particle creation contained a bug with initial adaptive refinements that was never found because none of my testcases used the 'Initial adaptive refinement' setting. Later adaptive refinements did not produce this error. The bug is now fixed by only generating the particles in the first initial refinement cycle and only reinitializing the particle properties in following cycles (identical to what we do with the initial condition).
> Fix adaptive mesh particle bug

- source/postprocess/depth_average.cc
- tests/adiabatic_conditions/screen-output
- tests/adiabatic_initial_conditions/screen-output
- tests/adiabatic_initial_conditions_chunk/screen-output
- tests/adiabatic_initial_conditions_chunk_3d/screen-output
- tests/adiabatic_initial_conditions_constant/screen-output
- tests/adiabatic_initial_conditions_subadiabaticity/screen-output
- tests/depth_dependent_box_none_simple/screen-output
- tests/diffusion/screen-output
- tests/diffusion_dislocation_fixed_strain_rate/screen-output
- tests/maximum_refinement_function/screen-output
- tests/maximum_refinement_function_cartesian/screen-output
- tests/maximum_refinement_function_spherical/screen-output
- tests/minimum_refinement_function/screen-output
- tests/minimum_refinement_function_cartesian/screen-output
- tests/minimum_refinement_function_spherical/screen-output
- tests/morency_doin/screen-output
- tests/no_adiabatic_heating_03/screen-output
- tests/passive_comp/screen-output
- tests/petsc_refinement/screen-output
- tests/refine_vel/screen-output
- tests/simple_compressible/screen-output
- tests/simple_incompressible/screen-output
- tests/solidus_initial_conditions/screen-output
- tests/spherical_velocity_statistics/screen-output
- tests/steinberger_compressible/screen-output
- tests/steinberger_incompressible/screen-output
- tests/steinberger_viscosity/screen-output
- tests/steinberger_viscosity_adiabatic/screen-output
- tests/velocity_boundary_statistics/screen-output
Like #794: Almost all postprocessors write a colon at the end of the first part of their screen message. Depth average did not. Fix this.
> Make message uniform

- include/aspect/postprocess/depth_average.h
- source/postprocess/depth_average.cc
Specifically, update a wrong documentation string; and add an assertion.
This addresses two issues pointed out in the review for #799 at the source.
> Minor updates.

- include/aspect/boundary_composition/interface.h
- include/aspect/boundary_temperature/interface.h
The docs of these two deprecated functions point to the new names, but misspelled them.
> Adjust names in the document.

- source/particle/property/interface.cc
This is only allowed in C++11, whereas in C++98 the names of members of an enum
are only part of the *enclosing* namespace, but not members of the enum's namespace
itself.
> Do not classname-qualify members of enums.

- source/simulator/nullspace.cc
- source/simulator/simulator_access.cc
When an MPI rank has no cells and as such no DoFs, we are triggering two
problems:
- Assert in SimulatorAccess::get_fe()
- handling of nullspace constraints
There are still issues with deal 8.2.1, but this fixes parallel
computations with 8.3 or newer.
> fix bugs when MPI proc has no DoFs

- source/postprocess/visualization/particle_count.cc
No, I definitely do not want to copy all particles just to output their numbers, but that is what seems to be happening right here. Who wrote this code? Oh, it was me.
> Remove unintended copy of particles

- include/aspect/mesh_refinement/particle_density.h
- source/mesh_refinement/particle_density.cc
- tests/particle_load_balancing_refinement_02.prm
- tests/particle_load_balancing_refinement_02/screen-output
- tests/particle_load_balancing_refinement_02/statistics
The refinement criterion 'particle density' did not decrease when the cells were refined, which was not caught by the test, because it only refined once. The correct measure is the number of particles per cell (equivalent to: particle_density * cell_volume). The new test captures this behavior.
> Fix 'particle density' mesh refinement

- source/particle/world.cc
Tiny bugfix that prevents a few tracers from being duplicated when transferred during adaptive mesh refinement. GeometryInfo<dim>::is_inside_unit_cell apparently returns true for two children, if the position is very close to their boundary. Now the particle is only inserted into one of the children.
> Prevent a particle from being assigned to two children

- include/aspect/particle/world.h
I would like to use the result of this function in a postprocessor, and since it is a const function anyway, I think there is little harm in making it public.
> Make get_global_max_tracers_per_cell() public

- doc/modules/changes.h
- include/aspect/particle/world.h
- source/particle/world.cc
These additional lines of code improve the scaling for large number of cells and particles per subdomain, and can save up to 75 % of the total particle computation cost in a few cases. Realistic speed gains are around 10 %.
The sorting into new cells now first considers neighbors in the order of the distance between particle and the center of the face that connects the old cell with the neighbor.
> Speed up particle sorting.

- source/postprocess/point_values.cc
In optimized mode, we did not check that a point at which we want to evaluate
the solution was actually found. This led to a warning about an unused
variable 'point_found'. This could be addressed by doing a 'void' cast
of said variable, but the better solution appears to be to actually
perform the check also in optimized mode -- after all, the list of points
at which we want to evaluate the solution is read at run-time from the
input field.
> Avoid warning about potentially unused variable.

- doc/modules/changes.h
- include/aspect/mesh_refinement/interface.h
- include/aspect/mesh_refinement/maximum_refinement_function.h
- include/aspect/mesh_refinement/minimum_refinement_function.h
- source/mesh_refinement/interface.cc
- source/mesh_refinement/maximum_refinement_function.cc
- source/mesh_refinement/minimum_refinement_function.cc
- source/simulator/core.cc
- tests/minimum_refinement_function_time_dependent.prm
- tests/minimum_refinement_function_time_dependent/log.txt
- tests/minimum_refinement_function_time_dependent/screen-output
- tests/minimum_refinement_function_time_dependent/statistics
I'm using a case right now where I'd like the minimum and maximum refinement levels to change with time, which was apparently not previously supported.
> Enable time-dependent min/max refinement

- include/aspect/particle/world.h
- include/aspect/postprocess/tracers.h
- source/particle/world.cc
- source/postprocess/tracers.cc
- tests/particle_timing_information.prm
- tests/particle_timing_information/screen-output
Originally I just intended to add some more granular timing information to the particle code for benchmarking purposes. It turned out I need to shuffle some code from the tracer postprocessor to the particle world in order to also measure the time spent in writing the particle output. On the other hand I should have done this change a while ago already, it was never a good idea to let the postprocessor handle the creation of plugins and then hand over ownership to particle::World. Sorry for mingling these two things in one pull request. 
This patch should not change any functionality. The new `TimerOutput` introduces some MPI_Barriers in the particle code for benchmarking purposes, do you think this is relevant for performance?
Otherwise this is ready for a review.
> Add particle timing information. Move parameters to world.

- include/aspect/assembly.h
- include/aspect/simulator.h
- include/aspect/simulator_access.h
- source/simulator/assembly.cc
- source/simulator/simulator_access.cc
This moves the face advection terms of #661 in the same Assembler structure as the cell terms in #769.
All in the intention of #733 to allow extensions of the assembled equations.
This PR is at a pretty early stage (I want to see the test results), and there is a structural problem at the moment that I would like to discuss: 
The FaceQuadrature in the Scratch AdvectionSystem object is currently only initialized in `assemble_advection_system` if the current `advection_field` is discontinuous, because that is the only case we need it so far. However, we currently have only one signal `local_assemble_advection_system_on_boundary_face`, and I would like to use its number of connected slots to determine if the `face_finite_element_values` will be initialized and the signal is called. This …
> Restructure advection face assembly

- include/aspect/prescribed_stokes_solution/circle.h
- source/prescribed_stokes_solution/circle.cc
We do this for all other plugins, not because it's necessary, but by convention
and because it makes it possible to show all of these classes via doxygen. Do
this for the 'circle' plugin as well.
> Split the 'circle' plugin into .h and .cc files.

- doc/modules/changes.h
- include/aspect/compat.h
- source/initial_conditions/S40RTS_perturbation.cc
- source/initial_conditions/SAVANI_perturbation.cc
- source/initial_conditions/solidus.cc
- source/main.cc
- source/material_model/depth_dependent.cc
- source/material_model/steinberger.cc
- source/particle/generator/ascii_file.cc
- source/utilities.cc
- source/velocity_boundary_conditions/gplates.cc
We had many places where we replace ``$ASPECT_SOURCE_DIR`` in input
variables by the current source dir. Do this once at the beginning
instead. This patch allows us to use this variable in include statements inside tests.
Note that this patch will break the usage of ``$ASPECT_SOURCE_DIR`` within ``include``'d files, see #852.
> replace $ASPECT_SOURCE_DIR in central location

- include/aspect/velocity_boundary_conditions/gplates.h
- source/velocity_boundary_conditions/gplates.cc
While cleaning my local repository I found this branch that I thought merged long ago. Anyway, this will remove deprecation warnings for some compilers for the gplates plugin. It now uses the new boundary_velocity interface (all other plugins were updated long ago already).
> Update gplates plugin to use new interface

- benchmark/davies_et_al/case-2.3-plugin/VoT.cc
- cookbooks/free-surface-with-crust/plugin/simpler-with-crust.cc
This should close #777. I went through all the benchmarks and cookbooks, and they mostly use the `InterfaceCompatibility` base class, which does prevent this problem by setting the reaction terms to 0 in the default implementation.
> Minor bugfixes

- source/material_model/interface.cc
- tests/geometric_average_crash.prm
- tests/geometric_average_crash/screen-output
Computing the geometric average in 3d caused a floating point overflow
when averaging viscosity values.
fixes #871
> fix geometric averaging in 3d

- source/heating_model/interface.cc
- source/velocity_boundary_conditions/interface.cc
This was suggested in #785 and indeed removes some warnings for Intel compilers, thanks @tjhei.
The only remaining warning I get is: "icpc: command line warning #10006: ignoring unknown option '-fuse-ld=gold'". That is related to the deal.II build system I guess? I can open an issue there.
> [post-1.4] Silence warnings for other compilers

- source/simulator/assembly.cc
This is a hostile takeover of #717 as discussed there and fixes #711.
This avoids stepping on indices that may be used elsewhere.
> Avoid using the user_index when we can use active_cell_index instead.

- source/simulator/core.cc
Right now, the traction boundary conditions are initialized before we fill the map that contains the information which plugin is used for which boundary indicator. This means that during their initialization, traction boundary plugins do not know if they are used for a given model boundary. 
This pull request should fix this, and the implementation is now the same as for the velocity boundary conditions.
> fix the initialization of traction boundary conditions

- doc/modules/changes.h
- include/aspect/traction_boundary_conditions/function.h
- include/aspect/traction_boundary_conditions/interface.h
- include/aspect/traction_boundary_conditions/zero_traction.h
- source/simulator/assembly.cc
- source/traction_boundary_conditions/function.cc
- source/traction_boundary_conditions/interface.cc
- source/traction_boundary_conditions/zero_traction.cc
- source/velocity_boundary_conditions/interface.cc
Currently, the traction boundary conditions do not get the boundary indicator when they are called (but only the position and the normal). As different boundaries can have different boundary traction plugins, it is useful to also hand over the boundary indicator (just as we do for velocity boundary conditions). 
This pull request updates the interface of the traction boundary conditions.
> move traction boundary conditions to new interface

- benchmark/inclusion/adaptive.prm
- benchmark/inclusion/adaptive.prm.base
- benchmark/inclusion/global.prm.base
- benchmark/inclusion/inclusion.cc
- benchmark/inclusion/run.sh
- change output directories for global and adaptive
- include velocity and pressure dofs in error output line
- include option to turn on averaging
> update inclusion benchmark

- source/simulator/assembly.cc
I must have missed this when reviewing #883. This fixes compilation errors with deal.II-8.5.0-pre.
> Fix assembly for deal.II-8.5.0-pre

- include/aspect/global.h
- source/simulator/core.cc
- source/simulator/freesurface.cc
- source/simulator/solver.cc
[Block]CompressedSparsityPattern has been renamed to
[Block]DynamicSparsityPattern in deal.II before 8.4. Use the new name
throughout to avoid deprecation warnings.
Also avoid some other warnings:
- vector.add()
- warnings inside vector_tools.templates.h
- using the wrong petsc header files
> Avoid deprecated Linear Algebra stuff

- include/aspect/particle/generator/interface.h
- include/aspect/particle/generator/probability_density_function.h
- include/aspect/particle/generator/random_uniform.h
- source/particle/generator/random_uniform.cc
- source/particle/generator/uniform_box.cc
suppress warning:
```
In file included from
deal.II/installed-v8.4.1-clang/include/deal.II/bundled/boost/random.hpp:69:
In file included from
deal.II/installed-v8.4.1-clang/include/deal.II/bundled/boost/random/negative_binomial_distribution.hpp:21:
deal.II/installed-v8.4.1-clang/include/deal.II/bundled/boost/random/poisson_distribution.hpp:338:9:
warning: anonymous types declared in an anonymous union are an extension
[-Wnested-anon-types]
```
> wrap boost include with silencing macros

- doc/modules/changes.h
- tests/CMakeLists.txt
- tests/cmake/default.sh
- tests/cmake/run_test.sh
- tests/fail.prm
- tests/fail/screen-output
This pull request allows you to mark tests that you expect to fail by putting the string "EXPECT FAILURE" into the .prm.
> allow failing tests

- source/postprocess/heat_flux_statistics.cc
- source/postprocess/mass_flux_statistics.cc
- source/postprocess/velocity_boundary_statistics.cc
Initializing the vectors used for MPI function to the correct size to prevent crashes as described in #909. 
I checked most post-processors (basic statistics, boundary densities, boundary pressures, composition statistics, depth average, dynamic topography, heat flux statistics,  heating statistics, mass flux statistics, point values, pressure statistics, Stokes residual, temperature statistics, velocity boundary statistics, velocity statistics, viscous dissipation statistics,visualization) by running them. I but I didn't run command, spherical velocity statistics and topography (only checked out the code), because they where incompatible with the model I was testing it with and I assumed that spherical velocity statistics, topography are in the testing package anyway because they are …
> A fix to postprocessers which crash with deal.ii 8.5.0-pre.

- include/aspect/material_model/visco_plastic.h
this fixes
include/aspect/material_model/visco_plastic.h:162:20: warning: comma at end of enumerator list [-pedantic]
> fix compiler warning

- cookbooks/finite_strain/finite_strain.cc
- cookbooks/finite_strain/finite_strain.prm
- doc/manual/cookbooks/finite_strain/finite_strain.cc
This PR is analogous to the changes in #856 in that it changes the storage type for the finite strain from `Tensor<2,dim>` to `SymmetricTensor<2,dim>`. This requires 1 less compositional field in 2D and 3 less in 3D.
> Use SymmetricTensor for finite strain

- doc/manual/manual.tex
Following a recent discussion about this, it occurred to me that it would be useful to explicitly say that `\varepsilon` is an operator, not something that stands on its own.
> Explicitly explain what epsilon is and how it relates to strain/strain rate

- source/simulator/parameters.cc
- change typo "ths" to "the" in the description for the parameter 'Run postprocessors on initial refinement'
> fix spelling mistake in parameter description

- doc/manual/manual.tex
The references to cookbooks/composition-passive.prm in the manual were all cookbooks/composition**al**-passive.prm. This has been changed to the first to be consistent with the file system.
> Fix some typos in manual

- source/simulator/core.cc
- remove ambiguity from two 'Initialization' sections
- rename 'Initialization' that computes the initial temperature, compositional, and pressure fields to 'Setup initial conditions'
EDIT: 'Initial Conditions' -> 'Setup initial conditions'
> rename initialization compute-time section

- source/initial_conditions/S40RTS_perturbation.cc
- source/initial_conditions/SAVANI_perturbation.cc
- change 'vs' to "Vs" in S40RTS and SAVANI perturbation implementations
- see issue #976
> fix documentation spelling mistake

- doc/manual/manual.tex
- Includes instructions to ensure Xcode and command line tools are up-to-date.
- Adds lines to ensure the correct compilers are picked up.
- Includes instructions to generate and run an Aspect project in Xcode in both serial and parallel.
I'd appreciate your thoughts on what I've written.
There is also the matter of the link to Matsui's instructions (URL on line 2025) which are now out-of-date - should I remove the link altogether, or still provide it but caution that it is out-of-date?
> Update MacOSX install instructions.

- include/aspect/boundary_composition/interface.h
- include/aspect/boundary_temperature/interface.h
- source/boundary_composition/interface.cc
- source/boundary_temperature/interface.cc
- source/simulator/core.cc
Replaces them with `boundary_temperature` and `boundary_composition`, as brought in with #689 . Contributes towards #943
> Remove deprecated 'temperature' and 'composition'

- benchmark/burstedde/burstedde.cc
- benchmark/inclusion/inclusion.cc
- benchmark/inclusion/run.sh
- benchmark/solcx/solcx.cc
- benchmark/solkz/solkz.cc
- tests/burstedde.cc
- tests/inclusion_2.cc
- tests/melt_compressible_advection.cc
- tests/melt_material_4.cc
- tests/melt_transport_convergence_simple.cc
- tests/melt_transport_convergence_test.cc
- tests/prescribed_velocity_boundary.cc
- tests/sol_cx_mpi_2.cc
- tests/sol_cx_mpi_2.prm
- tests/sol_cx_mpi_2/screen-output
- tests/sol_cx_mpi_2/statistics
- tests/solcx.cc
- tests/solkz.cc
Fix issue #958.
Testing completed.
For solcx and solkx logs match for single processor, for MPI change in computed error is within epsilon.
For inclusion, script output matches for single processor, and to within a reasonable epsilon for MPI.
> Parallel benchmarks

- source/simulator/helper_functions.cc
- tests/discontinuous_composition_bound_preserving_limiter_3d.prm
- tests/discontinuous_composition_bound_preserving_limiter_3d/screen-output
- tests/discontinuous_composition_bound_preserving_limiter_3d/statistics
The DG bound preserving limiter now can be applied to both 2d and 3D cases, and the new version has the same 2D outputs of the test case used in the early version. For 3D case, only run a simple short time run test example, and it works.
> Update on the DG bound preserving limiter for 3D

- doc/manual/manual.bib
- doc/manual/manual.tex
Instead mention it in a historical context.
Fixes #925.
> Remove references to the IMPES algorithm used earlier.

- include/aspect/free_surface.h
- source/simulator/checkpoint_restart.cc
- source/simulator/core.cc
- source/simulator/free_surface.cc
This, along with #965, addresses #369 and #1006.
> No longer necessary to detach manifolds since we use MappingQ1Eulerian.

- include/aspect/initial_conditions/interface.h
- source/initial_conditions/interface.cc
When for example reading in temperature perturbations from tomography (e.g. with the `ascii_data` plugin), the perturbations have to be added to a reference profile (e.g. from the `adiabatic` plugin). With the base model functions we can easily do this without copying code.
> Add base model functions to initial conditions

- doc/modules/changes.h
- include/aspect/utilities.h
- source/initial_conditions/S40RTS_perturbation.cc
- source/initial_conditions/SAVANI_perturbation.cc
- source/initial_conditions/harmonic_perturbation.cc
- source/initial_conditions/solidus.cc
- source/utilities.cc
There were several places in the code that call boost's spherical harmonics functions, with duplicated effort and potential for normalization errors. Furthermore, there will soon be more plugins that require spherical harmonics.
This provides a function in the `Utilities` namespace that calculates real spherical harmonics, according the the fully normalized convention (such as that described  in Dahlen and Tromp).
@Shangxin-Liu, @jaustermann  , could you take a glance at this to make sure that I have not broken the fix in #966?
> Spherical harmonics helper

- source/simulator/assembly.cc
- tests/discontinuous_temperature_spherical_shell_3d.prm
- tests/discontinuous_temperature_spherical_shell_3d/screen-output
Replace face->measure() in dG face assembly functions with a new function dg_approximaion_to_face_measure(face), which has 2d and 3d implementations. This fudges an issue where, in 3d, faces can be non-planar, and deal.II doesn't implement a measure for such non-planar faces. Since the only important feature of the measure here is that it scales correctly, this may be sufficient.
For reference, these come from 
https://www.dealii.org/developer/doxygen/deal.II/tria__accessor_8cc_source.html#l00900 (2d) and https://www.dealii.org/developer/doxygen/deal.II/tria__accessor_8cc_source.html#l00974 (3d) (only using the part for planar faces)
What do you guys think?
- is this a sufficient calculation, given we only want the scaling to be right? We don't make any use of the Jacobian, for example, …
> dG face measure for nonplanar faces

- doc/manual/manual.tex
I moved the parameter section to the end of the manual but kept the overview subsection in the main text. I moved that into section 4 - Running ASPECT. This addresses issue #940.
> Move parameter section to the end of the manual

- doc/manual/manual.tex
- make fit on one page again
- move maintainers up to save space
- arrange contributors at left boundary
> fix title layout of manual

- benchmark/inclusion/run.sh
- add harmonic averaging to the current list of averaging schemes (none, arithmetic, geometric) in the inclusion benchmark
- compared to other averaging schemes, harmonic averaging seems to reduce both velocity and pressure L2 errors
- https://docs.google.com/spreadsheets/d/1GYPWl4UOe-Jc5AkVqDX6PDQmL73YU-0S9rwBi7S-Ce0/edit?usp=sharing
> add harmonic averaging to inclusion benchmark

- source/boundary_composition/box.cc
- source/boundary_temperature/box.cc
Update 'box' descriptions to clarify that unselected sides default to zero flux, not zero Dirichlet.
Addresses #1033
> Update 'box' descriptions

- source/material_model/averaging.cc
- source/material_model/interface.cc
Apply averaging to thermal conductivities and reaction terms. Also correct a couple of typos.
Addresses #698.
The reaction terms are tricky as they have quadrature points as their first argument, meaning it's impossible to output the average() function to, say, out.reaction_terms[q][0] or out.reaction_terms[q][1] for all q quadrature points.
If there's a better implementation please let me know!
> Average conductivities and reaction terms.

- source/utilities.cc
- fix a bug where processor 0 throws an exception and the other processor(s) remain stuck in a broadcast state
- make processor 0 broadcast the error and then throw an exception
- make the other processor(s) receive the error and throw an exception
* if merged, resolves issue #984
> fix hanging processes when running in parallel

- source/postprocess/heat_flux_map.cc
As requested by @gassmoeller. Thanks for pointing this out to me!
> Fix warning for heat_flux_map postprocessor

- include/aspect/simulator_signals.h
- source/simulator/core.cc
Adds a signal called after setting the initial state.
I am currently looking at moving the initialize_tracers logic into a connection to this signal.
> Add post_set_initial_state signal

- include/aspect/particle/world.h
- source/particle/world.cc
- source/simulator/core.cc
- source/simulator/initial_conditions.cc
Depends on pull request #1079.
Removes postprocessors scanning logic from initial conditions to instead use post_set_initial_state signal
> Particle init signal

- source/simulator/parameters.cc
#989 Clarify that alpha is used for two different quantities. Disambiguation in parameter.cc ; add text clarifying that alpha (entropy viscosity stabilization) is not alpha (thermal expansion coefficient)
> Aspect alpha1

- doc/manual/manual.tex
- we can not cite the manual 1.5.0 because it is not released yet and
might never be (if the next one is 2.0.0)
- fix capitalization
note: this is only an intermediate fix
> fix citation info

- include/aspect/utilities.h
- tests/ascii_boundary_member.cc
- tests/ascii_boundary_member.prm
- tests/ascii_boundary_member/screen-output
- tests/ascii_boundary_member/statistics
This PR closes #857 and is useful for user plugins that want to keep around an object of type AsciiDataBoundary for lookup purposes.
> Allow using AsciiDataBoundary as member variable

- source/simulator/core.cc
- source/simulator/parameters.cc
- source/simulator/solver.cc
Currently  the function " apply_limiter_to_dg_solutions "  is implemented inside the core.cc, and only for the nonlinear solver IMPES. In order to be applied to other nonlinear solver, it's better to move it inside the solver.cc
> Move apply_limiter_to_dg_solutions to solver.cc

- source/utilities.cc
John Rudge reported to me that compiling with icc and mpich2 causes a SEEK_SET issue (I have seen similar issues with Trilinos, but not with ASPECT previously). The bug is documented here:
https://wiki.mpich.org/mpich/index.php/Frequently_Asked_Questions#Q:_I_get_compile_errors_saying_.22SEEK_SET_is_.23defined_but_must_not_be_for_the_C.2B.2B_binding_of_MPI.22.
I have not reproduced this myself, but apparently moving the `boost` include further down fixes the issue.
> Moving this include to avoid MPICH error.

- doc/modules/changes.h
- include/aspect/postprocess/matrix_statistics.h
- include/aspect/simulator_access.h
- source/postprocess/matrix_statistics.cc
- source/simulator/simulator_access.cc
- tests/matrix_nonzeros.prm
- tests/matrix_nonzeros/screen-output
Addresses #1053. Outputs to screen. To help with what this looks like:
```
Number of active cells: 64 (on 4 levels)
Number of degrees of freedom: 1526 (578+81+289+289+289)
*** Timestep 15:  t=0.9375 seconds
Solving temperature system... 10 iterations.
Solving C_1 system ... 10 iterations.
Solving C_2 system ... 9 iterations.
Rebuilding Stokes preconditioner...
Solving Stokes system... 8+0 iterations.
Postprocessing:
Temperature min/avg/max:               0 K, 0.4917 K, 1 K
Compositions min/max/mass:             -0.001546/1.056/0.4167 // -0.001105/0.9944/0.4581
System matrix memory consumption (MB): 0.440365
Total system matrix memory consumption: 0.440365 MB.
Total system matrix nnz: 33749
system matrix nnz by block: 
14842        3116           0           0           0
3116           0 …
```
> Matrix memory and n_nonzeros postprocessor.

- source/simulator/assembly.cc
> Replace call to this->get_timestep() with local variable time_step.

- tests/resume_free_surface.cc
#1110 accidentally merged a file that is not properly indented. Fix this here.
This fixes #1117.
I think that something must have been wrong with the tester when we merged #1110
because it both missed the fact that the indentation is wrong, as well as the
fact that the test seems to fail since then on the tester. Nothing we can do about
this right now other than address one issue at a time.
> Fix indentation of test file.

- include/aspect/postprocess/dynamic_topography.h
- include/aspect/postprocess/visualization/dynamic_topography.h
- source/postprocess/dynamic_topography.cc
- source/postprocess/visualization/dynamic_topography.cc
Sometimes we want to compute dynamic topography underneath ocean or other surface geological body. This needs the density contrast throughout the top boundary instead of only density value of the top cell. I set the default value of outside density to zero.
> Allow dynamic topography calculation from surface density contrast

- CONTRIBUTING.md
A link to the contents of this file (in markdown format) is automatically shown when trying to open a github issue. The file here is an adaptation of the one already displayed by deal.II at https://github.com/dealii/dealii/blob/master/CONTRIBUTING.md .
> Add a file CONTRIBUTING.md.

- include/aspect/introspection.h
- include/aspect/simulator.h
- source/simulator/assembly.cc
- source/simulator/helper_functions.cc
- source/simulator/introspection.cc
Whenever we need to use the degree of polynomial of AdvectionField, we have to verify the advection field name first. This patch is the enhancement of current implementation.
> Introduce AdvectionField::degrees using introspection.degrees.field_name

- source/simulator/core.cc
Relies on https://github.com/dealii/dealii/pull/2846 to reduce the memory consumption for dG quite dramatically when in parallel. I'm submitting this now to check that it at least builds (it does on my system), if someone would oblige?
This doesn't really merit a WIP tag as it's (hopefully) working, but no point merging before https://github.com/dealii/dealii/pull/2846 is merged.
> Fix make_flux_sparsity_pattern() to use internal and flux masks in parallel

- doc/modules/changes.h
- include/aspect/geometry_model/initial_topography_model/prm_polygon.h
- include/aspect/utilities.h
- source/geometry_model/initial_topography_model/prm_polygon.cc
- source/utilities.cc
- tests/prm_polygon_in_out.cc
- tests/prm_polygon_in_out.prm
- tests/prm_polygon_in_out/screen-output
This adds an initial topography plugin which defines the initial topography by defining 2d polygons on the surface and setting it to the desired elevation. After this I will update the ellipsoidal chunk and make a test out of this. Or should I do this within this pull request?
> Initial topography plugin prm polygon

- doc/manual/manual.tex
For a variety of reasons, it is recommended to use the T1 encoding of latex fonts. To
make this work with pdflatex, one then also has to load the appropriate font family,
which today is the Latin Modern (lmodern) family.
For context with the T1 encoding, see 
http://tex.stackexchange.com/questions/664/why-should-i-use-usepackaget1fontenc
For context with the lmodern package, see
http://tex.stackexchange.com/questions/172079/t1-encoding-causing-bad-pdf-quality
> Use T1 encoding for latex fonts; also use lmodern package.

- source/postprocess/matrix_statistics.cc
- tests/matrix_nonzeros/screen-output
Specifically, print number of nonzeros (which are often large) with a
separator between thousands, millions, etc.
This is a follow up to @spco's #1105.
> Better format matrix nonzero statistics.

- include/aspect/utilities.h
- source/postprocess/matrix_statistics.cc
- source/simulator/core.cc
Add `struct` in `Utilities` to enable outputting numbers with comma as thousands separator.
See https://github.com/geodynamics/aspect/pull/1138#issuecomment-236851007 for previous discussion. This fixes the issue where `std::locale("")`, dependent on platform, may not give comma-separated thousands.
> Thousands separator

- cmake/AspectConfig.cmake.in
- include/aspect/utilities.h
- source/utilities.cc
- tests/plugin.cc
- tests/plugin/screen-output
Do not inline expand_ASPECT_SOURCE_DIR() so it also works in plugins.
Extend documentation.
Fixes:
```
~/aspect/include/aspect/utilities.h:341:43: error:
use of undeclared identifier 'ASPECT_SOURCE_DIR'
```
when compiling plugins.
> move expand_ASPECT_SOURCE_DIR() into .cc

- source/simulator/free_surface.cc
A recent deal.II patch re-ordered the arguments and deprecated the version we are
currently using. Switch this to the modern version of the constructor.
> Use the modern version of the MappingQ1Eulerian constructor.

- include/aspect/geometry_model/chunk.h
- source/geometry_model/chunk.cc
- tests/chunk_cross_hemisphere.prm
- tests/chunk_cross_hemisphere/screen-output
- tests/chunk_cross_hemisphere/statistics
When the longitude of the chunk geometry crosses 180 degrees, 
the model will crash because of the negative longitudes returned in the
pull_back function for all points between 180 and 360 degrees.
It is not sufficient to add 360 degrees to all negative longitudes,
because this will still cause a crash when the geometry runs from, 
for example, -10 to 220 degrees longitude. Returned points will
then run from 350 to 220 degrees, while angles should be strictly
increasing.
> Prevent crash when chunk domain crosses 180 hemisphere

- tests/cmake/diff_test.sh
When running tests, if Numdiff is used only the differing values and their position in the lines in question are shown in the generated diff files. This results in having to either visually do the comparison, use another diff tool or redoing the diff using "numdiff -V" in order to obtain the context of the variations between the two. The change made is to use "numdiff -V" when generating the DIFF_OUTPUT intended to become *.diff or *.diff.failed in order to also include the originating lines when printing the diff.
Is not making use of this flag an intended design decision, a compatibility limitation, or was the capability overlooked?
> Include line diff in numdiff output

- include/aspect/geometry_model/box.h
- include/aspect/geometry_model/two_merged_boxes.h
As suggested to me when discussing #1044. This way we don't need a conditional statement for both Box and TwoMergedBoxes, for example if we want to check whether a plugin can be used for a specific geometry, or when logic is the same for Box and TwoMergedBoxes, we can combine it.
> Derive two_merged_boxes from box

- source/simulator/initial_conditions.cc
- tests/normalize_initial_composition.prm
- tests/normalize_initial_composition/screen-output
Addresses issue #1145. 
The unification on the standard of the n_compos+1 loop is due to wanting to reduce logic duplication.
This pull request also adds a test for the composition normalization due to no existing test using said feature.
> Remove code duplication in initialization of temperature and composition

- include/aspect/particle/world.h
- include/aspect/simulator_signals.h
- source/particle/world.cc
- source/postprocess/tracers.cc
- source/simulator/checkpoint_restart.cc
Previously the particle serialization was not very scalable, because the data was serialized in the usual way for postprocessors. Every process had to send its data to process 0, which then wrote the data  into an output stream,  which was saved to disk. This is impractical or even impossible for large application models. The new implementation utilizes the same functionality that we use for remeshing, i.e. the particle data is attached to the cells of the triangulation and stored together with the mesh. In essence this is similar to a SolutionTransfer object for particle data. The drawback is that every cell has to store the same amount of data (p4est limitation), therefore we now need significantly more disk space. An example application with around 20 million particles now need 4 GB …
> Improve particle serialization scalability

- doc/modules/changes.h
- include/aspect/particle/particle.h
- include/aspect/particle/world.h
- source/particle/generator/interface.cc
- source/particle/particle.cc
- source/particle/property/interface.cc
- source/particle/world.cc
Particles now also store their location in the
coordinate system of their current cell. This decreases the
number of times this location has to be computed by inverting
the mapping for the current cell, which is expensive.
On average this change will save 40-50% of the overall
particle computing time, while increasing the particle
memory footprint (which is usually small compared to the
system matrix).
The new algorithm relies on the fact that the reference location is set before the particles are advected. All implemented particle generators do that, but it is possible to use the old constructor to construct a particle without setting this location (e.g. in a user-written generator). What should I do about the old constructor? Remove? Deprecate? Add a sentence to the documentation that …
> Speedup particle sorting

- source/postprocess/point_values.cc
To debug a problem I was having. Helps to know which point was the problem.
Related: the problem I was debugging was that two processors claimed one point. The point was on a boundary, but so were many other points which didn't throw this exception. Is there an easy way to deal with that?
> [WIP] Improved point_values exception error message

- source/postprocess/point_values.cc
One possible solution to problem discussed in #1169 -- simply averages the values reported by each processor who claims to own a point. Prints a warning, but does not throw an exception. Still throws an exception in cases where points lie outside of the domain.
> Average 'point values' in cases where multiple processors' domains overlap.

- source/simulator/helper_functions.cc
- source/simulator/melt.cc
When go though the advection solver part,  I found several places can be improved by using current introspection properties for advection field.
Besides above, I also made one change on assembly.cc . For DG approach, the current Dirichlet boundary condition seems only be weakly imposed on inflow boundary condition no matter the filed is temperature field or compositional filed, but I think we don't have to check this for the temperature filed. So I'll just wait for other opinions.
> several changes using introspection advection field,  degree and component index

- source/particle/world.cc
More optimizations based on profiling example models with particles. It turns out that creating FEValues objects for every cell with particle positions as quadrature points is expensive (who would have thought :smile:), but since the quadrature is different for every cell we can not use the approach of the matrix assembly and reuse the FEValues object for every cell. Instead we can do the evaluation of the velocity manually, and save between 75% (2D box models) and 25% (3D shell models) of the total particle advection time. In general the cheaper the inversion of the mapping the larger the (relative) saving of advection time.
I am looking for a similar approach for the local_update_particles, but there I not only need the velocity but possibly more variables depending on the particle …
> Not longer construct FEValues in local_advect_particles

- source/postprocess/visualization.cc
- tests/parallel_output_group_1/solution/solution-00000.0000.vtu
- tests/parallel_output_group_1/solution/solution-00001.0000.vtu
- tests/parallel_output_group_2/solution/solution-00000.0000.vtu
- tests/parallel_output_group_2/solution/solution-00000.0001.vtu
- tests/parallel_output_group_2/solution/solution-00001.0000.vtu
- tests/parallel_output_group_2/solution/solution-00001.0001.vtu
This achieves what #1186 was supposed to do without relying on new deal.II features. Currently we only write the vtkflags 'time' and 'cycle' into the .vtk files if 'Number of grouped files' is set to 0, although we should do it in every case.
> Always pass vtk flags time into the output

- doc/modules/changes.h
- source/postprocess/visualization.cc
See dealii/dealii#3012 for a discussion of the issue (this PR should only be merged after that one). This adds time information to the .visit files.
> Add time information to .visit files

- include/aspect/particle/world.h
- source/particle/world.cc
This makes use of dealii/dealii#2981 and ships the cellid and reference location of a particle with it when sending it to a different process. This makes the code cleaner (when we can remove the old code path for deal.II 8.4) and saves a bit of time (only a few percent of the overall particle time, depending on how many particles are sent around). I have tested the code both for deal.II 8.4 and 8.5.0.pre. 
The only thing I am not quite happy with is the frequent casting of pointers and comparing them to integers in the `send_recv_particles` function, but since the length of a CellId is not constant there is no way around it (except padding each data package with zeroes, which I would not like).
> Send CellId during particle mpi transfer

- doc/modules/changes.h
- include/aspect/particle/property/initial_composition.h
- include/aspect/particle/property/integrated_strain.h
- include/aspect/particle/property/interface.h
- include/aspect/particle/property/pT_path.h
- include/aspect/particle/property/position.h
- include/aspect/particle/property/velocity.h
- source/particle/property/integrated_strain.cc
- source/particle/property/interface.cc
- source/particle/property/pT_path.cc
- source/particle/property/velocity.cc
- source/particle/world.cc
This is analogous to #1185 and should speed up particle property update significantly (except for the integrated strain property that needs the gradients of the solution). 
I have one backwards-compatibility issue though: I would like all particle properties by default declare the smallest possible amount of update_flags to prevent wasting time, but that means user-written particle property plugins might suddenly no longer get the solution values / gradients they need. But defining all update_flags by default and letting plugins declare less seems strange too (every user-written plugins will be slow, unless they figure out how to request less updates). Is there anything we can do about that?
> Component-wise value calculation

- doc/modules/changes.h
- source/particle/interpolator/cell_average.cc
- tests/particle_interpolator_empty_cells.prm
- tests/particle_interpolator_empty_cells/screen-output
- tests/particle_interpolator_empty_cells/statistics
This makes the particle interpolator handle cells without particles more robustly. Previously it contained an Assertion that prevented such cases, but with a statistical particle distribution it is very easy to refine a cell that contains a reasonable number of particle (10-20 in 2D) and still end up with children that are empty. In these cases it is just reasonable to interpolate from neighboring cells (essentially the same interpolation that is also happening with the solution during refinement).
@jperryhouts: This PR should solve your problem, at least it does for the parameter file you send me. I changed the file a bit and attached it as a test, I hope that is fine with you (since it does not seem to contain any specific things about your model).
> Make particle interpolator handle empty cells

- cmake/fpe_check.cmake
We accidentally save/restore a wrong value for include dirs in the FPE check. Both vars are empty on my machines, but I expect this could break the build or disable the FPE check if they are not.
> Fix typo in FPE check cmake path

- include/aspect/particle/output/ascii.h
- include/aspect/particle/output/hdf5.h
- include/aspect/particle/output/interface.h
- include/aspect/particle/output/vtu.h
- include/aspect/particle/property/interface.h
- source/particle/output/ascii.cc
- source/particle/output/hdf5.cc
- source/particle/output/vtu.cc
- source/particle/property/interface.cc
- source/simulator/initial_conditions.cc
This resolves the same issue as #1200, but it reorganizes the particle property information in a more accessible way. There is now a class `ParticlePropertyInformation` that is essentially equivalent to the `Introspection` class for the finite-element part of the code.
I would be happy about comments and suggestions for improvements. This also somewhat changes the interface to retrieve information about the particles. I am not sure if this affects the models of @jperryhouts, @naliboff or @hlokavarapu, if so let me know and we can find a way around it.
> Improve particle property information.

- include/aspect/assembly.h
- source/simulator/assembly.cc
- source/simulator/melt.cc
Something I realized when reviewing #1210. There is really only one case when we need the hessians in the advection system assembly: When calculating the advection system residual for the artificial viscosity of the temperature equation. In all other cases we either treat the diffusion implicitly (matrix assembly for temperature equation), or there is no diffusion at all (compositional fields). This change can save significant time in the assembly for curved geometries (up to 50% for the composition system for 3D spherical shells).
As a side effect this PR makes the constructor of `Scratch::AdvectionSystem` more similar to `Scratch::StokesSystem`.
> Only compute hessians in assembly if necessary

- include/aspect/simulator.h
- source/simulator/core.cc
- source/simulator/helper_functions.cc
Another consequence of #1210. When reviewing that pull request, I again realized how atrociously complicated our main loop has become over time. This is an effort to simplify things to let new users (and me) understand how this loop works. The improvement is especially obvious in the 'split' code view of Github. I moved all complicated conditions and commands that take several lines into separate helper functions. I am open for name suggestions for these functions, I feel like `time_for_...` might be misleading, but have not found a better name yet.
This PR should wait for #1210 to be merged, and I will take another look at it after that.
> Simplify main loop

- source/simulator/helper_functions.cc
There is a comment that this variable may be used in the future. But if
we want to do this, we can always get it back from the archive. In the
meantime, removing it avoids a compiler warning about an unused variable.
> Remove an unused local variable.

- tests/CMakeLists.txt
> Use alternative form of cmake command for cmake < 2.8.12.

- source/particle/world.cc
Silence the warning of the comparison between different integer format in the line 866 when compiling ASPECT.
> Silence the comparison warning between int and unsigned int

- include/aspect/particle/world.h
- source/particle/interpolator/cell_average.cc
- source/particle/world.cc
- tests/particle_interpolator_from_ghost_cells.prm
- tests/particle_interpolator_from_ghost_cells/screen-output
- tests/particle_interpolator_from_ghost_cells/statistics
A first stab at the problem raised by @egpuckett that many algorithms projecting particle properties onto the mesh want to use particles from neighboring cells, but they might not be available in our code, because they might be owned by a different processor. 
After discussion with @bangerth I tried to keep the ghost particles as separated from the normal particles as possible to avoid the problem of one process changing particle properties that it does not own. Still the access to ghost particles in the interpolator feels somewhat clumsy at the moment (having to ask for the postprocessor once per cell just does not feel right), but other options would involve changing the interface, which would be incompatible, or handing over a merged version of `particles` and `ghost_particles`, which …
> Keep ghost particles around

- CMakeLists.txt
The reporting of ASPECT_USE_SHARED_LIBS and ASPECT_HAVE_LINK_H in
detailed.log were broken, because we never created these variables. The
change here also allows the user to toggle these two settings to OFF
even if detection succeeded.
> cmake: use and report variables for dynamic plugins loading

- tests/particle_interpolator_from_ghost_cells/statistics
The test was created on a branch that branched off another patch that changed the
output in the 'statistics' file, and so the continuous integration machine did not
catch the issue. This fixes the statistics output to conform to the current standard.
> Fix test output.

- source/simulator/initial_conditions.cc
Fixed compilation errors  
aspect/source/simulator/initial_conditions.cc:99: error: ‘ref’ is not a member of ‘std’"
aspect/source/simulator/initial_conditions.cc:105: error: ‘ref’ is not a member of ‘std’
> Replaced std::ref with std_cxx11::ref

- include/aspect/particle/world.h
- source/particle/world.cc
- tests/particle_timing_information/screen-output
In hindsight it was wrong to assume that a user would only want to use one particle load balancing strategy. If for example one has a wide spectrum of allowed number of particles per cell, one might still want to repartition the mesh according to the combined weights of cells and particles (this is what I want to do right now in a model).  This PR allows to combine the existing strategies. It also allows to only add particles in poorly populated areas, which was previously only possible if the remove particles strategy was selected as well. Finally, I would like to change the default balancing strategy to 'repartition', since it does not harm a model (it is a small slowdown of the repartition, but it can lead to significant improvements in runtime), and it speeds up models for users with …
> Allow use of multiple particle load balancing techniques

- source/main.cc
Handle #1239.
When ending due to bad prm file also include reason if provided through exception.
Tester failure expected due to current test output being based on deal.II 8.5.
> Change to ParameterHandler::parse_*

- CMakeLists.txt
On some systems we need to link with "dl" to be able to use dlopen.
While we are here, make sure we can compile a simple test before
enabling that feature.
> link with libdl and check we can use dlopen

- include/aspect/introspection.h
- source/simulator/assembly.cc
- source/simulator/introspection.cc
- source/simulator/melt.cc
Currently we assemble every degree of freedom in the Stokes assembly, although many of them are zero because they belong to temperature or compositional fields. This PR fixes this by skipping all non Stokes dofs, which speeds up the assembly of an example model of mine by 20% (3D, box, incompressible, 1 compositional field). I think we could save even more, if we would figure out a way to make the scratch matrices and objects only large enough to hold the Stokes dofs, and only loop over them (as we do for the advection system). This would make the call to `is_stokes_component` unnecessary. It is a bit more tricky for Stokes though, because we would need a way from an index (0,stokes_dofs), which can be either a pressure or a velocity dof, to the correct dof of the global system. Something …
> Speed up Stokes assembly by only assembling Stokes degrees of freedom

- source/postprocess/visualization.cc
- tests/graphical_output_hdf5.cc
- tests/graphical_output_hdf5.prm
- tests/graphical_output_hdf5/screen-output
- tests/graphical_output_hdf5/solution.xdmf
- tests/graphical_output_hdf5/statistics
It looks like our HDF5 output was broken since the conversion to solution/ subdirectories, because the paths in the .xdmf file were added twice ("solution/output_directory/solution/filename.h5") and nobody noticed. Does not seem to be our usual output format :smile:. Anyway, this fixes the paths, and adds a test for the output format (sadly another binary output test, but it is small). I might also remove the .h5 files if we prefer to keep the binary files out of the repository.
> Fix hdf5 output

- doc/modules/changes.h
- include/aspect/assembly.h
- include/aspect/free_surface.h
- source/simulator/assembly.cc
- source/simulator/free_surface.cc
- source/simulator/melt.cc
- tests/inner_core.cc
This should address #756. It is quite likely that there will be test failures (I only checked incompressible cases without melt so far), but the speedup I have seen has been very nice (~30% faster Stokes matrix assembly, maybe 10-15% for Stokes preconditioner, for a 3d box test model). Given that for simple models the Stokes assembly takes on the order of 10-30% of the total model time this is a nice 3-10% overall speedup for many of my models. In particular simple benchmark problems will benefit.
> Shrink Stokes system assembly

- doc/modules/changes.h
- include/aspect/particle/world.h
- source/particle/world.cc
- tests/matrix_nonzeros_2.prm
- tests/matrix_nonzeros_3.prm
- tests/particle_interpolator_cell_average.prm
- tests/particle_interpolator_cell_average_2.prm
- tests/particle_interpolator_empty_cells.prm
- tests/particle_interpolator_from_ghost_cells.prm
- tests/particle_load_balancing_removal_addition_properties.prm
- tests/particle_property_multiple_functions_with_interpolation.prm
I have observed that in some models with many particles the exchange of ghost particles is quite expensive. It might be possible that there is a bottleneck in the code that I do not quite understand, but so far I have not observed  this behaviour in applications (only in tests). Therefore I would like to disable the exchange by default for now, until we figure out what is going on. @naliboff, @egpuckett, @hlokavarapu: This will likely require you do add the parameter 'Update ghost particles = true' to your models with active particles, sorry for that inconvenience. Did you ever had a model in which the exchange of ghost particles took longer than all of the rest of the particle algorithm combined?
> Make ghost particle exchange optional

- source/simulator/melt.cc
Well, I wanted to run the ASPECT test suite to double check the boost upgrade (see dealii/dealii#3279) and I noticed this.
This fixes compilation when deal.II is compiled with 64 bit indices (i.e., DEAL_II_WITH_64BIT_INDICES=ON).
> Use types::global_dof_index for dof indices.

- include/aspect/material_model/simple.h
- source/material_model/simple.cc
Remove hard-coded limits in simple.cc and replace with user-specified viscosity cutoff values. Retain former hard-coded values as default behavior.
> Viscosity limits

- include/aspect/particle/particle.h
- source/particle/particle.cc
- source/particle/world.cc
This is the first of a series of pull requests optimizing some aspects of particle transfer. This one specifically:
- Adds a move constructor to particles that are generated from other particles that are not longer needed. @bangerth: I am not sure if what I implemented in the constructor is already optimal, but at least it is four times faster than the copy constructor (no more allocation of dynamic memory). Is there something I am missing?
- Reduces the number of particle constructor calls from `load_tracers` and if possible use the move-constructor
- Provides insertion hints inside `load_tracers` into the particles multimap (because all tracers of the same cell are inserted into the same region of the multimap), which improves the scaling behaviour of this function (but does not matter …
> Reduce particle creations in load_tracers

- include/aspect/particle/world.h
- source/particle/world.cc
In a similar fashion as #1258 this PR tries to optimize particle runtime in adaptive parallel models. It includes three improvements:
- `send_recv_particles` no longer takes a multimap, but rather a vector of vectors of particles to send. This should have been the behaviour from the beginning, because there is no reason to keep them in a multimap here (we loop over them particle-by-particle, not cell-by-cell, and we excactly know how many neighbors we have), and the vector can be filled faster. This results in a number of container changes in other functions as well, but replaces another case of `NlogN` complexity by linear complexity.
- The `sort_particles_in_subdomains_and_cells` function had a major scalability flaw by only checking face neighbors of the current cell before doing a …
> Avoid maps. Use vertex neighbors for sort.

- source/particle/world.cc
Supersedes #1263 and includes a fix for a pre-existing bug.
emplace_hint is not supported in gcc 4.6.x and 4.7.x even though this is
part of cxx11. So we require cxx14 for this for now.
> Particle emplace cpp14

- source/particle/world.cc
- source/simulator/core.cc
1. boost::scoped_ptr can not be returned from a function
2. std::multimap::insert(hint) takes a non-const iterator pre cxx11
> fixes to compile without cxx11

- doc/modules/changes.h
- include/aspect/material_model/visco_plastic.h
- source/material_model/visco_plastic.cc
- tests/visco_plastic/screen-output
- tests/visco_plastic_yield/screen-output
- tests/visco_plastic_yield_strain_weakening.prm
- tests/visco_plastic_yield_strain_weakening/screen-output
Implementation of a strain weakening option to the visco_plastic material model.  Strain weakening is calculated via finite strain, which may be calculated through particles or compositional fields through the finite_strain plugin.  
For either of these options, the material model assumes (and states in the documentation) that the fields tracking each finite strain component must be listed prior to any additional fields.  This allows removing the contribution of the finite strain fields from the volume fraction of each element.  Is there a better way to do this?  I can think of a few other methods, but am interested to hear new ideas on this point.
> Add strain weakening option to the visco_plastic material model

- source/postprocess/matrix_statistics.cc
> Fix memory postprocessor to output with types::global_dof_index.

- source/material_model/melt_simple.cc
Allow negative density changes (in addition to positive ones) in the melt simple material model. This was always intended (and is already included in the documentation of the parameter), and was just an oversight during the implementation, noticed by @mgouiza.
> Allow negative depletion density changes

- doc/manual/manual.tex
In the current version, the figures are too close together to see that they are not supposed
to be part of the same.
> Put some space between two rows of pictures.

- doc/manual/cookbooks/composition-active-tracers/tracers.part.prm
- doc/manual/cookbooks/composition-passive-tracers/tracer-properties.part.prm
With the current versions of these two files, our scripts could not generate correct links
for each parameter to the section of the manual where the parameter is described. For this
to work, we need to use the complete set of surrounding sections.
Add these.
> Use complete subsection paths in manual .prm snippets.

- doc/modules/changes.h
- include/aspect/particle/output/vtu.h
- source/particle/output/vtu.cc
We already created a .pvd file for Paraview, but not a .visit file.
> Also create a .visit record for all particle files.

- include/aspect/particle/particle.h
- include/aspect/particle/property/integrated_strain.h
- include/aspect/particle/property/interface.h
- include/aspect/particle/property/pT_path.h
- include/aspect/particle/property/position.h
- include/aspect/particle/property/velocity.h
- include/aspect/particle/world.h
- source/particle/interpolator/cell_average.cc
- source/particle/output/ascii.cc
- source/particle/output/hdf5.cc
- source/particle/output/vtu.cc
- source/particle/particle.cc
- source/particle/property/integrated_strain.cc
- source/particle/property/interface.cc
- source/particle/property/pT_path.cc
- source/particle/property/position.cc
- source/particle/property/velocity.cc
First part of #1220, only containing the interface changes to `Particle::get_properties`.
I was wondering if  `Particle::set_properties` should now also take an ArrayView instead of a vector? But on the other hand we do this change to hide the internal representation of the properties from the outside, and `set_properties` can simply convert the vector to something else in that case, so it should be fine to keep the vector?
> Return particle properties as ArrayView

- doc/manual/manual.tex
Added space in \times10. This supersedes #1094
> Manual fixes: alpha for thermal expansivity and more

- doc/manual/manual.tex
This is entirely justified following the merge of #1095.
> Add Louise Kellogg as an author.

- source/particle/output/vtu.cc
- source/postprocess/visualization.cc
https://github.com/dealii/dealii/pull/3658 moved a bunch of functions from DataOutInterface
to DataOutBase and deprecated the former. This patch makes the corresponding change
in ASPECT to avoid the warning about the use of deprecated functions.
> Use non-deprecated function name where necessary.

- include/aspect/particle/generator/quadrature_points.h
- include/aspect/particle/generator/reference_cell.h
- source/particle/generator/quadrature_points.cc
- source/particle/generator/reference_cell.cc
Fix to #1302 
The particle generator code for storing particle index variables has been removed from 'quadrature points' and 'reference cell particle' generators after Wolfgang has pointed out that the function is not being called anywhere else and that the particle index is not being stored at checkpoints as well.
> Removed particle index storage in particle generators reference cell and quadrature points

- doc/manual/manual.tex
This was previously missing from the manual.
Fixes #1304. Also addresses in part #989.
> Define thermal expansion coefficient alpha.

- doc/manual/manual.bib
Fix the title of the remaining copy.
> Remove duplicated reference.

- doc/manual/manual.tex
We used to dump everything into the output/ directory, but now use output/solution/
for solution files. Reflect this in the manual.
While there, also update a bunch of other things.
Fixes #1199.
> Update the manual for output file paths.

- doc/manual/cookbooks/overview/simple.prm
- doc/manual/cookbooks/overview/structure.part.prm
Specifically, align them with choices in the cookbooks. Also no longer use
'all' for postprocessors, since that is no longer allowed.
> Update a few .prm fragments that go into the manual.

- source/postprocess/depth_average.cc
If a number happens to fill 12 digits, there is no space to the next
column leading to an unreadable file.
> fix missing space in depth_average txt output

- include/aspect/global.h
This disables a bunch of warnings inside boost we can not control (for
example new warnings produced by clang 3.9.1).
> wrap boost include with DIAGNOSTICS macro

- include/aspect/melt.h
> Avoid using the deprecated class std::auto_ptr.

- source/simulator/core.cc
When working on a test problem for #1177, I found a bug of current code that the time dependent boundary condition doesn't update for the temperature/composition if use the discontinuous discretization. This patch fixes this bug.
> bug fixed for time-dependent boundary condition with DG approach

- include/aspect/utilities.h
- source/utilities.cc
While there, also fix an in-code comment that is grammatically incorrect and
only documents the history of a line, not what it does.
> Fix documentation of Utilities::fexists.

- doc/manual/manual.tex
This makes sure parameters are correctly cross-linked and the snippet appears in the
index of the manual.
> Use the annotated version of a .prm snippet in the manual.

- include/aspect/geometry_model/interface.h
The comment suggests that a function has a default implementation, but
it's actually abstract ('=0').
> Remove a wrong comment.

- doc/manual/manual.tex
Add entry suggested by #1140
This is a sparse skeleton manual entry for writing and running tests. I have assumed that the section on tests is best included under the section for extending aspect.
> [WIP] Manual entry for tests

- cookbooks/composition-active-tracers.prm
- source/particle/interpolator/cell_average.cc
- tests/melt_material_1.cc
The `cell_average` particle property interpolator always tried to access the particles in ghost cells, even in serial computations. This is unnecessary, and I moved that call to the places where it is needed (if it encounters ghost cells). Additionally it is more save to just exchange ghost particles in the cookbook, in case it is run in parallel and there is an empty cell next to a ghost cell. Fixes #1376.
> Fix cookbook and interpolator

- cookbooks/future/steinberger.prm
The crash was likely caused by some changes to the material model in the recent months, although it is not quite clear why. This PR at least makes the future cookbook converge again. Most of this PR is cleanup of the parameter file, but the significant changes are:
- inclusion of adiabatic and shear heating (the material model is compressible, so those should be enabled)
- using an initial condition with a perturbation, instead of an unperturbed state
- setting the reference_viscosity to the average viscosity of the model, not the maximum viscosity
The last point was the solution to the convergence problems. I am not very happy that this somewhat arbitrary property decides if a model converges or not, but that is a problem for another time. The parameter file is working again. Fixes …
> Fix steinberger cookbook parameter file

- include/aspect/assembly.h
- include/aspect/simulator.h
- source/simulator/assembly.cc
- source/simulator/helper_functions.cc
This is a workaround to an inefficiency in our current assembly system. We determine whether to assemble face terms by checking the number of face assemblers. These assemblers might only be necessary for a different advection system though (e.g. the discontinuous compositional fields in case of active particles). This slows down assembly unnecessarily by evaluating FeFaceValues in many unnecessary cases in models with mixed discontinuous/continuous advection elements.
I call this a workaround, because in the future we might have other reasons for assembling face terms for the advection assembly than just discontinuous elements, but since there is no case I am currently aware of, this is the easiest solution for now.
> Restrict assembly of face values to discontinuous fields

- source/utilities.cc
This silences a warning for very new gcc compilers. We always initialize this variable (because we do not fiddle around with the loop counter of this for-loop), but in order to avoid this warning this is a fix, and a small cleanup. This PR should be included in 1.5.0.
> Silence a warning for gcc 6

- Dockerfile
- doc/manual/manual.tex
- doc/release-tasklist
- docker/Dockerfile
- docker/build.sh
Following the recent discussion about docker containers on the mailing list, I thought it would be nice to have a more practical discussion, including an example for how such a image could look like, and how the workflow of running a model would look like. When reading into the topic again I noticed some improvements on Docker's side since I last read about it (~1-2 years ago). Installation on Ubuntu is now better explained, and some comfort features I was missing before have been added (like cleanup of finished containers and dangling images: `docker container prune` and `docker image prune`). Unfortunately they introduced the cool new Docker for Windows app that only runs on Win 10 Professional, and hide the legacy solution for Win 10 Home pretty well (it is called docker toolbox, if …
> Provide a Docker image

- doc/modules/changes.h
- source/simulator/helper_functions.cc
- tests/pressure_compatibility_dg.prm
- tests/pressure_compatibility_dg/screen-output
- tests/pressure_compatibility_dg/statistics
- tests/pressure_compatibility_dg_direct.prm
- tests/pressure_compatibility_dg_direct/screen-output
- tests/pressure_compatibility_dg_direct/statistics
- tests/pressure_compatibility_direct.prm
- tests/pressure_compatibility_direct/screen-output
- tests/pressure_compatibility_direct/statistics
Completely re-implement make_pressure_rhs_compatible to handle all
combinations of
1. CG vs DG
2. direct vs iterative solver
3. melt vs no melt
(except melt and DG)
and add documentation and tests.
Bonus: remove wrong assert in denormalize_pressure that would trigger for parallel DG computations with a direct solver.
> Implement make_pressure_rhs_compatible for compressible computations

- benchmark/king2dcompressible/ala/ala.prm
When updating the run script I forgot to update the parameter file as well. No functional changes, only the termination criterion was wrong (the previous file would run forever). The change in linear solver tolerance does not change the result significantly, but I include it to exactly match the file we used for creating the official output.
> Fix King benchmark parameter file

- include/aspect/material_model/latent_heat.h
- source/material_model/latent_heat.cc
- tests/latent_heat_viscosity.prm
- tests/latent_heat_viscosity/screen-output
- tests/latent_heat_viscosity/statistics
This pull request fixes a bug in the latent heat material model: there was an input parameter `Viscosity prefactors` that was documented and could be set in the input file, but was never used in the code and hence had no actual effect. With these changes, the parameter now does what the documentation says. In addition, parameters for setting a min and max viscosity is introduced. This brings the material to the state we used in our manuscript about numerical methods in ASPECT. 
I also want to see if this changes any tests, if not, I will add one.
> fix a bug in the latent heat material & add min and max viscosity

- include/aspect/compat.h
- include/aspect/material_model/interface.h
When trying some things regarding #1361 I noticed that our current development version depends in many places on some internal includes in deal.II that were removed after 8.5. Since I assume we want to require 8.5 (and not 9.0 + C++11) for our next ASPECT release, we should fix this. I would advocate for dropping non C++11 support for ASPECT after the next release.
> Add legacy includes to make compile with deal.II 9.0.pre

- doc/manual/manual.tex
Use figshare for the location of the manual so we have a citable version including a DOI.
The title is a little weird but I would like to have the word "manual" in the title. Also is it "user's manual" or "user manual"? Right now it is closest to what you actually see in the pdf.
> update reference for user manual

- doc/indent
> Fix indent script

- source/simulator/melt.cc
This call creates deprecation warnings with a recent deal.II.
> [Dont merge] Remove deprecation warning

- CMakeLists.txt
- doc/modules/changes/201704229_tjhei
- tests/CMakeLists.txt
- put the tests into a separate cmake project
- do not recompile aspect while running ctest
- always use make as the generator for the test project
> Testing project

- doc/manual/manual.tex
This fixes #1454. What was missing was just to use \noindent in a couple of places.
> Fix the layout of the front page of the manual.

- source/boundary_velocity/interface.cc
- source/initial_temperature/interface.cc
- source/postprocess/interface.cc
- source/postprocess/visualization.cc
This is the uncontroversial part of #1460. Only code cleanup to avoid namespace and variable confusions.
> Cleanup some code

- CMakeLists.txt
- cmake/cotire.cmake
This is the most useful part of #1460, that will already by itself allow to precompile all external header files and reduce ASPECT's compile time by around 50%. The new cmake option is disabled by default, until we get a feeling for how well this works on different machines. The current plan is to merge this PR and make a little poll at the hackathon to see how reliable this is, and how we should proceed.
Unity builds (discussed in #1460) will be allowed when the cmake option is enabled (there will be a new make target `aspect_unity`), but until #1472 is merged, and the remaining problem in #1460 is solved they will not succeed.
> Add ASPECT_PRECOMPILE_HEADER cmake option

- CMakeLists.txt
The PR #1466 removed the test target by accident, which allows you to do
``make test`` in the ASPECT build directory.
This PR introduces a new 'test' target that builds aspect first and then runs
the 'test' target in the ``tests/`` subdirectory.
fixes #1479
> re-add test make target

- doc/manual/manual.bib
The manual currently uses a mix of abbreviated and non-abbreviated first names
in the list of references. Consistently use abbreviated first names for the
entry buiter2008dissipation.
> Use consistent abbreviations of first names in the list of references.

- .gitignore
- doc/manual/manual.tex
I prefer "Elbridge Gerry Puckett" to "E. Gerry Puckett".
> Changed the convention for naming EGP in the manual author list.

- source/adiabatic_conditions/interface.cc
- source/boundary_composition/interface.cc
- source/boundary_fluid_pressure/interface.cc
- source/boundary_temperature/interface.cc
- source/boundary_traction/interface.cc
- source/geometry_model/interface.cc
- source/gravity_model/interface.cc
- source/heating_model/interface.cc
- source/initial_composition/interface.cc
- source/material_model/interface.cc
- source/mesh_refinement/interface.cc
- source/particle/generator/interface.cc
- source/particle/integrator/interface.cc
- source/particle/interpolator/interface.cc
- source/particle/output/interface.cc
- source/prescribed_stokes_solution/interface.cc
- source/termination_criteria/interface.cc
These changes avoid errors in unity builds on some machines, but they are also independently useful and correct.
> More fixes for unity build

- include/aspect/simulator.h
- source/simulator/helper_functions.cc
- source/simulator/initial_conditions.cc
- source/simulator/solver.cc
This makes the function a bit easier to understand because it returns the
pressure adjustment. All callers currently still store the result in the same
place where it was stored before, but at least the hidden side effect is
gone.
This addresses a part of #1229. I will follow up with more cleanups
later, but I want to see whether this one works first.
This is a candidate for a Puckett Bucket award. I'm not 100 per cent
sure it's going to work, but thought I'd punt it over to the tester
to see what happens.
> Make normalize_pressure() return a value.

- include/aspect/heating_model/compositional_heating.h
- source/heating_model/compositional_heating.cc
- tests/compositional_heating.prm
- tests/compositional_heating/screen-output
Lithospheric-scale models often assign fixed heat generation (W/m^3) values to distinct materials. This pull request provides this functionality by adding a heating model where one may assign temporally constant values of heat production to compositional fields.
> Add compositional heating model

- tests/CMakeLists.txt
There was a missing dependency from the .cmp.notime file to the
normalization of all (generated and reference) outputs. This caused the
tester to occasionally fail. Fix this.
> set correct test dependencies

- source/boundary_traction/interface.cc
Fixes a problem reported in #1491 by @ian-r-rose.
> Avoid a warning about an unused argument.

- include/aspect/simulator.h
- source/simulator/checkpoint_restart.cc
- source/simulator/core.cc
- source/simulator/helper_functions.cc
- source/simulator/initial_conditions.cc
- source/simulator/solver.cc
This is follow-up to #1495 and another patch addressing #1229.
> Rename a variable in Simulator to make its intent clearer.

- tests/cmake/run_test.sh
Print the screen-output when running ctest and ASPECT crashes. This way
it will show up on the tester as well.
> report test output on test failure

- source/geometry_model/interface.cc
changing assert in geometry_model interface.cc because it stated material model instead of geometry model
> fix assert message geometry_model interface

- include/aspect/material_model/interface.h
- source/material_model/interface.cc
- source/simulator/lateral_averaging.cc
This patch adds a new MaterialModel array constructor that both initializes
and populates the MaterialModel arrays. The old constructor only sizes
the arrays, then the arrays must be populated within the calling function.
This constructor streamlines how these array values are obtained by making
a single standard call to the constructor. This patch is now called in
nullspace.cc to test.
> Create a new MaterialModel constructor.

- doc/update_prm_files_to_2.0.0.sed
- doc/update_source_files_to_2.0.0.sed
On mac the command for sed inline replacement without a backup need quotes.
> Add comment for mac

- include/aspect/utilities.h
- source/utilities.cc
- tests/prm_distance_polygon.cc
- tests/prm_distance_polygon.prm
- tests/prm_distance_polygon/screen-output
Not sure if it needed a test, but out of curiosity I made one of this type.
> Add distance to polygon function

- source/postprocess/global_statistics.cc
- source/simulator/assembly.cc
- source/simulator/core.cc
- source/simulator/entropy_viscosity.cc
- source/simulator/helper_functions.cc
- source/simulator/initial_conditions.cc
- source/simulator/nullspace.cc
- source/simulator/simulator_access.cc
> Fix n_comp_fields

- source/geometry_model/interface.cc
This removes two warning during the compilation.
> Add return to the geometry model default natural coordinates function.

- doc/modules/changes/20170509_tjhei
- include/aspect/assembly.h
- include/aspect/material_model/interface.h
- include/aspect/parameters.h
- source/simulator/assemblers/stokes.cc
- source/simulator/melt.cc
- source/simulator/parameters.cc
- tests/burstedde_stokes_rhs.cc
- tests/burstedde_stokes_rhs.prm
- tests/burstedde_stokes_rhs.sh
- tests/burstedde_stokes_rhs/screen-output
- tests/melt_force_vector.cc
- tests/melt_force_vector.prm
- tests/melt_force_vector/screen-output
Latest idea on how to do force vector for the Stokes system.
supersedes #1300
> Additional Stokes RHS

- source/main.cc
- source/simulator/core.cc
- source/simulator/free_surface.cc
- source/simulator/initial_conditions.cc
The #if DEAL_II_VERSION_GTE(8,5,0) #else statements were added when dealii.8.5.0 was not released. Now we can remove those statements as  it will be mandatory for aspect 2.0
> Remove requirement deal.ii.8.5.0 related statements

- include/aspect/material_model/interface.h
- source/geometry_model/interface.cc
- source/material_model/interface.cc
Same for derived class NamedAdditionalMaterialOutputs. Also move a couple of
function definitions to the .cc file.
While there also clean up the spacing between functions in another file.
> Provide better documentation for the AdditionalMaterialModelOutput class.

- source/boundary_traction/initial_lithostatic_pressure.cc
There are other warnings in this file, but this is the one that's easy to fix.
The others are about using deprecated functions like boundary_temperature() when
they should be using the corresponding manager.
> Avoid one warning about an unused variable.

- include/aspect/adiabatic_conditions/ascii_data.h
- include/aspect/gravity_model/ascii_data.h
- include/aspect/material_model/ascii_reference_profile.h
- include/aspect/newton.h
- include/aspect/particle/interpolator/nearest_neighbor.h
- include/aspect/postprocess/geoid.h
Macros are not allowed to start with double underscores and my IDE warns
about this.
> remove macro double underscore

- include/aspect/geometry_model/interface.h
- source/geometry_model/interface.cc
- source/postprocess/stokes_residual.cc
- source/utilities.cc
This uses the following compiler: icc version 15.0.0 (gcc version 4.4.7 compatibility)
> Compiler compatibility

- source/utilities.cc
The old function produced NaNs for zero arguments.
> Fix Utilities::compute_spd_factor.

- doc/manual/manual.bib
I altered the author names in the list of references per issue #1488. This update is part one of two and includes up to line 5620 in manual.bib. All authors (and editors if applicable) are now listed as last name followed by initials. A paper authored by Joshua Keyes, Edward Brazzelton, and Conrad Zimsky would be listed as {Keyes, J. and Brazzelton, E. and Zimsky, C.} .
> bib_fix_pt1

- include/aspect/material_model/interface.h
- source/material_model/interface.cc
This patch adds a function to reinitialize and populate the arrays created by
the MaterialModelInputs constructor. The MaterialModelInputs constructor with the
same arguments creates the arrays, then calls this function to populate them.
This function is intended to be called within loops over cells so that arrays
are not recreated more than necessary.
> Added a reinit function to MaterialModelInputs.

- doc/manual/manual.tex
The fixes a small typo in the equation of the implicit reference density profile in the manual.
> Fix a small typo in the manual

- include/aspect/simulator.h
The function definition belonging to this declaration was removed quite a while ago. I looked for this function for a while, until I noticed it was replaced by a signal slot.
> Remove non-existent function declaration

- doc/manual/manual.tex
Add details to the command line options of point 2, in particular, details of mounting a volume using docker. Fixed warped line issue as well.
Reference issue #1481
> Clarify and elaborate point 2 of section 3.1.2 in the manual

- doc/manual/manual.tex
Some text boxes within the manual contained words separated by visible space
characters. These were removed by adding the option showstringspaces=false to
the lstlisting sections in manual.tex.
> Remove explicit space characters from text boxes in the manual.

- include/aspect/utilities.h
- source/utilities.cc
While there, also follow convention of passing std::string objects
by reference.
> Minor doc update.

- include/aspect/geometry_model/spherical_shell.h
- source/geometry_model/spherical_shell.cc
Reference issue #1589
@jaustermann , unfortunately I do not have intel compilers to test this fix. However, both Rene and I are confident that this will fix the issue.
> Add constructor to SphericalShell class to silence icc compiler warning

- doc/modules/changes/20170509_dannberg
- doc/update_prm_files_to_2.0.0.sed
This extends the documentation and extends our update scripts for the changes merged in #1540. I tested the script on a little example file, it seems to work (replacing the old postprocessors into one instance of the new postprocessor).
> Update script and changelog

- include/aspect/boundary_temperature/function.h
- include/aspect/boundary_traction/function.h
- include/aspect/boundary_velocity/function.h
- include/aspect/initial_temperature/function.h
- include/aspect/mesh_refinement/maximum_refinement_function.h
- include/aspect/mesh_refinement/minimum_refinement_function.h
In reference to a discussion in #1628.
> Simplify some code by not qualifying an enum fully.

- doc/modules/changes/20170513_egp-cig-reu
- include/aspect/particle/interpolator/bilinear_least_squares.h
- source/particle/interpolator/bilinear_least_squares.cc
- tests/particle_interpolator_bilinear_solkz.cc
- tests/particle_interpolator_bilinear_solkz.prm
- tests/particle_interpolator_bilinear_solkz/screen-output
- tests/particle_interpolator_bilinear_solkz/statistics
@gassmoeller, New bilinear particle interpolation scheme contributed by @yinghe616 , @egpuckett . We plan to incrementally update this scheme in the near future introducing limiters to prevent overshoot and undershoot as well as implement the case for 3D models.
> Bilinear Least Squares Particle Interpolation Scheme

- benchmarks/tangurnis/ba/tan.prm
- doc/manual/manual.tex
- doc/modules/changes/20170514_myhill
- doc/modules/to-1.5.0.h
- doc/update_prm_files_to_2.0.0.sed
- include/aspect/material_model/nondimensional.h
- include/aspect/parameters.h
- source/simulator/parameters.cc
- tests/blankenbach_approximation.prm
- tests/tangurnis_ba.prm
> Capitalized Boussinesq approximation

- benchmarks/check.sh
Recent edits to check.sh in benchmarks as part of the recent merge of PRs #1633, #1539, and #1498 results in failure. This was an oversight on my part and this PR is a fix to the issue. Also, I have added stylistic changes for better readability.
@tjhei , can you review this PR please, thanks.
> Fix bug for Inclusion, SolCx, and SolKz benchmarks in check.sh

- include/aspect/mesh_refinement/composition_approximate_gradient.h
- source/mesh_refinement/composition_approximate_gradient.cc
- tests/particles_with_AMR_on.prm
- tests/particles_with_AMR_on/screen-output
- tests/particles_with_AMR_on/statistics
This new patch added a new mesh refinement criterion for compositional field using approximated gradient, which can be also used for passive particles, where the properties are  interpolated to the discontinuous composition field. Below are the three simple tests with provided test example prm file but with three different mesh refinement strategies: 
set Strategy    = composition approximate gradient
set Strategy    = composition gradient
set Strategy    = composition
> New mesh refinement criterion for discontinuous composition field using approximated gradient

- source/mesh_refinement/artificial_viscosity.cc
- source/mesh_refinement/composition.cc
- source/mesh_refinement/temperature.cc
I didn't change any functionality or logic of those code. When I wrote the new mesh refinement composition_approximate_gradient.cc, just looked around other sources files in the same folder, and I found that some of those codes can also be simplified.
> simplifying the code in the other source files under the refinement folder

- source/mesh_refinement/composition_gradient.cc
> Cross link plugins.

- source/boundary_temperature/function.cc
- source/boundary_traction/function.cc
- source/boundary_velocity/function.cc
- source/initial_temperature/function.cc
- source/mesh_refinement/maximum_refinement_function.cc
- source/mesh_refinement/minimum_refinement_function.cc
- source/simulator/assemblers/newton_stokes.cc
- source/utilities.cc
This addresses incompatibilities with a pre c++11 compiler introduced by the CoordinateSystem namespace @mbweller . I also included the to_string incompatibility addressed by a pull request by @MFraters (I had to do that as well to check whether it compiles).
> fixes for non c++11 compilers

- doc/modules/changes/20170515_austermann
- source/postprocess/visualization.cc
I would prefer the default to be 1 ... what do others think?
> Make default of Number of grouped files 16

- source/main.cc
Due to the complexity of the issue #1674 , until the underlying code has been implemented, this PR will include the deal.ii git short revision id as part of `./aspect --version`
> Add deal_II git short revision to version info

- doc/Makefile
This change allows to make the manual on Linux and MacOS (they have different syntax for sed). @tjhei: slightly different from what we discussed, because the other version did not run on Linux (I tested the wrong version).
> fix make manual.pdf on macos

- doc/modules/changes/20170516_3_mfraters
- include/aspect/postprocess/visualization/spd_factor.h
- source/postprocess/visualization/spd_factor.cc
Split up of #1653, part 3. This pull request add a visualisation postprocessor for the spd factor which is used in the Newton solver to keep the Jacobian Positive definite.
> Newton merge 3, part 3: Add visualisation postprocessor for the spd factor of the Newton method.

- include/aspect/material_model/interface.h
- source/material_model/interface.cc
- source/mesh_refinement/density.cc
- source/mesh_refinement/thermal_energy_density.cc
- source/mesh_refinement/viscosity.cc
- source/postprocess/geoid.cc
- source/postprocess/heat_flux_densities.cc
- source/postprocess/heat_flux_statistics.cc
- source/postprocess/heating_statistics.cc
- source/postprocess/mass_flux_statistics.cc
- source/postprocess/melt_statistics.cc
- source/postprocess/viscous_dissipation_statistics.cc
- source/simulator/nullspace.cc
This uses the new MaterialModelInputs<dim>::reinit() function of @pmbremner in a bunch of places.
> Use MaterialModelInputs<dim>::reinit() where appropriate.

- include/aspect/material_model/latent_heat_melt.h
- source/material_model/latent_heat_melt.cc
In material_model/latent_heat_melt
> Removed interface compatibility.

- benchmarks/shear_bands/shear_bands.cc
- benchmarks/solitary_wave/solitary_wave.cc
- include/aspect/material_model/latent_heat_melt.h
- include/aspect/material_model/melt_global.h
- include/aspect/material_model/melt_simple.h
- include/aspect/melt.h
- source/material_model/latent_heat_melt.cc
- source/material_model/melt_global.cc
- source/material_model/melt_simple.cc
- source/simulator/melt.cc
- tests/composition_active_with_melt.cc
- tests/melt_compressible_advection.cc
- tests/melt_force_vector.cc
- tests/melt_introspection.cc
- tests/melt_material_1.cc
- tests/melt_material_2.cc
- tests/melt_material_3.cc
- tests/melt_material_4.cc
- tests/melt_transport_adaptive.cc
- tests/melt_transport_compressible.cc
- tests/melt_transport_convergence_simple.cc
- tests/melt_transport_convergence_test.cc
- tests/melting_rate.cc
- require material models to derive from MeltInterface if you want to use them with melt transport
- add a new function ``reference_darcy_coefficient()`` (not used in computation yet)
> Add MeltInterface and reference_darcy_coefficient

- include/aspect/simulator_signals.h
- source/simulator/free_surface.cc
Without these signals, pre deal.II 9 versions will complain, because they will only have a manifold and not a boundary object to compute normal vectors.
> Add signal to free_surface to remove manifold from boundaries

- source/postprocess/visualization.cc
Specifically, when the number of grouped files is larger than the number of MPI
processes, run through the same code path as the one we use when creating
one output file per process (grouped files = 0).
This works around something that looks like a bug in the Mac OS X MPI libs
where we quickly run out of file handles when trying to write in parallel
via grouped files (which involves MPI IO calls).
Found on @cedrict 's machine.
> Simplify code paths in parallel output generation.

- include/aspect/utilities.h
- source/simulator/core.cc
- source/utilities.cc
This does not change functionality but allows me to use the function in other .cc files later.
> move and rename extract_component_subset

- include/aspect/material_model/visco_plastic.h
- source/material_model/visco_plastic.cc
- tests/visco_plastic_yield_strain_weakening_full_strain_tensor.prm
- tests/visco_plastic_yield_strain_weakening_full_strain_tensor/screen-output
Provide an option to use the full finite strain tensor for the strain weakening component of the visco_plastic material model.  There is a warning in the material model's documentation about the pitfalls of this option.
@anne-glerum - Any and all feedback welcome!
> Add option to use full finite strain tensor for strain weakening

- doc/modules/changes/20170516_myhill_2
- doc/modules/changes/20170516_myhill_3
- include/aspect/initial_composition/interface.h
- include/aspect/initial_temperature/interface.h
- source/initial_composition/interface.cc
- source/initial_temperature/interface.cc
- tests/initial_composition_list_using_maximum.prm
- tests/initial_composition_list_using_maximum/screen-output
- tests/initial_composition_list_using_maximum/statistics
- tests/initial_composition_list_using_minimum.prm
- tests/initial_composition_list_using_minimum/screen-output
- tests/initial_composition_list_using_minimum/statistics
- tests/initial_composition_list_using_subtract.prm
- tests/initial_composition_list_using_subtract/screen-output
- tests/initial_composition_list_using_subtract/statistics
- tests/initial_temperature_list_using_maximum.prm
- tests/initial_temperature_list_using_maximum/screen-output
- tests/initial_temperature_list_using_maximum/statistics
- tests/initial_temperature_list_using_minimum.prm
- tests/initial_temperature_list_using_minimum/screen-output
- tests/initial_temperature_list_using_minimum/statistics
- tests/initial_temperature_list_using_subtract.prm
- tests/initial_temperature_list_using_subtract/screen-output
- tests/initial_temperature_list_using_subtract/statistics
This PR adds the ability to choose basic arithmetic operators to the initial temperature interface (add, subtract, minimum, maximum), which control how successive plugins modify the initial temperature field.
> Initial temperature operators

- include/aspect/simulator_access.h
- source/material_model/drucker_prager.cc
- source/simulator/simulator_access.cc
This fixes the drucker_prager material model compiling warning after @bangerth
> Fix the drucker_prager material model compiling warning

- source/main.cc
- tests/fail/screen-output
- tests/steinberger_lateral_fail/screen-output
- tests/visualization_unique_list/screen-output
- tests/zero_matrix/screen-output
triggering Assert() in debug mode on rank!=0 can cause a deadlock inside
std::abort. This causes the tester to hang for 10 minutes on each
failing test. Work around this by hooking into SIGABRT and terminating
the process.
Also extend the information shown when an exception is detected (MPI
rank, exception name).
> add clever abort handling to avoid MPI deadlock

- doc/aspect-gui
In particular, we only want to do one replacement (so don't use 'g') and
only want to do it at the end of the filename (use the dollar sign for end
of string).
This is an update to #1759. I'd appreciate if @gassmoeller could verify
that using the dollar sign in the regex with sed actually works as
expected. But it seems to work for me.
> Be more conservative with regexes.

- doc/aspect-gui
While reviewing #1762 I noticed that `aspect-gui` will currently overwrite input file names, if sed does not find anything to replace. All our parameter files usually end on `.prm`, but this is not a requirement, and we should take care not to damage input files in the process.
> Add safeguard for unusual file names to aspect-gui

- include/aspect/initial_composition/interface.h
- include/aspect/initial_temperature/interface.h
- include/aspect/utilities.h
- source/initial_composition/interface.cc
- source/initial_temperature/interface.cc
- source/utilities.cc
- tests/ascii_boundary_member.cc
#1720 introduced some duplication by copying operators into both interfaces for initial composition and initial temperature. As I plan to extend this functionality to boundary conditions as well, it makes sense to move the code into utilities instead, and make it available for other parts of the program as well.
> Move operators to utilities

- source/boundary_temperature/constant.cc
- source/simulator/assemblers/stokes.cc
- source/simulator/core.cc
- source/simulator/entropy_viscosity.cc
- source/simulator/lateral_averaging.cc
- source/simulator/melt.cc
More specifically, replace quiet NaNs by signaling NaNs since they are a faster
way of figuring out what may be going wrong.
> Use the hammer.

- tests/checkpoint_01.cc
- tests/checkpoint_01/screen-output
I had to do this for debugging why this test failed with a floating
point exception in #1756. I thought it may be worth always doing.
It may fail because I'm printing a pathname, which I'm only
moderately sure the comparison script normalizes. Let's find
out what the tester has to say.
> Print the commands being executed in tests/checkpoint_01.

- include/aspect/utilities.h
- source/utilities.cc
- tests/var_declaration_expansion.cc
- tests/var_declaration_expansion.prm
- tests/var_declaration_expansion/screen-output
Attempt to add function requested by #1240. Needs to be tested, so it would help to identify likely locations of use.
Note that this will not be sufficiently dimension agnostic in composition field names, as the count cannot be currently used as the number of fields is a provided constant. This could possibly be corrected by making a breaking change to the parameter file that would also require that composition fields always be named. As I do not know of any other good test locations, I do not yet have a test in place.
> Add function to expand variable names

- doc/manual/manual.tex
In verbatim environments, one can just use a regular backslash, without having
to escape it somehow. In contrast, writing \backslash leads to printing
exactly this in the pdf, which is not what we want.
> Fix a mistake in the manual.

- include/aspect/plugins.h
Also update a comment while there.
This fixes #1801. Update to #1777. I didn't update the .dot file for the graph
because there is no real functional change. The output also already changes
due to #1804. We'll get the next full update the next time anyone runs
./doc/update_parameters.sh.
> Sort plugins before outputting them as a graph.

- doc/manual/plugin_graph.dot
- include/aspect/plugins.h
In particular, make sure that we don't spread text across multiple
lines. This appears to work on some versions of neato, but on others
it leads to errors. Instead, use \n where necessary.
Update to #1777.
> Update the style for the plugin graph.

- include/aspect/global.h
- include/aspect/simulator.h
We ought to be using the one that declares the *parallel* Trilinos block vectors,
not the one for the sequential version.
This may not have mattered in the past, but is currently necessary because
compilation with current deal.II otherwise fails, see
https://github.com/dealii/dealii/issues/4486 . It is also clearly the correct
thing to do regardless.
> Fix which include file we include.

- doc/manual/manual.tex
Prompted by a recent mailing list discussion.
> Update the manual section on tests.

- source/material_model/compositing.cc
The function was made obsolete by #1793, but I didn't notice it at the time.
Follow-up to #1602.
> Remove a function that is no longer used.

- doc/update_source_files_to_2.0.0.sed
There was a bug in the update script introduced by myself during the hackathon. The script accidentally deletes two characters (that I need to distinguish `initial_conditions*` from `initial_conditions.cc`). Now I keep those characters.
> Fix source update script

- include/aspect/particle/output/interface.h
- source/particle/output/ascii.cc
- source/particle/output/hdf5.cc
- source/particle/output/interface.cc
- source/particle/output/vtu.cc
The current implementation of the various serialization functions of particle output
classes have a comment that says that we ought to call the serialization function
of the base class -- but then they all do not actually do so. Fix this.
It doesn't current make any difference since the base class has nothing to serialize.
But it may acquire some data at some point in the future, and this patch prevents
the bug that would then become apparent.
> Ensure that the base class also gets to serialize its data.

- cmake/fpe_check.cmake
- source/main.cc
I found some systems do not initialize the FPE flags correctly (or inherit them in an unclean state). This means their state can be different for the cmake test than for the main program, passing our cmake test, but failing at runtime. 
Additionally, there is no exception that is raised (it was supposedly raised some time before program execution, but ignored). This means the FPE is raised at some random time, whenever the first function checks the state of these flags. This can for example happen in an innocent line like `ostream << 0.0`. Not to mention any names, but this change fixes crashes on Lonestar 5 :smile:, where we so far had to explicitly disable FPE_Exceptions (although cmake wants to enable them).
> Clear initial FPE flags

- doc/manual/manual.tex
The correct grant number was already listed just a few lines above, but we must have forgotten to fix this one.
> Fix reference to an outdated grant number.

- doc/manual/manual.tex
Found these outdated descriptions during reading a section of the manual.
> Update outdated material model interface description

- doc/manual/manual.tex
This part was not rendered correctly, it was simply missing the in manual.
> Fix manual code fragment

- CONTRIBUTING.md
- README.md
- doc/manual/manual.tex
This PR hopefully closes #438. Instead of duplicating this information we should explain it once in CONTRIBUTING.md (or in places linked from there) to avoid getting the manual and the file out of sync.
> Advertise CONTRIBUTING.md

- source/adiabatic_conditions/function.cc
The order for adiabatic function input should be temperature, pressure, and density. This causes a little confusion for the user. The description for the input order at the bottom is correct.
> Improve manual description for adiabatic conditions function subsection

- source/postprocess/geoid.cc
This pull request improves geoid code to use temperature polynomial degree for density integral and dynamic topography, which should be more appropriate. The geoid test prm file uses the same quadratic polynomial degree for velocity and temperature so I guess the test results should not change. @gassmoeller
> Polynomial degree change in geoid code

- doc/manual/manual.tex
This is only a first try to address #1818.
I am open for suggestions about which parts need to be more verbose. I would just like to avoid duplicating documentation between candi and the ASPECT manual, because they will get out of sync eventually.
> Rewrite install section

- doc/update_source_files_to_2.0.0.sed
- source/material_model/visco_plastic.cc
The current source update script renames `prescribed_traction_boundary_indicators` into `prescribed_boundary_traction_indicators`, which is inconsistent with our writing of `prescribed_velocity_boundary_indicators`. Fix that by excluding those cases from the replacement. Not sure why I did not notice this earlier.
Also there is one occurrence of `tracers` that was not properly replaced, because it was an open pull request at the time I applied the script to the repository.
> Fix and apply update source script

- CONTRIBUTING.md
- README.md
After reading through most of https://opensource.guide/ I made some more changes to our readme and contributing.md. Hopefully this will lower the barrier to contribute to ASPECT. One thing I am not sure about is the advice on including a code of conduct in the repository. I am not aware that we had much trouble in this regard so far, and I dislike playing by github's rules, just to get our last checkmark at https://github.com/geodynamics/aspect/community, but on the other hand it is not much of a pain, and might become useful. What do others think?
Please wait with merging this PR, I am currently waiting for a response from UC Davis IT staff as to how to search through our mailing list (if that is at all possible).
> Improve advice on contributing patches

- source/postprocess/geoid.cc
The default value for 'density below' was different in the dynamic topography postprocessor and the  geoid postprocessor but for consistency this should probably be the same value. I adapted the default density below in the geoid postprocessor to be the same as in the dynamic topography postprocessor.
> Make default value for 'density below' consistent across postprocessors

- include/aspect/particle/particle.h
- source/particle/particle.cc
This is the first step towards addressing the comments and discussions of dealii/dealii#4729 inside of ASPECT to then move parts of the particle implementation into deal.II
This PR allows for particles where dim != spacedim, which never happens in ASPECT.
> Instantiate particles for spacedim

- benchmarks/solcx/compositional_fields/solcx_compositional_fields.h
- benchmarks/solcx/compositional_fields/solcx_particles.prm
The density and viscosity values at each point were not being set to the values on their respective compositional fields in solcx_compositional_fields.h.  This is because SolCxCompostionalMaterial was outdated and needed to be updated.  As a result, we would always obtain the convergence results for the direct method regardless of the method being used in the Solcx parameter file.  
Currently, if a compositional field carries viscosity, then the convergence results are less accurate then that of the direct methods.  However, the convergence results for Solcx are exactly the same as the direct method if only density is carried on a compositional field.
> Fixed bug preventing particles from working in Solcx benchmark

- include/aspect/particle/particle_accessor.h
- include/aspect/particle/particle_iterator.h
- include/aspect/particle/world.h
- source/particle/particle_accessor.cc
- source/particle/particle_iterator.cc
- source/particle/world.cc
This PR is not  quite complete, but I would like to ask for a review by @bangerth to see if I got the concept right. I added `ParticleIterator` and `ParticleAccessor` classes and converted one of the direct uses inside of `World` to use the iterators to test they work. The intention is to convert all direct uses of particles into using the iterator class.
> Add particle iterator and accessor

- include/aspect/particle/particle.h
- source/particle/particle.cc
Fixes some doxygen warnings due to parameter renaming in #1885.
Closes #1888.
> Fix doxygen warnings

- README.md
- doc/manual/manual.tex
One of two steps towards #1879. These paragraphs have been moved to the wiki. This way it is easier for anybody to update them, and it is easier to link to them (and the manual does not get filled up with special case instructions).
In a follow-up PR I will move over the content of the `doc/install` directory (although that it pretty outdated).
> Move special installation instructions

- include/aspect/particle/particle.h
- include/aspect/particle/particle_accessor.h
- include/aspect/particle/particle_handler.h
- include/aspect/particle/particle_iterator.h
- include/aspect/particle/world.h
- include/aspect/simulator.h
- source/particle/particle_accessor.cc
- source/particle/particle_handler.cc
- source/particle/particle_iterator.cc
- source/particle/world.cc
This PR takes apart the `World` class. Everything specific to ASPECT remains in `World`, everything related to particle handling goes into `ParticleHandler`. So far `ParticleHandler` only contains the data structures and some simple functions. In follow-up PRs I will move functionality from `World` into `ParticleHandler` until `World` no longer needs to be friend of `ParticleHandler`. At that point `ParticleHandler` and the iterator and accessor classes can move into deal.II.
> Add ParticleHandler

- source/material_model/latent_heat.cc
- tests/latent_heat_composition.prm
- tests/latent_heat_composition/screen-output
This pull request addresses issue #1896, which was originally pointed out by Derek Neuharth (University of Idaho). Specifying the reaction terms in the latent heat material model fixes the assembly error when using compositional fields.
> Specify reaction terms in latent heat material model

- source/postprocess/visualization/melt.cc
In the beginning, we thought that the additional material model outputs used in models with melt transport (which are visualized by the Melt material properties visualization postprocessor) would not depend on the strain rate. However, it turned out that in more complex models, for example the compaction viscosity might depend on the strain rate. Because of that, we need the strain rate in the material model inputs that is used by the postprocessor. This issue is fixed in this pull request.
> give the strain rate to the melt properties visualization postprocessor

- doc/modules/changes/20170821_jdannberg
- include/aspect/material_model/interface.h
- source/heating_model/adiabatic_heating_of_melt.cc
- source/heating_model/shear_heating_with_melt.cc
- source/initial_composition/porosity.cc
- source/material_model/interface.cc
- source/material_model/melt_global.cc
- source/material_model/melt_simple.cc
- source/material_model/visco_plastic.cc
- source/postprocess/visualization/heating.cc
- source/postprocess/visualization/seismic_anomalies.cc
- source/simulator/assembly.cc
- source/simulator/entropy_viscosity.cc
- tests/cell_reference.cc
- tests/cell_reference/screen-output
- tests/drucker_prager_derivatives.cc
- tests/simple_nonlinear.cc
- tests/simple_shear.cc
This pull request adds an active cell iterator (instead of a reference to the active cell iterator, which was used before, and is now marked as deprecated) to the material model inputs structure, which allows the cell to be filled in the constructor of material model inputs that is used for the visualization postprocessors (using `get_cell<DoFHandler<dim>`). 
This is useful in cases where the material model uses the cell information to extract, for example, the old solution, or some additional solution variables that are not in the material model inputs, like in the case of melt transport, and the computes the material model outputs using this information. With this new version, visualization postprocessors will now also be able to output these quantities from material model outputs …
> allow visualization postprocessors to use the current cell

- source/simulator/solver.cc
This addresses one of the issues in #1912. 
Through patch dealii/dealii/pull/4870, `SolverControl ` now initializes the number of iterations as `numbers::invalid_unsigned_int`. This broke most (all?) of the tests as the number of printed cheap or expensive iterations was incorrect.
This is fixed by printing `0` if the number of stokes iterations is `numbers::invalid_unsigned_int`.
> Print 0 if solver_control returns an invalid unsigned integer for last_step

- source/simulator/parameters.cc
Avoids accidentally using a direct solver with nullspace removal
> Change nullspace removal Assert to AssertThrow

- AUTHORS
- CONTRIBUTING.md
This PR adds the new developers to the AUTHORS file and documents a bit what it means to be a developer. Let me know if you prefer a different formatting of the AUTHORS file.
> Add new developers

- source/initial_temperature/adiabatic.cc
This pull request fixes a problem that shows up if the `porosity` initial composition, the `adiabatic` initial temperature, and the `initial profile` adiabatic conditions are used together. They all need data from each other, so they called each other in a loop, which lead to a crash of ASPECT with an error message that was difficult to understand. This pull request fixes this particular problem in the way that the reference composition profile that is used to compute the adiabatic initial profile does not take into account boundary layers that might exist in the adiabatic initial temperature (so this is a very specific case, and it is only a problem if the initial composition depends on the initial temperature).
> fix for porosity initial composition plugin

- cookbooks/convection-box.prm
- doc/manual/cookbooks/convection-box/box.prm
- doc/manual/cookbooks/convection-box/gravity.part.prm
- doc/manual/manual.tex
This pull request updates the text of the convection box cookbook in the manual so that it fits what we do in the input file. Before, the 'playtime' sections in the manual didn't work any more, because they included wrong values for the Gravity that made the cookbook crash. In addition, the cookbook now correctly uses the Boussinesq formulation (which it should have done before already, as it has a value of 1 instead of 1e-10 for the thermal expansivity). So this should really be considered a bugfix. It addresses #1924.
> update convection box cookbook

- source/particle/particle_accessor.cc
- source/postprocess/particles.cc
I did not test #1929 for deal.II 9.0.pre. Turns out some code that is only included for 9.0pre does not compile :worried:. This PR fixes that.
I would appreciate if somebody could soon merge this, before too many people notice :smile:.
> Fix for deal 90 pre

- source/particle/output/hdf5.cc
@gassmoeller I noticed that I could not longer compile my code with the newest version of aspect and deal.ii with the following error message:
```
aspect/source/particle/output/hdf5.cc: In member function ‘virtual std::__cxx11::string aspect::Particle::Output::HDF5Output<dim>::output_particle_data(const aspect::Particle::ParticleHandler<dim>&, const aspect::Particle::Property::ParticlePropertyInformation&, double)’:
aspect/source/particle/output/hdf5.cc:296:16: error: ‘particles’ was not declared in this scope
(void) particles;
```
This patch makes it compile again. It seems like is a left over from the change in the interface, but since I am not really familiar with this code it might be not be the best fix.
> Fix particle hdf5 output compling on a machine which has no hdf5 installed

- include/aspect/boundary_temperature/interface.h
- source/boundary_temperature/dynamic_core.cc
- source/postprocess/core_statistics.cc
This PR fixes some compiler and deprecation warnings that were introduced in #1882. These fixes reveal a bug in `BoundaryTemperature::Manager::find_boundary_temperature_model` that was introduced by me in #1771. The bug was never discovered, because it was in a template function that was not instantiated until now. Fixed now.
> Fix some warnings and a bug

- source/simulator/core.cc
I noticed that I forgot to put this optimalisation into the newton solver. This saves a lot of runtime on bigger models on many mpi processes.
In contrast with the Picard type solver, which only needs to compute the constraints once, in the Newton solver, the first iteration and second iteration have different values because of the velocity boundary conditions. After the second iteration they stay the same, so we don't need to recompute.
> optimalisation of compute current constraints in the Newton solver.

- .gitignore
because this file is created on demand
> add doc/modules/changes.h to .gitignore

- doc/update_parameters.sh
move the temporary plugin_graph files instead of copying them so we
don't have them sit there in the main directory.
> move plugin_graph files

- include/aspect/particle/particle_handler.h
- include/aspect/particle/world.h
- source/particle/particle_handler.cc
- source/particle/world.cc
This moves most of the particle serialization functionality into the ParticleHandler class. Some parts remain in World for now, I will address them in a follow-up PR.
> Move particle serialization into ParticleHandler

- source/geometry_model/ellipsoidal_chunk.cc
> Remove assert because initial topo is incorporated into pull_back(point)

- source/postprocess/visualization.cc
Something I noticed while working on #1864. 
The hdf5 filter tries to merge duplicate vertices at the same location to reduce the necessary disk space. However, for discontinuous elements this means averaging the values at the element boundary, something that is often not intended. Even worse: The merge does not always work, because the check in deal II does not take into account floating point imprecision in the vertex position, I am opening a separate issue for that. The consequence is that during mesh refinement, even if the mesh does not change and the solution stays the same, the internal position of the vertices can be changed slighty, and the filter will create a different output field, suggesting a change that does not exist. This behavior is not a problem for continuous elements …
> Only filter hdf5 output for continuous elements

- doc/manual/manual.tex
If someone only reads the online version of the manual, the link in the manual to the CONTRIBUTING.md file will not work for them, because it points to the file in the local aspect folder. This pull request adds a link to the file on the github website.
> add a link to the online version of CONTRIBUTING.md in the manual

- source/simulator/assemblers/newton_stokes.cc
In general, writing large amounts of data directly rarely leads to good
things, in particular if the program is running parallel. Instead, just
abort the program -- one has to start a debugger anyway.
This is a follow-up to #1939. @mfraters?
> Simplify error reporting.

- source/simulator/core.cc
- source/simulator/helper_functions.cc
- source/simulator/solver_schemes.cc
- tests/annulus/screen-output
- tests/burstedde/screen-output
- tests/burstedde_stokes_rhs/screen-output
- tests/composition_reaction_iterated_IMPES/screen-output
- tests/compressibility_iterated_stokes/screen-output
- tests/hollow_sphere/screen-output
- tests/material_model_dependencies_burstedde/screen-output
- tests/no_adiabatic_heating/screen-output
- tests/no_adiabatic_heating_02/screen-output
- tests/simple_compressibility_iterated_stokes/screen-output
- tests/tangurnis_tala_implicit/screen-output
Follow up to #1850 that unifies the condition under which we rebuild the Stokes matrix and preconditioner. I have a technical question here:
The current solver schemes had three different conditions for when to rebuild:
1. Only rebuild in every nonlinear iteration if stokes matrix depends on solution
2. Rebuild if stokes matrix depends on solution or there are prescribed velocity BCs
3. Rebuild if stokes matrix depends on solution or (we are in the first iteration and there are prescribed velocity BCs)
Which of these is correct? My understanding was that the prescribed velocity BCs end up in the constraints matrix, which is applied after the matrix is assembled. Thus, if neither matrix nor constraints change in subsequent iterations there should be no need to reassemble matrix or …
> Unify rebuild of stokes matrix

- source/boundary_temperature/dynamic_core.cc
- source/heating_model/compositional_heating.cc
- tests/dynamic_core.prm
prm names with underscores are not our style and break the manual (names
need to be escaped, but not in the index keys).
Also some other minor changes.
> parameter names without underscores

- include/aspect/geometry_model/sphere.h
- source/geometry_model/sphere.cc
This primarily fixes a deprecation warning with deal.II 9.0.pre.
Note that I do not set the manifold ids for all cells yet. The reason is that the resulting mesh looks strange, and I wanted an opinion on that. The figure below shows from left to right the mesh with 8.5.0, the mesh with 9.0.pre with this PR (no difference), and the mesh with 9.0.pre with the spherical manifold attached to all cells. The mesh on the right has some pretty distorted cells. Is there some best practice for how to prescribe manifolds to this case?
> Fix deprecation warning

- source/postprocess/stokes_residual.cc
This closes the remaining issue in #1912. The solver_history test should now work correctly with deal.II 9.0.pre.
> Fix solver history for deal.II-dev

- source/geometry_model/initial_topography_model/ascii_data.cc
I just wrote an ascii initial topography file just to find out (at runtime) that it's not supported by all geometry models. I feel like it should be mentioned in the manual.
> Specify supported geometry models for ascii initial topography

- include/aspect/geometry_model/sphere.h
Adding `#include <deal.II/grid/manifold_lib.h>` to` include/aspect/geometry_model/sphere.h` enables ASPECT to compile correctly when using the development version of deal.II. Thanks to @bangerth for pointing out the fix in #1912.
> Include access to dealii manifold_lib in sphere.h

- source/utilities.cc
The "WARNING: Filename convention concerning geometry boundary names changed..." message was printing three times on every processor. Now it should only print once for each offending filename.
> make boundary filename convention warning print once per file

- tests/CMakeLists.txt
- tests/cmake/diff_test.sh
Only perform normalization of output files if we actually look at the results. This fixes the last remaining test failures for deal.II-dev with ASPECT_COMPARE_TEST_RESULTS=OFF. 
This PR makes some of the earlier changes in #1973 unnecessary, because we now only call `tests/cmake/diff_test.sh` if we want to compare the results. Should I revert the now unnecessary changes to that file?
> Do not look at output if ASPECT_COMPARE_TEST_RESULTS=OFF

- include/aspect/melt.h
- include/aspect/newton.h
- include/aspect/simulator.h
- include/aspect/simulator_access.h
- source/simulator/assembly.cc
- source/simulator/core.cc
- source/simulator/melt.cc
- source/simulator/newton.cc
- source/simulator/simulator_access.cc
This is on top of #1785 and simplifies `set_assemblers` by outsorcing many parts into the melt handler and newton handler classes.
> Refactor set_assemblers into separate functions

- source/simulator/parameters.cc
> Update documentation of a parameter.

- source/main.cc
- source/simulator/core.cc
- tests/fail/screen-output
- tests/steinberger_lateral_fail/screen-output
- tests/visualization_unique_list/screen-output
- tests/zero_matrix/screen-output
If an exception is thrown, we will call the TimerOutput destructor,
which will exit subsections and in turn call Timer functions that
trigger MPI communication. This can a) hang if only some processors
throw, or b) report incorrect messages (about Trilinos compress()).
Avoid this problem (at least in c++11 or newer), by reporting the
exception and then aborting before the destructor is executed.
> avoid deadlock when exception is thrown

- source/simulator/core.cc
So far we do not initialize `Simulator::nonlinear_iteration`, but it would be nice to be able to check against a specific value (e.g. in my particular application to test in a signal if we are in the process of setting up initial conditions, or within the nonlinear solver loop of the first timestep).
> Initialize nonlinear iteration count

- .gitignore
- benchmarks/inclusion/adaptive.prm.base
- benchmarks/inclusion/global.prm.base
The graphical output for the inclusion benchmark were set to "Use years
in output instead of seconds" which doesn't make much sense for a
problem on a unit square. The computed errors are independent of this
change.
> inclusion benchmarks: use seconds not years

- CMakeLists.txt
- doc/manual/manual.tex
- doc/modules/changes/20171212_gassmoeller
- include/aspect/global.h
- include/aspect/revision.h.in
- source/global.cc
As mentioned in the changelog entry. This change will only require a rerun of cmake and a recompilation of global.cc if the git HEAD changes, no full recompilation required. I several times wished I had this output for old models.
+1 for reproducibility of old models.
> Include more version information in header

- jabref-template/listrefs.layout
The patch disentangles the formatting used in the file (without any actual change other than making it more readable what is happening here).
The only change is adding a `<br>` at the end of each entry. That's because https://aspect.geodynamics.org/publications.html just looks a bit unkempt between entries -- the text would be easier to read if there was more space between entries.
I don't know how this new formatting is going to work out, but thought I'd give it a shot. I may tweak it some further later on.
> Try something with the format for references.

- doc/modules/changes/20171222_tjhei
- source/simulator/core.cc
- tests/matrix_nonzeros_1/screen-output
- tests/matrix_nonzeros_2/screen-output
- tests/matrix_nonzeros_3/screen-output
- tests/pressure_constraint/screen-output
The system_preconditioner_matrix is only used for the Stokes system, so
there is no need to allocate entries for temperature/composition. Fix
this.
> Fix: Do not allocate unnecessary preconditioner matrix blocks

- include/aspect/simulator.h
- source/simulator/assembly.cc
- source/simulator/solver.cc
The advection (temperature and composition) preconditioner is always re-
initialized before using it, so keeping them around afterwards is not
necessary. This should also save some memory.
> Simplify advection preconditioner lifetime

- source/global.cc
A deal.II release has a commit ID, but no branch information in revision.h. In this case currently we output a strange string `(, commitID)`. 
Do not output anything about ID or branch in this case, because a release version is unique already (I could have fixed if with more complicated logic about which of the two is present, but this seems easier, and provides the same information.
One problem I just noticed while testing this patch is that we use a deal.II cmake macro to generate Aspect's version information. That means if we use a deal.II installation (not a build folder) we can not use that script (cmake scripts are not installed), and even if git is available we have no version information for aspect. Is it possible to find the source or build folder for an installation (if those …
> Fix version if using deal.II release

- CMakeLists.txt
- cmake/macro_aspect_query_git_information.cmake
See #2047. This script allows us to query the git information of ASPECT, even if we use a deal.II installation that does not contain this script. I checked that the script works as intended with a deal.II installation.
> Copy git version macro from deal.II

- doc/modules/changes/20180105_gassmoeller
- include/aspect/boundary_velocity/interface.h
- include/aspect/parameters.h
- include/aspect/simulator.h
- include/aspect/simulator_access.h
- source/boundary_velocity/ascii_data.cc
- source/boundary_velocity/interface.cc
- source/simulator/core.cc
- source/simulator/free_surface.cc
- source/simulator/helper_functions.cc
- source/simulator/parameters.cc
- source/simulator/simulator_access.cc
- source/simulator/solver_schemes.cc
- tests/ascii_data_boundary_velocity_2d_box_list.prm
- tests/ascii_data_boundary_velocity_2d_box_list/screen-output
- tests/ascii_data_boundary_velocity_2d_box_list/statistics
Same as #2043, but for velocity plugins. This one is much more complicated, because we already allow different velocity plugins for different boundaries, and there is the additional complication of component selectors. I need to clean the code one more time before a proper review, but there are a few design decisions I would like to hear an opinion about:
1. Long term I would like to move all input parameters like "Prescribed velocity boundary indicators" from the generic "Model settings" subsection into the more appropriate "Boundary velocity model" subsection (same for temperature, composition, and so on). This is why I created a new "List of model names" parameter in the boundary velocity subsection. I feel this is easier to understand, also this would logically mean the Simulator …
> Create boundary velocity manager

- jabref-template/listrefs.layout
In particular, avoid white space in the details of a publication. For examples, take a look at each of the ones here:
https://aspect.geodynamics.org/publications.html
> Fix formatting

- include/aspect/parameters.h
- source/simulator/helper_functions.cc
- source/simulator/parameters.cc
This pull requests adds the possiblity to set a percentage with which the the time step is limited to increase. Generally the time step based on the CFL number should be sufficient, but for complicated models which may suddenly drastically change behavoir, it may be usefull to limit the increase in the timestep, without limiting the time step size of the whole simulation to a particular number.
> Add limiting timestep increase function.

- doc/modules/changes/20180116_gassmoeller
- source/material_model/steinberger.cc
These limits were introduced at a time when I wanted to stabilize things, but they fooled us for a day thinking our model was wrong, and they are bad for at least two reasons:
1. They give wrong results instead of crashing when things go wrong.
2. Their numbers are arbitrary, at least they would need to be input parameters.
I think it is best to remove them, bad things should happen when these get unreasonable, and it is not possible to provide bounds for what "unreasonable" means.
> Remove arbitrary limits in Steinberger material model

- source/simulator/solver_schemes.cc
- tests/global_melt_parallel.prm
- tests/global_melt_parallel/screen-output
- tests/global_melt_parallel/statistics
Apparently, we had no test for parallel melt models, because parallel melt transport was likely broken since #1850. Should be fixed now though.
> Fix melt in parallel computations

- cookbooks/inner_core_convection/inner_core_convection.cc
This is the first one of (hopefully) a series of pull requests that will extend the inner core cookbook, adding a number of new features to it. Once we have all of the new functionality, we will also modify the cookbook text and add an input file that demonstrates how to use these new features. 
This pull request adds the option to include a phase transition with variable depth/width/Clapyeron slope/etc. in the model, similarly to the latent heat material model, just much simpler.
> add a phase transition to the inner core material model

- doc/update_prm_files_to_2.0.0.sed
- doc/update_source_files_to_2.0.0.sed
It looks like `\<` and `\>` (beginning or end of word) are GNU extensions to sed, and not available on Mac, while `\b` (boundary of word) is available. Thus this change should fix #1857. I was able to verify that this does not break anything on my Ubuntu, and at least one Mac I had available for testing (thanks @MarineLasbleis :smile:) seems to work.
> Fix Mac sed commands in update scripts

- include/aspect/material_model/visco_plastic.h
- source/material_model/visco_plastic.cc
- tests/visco_plastic_complex.prm
- tests/visco_plastic_complex/screen-output
@naliboff Maybe I misunderstand, but at the moment, the stress_limiter option does not seem to take into account the pre_yield_viscosity. From the papers cited in the plugin description, I gathered, usually the viscosity_pre_yield and the viscosity_limiter are averaged, so I added that in. Or would you rather keep the min(viscosity_pre_yield, viscosity_limiter) that was commented out?
> Average stress limiter and pre yield viscosity

- include/aspect/simulator.h
- source/simulator/solver.cc
While there, also use an empty line to better delineate two parts of a
comment.
@mfraters: this is what we talked about last week. Can you take a look?
I didn't update comments in the solve_stokes() function itself so as not to
step onto the changes you make in #2070.
> Update documentation of Simulator::solve_stokes().

- source/simulator/solver.cc
Based on a discussion in #2006. When the expensive linear sovler crashes, the section `   Solve Stokes system` is never exited. This can cause problems for the failsafe in #2006. I am just not sure what happens with this solution when the cheap solver fails with anything else then a non-convergence.
> add the exit timer in the linear solver catch

- include/aspect/newton.h
- include/aspect/parameters.h
- source/simulator/assemblers/newton_stokes.cc
- source/simulator/core.cc
- source/simulator/helper_functions.cc
- source/simulator/newton.cc
- source/simulator/parameters.cc
- source/simulator/solver_schemes.cc
- tests/nonlinear_channel_flow_tractions_Newton_Stokes/screen-output
- tests/nonlinear_channel_flow_velocities_Newton_Stokes/screen-output
This is something which I have been working on and with for a while now, and since #1996 is (hopefully) nearly merged, it seems me like a good time to discuss this now. This pull request actually add two features at the same time, because they used to be intertwined, but I untangled them just before this pull request. If you want I can make two pull requests from this one.
The first feature is that it will  now be possible to chose whether to use the stabilisation or not (and which of the two) for both the preconditioner and the A block. 
My tests with the Spiegelman benchmark (I only tested with preconditioner being `SPD`) seem to indicate that if the solver doesn't fail, the convergence rate is by far the best if you only symmetrise the the A block (`symmetric`), then much closer …
> Split newton stabilisation as options and add a failsafe

- source/material_model/melt_global.cc
- source/material_model/melt_simple.cc
- source/simulator/helper_functions.cc
- tests/heat_advection_by_melt_operator_splitting.cc
- tests/heat_advection_by_melt_operator_splitting.prm
- tests/heat_advection_by_melt_operator_splitting/screen-output
- tests/heat_advection_by_melt_operator_splitting/statistics
Due to some missing lines in the operator splitting routine, heating models did not get additional material model outputs (like melt outputs) and so any heating model that requires these outputs did not work with operator splitting. 
In addition, if melt transport was switched off, the reaction rate outputs were not filled correctly in the melt material models, and so they could not be used together with operator splitting. 
This pull request fixes both issues.
> [Bugfix] Make models that use melt heating models work with operator splitting

- doc/modules/changes/20180212_jdannberg
- include/aspect/mesh_refinement/compaction_length.h
- source/mesh_refinement/compaction_length.cc
- source/mesh_refinement/density.cc
- tests/compaction_length_refinement.prm
- tests/compaction_length_refinement/screen-output
- tests/compaction_length_refinement/statistics
This is useful in models with melt transport, as the compaction length is a typical length scale for these models.
> Add a mesh refinement criterion based on the compaction length

- include/aspect/newton.h
- source/simulator/assemblers/newton_stokes.cc
- source/simulator/core.cc
- source/simulator/newton.cc
- source/simulator/parameters.cc
- source/simulator/solver_schemes.cc
This is the first part of what I want to do for #2083. This
patch does not remove the many getter/setter functions for
all of the parameters, but that will come next. One step
at a time.
> Break the runtime parameters out of the NewtonHandler class.

- include/aspect/simulator.h
- source/simulator/helper_functions.cc
- source/simulator/solver.cc
- source/simulator/solver_schemes.cc
Previously, solve_stokes() returned something in some contexts, and something else in others.
Make this more uniform by just returning a pair of values.
While there, also adjust some naming of variables to indicate that they refer to
*nonlinear* residuals.
Fixes #2082.
> Let solve_stokes() return something more uniform.

- source/simulator/simulator_signals.cc
remove:
```
simulator_signals.cc:110:22: warning: explicit instantiation of
'call_connector_functions<2>' that occurs after an explicit
specialization has no effect [-Winstantiation-after-specialization]
```
> avoid clang warning

- include/aspect/utilities.h
- source/material_model/visco_plastic.cc
- source/utilities.cc
- tests/visco_plastic_derivatives.cc
- tests/visco_plastic_derivatives.prm
- tests/visco_plastic_derivatives/screen-output
Adding finite difference derivatives to the visco-plastic material model, so it can be used with the Newton solver. With this finite difference model, it should be relatively easy to add derivatives to other material models. 
The finite difference could actually be done somewhere higher up or abstracted into a single function.
> Add derivatives to visco plastic material model

- doc/modules/changes/20180220_jdannberg
- source/simulator/helper_functions.cc
This is something that annoyed me several times now: If a model has a zero velocity (either because that is the prescribed Stokes solution, or just because nothing is moving), the time step size is arbitrarily set to 1s. This doesn't make any sense, in particular as we have a parameter that allows the user to set a maximum time step. But because that setting of the time step size to 1 occurs before we apply the maximum time step, the maximum time step parameter is essentially not used in case of zero velocity, because 1s is pretty much always smaller than what you want to use as your maximum time step. 
I suggest that instead of setting the time step size to 1, it should just be set to the maximum time step (which is there for exactly that purpose).
> fix time step size for zero velocity

- source/simulator/assemblers/newton_stokes.cc
This pull request optimizes the defect correction Picard scheme in the Newton solver code. It does it by only adding the derivatives as additional output when they are actually needed.
> only ask for the derivatives when actually needed.

- source/simulator/newton.cc
This is a follow-up to #2108. @mfraters: In order to get a backslash into the output,
you need to write two backslashes in the C++ code.
> Fix a LaTeX markup problem.

- doc/modules/changes/20180311_gassmoeller
- source/simulator/core.cc
Following a discussion on the mailing list with @MarineLasbleis this writes a machine readable JSON version of the parameter file to the output directory.
> Add a machine readable JSON file for parameters

- include/aspect/initial_temperature/S40RTS_perturbation.h
- include/aspect/initial_temperature/SAVANI_perturbation.h
- source/initial_temperature/S40RTS_perturbation.cc
- source/initial_temperature/SAVANI_perturbation.cc
Finally fix #962. Something I wanted to do for a long time (waiting time at an airport is so useful :smile:). Both plugins show a ~15X speedup with the changes in the first commit. They are still a big part of an instantaneous model (~50% for the tests, compared to 90% before), but at least they are now comparable to a Stokes solve, which should be good enough. The second commit adjusts the code style to our usual convention and uses more correct types for many indices.
@jaustermann or @Shangxin-Liu maybe one of you could take look and do a review of this PR, since you wrote the initial code? Did I mess anything up?
> Optimize seismic ic

- source/simulator/helper_functions.cc
- tests/initial_condition_S20RTS_dgp.prm
- tests/initial_condition_S20RTS_dgp/screen-output
- tests/initial_condition_S20RTS_dgp/statistics
With deal.II 9.0 (but not 8.5) I trigger the following assert in `normalize_pressure` and `denormalize_pressure`. This fix changes the access to the vector to the same operations we already do for the continuous pressure case. I am not sure why this was not found by our tests, or what has changed in deal.II to cause this. I vaguely remember some changes to prevent a bug in the distributed vector, but can not find the discussion. Does anyone remember?
```
--------------------------------------------------------
An error occurred in line <545> of file </home/rengas/Software/dealii/source/lac/trilinos_vector.cc> in function
void dealii::TrilinosWrappers::MPI::Vector::compress(dealii::VectorOperation::values)
The violated condition was: 
((last_action == Add) && …
```
> Fix pressure normalization for DGP element with deal.II 9.0

- source/material_model/averaging.cc
This fixes a fallthrough warning I received with a current deal.II master and gcc 7.2
> Silence warning

- doc/modules/changes/20180321_gassmoeller
- include/aspect/lateral_averaging.h
- include/aspect/postprocess/depth_average.h
- source/postprocess/depth_average.cc
- source/simulator/lateral_averaging.cc
- tests/depth_average_underres/screen-output
- tests/steinberger_lateral_fail/screen-output
This began as a small optimization project and ended up as nearly complete rewrite of the lateral averaging functionality. All external interfaces are kept, and all functionality should work as before, but by reducing duplication the depth average postprocessor is now nearly ten times faster than before. Instead of n loops over all cells for n properties, lateral averaging now performs 1 loop for n properties (by providing n functors that are all executed for each cell). The `compute_average` function no longer takes a `FUNCTOR` template argument, but instead each functor is derived from a common base class, which makes creating a vector of functors much simpler. I am quite happy with the current state so I would like to ask for a review. In particular I would like to ask for comments …
> Speed up depth average postprocessor

- source/postprocess/visualization/named_additional_outputs.cc
The 'named additional outputs' postprocessor offers only a cryptic error message if no named outputs are provided by the material model. Make this check more clear and immediately crash at model start.
> Add error messages

- include/aspect/plugins.h
- include/aspect/postprocess/interface.h
- include/aspect/simulator_access.h
- include/aspect/utilities.h
- source/boundary_temperature/dynamic_core.cc
- source/gravity_model/radial.cc
- source/simulator/simulator_access.cc
- tests/find_postprocess.cc
- tests/find_postprocess/screen-output
- tests/find_postprocess_fail_1.cc
- tests/find_postprocess_fail_1.prm
- tests/find_postprocess_fail_1/screen-output
- tests/find_postprocess_fail_2.cc
- tests/find_postprocess_fail_2.prm
- tests/find_postprocess_fail_2/screen-output
One of the features of ASPECT I understood the least in the beginning was the use of `dynamic_cast` to determine the actual type of an interface plugin pointer. This is a proposal to make this more explicit and easier to understand. There are two main advantages to the new functions:
- No `dynamic_cast` that confuses users, instead function names that describe what is done
- No use of null pointers anymore. Therefore, nobody can forget to check for a null pointer before using the object. Always return references.
If this is something that we would like to do, there are dozens of places over the whole codebase which can be simplified with the new functions.
Comments?
> Introduce conversion functions for plugins

- benchmarks/spiegelman_et_al_2016_gcubed/spiegelman_material.cc
- tests/spiegelman_material.cc
- tests/spiegelman_material.prm
- tests/spiegelman_material/screen-output
I am not sure whether this should be merged in the end, since it is only a test of a material only used for a benchmark, but since @bangerth and I wanted to make sure that the derivatives of the benchmark material are working correctly I added this test.
The tests show that in general the derivatives are in agreement, but only with very low strain-rates they become different. As I commented in the code, the differences disappear when larger and fully divergence free strain-rate tensor is used.
> Add spiegelman benchmark material test.

- source/boundary_fluid_pressure/density.cc
- tests/average_density_boundary_fluid_pressure.prm
- tests/average_density_boundary_fluid_pressure/screen-output
- tests/average_density_boundary_fluid_pressure/statistics
I don't know how we missed that in the melt solver pull request, but apparently in my rebase some lines got messed up and the new "average density" option for the boundary fluid pressure did not work. This pull request fixes this and also adds a test.
> [bugfix] fix average density implementation for boundary fluid pressure

- include/aspect/simulator.h
- source/simulator/core.cc
- source/simulator/helper_functions.cc
I am trying to work on something else, but this just keeps getting in the way and producing subtle bugs (and I think it was broken before already, because the velocity boundary ids are used for a check, before the velocity boundary manager has parsed its parameters). It also makes reading the constructor of Simulator a pain. It should really be a helper function. Btw, the Asserts I removed in core.cc are superfluous, that is why I did not bother to reimplement them: If we ask the boundary temperature manager for boundary ids on which boundary conditions are active it is the manager's responsibility to make sure the returned values are really boundary ids from the current geometry, not the responsibility of the calling function.
> Clean Simulator::Simulator()

- cmake/compile_and_update_tests.sh
- cmake/generate_reference_output.sh
- doc/manual/manual.tex
This is related to #2143 and allows everybody to run the official ASPECT tester setup (currently only `aspect-8.5-gcc-hd`) on their local machine. This is super helpful if you know the tester is busy, or to check and update test results yourself if you are offline. It also allows with a little hack to `generate_reference_output` to only run certain tests you are interested in. This is a step towards having all the tester information as part of the official repository.
> Allow to run official ASPECT tester at home

- doc/modules/changes/20180322_gassmoeller
- include/aspect/material_model/interface.h
- source/heating_model/shear_heating.cc
- source/material_model/interface.cc
- source/simulator/assemblers/newton_stokes.cc
- source/simulator/assemblers/stokes.cc
- source/simulator/melt.cc
- tests/anisotropic_viscosity.cc
- tests/anisotropic_viscosity.prm
- tests/anisotropic_viscosity/statistics
It does not seem as if the anisotropic viscosity is used in practical applications a lot. On the other hand we now have all the infrastructure to remove it from the main assemblers, and restrict its use to the models that actually need it. The only model that uses it so far is our test/anisotropic viscosity (and we have no normal material model that supports it, only the plugin for anisotropic viscosity).
I did this mostly to clean up the code of the assemblers, but it turns out that the performance influence was bigger than expected. The change speeds up the assembly of the Stokes system and the preconditioner by about 25% in terms of instructions measured by callgrind (in 3d, optimized mode, using the geoid.prm test as reference). I am not sure why, but in the example we save about 10 …
> Remove anisotropic viscosity from main code (move to tests)

- include/aspect/coordinate_systems.h
- include/aspect/geometry_model/box.h
- include/aspect/geometry_model/chunk.h
- include/aspect/geometry_model/ellipsoidal_chunk.h
- include/aspect/geometry_model/interface.h
- include/aspect/geometry_model/sphere.h
- include/aspect/geometry_model/spherical_shell.h
- include/aspect/geometry_model/two_merged_boxes.h
- include/aspect/utilities.h
- source/geometry_model/box.cc
- source/geometry_model/chunk.cc
- source/geometry_model/ellipsoidal_chunk.cc
- source/geometry_model/sphere.cc
- source/geometry_model/spherical_shell.cc
- source/geometry_model/two_merged_boxes.cc
- source/utilities.cc
- tests/natural_coordinates_conversion.cc
- tests/natural_coordinates_conversion.prm
- tests/natural_coordinates_conversion/screen-output
This implements the cartesian_to_natural_coordinates and natural_to_cartesian_coordinates functions for the box, two_merged_boxes, chunk and ellipsoidal chunk geometry models. These where the easy ones since they where or just the original input, or I could use their manifold of the geometry model itself. 
I will add a test for these functions later.
> Add support for natural coordinates to geometry models

- doc/update_prm_files_to_2.0.0.sed
- tests/update_script_2.cc
- tests/update_script_2.prm
- tests/update_script_2/screen-output
- tests/update_script_2/statistics
- tests/update_script_2/updated2.prm
Since #2152 there was an ugly bug in the update_prm script that repeatedly added lines if the script was applied more than once and the `radial linear` gravity profile subsection existed in the parameter file. The fix is some ugly sed-magic, but I also added a new test that checks this behavior. The test essentially copies the first update script test, but applies the script twice. I checked that the test fails, if one of the following happens:
- diff reports a difference in the parameter file between the first and second application of the update script
- aspect can not run the twice updated version of the parameter file
- updated2.prm (the twice updated version) differs from the stored reference version in the test output
> Fix update script and add test

- doc/manual/manual.tex
- doc/modules/changes/20180420_gassmoeller
- doc/update_all_files.sh
- doc/update_prm_files.sh
- doc/update_scripts/prm_files/update_prm_files_to_2.0.0.sed
- doc/update_scripts/source_files/update_source_files_to_2.0.0.sed
- doc/update_source_files.sh
- tests/update_script.cc
- tests/update_script/screen-output
- tests/update_script_2.cc
- tests/update_script_2/screen-output
This will make #2157 and #2163 simpler to merge, and also improves the organization of the update scripts. Currently, the update script is one sed-script that tries to update everything. Unfortunately, sed was a bad choice by me for this type of operation, because it has only one hold space, and its syntax is very hard to understand. With the new organization (one shell script in doc/ that calls all existing scripts in a subfolder), it will be simpler to add future changes in whatever language we prefer, and it prevents conflicts between different renaming operations. I also added more documentation to the manual, and made the application of the update script safer, by always generating backup files with the ending .bak. I also added a changelog entry.
> Reorganize update scripts

- tests/ellipsoidal_chunk_geometry.cc
- tests/ellipsoidal_chunk_geometry.prm
- tests/ellipsoidal_chunk_geometry/screen-output
This closes  #1950. While the manifold conversion can produce significant errors very close to the center (e.g. 10% at a distance of 50 km from the center as mentioned in #1950), it is already negligible at the inner-core boundary (1e-7 at 1000km radius), and completely insignificant at the CMB (5e-11 at 2890 km depth).
> Add test for ellipsoidal chunk manifold conversion

- cookbooks/global_melt.prm
Closes #2179. It was only this cookbook (I checked cookbooks, benchmarks, and files in doc/), and the parameter existed in the main code for less than two weeks, so I do not think there is a need for an inclusion into the update script.
> Fix remaining cookbook that uses p_c in the input file

- source/geometry_model/ellipsoidal_chunk.cc
fixes
```
source/geometry_model/ellipsoidal_chunk.cc:781:61: warning:
dereferencing type-punned pointer will break strict-aliasing rules
[-Wstrict-aliasing]
```
> fix warning in ellipsoidal chunk

- doc/modules/changes/20180430_naliboff
- source/material_model/diffusion_dislocation.cc
- source/material_model/visco_plastic.cc
- tests/diffusion_dislocation_reference_density_profile.prm
- tests/diffusion_dislocation_reference_density_profile/screen-output
- tests/diffusion_dislocation_reference_density_profile/statistics
- tests/visco_plastic_reference_density_profile.prm
- tests/visco_plastic_reference_density_profile/screen-output
Follow up to #2170. It turns out none of the `diffusion_dislocation` or `visco_plastic` tests use the `reference density profile` formulation for the temperature equation (I have no idea why I assumed they did .. careless error). 
As previously written, the two material models did not check whether adiabatic conditions are initialized before asking for the density from `adiabatic_conditions`. This is now fixed and I've added tests that use `reference density profile` in both material models. I also checked that the other changes (`basic statistics` & `thermal diffusivity` post processors) in #2170 work with `reference density profile`, but did not add any associated tests.
> Fix visco_plastic and diffusion_dislocation thermal diffusivity

- source/global.cc
Adds to #2195 and #2196 a note to the header of the model output. I am aware we do not want to put too much into the header, but this seems like an important enough notice that many might forget otherwise.
> Add citation info to header

- source/simulator/nullspace.cc
When I read through this part, the inverse sign in this comment seems redundant because the left side is angular momentum and the right side is moment of inertial times angular velocity (\omega)?
> A redundant inverse sign in the comment here?

- include/aspect/lateral_averaging.h
- source/simulator/lateral_averaging.cc
fixes clang 6 warning:
```
/usr/lib/gcc/x86_64-linux-
gnu/4.8/../../../../include/c++/4.8/bits/unique_ptr.h:67:2: warning:
delete called on 'aspect::internal::FunctorBase<2>' that is abstract but
has non-virtual destructor [-Wdelete-non-virtual-dtor]
```
> provide base class to fix warning

- include/aspect/boundary_traction/interface.h
- include/aspect/heating_model/interface.h
- include/aspect/particle/interpolator/interface.h
- include/aspect/particle/property/interface.h
- include/aspect/postprocess/interface.h
- include/aspect/simulator_access.h
Fixes errors like:
```
../include/aspect/simulator_access.h:762:35: error: 'deprecated'
attribute cannot be applied to types
find_postprocessor () const DEAL_II_DEPRECATED;
```
> clang 6 requires deprecation attribute in front

- doc/modules/changes/20180503_gassmoeller
- source/simulator/nullspace.cc
This is the fix for the bug described in #2198. I am working on a test and postprocessor for the rotation properties, but it is more complicated than I expected, since I need to find a case where it matters (I will open a separate pull request for that). Since @Shangxin-Liu @ian-r-rose and I agree this is a bug, we should get this merged before the release (even if the test has to wait).
> Fix nullspace removal

- benchmarks/operator_splitting/advection_reaction/advection_reaction.cc
- benchmarks/operator_splitting/exponential_decay/exponential_decay.cc
- benchmarks/solcx/solcx.h
- benchmarks/solitary_wave/solitary_wave.cc
- benchmarks/solkz/solkz.h
- tests/melt_force_vector.cc
- tests/melt_transport_adaptive.cc
This triggers an assert with deal.II 9.0, I guess because of a newly intoduced assert. Anyway, it is clearly a bug.
> Fix wrongly defined analytic function

- source/simulator/helper_functions.cc
For some reason this does not trigger in deal.II 8.5, but it does in 9.0. Maybe we got more accurate and that is why one of the denominators now is zero. Anyway this fixes it and also makes the style a bit more uniform.
> Prevent division by zero in bound preserving limiter

- source/material_model/drucker_prager.cc
- tests/drucker_prager_derivatives.cc
- tests/drucker_prager_derivatives/screen-output
Found this bug when I looking at the equations to make a analytical solution for the visco-plastic derivatives. I have extended the test to now also test the 3d implementation and fixed the bug (as the test shows). I will now also look at and update the other derivative tests.
> fix drucker prager 3d derivatives and extend test to catch this in the future.

- source/utilities.cc
I was looking into #2210 and #2211 and found this instead. We do not close the directory handle for the output directory, if the directory already exists. Valgrind reports this as a resource leak (which is correct).
> Close output directory handle

- include/aspect/utilities.h
- source/utilities.cc
- tests/adiabatic_boundary/screen-output
- tests/ascii_data_nonuniform_initial_composition_2d_box/screen-output
- tests/dynamic_core/screen-output
- tests/geometric_average_crash/screen-output
- tests/gravity_prem/screen-output
- tests/initial_condition_S20RTS/screen-output
- tests/initial_condition_S20RTS_dgp/screen-output
- tests/initial_condition_S40RTS/screen-output
- tests/initial_condition_SAVANI/screen-output
- tests/material_model_dependencies_steinberger/screen-output
- tests/passive_comp/screen-output
- tests/radioactive_decay/screen-output
- tests/solidus_initial_conditions/screen-output
- tests/topo_shell/screen-output
Closes #2217. Is this what you thought about @tjhei? I agree that this message is confusing (since everything works even if the coordinates are non-equidistant). So it is more an info message than a warning. I can see that somebody might want to check though (i.e. to see if a data file was prepared correctly) that is why I introduced the get function. This might break test output.
> Remove info message

- CMakeLists.txt
Title says it all. As described in #2211 clang6 passes our test for floating point exceptions during running cmake, but triggers floating point exceptions during runtime.
> Disable floating point exceptions for clang6

- tests/drucker_prager_derivatives.cc
- tests/drucker_prager_derivatives/screen-output
- tests/simple_nonlinear.cc
- tests/simple_nonlinear/screen-output
- tests/visco_plastic_derivatives_2d.cc
- tests/visco_plastic_derivatives_2d/screen-output
- tests/visco_plastic_derivatives_3d.cc
- tests/visco_plastic_derivatives_3d/screen-output
This is a large restructuring of the derivatives tests. This makes them cleaner, shorter, more uniform and better documented :)
The 2d values should be the same as before, but the order in which they appear is different. The 3d cases now use full 3d strain-rate tensors.
> Restructure derivative tests

- source/material_model/visco_plastic.cc
- tests/visco_plastic_yield_strain_weakening.prm
- tests/visco_plastic_yield_strain_weakening/screen-output
- tests/visco_plastic_yield_strain_weakening/statistics
The visco plastic material model throws floating point exceptions when used with strain weakening, because it assumes to always get a strain rate, which is not the case. This was not covered by the existing test, because the test only solves the first timestep (for which strain weakening is explicitly disabled). The fix is simple, and might be important enough to be cherry picked to the release branch. But I will leave that decision up to @naliboff and @tjhei.
> Fix visco plastic floating point exception

- index.html
I thought we should link to the webinar so that people can go and watch it if they missed it and want to hear about the new features. If you think there's a better places than in the "News" column, let me know!
> add a link to the ASPECT 2.0 webinar

- Jenkinsfile
not sure why it worked before, but the current code generates:
No such property: CHANGE_AUTHOR_EMAIL for class: groovy.lang.Binding
because it is interpreted as groovy instead of a shell variable.
> jenkins: fix info stage

- include/aspect/simulator/assemblers/interface.h
- source/simulator/assemblers/interface.cc
This branch fixes the bug described in [issue #2252]. The modifications mostly follow the comments of @bangerth . This branch runs well with /tests/discontinuous_composition_1.prm using multi-threads now, while the master branch would fail.
However, there is a small problem when running ./aspect -j $PATH_TO_TESTS/discontinuous_composition_1.prm.  The output on my computer is like this:
`-----------------------------------------------------------------------------
-- This is ASPECT, the Advanced Solver for Problems in Earth's ConvecTion.
--     . version 2.1.0-pre (iss#2252, 5f43cb715)
--     . using deal.II 8.5.1
--     . using Trilinos 12.12.1
--     . using p4est 1.1.0
--     . running in DEBUG mode
--     . running with 1 MPI process
--     . using 8 threads 
-- How to cite ASPECT: …
> fix bug described in [issue #2252]

- source/main.cc
This fixes the warnings reported in #2252 if deal.II is compiled with PETSc, and ASPECT has additional command line options unrecognized by PETSc (e.g. -j). I just filter out all ASPECT related options before initializing PETSc.
> Fix initialization warning with PETSc

- include/aspect/material_model/interface.h
- include/aspect/material_model/steinberger.h
- source/material_model/diffusion_dislocation.cc
- source/material_model/drucker_prager.cc
- source/material_model/dynamic_friction.cc
- source/material_model/grain_size.cc
- source/material_model/latent_heat.cc
- source/material_model/melt_global.cc
- source/material_model/melt_simple.cc
- source/material_model/multicomponent.cc
- source/material_model/steinberger.cc
- source/material_model/visco_plastic.cc
- source/simulator/solver.cc
I noticed this while talking to @menno-fraters about the Newton solver.
The code in question here is used for both the preconditioner of the regular
Stokes solver as well as for the Newton-Stokes solver where that one matrix
block has a different meaning.
> Update a comment.

- include/aspect/material_model/interface.h
- include/aspect/material_model/steinberger.h
- source/material_model/diffusion_dislocation.cc
- source/material_model/drucker_prager.cc
- source/material_model/dynamic_friction.cc
- source/material_model/grain_size.cc
- source/material_model/latent_heat.cc
- source/material_model/melt_global.cc
- source/material_model/melt_simple.cc
- source/material_model/multicomponent.cc
- source/material_model/steinberger.cc
- source/material_model/visco_plastic.cc
This addresses #676. While there, I also improved the latex markup of 'Pa s', where
latex would ordinarily eat the space between the two units.
> Better document the purpose of the reference viscosity in material models.

- cite.html
Specifically: `<pre>` blocks are not formatted, so long lines break awkwardly.
Also update the year of the manual.
> Update the citation page.

- README.md
I saw that the readme was a bit out of date, using inconsistent terminology compared to the authors file, so here is a proposal to update it. I basically just copied the authors file and combined it with was already there. I kept the mail addresses for the maintainers, but I am fine with putting it at the location of the principal developers and adding the others.
> Update Readme.md to reflect the AUTHORS file better.

- README.md
This is the grammatically correct form. Follow-up to #2275.
> Principle -> principal developers.

- include/aspect/geometry_model/spherical_shell.h
- source/geometry_model/chunk.cc
- source/geometry_model/ellipsoidal_chunk.cc
- source/geometry_model/sphere.cc
- source/geometry_model/spherical_shell.cc
This header file was removed in deal.II, and the content was deprecated (and was not used any longer even before this PR). This PR fixes compiling with the recent deal.II master.
> Remove deprecated deal.II header

- cite.html
This is the companion patch to #2306.
> Bring a bibtex entry back in synch with manual.bib.

- include/aspect/parameters.h
- source/simulator/parameters.cc
- source/simulator/solver.cc
Add variable "GRMES solver restart length" as an input parameter. Solves convergence problems due to high viscosity jumps in the domain, and very likely will be helpful in other sorts of problems. 
Right now I left (though edited) the original version of increasing the number of restart iterations to 100 if melt transport is included, but maybe that it is not necessary anymore since it is now an input parameter?
> Add GRMES solver restart length as an input parameter

- doc/manual/manual.tex
right now the internal links are "section_2.4", etc.. This means they
are not stable when the number of sections change. Currently we don't
care, but this change allows us to deeplink into section of the pdf.
Demo:
http://www.math.clemson.edu/~heister/aspect-pdf-manual/web/viewer.html?file=b.pdf#sec%3Apressure
related to: https://github.com/geodynamics/aspect/issues/2231
> manual: switch to named anchor labels

- include/aspect/simulator_access.h
This change is in reference to the issue reported in #2256.
> Fix grammar in the documentation of a function.

- doc/manual/manual.tex
changed a bit of the manual so that it correctly locates parameters in the "solver parameters" subsection
> Fix reference to solver tolerance parameters in manual

- source/mesh_refinement/composition.cc
- source/mesh_refinement/temperature.cc
- source/mesh_refinement/velocity.cc
> Avoid the use of the deprecated FunctionMap typedef.

- doc/manual/manual.bib
- include/aspect/boundary_temperature/dynamic_core.h
- source/boundary_temperature/dynamic_core.cc
> Add bib entry for dynamic core reference Nimmo 2004

- doc/modules/changes/20180619_myhill
- source/postprocess/depth_average.cc
Depth average output files using gnuplot format labelled the first two columns as `<x> <y>`. This has now been corrected to `<depth> <time>`.
This PR resolves Issue #945.
> Correct depth average gnuplot labels

- tests/checkpoint_01.cc
- tests/checkpoint_02.cc
- tests/checkpoint_02_direct.cc
- tests/checkpoint_02_petsc.cc
- tests/checkpoint_03_particles.cc
- tests/checkpoint_04_particles_no_output.cc
`abort` has the connotation of being an error, but we just do `exit(0)`, which is totally acceptable way to say that we just end the program.
> Replace the word 'abort' by 'terminate' if we exit with a zero error code

- doc/manual/manual.tex
Addressing issue #2300 - I edited the note in Section 2.3 and added a short subsection 2.3.1 to clarify that the flag pertains to time and velocity units for input parameters as well as outputs.
> Re-word manual sections on "Use years in output instead of seconds" flag

- source/geometry_model/chunk.cc
Addressing issue #2331 - added error messages when lat =90/-90
> Added error messages for boundaries that do not work in chunk geometry model

- CMakeLists.txt
We need a compiler with c++ 11 starting with deal.II 9.0 anyways. Can we require this already? We are not testing on older compilers anyways.
> require c++11

- source/particle/world.cc
- tests/particle_free_surface.prm
- tests/particle_free_surface/screen-output
The particles were never tested with the free surface and I am reasonably sure that at least something is broken in this case (see also #2243). Disable this feature for now until we further test it.
> Disable combining particle with free surface

- doc/manual/manual.bib
There are several bibtex entries issues in the tree for ASPECT where some necessary capital letters such as in  "Advanced Solver for Problems in Earth ConvecTion" or in names like "Stokes" turns out to show small letters when bibtex runs. We fix this issue by enclosing all necessary capital letters into curly braces.
> Fix bibtex entries for ASPECT.

- Jenkinsfile
one of the servers is timing out at 45 min test time. Increase time for now.
> Jenkins: increase timeout

- include/aspect/material_model/grain_size.h
- source/material_model/grain_size.cc
> grain_size: do not copy arguments

- include/aspect/geometry_model/spherical_shell.h
- include/aspect/global.h
- include/aspect/simulator_signals.h
- source/geometry_model/chunk.cc
- source/geometry_model/ellipsoidal_chunk.cc
- source/geometry_model/sphere.cc
- source/geometry_model/spherical_shell.cc
- source/simulator/assembly.cc
- source/simulator/core.cc
- source/simulator/helper_functions.cc
- source/simulator/initial_conditions.cc
- source/simulator/nullspace.cc
- source/simulator/solver.cc
cherry-pick  #2292 and #2329 to avoid deprecation warnings. As discussed in #2262.
> [2.0.1] cherry-pick #2292 and #2329

- include/aspect/global.h
- include/aspect/simulator.h
- include/aspect/simulator_access.h
- include/aspect/simulator_signals.h
- source/simulator/core.cc
- source/simulator/helper_functions.cc
- source/simulator/initial_conditions.cc
- source/simulator/nullspace.cc
- source/simulator/solver.cc
This is a fixup to #2329. I do not like to include more things into global.h, we should only include what is necessary. In practice this will not make a big difference, because most plugins include simulator_access.h, but when we require deal.II 9.1 we can replace the include in the simulator_access.h by a forward declaration and probably save some compile time. For the moment I think this is a cleaner solution than just putting `ConstraintMatrix` into global.h.
> Remove ConstraintMatrix in global.h

- include/aspect/utilities.h
- source/utilities.cc
At the moment the fixed subsection name for any use of AsciiData is "Ascii data model". This might sometimes not be very descriptive. For example, I want to add an option to read in a vs to density scaling from a file. If I do this using AsciiData there is nothing in the parameter file that tells the user that the ascii data model is used for the vs to density scaling. This pull request makes the subsection name an input, which can be changed to e.g. "Ascii data model for vs to density scaling". The default is subsection name is set to "Ascii data model" to be backward compatible. This addresses issue #2365.
> Make the name of the subsection in AsciiData an input

- include/aspect/material_model/simple_compressible.h
"reference_rho" variable was mistakenly commented as reference surface temperature.
> Fixed a typo in the comment of a header file.

- source/initial_temperature/S40RTS_perturbation.cc
I added a comment to the beginning of S40 to point out that it uses a different normalization than is normally used. We already had this comment in the code but further down. The purpose of having it at the beginning is to alert people who might copy and paste this for some other spherical harmonic based functionality that they need to change this. In most cases the normalization in S40 is not what they will want.
> improve comments in the S40RTS initial temperature model

- include/aspect/introspection.h
- source/simulator/introspection.cc
The change allows the full list of compositional fields to be returned in a vector. This change was needed for adding a different new function in utilities.cc to parse maps. The reference for this related function will be added soon.
> Add new function to return the full list of compositional fields

- tests/edit_parameters.cc
Specifically, a warning about an unused variable, and a warning about comparison
between signed and unsigned.
> Fix warnings when compiling a test.

- Jenkinsfile
- generate output while prebuilding test to hopefully avoid the timeout
disconnects happening
- ignore the result of the prebuild but use the output of ctest to check
if tests failed
> jenkins: make more robust

- source/particle/output/interface.cc
- source/postprocess/depth_average.cc
- source/postprocess/particles.cc
- source/postprocess/visualization.cc
Fixes #2055. I did not include the format options themselves, because that would duplicate them in the manual. Instead I just refer to the manual.
> Improve documentation of output formats

- Jenkinsfile
on some machines mpirun will produce an OpenFabrics warning that will make all
tests fail. Just disable this transport protocol.
> Jenkins: disable openmpi output

- Jenkinsfile
I think it is not useful to run N+2 processes with N cores (ninja default),
because some of our machines are short on RAM (at least tjhei-timo).
> jenkins: limit ninja processes

- include/aspect/parameters.h
- source/simulator/core.cc
- source/simulator/parameters.cc
- tests/skip_initial_conditions_setup_on_initial_refinement.prm
- tests/skip_initial_conditions_setup_on_initial_refinement/screen-output
- tests/skip_initial_conditions_setup_on_initial_refinement/statistics
- tests/skip_solvers_on_initial_refinement.prm
- tests/skip_solvers_on_initial_refinement/screen-output
- tests/skip_solvers_on_initial_refinement/statistics
For those who want to skip solvers and the initial conditions setup, this pull request adds 2 parameters for the subsection mesh refinement.
AssertThrow for solvers ON while setup initial conditions OFF does not work for some reason.
AssertThrow for skipping setup initial conditions while running postprocessors on initial refinement does not work either.
> Possibility to turn off the solvers and initial conditions setup during the initial refinement

- source/material_model/melt_global.cc
- source/material_model/melt_simple.cc
- source/postprocess/global_statistics.cc
The flag for converting years to seconds can be checked with the wrapper function convert_output_to_years(), and all but three of the material models and postprocessors use the wrapper. @tjhei suggested cleaning up those three files to make things more consistent/searchable, so I've done that.
> Clean up get_parameters().convert_to_years in material models and postprocessors

- source/particle/generator/uniform_box.cc
I was getting floating point exceptions when I tried to generate particles using a uniform box with maximum y less than minimum y.
This adds an AssertThrow to prevent that.
> Add AssertThrow to check 'uniform box' particle generator limits

- source/boundary_heat_flux/function.cc
I think the problem came in through an unfortunate combination of #2343 and #2337 -- each might have compiled successfully individually, but not in combination.
> Add necessary #include file to make things compile again.

- source/simulator/assemblers/newton_stokes.cc
This fixes two problems in the Newton solver assembly discovered by @gassmoeller. The first problem is that the functions call in the inner most loop the function `this->get_pressure_scaling()`. We now store this value in the beginning and reuse it. The second problem was that the tensor contraction for the symmetrisation was very expensive. We could use a similar trick here, making it a lot cheaper.
The stats before:
```
+---------------------------------------------+------------+------------+
| Total wallclock time elapsed since start    |      88.6s |            |
|                                             |            |            |
| Section                         | no. calls |  wall time | % of total |
+---------------------------------+-----------+------------+------------+
| …
```
> Fix two performance problems in the Newton assembly.

- source/simulator/parameters.cc
This is basically #2448, just done in the right place.
> Remember that Patterns::Integer has *inclusive* bounds.

- source/geometry_model/ellipsoidal_chunk.cc
The functions in it are only used in a single .cc file, so they don't need
to be exported from the object file.
This is another follow-up to #2442 and #2444, in pursuance of #2402.
> Make a local namespace anonymous.

- include/aspect/geometry_model/ellipsoidal_chunk.h
#2442 moved these functions out of the class declaration and instead made them
functions in an internal namespace. But it also moved the declaration into the
.h file, which is not necessary since these functions are only used in the
.cc file. So remove the declarations from there.
This finally fixes #2402.
> Remove unnecessary forward declarations.

- source/utilities.cc
We repeatedly reference Utilities::AsciiDataBase<dim>::, which looks like we're accessing
a (possibly static) member of some unrelated class. But we really just access a member of
a template-dependent base class. This can be more easily -- and more obviously -- stated using
'this->'.
> Simplify code.

- source/simulator/assembly.cc
In the assembly of the advection system for boundary faces, where we attach the additional outputs to the material model outputs, we used to attach the additional outputs to the "normal" material model outputs instead of the face material model outputs. I don't think anyone noticed this, probably because so far we haven't used additional outputs with the face assemblers. 
This pull request fixes this.
> [bugfix] fix additional material model outputs on face assemblers

- doc/modules/changes/20180625_niday
- source/particle/generator/uniform_radial.cc
The default maximum longitude and latitude are pi, which does not make sense for angles measured in degrees.
> Change default limits for 'uniform radial' particle generator

- include/aspect/boundary_temperature/interface.h
- include/aspect/boundary_velocity/interface.h
- include/aspect/heating_model/interface.h
- include/aspect/initial_composition/interface.h
- include/aspect/initial_temperature/interface.h
- source/heating_model/interface.cc
- source/postprocess/core_statistics.cc
- source/simulator/helper_functions.cc
This pull request addresses #2260. The deal.ii deprecated find_plugin functions for the following interfaces are replaced by has_matching and get_matching.
> Replace find_plugin function

- CMakeLists.txt
otherwise I am getting
```
CMake Warning at CMakeLists.txt:336 (FIND_PACKAGE):
Could not find a package configuration file provided by "PerpleX" with
any
of the following names:
```
related to #2400
> make perplex cmake search quiet

- include/aspect/utilities.h
- source/material_model/multicomponent.cc
- source/utilities.cc
- unit_tests/parse_map_to_double_array.cc
This is a new function that parses a comma separated series of maps of keyword_id and doubles. This function addresses issue #1489, to clarify the number of compositional fields in the multicomponent material model and other similar plugins. The current format uses a comma separated list of doubles to assign values to various parameters, such as density, for each compositional field. However, it is unclear which value is assigned to which field. This new function allows for each value to have a label id that matches the labels given to the compositional fields in the parameter file. The current format is also still supported, and the function detects which format is provided. As an example, this function has been implemented in multicomponent material model for the density parameter. This …
> Parse map utility

- benchmarks/solcx/solcx.prm
- benchmarks/solkz/solkz.prm
As they are now the two parameter files for SOLCX and SOLKZ generate velocity outputs in m/year which is a) nonsensical b) different than what is shown in the manual.
> switching output of solcx, solkz to MKS again

- source/simulator/solver.cc
This modifies the cheap Stokes solver iterations to use the same restart length as the expensive iterations. I see no reason why this parameter should be limited to expensive iterations, and currently, I see no reason to have this as two separate parameters either.
The reason I would iike to have this parameter is that I am trying to reproduce a benchmark that specifies this parameter differently, and I am not able to change this for just a single benchmark in a plugin.
> Use the parameter GMRES restart length also for cheap iterations

- doc/manual/manual.tex
This resolves (i.e., fixes) Issue #1494 
> The Manual's Appendix numbers are overwriting the section titles #1494 
The one line of code
`\renewcommand{\numberline}[1]{#1~}`
adds a space between the Appendix number (e.g., A.101) and the Appendix title.
There is still one problem with the table of contents; namely, some long titles are not being broken into multiple lines.  For example, see 
> A.10 Parameters in section Boundary composition model/Box with lithosphere ... 271
> Aspect Manual Table of Contents

- source/utilities.cc
possible there is a difference in UK/USA spelling
> Fixed typo in comment
