- include/aspect/material_model/simple_compressible.h
- source/material_model/simple_compressible.cc
A few lines to explain that the simple compressible model doesn't obey Maxwell's relations.
> added clarification to simple compressible model

- doc/manual/manual.tex
This PR addresses Issue #2491
The solution was to adjust two internal LaTeX parameters that set the width of the right-hand TOC margin and the size of the box that contains the page numbers, so that now the page numbers in the TOC are aligned in a column.  There is addition documentation in a comment at the top of manual.tex.
> Aspect manual TOC

- tests/melting_rate.cc
Thereby also avoiding the corresponding warning.
> Remove an unused variable in a test .cc file.

- source/simulator/checkpoint_restart.cc
We should check first whether input parameters upon restart are reasonable before
we start to read the rest of the simulation data. That's because the rest may not make
sense to us if the parameters are non-sensical. 
In other words: Try to give error messages as early as possible.
This is a follow-up to #2310, in pursuance of #2090.
> Move the check for reasonable parameters earlier in the function.

- doc/manual/manual.tex
Tweaks to manual:
- Consistent notation for critical Rayleigh number to Ra_c (previously both Ra_c and Ra_{cr} were in the manual.
- Changed description of Ra in example "Play time 1: Different Rayleigh numbers" for clarity.
> Consistent notation for Ra_c in manual

- CMakeLists.txt
Running the whole testsuite in an in-source build has several problems.
Most importantly, the test build and source directory are not separate,
so the project can not be easily reset.
Rather than trying to fix this, disallow running the "all tests". Of
course running our single "quick test" is still okay.
> cmake: disallow in-source test runs

- doc/manual/manual.tex
Note: There may be new authors after this PR, since there may be open PRs from Hackathon participants which make changes to the manual.
> Added new authors from the 2018 Hackathon to the manual.

- doc/modules/changes/20180620_bangerth
- source/geometry_model/box.cc
- source/material_model/viscoelastic.cc
- source/simulator/core.cc
- tests/edit_parameters.cc
- tests/melting_rate.cc
This way, the initialization code and other places have a way of determining
whether we are still in initialization, or whether we have already started time
stepping.
Right now, there is no way to find out, for example in the hook that
is called from the function that builds constraints, whether we
are already in the process of time stepping, or only in the
initialization phase. So move the initialization of the time
step number and time step variables to the very end of the
initialization phase.
> Only set time step number and timestep sizes after initialization is finished.

- include/aspect/parameters.h
- source/simulator/assemblers/stokes.cc
- source/simulator/assembly.cc
- source/simulator/parameters.cc
- tests/use_full_A_block_preconditioner.prm
- tests/use_full_A_block_preconditioner/screen-output
- tests/use_full_A_block_preconditioner/statistics
In order to finish #2498 I would like to be able to use the same solver setup as the paper Rudi et al (2017), "Weighted BFBT Preconditioner for Stokes Flow Problems with Highly Heterogeneous Viscosity". However, they use the full A block for the preconditioner, instead of our simplified version. This PR adds a parameter that allows changing this behavior, which might also be of interest for other models that struggle with convergence issues in the linear solver. I also tried to avoid some unnecessary work in that case (there is not much use in assembling a preconditioner matrix block that will never be used). 
In theory there is more potential for savings, we could even think about not allocating the preconditioner A block at all, but that would require more changes to the constraints, so …
> Add option to use full A block as preconditioner

- doc/manual/manual.tex
The note showed the divergence of the stress tensor. But it talked about the
strain rate tensor (which is only a part of it) and it is in fact not necessary
to use the divergence of it at all.
> Update a note in the manual.

- include/aspect/initial_temperature/S40RTS_perturbation.h
- include/aspect/initial_temperature/SAVANI_perturbation.h
- source/initial_temperature/S40RTS_perturbation.cc
- source/initial_temperature/SAVANI_perturbation.cc
- tests/thermal_alpha_s40rts.prm
- tests/thermal_alpha_s40rts/screen-output
This adds an option so that S40RTS or SAVANI initial conditions can read in thermal expansivity from the material model, instead of inputing a constant value in the parameter file. By default the option is off.
> Let initial conditions use thermal expansivity from material model

- Jenkinsfile.k8s
So far this is a test to avoid a deprecation warning and a few issues with the kubernetes jenkins tester. Do not merge, if this works I will add more detailed explanations.
> Avoid creating too many jenkins kubernetes agents

- benchmarks/annulus/annulus.cc
- benchmarks/shear_bands/shear_bands.cc
- benchmarks/solitary_wave/solitary_wave.cc
- include/aspect/boundary_composition/interface.h
Some benchmarks still use the deprecated find_...(plugin) functions. Use the newer `has_...` and `get_...` plugin functions introduced in #2260 and related pull requests.
> Remove usage of deprecated functions

- Jenkinsfile.k8s
Hopefully this lets the tester query a pull request for its labels, and proceed with testing if the 'ready to merge' label has been set.
> Tester check for 'ready to test' label

- doc/manual/manual.tex
The compressibilities used in the compressible formulations were ambiguous in the manual. 
This PR: 
- Explicitly states which compressibility is used in each formulation. 
- Replaces \kappa with \beta wherever the symbol is used for the compressibility, as \kappa is already used for the thermal diffusivity.
Addresses #2506.
> doc: compressibility type for different approximations

- source/main.cc
Instead of showing a 16 line long and hard to understand blurb about MPI
deadlock, Exceptions, and failing assertitions in line xyz, output the
error directly.
> Improve prm not found error

- source/postprocess/visualization/seismic_anomalies.cc
This is just like #2565, but I had not realized that the class is duplicated twice
in one file. So I should have made the changes of #2565 in two more places. This
is done here.
> Move variable declarations right before the loop they control.

- source/material_model/visco_plastic.cc
Fix for the `visco_plastic` quadrature formula assumption in `FEValues`, which addresses #2579. 
@jdannberg - Let me know if this is not what you had in mind and thanks again for catching this!
> Update viscoplastic FEValues quadrature

- source/simulator/assembly.cc
In the assembly, where we assemble the boundary terms for the stokes assemblers, we do not check for periodic boundaries, so boundary terms are assembled on periodic faces too. This is not a problem for Stokes or traction boundary conditions, because for these terms we have Asserts that make sure no velocity/traction boundary conditions are prescribed on periodic boundaries. However, for other boundary terms from additional assemblers, we probably don't want them to be assembled on periodic faces. Or is there any situation where one might want to do that, and the assemblers should check for that individually?
> Do not assemble stokes boundary assemblers on periodic faces

- .gitmodules
- CMakeLists.txt
- include/aspect/parameters.h
- include/aspect/simulator.h
- include/aspect/simulator_access.h
- source/simulator/core.cc
- source/simulator/parameters.cc
- source/simulator/simulator_access.cc
Since it took too long for the review of #2462 to be done, I decided to put the world builder code in a own repository so I could develop the code faster. Now that the basics are done, I thought it would be a good idea (and useful to me) to merge it with aspect in way smaller pieces than I proposed in #2462. I hope this will help the reviewing of the code.
I have added it as a git submodule which is automatically loaded by cmake. This way the version used by aspect can be controlled, and the installation is done automatically with the installation of aspect.
> World builder 3: adding it to the core of asepct

- doc/manual/manual.tex
This is based on feedback I got from @cedrict at the hackathon. Before, it was not really clear in which directory the commands outlined in the manual should be run, so I made the instructions more clear.
> update section on how to write a test

- doc/modules/changes/20180806_gassmoeller
- source/postprocess/visualization/named_additional_outputs.cc
Fix an index bug in an inner loop that should only loop over the quantities of the current named additional output object (instead of looping over all of them). The two are the same if only one object is active, but not if there is more than one active.
> Fix named additional outputs

- doc/manual/cookbooks/gplates/gplates.part.prm
- doc/manual/manual.tex
This PR addresses the issue #2551.
All but one of the warnings for invalid references were for parameters used in benchmarks and cookbooks source files, which I do not know how to fix. I commented a sentence in the manual.tex which refers to an older parameter in Gplates cookbook.
> Fix manual references

- doc/update_source_files.sh
This was broken since #2460. By starting from the backup file $file.bak the first changes that were made by the sed script were always ignored. Instead the perl scripts need to be applied to the already partially upgraded file $file.
> Fix update source file script

- doc/manual/manual.tex
This is a pure documentation update about the different ways one could modify ASPECT for own model setups. I have found that while we describe in detail how one would write a plugin, there is no discussion about where to keep these plugins, or under which conditions one should keep them in a branch in the main repository, or put them in another directory somewhere else. I hope this text makes it a bit clearer. I also updated some outdated advice (change the Makefile of ASPECT? how long has that been gone), and consolidated some duplications.
> Update manual section about extending

- tests/global_melt_parallel.prm
remove checkpointing that would happen if tester runs slow
fixes #2603
> fix tests/global_melt_parallel

- CMakeLists.txt
Specifically, do not use tabs. Also always capitalize CMAKE commands.
This is a follow-up to #2571.
> Clean up some cmake pieces.

- include/aspect/simulator_access.h
- source/simulator/core.cc
- source/simulator/simulator_access.cc
This allows writing code that calls SimulatorAccess::get_world_builder()
without having to worry whether the WorldBuilder is actually available.
The check then simply happens at run-time.
This is the follow-up promised in #2571.
> Make a function unconditionally available and conditionally fail.

- doc/manual/manual.tex
Unimportant, but I just noticed that some of the prm excerpts in the manual weren't properly formatted.
> Fix prm formatting in the manual

- Jenkinsfile.k8s
This is just some cleanup that I didn't want to add to #2604. Replacing tabs with spaces, making sure indentation is correct, and capitalizing step names.
> Jenkinsfile.k8s whitespace and step names

- citing.html
The file had a duplicated `</head>` tag, and was awkwardly indented.
> Cleanup citing.html

- include/aspect/termination_criteria/end_walltime.h
- source/termination_criteria/end_walltime.cc
- tests/walltime.prm
- tests/walltime/screen-output
Many HPCs have wall time limitations for jobs (e.g. 24 hours). I created a termination criteria base on the wall time used. I thought it would be useful for those running long jobs on those HPCs have limited wall time.
> Add a termination criteria based on wall time.

- Jenkinsfile.k8s
Some more refactoring to remove complexity.
Regarding https://github.com/geodynamics/aspect/commit/bbe3c56225d3e1b3178c3fc78a6dee0626376be5, I'm not sure how Aspect detects the Deal.ii installation in the container, so that change may need to be reverted.
> Jenkinsfile.k8s : Build in Jenkins workspace instead of /home/dealii and other build step cleanup

- source/main.cc
This idea could definitely be improved upon, but is of useful as is. This PR adds a `--validate` flag that exits after parsing the parameter file. I typically do the same thing by just starting a model and ctrl-c'ing it after the parameter file is parsed. This is very slightly more straightforward, and possible to automate in a script later on if needed.
> Add basic parameter file validation mode.

- doc/manual/manual.tex
Just a minor fix for the manual to prevent merging the two dashes.
> Separate dashes in manual.tex

- source/geometry_model/spherical_shell.cc
I was confused by seeing hard-coded values, but it's really just
a magic number/scaling factor we use there.
> Clarify a comment and a formula.

- include/aspect/utilities.h
- source/utilities.cc
- unit_tests/common.h
- unit_tests/parse_map_to_double_array.cc
This is a function that allows to parse two-dimensional input arrays. One application would be to assign different densities to different compositions, with each composition having different phases (e.g. dependent on the depth). As discussed with @naliboff, I think this can be used to make #2586 more generic. It is not yet used anywhere, I just added tests, and we can discuss about how to integrate it best tomorrow.
> Add parse input table function

- source/simulator/entropy_viscosity.cc
Found this while working on the stabilization. The logic in the old form does not smooth artificial viscosity across processor domains, because for ghost cells `!cell->is_locally_owned()` is true and the cell is skipped no matter what the second condition says. I think the old form missed a parentheses around the two conditions (`!(is_locally_owned || smoothing && is_ghost)`). However, instead of keeping this complicated logic I propose we just always compute the entropy viscosity on ghost cells (whether we need it for smoothing or not). It should not be very expensive, and is much simpler to understand.
> Fix parallel viscosity smoothing

- source/simulator/core.cc
aspect now happily prints the citation info, which generates a broken
plugin-graph. Fix this by suppressing the output.
> Fix plugin graph generation

- doc/modules/changes/20180822_gassmoeller
- source/postprocess/material_statistics.cc
Better be specific with formulas than rely on a reader's understanding of
a text description.
I'm not sure there is a reason why one would ever want to use anything
other than the usual arithmetic averaging for the density and mass,
given that these have physical interpretations, so I dropped that remark.
I'm tacking on a change in wording in @gassmoeller's original changelog
to make it clear that the postprocessor computes 'the average density',
(passive) rather than 'averages the density' (an action).
Follow-up to #2630.
> Provide formulas for the material-statistics postprocessor.

- source/particle/generator/uniform_radial.cc
This allows it to make particle distributions that cross the prime meridian.
> Negative longitude in uniform radial particle generator

- source/simulator/parameters.cc
It makes no sense to check for the correct length of the `global_composition_max_preset` variable if only the temperature limiter is selected. The check is only relevant if the composition limiter is selected.
> Fix input check for bound preserving limiter option

- include/aspect/initial_composition/world_builder.h
- include/aspect/initial_temperature/world_builder.h
- source/initial_composition/world_builder.cc
- source/initial_temperature/world_builder.cc
Follow up to #2571. This add the plugins which do the actual linking to the world builder.
> World builder3 add plugins

- Jenkinsfile
Every time a comment that contains "/rebuild" is added to a PR, a fresh build will be triggered.
> allow /rebuild in Jenkins

- source/initial_composition/world_builder.cc
- source/initial_temperature/world_builder.cc
Some fixes for #2574, nothing critical, just things I noticed but did not want to delay the PR further for. 
@MFraters: When I updated the world builder submodule git commited the change to the version of the submodule as well. Does that mean we need to manually update the submodule every time we want to have a newer version of the world build? Or the other way around: Does the version of the world build in ASPECT stay the same if we do not update it? I guess this ties into #2613, and we should continue the discussion there at some point in the future, but here I was just curious. I can remove the update to the world builder when that is wanted, but the current version of the world build that is part of ASPECT has some serious bugs (like it returns the composition as a bool instead of a …
> Fix some typos

- source/simulator/helper_functions.cc
I think there were indexing errors in the bound preserving limiter 3D case that could explain why @maxrudolph sees values outside of the bounds of the limiter in his models. The first commit fixes the indexing errors. The second and third commit of this PR simply refactor the code to avoid the index computation altogether and prevent future mistakes.
I tried to create a testcase, but could not find a model where the bound preserving limiter is actually needed. @egpuckett or @yinghe616 do you maybe have testcases that test the bound preserving limiter?
> Fix bound preserving limiter in 3d

- doc/modules/changes/20181004_gassmoeller
- source/postprocess/visualization/named_additional_outputs.cc
As described in the changelog. This was only a problem if a material model creates multiple named additional outputs and only if this postprocessor is active.
> Fix multiple additional named outputs postprocessor

- Jenkinsfile
- Jenkinsfile.k8s
- README.md
- doc/manual/manual.tex
The github default email address should be my gmail now.
> update Timo's affiliation

- index.html
I think this was appropriate when our website was still hosted at dealii.org, but now it is outdated (and confusing).
> Remove link to legal notice of deal.ii on website

- source/material_model/grain_size.cc
The `DislocationViscosityOutputs` are only implicitly used in the grain size material model, but not explicitly instantiated. This can lead to linker errors if they are used in an external plugin (very rare, but happened to me with clang 6.0).
> Instantiate additional dislocation viscosities output object

- README.md
We no longer run CI on master (wasting energy), so the picture is
broken.
> remove broken badge from readme

- source/simulator/checkpoint_restart.cc
- tests/melt_restart.cc
- tests/melt_restart.prm
- tests/melt_restart/log.txt1
- tests/melt_restart/log.txt2
- tests/melt_restart/screen-output
- tests/melt_restart/statistics1
- tests/melt_restart/statistics2
I just noticed that this was broken and that models with melt transport couldn't be restarted any more. I think we broke it in #2419, where we moved the line 
`melt_handler->add_current_constraints (new_current_constraints);`
into `compute_current_constraints()`, where we then close the constraints, so we can't and shouldn't let the melt handler add its constraints again outside of compute_current_constraints() when we restart the computation. 
I added a test to make sure we don't break this in the future.
> [bugfix] fix restarting melt models

- include/aspect/parameters.h
- source/simulator/helper_functions.cc
- source/simulator/parameters.cc
I noticed that in models with a free surface and open boundaries all around, it can help a lot if the first timestep can be capped manually. I thought it might also be useful to others.
> Implement maximum first timestep parameter.

- doc/modules/changes/20181029_jdannberg
- doc/modules/changes/20181031_jdannberg
- include/aspect/parameters.h
- include/aspect/simulator.h
- include/aspect/simulator/assemblers/advection.h
- source/simulator/assemblers/advection.cc
- source/simulator/assembly.cc
- source/simulator/helper_functions.cc
- source/simulator/parameters.cc
- source/simulator/solver_schemes.cc
- tests/prescribed_field/screen-output
- tests/prescribed_field_with_diffusion.cc
- tests/prescribed_field_with_diffusion.prm
- tests/prescribed_field_with_diffusion/screen-output
- tests/prescribed_field_with_diffusion/statistics
This pull request adds an advection method that allows it to first copy a material model output into a compositional field, and then to diffuse it using a fixed length scale. In order to make this work, I had to change the way the prescribed_field method works: It will not be called after all of the other fields are solved, but instead will be called in the order the fields are listed in (so if the input file lists the prescribed_field last, it would still be solved last). As I just added this functionality two weeks ago, I don't think anyone has started using it yet. 
If we agree that this makes sense, I'll also add a changelog entry explaining this.
> add diffusion of prescribed fields

- Jenkinsfile
this speed ups cloning of the repo by using a local copy of the
repository as a reference
> jenkins: set reference repo

- include/aspect/material_model/diffusion_dislocation.h
- include/aspect/material_model/dynamic_friction.h
- include/aspect/material_model/interface.h
- include/aspect/material_model/multicomponent.h
- include/aspect/material_model/visco_plastic.h
- include/aspect/material_model/viscoelastic.h
- source/material_model/diffusion_dislocation.cc
- source/material_model/dynamic_friction.cc
- source/material_model/interface.cc
- source/material_model/multicomponent.cc
- source/material_model/visco_plastic.cc
- source/material_model/viscoelastic.cc
I am trying to clean up the material models a bit by moving functions into the interface. I started with the average_value function (which was used in 5 different material models, with bugfixes only being included in some of them), but there are more candidates. 
The interface already had a similar function that is used in a number of material models (the `compute_volume_fractions` function), and at the moment, these functions are just normal functions in the interface. As I plan to add more, a question:
Does it make sense to just add all of them in the place they are at the moment, or do we want to start a new file (interface.cc already has more than 1000 lines!) or a new namespace for these functions? We could call it something like material helper functions.
> move average_value function to material model interface

- doc/manual/manual.tex
The current link to the installation FAQ is not really visible inside the instructions if someone gets stuck at a particular point (because it is in the introductory text of the section). Put another reference to the point where it is most likely needed (when running candi). This was suggested by Björn Heyn.
Also update the reference to the mailing list by the forum address.
> Make installation FAQ more visible.

- source/material_model/visco_plastic.cc
When strain weakening is enabled, a non-linear solver scheme with more than one (e.g., iterated) advection iteration should not be used.
> Check visco-plastic nonlinear solver schemes

- source/simulator/solver.cc
This will be deprecated in deal.II
(https://github.com/dealii/dealii/pull/7451) and the parameter has no
meaning to begin with.
> avoid FGMRES unused argument

- doc/manual/manual.tex
I seem to have had this sitting around in my working directory for a while
already. I believe I thought that the term 'basically' is informal. It's
also incorrect: You really do have to describe 'everything', not just
'basically everything'.
> Micro-language-fix for the manual.

- source/utilities.cc
Made possible by the fact that we now require C++11 for ASPECT. Related
to #2375.
> C++11-related cleanups.

- include/aspect/utilities.h
- source/utilities.cc
This also removes the current memory leak we have because the pointer is never
released.
Also in relation to #2375.
> Replace a plain pointer by a std::unique_ptr.

- source/geometry_model/initial_topography_model/ascii_data.cc
The documentation for the 'ascii data' option of the 'Initial topography' model currently states that box, chunk and spherical shell geometries are supported. It appears that only the box geometry is currently supported, but #1705 will add support for the Chunk geometry.
I have not explicitly tried a test model, but I believe the 'prm_polygon' option will only work with the box geometry as well.
In addition to adding documentation, would it be worth adding Asserts so that one cannot use the Chunk or Spherical shell geometry with the unsupported Initial topography options?
> Update initial topography documentation

- include/aspect/material_model/interface.h
- include/aspect/parameters.h
- include/aspect/simulator.h
- source/simulator/helper_functions.cc
- source/simulator/solver_schemes.cc
These are all updates for code introduced mostly in #2677. The only functional
change is to rename interpolate_material_output_into_field() to
interpolate_material_output_into_compositional_field() to make clear
where the data goes.
I have some more questions about this code, but will ask that separately
once these cleanups are merged.
Related also to #2715, #2716, #2718, #2719.
> Updates to the code for copying material model data into compositional fields.

- source/geometry_model/chunk.cc
- source/geometry_model/ellipsoidal_chunk.cc
types::invalid_manifold_id is deprecated in deal.II post 9.0 and
has been replaced by types::flat_manifold_id. I am pretty sure that
flat_manifold_id already existed in deal.II 9.0, which we require
anyway. So it's safe to use this.
ASPECT cannot currently be compiled with deal.II 9.1-pre because
of #2602, so this does not actually matter in some sense. But it
is a step in the right direction and will have to be addressed
at one point anyway. For me, it also reduces the number of
warnings I get when I want to compile the current state to
the degree this is possible.
> Replace invalid_manifold_id by flat_manifold_id.

- source/simulator/solver_schemes.cc
Found while looking at #2677 and #2715. The code is not wrong,
but unnecessarily hard to read.
> Fix a syntactic oddity.

- source/simulator/core.cc
There are complicated reasons for this not worth repeating here. See the
long comment I'm adding.
> Use std::uncaught_exceptions if possible.

- source/boundary_traction/initial_lithostatic_pressure.cc
The two merged boxes should also not convert spherical to cartesian coordinates.
> add two merged boxes to initial lithostatic pressure plugin.

- source/postprocess/visualization.cc
This does not functionally change anything, but for a few minutes I thought I had found a bug, because we omit the third argument in the case we interpolate the output file. In practice this argument is not used, if no subdivision is requested, but I think the new way is more consistent.
> Unify call to visualization build_patches()

- benchmarks/doneahuerta/doneahuerta.cc
this is broken with deal.II 9.0 right now...
> benchmarks/doneahuerta: use c++11 namespace

- doc/parameter_view/parameters.css
- doc/parameter_view/parameters.js
- doc/parameter_view/parameters.xml
- doc/parameter_view/parameters.xsl
- doc/update_parameters.sh
This change makes `doc/update_parameters.sh` also create a parameters.xml file that can be used for an extremely convenient view of all parameters (better interface than the long list in the manual, and easier to use than the parameter gui). Since it is included in the usual update cycle, it will always be in sync with the parameters.tex in the repo and the latest manual. The xml file is combined with an .xsl stylefile that allows viewing the file in a browser offline or online. For an online preview see: https://gassmoeller.github.io/parameters/parameters.xml, but the file also works offline (just open the .xml file in your browser, I think Chrome has a security feature that disallows the offline view, but firefox works). In a follow up PR I will link to this file from our website. This …
> Introduce parameters.xml

- doc/parameter_view/parameters.js
- doc/parameter_view/parameters.xsl
This is a reopened #2749. I accidentally changed the base branch of that one, and github could not revert that. Description and commits just like in #2749.
> Extend parameter view

- source/utilities.cc
- tests/ascii_data_boundary_velocity_3d_sphere.prm
- tests/ascii_data_boundary_velocity_3d_sphere/screen-output
- tests/ascii_data_boundary_velocity_3d_sphere/statistics
The title says it all. The ascii data plugin already supports spherical geometries in general, but it did not recognize the sphere geometry as a supported geometry model.
> Support sphere geometry in ascii data plugin

- source/material_model/interface.cc
This disables FPEs while averaging quantities, which allows us to
average NaNs (values the user didn't fill) without crashing. This is
useful if the values are unused. Errors will still trigger on usage of
the averaged quantity. A good example is
output.entropy_derivative_pressure.
supersedes #2025
> disable FPEs while averaging

- source/material_model/latent_heat.cc
It looks like the iteration over the number of points in `latent_heat.cc` using iterator `i`:
https://github.com/geodynamics/aspect/blob/a19b94bc9ca75891c3bcead9a808ab5327f01eed/source/material_model/latent_heat.cc#L148
is unfortunately later overwritten by the first loop over the number of phase transitions:
https://github.com/geodynamics/aspect/blob/a19b94bc9ca75891c3bcead9a808ab5327f01eed/source/material_model/latent_heat.cc#L229
If `i` is indeed overwritten, the fix in this PR should break a number of tests.
> Fix latent_heat phase transitions loop

- source/simulator/assembly.cc
- source/simulator/solver.cc
As was pointed out in #835 some of ASPECT's timing sections have strange indentation in their names, likely because the names were copied from the screen output string close by that is indented. The majority of sections is not indented, and it is not visible anyway, because the `Timer` class does not print leading spaces in the timing output. Therefore this PR removes the indentation and unifies the naming of our timing sections.
> Remove indentation in some timing sections

- source/simulator/assembly.cc
- source/simulator/solver_schemes.cc
We use constraints.distribute_local_to_global() without a matrix in the
Stokes assembly. This gives incorrect results when we have inhomogeneous
constraints. Make sure that we never use this. Also add documentation
for this.
> add assert and notes about inhomogeneous constraints

- CMakeLists.txt
- only include files if enabled
- allow disabling after the fact
- put config file in binary dir instead
based on #2777.
> world builder update 2

- source/boundary_velocity/gplates.cc
- source/geometry_model/ellipsoidal_chunk.cc
- source/heating_model/latent_heat_melt.cc
- source/particle/generator/uniform_box.cc
- source/particle/generator/uniform_radial.cc
- source/postprocess/gravity_point_values.cc
- source/simulator/helper_functions.cc
- source/termination_criteria/end_walltime.cc
- source/utilities.cc
Interesting how often we ``get_double`` even though we want to do ``get_integer``...
> fix several clang warnings

- include/aspect/simulator.h
- source/simulator/assembly.cc
I suspect that this is a left-over from the time when we used boost's shared_ptr
but there was no equivalent for shared_ptr.
> Use std::unique_ptr instead of std::shared_ptr.

- include/aspect/postprocess/visualization.h
- include/aspect/postprocess/visualization/ISA_rotation_timescale.h
- include/aspect/postprocess/visualization/artificial_viscosity.h
- include/aspect/postprocess/visualization/boundary_indicator.h
- include/aspect/postprocess/visualization/dynamic_topography.h
- include/aspect/postprocess/visualization/error_indicator.h
- include/aspect/postprocess/visualization/geoid.h
- include/aspect/postprocess/visualization/grain_lag_angle.h
- include/aspect/postprocess/visualization/heat_flux_map.h
- include/aspect/postprocess/visualization/particle_count.h
- include/aspect/postprocess/visualization/seismic_anomalies.h
While there, also don't copy things literally, but use doxygen facilities.
> Fix formatting problems in the documentation.

- include/aspect/initial_temperature/S40RTS_perturbation.h
- include/aspect/initial_temperature/SAVANI_perturbation.h
- source/initial_temperature/S40RTS_perturbation.cc
- source/initial_temperature/SAVANI_perturbation.cc
Part of #2375 and #2811.
For reasons not clear to me, using unique_ptr requires me to declare some
classes that are used in the S40RTS models in the header file instead of
the source file. They were previously only forward-declared there, but now
need to have a complete declaration in the header file. This is necessary
because we have a *separate* source file patch_on_S40RTS that derives
from/uses the main S40RTS class and now also wants to destroy these
kinds of objects.
> Use std::unique_ptr instead of std::shared_ptr in some initial temperature models.

- include/aspect/boundary_composition/interface.h
- include/aspect/boundary_temperature/interface.h
- include/aspect/boundary_velocity/interface.h
- include/aspect/heating_model/interface.h
- include/aspect/initial_composition/interface.h
- include/aspect/initial_temperature/interface.h
- include/aspect/mesh_refinement/interface.h
- include/aspect/postprocess/interface.h
- tests/find_boundary_composition_model_fail_1/screen-output
- tests/find_mesh_refinement_fail_1/screen-output
- tests/find_postprocess_fail_1/screen-output
There is really just a : missing as a namespace separator.
> Fix misspelled function names in error messages.

- include/aspect/simulator.h
- include/aspect/simulator_access.h
- source/boundary_traction/ascii_data.cc
- source/boundary_traction/initial_lithostatic_pressure.cc
- source/simulator/core.cc
- source/simulator/simulator_access.cc
> Use std::unique_ptr instead of std::shared_ptr for the boundary tractions.

- jabref-template/listrefs.begin.layout
- jabref-template/listrefs.phdthesis.layout
I've apparently had this in my repository for a while already. It takes over jabref style files from deal.II.
> Update citation templates.

- jabref-template/listrefs.layout
the PDF links to files are not working and do nothing (because these are local files in
mendeley). Remove them.
> www: publications.html: remove pdf

- jabref-template/listrefs.misc.layout
In particular, this affects the entry at
https://aspect.geodynamics.org/publications.html
for the ASPECT manual (the second one in 2015). The format totally doesn't
match any of the other entries, and also misses the newline at the end to separate
itself from Tosi et al.
> Fix the formatting of '@misc' entries.

- jabref-template/listrefs.misc.layout
The previous version would just output ', 2015' if no publisher was given.
Further refinement of #2827.
> Further update the @misc template.

- source/postprocess/gravity_point_values.cc
I am getting warnings about un-initialized variables for the dim=2
instantiation that doesn't work anyways. Fix this.
> avoid warning in gravity point postprocessor

- source/simulator/core.cc
clang 6 warns about an array access out of bounds when instantiating for
dim=2. This is of course not a problem as this code is only executed for
dim=3. Silence the warning by using dim-1 instead of 2.
> fix clang warning

- source/postprocess/visualization/volume_of_fluid_values.cc
While working on putting together a cookbook for the VoF composition advection method, I found that I had not corrected the names of the parameters for the vis postprocessor when reading from the parameter file. This PR makes that correction.
> Fix Volume of Fluid visualization plugin

- include/aspect/material_model/melt_global.h
- source/material_model/melt_global.cc
The melt_global material model tracks depletion through the ‘peridotite’ composition. This peridotite value can affect density, but not yet viscosity. Changing viscosity due to depletion is very useful to model, as it is, e.g., an essential contribution to craton strength and stability (e.g., Wang et al., 2014).
The reason for a ‘depletion’-dependent viscosity is that melting removes most of the volatiles from the source rock, and dry rocks are typically stronger than hydrated ones. The exact dependence of this strengthening on depletion, and even the maximum amount of strengthening is quite unknown. Hirth and Kohlstedt (1996) report typical values around a factor 100 to 1000 viscosity contrast between wet and dry rocks, although some experimental studies report a smaller (factor 10) …
> depletion strengthening in melt_global material model 

- benchmarks/buiter_et_al_2008_jgr/README
- benchmarks/buiter_et_al_2008_jgr/figure_6_1e20.prm
- benchmarks/buiter_et_al_2008_jgr/figure_6_1e22.prm
This pull request addresses part of #2859, while also improving the documentation and formatting of the `buiter_et_al_2008_jgr` benchmarks.
The key change to these benchmarks is to update the strain weakening options, which currently use options that are no longer supported (e.g., they do not run). The strain weakening has also been updated to use the plastic finite strain invariant, which is consistent with the Buiter et al. 2008 study.
> Update Buiter et al. 2008 benchmarks

- source/simulator/core.cc
Here was a significant section of code @tjhei and I found that wasn't being included in the timings.
I'll give an example of why this is a significant section using other setup sections that are being timed:
Ex. 3d, 4 cores, 1.2M DoFs:
Total runtime: 73.1s
Setup dof systems: 0.842s
Setup initial conditions: 2.42s
**_Setup sparsity patterns: 2.56s_**
> timing sparsity pattern setup

- .gitmodules
The submodule is currently specified to use ssh. When somebody clones
aspect with ``git clone --recursive
https://github.com/geodynamics/aspect`` it will try to fetch the world
builder using ssh (and ask for authentication or fail).
Change this.
I don't see any disadvantage of doing so.
> use http git submodule for WorldBuilder

- CMakeLists.txt
List the build/include dir before ./include to give it preference over
the source directory. Reasoning: I had a stray
include/aspect/revision.h (maybe from an accidental in-source build?)
that was used instead of the current generated one. As a result,
ASPECT would show the wrong git branch/version/etc..
> CMakeLists.txt: prefer binary include dir

- benchmarks/shear_bands/run_angle_melt_bands.sh
- benchmarks/shear_bands/run_plane_melt_bands.sh
- benchmarks/shear_bands/shear_bands.cc
The shear bands benchmark had a leftover pre 2.0 input file, because the file is generated from a script and not stored in the repository. Also fixed a floating-point exception in the associated postprocessor that occurs if the analytical growth rate of the shear bands is 0.
> Fix shear bands benchmark input and FPE

- CMakeLists.txt
- cmake/cotire.cmake
This is a workaround for #2314. It updates cotire to the latest release, and disables it for cmake version >= 3.9 due to the errors with the generator expressions that are used in deal.II as discussed in that issue. If we fix the issues otherwise we can again enable cotire for later cmake versions.
> Fix and update cotire

- include/aspect/boundary_velocity/gplates.h
- include/aspect/free_surface.h
- include/aspect/geometry_model/box.h
- include/aspect/geometry_model/chunk.h
- include/aspect/geometry_model/ellipsoidal_chunk.h
- include/aspect/geometry_model/initial_topography_model/ascii_data.h
- include/aspect/geometry_model/sphere.h
- include/aspect/geometry_model/spherical_shell.h
- include/aspect/geometry_model/two_merged_boxes.h
- include/aspect/melt.h
- include/aspect/newton.h
- include/aspect/particle/generator/probability_density_function.h
- include/aspect/prescribed_stokes_solution/function.h
- include/aspect/simulator.h
- include/aspect/simulator/assemblers/advection.h
- include/aspect/simulator/assemblers/interface.h
- include/aspect/simulator/assemblers/stokes.h
- include/aspect/utilities.h
- include/aspect/volume_of_fluid/assembly.h
- include/aspect/volume_of_fluid/handler.h
found with clang-tidy option
readability-inconsistent-declaration-parameter-name
This should have no effect but makes things a bit more consistent.
> cleanup: consistent parameter names

- source/postprocess/particles.cc
- source/postprocess/visualization.cc
- source/simulator/helper_functions.cc
Suppress the three locations where we want to ignore performance-
unnecessary-value-param.
followup to #2879 and required for clang-tidy to pass again.
> clang-tidy: suppress warnings

- source/volume_of_fluid/reconstruct.cc
With deal.II dev and gcc 7.3 I get a warning about missing parentheses. This fixes it.
> Fix a warning

- doc/manual/manual.tex
This is at the end of the short section about design criteria, where we talk about
the numerical methods underlying ASPECT. We never updated the references there to
include the second ASPECT paper.
> Add a reference to the ASPECT II paper to the manual.

- contrib/.clang-tidy
- source/simulator/simulator_access.cc
- WorldBuilder does not run cleanly with our clang-tidy checks, instead
of fixing those, disable it inside contrib/
- fix one nullptr location
> clang-tidy with worldbuilder

- CMakeLists.txt
Declare the project as a CXX only project and change one of the tests to
be a c++ check (instead of a C check). This change will:
- not check the existence of a c compiler (speed up cmake!)
- stop printing confusing messages (finding gcc for the C language,
while we compile with intel for CXX for example)
- actually perform the include check with CXX
> cmake: switch to CXX only project

- benchmarks/tangurnis/code/tangurnis.cc
- include/aspect/heating_model/interface.h
- source/heating_model/interface.cc
- source/postprocess/heating_statistics.cc
- source/postprocess/visualization/heating.cc
Strictly speaking, this is an incompatible change because the heating model manager
exports its list of heating models. I suspect that few plugins we don't have
in the tree ourselves (which I have all converted) make use of this.
Related to #2375 and #2811.
> Replace std::shared_ptr by std::unique_ptr in the heating models.

- doc/release-tasklist
Update the places to announce releases, and include CIG's software page in the release announcement.
> Update announcement lists

- doc/modules/changes/20190502_bangerth
I decided that I should have written a changelog entry for #2882 after all -- it's a functional change visible to users, let's list these in the changelog.
> Add a changelog entry.

- source/simulator/core.cc
We are still reserving memory for the temperature matrix even when it is not needed. Adding an if-statement that ignores the Stokes-only case.
> no temperature matrix for Stokes only

- docker/Dockerfile
Follow up on #2867 to update the docker image.
> Update dockerfile for new base image

- doc/manual/manual.tex
- doc/release-tasklist
- docker/build.sh
I pushed a docker image to https://hub.docker.com/r/geodynamics/aspect that is identical to the current gassmoeller/aspect image. This PR modifies the documentation to use the new image instead of my own.
> Update docker instructions to geodynamics/aspect

- Jenkinsfile.cig
- source/postprocess/interface.cc
The unity build functionality was broken due to a namespace that was only unique in the non unity build. Fix that, and also add a test stage for the unity build. This is currently just to compare the two stages, we could also decide to switch the CIG tester over to the unity build altogether if it saves a bit of time.
> Fix unity build

- CMakeLists.txt
When you run "make info", we did not show the helper target
"setup_tests". Fix this.
> cmake: make info now shows setup_tests

- doc/manual/manual.tex
Capitalized the E in Earth - line 600 of the manual
> Capitalize Earth in manual - section 2.1.2, line 599

- source/simulator/checkpoint_restart.cc
This PR supersedes #2523. It simply moves the commit there to the current master and makes the adjustments necessary to make things run (or, at least, we'll find out whether that works).
Fixes #2090. Closes #2523.
> Verify parameter/variable settings when restart, for issue #2090

- doc/modules/changes/20180620_bangerth-2
- source/boundary_temperature/dynamic_core.cc
- tests/dynamic_core.prm
All plugins use lower-case letters when they are identified in the place
where one selects a plugin, and an initial upper-case letter as a section
name. However, the DynamicCore class uses 'Dynamic core' also as the
plugin name.
Fix this.
This is clearly an incompatible change. I don't know how we usually handle
this: it's a bit of an obscure plugin, so I'd venture the guess that not
many people will actually notice, and maybe we shouldn't be terribly
concerned with backward compatibility. But I still wanted to see what
people think about it first.
> As is usual, make a plugin name lower-case.

- doc/manual/manual.tex
isenchoric -> isochoric
equi-dimensional -> equidimensional
fullfill -> fulfill and fulfil -> fulfill (U.S. spelling)
bouyancy -> buoyancy
timestp -> timestep
> Corrected a few manual typos

- include/aspect/boundary_velocity/gplates.h
- source/boundary_velocity/gplates.cc
We're now down to less than one page of references to `std::shared_ptr`.
Part of #2811 and #2375.
> Remove more references to std::shared_ptr.

- benchmarks/time_dependent_annulus/time_dependent_annulus.prm
This benchmark has no temperature boundary conditions (there are no indicators prescribed). Additionally, it is in a spherical shell, not a box.
> Clean up an unused parameter file subsection.

- doc/modules/changes/20190522_bangerth-2
- doc/modules/changes/20190522_bangerth-3
- include/aspect/boundary_velocity/interface.h
- include/aspect/simulator_access.h
- source/boundary_velocity/ascii_data.cc
- source/boundary_velocity/interface.cc
- source/simulator/simulator_access.cc
- tests/ascii_boundary_member.cc
This also removes a deprecated function that can't easily be converted.
Part of #2811 and #2375.
> Convert more std::shared_ptr to std::unique_ptr.

- include/aspect/material_model/interface.h
- source/material_model/interface.cc
This isn't going to compile, but because I think there is a debug I'd like to discuss with @jdannberg and @tjhei , I'm uploading it here anyway.
The point is this: `MaterialModelOutputs` objects can have additional output objects associated with them. Copying a `MaterialModelOutputs` object would require us to be able to re-create these additional output objects a second time, but we don't know how to do that without knowing who created the additional output objects. 
That said, in the current setup, we just store `std::shared_ptr`s to these additional outputs objects. That seems patently wrong, because now multiple `MaterialModelOutputs` objects might reference the same additional outputs objects, and that can surely not lead to anything useful.
The solution is to disallow copying these …
> Prohibit copying MaterialModelOutputs objects.

- include/aspect/simulator_access.h
See the review done by @gassmoeller (but credited to @tjhei) of #2972.
> Fix a missing space in a function declaration.

- source/simulator/core.cc
> Minor cleanup: Don't duplicate the value of an argument.

- include/aspect/material_model/interface.h
- source/material_model/interface.cc
> Also check additional input objects when copying MaterialModelInputs.

- include/aspect/material_model/interface.h
- source/material_model/interface.cc
> Simply prohibit copying material model inputs/outputs.

- benchmarks/operator_splitting/advection_reaction/advection_reaction.cc
- benchmarks/operator_splitting/exponential_decay/exponential_decay.cc
- include/aspect/material_model/averaging.h
- include/aspect/material_model/compositing.h
- include/aspect/material_model/depth_dependent.h
- include/aspect/material_model/grain_size.h
- include/aspect/material_model/interface.h
- include/aspect/material_model/steinberger.h
- source/material_model/interface.cc
- source/material_model/viscoelastic_plastic.cc
- tests/additional_outputs_02.cc
- tests/additional_outputs_03.cc
- tests/anisotropic_viscosity.cc
- tests/drucker_prager_derivatives.cc
- tests/multiple_named_additional_outputs.cc
- tests/prescribed_field.cc
- tests/prescribed_field_with_diffusion.cc
- tests/simple_nonlinear.cc
- tests/spiegelman_material.cc
- tests/visco_plastic_derivatives_2d.cc
- tests/visco_plastic_derivatives_3d.cc
In reference to #2811 and #2375.
This in fact closes #2811.
> Get rid of the remaining uses of std::shared_ptr.

- contrib/utilities/compile_and_update_tests.sh
We updated the image for the tester, but forgot to update the script that can run all tests automatically. Found this while looking at #3023.
> Update tester image in run tests script

- tests/CMakeLists.txt
No functional changes, but:
- convert tabs to spaces
- reindent
- a few nicer line breaks
> cmake: fix file formatting

- source/utilities.cc
- tests/ascii_boundary_member/screen-output
- tests/ascii_data_boundary_composition_2d_box_time/screen-output
- tests/ascii_data_boundary_composition_3d_box/screen-output
- tests/ascii_data_boundary_temperature_2d_box_time/screen-output
- tests/ascii_data_boundary_temperature_3d_box/screen-output
- tests/ascii_data_boundary_velocity_2d_box/screen-output
- tests/ascii_data_boundary_velocity_2d_box_list/screen-output
- tests/ascii_data_boundary_velocity_2d_box_time/screen-output
- tests/ascii_data_boundary_velocity_2d_box_time_backward/screen-output
- tests/ascii_data_boundary_velocity_2d_chunk/screen-output
- tests/ascii_data_boundary_velocity_2d_shell/screen-output
- tests/ascii_data_boundary_velocity_2d_shell_spherical/screen-output
- tests/ascii_data_boundary_velocity_3d_box/screen-output
- tests/ascii_data_boundary_velocity_3d_chunk/screen-output
- tests/ascii_data_boundary_velocity_3d_shell/screen-output
- tests/ascii_data_boundary_velocity_3d_shell_spherical/screen-output
- tests/ascii_data_boundary_velocity_3d_sphere/screen-output
- tests/box_initial_topography_ascii_data/screen-output
- tests/box_initial_topography_ascii_data_moved_origin/screen-output
- tests/traction_ascii_data/screen-output
The original message for the end of Ascii datafile read-in was very confusing, and made it seem like ASPECT had encountered a problem. This 2-line PR improves that message.
> Improved: Ascii datafile end-read warning message

- include/aspect/postprocess/visualization.h
The class has a virtual member function but a non-virtual destructor. This is generally
a bad idea, though it doesn't matter here because we never store pointers to this
particular type of class (we use this class as one of several base classes of
the viz postprocessor classes, and only store pointers to the Interface class). But
it is bad practice, so fix this anyway.
> Provide a base class with a virtual destructor.

- doc/modules/changes/24052019_glerum
- include/aspect/initial_temperature/continental_geotherm.h
- source/initial_temperature/continental_geotherm.cc
- tests/continental_extension.prm
- tests/continental_extension/screen-output
This sets up a laterally homogeneous continental geotherm as initial temperature condition for for example rift models.
> Continental geotherm initial temperature condition

- source/postprocess/visualization.cc
Specifically, remove the note that the DataOut object is later passed on to some
other thread for writing to disk. I don't recall what patch changed it, but we
don't do this any more, and the comment is no longer accurate.
> Update a couple of comments in visualization.cc.

- include/aspect/postprocess/visualization.h
- source/postprocess/visualization.cc
This is the first step towards being able to writing face data (on the surface of the domain). There are no functional changes in this patch. The only thing I'm doing is breaking out a substantial chunk of work from `Visualization::execute()` into a function of its own (`Visualization::write_data_out_data()`).
I want to get this part out of the way before I make functional changes because the large-scale code motion without functionality change will be difficult to review if I also mix in functionality changes.
(The new function has a template argument that I don't currently use but will in the follow-up patches.)
> Refactor writing data in the viz postprocessor.

- CMakeLists.txt
- doc/manual/manual.tex
- doc/modules/changes/20190426_tjhei
The wait is kind of annoying, so only configure the tests when it is
actually needed.
> cmake: do not configure test project every time

- source/material_model/viscoelastic.cc
clang + lld complains about a missing instantiation. I guess gcc doesn't
require it, but it is certainly correct to do so.
> fix missing ElasticAdditionalOutputs instantiation

- source/material_model/latent_heat_melt.cc
- source/postprocess/visualization/melt_fraction.cc
When moving this from parameter descriptions to latex to pdf, the end result is that it doesn't work and doesn't print like the degree symbol. Fix this.
> Fix incorrect formatting of the degree symbol.

- doc/modules/changes/20190524_gassmoeller
- source/simulator/entropy_viscosity.cc
This is the more robust parameter design as discussed with @tcclevenger over the last few days.
Synthetic benchmarks show little to no difference, but I expect it to be more robust if one of the parameters (\|u\|, eps) goes to zero.
> new SUPG parameter design

- source/geometry_model/two_merged_boxes.cc
- tests/two_merged_boxes_free_surface.prm
- tests/two_merged_boxes_free_surface/screen-output
When running a model with this geometry model and a free surface the assert was triggered before the first timestep, which is not consistent with the assert message. I think this should fix it. @anne-glerum Could you look at this?
> Fix assert two merged boxes in point_in_domain on free surface.

- doc/modules/changes/20190522_bangerth-4
- doc/modules/changes/20190524_bangerth
- include/aspect/simulator.h
- include/aspect/simulator_access.h
- source/material_model/drucker_prager.cc
- source/simulator/core.cc
- source/simulator/simulator_access.cc
This should provide @anne-glerum and @naliboff a way to do what they want to do, and more elegantly than they try to do in #2529.
> Provide a way to check whether the simulator has been completely initialized

- doc/options.dox
required for \triangledown to work.
> doxygen: add amssymb package

- doc/manual/manual.tex
> Use our usual capitalization scheme for manual section headings.

- source/simulator/helper_functions.cc
Would have saved us ten minutes of debugging.
> Provide an error message for a case we ran into this morning.

- contrib/utilities/indent
sed is weird on OSX as it doesn't understand \t. Work around this.
> indent: fix tab replace on OSX

- doc/modules/changes/20190527_tjhei
- source/simulator/core.cc
In rare cases, the code to check if the ConstraintMatrix changed can
cause a deadlock (only some processes would invoke the MPI::sum to check
if the mesh changed).
For this to happen, the total number of DoFs has to stay the same during
refinement. Fix this by unconditionally doing the communication step.
> Fix: avoid MPI deadlock in constraints

- source/material_model/latent_heat_melt.cc
- source/material_model/melt_simple.cc
- source/postprocess/visualization/melt_fraction.cc
Requires #3061.
Done with the command
```
perl -pi -e 's/\{\}\^\\\\circ/\\degree/g;' `find source | egrep '\.cc$'`
```
which is one of those things that seems completely normal to me...
> Use the \degree symbol for degrees in the parameter descriptions.

- include/aspect/utilities.h
- source/initial_temperature/interface.cc
- source/utilities.cc
- tests/initial_temperature_list_using_replace_if_valid.prm
- tests/initial_temperature_list_using_replace_if_valid/screen-output
- tests/initial_temperature_list_using_replace_if_valid/statistics
Create new 'replace if valid' operator for initial temperature conditions. It checks if the value in the second model in a nan, if so it replaces with the value from the first model.
Test also included based on the tests for the other operators.
> Replace if valid operator for initial temperature conditions

- include/aspect/compat.h
- source/utilities.cc
InterpolatedUniformGridData is needed for some planned ascii data plugins, but is not yet implemented in deal.ii. This PR is a workaround for that problem. 
It has been tested using the new functionality in PR #3039.
> Added missing grid interpolator

- include/aspect/utilities.h
- source/boundary_composition/interface.cc
- source/boundary_temperature/interface.cc
- source/initial_composition/interface.cc
- source/initial_temperature/interface.cc
- source/utilities.cc
I added a get_model_operator_options function in utilities which returns "add|subtract|minimum|maximum|replace if valid", and then replaced the list with a call to this function in all the relevant interface.cc files. This way they cannot become out of sync if someone adds a new operator.
> Add get_model_operator_options function in utilities so operator options don't get out of sync

- include/aspect/particle/interpolator/cell_average.h
- include/aspect/particle/interpolator/harmonic_average.h
- include/aspect/particle/interpolator/nearest_neighbor.h
- source/particle/interpolator/cell_average.cc
- source/particle/interpolator/harmonic_average.cc
- source/particle/interpolator/nearest_neighbor.cc
These changes allow the cell/harmonic average, and nearest neighbor particle interpolators to apply the particles as a field even when there are areas with no particles. 
A few questions, as of now this assumes that any area with no particles should be given a value of zero. Would it be better to have this be user defined? Also, should I add a flag for this so that, generally, an assert would still be thrown unless this feature is specifically wanted?
> Allow particles to be applied to fields when particles aren't distributed throughout model.

- include/aspect/geometry_model/spherical_shell.h
- source/geometry_model/spherical_shell.cc
This fixes an oversight, and implements a function that is required for #3069 to work.
> Implement natural_to_cartesian_coordinates for SphericalShell

- include/aspect/initial_temperature/SAVANI_perturbation.h
- source/initial_temperature/SAVANI_perturbation.cc
Here I've simply rearranged the savani_perturbation plug-in so there is a function to return Vs, and this can be called from another plug in. It is now in exactly the same format as s40rts_perturbation.
> Rearrange savani_perturbation to be the same as s40rts_perturbation

- include/aspect/geometry_model/sphere.h
- source/geometry_model/sphere.cc
- source/utilities.cc
Spherical geometry models (e.g. sphere, chunk) can accept information which runs from -pi to pi or 0 to 2pi. For the new initial topography/ascii data plugin, there is 
1) a call to `spherical_to_cartesian_coordinates` before 
2) a call to `Utilities::get_data_coordinates`, which then calls 
3) `spherical_to_cartesian_coordinates`.
This results in a loss of information; we no longer know whether our ascii data runs from -pi to pi or 0 to 2pi. In this particular case, we don't need the conversions at all.
This PR fixes this problem.
> use natural_coordinates in boundary get_data_component

- benchmarks/buiter_et_al_2016_jsg/README
- benchmarks/buiter_et_al_2016_jsg/exp_2_high_resolution.prm
- benchmarks/buiter_et_al_2016_jsg/exp_2_low_resolution.prm
We (Sibiao, Stephanie, John, and Cederic) did benchmark numerical models for brittle thrust wedge experiment 1 and 2 in the JSG paper of Butter et al., 2016.
This benchmark models reproduced similar results (e.g., material fields, strain, strain rate, pressure) as that in other numerical and analogue models indicating that the late version of Aspect has a great performance to simulate sandbox thrust wedge experiments with significant computational challenges.
We only reproduce the model and do not do the model analysis, i.e., measuring the surface slope,  the dip angle, etc.
> Benchmark for brittle thrust wedge experiments in Buiter et al., 2016,JSG paper

- include/aspect/geometry_model/chunk.h
- include/aspect/geometry_model/ellipsoidal_chunk.h
- source/geometry_model/chunk.cc
- source/geometry_model/ellipsoidal_chunk.cc
Referenced in this issue: https://github.com/geodynamics/aspect/issues/2921
Combined with https://github.com/geodynamics/aspect/pull/3122 there are no more references to DEAL9.0.0 in `geometry_model`
> Finish removing 9.0.0 references from geometry_model

- doc/manual/manual.tex
Some late burst of activity :-) The `\si` command is documented here if anyone cares: http://ctan.math.utah.edu/ctan/tex-archive/macros/latex/contrib/siunitx/siunitx.pdf
Part of #3044.
> Use semantic mark-up for SI units in the manual.

- include/aspect/compat.h
gradient/value is now implemented for InterpolatedUniformGridData in deal.II and will be contained in the 9.2 release. In this PR, we add an if statement in compat.h to only use the compatibility functions if the deal.II version is <9.2.
Fixes Issue #3144
> added if !DEAL_II_VERSION_GTE(9,2,0) back into compat.h

- cookbooks/inner_core_convection/inner_core_assembly.cc
My manual did not compile because of non-ASCII characters in this file. I am not sure why this did not happen before, the line did not change for a long time. Anyway, this change fixes the latex error.
> Fix manual compile by removing non-ASCII character

- Jenkinsfile.cig
- contrib/ci/Dockerfile
- contrib/ci/build.sh
- source/material_model/modified_tait.cc
- source/mesh_deformation/interface.cc
We keep breaking our manual, because we do not have a test for it. This PR creates a new docker image for the tester (including latex) and should test the creation of the manual for every PR. We can also extend it later to update the input parameters.
Having the tester as a separate image from the deal.II image will also be helpful for #2978.
> [CI]: test manual on CIG tester

- doc/modules/changes/20190628_coulson
- include/aspect/material_model/replace_lithosphere_viscosity.h
- source/material_model/replace_lithosphere_viscosity.cc
- tests/replace_lithosphere_viscosity_file/screen-output
Updated from #3089 according to Rene's comments. @gassmoeller
New material model plug-in that sets a constant specified lithosphere viscosity above the lithosphere-asthenosphere boundary and takes the viscosity from a base model below this. The LAB can be specified by an ascii file or a maximum lithosphere depth value. All other material properties are taken from the base model.
> Updated: Material model that sets a constant viscosity in the lithosphere

- doc/modules/changes/20190614_gassmoeller
- doc/update_scripts/prm_files/update_prm_files_to_2.2.0_isentropic_compression.sed
- doc/update_scripts/source_files/update_source_files_to_2.2.0_isentropic_compression.pl
- include/aspect/newton.h
- include/aspect/parameters.h
- include/aspect/simulator/assemblers/stokes.h
- source/simulator/assemblers/newton_stokes.cc
- source/simulator/assemblers/stokes.cc
- source/simulator/assembly.cc
- source/simulator/helper_functions.cc
- source/simulator/melt.cc
- source/simulator/newton.cc
- source/simulator/parameters.cc
- tests/anisotropic_viscosity.cc
This changes the name of the isothermal compression approximation to isentropic compression. As discussed in our recent manuscript the current name is misleading and leads to inconsistent models. I have thought about keeping backward compatibility by still allowing the old name, but (1) I think nearly nobody specified this approximation explicitly in the input file (it was the default), and (2) if they did, crashing with an error will force everyone to think about the change and make sure they fix their models.
> Rename isothermal to isentropic compression

- include/aspect/mesh_deformation/interface.h
Fixes some deprecation messages caused by the new mesh deformation plugin system (the branch overlapped with the fixes that were already done in all other places where we use constraint matrices).
> Fix deprecation message with deal.II 9.1

- include/aspect/simulator.h
- source/simulator/helper_functions.cc
- source/simulator/solver_schemes.cc
Currently the `interpolate_material_output_into_compositional_field` function interpolates the material output both into `solution`and `old_solution`, because the `prescribed_field_with_diffusion` advection method needs it that way (because it afterwards solves a diffusion equation as if the interpolation had not happened). This does not matter for all current applications, but I want to use the prescribed field to compute a time-derivative of the composition, and the current assignment to `old_solution` prevents that.
Also it feels weird to me that the function modifies the solutions of previous time steps, because it is intended to create the current compositional field. This PR solves this, by moving the assignment out of the function into the advection method. Technically that changes …
> Move assignment to old_solution to the only place it is used

- benchmarks/burstedde/burstedde.cc
- benchmarks/hollow_sphere/hollow_sphere.cc
- benchmarks/inclusion/inclusion.h
- benchmarks/layeredflow/layeredflow.cc
- benchmarks/operator_splitting/advection_reaction/advection_reaction.cc
- benchmarks/operator_splitting/exponential_decay/exponential_decay.cc
- benchmarks/rigid_shear/plugin/rigid_shear.cc
- benchmarks/shear_bands/shear_bands.cc
- benchmarks/solcx/solcx.h
- benchmarks/solitary_wave/solitary_wave.cc
- benchmarks/solkz/solkz.h
- benchmarks/tangurnis/code/tangurnis.cc
- benchmarks/tosi_et_al_2015_gcubed/tosi.cc
- cookbooks/anisotropic_viscosity/av_material.cc
- cookbooks/inner_core_convection/inner_core_assembly.cc
- cookbooks/inner_core_convection/inner_core_convection.cc
Since #2148 there is not really a use any more for casting pointers to determine the type of a plugin, and it is confusing for new users. This PR replaces all occurences of `dynamic_cast` with the appropriate functions. In a few cases I had to change the order of checks, and I removed a bit outdated code.
> Replace dynamic cast in cookbooks and benchmarks

- .github/PULL_REQUEST_TEMPLATE.md
After a few pull requests with the new template, I would like to shorten it a bit in some places, and add a message for how to get help with the process. I hope this makes it less annoying for experienced developers, and less intimidating for new developers. I am open for suggestions about improvements.
> Streamline pull request template

- cookbooks/anisotropic_viscosity/av_material.cc
This fixes a floating point exception reported by @KiralyAgi in the anisotropic viscosity cookbook. Agi could you take a look and see if this version fixes your problems? You can see the code changes by clicking on `Files changed`, and you can download this version by doing:
```
git remote add gassmoeller
git fetch gassmoeller fix_floating_point_exception_in_av_cookbook
git checkout gassmoeller/fix_floating_point_exception_in_av_cookbook
```
Then recompile and see if it works. If it works, and when this pull request has been merged you can switch back to the main branch and update to the newest version to get the changes as usual, i.e. `git checkout master; git pull upstream master`. 
Also if that succeeds, can you create a test case for your cookbook, so that we know if something breaks …
> Fix floating point exception caused by accessing timestep prematurely

- source/simulator/parameters.cc
As mentioned in #3186 (and #835), the volume of fluid method isn't implemented in 3d right now. Make sure we get an error message at the earliest possible place about this.
@class4kayaker , @egpuckett -- FYI.
> Make sure we get a reasonable exception when using volume of fluid in 3d

- doc/modules/changes/20190806_clevenger
- include/aspect/stokes_matrix_free.h
- source/simulator/solver_schemes.cc
- source/simulator/stokes_matrix_free.cc
- tests/tangurnis_tala_gmg.cc
- tests/tangurnis_tala_gmg.prm
- tests/tangurnis_tala_gmg/screen-output
- tests/tangurnis_tala_gmg/statistics
Adds functionality for compressible flow computations with the block GMG precoditioner. I verified with the tangurnis benchmarks that we are solving for the same solution as with the block AMG preconditioner and added a test based on tangurnis/tala
I've also changed some function names to be more appropriate to their functionality:
`evaluate_viscosity`->`evaluate_material_model` 
and 
`fill_viscosities_and_pressure_scaling`->`fill_cell_data`
so if you have any thoughts there, let me know.
Note: Does not yet include functionality for implicit reference density computations.
> Compressible computations with GMG

- source/main.cc
When running `mpirun -np 2 ./aspect` without further arguments (maybe not the smartest thing to do, but I'm unlikely the first one to try), then one gets an error message as follows:
```
> mpirun -np 2 ./aspect 
-----------------------------------------------------------------------------
-- This is ASPECT, the Advanced Solver for Problems in Earth's ConvecTion.
--     . version 2.2.0-pre (master, cf178d357)
--     . using deal.II 9.2.0-pre (master, e1068ad104)
--     .       with 32 bit indices and vectorization level 1 (128 bits)
--     . using Trilinos 12.8.1
--     . using p4est 2.0.0
--     . running in DEBUG mode
--     . running with 2 MPI processes
-----------------------------------------------------------------------------
Usage: ./aspect [args] <parameter_file.prm>   (to read …
```
> Avoid MPI error messages when calling 'aspect' without arguments.

- unit_tests/CMakeLists.txt
Newer versions of cmake produce a warning that the unittest cmake
project doesn't have a PROJECT() statement. Fix this.
> add cmake PROJECT directive

- source/simulator/solver_schemes.cc
I found this by chance, just to make the code consistent.
> Add missing braces around a case statement

- doc/modules/changes/20190917_naliboff
- include/aspect/material_model/rheology/strain_dependent.h
- source/material_model/rheology/strain_dependent.cc
This PR is a follow-up to #3219 and removes input parameters and related checks for the old strain softening syntax. This removes backward compatibility for the prior strain softening, but removes a significant amount of code and tricky logic.
> remove duplicate strain softening parameters

- include/aspect/postprocess/particles.h
- source/postprocess/particles.cc
This pull request fixes the vtu (and probably also for other formats) output for vectors made by the particle postprocessor. This was needed because deal.ii 9.1.0 changed from using `get_vector_data_ranges()` to `get_nonscalar_data_ranges()`.
> fix particle vector output for dealii 9.1.0

- source/simulator/core.cc
Work around deprecation warning: performance problem is not an issue as
we only do this in debug mode.
> deal.II master locally_owned_dofs_per_processor() warn

- source/simulator/stokes_matrix_free.cc
This adds mf=1 to the auto-generated link. This part is not parsed on
the website yet, but it doesn't hurt to have it in there already.
> CitationInfo: add matrix-free

- doc/modules/changes/20190922_naliboff
- include/aspect/material_model/latent_heat.h
- include/aspect/material_model/utilities.h
- include/aspect/simulator_access.h
- source/material_model/latent_heat.cc
- source/material_model/utilities.cc
- tests/latent_heat_pressure.prm
- tests/latent_heat_pressure/screen-output
- tests/latent_heat_pressure/statistics
First stab at moving the phase function routines over to the material model utilities. This needs to be implemented before proceeding further with #2656.
> Add phase_function material utilities

- source/boundary_composition/box.cc
- tests/compositional_boundary_values.prm
The boundary_composition/box plugin requires for each of its input parameters a list of as many entries as compositional fields, even if this parameter is never used because this boundary is not in the list of prescribed composition boundaries. This is not necessary and seems a bit silly when writing new parameter files. I removed that requirement (but still check the other parameters that are actually used). And I modified one of the tests that has only prescribed compositions on one boundary, but so far had to prescribe values for all of them.
> Do not require composition input parameter for not prescribed boundaries in box plugin

- source/simulator/stokes_matrix_free.cc
Also check preconditions coming from prms for matrix-free in release
mode by using AssertThrow instead of Assert.
> matrix-free: use AssertThrow

- source/simulator/stokes_matrix_free.cc
- tests/no_cheap_gmg.cc
- tests/no_cheap_gmg.prm
- tests/no_cheap_gmg/screen-output
- tests/no_cheap_gmg/statistics
The code in the Stokes solver was missing the throw to skip the cheap
solver if so desired by the user. As a consequence, we were always doing
1 cheap solver step. Fix this and add a test.
> GMG: allow no cheap iterations

- source/geometry_model/spherical_shell.cc
fix warning with gcc7:
```
source/geometry_model/spherical_shell.cc:187:67: warning: dereferencing
type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
subcell_data.boundary_quads.push_back(reinterpret_cast<CellData<2>&>(face));
```
> fix aliasing warning

- include/aspect/simulator.h
- include/aspect/stokes_matrix_free.h
- source/simulator/core.cc
- source/simulator/stokes_matrix_free.cc
- tests/hollow_sphere_gmg_q3.cc
- tests/hollow_sphere_gmg_q3.prm
- tests/hollow_sphere_gmg_q3/screen-output
First working version of higher order FEM support for the geometric multigrid solver. This requires introducing a base class for the StokesMatrixFreeHandler to be able to have the degree be a compile time template argument.
This PR works, but needs some cleanup (ordering of functions in .cc, possibly different class names, etc.) and tests. I can confirm that we get identical errors for the burstedde benchmark for Q3 between matrix-free and matrix-based.
@tcclevenger can you please take a look?
> implement higher order Stokes GMG

- .clang-tidy
- source/postprocess/visualization.cc
- source/simulator/core.cc
- source/simulator/lateral_averaging.cc
- source/simulator/nullspace.cc
- source/simulator/solver_schemes.cc
- unit_tests/additional_outputs.cc
- replace virtual with override
- enable clang-tidy rule
- rationale is here:
https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md
> use c++ override instead of virtual

- include/aspect/mesh_deformation/free_surface.h
- include/aspect/newton.h
- include/aspect/simulator/assemblers/interface.h
- include/aspect/stokes_matrix_free.h
- source/simulator/stokes_matrix_free.cc
- use =default if possible
- empty destructors in derived classes are not needed at all
> cleanup virtual destructors

- source/simulator/stokes_matrix_free.cc
- tests/shell_quarter_gmg.prm.dealii_9.2
- tests/shell_quarter_gmg/screen-output
This fixes a crash caused by confliciting constraints between no-normal
flux and Dirichlet as observed with a quarter_shell.
> matrix-free free-slip and no-slip conflict

- doc/modules/changes/20191019_jrobey
- source/volume_of_fluid/assembler.cc
- tests/vof_linear_inflow.prm
- tests/vof_linear_inflow/screen-output
Corrects the inflow boundary assembly calculations for VOF composition fields, and adds a basic test case to ensure that it does not break in the future.
> Correct inflow boundary condition for Volume of fluid method

- include/aspect/utilities.h
- source/utilities.cc
- unit_tests/parse_map_to_double_array.cc
This PR extends Utilities::parse_map_to_double_array to allow multiple entries per key using the syntax: `key1: value1|value2|value3, key2: value1, key3: value1|value2`. We would like to use this syntax to make progress with defining phase transitions for multiple compositional fields (like #2656). The unit tests should cover all cases, so I can make this as a separate PR without actual implementations using it (it will be used by several rheologies, equations of state and material models).
> Extend parse function to allow multiple values per key

- doc/modules/changes/20191030_glerum
- source/geometry_model/ellipsoidal_chunk.cc
- tests/natural_coordinates_conversion/screen-output
While updating my models, I realized that the order of the coordinates that are read in for `AsciiData` with an `EllipsoidalChunk` has changed; the `cartesian_to_natural_coordinates` function outputs radius, lat, lon. Looking into the geometry model, the comments (radius, lon, lat) do not seem to match the order of the coordinates used in the `cartesian_to_natural_coordinates` and `natural_to_cartesian_coordinates` functions (radius, lat, lon). 
As I think the order should be as written in the comments (radius, lon, lat), I've reordered the coordinates. However, the failure of the `natural_coordinates_conversion` test is now even worse, so @MFraters, do you think these changes are correct? Note that for an eccentricity of zero, the functions recover the original coordinates. 
@bobmyhill …
> Reverse order natural coordinates

- Jenkinsfile.cig
This should fix spurious tester failures with the unity build as observed in #3281. The problem arises, because compiling call files of ASPECT in a single file now requires > 7GB of RAM, and some of the tester machines only have 8 GB total (which also needs to hold the OS, Jenkins, etc). Whenever the tester needs to use swap space for frequently accessed data it does not finish in the wall time we set for the tester and so fails. This change splits the unity build into chunks of 100 files each (currently 3 chunks, for the 293 files it reports). This brings down maximum memory consumption from 7 GB to 4.6 GB on my system, and only increases the compile time slightly (from 2 minutes to 2:30 minutes).
The only drawback is that now a unity build with only a single chunk could fail, and we …
> Reduce memory consumption of unity build on tester

- source/simulator/core.cc
It turns out that constraints.is_consistent_in_parallel() is too eager
and gives false alarm if constraints differ by machine epsilon. For now,
just remove this call.
> remove constraint consistency check

- doc/modules/changes/20191010_naliboff
- include/aspect/material_model/drucker_prager.h
- include/aspect/material_model/dynamic_friction.h
- include/aspect/material_model/rheology/drucker_prager.h
- include/aspect/material_model/utilities.h
- include/aspect/material_model/visco_plastic.h
- source/material_model/drucker_prager.cc
- source/material_model/dynamic_friction.cc
- source/material_model/rheology/drucker_prager.cc
- source/material_model/utilities.cc
- source/material_model/visco_plastic.cc
This PR adds a new model in the `Rheology` namespace for Drucker Prager plasticity, which will replace the similar functionality in `MaterialUtilities`.
This is currently work in progress and I wanted to let @anne-glerum take a look before proceeding further. 
Remaining tasks and topics for discussion:
- Use the new functions in the `drucker_prager` and `viscoelastic_plastic` material models.
- Remove the related functionality in MaterialUtilities
- Consistently use "yield stress" or "yield strength"
- Rename various functions to be more intuitive/descriptive
- Simplify existing documentation and make code more readable
> add drucker prager rheology module

- include/aspect/global.h
These includes are already part of ` #include <deal.II/lac/generic_linear_algebra.h>` (in the line below) so no need to repeat them. I have checked that this works for deal.II 9.0 and current master. They are likely a remnant from an earlier version.
> Remove duplicated headers

- include/aspect/stokes_matrix_free.h
- source/simulator/stokes_matrix_free.cc
Reduce the storage of the matrix-free GMG Stokes setup by only storing one viscosity value for each cell instead of one viscosity value for each quadrature point. This was left over from old code where I was querying viscosity values from some functional representation on each level, not using averaging. When we update the code in the future to not requiring averaging, this may look different. In the meantime, this greatly reduces storage for the case of cell-wise coefficient averaging.
I did not create any new tests since this is not a new feature, and all tests currently using GMG should pass.
> reduce storage for matrix-free gmg

- benchmarks/check.sh
I noticed this while reviewing #3292. This benchmark was not in the check script and somehow we forgot to update its parameter file. This should fix it. Edit: ~~The tests will fail until #3292 is merged.~~
> Add missing benchmark to check script

- include/aspect/particle/world.h
- include/aspect/postprocess/particles.h
- include/aspect/simulator.h
- include/aspect/simulator_access.h
- source/postprocess/particles.cc
- source/simulator/core.cc
- source/simulator/simulator_access.cc
Currently the particle world is owned by the particle post-processor. This may have made sense in the beginning, but since particles can be active now it seems to make more sense to me for them to be part of the simulator. Furthermore, I am developing a plugin which needs access to up to date particle information. Currently this is only the case if the user provides that post processor after the particle post processor because the particle post-processor also moves and updates the particles.
Although further reorganization might we wanted in the future, this pull request is limited to just letting the simulator own the particle world and update the particles, so that the order given by the user of the post-processors do not matter any more.
I am still looking at a bug (there seems to be a …
> Move ownership and responiblity of particle world to simulator

- doc/release-tasklist
We forgot this for the last release.
> Add spack task to release list

- contrib/spack/spack.yaml
This adds a 'spack' configuration file into `contrib/`, which allows for an easy installation on systems that already contain spack. `spack install` executed in that folder will install ASPECT and all its dependencies, `spack install --only dependencies` will install only dependencies (dealii and the necessary packages). The benefit of this file over doing `spack install aspect` is that I can explicitly disable a lot of options in our dependencies, which greatly reduces the time for compiling, and the likelihood of compiler problems (e.g. version 5.3.0 of suite-sparse does not seem to work with the other packages so I had to manually specify a version). For now I would keep this hidden, but perspectively, I think spack is the more sustainable installation option compared to candi (but …
> Add spack installation file

- source/gravity_model/radial.cc
- source/gravity_model/vertical.cc
We usually use AssertThrow for checks depending on runtime parameters, because they can be triggered by changing a parameter file. These asserts were likely older than the convention.
> Make some runtime checks AssertThrow

- source/boundary_composition/box.cc
- source/boundary_composition/spherical_constant.cc
- source/boundary_composition/two_merged_boxes.cc
- source/boundary_temperature/box.cc
- source/boundary_temperature/dynamic_core.cc
- source/boundary_temperature/two_merged_boxes.cc
- source/boundary_traction/initial_lithostatic_pressure.cc
This is a follow-up to #3173 that replaces some more dynamic casts by the functions in the `Plugins` namespace. I also moved some geometry model checks into more appropriate functions (only check once per model run instead of every call).
> Replace dynamic_casts by proper function calls

- include/aspect/compat.h
- include/aspect/mesh_deformation/interface.h
- include/aspect/simulator_access.h
With deal.II-dev and gcc 8.3.0 I still get deprecation warnings complaining about the use of `ConstraintMatrix` despite the fixes in #2847 and #3172. Moving the fix into compat.h fixes it (likely it is now included everywhere, and before any other includes that might use it). I think this makes sense, because perspectively we want to remove this workaround, once we require 9.1 and have removed all usage of ConstraintMatrix from other parts of the code.
> Fix a deprecation warning with deal.II dev

- include/aspect/boundary_velocity/gplates.h
- include/aspect/gravity_model/vertical.h
- source/boundary_velocity/ascii_data.cc
- source/boundary_velocity/function.cc
- source/boundary_velocity/gplates.cc
- source/geometry_model/box.cc
- source/geometry_model/chunk.cc
- source/geometry_model/initial_topography_model/ascii_data.cc
- source/geometry_model/sphere.cc
- source/geometry_model/spherical_shell.cc
- source/geometry_model/two_merged_boxes.cc
- source/gravity_model/ascii_data.cc
- source/gravity_model/radial.cc
- source/gravity_model/vertical.cc
Follow-up to #3304. Replace some more dynamic_casts and simplify some checks. I replaced checks for specific geometry models with `natural_coordinate_system` wherever I was sure the functionality would work with any geometry model of that coordinate system someone could come up with. When I was unsure if that was true I left checks for specific geometry model plugins (like the initial topography).
> Replace some more dynamic_casts

- CMakeLists.txt
@gassmoeller found that compiling with an external world builder gave a error. It turned out I made a small mistake in the cmake file. This fixes it.
> Fix world builder external dir

- include/aspect/particle/world.h
Fix: warning: class template 'SimulatorSignals' was previously declared
as a struct template [-Wmismatched-tags]
Reported by clang-6
> fix warning for SimulatorSignals

- cookbooks/S20RTS.prm
This is not exactly a bug for this cookbook, but if you modify it for applications that rely on the reference profile we want to set the correct adiabatic surface temperature. I feel like having the wrong adiabatic profile is a classical bug in many of our models, we need to find a better way than this PR, but this is a start.
> Add adiabatic surface temperature to S20RTS cookbook

- source/mesh_deformation/free_surface.cc
When using PETSc for linear algebra, we use a function from namespace
SparsityTools. Make sure it is available.
> Add appropriate #include file.

- source/simulator/solver_schemes.cc
Follow up from #3109. Cleans up the `Single advection, iterated Newton Stokes` solver. My local machine shows changes for the test which are not significant. Want to see what the official tester returns before changing the test.
> Reuse Newton code for single advection iterated Newton Stokes code.

- source/simulator/solver.cc
- source/simulator/stokes_matrix_free.cc
We add an `AssertThrow(n_expensive_steps>0)` before starting the expensive Stokes solver. This just ensures we don't waste time by running the expensive solver with 0 max iterations if the user sets `Maximum number of expensive Stokes solver steps = 0`.
> Abort expensive solve if Maximum number of expensive Stokes solver steps = 0

- source/particle/generator/probability_density_function.cc
Follow up from #3349. Changes MPI_Scan to MPI_Exscan in the particle probability density function. Also renames variables to align better with the deal.ii code.
> Align particle prob. density function code with deal.ii.

- source/simulator/helper_functions.cc
If using a formulation like BA, we should use adiabatic density instead
of the real density to compute the conduction timestep.
part of #3335
> use reference density for conduction timestep

- source/simulator/helper_functions.cc
After looking at #3356 I noticed two things: 
1. We can potentially allow negative time step sizes if the material model hands over negative densities, specific heat capacities or thermal conductivities and the conduction time step is used. This is addressed in this PR by adding a new AssertThrow that also trigger in release mode.
2. The logic for limiting time steps at the end of this function was pretty hard to understand. I simplified it here. All of the functionality should be preserved (every condition change should be equivalent to the conditions before).
Let me know what you think.
> Simplify step limiting logic and add error message for negative timesteps

- benchmarks/free_surface_tractions/viscoelastic/README
- benchmarks/free_surface_tractions/viscoelastic/compare_VE_def.gnuplot
- benchmarks/free_surface_tractions/viscoelastic/compare_VE_def_profile.gnuplot
- benchmarks/free_surface_tractions/viscoelastic/compare_VE_def_profile_unloading.gnuplot
- benchmarks/free_surface_tractions/viscoelastic/compare_VE_def_unloading.gnuplot
- benchmarks/free_surface_tractions/viscoelastic/compare_VE_soln.py
- benchmarks/free_surface_tractions/viscoelastic/free_surface_VE_cylinder_2D_loading.prm
- benchmarks/free_surface_tractions/viscoelastic/free_surface_VE_cylinder_2D_loading_fixed_elastic_dt.prm
- benchmarks/free_surface_tractions/viscoelastic/free_surface_VE_cylinder_2D_loading_unloading.prm
- benchmarks/free_surface_tractions/viscoelastic/free_surface_VE_cylinder_3D_loading.prm
- benchmarks/free_surface_tractions/viscoelastic/free_surface_VE_cylinder_3D_loading_fixed_elastic_dt.prm
- benchmarks/free_surface_tractions/viscous/README
- benchmarks/free_surface_tractions/viscous/compare_viscous_def.gnuplot
- benchmarks/free_surface_tractions/viscous/compare_viscous_def_profile.gnuplot
- benchmarks/free_surface_tractions/viscous/free_surface_viscous_cylinder_2D_loading.prm
- benchmarks/free_surface_tractions/viscous/free_surface_viscous_cylinder_3D_loading.prm
- doc/modules/changes/20200205_clerc
This pull request add an exception to allow boundary tractions to be applied on the free surface. It also includes benchmarks for the surface deformation of viscous and viscoelastic materials in response to surface loading.
> Free surface tractions

- include/aspect/newton.h
- source/material_model/rheology/elasticity.cc
- source/simulator/assemblers/newton_stokes.cc
This PR enables additional RHS terms, including elasticity, in the Newton solver assembly. 
As the `viscoelastic` and `viscoelastic_plastic material` model currently do not setup the Newton derivatives, this PR should wait until #3306 is merged and this is rebased on top of it. 
The single added test using the Newton solver is a cheat in that only one nonlinear iteration is performed and thus no call to assemble derivatives is required.
@MFraters - opening this so you can take a look.
> [WIP] Enable additional RHS terms and elasticity in Newton solver

- tests/viscoelastic_plastic_brick_extension.prm
This PR is part of the preparation for the update to the visco_plastic material model in #3306. 
The test parameter file updated here is derived from the `kaus_2010_extension benchmark`, which uses the viscoelastic_plastic material model. In #3306 this benchmark will be modified to use the visco_plastic material, but for a short period we are going to keep the viscoelastic_plastic material for testing purposes. This change ensures continuity of the test suite and allows for easier comparisons of test results in #3306.
> update vep test parameter file

- include/aspect/geometry_model/chunk.h
- source/geometry_model/chunk.cc
I am looking at the ChunkGeometry manifold as possible reason for the issues in #3359, but for easier testing (additional PR with tests incoming) I need the manifold declaration to be available outside of the geometry model class (also moving this class declaration into a namespace internal is closer to our usual style). This PR is no-op, only moving a declaration, no changes to functionality have been made.
> Move ChunkGeometry into an internal namespace

- source/mesh_deformation/function.cc
- source/mesh_deformation/interface.cc
While looking into #3359 I came across these function calls that omit the mapping when interpolating boundary values. It does not fix the problems there, and it may not be a problem at all as we use a MappingQ1Eulerian for free surface at the moment, but it might be one in the future if we change that, or it might already be one if the mesh is already deformed? In the past we had some hard to find bugs because of forgotten mapping arguments, so I thought I better add these. Not sure if the tester will find a difference, lets see.
> Add mapping as argument to some boundary value calls

- doc/options.dox
The flag in question determines the doxygen output directory if one
generates LaTeX output -- which is not something that we probably want
to do, but it's still worth giving the flag a meaningful directory
name. (The previous value, 'me-latex', refers to the 'multiple experiment
inverse problem' code I wrote during my PhD thesis and from which this
options.dox file apparently derives.)
> Fix a doxygen flag.

- include/aspect/utilities.h
- source/utilities.cc
> Avoid a function if deal.II has a substitute.

- source/particle/generator/interface.cc
- source/particle/integrator/interface.cc
- source/particle/interpolator/interface.cc
- source/particle/property/interface.cc
As title states. Follow up from discussion in #3383
> Ensure three lines between function defintions in particle interface files

- source/simulator/checkpoint_restart.cc
- source/simulator/helper_functions.cc
This is a follow-up to #3389, implementing a suggestion by @maxrudolph. Let's see what the tester says here.
/rebuild
> Immediately overwrite the statistics file upon restart.

- include/aspect/simulator.h
- source/simulator/helper_functions.cc
- tests/advection_reaction/screen-output
- tests/average_density_boundary_fluid_pressure/screen-output
- tests/exponential_decay/screen-output
- tests/global_latent_heat/screen-output
- tests/heat_advection_by_melt_operator_splitting/screen-output
- tests/latent_heat_melt_operator_split/screen-output
- tests/latent_heat_melt_transport/screen-output
- tests/mass_reaction_term/screen-output
- tests/melt_and_traction/screen-output
- tests/melt_transport/screen-output
- tests/melting_rate_operator_splitting/screen-output
- tests/melting_rate_operator_splitting2/screen-output
- tests/mid_ocean_ridge/screen-output
- tests/prescribed_stokes_solution_melt/screen-output
- tests/rising_melt_blob_freezing/screen-output
- tests/shear_heating_with_melt/screen-output
This refactors the operator splitting functionality and includes the changes from #3167. #3167 should be merged first, as it contains changes to the test results. 
This PR should not create any changes. It usually saves 50% of the operator splitting time, because if the temperature and composition element are identical we can skip a lot of the duplicated computations.
This addresses a part of #1867.
> Refactor operator splitting function

- Jenkinsfile.cig
The coveralls step is not useful to run if tests failed, so only run on
success. This fixes the problem that clicking on details of a failed run
no longer shows thousands of output lines from coveralls, that are
difficult to hide to see the actual error.
> Jenkins: ignore coveralls failure

- source/initial_temperature/S40RTS_perturbation.cc
- source/initial_temperature/SAVANI_perturbation.cc
- avoid copying std::vectors containing the coefficient data at each
evaluation point
- minor cleanup
> S40RTS/SAVANI: avoid data copies and cleanup

- source/simulator/assemblers/stokes.cc
- source/simulator/assembly.cc
- source/simulator/core.cc
- source/simulator/melt.cc
This is a follow up to #3404, which makes similar improvements to the coupling of the preconditioner matrix. It turns out we allocate the A block of the preconditioner matrix even if we use the system matrix for the preconditioner in the end.  Additionally, we also assemble the preconditioner A block for free surface models and for melt models, even though we use the system matrix block for the preconditioner. This PR should save some memory and some time in the assembly for all melt and free surface models.
> Improve preconditioner coupling and assembly

- source/simulator/core.cc
Introduce a switch for the newly introduced helper functions. This makes
the code longer, but will be easier to maintain as it will trigger an
exception when a new solver type is implemented.
> use switch for solver-type check

- include/aspect/melt.h
- source/simulator/core.cc
- source/simulator/melt.cc
- source/simulator/solver.cc
- source/simulator/stokes_matrix_free.cc
This PR removes the reconstruction of a matrix block whenever the fluid velocity is solved, and instead uses the existing system matrix (as for all other solution variables we have). This means the memory is allocated permanently than just while solving for the fluid velocity, but in some sense that is more consistent with the other blocks (and also does not change the maximum amount of memory allocated during the whole run).
> Reuse system matrix for melt solver

- doc/manual/citing_aspect.bib
This paper actually appeared in 2018 and is listed further down below.
While there, also fix a comma issue.
Fixes #3423.
> Remove a duplicate citation.

- doc/modules/changes/20200319_glerum
- source/material_model/visco_plastic.cc
The PlasticAdditionalOutputs output the internal angle of friction in radians. This PR outputs them in degrees, which is more intuitive. I don't think it will break any tests, because I didn't see any that combines a nonzero friction angle with named additional output and compares the gnuplot output.
> Output degrees instead of radians

- doc/modules/changes/20191029_gassmoeller_2
- include/aspect/material_model/equation_of_state/interface.h
- include/aspect/material_model/equation_of_state/multicomponent_incompressible.h
- include/aspect/material_model/utilities.h
- include/aspect/material_model/visco_plastic.h
- source/material_model/equation_of_state/interface.cc
- source/material_model/equation_of_state/multicomponent_incompressible.cc
- source/material_model/latent_heat.cc
- source/material_model/utilities.cc
- source/material_model/visco_plastic.cc
- tests/visco_plastic_derivatives_2d.cc
- tests/visco_plastic_derivatives_3d.cc
- tests/visco_plastic_phases.prm
- tests/visco_plastic_phases/screen-output
- tests/visco_plastic_phases_compositions.prm
- tests/visco_plastic_phases_compositions/screen-output
This PR builds on #3271 and #3267 and shows how the implemented improvements can be used. In this example it implements simple phase transitions for the equation of state that is used by the visco_plastic material model. This PR in itself is useful, but it is mostly meant as a starting point for @naliboff and @mibillen to start implementing this functionality for the rheology modules they want to use with phase transitions.
> Use phase functions for EoS in visco_plastic material model

- source/simulator/stokes_matrix_free.cc
- tests/nonlinear_channel_flow_velocities_Newton_Stokes_GMG/screen-output
Updates the Chebyshev parameters for the Coarse GMG solver. Previously, the coarse solver contained a full CG solve of eigenvalues. This is not an issue on meshes with small coarse levels, but is quite slow otherwise. 
An example of the time saved (over 4x faster) is discussed in https://github.com/geodynamics/aspect/pull/3382.
All current GMG tests should have the same output (or slightly lower iteration counts).
> update chebyshev parameters

- include/aspect/material_model/rheology/elasticity.h
- source/material_model/rheology/elasticity.cc
- source/material_model/visco_plastic.cc
Seen while looking into #3184. This deduplicates some code and moves a bit of code inside `elastic.cc` so that it is available for all material models using elastic rheologies.
> Refactor viscoelastic computations

- doc/modules/changes/20200330_jeanniot
- include/aspect/postprocess/gravity_point_values.h
- source/postprocess/gravity_point_values.cc
This PR just changes the precision of gravity written in the output of the gravity_point_values postprocessor to 12 instead of 18. 
The tests were not altered by this change.
> Set the precision of gravity to 12 in gravity_point_values postprocessor

- source/simulator/assembly.cc
- source/simulator/stokes_matrix_free.cc
- tests/prescribed_dilation_gmg.cc
- tests/prescribed_dilation_gmg.prm
- tests/prescribed_dilation_gmg/screen-output
- tests/simple_compressibility_iterated_stokes_gmg.cc
- tests/simple_compressibility_iterated_stokes_gmg.prm
- tests/simple_compressibility_iterated_stokes_gmg/screen-output
- tests/steinberger_compressible_gmg.prm.dealii9.2
- tests/steinberger_compressible_gmg/screen-output
- tests/steinberger_compressible_gmg/statistics
Two fixes are required for `StokesMatrixFree::correct_stokes_rhs()` function. 
1. When the variable `Simulator::do_pressure_rhs_compatibility_modification = true`, `make_pressure_rhs_compatible()` must  be called before adding the rhs correction to `system_rhs`. 
2. For compressible computations, the `2*eta/3*div` term needs to be included in the residual computation for the rhs correction. This was an oversight for this function and did not show up since I only had compressible tests with Zero or Tangential boundary (`correct_stokes_rhs()` is not necessary in that case).
I added two tests, prescribed_dilation_gmg and simple_compresssibility_iterated_Stokes_gmg. Both require fix 1. Fix 2. is required by simple_compresssibility_iterated_Stokes_gmg as it is a compressible computation with …
> fix GMG for compressible computations - correct_stokes_rhs()

- source/simulator/assembly.cc
Fix for a Trilinos amg bug. 
If you do a Stokes solve with the AMG preconditioner where an mpi rank owns 0 DoFs, Trilinos gives either an error (version 12-10-1) or a warning (version 12-18-1) when initializing the preconditioner:
**trilinos-12-10-1:**
ML::FATAL ERROR:: 1, /hdscratch/shared/libs-candi-9.1.1-r2/tmp/unpack/Trilinos-trilinos-release-12-10-1/packages/ml/src/Utils/ml_MultiLevelPreconditioner_NullSpace.cpp, line 98
**trilinos-12-18-1:**
WARNING:  When no nullspace vector is specified, the number
of PDE equations must equal the nullspace dimension.
This pull request gets around this by only setting the `constant_modes` on ranks which own DoFs. Eventually, maybe the fix should instead be in deal.II (either return empty in `DoFTools::extract_constant_modes` or change the …
> fix trilinos amg bug

- source/boundary_velocity/gplates.cc
In particular, use the 3-empty-line rule between functions.
/rebuild
> Make spacing in one file more uniform.

- doc/parameter_view/run.sh
Chrome can not open .xls from file:// urls locally for security reasons.
Add a simple shell script to launch the browser.
> parameter_view: add run.sh script

- source/simulator/checkpoint_restart.cc
- source/simulator/parameters.cc
- source/termination_criteria/user_request.cc
Found while looking into #3468. This replaces some checks for the existence of files with the `Utilties::fexists` function.
> Use Utilities::fexists where appropriate

- benchmarks/nonlinear_channel_flow/simple_nonlinear.cc
- benchmarks/shear_bands/shear_bands.cc
- benchmarks/tosi_et_al_2015_gcubed/tosi.cc
- cookbooks/morency_doin_2004/morency_doin.cc
- include/aspect/material_model/interface.h
- source/material_model/depth_dependent.cc
- source/material_model/diffusion_dislocation.cc
- source/material_model/drucker_prager.cc
- source/material_model/dynamic_friction.cc
- source/material_model/grain_size.cc
- source/material_model/interface.cc
- source/material_model/melt_global.cc
- source/material_model/melt_simple.cc
- source/material_model/rheology/elasticity.cc
- source/material_model/rheology/strain_dependent.cc
- source/material_model/steinberger.cc
- source/material_model/visco_plastic.cc
- tests/grain_size_latent_heat.cc
- tests/latent_heat_enthalpy.cc
- tests/nonlinear_convergence_for_small_composition.cc
- tests/shear_thinning.cc
- tests/spiegelman_fail_test.cc
- tests/velocity_divergence.cc
Follow up to #3456, which allows to tell a material model which properties to compute, and for a material model to find out which properties are requested. This is implemented so that no current functionality should break. In later PRs I would suggest the following:
> Allow requests for material properties

- .gitignore
Add folders output* in any location of the repo to the ignore list. I
often create top-level folders for specific problems and end of with two
many untracked files.
> .gitignore output folders

- source/material_model/visco_plastic.cc
To get an informative error message for the combination
`set Strategy                                 = minimum refinement function, viscosity `
`set Skip solvers on initial refinement       = true`
`set Skip setup initial conditions on initial refinement = true`
which leads to zero temperatures in the pre-refinement phase, which are not allowed when computing the viscosity in the visco_plastic material model. Viscosity is however requested by the refinement strategy. In parallel release mode, the model just hangs at the moment.
> Make Assert AssertThrow in vp 

- include/aspect/stokes_matrix_free.h
- source/simulator/stokes_matrix_free.cc
- tests/nonlinear_channel_flow_velocities_Newton_Stokes_GMG/screen-output
Reduces the storage requirement for the `block GMG` Stokes solver. Now, only 1 active level coefficient table needs to by stored instead of 3 (was 1 for each StokesOperator, ABlockOperator, and MassMatrixOperator), and only 1 multievel set of coefficient tables needs to be stored instead of 2 (was 1 for each ABlock GMG and SchurComplement GMG).
This is not too consequential for the current setup (cellwise constant viscosity), but will be necessary for the initial version of DGQ1 viscosity. The pull request for the DG1 projected viscosity will be able to be submitted once this change is incorporated.
> reduce gmg storage

- include/aspect/utilities.h
- source/simulator/initial_conditions.cc
- source/utilities.cc
From https://github.com/geodynamics/aspect/pull/3495. This `project_cellwise` function computes a DGQ1 projection of a set of input values given in the std::function into a given vector. 
We will use this in the Q1 viscosity for GMG, and it is used once now in the code (DGQ1 pressure). I did not write a test, since every test which has `set Use locally conservative discretization = true` will be reliant on this code and will pass now if this is implemented correctly.
> add project_cellwise function

- source/utilities.cc
The class `AsciiDataLookup` stores its data internally in either a `InterpolatedUniformGridData` or a `InterpolatedTensorProductGridData` object. Both classes have the following clause in their documentation for `get_gradients`:
```
* @param component The vector component. Since this function is scalar,
* only zero is a valid argument here.
```
Previously we called this function also with other components, because the function implementation mixed up the component of `AsciiDataLookup` (which depends on the number of columns in the data file), and the component of the internally stored tables (each of the n_components tables only stores a single component).
I suspect this was not discovered earlier, because this function is rarely used, and if so, it was so far only used to compute the …
> Fix call to AsciiDataLookup::get_gradients()

- source/material_model/visco_plastic.cc
- tests/visco_plastic_derivatives_2d.cc
- tests/visco_plastic_derivatives_2d/screen-output
- tests/visco_plastic_derivatives_3d.cc
- tests/visco_plastic_derivatives_3d/screen-output
- tests/visco_plastic_newton_nonlinear_channelflow.prm
- tests/visco_plastic_newton_nonlinear_channelflow/screen-output
in pull request #3460 a discussion came up about the 0.5 in the finite difference terms. This discussion was concluded that the 0.5 should be there. During that discussion I looked at the visco plastic material model for reference, and noticed that it wasn't there while it should be. 
I have done some testing to convince myself that this is actually better, and that was harder then expected. For the simple "compex" cases it converges very vast anyway or not at all anyway. The nonlinear channel flow was actually a nice in between case, where I could study the actual impact of adding the 0.5. The conclusion is that sometimes it is better, sometimes it is worse, but without the 0.5 the SPDness is lost. Without the 0.5 every now then the assert
```
The violated condition was: …
```
> Fix visco plastic finite difference

- source/mesh_deformation/function.cc
I added a sentence to the description of the Boundary function mesh deformation plugin to explain that the velocity should always be given in m/s, even if Use years in output instead of seconds = true. I didn't see a quick fix as the function is directly given to the interpolate_boundary_values function.
> Add info unit boundary velocity

- source/simulator/stokes_matrix_free.cc
From issue https://github.com/geodynamics/aspect/issues/3512, the iteration counts for Stokes would increase when running in parallel on spherical mesh with Tangential boundary. Simple fix: ~~when~~ after constructing the diagonal of the A block operator (used in GMG smoothers), ~~we needed to loop over all owned and ghost cells (previously just looped over owned cells)~~, we need to call `compress()` to exchange contribution from ghosted cells (previously only contributions from owned cells were accounted for).
There is actually already a test (`shell_3d_gmg.prm.dealii_9.2`), but I believe that since it is only on version dealii9.2 it wasn't being run and the high iteration counts were overlooked.
> Fix tangential BCs for GMG

- doc/manual/citing_aspect.bib
This addresses #3517 and adds a few more publications. 
This list is probably not complete, I only checked for the last two years, going through the list of papers referencing our 2017 paper to check if they were using ASPECT.
> add publications from 2019 and 2020

- doc/parameter_view/parameters.js
the fancy logic to call the autorun function doesn't work in firefox causing expand/collapse not to work.
Fix this.
> fix parameter_view in firefox

- doc/modules/changes/20200525_clevenger
- include/aspect/parameters.h
- source/simulator/parameters.cc
- source/simulator/stokes_matrix_free.cc
- tests/nsinker_gmg_idr.cc
- tests/nsinker_gmg_idr.prm.dealii_9.2
- tests/nsinker_gmg_idr/screen-output
This pull request adds the IDR(s) solver discussed in Chapter 5 of my [PhD thesis](https://tigerprints.clemson.edu/all_dissertations/2523/) and section 3.4 of the [GMG Stokes paper](https://arxiv.org/pdf/1907.06696.pdf) @tjhei and I wrote (under review). Here is a summary chart from the preprint for IDR(2) compared with GMRES, as well as a scaling plot of IDR(2) (I think these are the largest runs done with ASPECT, even if they aren't that interesting scientifically).
Summary: Around the same cost as GMRES, but much less memory required (roughly 1/3 in the example above). There is no convergence guarantee like GMRES, but various papers suggest the behavior is similar to GMRES as `s` is increased.
> add IDR(s) Stokes Kylov solver

- include/aspect/geometry_model/ellipsoidal_chunk.h
- source/geometry_model/ellipsoidal_chunk.cc
This PR avoids getting stuck into a loop when reading ascii data, which requires converting points to natural coordinates, which requires knowing the topography which is being read from the ascii data. Same change as was made to the chunk geometry. 
Actually using AsciiDataBoundary for the EllipsoidalChunk will require some changes to utilities.cc
> Bypass topography in coordinate conversion

- include/aspect/heating_model/interface.h
fix clang warning
'aspect::HeatingModel::HeatingModelOutputs' that has virtual
functions but non-virtual destructor [-Wdelete-non-virtual-dtor]
There is no reason to have a virtual function in this struct.
> fix HeatingModelOutputs warning

- include/aspect/particle/property/interface.h
- source/particle/property/interface.cc
This follows a discussion with @naliboff. The current interface for updating particle properties does not give information about which cell the current particle is in, which e.g. prevents particle properties from calling some material models to figure out properties. I think we need to extend our current interface for that, and there is no reason particle properties should not know all information about the particle they are currently updating. 
In theory we could use the same interface as postprocessors (handing over a `DataPostprocessorInputs::Vector<dim>` input argument) or as the material model (handing over a `MaterialModelInputs` argument), but I think changing the interface as little as possible with just the small addition of handing over the particle iterator -- instead of the …
> Extend particle property update interface

- include/aspect/postprocess/visualization/geoid.h
- source/postprocess/geoid.cc
- source/postprocess/visualization/geoid.cc
This PR adds the geoid citation info per discussion with Timo and Rene.
I put a call to geoid citation at both the main geoid postprocessor (parse prm section) and the geoid visualization postprocessor which calls the main geoid function.
Feel free to let me know whether I did this correctly.  @tjhei @gassmoeller
> Add geoid citation info

- cookbooks/prescribed_velocity/prescribed_velocity.cc
with 64 bit indices, compilation fails.
> fix cookbooks/prescribed_velocity/ in 64 bit mode

- source/geometry_model/ellipsoidal_chunk.cc
- source/initial_temperature/lithosphere_mask.cc
- source/postprocess/geoid.cc
- source/postprocess/visualization/temperature_anomaly.cc
Warnings reported by gcc10. These are irrelevant as the plugins only work for dim==3.
> avoid invalid arrary access warnings

- include/aspect/compat.h
- source/mesh_deformation/interface.cc
- source/simulator/core.cc
deal.II master removed the deprecated ZeroFunction outside the
Functions namespace.
> use proper namespace for ZeroFunction

- benchmarks/check.mk
- benchmarks/slab_detachment/slab_detachment.prm
fix benchmarks/slab_detachment/ data directory
only run specific prms in rayleigh_taylor_instability and sinking_block
> fix several benchmarks

- benchmarks/entropy_adiabat/entropy_adiabat.prm
- doc/update_scripts/prm_files/update_prm_files_to_2.0.0.sed
- doc/update_scripts/prm_files/update_prm_files_to_2.0.0_model_settings.sed
- tests/visco_plastic_newton_nonlinear_channelflow.prm
The script to update parameter files to more recent versions did use GNU sed extensions that are not available on MacOS leading to broken files (see #2347). This PR fixes some of the issues.
> Make parameter file update script work on Mac

- benchmarks/viscoelastic_beam_modified/20km_opentopbot.prm
this fixes the error
Boundary indicator <2> with symbolic name <bottom> is listed as having more than one type of velocity or traction boundary condition in
the input file.
> fix benchmarks/viscoelastic_beam_modified

- CMakeLists.txt
- source/simulator/melt.cc
Necessary to make CMAKE_UNITY_BUILD work. I am not quite sure why explicit instantiations for ``Simulator`` and ``AdvectionField`` need to be in the same file, but this is the only way I could make it work with and without unity build.
related to #3585
> unity build fixes

- benchmarks/tosi_et_al_2015_gcubed/tosi.cc
- include/aspect/geometry_model/two_merged_boxes.h
- source/boundary_traction/initial_lithostatic_pressure.cc
- source/geometry_model/initial_topography_model/ascii_data.cc
- source/geometry_model/initial_topography_model/function.cc
- source/geometry_model/two_merged_boxes.cc
- source/initial_temperature/adiabatic.cc
- source/initial_temperature/harmonic_perturbation.cc
- source/particle/world.cc
- source/utilities.cc
Separate two merged boxes from box geometry model and define a independent height_above_reference_surface function.
I found that the world builder didn't work for a model anymore where I did work before, and it turned out that due to pull request #3378, now the wrong height above the surface was passed (always 0) because the two merged boxes relied on the function from the box model, which relied on a point variable which was never filled in the two merged boxes model. To prevent these kind of problems in the future I separated them.  
I have not added a test yet, but will do that later.
> separate two merged boxes from box geometry model

- benchmarks/rigid_shear/plugin/rigid_shear.cc
- include/aspect/postprocess/particles.h
- include/aspect/simulator_access.h
- source/postprocess/particles.cc
- source/simulator/simulator_access.cc
Found while working on #3587. Simulator_access.h already has a forward declaration and most users of the header do not need this expensive include. Some may rely on it (though I find it reasonable to expect from a particle plugin to include `particle/world.h`).
> Remove unnecessary include from simulator_access.h

- CMakeLists.txt
See the discussion in #3585. We could also enable this unconditionally as long cmake supports it. Or we keep it like this for now and enable it by default later.
> Use native cmake to precompile headers

- doc/modules/changes/20200706_tjhei
see #3587 and #3585 for details.
For the record (old vs precompiled headers+unity builds):
~/aspect-git/build-nounity $ time ninja -j 16
real    3m25.492s
~/aspect-git/build-unity $ time ninja -j 16
real    0m54.797s
or a 3.6x faster build.
> add unity build changelog entry

- CMakeLists.txt
This was reported by Kiran Chotalia for cmake version 3.15.6. Our current cmake check tries to precompile headers for this version, but the feature is only available starting with 3.16. Ideally we would like to use `CMAKE_VERSION VERSION_GREATER_EQUAL 3.16`, but `VERSION_GREATER_EQUAL` is only available since cmake version 3.7 (and we allow versions since 2.8.12). This workaround fixes the problem (as long as cmake never releases a version 3.15.100).
> Fix cmake version check in CMakeLists.txt

- benchmarks/rigid_shear/plugin/rigid_shear.cc
- include/aspect/particle/property/composition.h
- include/aspect/particle/property/integrated_strain.h
- include/aspect/particle/property/integrated_strain_invariant.h
- include/aspect/particle/property/melt_particle.h
- include/aspect/particle/property/pT_path.h
- include/aspect/particle/property/position.h
- include/aspect/particle/property/velocity.h
- include/aspect/particle/property/viscoplastic_strain_invariants.h
- source/particle/property/composition.cc
- source/particle/property/integrated_strain.cc
- source/particle/property/integrated_strain_invariant.cc
- source/particle/property/melt_particle.cc
- source/particle/property/pT_path.cc
- source/particle/property/position.cc
- source/particle/property/velocity.cc
- source/particle/property/viscoplastic_strain_invariants.cc
This PR updates the particle property plugins to use the new interface function introduced in #3482, no functional changes are expected. The old function is already deprecated. This will be necessary to address a question raised in #3598. I will open a follow-up PR in which the connection will become more clear.
> Use new particle property interface

- include/aspect/material_model/visco_plastic.h
- include/aspect/particle/property/viscoplastic_strain_invariants.h
- source/material_model/visco_plastic.cc
- source/particle/property/viscoplastic_strain_invariants.cc
This PR sits on top of #3612 and allows to input more properties into the `ViscoPlastic::is_yielding` function as is necessary for #3598. I have checked that the version of this function in this PR is as fast as the one in master (this is important because this function is called once per particle per timestep and can become very expensive).
> Update visco plastic is yielding

- Jenkinsfile.cig
This was switched on before #3583 and it turns out some of the older CIG test agents can not finish compiling in 30 minutes without the setting (e.g. seen in #3598). Since the 'OFF'/'OFF' (precompiling headers/unity build) option is already tested on jenkins.tjhei.info, we can probably enable it here. The alternative is to increase the walltime limit and wait for a long time for some PRs.
> Enable precompiling headers on CIG testers

- .github/workflows/linux.yml
As discussed during the meeting today.
This CI job runs unconditionally in about 12 minutes and checks indentation, compilation (unity build), and documentation. This will help us with rapid iteration for pull requests but our own testers are obviously required before merging anything.
Github actions currently runs 20 concurrent linux jobs for open source projects.
> CI: add github actions

- doc/update_parameters.sh
Round parenthesis in bash open a subshell, so the outer script doesn't
exit. Replace by curly to make that work.
> fix error handling in update_parameters.sh

- .github/workflows/linux.yml
- doc/update_parameters.sh
1. Disable openmpi warning for the github actions run (breaks documentation and is detected with the merge of #3622)
2. Output the .dot file if generation fails to help with this in the future.
> CI: fix github actions update_parameters.sh

- Jenkinsfile.cig
The cookbook testing phase introduced in #3621 does not finish in time on the slow testers (see some of the other current PRs). Reduce concurrency and increase acceptable runtime.
> Fix cookbook phase for slow testers

- source/main.cc
The deal.II ubuntu package is
/lib/x86_64-linux-gnu/libdeal.ii.g.so.9.2.0
so the detection for library mismatch between plugin and binary fails.
Fix this.
> fix conflicting lib detection for deal.II ubuntu package

- tests/parallel_refine_crash.prm
- tests/vof_mpi_amr_no_dof.prm
This is just a test to see how much time this limitation saves on the slower jenkins agents. Obviously these test do not work any more with the new settings (they specifically test problems with many MPI ranks).
> Limit number of MPI ranks for tests

- .github/workflows/linux.yml
- add second github actions to do a build without unity/precompiled
header
- also run the unittests
as discussed with @gassmoeller
> github-actions: test no-unity build and unittests

- include/aspect/volume_of_fluid/utilities.h
- source/volume_of_fluid/setup_initial_conditions.cc
- source/volume_of_fluid/utilities.cc
- tests/vof_err_calc.h
I think @tjhei was also working on this, but I haven't seen his patch posted yet and mine was nearly ready. So here it goes: Use overloads instead of explicit specializations to avoid having to use declarations of the explicit specializations. The previous code was wrong according to the C++ standard, but most compilers accept it anyway.
/rebuild
> Fix a problem with template explicit specializations.

- Jenkinsfile
- Jenkinsfile.cig
- tests/cmake/default
- tests/zero_matrix/screen-output
We added the unity build to github actions in #3636, so we can remove it
from Jenkins to improve CI times:
- remove unity build from both jenkins
- take over some changes from cig->tjhei
- rename build directory
part of #3630
> jenkins: remove unity build

- Jenkinsfile
If it is not a change request, allow running Jenkins (master, other
branches, tags) unconditionally.
> jenkins: allow running on release branches

- CMakeLists.txt
This should fix instantiation warnings/errors
part of #3633
fixes #3651 
closes #3650 (better alternative)
related to #3637
> unity: move some files to the end

- source/material_model/visco_plastic.cc
This parameter is declared twice, once in `EquationOfState::MulticomponentIncompressible<dim>::declare_parameters (prm);` (a few lines above) and again here. It is not actually used in `ViscoPlastic`, so remove it.
> Remove unused input parameter

- include/aspect/postprocess/visualization/stress.h
We had copied this file from the "shear stress" postprocessor but forgot to adjust the documentation. Fix this.
> Fix documentation.

- .gitignore
We really do just one `*`, `**` is for recursive matching of directories.
> Fix .gitignore.

- include/aspect/material_model/viscoelastic.h
doxygen is unhappy with the existing two backslashes...
> No need to have two backslashes in .h file documentation.

- .github/workflows/linux.yml
Server seems to be unreliable. Use a github.com mirror instead.
> github actions: do not download from sourceforge.net

- doc/manual/parameters.tex
- source/material_model/composition_reaction.cc
This PR starts to address Issue #3046 by using proper markup for units in parameter descriptions, using the latex package siunitx (already a dependency for the manual).
Currently, this PR has only changed the descriptions in composition_reaction.cc. 
If this method is approved, then I'll work on doing the same for the other descriptions.
> markup for units in composition reaction

- source/mesh_deformation/interface.cc
Point is that we can get the same information via `SimulatorAccess`, and should do so.
> Lessen reliance on a friend declaration.

- doc/manual/citing_aspect.bib
This has a numerous miscellaneous corrections discovered while parsing the citing_aspect.bib file. 
Changes include:
- adding missing commas in multiple places
- adding 'school' attribute to Robey Thesis
- changing Bangerth2017a from type techreport to misc to be consistent with figshare (note consistent with manual.bib)
- updated Muluneh 2020
> Fixes and updates to citing_aspect.bib

- tests/normalize.pl
The current version happens to not show the file that can't be opened, and leads to a rather
confusing error message that took me a good long while to understand.
> Fix an error message in normalize.pl.

- source/mesh_deformation/interface.cc
- source/simulator/checkpoint_restart.cc
This would supersede #2983 . 
At the moment I want to see what the tester says, because on my machine all free surface tests fail, while on @gassmoeller 's machine only 1. Only one of my tests seems to really produce different results tho, but this is another test than Rene's.  
Edit: All free surface tests pass on the tester except where a computation is resumed from snapshot. Some of the tests include adaptive mesh refinement. This therefore seems to work with the new location of the setting of the pointer.
> [WIP] Move set pointer to mapping

- source/utilities.cc
Currently, the 'Data file name' parameter in the AsciiDataBase class describes files for the quantities computed on the boundary. This description is not correct for initial temperature/composition plugins, which use this class. This PR overwrites the 'Data file name' parameter in AsciiDataBoundary Class and generalizes the 'Data file name'  parameter in AsciiDataBase.
> Modify documentation of filename in asciiboundary.

- source/material_model/rheology/strain_dependent.cc
```
[127/297] Building CXX object CMakeFiles/aspect.dir/source/material_model/rheology/strain_dependent.cc.o
/home/bangerth/p/deal.II/1/projects/aspect/source/material_model/rheology/strain_dependent.cc: In instantiation of ‘std::array<double, 3> aspect::MaterialModel::Rheology::StrainDependent<dim>::compute_strain_weakening_factors(unsigned int, const std::vector<double, std::allocator<double> >&) const [with int dim = 2]’:
/home/bangerth/p/deal.II/1/projects/aspect/source/material_model/rheology/strain_dependent.cc:552:5:   required from here
/home/bangerth/p/deal.II/1/projects/aspect/source/material_model/rheology/strain_dependent.cc:357:31: warning: missing braces around initializer for ‘std::__array_traits<double, 3>::_Type {aka double [3]}’ [-Wmissing-braces]
std::array<double, 3> …
```
> Avoid a warning about missing braces.

- source/mesh_deformation/interface.cc
- tests/free_surface_tangential_mesh_velocity_2.prm
- tests/free_surface_tangential_mesh_velocity_2/screen-output
- tests/free_surface_tangential_mesh_velocity_2/statistics
Found while looking into #3407. If we apply tangential mesh constraints to the same boundary that has some other prescribed mesh deformation (e.g. tangential movement) we try to increment an iterator after it was invalidated by erasing its target. This application is very rare.
> Fix use of invalid iterator

- CMakeLists.txt
- contrib/world_builder/source/features/fault.cc
- contrib/world_builder/source/features/oceanic_plate.cc
- contrib/world_builder/source/features/subducting_plate.cc
After the suggestion of @tjhei I played around with the unity build for the world builder inside aspect a bit, and the fixes where very simple. It does require some changes to the world builder source files, but that only includes clarifying the scope (I am not sure why that was a problem for the unity build). Normally I would be really hesitant to have any changes in the world builder in ASPECT, without going to a newer version of the world builder, but since the change are so minimal that we can verify that it can't influence the results or the (internal or external) api, I would be fine with merging this change in aspect independent of the world builder.
> Build world builder with unity

- source/mesh_deformation/interface.cc
Originally, this was only triggered in case initial adaptive refinement is applied, not when only initial global refinement occurs.  From the documentation, I gather that some versions of LinearAlgebra::Vector::reinit set the vector entries to zero by default, but this particular version does not. Which also makes me wonder why this works for non adaptive initial meshes. 
With the new condition, the mesh_displacements are set to zero once, before solving for the mesh velocity on the coarse mesh. With `sim.time==0`, they would be set to zero before solving on the coarse mesh and again before solving on the initially adaptively refined mesh.
With just the free surface, it doesn't really matter when during the first timestep the displacements are set to zero, because the Stokes velocities …
> Set mesh displacement to zero

- include/aspect/material_model/interface.h
Fixes #3728, which could generate the following error
```
In file included from /hdscratch/shared/libs-
candi-9.2.0-r1/deal.II-v9.2.0/include/deal.II/fe/mapping_cartesian.h:22:0,
from /home/heister/aspect-
git/source/simulator/core.cc:53,
from CMakeFiles/aspect.dir/Unity/unity_2_cxx.cxx:97:
/hdscratch/shared/libs-
candi-9.2.0-r1/deal.II-v9.2.0/include/deal.II/base/qprojector.h:414:54:
error: specialization of ‘dealii::QIterated<dim>::QIterated(const
dealii::Quadrature<1>&, unsigned int) [with int dim = 1]’ after
instantiation
const unsigned int   n_copies);
```
This is due to deal.II 9.2. having an incorrect specialization of
QIterated inside quadrature.h.
> fix deal.II 9.2 instantiation bug in qprojector.h

- include/aspect/utilities.h
- source/simulator/core.cc
- source/utilities.cc
I need access to this utility class in a different PR, but since it is a self-contained change it makes sense to merge it separately.
> Move VectorFunctionFromVelocityFunctionObject to Utilities namespace

- source/simulator/parameters.cc
- tests/drucker_prager_derivatives_2d.prm
- tests/drucker_prager_derivatives_3d.prm
- tests/visco_plastic_derivatives_2d.prm
- tests/visco_plastic_derivatives_3d.prm
In response to #3691 this sets the minimum number of nonlinear iterations to 1. If models require no solve performed at all they should choose the nonlinear solver scheme `no Advection, no Stokes` instead of setting the number of iterations to 0.
> Require at least one nonlinear iteration

- tests/melt_transport_adaptive.cc
we do ignore them, but this will break at some point if we don't fix
them.
> fix deprecation warnings in tests

- source/simulator/parameters.cc
When using DG, the global min and max value for each composition can be specified to be applied as limits on the fields. Till now, these had to be specified for all fields separately, even when the value was the same for each field. Now the parameter parsing uses the `possibly_extend_from_1_to_N` function.
This PR also cleans up a check on the number of limiters given in the input file and a double read of the number of fields.
> Expansion global limiter

- include/aspect/simulator.h
- include/aspect/termination_criteria/interface.h
- include/aspect/time_stepping/interface.h
- source/simulator/core.cc
- source/simulator/helper_functions.cc
- source/simulator/parameters.cc
- source/termination_criteria/interface.cc
- source/time_stepping/interface.cc
This is step 1 of N to introduce a new facility to handle the task to
determinate time step sizes and allow redoing time steps for various
reasons.
This PR creates a new TimeStepping::Manager class without changing
functionality:
- Introduce TimeStepping::Manager that contains the TerminationManager
- move do_checkpoint_on_terminate to it
- simplify core.cc termination handling
part of #3549
> Introduce TimeStepping::Manager

- include/aspect/material_model/utilities.h
- source/material_model/utilities.cc
The PerpleX lookup table previously assumed a certain ordering of columns, and of units. This PR instead reads the column labels, and assigns properties according to those labels.
This PR is a first step toward adding additional columns to the lookup, such as individual phase volumes.
> PerpleX lookup now uses column labels to assign properties

- CMakeLists.txt
Let's disable the world builder unity builds for now as this is causing various problems for people.
Grouping world builder and ASPECT files into the same .cxx is the wrong approach.
> world builder: disable unity builds temporarily

- tests/melt_force_vector.cc
- tests/melt_force_vector/screen-output
This pull request updates the melt force vector test so that all errors in the screen output now converge. This is achieved by using the correct reference solution in the .cc file. 
This is useful because this is one of the few tests that uses additional material model outputs to add terms to the RHS of the equations, and this update makes it more clear how to use this feature.
> update melt force vector test

- benchmarks/free_surface_tractions/viscoelastic/README
I had a closer look at this benchmark and played with timestepping. I corrected parts of the text and added some more information on elastic and numerical time step sizes. In the example .prm files the numerical time step is actually 10 while the elastic time step is 100, so they were not equal as stated in the text.
> played with timestepping and added my results in the readme

- source/mesh_refinement/interface.cc
Specifically, remove an unused variable in a couple of places. This should also enable the use of range-based for loops, see #3774.
> Minor cleanups.

- include/aspect/material_model/interface.h
- source/material_model/interface.cc
This PR adds a constructor to NamedAdditionalMaterialOutputs so that the user can pass user-defined output names and a number of points for which those outputs should be stored.
This PR was suggested by @gassmoeller based on comments in #3733.
> added constructor for NamedAdditionalMaterialOutputs

- include/aspect/stokes_matrix_free.h
- source/simulator/stokes_matrix_free.cc
Adding some more explanatory comments to the stokes_matrix_free.h/.cc files. Let me know if anyone has other places that deserve some clarification.
> Adding some helpful comments to GMG code

- source/simulator/solver_schemes.cc
In both pull request #3112 and #3787 I ran into the issue that the optimalizations in #3709 may have set some flags too strict. This pull request makes sure that the matrix is always rebuild on the first nonlinear iteration. We may be able to set it more strict again after #3112 and #3787 are merged and have a better idea of when exactly a rebuild (and of what) is needed.
> Always rebuild Newton stokes matrix on first nonlinear iteration

- source/simulator/solver_schemes.cc
- tests/spiegelman_fail_test/screen-output
Found while looking at #3787. The proper past tense of "catch" is "caught", but I think we don't need that word at all.
> Fix grammar.

- include/aspect/particle/interpolator/bilinear_least_squares.h
- source/particle/interpolator/bilinear_least_squares.cc
The old one was, I believe, a typo: it should (in the bilinear case already) have been named
'use_global_values_limiter'. But we can choose an even better name:
'use_global_min_max_limiter'.
> Rename a member variable.

- source/initial_temperature/lithosphere_mask.cc
The wrong type of quotes was used which led to such things as "exampleâĂŸ# POINTS: 3 3âĂŹ" in the manual. Corrected two instances of this in lithosphere mask.
* [x ] I have read the guidelines in our [CONTRIBUTING.md](../blob/master/CONTRIBUTING.md) document.
* [ x] I have followed the [instructions for indenting my code](../blob/master/CONTRIBUTING.md#making-aspect-better).
> correct quotes type in lithosphere mask manual entry

- include/aspect/boundary_velocity/gplates.h
- include/aspect/plugins.h
- include/aspect/volume_of_fluid/handler.h
- source/postprocess/heat_flux_map.cc
- source/simulator/assemblers/newton_stokes.cc
- source/simulator/helper_functions.cc
- source/simulator/parameters.cc
- source/utilities.cc
- source/volume_of_fluid/reconstruct.cc
Not all `typename`s are actually necessary: It's only necessary when the references name is a type inside a template-argument dependent (outer) type. Remove a number of cases where that is not actually necessary.
> Remove some unnecessary 'typename's.

- include/aspect/material_model/rheology/constant_viscosity_prefactors.h
- source/material_model/rheology/constant_viscosity_prefactors.cc
The function compute_viscosity in the ConstantViscosityPrefactors rheology model takes an argument called viscosity as an argument. This was very confusing for my Winnie-the-Pooh-like brain. I think base_viscosity is clearer.
> rename viscosity argument to base_viscosity in ConstantViscosityPrefactors

- include/aspect/mesh_deformation/interface.h
It seems like these functions were not used very often. Seen while working on #3751.
> Fix function name

- benchmarks/time_dependent_annulus/plugin/time_dependent_annulus.cc
- benchmarks/time_dependent_annulus/plugin/time_dependent_annulus.h
- source/boundary_temperature/dynamic_core.cc
- source/heating_model/compositional_heating.cc
- source/initial_composition/ascii_data_layered.cc
- source/material_model/diffusion_dislocation.cc
- source/material_model/grain_size.cc
- source/material_model/visco_plastic.cc
- source/postprocess/geoid.cc
- source/postprocess/gravity_point_values.cc
- source/postprocess/particles.cc
- source/simulator/core.cc
- source/simulator/solver_schemes.cc
- source/simulator/stokes_matrix_free.cc
- source/termination_criteria/end_walltime.cc
- source/volume_of_fluid/handler.cc
- source/volume_of_fluid/utilities.cc
Fixed some typos in source code comments and doc strings. 
I've purposefully avoided anything that changes how the code functions.
> fixed some typos in source code comments/doc strings

- source/simulator/solver_schemes.cc
- tests/prescribed_dilation_newton/screen-output
- tests/sol_cx_newton_crash.cc
- tests/sol_cx_newton_crash.prm
- tests/sol_cx_newton_crash/screen-output
- tests/sol_cx_newton_crash/statistics
This is a proposed fix for the problem found in #3705. I made a new pull request out of it to allow me to easily change the code.
In short, this introduces a test of whether the rhs has dropped more than 1e-8 (I could make this a parameter if desired).
While fixing this, I noticed that to get it working I had to enable rebuilding of the Newton stokes matrix every 0th nonlinear iteration. It doesn't seem to change anything for the other tests (as far as I could see locally) because they already did that due to their boundary conditions.
> Newton fail test fix

- doc/modules/changes/20200814b_bobmyhill
- include/aspect/material_model/diffusion_dislocation.h
- include/aspect/material_model/rheology/diffusion_creep.h
- include/aspect/material_model/rheology/dislocation_creep.h
- source/material_model/diffusion_dislocation.cc
- source/material_model/rheology/diffusion_creep.cc
- source/material_model/rheology/dislocation_creep.cc
This PR adds `strain rate(P, T, C, stress)` and `d(strain rate)/d(stress) (P, T, C, stress)` functions to diffusion and dislocation creep. These stress-dependent functions are needed for correct compositing (via a Newton-Raphson iteration). 
At the moment, diffusion_dislocation.cc contains these functions, but more composite rheologies are now being considered, and each of these will need the same functions.
Opened for comment, especially on the use of std::map<std::string, double> to store the creep parameters. The storage avoids repeated calculation of the creep parameters in compute_strain_rate_and_derivative(), but may slow down the code. If there's a more clean and efficient way to do this, I'll make a change.
> added new strain rate and derivative functions to diffusion and dislocation creep

- tests/cmake/diff_test.sh
Teach numdiff to ignore differences in line endings between unix and windows.
> Ignore differences in line endings on Windows and Linux.

- include/aspect/particle/world.h
- source/particle/world.cc
- tests/particle_handler_copy.cc
- tests/particle_handler_copy.prm
- tests/particle_handler_copy/screen-output
This is the function I promised @anne-glerum for #3760 to work. The test case does something very similar to what is needed there, it creates a new particle handler as a copy of the existing one and afterwards copies the new particle handler back into the existing one (thus overwriting the particles in the existing handler). @tjhei: I decided to register all signals to the copy as well, i.e. the particles of the copied handler will be shipped around in case the triangulation is refined or repartitioned. I did not attach the the signal that actually modifies the set of stored particles (the ones that enforce the particle per cell limit). Is this what you need as well?
> Introduce copy_particle_handler_function to particle world.

- source/particle/interpolator/bilinear_least_squares.cc
This seems like the wrong include file to me, and it may be related to compilation problems with the Intel compiler reported here: https://community.geodynamics.org/t/issues-compiling-aspect-on-tacc/1401.
> Replace header file

- cookbooks/van-keken-vof/doc/van-keken-vof.tex
- doc/manual/manual.tex
We're generally quite consistent in making figure and table captions italics,
but a few have slipped our attention. Fix this.
> Make all captions italics.

- doc/modules/changes/20200829b_bobmyhill
- include/aspect/material_model/rheology/peierls_creep.h
- source/material_model/rheology/peierls_creep.cc
- tests/visco_plastic_peierls_mei_exact.prm
- tests/visco_plastic_peierls_mei_exact/screen-output
- tests/visco_plastic_peierls_mei_exact/statistics
This PR adds the exact formulation for Peierls creep to the Peierls creep rheology module, along with the associated strain rate and derivative functions.
It also adds a new test using the analytical calculations by @mibillen and @naliboff.
Based on #3723.
> New: Add Peierls exact formulation

- source/postprocess/point_values.cc
- tests/point_value_natural_coordinates_shell.prm
- tests/point_value_natural_coordinates_shell/point_values.txt
- tests/point_value_natural_coordinates_shell/screen-output
As natural coordinates conversions have been implemented in the spherical geometries, this assert can be removed from the point values postprocessor.
> Remove assert natural coordinates

- contrib/ci/Dockerfile
The new image uses -O3 in debug mode as discussed in #3835.
related to #3630
> CI: switch to newer 9.2 deal.II image

- include/aspect/stokes_matrix_free.h
- source/simulator/stokes_matrix_free.cc
We still have problems switching to single precision in #3532 as some test results seem to break. As a first step, rebase that PR and switch the number type back to double.
This should have no effect on functionality and would be good to merge separately.
> GMG: template argument for number type

- source/simulator/melt.cc
- tests/melt_boundary_heat_flux.cc
- tests/melt_boundary_heat_flux.prm
- tests/melt_boundary_heat_flux/screen-output
- tests/melt_boundary_heat_flux/statistics
This fixes a bug described on the forum (https://community.geodynamics.org/t/melt-production-migration/1498/6?u=jdannberg). 
Basically, the melt migration routine calls its own set_assemblers function, so it didn't include the assembler for the heat flux boundary conditions. 
I think the same fix will have to be done for the Newton assembly as well. @MFraters, this wouldn't cause any problems for the assembler, since it is only an assembler for the temperature equation, correct?
* [x ] I have followed the [instructions for indenting my code](../blob/master/CONTRIBUTING.md#making-aspect-better).
> fix melt migration with heat flux boundaries

- doc/modules/changes/20201021_mfraters
- include/aspect/simulator.h
- source/simulator/assembly.cc
- source/simulator/newton.cc
A slight refactoring of the code which should fix the problem with the heatflow boundaries and make it more future proof. 
followup to #3868. Fixes #3869.
> refactor set_default_assemblers to fix the Newton solver for heatflow boundaries

- source/postprocess/gravity_point_values.cc
- tests/gravity_point_values_list/screen-output
- tests/gravity_point_values_map/screen-output
- tests/gravity_point_values_spiral/screen-output
Found while looking through #3850. This unifies the screen output of the gravity point values postprocessor with the visualization, depth average, and geoid postprocessor.
> Unify postprocessor sceen output

- doc/Makefile
See the message today on the mailing list. With this change, the output becomes a lot more visible:
```
[...]
This is makeindex, version 2.15 [TeX Live 2017] (kpathsea + Thai support).
Scanning input file prmindex.idx......done (2025 entries accepted, 0 rejected).
Sorting entries....................done (25273 comparisons).
Generating output file prmindex.ind.....done (1151 lines written, 0 warnings).
Output written in prmindex.ind.
Transcript written in prmindex.ilg.
This is makeindex, version 2.15 [TeX Live 2017] (kpathsea + Thai support).
Scanning input file prmindexfull.idx......done (2025 entries accepted, 0 rejected).
Sorting entries...................done (23968 comparisons).
Generating output file prmindexfull.ind......done (1860 lines written, 0 warnings).
Output written in …
```
> Make error messages more visible when compiling manual.tex.

- source/boundary_velocity/gplates.cc
internal::GPlatesLookup is used in boundary_velocity_residual_statistics
and clang correctly complains that we don't explicitly instantiate the
template class. Fix this.
> add missing instantiation

- source/material_model/rheology/elasticity.cc
This PR ensures that the Elasticity<dim>:: calculate_viscoelastic_viscosity outputs the correct value even when the viscous viscosity is infinite.
> Refactor viscoelastic viscosity

- source/postprocess/visualization/principal_stress.cc
Prevent a warning in release mode of an unused variable in principle stress visualization by removing the variable and using the computation directly in the assert.
> Prevent a warning in release mode of an unused variable in principle stress visualization

- cookbooks/anisotropic_viscosity/av_material.cc
- source/heating_model/shear_heating.cc
- source/postprocess/visualization/maximum_horizontal_compressive_stress.cc
- source/postprocess/visualization/principal_stress.cc
- source/postprocess/visualization/shear_stress.cc
- source/postprocess/visualization/strain_rate.cc
- source/postprocess/visualization/strain_rate_tensor.cc
- source/postprocess/visualization/stress.cc
- source/postprocess/visualization/surface_stress.cc
- tests/anisotropic_viscosity.cc
Following the discussion in #3897, the deviatoric strain rate is represented with a variable named `compressible_strain_rate` in multiple locations. This PR changes those variable names to `deviatoric_strain_rate`. @bobmyhill
> Rename strain rate variable

- include/aspect/material_model/simpler.h
- source/material_model/simpler.cc
The member "reference temperature" is unused inside Simpler (but it is
declared and used in the EquationOfState::LinearizedIncompressible EoS).
This means this change should be backwards-compatible.
> Simpler material model: remove reference_T

- .htaccess
- header.include
- index.html
This enables the address https://aspect.geodynamics.org/manual.pdf which will auto-redirect to the existing URL.
> www: create a redirect to manual.pdf

- tests/rheology_scaled_profile.cc
This PR addresses a minor change in the exisiting test plugin which scales the aveage rheology of the material model to an input ascii reference data, to use the last depth layer when the dephs are greater than the input ascii data rheology.
> Modified the plugin for depths more than the input viscosity file.

- doc/modules/changes/20200706_tjhei
- doc/modules/changes/20200727_tjhei
- doc/modules/changes/20200801_tjhei
- doc/modules/changes/20200802_tjhei
- doc/modules/changes/20200803Bangerth
- doc/modules/changes/20200804_gassmoeller
- doc/modules/changes/20200805_jdannberg
- doc/modules/changes/20200807_erinheilman
- doc/modules/changes/20200807_jdannberg
- doc/modules/changes/20200810_jaustermann
- doc/modules/changes/20200810_naliboff
- doc/modules/changes/20200812_erinheilman
- doc/modules/changes/20200812_gassmoeller
- doc/modules/changes/20200812_naliboff
- doc/modules/changes/20200812_tjhei
- doc/modules/changes/20200814_bobmyhill
- doc/modules/changes/20200814_tjhei
- doc/modules/changes/20200814b_bobmyhill
- doc/modules/changes/20200819_sac-bsa
- doc/modules/changes/20200820_gassmoeller
- doc/modules/changes/20200828_bobmyhill
- doc/modules/changes/20200829b_bobmyhill
- doc/modules/changes/20200903_naliboff
- doc/modules/changes/20200904_bobmyhill
- doc/modules/changes/20201022_gassmoeller
- doc/modules/changes/20201030_gassmoeller
- doc/modules/changes/20201109_jdannberg
We introduced a stray `<li>` in our changelog that got copied into many entries. See: https://aspect.geodynamics.org/doc/doxygen/changes_current.html.
This should fix the issue.
> Fix changelog

- doc/modules/changes/20201130_bobmyhill
- include/aspect/material_model/rheology/visco_plastic.h
- include/aspect/material_model/visco_plastic.h
- source/material_model/rheology/visco_plastic.cc
- source/material_model/visco_plastic.cc
This PR splits the rheological parts of the ViscoPlastic material model into a new Rheology model.
The intention is to make it easier for users to use the viscoplastic rheology in their own material models while using a different equation of state.
> ViscoPlastic rheology migrated into separate rheology module

- include/aspect/parameters.h
- source/simulator/core.cc
follow up to #3112. This creates a helper function to centralize the question whether a type of nonlinear solver is a defect correction solver. 
I placed it close to the enum definition in parameters.h, but I am fine with putting it at an other location if there are strong opinions about it.
> create and use is_defect_correction helper function.

- source/simulator/parameters.cc
I noticed some asserts which I think should be also active in release mode since they check user input.
> change parameters.cc asserts to assertthrows when dealing with user input.

- doc/manual/citing_aspect.bib
Adds new citation Negredo et al. 2020, Geodynamic Modeling of Edge-Delamination Driven by Subduction-Transform Edge Propagator Faults: The Westernmost Mediterranean Margin (Central Betic Orogen) Case Study, to publications citing ASPECT.
> add new citation Negredo et al.

- tests/CMakeLists.txt
- tests/cmake/timeout.sh
It turns out the the GNU timeout command is not available on OSX by
default. Work around this by ignoring the time limit on OSX.
> testsuite: do not require timeout command

- doc/options.dox
- enable MATHJAX
- remove obsolete config options my doxygen version complains about
> doxygen options

- CMakeLists.txt
In what is probably a historical accident, our CMakeLists.txt file allows querying if
a user has set PERPLEX_DIR as an environment variable, but not on the command line
via
-DPERPLEX_DIR=/where/I/installed/perplex
I suspect that that was not on purpose, and it is easily fixed. It also makes this
call to FIND_PACKAGE look more like the other calls to this command in this file.
/rebuild
> Also allow setting PERPLEX_DIR on the command line.

- include/aspect/material_model/rheology/visco_plastic.h
- source/material_model/rheology/visco_plastic.cc
- source/material_model/visco_plastic.cc
As discussed with @anne-glerum @gassmoeller and @naliboff I changed calculate_isostrain_viscosities in visco_plastic.cc from being a pair into a structure, so that it is easier to return more parameters (e.g. current_edot_ii) needed in other functions.
> changed calculate_isostrain_viscosities from pair to structure

- include/aspect/simulator.h
- include/aspect/simulator_access.h
- source/postprocess/rotation_statistics.cc
- source/simulator/nullspace.cc
- source/simulator/simulator_access.cc
Similar to #3943, but this unifies the code used in the rotation statistics postprocessor with the similar code in nullspace removal. There should be no changes in behavior.
> Refactor rotation statistics postprocessor

- doc/modules/changes/20210201_gassmoeller
- source/simulator/core.cc
- tests/hollow_sphere_gmg_project_q1/screen-output
I think this was suggested to me by one of the deal.II maintainers (maybe Martin?) a while ago, and I had a test branch for a while, but did not see much of a change for most applications so I never pursued it further. However, when looking at a particularly slow particle model in a sphere I realized that that is exactly the application getting the largest benefit from using a `MappingQCache` object instead of a `MappingQ` that we used before. The caching of mapping support points drastically speeds up particle sorting in curved geometries, because often there are dozens of particles in a cell, and in the current implementation we recompute the mapping support points for all of them when recomputing their reference locations. The improvement in 3D may be even larger.
The PR should not …
> Use MappingQCache for curved cells if possible to speed up particle sort

- source/material_model/rheology/diffusion_creep.cc
- source/material_model/rheology/dislocation_creep.cc
- source/material_model/rheology/peierls_creep.cc
@mibillen and @elodie-kendall could you take a look if this PR fixes your issues #3959 or #3957? It should prevent the diffusion and dislocation viscosities from becoming too large to trigger floating point overflows in the composite rheology. I decided to move this into the individual plugins instead of the combined visco plastic rheology, because it seemed safer (it may happen in other places that use these plugins as well).
> Add assert and maximum to viscosity computation

- source/utilities.cc
aspect::Utilities has accumulated a number of explicit instantiations that can be handled easier inside the `INSTANTIATE` macro. Do some cleanup.
> Cleanup instantiations

- source/postprocess/visualization/melt_fraction.cc
- source/simulator/parameters.cc
There is no nonlinear solver scheme `operator splitting`, but a separate parameter `Use operator splitting`, so I've updated the description of the `Operator splitting parameters`.
> update parameter doc

- source/material_model/rheology/visco_plastic.cc
Currently the min viscosity can be larger than the max viscosity, so when you accidentally switch them in the input file ... Hope it saves somebody else some time :sweat:
> Add assert max_visc >= min_visc

- source/time_stepping/function.cc
I noticed that the error message in the time stepping function was saying heating model. I guess this was just a mistake from copying it over so I changed to timestepping. 
* [ X] I have read the guidelines in our [CONTRIBUTING.md](../blob/master/CONTRIBUTING.md) document.
* [ X] I have followed the [instructions for indenting my code](../blob/master/CONTRIBUTING.md#making-aspect-better).
> adjusted error message for time stepping function

- include/aspect/postprocess/visualization/shear_stress.h
- include/aspect/postprocess/visualization/stress.h
- source/postprocess/visualization/shear_stress.cc
- source/postprocess/visualization/stress.cc
While the elastic contribution is added to the principal stress postprocesor, it was not in the stress and shear stress postprocesors.
> added elastic stress contribution to stress and shear stress vis pp

- doc/manual/manual.tex
The package makes sure that references are listed not as [4,2,8,5] but as [2,4,5,8]. As a side effect, it also replaces [1,3,5,6,7,8] by [1,3,5-8].
I'm slightly ambivalent about the latter. It makes the document marginally shorter, but one can't click on a reference individually any more that way -- though one can click on `5` and then quite easily get to 7 from there. Opinions appreciated.
> Use the 'cite' package for the manual.

- source/simulator/stokes_matrix_free.cc
Reusing the AlignedVector in the GMG code skips allocating memory over
and over. Prompted by https://github.com/dealii/dealii/issues/12008
> GMG: reuse AlignedVector

- source/particle/world.cc
We currently initialize particles one cell at a time, but because they are stored per cell, this amounts to initializing them all in the same order in which they are stored. We might as well initialize them all at once.
/rebuild
> Initialize particles in one go.

- source/postprocess/visualization.cc
- tests/composition_names_duplicates.prm
- tests/composition_names_duplicates/screen-output
Fixes #3996. The task is slightly more complicated than I thought at first, because each postprocessor can rightly return multiple copies of the same name if it returns a vector or tensor. Thus each postprocessors names are first copied into a set to make them unique, and then this set is merged with the existing set of names, while checking for duplicates.
> Make sure visualization names are unique

- CMakeLists.txt
This fixes a reported issue in https://community.geodynamics.org/t/world-builder-causing-error-during-configuration/1823 for cmake version 2.8.12.2. I tested it locally and could reproduce the problem and it is fixed with this change.
> Fix split line problem for cmake version 2.8.12.

- source/particle/generator/interface.cc
This is required to make mainline compile again after the changes in dealii/dealii#11276.
> Work around removed exception

- source/initial_temperature/S40RTS_perturbation.cc
- source/initial_temperature/SAVANI_perturbation.cc
- source/initial_temperature/patch_on_S40RTS.cc
Found while doing some testing for @wanyingw. The S40RTS_perturbation and SAVANI_perturbation initial temperature plugins called their initialize functions from their parse_parameters functions, which is duplicative and unnecessary, because the initial temperature manager calls these functions immediately after parse_parameters again (which is the way the function is intended to be used). I removed the duplicated calls, but one other plugin actually depended on this behavior, so I fixed that as well.
> Remove duplicated calls to initialize

- source/mesh_refinement/volume_of_fluid_interface.cc
- source/simulator/assemblers/advection.cc
- source/volume_of_fluid/assembler.cc
This function is deprecated. Use TriaAccessor::n_children() instead.
/rebuild
> Avoid the use of TriaAccessor::number_of_children().

- source/simulator/stokes_matrix_free.cc
We use the same construct several times over to compute the inverse of the diagonal of a matrix in matrix-free contexts. Replace this by what I think is the equivalent construct.
/rebuild
> Avoid the use of deprecated functions for iterating over local vector elements.

- include/aspect/postprocess/visualization/surface_stress.h
- source/postprocess/visualization/surface_stress.cc
- tests/stress_vs_surface_stress/solution/solution_surface-00000.0000.gnuplot
In line with the normal stress visualization postprocessor, the surface stress PP now includes the elastic stresses as well. The names of the stress tensor components are also updated to avoid running into duplicate paraview output names and to differentiate between viscous and visco-elastic stresses.
> Add elastic stresses to surface stress output

- source/structured_data.cc
When the number of components can not be parsed (no column names
specified) and not specified in the constructor, we would crash with
bad:alloc. Instead, add an Assert.
Found while working on #4071
> add Assert to StructuredData

- source/simulator/stokes_matrix_free.cc
Fix matrix-free deprecation warnings, and it passed the test nsinker_gmg_idr. @tjhei
> Fix matrix-free deprecation warnings

- source/particle/world.cc
Since dealii/dealii#11577 particle iterators are invalidated if another iterator in the same cell is removed. This broke the functionality to limit the number of particles in a cell, because ASPECT stores a list of iterators to remove before removing them one by one. Instead we should remove all of them in one go as is now possible with the `remove_particles` function.
> Make particle removal compatible with latest deal.II particle structure

- contrib/release/release-tasklist
- doc/manual/manual.tex
Working towards #4069. We should automate this by having a container named aspect-tester that gets rebuild in a CI workflow from a defined deal.II image, then we would not need to update the doc (see e.g. https://hub.docker.com/repository/docker/gassmoeller/aspect-tester).
> Update docker container versions

- include/aspect/structured_data.h
- source/structured_data.cc
- unit_tests/utilities.cc
This is a first necessary step towards de-duplicating data. Related to #4051.
/rebuild
> Use std::move to move data instead of copy where possible.

- source/particle/world.cc
Unfortunately #4063 only fixed serial computations. `remove_particles` is a collective function that updates the cache of the particle handler so it is expected to be called on all processes which we dont, and we dont want to store all the local particle iterators we want to remove either. So instead I rewrote the removal logic for 10.0. It also looks much cleaner now. The code could be further improved if the particle_handler had a function `particle_in_cell(cell,particle_index)` that returned the n-th particle in a cell, but that is something to do for the future.
I have verified that this PR, together with the open fixes for deal.II (dealii/dealii#12485) fixes #4067 and the viscoelastic_bending_beam_particles and the viscoelastic_stress_buildup_particles benchmark finish in parallel.
> Fix particle removal in parallel

- doc/modules/changes/20210625_gassmoeller
- include/aspect/initial_composition/world_builder.h
- source/initial_composition/world_builder.cc
- tests/world_builder_select_composition.prm
- tests/world_builder_select_composition.wb
- tests/world_builder_select_composition/screen-output
We have a model setup where using the world builder to prescribe initial compositions is very expensive, however we only want to use it for 1 of our 5 compositions. At the moment it is impossible to call the world builder function only for selected compositions, but this is now added in this PR. 
@MFraters can you take a look if this makes sense?
> Allow selecting individual compositions for world builder

- source/simulator/checkpoint_restart.cc
This should fix #4088. The current constraints in computations with melt depend on the current linearization point (to determine which cells should be treated as melt cells), but we do not serialize the current linearization point and only initialize it after computing the current constraints. This could lead to different results in the first nonlinear iteration after a restart (presumably all cells were treated as non melt cells and only the normal Stokes equations were solved on them).
This PR makes sure the current linearization point is initialized before computing the current constraints after a restart. This means we now initialize the current linearization point twice after a resume, but that should not matter (it's reasonably fast and only happens occasionally).
@anne-glerum: Can …
> Initialize current linearization point after melt restart

- unit_tests/mesh_refinement.cc
- unit_tests/parse_map_to_double_array.cc
Found because of #4099. It seems the formatting of assertion output has changed (or catch has become more strict about comparisons), anyway it does not ignore newlines in the output. Adjust the unit test requirements to not contain strings that are broken by a newline.
> Fix unit tests for deal.II dev

- .github/workflows/linux.yml
This ensures that only a single github actions workflow per PR is run at the same time, and that new pushes will cancel existing runs. Will be useful to get quicker results from Github actions during the hackathon.
> Set Github Actions concurrency to speed up feedback

- .github/workflows/linux.yml
Fixup for #4101 to ensure branches from different users with the same branch name do not interfere.
> Use user-branch name for concurrency

- source/utilities.cc
The implementation of spherical harmonics in the boost library is limited to a degree of 120 or so after which the output becomes inaccurate. This is actually already documented for this utility function, but all the places that use it happily accept larger values. We should prevent this. Please do not merge just yet, I am waiting for feedback from @wanyingw on what degree is still working well, we should maybe be conservative and limit ourselves to that.
> Limit spherical harmonic degree to stable range

- source/simulator/helper_functions.cc
Should fix #4116. Restores the behavior from before #3681 for models that set viscosity to 0 and dont solve Stokes.
@tjhei: Do you think this is the correct way to fix it? I verified that the model now runs (there are only two models like this, the other one is benchmarks/advection/rotate_shape_*
> Allow viscosity 0 if Stokes is not solved

- cookbooks/crustal_deformation/crustal_model_2D.prm
Fix #4117. The solver restart length alone already fixes the issue of the non-converging linear solver (5000 iterations -> 195 iterations). However, the nonlinear tolerance in this cookbook is so small, that the nonlinear solver very rarely converges for this problem. With a more reasonable tolerance this cookbook is 5 times faster and the results are nearly the same (small visible difference in the shape of the free surface). Let me know if you want me to remove the change to the solver tolerance to keep the cookbook the same.
> Fix crustal cookbook

- .github/workflows/linux.yml
This adds a github action that compiles ASPECT against the dealii/dealii:master-focal container with every PR. Currently does not run the test suite.
No more PRs that work on the tester but break on deal.II dev :tada:
> Add dealii dev tester

- CMakeLists.txt
It has bothered me for a while that when using ninja you have to specifically add a flag to get color output. This pull request would automatically add that unless you turn it off manually. I don't see a downside of having the flag there, but if there is some, I will be happy to turn it off by default.
> Add option to force color output for ninja.

- include/aspect/boundary_temperature/dynamic_core.h
- include/aspect/particle/property/integrated_strain.h
- include/aspect/particle/property/melt_particle.h
- include/aspect/particle/property/pT_path.h
- include/aspect/simulator/assemblers/interface.h
- include/aspect/volume_of_fluid/assembly.h
Uses the lovely perl regex substitution
```
perl -pi -e 's/\*\*\//\*\//g;' `find include`
```
This might be the highlight of my day :-)
/rebuild
> Fix incorrect doxygen markup.

- source/boundary_temperature/box.cc
- source/boundary_temperature/two_merged_boxes.cc
- source/geometry_model/initial_topography_model/prm_polygon.cc
- source/initial_temperature/S40RTS_perturbation.cc
- source/initial_temperature/SAVANI_perturbation.cc
- source/initial_temperature/patch_on_S40RTS.cc
- source/material_model/averaging.cc
- source/material_model/interface.cc
- source/material_model/utilities.cc
- source/particle/interpolator/bilinear_least_squares.cc
- source/particle/interpolator/quadratic_least_squares.cc
- source/postprocess/boundary_velocity_residual_statistics.cc
- source/postprocess/composition_statistics.cc
- source/postprocess/gravity_point_values.cc
- source/postprocess/melt_statistics.cc
- source/postprocess/pressure_statistics.cc
- source/postprocess/temperature_statistics.cc
- source/postprocess/topography.cc
- source/postprocess/velocity_boundary_statistics.cc
- source/simulator/entropy_viscosity.cc
- source/simulator/helper_functions.cc
- source/simulator/parameters.cc
- source/simulator/stokes_matrix_free.cc
- source/structured_data.cc
We used `-max()` previously because `lowest()` is a C++11 feature. But the latter is canonically correct, and the former only works because floating point numbers actually store a sign bit, rather than using ones-complement to indicate the sign of a number as integers do.
References:
https://en.cppreference.com/w/cpp/types/numeric_limits/max
https://en.cppreference.com/w/cpp/types/numeric_limits/min
https://en.cppreference.com/w/cpp/types/numeric_limits/lowest
/rebuild
> Use std::numeric_limits::lowest() instead of -max().

- contrib/world_builder/source/config.cc.in
The current form is not technically wrong, but if it is used in a unity build it introduces all symbols from WorldBuilder into the top namespace, which causes a lot of conflicts with deal.II names. And the new form is cleaner anyway I think, unless we rely on things like `Data::WORLD_BUILDER_SOURCE_DIR` instead of `WorldBuilder::Data::WORLD_BUILDER_SOURCE_DIR`. 
I will open a separate companion PR to the world builder repo.
> Avoid using Worldbuilder in top namespace

- doc/manual/citing_aspect.bib
When updating the co-author network diagram, the R parser complain about a few of the entries. This updates their bibliographic information. 
Note that .bib from publisher's website did not include the "publisher" attribute, hence, it no longer appears for Njinju and Sandiford.
> update citing_aspect.bib with missing information

- doc/modules/changes/20200829_bobmyhill
- doc/modules/changes/20210708_bobmyhill
- include/aspect/material_model/equation_of_state/thermodynamic_table_lookup.h
- include/aspect/material_model/steinberger.h
- source/material_model/equation_of_state/thermodynamic_table_lookup.cc
- source/material_model/steinberger.cc
This PR makes a new EquationOfState plugin called ThermodynamicTableLookup. This can be used by both the Steinberger and GrainSize Material models, removing two almost identical chunks of code from those models. It will also make it easier for new material models to use the table lookup.
To make this PR as easy to read as possible, I will modify the GrainSize material model in a separate PR.
> New: Make thermodynamic table lookup into an EquationOfState

- doc/manual/manual.tex
Three minor fixes to the manual:
- removed trailing spaces
- renamed "testsuite" to "test suite"
- corrected "success of failure" to "success or failure".
> minor fixes to manual

- include/aspect/material_model/equation_of_state/interface.h
- source/material_model/equation_of_state/interface.cc
- source/material_model/steinberger.cc
This PR adds a function that does multicomponent EquationOfState property averaging. 
This function is stored in the equation of state interface, in the MaterialModel namespace.
> Created multicomponent EoS->Material averaging function 

- contrib/utilities/run_clang_tidy.sh
It wasn't clear to me that what I was seeing was actually an error message. Also move it further up before we do other stuff.
> Improve an error message in the clang-tidy script.

- source/simulator/initial_conditions.cc
At the beginning of every nonlinear iteration of an iterative Advection scheme, particles are reset and then advected and their properties updated. Then the updated properties are interpolated onto the FE. At the moment, during the first timestep, every nonlinear iteration resets the old_solution and old_old_solution. This PR limits it to just the first nonlinear iteration as discussed in #4123 .
> Only set old_(old_)solution in first NI for particles with an iterated Advection scheme

- doc/modules/changes/20210708c_bobmyhill
- source/boundary_temperature/constant.cc
- tests/chunk_topography_postprocessor.prm
- tests/depth_postprocessor_ellipsoidal_chunk.prm
- tests/free_surface_adaptive_blob.prm
- tests/free_surface_adaptive_blob_petsc.prm
- tests/free_surface_blob.prm
- tests/free_surface_blob_melt.prm
- tests/free_surface_blob_nonzero_melt.prm
- tests/free_surface_iterated_IMPES.prm
- tests/free_surface_iterated_stokes.prm
- tests/free_surface_relaxation.prm
- tests/melt_velocity_boundary_conditions.prm
- tests/mesh_velocity_output.prm
- tests/periodic_box.prm
- tests/periodic_box_freesurface.prm
- tests/periodic_linear_momentum.prm
- tests/resume_free_surface.prm
- tests/slope_refinement.prm
When using the constant temperature boundary plugin, ASPECT now checks that the Fixed temperature boundary indicators match the indicators in the model subsection.
> Enforce consistent constant temperature boundary indicators

- doc/modules/changes/20210708_gassmoeller
- include/aspect/particle/integrator/euler.h
- include/aspect/particle/integrator/interface.h
- include/aspect/particle/integrator/rk_2.h
- include/aspect/particle/integrator/rk_4.h
- include/aspect/particle/property/interface.h
- source/particle/integrator/interface.cc
- source/particle/integrator/rk_2.cc
- source/particle/integrator/rk_4.cc
- source/particle/interpolator/bilinear_least_squares.cc
- source/particle/interpolator/quadratic_least_squares.cc
- source/particle/property/interface.cc
- source/particle/world.cc
- source/postprocess/particles.cc
- unit_tests/particles.cc
This PR properly implements the first half of #4060. By not longer storing an internal map for the integrators that hold temporary data we avoid a lot of data allocation and lookups into the maps as well as the complicated data transfer. In one case with nearly 1 million particles per core this saves about 33% of the particle advection time (in most cases it is likely less).
I tried to hide the new particle property by:
- defining it internally in interface.cc instead of as a separate plugin
- adding its properties to the end of the particle properties
- automatically ignoring it for the output
However, it is of course still there, so if you output all particle properties you will see properties at the end that have no relation to the selected particle properties in the list of …
> Store integrator properties as regular particle properties

- source/simulator/stokes_matrix_free.cc
I came across this as an assert in the `setup_dofs`, but I think it would be better to have this as an assert throw at the beginning of the program.
> Add gmg assert throw for direction at parse parameters phase.

- include/aspect/material_model/equation_of_state/interface.h
- include/aspect/material_model/utilities.h
- source/material_model/equation_of_state/interface.cc
- source/material_model/steinberger.cc
- source/material_model/utilities.cc
The fill_averaged_equation_of_state_outputs function is really a utilities function and should be in the material model utilities rather than in the equation of state interface. 
See discussion in #4148.
> move fill_averaged_equation_of_state_outputs to utilities

- doc/manual/manual.tex
correcting a simple typo and adding a folder location in the manual section about creating tests.
> correct typo

- CMakeLists.txt
This prevents in-source builds. Unfortunately there is no way to prevent cmake from writing the CMakeCache and CMakeFiles, and as soon as those are written in the source directory all future calls to cmake will crash (see https://dpiepgrass.medium.com/cmake-fights-against-disabling-in-source-builds-ab1d71c1d26f). I think this is the best we can do, explaining this to the user.
> Add check to CMakeLists.txt preventing insource builds

- source/postprocess/geoid.cc
- tests/geoid.prm
- tests/geoid_no_topo.prm
- tests/geoid_visualization.prm
The PR corrects a geoid parameter typo:
Include the contributon from dynamic topography -> Include the contribution from dynamic topography
> corrected geoid parameter typo

- source/material_model/rheology/diffusion_creep.cc
- source/material_model/rheology/dislocation_creep.cc
Avoid division by zero by checking the creep prefactors in parse_parameters. With the new phase transition functionality, the pattern of the prefactors can be anything, so there is no checking of the bounds. Values have to be given for all fields, even if they're masked. Often, users give masked fields a nonsensical value, like zero. This can trigger asserts in e.g. harmonic averaging. This PR just checks that the prefactors are larger than zero after reading them in. 
Related to #4182.
> Add check that creep prefactors are larger than zero

- include/aspect/material_model/equation_of_state/multicomponent_incompressible.h
It turns out that this variable isn't used -- I suspect it's a copy-paste left-over. Found while working on #4187 .
/rebuild
> Remove an unused variable in the multicomponent incompressible model.

- CMakeLists.txt
- doc/modules/changes/20210713_gassmoeller_tjhei
Exit with a fatal error when an incomplete in-source build is found.
improves #4175
> cmake: error when detecting insource cmakecache

- cmake/AspectConfig.cmake.in
We set some required options (.so ending among others) on OSX, but the
check is incorrect: it needs to happen if you use gcc or clang.
Part of #4199
> fix plugin setup for gcc on OSX

- source/initial_temperature/adiabatic_boundary.cc
A while ago we renamed all boundary names that were "outer" to "top". This updates the use of this in the adiabatic boundary plugin (which should allow it to be used with Cartesian geometries in the future).
> use top instead of outer as boundary id

- include/aspect/particle/world.h
- source/particle/world.cc
With the new particle abilities in deal.II there is a lot that can be optimized in ASPECT's particle implementation. This is a first stab. The implementation is far from clean right now, I mostly open this to remind myself to finish it during the hackathon.
Major new changes:
- integrators should use particle properties instead of storing their own cached properties, making transfer and storage much more efficient. But these are temporary properties we usually do not want to appear in the output. I need to find a way to hide certain particle properties
- advection and update can be much more efficient using the FEPointEvaluation class instead of manually evaluating shape functions, or using FEValues
Missing features at the moment:
- boxes without mesh deformation do not benefit from …
> Particle evaluation optimizations

- doc/manual/manual.tex
Update to #4164, with just minor stuff.
I replaced $R_s$ by $r$ because that is what the beginning of the paragraph uses for the distance.
@cedrict FYI.
/rebuild
> Minor edits to the gravity benchmark section.

- source/material_model/rheology/diffusion_creep.cc
- source/material_model/rheology/dislocation_creep.cc
Add an output to ExcMessage showing the temperature and pressure values when a negative (or non-positive) diffusion or dislocation viscosity is detected. This helps the user to quickly know if a non-positive viscosity is caused by the wrong solution of temperature or pressure.
This is the same as #4197, which is related to issue #4193.
>  Add check that printouts Temperature & Pressure values when nonpositive diffusion or dislocation viscosity is detected

- benchmarks/newton_solver_benchmark_set/nonlinear_channel_flow/input_t.prm
This is the second pull request related to issue #4205. This fixes the input file by changing the nonlinear solver. This would normally have been performed by the scripts, but I think it is good to have a working reference script. basically just ran the script, copied one of the produced input files and made some small changes. Most of the changes are not that important, since it is just a reference file.
> fix and cleanup the nonlinear channel flow input_t.prm in the newton benchmark set

- README.md
the readme currently shows MIT as our license. Pick the right image instead.
supersedes #4215
> README: replace license badge

- include/aspect/postprocess/visualization/spd_factor.h
- source/postprocess/visualization/spd_factor.cc
Addressing one of the two issues in #4205. This adds an assert to prevent the SPD factor visualization plugin to be used in when we know that the  `simulator->newton_handler.get()` is a  `nullptr`, which is when a non-defect correction type nonlinear solver is used.
> Assert SPD factor visualization against full Stokes solver.

- cookbooks/prescribed_velocity/prescribed_velocity.cc
- cookbooks/prescribed_velocity_ascii_data/prescribed_velocity_ascii_data.cc
- include/aspect/utilities.h
- source/utilities.cc
- tests/prescribed_velocity_dgp.cc
The `get_unit_support_points_for_velocity` function used to prescribe velocities was duplicated in all three plugins. This PR migrates that function into utilities.
> Migrate support points function to utilities

- source/mesh_refinement/slope.cc
- source/postprocess/dynamic_topography.cc
- source/postprocess/geoid.cc
Seen while reviewing #4210. We have a number of postprocessors that use an expensive name lookup in an inner loop over all faces when the index does not change. Caching the result is faster, and also easier to read.
> Optimize boundary name lookups in postprocessors

- benchmarks/newton_solver_benchmark_set/spiegelman_et_al_2016/input.prm
fixes
An error occurred in line <174> of file
<../source/boundary_temperature/interface.cc> in function
void
aspect::BoundaryTemperature::Manager<dim>::parse_parameters(dealii::ParameterHandler&)
[with int dim = 2]
The violated condition was:
model_names.size() == 0
Additional information:
You have indicated that you wish to apply a boundary temperature
model, but the <Fixed temperature boundary indicators> parameter is
empty. Please use this parameter to specify the boundaries on which the
model(s) should be applied.
> fix benchmarks/newton/spiegelman

- source/particle/world.cc
Not sure if this is a bug fix (I think current_linearization_point technically is more correct), but in the old version of the function `local_update_particles` that is used with deal.II 9.2 we use the solution vector instead, and the current form using `current_linearization_point` (introduced in #4060) creates oscillations in the viscoelastic_bending_beam_particles benchmark. This benchmark uses a single Advection, single Stokes solver scheme and stresses are transported on particles. I guess because values are extrapolated to the current linearization point and then used to compute the update the particles (without iterating out the nonlinearity) they start to oscillate after some timesteps and the benchmark crashes.
I have verified that with this change the benchmark is back to its …
> Unify particle update for deal.II 9.2 and 9.3

- source/postprocess/dynamic_topography.cc
If one is not careful in the choice of densities above the surface or below the CMB, the parameter delta_rho can end up being zero, leading to a division by zero. I have added two AssertThrow's to prevent this from happening.
> avoiding division by zero in dyn topo pp

- include/aspect/particle/world.h
- source/particle/world.cc
It turns out the changes in #4060 only speed up things under very specific conditions like very many particles per cell >>100 and few compositional fields. Unfortunately I did not benchmark more realistic models, where they seem to perform much worse than before and those I did benchmark I combined with #4062, which more or less offsets the changes to the advection part. 
I think the performance can be fixed with improvements to the FEPointEvaluation class in deal.II, in particular to teach it how to handle FESystems efficiently, currently we recalculate mapping related data for each base element separately. However, these changes would still need to be made and benchmarked so the changes only make sense starting with deal.II 10 at the earliest.
I would like to disable #4060 for now to …
> Revert some particle performance regressions

- source/simulator/core.cc
This PR follows discussions in issues #4259,  #3822 and #4131. In short, the DG limiters have not been tested in spherical geometries and tests reported in the issues above reveal it is currently not functional properly in non-cartesian models. This PR adds an AssertThrow if either the temperature or compositional limiters are used in a non-cartesian geometry.
> check DG limiters only used with cartesian mapping

- source/material_model/interface.cc
It's not wrong as is right now because the velocity always comes first among
all variables, but the code right now makes an assumption that is unnecessary.
The author of this code got it right in the next line already :-)
/rebuild
> Fix a possible bug.

- source/particle/world.cc
- tests/particle_periodic_quarter_shell.prm
- tests/particle_periodic_quarter_shell/particles/particles-00001.0000.vtu
- tests/particle_periodic_quarter_shell/particles/particles-00001.0001.vtu
This is a minimal version of #4264 that only disables the broken functionality. I have checked that the test still gives reasonable results with forward euler, and that it now crashes if used with rk2 or rk4.#4264 
@tjhei: Would you be ok cherry-picking this into the release?
> Disable failing particle integration schemes in periodic shells

- include/aspect/material_model/interface.h
- source/material_model/interface.cc
The previous name 'use_strain_rate' did not quite describe what the argument
represented. Better to call it 'compute_strain_rate'. While there, document
what that argument actually means.
/rebuild
> Rename an argument.

- .zenodo.json
This is used by zenodo to fill in authorship of the zenodo release.
> add maintainers to zenodo template

- source/simulator/stokes_matrix_free.cc
- tests/gmg_no_normal_flux_only.prm
- tests/gmg_no_normal_flux_only/screen-output
GMG would crash/assert in
const dealii::IndexSet&
dealii::MGConstrainedDoFs::get_boundary_indices(unsigned int) const
when no prescribed/fixed boundary conditions are set. Bug was introduced
in #4251
fixes #4282
> Fix gmg only normal flux

- source/postprocess/dynamic_topography.cc
- source/postprocess/geoid.cc
- source/postprocess/heat_flux_map.cc
- source/postprocess/topography.cc
proposed solution to address #4190 by using deal.II functionality.
MPI::gather uses boost serialization and receives all data before we can
process it. So this solution might not have great performance for large
runs. I don't think that matters here, though.
> simplify MPI gather for file concatenation

- source/structured_data.cc
- tests/ascii_data_boundary_composition_2d_box_time/screen-output
- tests/ascii_data_boundary_temperature_2d_box_time/screen-output
- tests/ascii_data_boundary_velocity_2d_box_time/screen-output
- tests/ascii_data_boundary_velocity_2d_box_time_backward/screen-output
- tests/ascii_data_boundary_velocity_2d_box_time_non_equidistant/screen-output
- tests/traction_ascii_data/screen-output
I was confused by the presence of an message on screen that turns out to just be written in the wrong place. Move it to where the action described in the message is actually happening, not before the guarding `if`.
/rebuild
> Move a screen message.

- source/boundary_temperature/dynamic_core.cc
- source/postprocess/visualization/seismic_anomalies.cc
This PR uses the reinit function to reinitialize the MaterialModel inputs. It shouldn't change anything, but it's late.
> Use the reinit function for MaterialModelInputs

- source/simulator/stokes_matrix_free.cc
Adding the Newton part to the function`StokesMatrixFreeHandlerImplementation::correct_stokes_rhs()`. @tjhei
> GMG Newton: correct Stokes rhs

- include/aspect/material_model/interface.h
The Property `thermal_conductivity` was missing from the list of all properties.
> Add conductivity to MaterialProperties Property all_properties

- include/aspect/material_model/rheology/drucker_prager.h
Fixes #4273.
Update the documentation of the parse_parameters function now that its implementation has changed. 
@gassmoeller For dislocation and diffusion creep, the documentation says it's the number of phase transitions. The way I read the code, it's the number of phases, so I've updated the documentation accordingly. Is this correct?
> Update documenation of drucker prager parse_parameters()

- source/mesh_deformation/interface.cc
After restart, the setup_dofs function in mesh_deformation/interface.cc is evaluated when sim.time is a NaN. On my local machine, this does not give any issues, but on our cluster, restarted models fail due to this. 
I've replaced the condition with what is used several lines below to deform the initial mesh. However:
When setup_dofs is evaluated at the start of a model run,
sim.time / this->get_time() is 0
sim.timestep_number / this->get_timestep_number() is max int
When setup_dofs is evaluated after restart,
sim.time / this->get_time() is NaN 
sim.timestep_number / this->get_timestep_number() is max int
So the timestep_number comparison seems superfluous, as that condition is never met.
> Do not compare against NaN time

- source/simulator/assemblers/stokes.cc
This quantity is not used in this assembler.
> Remove unnecessary computation

- source/simulator/stokes_matrix_free.cc
- tests/gmg_no_normal_flux_only/screen-output
I think there is a mapping argument missing here.  I have not seen a large influence of this (it only affects the main diagonal for curved meshes with tangential bcs), and it does not solve #4308, but it seem more correct this way anyway. Also fix a comment.
> Add missing mapping

- source/simulator/helper_functions.cc
I had this ready from before @tjhei reminded me that we don't require deal.II 9.3 (and consequently C++14) yet. So it needs to wait till after we require 9.3.
/rebuild
> [deal.II 9.3] Simplify some code using C++14 capture semantics.

- source/simulator/stokes_matrix_free.cc
If the matrix free Stokes solver with the cheap preconditioner does not converge and the parameter file set 0 expensive iterations we currently throw a non-helpful error message ("No history data found, maybe Stokes solver has not been run" or something similar). 
We should only try to access the history data if the solver has actually been run. This allows for a more helpful error message("The Stokes solver did not converge in the number of requested cheap iterations and you requested 0 for ``Maximum number of expensive Stokes solver steps''. Aborting.").
> Avoid unhelpful error message

- source/simulator/solver.cc
- source/simulator/stokes_matrix_free.cc
- tests/nsinker_gmg_idr/screen-output
- tests/poiseuille_2d_pressure_bc_gmg/screen-output
- tests/solver_history/screen-output
I was chasing a bug for quite some time until I realized it only happens in the expensive solver. It would be nice to get this indicated immediately, by printing the number of cheap Stokes solver steps as soon as we know it (to separate crashes in the cheap solver from crashes in the expensive solver). Related to #4330.
This should not change any test output.
> Print cheap stokes iterations immediately

- CONTRIBUTING.md
- doc/manual/manual.tex
Prompted by a question in https://github.com/geodynamics/aspect/pull/4220, which made me realize the process to contribute to the changelog is not well described at the moment. This should help.
> Improve documentation of changelog

- source/utilities.cc
- tests/stokes_solver_fail_A/screen-output
- tests/stokes_solver_fail_S/screen-output
- unit_tests/parse_map_to_double_array.cc
This PR improves the error message for parse_map_to_double_array, to include cases where the prm has the correct format but there is a mismatch in argument sizes (i.e. when the code is in error).
> improved parse_map error message for string format

- source/simulator/checkpoint_restart.cc
- tests/checkpoint_07_enable_free_surface_create.prm
- tests/checkpoint_07_enable_free_surface_create/screen-output
- tests/checkpoint_07_enable_free_surface_create/statistics
- tests/checkpoint_07_enable_free_surface_resume.cc
- tests/checkpoint_07_enable_free_surface_resume.prm
- tests/checkpoint_07_enable_free_surface_resume/screen-output
- tests/checkpoint_07_enable_free_surface_resume/statistics
This is an improvement related to #4341 and #4029. It reorders the operations upon resuming from a checkpoint so that:
- We correctly reach a useful assertion before trying to load the solution vector. This prevents the segmentation fault described in the linked issues and instead provides a useful error message (pressure normalization was changed incorrectly, or mesh deformation was not enabled for checkpoint)
- We now allow disabling pressure normalization during restart. We still do not allow to switch from surface to volume normalization or vice-versa since that makes no sense, however #4341 and #4029 showed that there is demand for switching on mesh deformation during a model for which we would like to be able to switch from surface pressure normalization to no normalization.
> Reorder restart checks

- tests/advection_solver_fail/screen-output
- tests/cmake/default
- tests/stokes_solver_fail/screen-output
- tests/stokes_solver_fail_A/screen-output
- tests/stokes_solver_fail_S/screen-output
- tests/stokes_solver_fail_gmg/screen-output
Several of the tests which purposefully fail report line numbers of errors in the screen-output. This PR replaces those lines so that the test outputs don't need to be changed so often.
> remove lines with code line number from screen-output

- doc/manual/citing_aspect.bib
We have quite a number of references that cite ASPECT that have non-standard fields `abstract`, `notes`, etc. I've removed them from some since bibtex doesn't actually do anything with them. I've also cleaned up inconsistent use of abbreviated first names.
/rebuild
> Clean up references somewhat.

- source/simulator/assemblers/stokes.cc
For GMG, we need grads_phi_u when we have elasticity. 
@tjhei Does this look right to you?
> Stokes: need grads_phi_u when enable_elasticity

- source/postprocess/particles.cc
This makes ASPECT compile with the recent deal.II dev. dealii/dealii#12874 made a parameter const that is set in ASPECT. ASPECT uses our own modified copy of the `ParticleOutput` class.
> Make compile with deal.II-dev

- source/postprocess/particles.cc
Our current particle postprocessor incorrectly builds the particle output patches even if no output format or the output format "none" is selected. This is wasted time. Avoid this by returning earlier if no output is going to be written.
I want to test this a bit further before merging, but reviews are welcome.
> Do not build particle output if no output format is selected

- source/postprocess/heat_flux_map.cc
A minor fix that makes sure that the points written by the heat_flux_map postprocessor actually lie on the surface of the domain (instead of being only linearly interpolated between the vertex locations of the boundary face). This makes no difference for box models, but is important for curved geometries like the spherical shell. The same fix was necessary for the dynamic topography postprocessor in #3370, but I did not check other postprocessors for the same problem at the time.
> Respect manifold for heat flux map postprocessor output

- source/particle/world.cc
This PR optimizes the particle advection in box models without mesh deformation by using the FEPointEvaluation class with MappingCartesian mappings. This was made possible by #dealii/dealii#12773 and results in a speedup of around 3x for particle advection. Non-box models and box models with mesh deformation had this speedup already before.
> Use fast path for particle advection in box

- include/aspect/mesh_deformation/free_surface.h
- source/mesh_deformation/free_surface.cc
Add a function to get the stabilization parameter for the free surface, which is required by the matrix-free implementation. @tjhei
> Mesh deformation: get the free surface stabilization parameter

- include/aspect/material_model/rheology/elasticity.h
- include/aspect/simulator_access.h
- source/material_model/rheology/elasticity.cc
- source/simulator/simulator_access.cc
This is another seemingly small change that drastically improves the speed of computing the reaction terms for elasticity, in particular for particles. By using the deal.II class `FEPointEvaluation` instead of `FEValues` we no longer need to create a new `FEValues` object for every evaluation (which in case of particles was for every particles). The new implementation is fully equivalent and gives the following speedups for the bending beam benchmark with particles. I benchmarked this in reduced resolution on a 25x10 grid and with 1e3 particles for 2 timesteps, I used aspect from PR #4415 and dealii from PR #12983, all in optimized mode:
- Particle Update -> from 0.131s (19%) to 0.00818s (1.7%) runtime, 16X speedup
- Stokes assembly -> from 0.038s (5.5%) to 0.0225s (4.7%), 1.7X speedup
- …
> Optimize elasticity evaluation in material model

- source/boundary_temperature/dynamic_core.cc
- source/geometry_model/two_merged_boxes.cc
- source/geometry_model/two_merged_chunks.cc
- source/mesh_refinement/volume_of_fluid_interface.cc
- source/particle/property/interface.cc
- source/postprocess/boundary_densities.cc
- source/postprocess/boundary_pressures.cc
- source/postprocess/boundary_velocity_residual_statistics.cc
- source/postprocess/dynamic_topography.cc
- source/postprocess/geoid.cc
- source/postprocess/heat_flux_densities.cc
- source/postprocess/heat_flux_map.cc
- source/postprocess/heat_flux_statistics.cc
- source/postprocess/mass_flux_statistics.cc
- source/postprocess/velocity_boundary_statistics.cc
- source/postprocess/visualization/boundary_indicator.cc
- source/postprocess/visualization/boundary_velocity_residual.cc
- source/postprocess/visualization/dynamic_topography.cc
- source/postprocess/visualization/geoid.cc
- source/postprocess/visualization/heat_flux_map.cc
- source/postprocess/visualization/surface_dynamic_topography.cc
- source/simulator/assembly.cc
- source/simulator/helper_functions.cc
- source/simulator/melt.cc
- source/simulator/nullspace.cc
- source/simulator/stokes_matrix_free.cc
- source/termination_criteria/steady_heat_flux.cc
GeometryInfo is quad/hex-specific, and so will have to be removed from deal.II at some point
in the near future. This patch removes a whole bunch of uses of that class and replaces
them by querying this information from the cell we are working on.
/rebuild
> Remove uses of GeometryInfo.

- include/aspect/utilities.h
- source/boundary_composition/function.cc
- source/boundary_temperature/function.cc
- source/boundary_velocity/function.cc
- source/initial_composition/function.cc
- source/initial_temperature/function.cc
- source/mesh_refinement/maximum_refinement_function.cc
- source/mesh_refinement/minimum_refinement_function.cc
- source/utilities.cc
Previously, there was only a non-const version that returned a non-const reference to
a member variable. This isn't usable when the object it is called on is 'const'. So
provide a 'const' version that returns a 'const' reference.
/rebuild
> Provide a 'const' version of NaturalCoordinate::get_coordinates().

- source/geometry_model/chunk.cc
This is the part of #4425 that didn't work yesterday. I checked that at least on my system, there is no difference between the before/after outputs of the `merged_chunks_2D` test that failed yesterday, though the output is (expectedly) slightly different than what's stored.
/rebuild
> More GeometryInfo work, the questionable part.

- source/geometry_model/two_merged_boxes.cc
- source/geometry_model/two_merged_chunks.cc
This seems uncontroversial.
/rebuild
> More GeometryInfo work.

- .github/workflows/linux.yml
It is convenient to see detailed.log and version info, to confirm what
deal.II sha1 was used.
> CI: dealii-dev, show details

- doc/modules/changes/20220103_ekendall
- source/heating_model/radioactive_decay.cc
In response to issue #4412 I changed the assert throw for radiogenic heating such that it should only be evaluated if crust is defined by composition.
* [ X] I have read the guidelines in our [CONTRIBUTING.md](../blob/master/CONTRIBUTING.md) document.
* [ X] I have followed the [instructions for indenting my code](../blob/master/CONTRIBUTING.md#making-aspect-better).
* [X ] I have tested my new feature locally to ensure it is correct.
* [X ] I have added a changelog entry in the [doc/modules/changes](../blob/master/doc/modules/changes) directory that will inform other users of my change.
> fix radiogenic heating assert

- source/material_model/utilities.cc
This is a helpful check if one wants to implement the use of the new types of compositional fields in a material model, since it's easy to make mistakes in the number of fields in the mass fractions vector.
> Add an assert

- doc/modules/changes/20211221_haoyuanli
- include/aspect/material_model/diffusion_dislocation.h
- include/aspect/material_model/latent_heat.h
- include/aspect/material_model/rheology/composite_visco_plastic.h
- include/aspect/material_model/rheology/visco_plastic.h
- source/material_model/diffusion_dislocation.cc
- source/material_model/latent_heat.cc
- source/material_model/rheology/composite_visco_plastic.cc
- source/material_model/rheology/visco_plastic.cc
- source/postprocess/entropy_viscosity_statistics.cc
- source/simulator/entropy_viscosity.cc
- tests/visco_plastic_phases_viscosity_max_min.prm
- tests/visco_plastic_phases_viscosity_max_min/screen-output
- tests/visco_plastic_phases_viscosity_max_min/statistics
I adjust the way "max_visc" and "min_visc" are parsed in the first place and extend them onto compositional phases in the visco_plastic model. This is motivated by granting flexibility to assign shear zone rheology in a subduction channel. It was first discussed in this issue:
https://github.com/geodynamics/aspect/issues/4417
I'd like to ask @anne-glerum or @bobmyhill to review this as they shared their thoughts on the previous issue. Are any of you available.
Since AGU is upcoming, we can slowly but surely go through this.
Thanks for your support.
> Adjust max_visc and min_visc in the visco_plastic module to vectors of phases

- benchmarks/compressibility_formulations/lateral_pipe/lateral_pipe.prm
- benchmarks/compressibility_formulations/lateral_pipe_advect/lateral_pipe.prm
- benchmarks/compressibility_formulations/lateral_pipe_increase_pressure/lateral_pipe.prm
- benchmarks/compressibility_formulations/lateral_pipe_transient/lateral_pipe.prm
- benchmarks/compressibility_formulations/plugins/compressibility_formulations.cc
- benchmarks/compressibility_formulations/vertical_pipe/vertical_pipe.prm
- include/aspect/initial_composition/adiabatic_density.h
- include/aspect/simulator/assemblers/stokes.h
- source/initial_composition/adiabatic_density.cc
- source/simulator/assemblers/stokes.cc
- source/simulator/helper_functions.cc
- source/simulator/parameters.cc
This is the promised follow-up to #4450 and #4451. Everywhere in the code where we were asking for a field named "density_field", we now check for the compositional field type "density" instead. I hope I found everything. 
This is also backwards compatible, since a field that is called "density_field" but has the type unspecified will be converted to type density upon reading in the parameters.
> use new "density" field type for density fields

- doc/modules/changes/20220126_jdannberg
- source/simulator/core.cc
- tests/periodic_compressible.prm
- tests/periodic_compressible/screen-output
- tests/periodic_compressible/statistics
Compressible models with periodic boundaries did not work before. The ones I tried always crashed in the Stokes solver or had very large iteration counts. The problem was that we did not do the pressure right-hand side compatibility modification in case a model had periodic boundaries. This PR fixes this. 
I added a very simple test case, but I also tested this with a more complex model (spherical geometry, nullspace removal, strong viscosity contrast, material properties read in from a look-up table) and it worked as well.
> fix periodic boundary conditions in compressible models

- doc/modules/changes/20220202_gassmoeller
- source/simulator/newton.cc
- tests/tosi_benchmark_newton_solver_full_A.cc
- tests/tosi_benchmark_newton_solver_full_A.prm
- tests/tosi_benchmark_newton_solver_full_A/screen-output
- tests/tosi_benchmark_newton_solver_full_A/statistics
This was a bug in debug mode I noticed in one of @elodie-kendall's models. If we set up a compressible model with a Newton solver and use the full A block of the Stokes matrix for the preconditioner, then the NewtonHandler still adds an assembler for the compressible terms in the preconditioner, although the preconditioner matrix is not used (the full matrix is used instead). Additionally the added assembler will throw an assertion. This change unifies the code paths between the Newton solver and the regular solver (which does not add the assembler for these models).
> Do not create unnecessary failing assembler for compressible Newton models with full A block preconditioner

- include/aspect/postprocess/gravity_point_values.h
- source/postprocess/gravity_point_values.cc
@cedrict complained that the gravity postprocessor is slow. This patch reworks a good bit of it to make it a bit easier to read and (slightly) more efficient. I have more work to do regarding efficiency, but thought I'd get this out of the way already. It's probably easiest to read side-by-side.
I've broken the work into self-contained commits that I've individually tested. I think that also makes it easier to follow the flow of the transformations I've applied.
/rebuild
> Rework the gravity postprocessor

- source/particle/world.cc
This one also makes the code easier to read.
/rebuild
> Avoid access to GeometryInfo in particle code.

- include/aspect/compat.h
- source/utilities.cc
This is the minimum implementation taken from deal.II to broadcast >2GB
of data (ascii data, etc.).
> support reading larger than 2GB data files

- source/material_model/melt_global.cc
- source/particle/property/elastic_stress.cc
- source/particle/world.cc
- source/postprocess/particles.cc
People keep mentioning that the next deal.II version won't be 10.0, but 9.4. We should conservatively check for 9.4 then, which is the correct check even if the release ultimately ends up being 10.0.
/rebuild
> Test for deal.II >= 9.4 instead of 10.0.

- include/aspect/simulator/assemblers/interface.h
- include/aspect/volume_of_fluid/assembly.h
- source/simulator/assemblers/advection.cc
- source/simulator/assemblers/interface.cc
- source/simulator/assembly.cc
- source/volume_of_fluid/assembler.cc
- source/volume_of_fluid/handler.cc
This continues my quest to get rid of places that use `GeometryInfo`. `GeometryInfo` is used widely in all places where we do assembly for DG elements because we need to allocate and then access vectors and matrices for all faces and subfaces. Counting how many of these there are, and then what index to use was previously done via `GeometryInfo::faces_per_cell` and `GeometryInfo::subfaces_per_face`. 
This patch introduces two new functions, `n_interface_matrices(...)` and `nth_interface_matrix(...)` that tell us the number of matrices we need to provision, and the index within such arrays that we want to access for a given face (and subface, if so relevant). The places where this is relevant are in the advection assemblers (where we sometimes use DG elements) and in the volume-of-fluid …
> Get rid of a bunch of GeometryInfo related things.

- source/simulator/core.cc
@anne-glerum: First baby step towards being able to disable boundary conditions for some compositional fields by keeping constrained dofs in the sparsity pattern. @tjhei and @bangerth is this what we talked about on Tuesday?
> Keep constrained dofs in composition block

- doc/modules/changes/20220328_jdannberg
- include/aspect/introspection.h
- source/simulator/assemblers/advection.cc
- source/simulator/assembly.cc
- source/simulator/helper_functions.cc
- source/simulator/introspection.cc
- source/simulator/parameters.cc
- source/simulator/solver_schemes.cc
- tests/prescribed_temperature_with_diffusion.cc
- tests/prescribed_temperature_with_diffusion.prm
- tests/prescribed_temperature_with_diffusion/screen-output
- tests/prescribed_temperature_with_diffusion/statistics
The pull request adds a new advection method for the temperature field called 'prescribed field with diffusion', analogous to the same method that already exists for compositional fields. This is useful for models with prescribed temperature outputs (such as when solving the energy equation for entropy instead of temperature as in the entropy_adiabat benchmark) because it allows for diffusion of the temperature field without applying any of the other terms in the equation. 
I have a follow-up pull request that applies this method using the entropy_adiabat benchmark.
> Prescribed temperature field with diffusion

- tests/gmg_mesh_deform_adaptive_bug/screen-output
https://github.com/geodynamics/aspect/pull/4528 was merged with test results that were correct before https://github.com/geodynamics/aspect/pull/4495 was merged, but wrong afterwards. Due to the overlap the results were not correctly updated (I didnt notice that during reviewing) so the tester currently fails on `main`. This applies the fix and is identical to the changes that #4495 caused in the test `gmg_mesh_deform_adaptive`.
> Fix tester results

- CMakeLists.txt
This PR fixes annoying behavior that happens if you have multiple deal.II versions installed and at least one of them is one or two directory levels above your build folder. In such configurations it is impossible to specify the used deal.II version via an environment variable, because the first deal.II found in the level above will be used instead. deal.II paths directly specified as cmake parameters are respected, but environment variables are not. This patch unifies the behavior for cmake variables and environment variables. deal.II versions in the levels above are still found, but only if there are no cmake or environment variables set.
> Make sure environment variable is respected when searching for deal.II

- benchmarks/viscoelastic_sheared_torsion/viscoelastic_sheared_torsion.prm
- tests/viscoelastic_sheared_torsion.prm
- tests/viscoelastic_sheared_torsion/screen-output
- tests/viscoelastic_sheared_torsion/statistics
This adds the input file for a 3D torsion plus shearing benchmark after Farrington et al. 2014.  
* [X ] I have read the guidelines in our [CONTRIBUTING.md](../blob/main/CONTRIBUTING.md) document.
* [X ] I have followed the [instructions for indenting my code](../blob/main/CONTRIBUTING.md#making-aspect-better).
* [X ] I have tested my new feature locally to ensure it is correct.
> add sheared torsion BM after Farrington et al. 2014

- tests/melt_transport_compressible.cc
The `.cc` file that goes with this test has numerous unused arguments and variables that show up when you do `ctest -V`.
/rebuild
> Avoid compiler warnings for a test.

- include/aspect/introspection.h
- source/simulator/introspection.cc
- source/simulator/stokes_matrix_free.cc
If we ever want to use anything other than hypercube cells, then we must also switch quadrature formulas. In other words, every occurrence of `QGauss` has to be replaced by something that depends on the cell type.
Rather than having lots of `if` or `?:` statements in the code, I thought I'd use this as an opportunity to provide centralized infrastructure for these cases. That's what the first commit does. I think it makes the code easier to read in general because one no longer has to know that adding one to the polynomial degree is what one should be doing to get an appropriate quadrature formula.
The second commit shows how this can be used. There are some 30 places left that need to be looked at, but I thought I'd put this patch out already for comment, and then just work through the …
> Provide centralized facilities for quadrature formulas.

- include/aspect/introspection.h
- source/postprocess/boundary_velocity_residual_statistics.cc
- source/postprocess/mobility_statistics.cc
- source/simulator/introspection.cc
This is the face equivalent of the patch that introduced quadrature formula objects to `Introspection`, #4536 . The second commit uses this in a couple of places as an example.
/rebuild
> Provide the infrastructure for face quadratures.

- include/aspect/geometry_model/box.h
- include/aspect/geometry_model/spherical_shell.h
- include/aspect/geometry_model/two_merged_boxes.h
- include/aspect/postprocess/gravity_point_values.h
Fix compiler warnings about functions that override member functions but are not marked as such.
> Fix override warnings

- include/aspect/introspection.h
- source/boundary_temperature/dynamic_core.cc
- source/postprocess/boundary_densities.cc
- source/postprocess/boundary_pressures.cc
- source/postprocess/composition_statistics.cc
- source/postprocess/heating_statistics.cc
- source/postprocess/mass_flux_statistics.cc
- source/postprocess/material_statistics.cc
- source/postprocess/max_depth_field.cc
- source/postprocess/melt_statistics.cc
- source/postprocess/temperature_statistics.cc
- source/postprocess/velocity_boundary_statistics.cc
- source/postprocess/velocity_statistics.cc
- source/postprocess/viscous_dissipation_statistics.cc
- source/simulator/assembly.cc
- source/simulator/helper_functions.cc
- source/simulator/initial_conditions.cc
- source/simulator/introspection.cc
- source/simulator/melt.cc
- source/simulator/nullspace.cc
- source/simulator/stokes_matrix_free.cc
Another follow-up to #4536 and #4544. This converts most of the rest of the uses of `QGauss`, but not all. 
I needed to also create a quadrature object for the pressure, which is what the first commit does. I somehow forgot that when I created the other quadrature objects.
/rebuild
> More using of centralized quadrature objects.

- source/particle/world.cc
This PR supersedes #4565. It fixes a number of deprecation warnings and uses a new version of a deal.II signal. In the process it also fixes a crash in current master with a current deal.II dev. Because this PR has a different implementation of the `cell_weight` function than #4565 for deal.II 9.4 the fix in the earlier PR is no longer necessary.
> Fix deprecation warnings and incompatibility with deal.II

- source/particle/world.cc
This fixes an incompatibility introduced in deal.II in dealii/dealii#13451. I need to make some further changes to remove deprecation warnings, but the current change at least fixes the crash that we currently get for all particle models running a relatively new deal.II dev version (because the `cell_weight` function is now occasionally called with a `CELL_INVALID` cell status, which it did not do before that change).
> Fix incompatibility with deal.II master

- source/boundary_traction/initial_lithostatic_pressure.cc
In the computation of the initial lithostatic pressure, the velocity, which is a material model input, was not set to any value, which means it was NaN. Material models that use the velocity in their evaluate function would then cause a floating point exception. That is fixed by this PR. 
This is needed so that #3768 works.
> set velocity in computation of initial lithostatsic pressure

- source/fe_variable_collection.cc
- source/simulator/entropy_viscosity.cc
- source/simulator/melt.cc
There are a number of files that for reasons I had never understood always needed to be recompiled after calling the indent script. I've finally figured out why that is so: We end a `#define` macro definition with a trailing backslash followed by an empty line. One part of our indentation script changes the whitespace for that, and another part changes it back. That results in no actual changes, but touched the file, requiring the recompile.
This patch fixes this for all affected files.
/rebuild
> Avoid ending a preprocessor macro with an empty line.

- source/postprocess/visualization.cc
We didn't notice this because the class so far does not have any interesting member functions, but it become clear to me that we were missing the instantiation when doing something related to #4244. Might as well make this a separate patch.
/rebuild
> Add missing instantiation.

- source/postprocess/visualization.cc
While there, document it better.
The function had confused me because, from the name, I had assumed that the point is that it adds something to a list. The problem was that the list was never actually used for anything -- the point wasn't to add something to the list, but to keep track of unique names of output variables, so the point of the function was to assert if necessary.
/rebase
> Rename a function.

- source/material_model/diffusion_dislocation.cc
- source/material_model/grain_size.cc
- source/material_model/rheology/composite_visco_plastic.cc
- source/material_model/rheology/elasticity.cc
- source/material_model/rheology/strain_dependent.cc
- source/material_model/rheology/visco_plastic.cc
- source/particle/property/integrated_strain_invariant.cc
- source/particle/property/viscoplastic_strain_invariants.cc
- source/postprocess/visualization/strain_rate.cc
- source/postprocess/visualization/stress_second_invariant.cc
#3755 made me think about the computation of e_dot_ii. In quite a number of places, we compute it as
```
sqrt( abs( second_invariant( deviator( eps ) ) ) )
```
but that seems wrong. I don't think we should be taking the absolute value -- the second invariant of a deviator should probably already be non-negative (I haven't tried to prove this, though).
This patch fixes this, but I imagine that it won't work because there will likely be cases where numerical round-off means that the second invariant is `-1e-16` or some such, and the square root will not be happy. I just want to try this out.
The "correct" patch -- should the current patch fail because of the anticipated issue with round off -- would be to treat everything negative as zero. I'll do that instead if the patch fails.
/rebuild
> Correct the computation of e_dot_ii.

- contrib/utilities/astyle.rc
As requested in #4614.
/rebuild
> Make --close-templates the default for astyle.

- doc/sphinx/user/methods/approximate-equations/ba.md
Properly hyphenated core-mantle. However please fix 'earth mantle' if you think this should be capitalized.
> Documentation: BA punctuation fix

- include/aspect/postprocess/visualization.h
- source/postprocess/visualization.cc
We're doing things right here with allocating a pointer and letting the consumer function (which may or may not run on a separate thread) delete it, but it can be done automatically if we use `std::unique_ptr` instead. If we run on the same thread, `std::unique_ptr` deletes the object. If we run on a separate thread, we *move* the pointer into the lambda function and the lambda function object deletes the pointed to object once it's done running (on the other thread).
/rebuild
> Use standard idiom to write data in the background.

- source/postprocess/visualization.cc
Using `operator<<` involves some formatting overhead (for example trying to fit a specific field width set with `out << std::width(...)` etc.). We really don't want that here -- just dump it all into that file alright!
/rebuild
> Use unformatted output -- we here really just want a bit-by-bit copy into a file.

- source/simulator/stokes_matrix_free.cc
extracted from #4413
I am not sure if this makes a difference for any of the existing tests.
> GMG: use right mapping with mesh deformation

- doc/sphinx/user/methods/advection-stabilization/entropy-viscosity.md
- doc/sphinx/user/methods/advection-stabilization/index.md
- doc/sphinx/user/methods/advection-stabilization/supg.md
- doc/sphinx/user/methods/freesurface/arbitrary-le-implementation.md
- doc/sphinx/user/methods/melt-transport.md
This addresses all occurrences of ` ` `{math} not starting at the top of the line.
The patch also contains a number of fixes where the `{math}` tag was missing from ` ` `. I suspect that there are many places, and I'm afraid they all need to be fixed by hand.
/rebuild
> Fix a number of sphinx markdown problems.

- source/postprocess/gravity_point_values.cc
This is my first step towards addressing #4485. We currently have a loop of the form
```
if (processor zero)
{
do some output;
for (i=...)
{
compute something;
output the computed thing;
}
}
```
This patch restructures things to do the following instead:
```
std::vector<...> results;
if (processor zero)
for (i=...)
compute something;
if (processor zero)
{
do some output;
for (i=...)
output the computed thing;
}
```
In the second step, I will make computing the thing distributed across all processors, rather than let everyone other than process zero wait.
/rebuild
> Separate computation and output in the gravity postprocessor.

- source/boundary_traction/initial_lithostatic_pressure.cc
This adds the option for the two merged chunks to the  initial lithostatic pressure plugin.
> Add two merged chunks to initial lithostatic pressure plugin.

- doc/sphinx/user/extending/idea-of-plugins.md
- doc/sphinx/user/extending/plugin-types/geometry-models.md
- doc/sphinx/user/extending/plugin-types/gravity-models.md
- doc/sphinx/user/extending/plugin-types/heating-models.md
- doc/sphinx/user/extending/plugin-types/initial-conditions.md
- doc/sphinx/user/extending/plugin-types/material-models.md
- doc/sphinx/user/extending/plugin-types/mesh-refinement.md
- doc/sphinx/user/extending/plugin-types/postprocessors.md
- doc/sphinx/user/extending/plugin-types/temp-bc.md
- doc/sphinx/user/extending/plugin-types/terminate-criteria.md
- doc/sphinx/user/extending/plugin-types/velocity-bc.md
- doc/sphinx/user/extending/plugin-types/vis-postprocessors.md
- doc/sphinx/user/extending/signals.md
See the correct syntax in quickref.md, and confirmed by @cmills1095 .
/rebuild
> Fix code block markup.

- cookbooks/burnman/doc/burnman.md
Get the burnman cookbook documentation cleaned up. Ideally this can be used as an example for anyone else who is cleaning up cookbooks. Can whoever approves this pull request please check the box "2D compressible convection with a reference profile and material properties from BurnMan" in my comment in [the associated github issue](https://github.com/geodynamics/aspect/issues/4595#issuecomment-1128164609), thank you
> Docs: Burnman cookbook converted

- doc/sphinx/user/cookbooks/cookbooks-overview.md
- doc/sphinx/user/cookbooks/geophysical-setups.md
- doc/sphinx/user/extending/idea-of-plugins.md
- doc/sphinx/user/extending/plugin-types/geometry-models.md
- doc/sphinx/user/extending/plugin-types/mesh-refinement.md
- doc/sphinx/user/extending/plugin-types/postprocessors.md
- doc/sphinx/user/extending/plugin-types/vis-postprocessors.md
- doc/sphinx/user/extending/signals.md
- doc/sphinx/user/extending/testing/test-properties.md
- doc/sphinx/user/extending/write-a-cookbook/manual-section.md
- doc/sphinx/user/extending/write-a-plugin.md
I suspect that these had gotten in there because someone used a non-American keyboard when writing the latex sources, inserting a unicode quote.
/rebuild
> Use ASCII quotes.

- doc/sphinx/user/install/docker-container/index.md
Deletes the duplicate header inserted as ####
> Documentation: docker - rm duplicate header

- include/aspect/postprocess/visualization.h
- source/postprocess/visualization.cc
Since we call this function from a lambda function (which may itself be run on a separate thread), we no longer need to worry about copying the function arguments -- the lambda function has to worry about it, and does in #4639 and #4645. (The style must have been a left-over when we didn't use lambda functions but used `Threads::new_thread()`.)
Follow-up to https://github.com/geodynamics/aspect/pull/4639.
> No longer take arguments by value.

- source/postprocess/gravity_point_values.cc
Related to #4485. We allocate a vector of tensors when a vector of symmetric tensors would be sufficient. It turns out that we only ever compute the upper right half of these objects anyway.
/rebuild
> Save a few bytes.

- .github/workflows/linux.yml
Currently the Github actions workflow only checks the indentation, but does not provide a diff file that fixes it. This PR adds that by uploading the diff as an artifact. The artifact will be uploaded for every build, but if the indentation is fine the artifact will be empty.
> Create indentation artifact by Github tester

- source/postprocess/gravity_point_values.cc
Finally fixes #4485. Passes the tests, including the one that runs the gravity postprocessor in parallel (a test that was quite useful because I broke it with several intermediate versions of this patch).
@cedrict FYI
/rebuild
> Parallelize the computation of theoretical gravity values.

- doc/sphinx/user/run-aspect/run-faster/pressure-norm-off.md
Deletes an awkward hyphen.
Still needs properly referenced links.
> Documentation: pressure normalization

- doc/sphinx/user/run-aspect/parameters-overview/index.md
I found the bullet points confusing as it referred to the "implemented models" in both bullets and the point was unclear. I rewrote it to remove the "which" that starts the phrase. Is this what is really meant?
Still needs properly referenced links.
> Documentation: Parameter overview

- doc/sphinx/user/benchmarks/index.md
Now from the correct repository. Supersedes #4714
> Documentation: fix reference to benchmark

- doc/sphinx/index.md
- doc/sphinx/user/index.md
Some improvements to the documentation start page. The text about ASPECT was taken from aspect.geodynamics.org.
> Improve documentation start page

- CMakeLists.txt
- doc/CMakeLists.txt
- doc/manual/cookbooks/annotate.pl
- doc/manual/cookbooks/escape_index_entries.pl
We need to eventually process all of the `.prm` snippets as input to sphinx. Right now, for the latex manual, this is done with a separate `Makefile` in the `doc/` directory, but that needs to eventually be replaced by something we do in cmake. This is a first step towards it.
The patch right now really only gathers the `.prm` files and runs them through a couple of perl files. This is essentially the same as the current `Makefile`, except that I'm using perl for both scripts where the `Makefile` uses one perl and one sed script. The result of the current steps also ends up in a sub-directory of the build directory, rather than the source directory.
At the moment, no target depends on doing all of this, so unless you type `make manual` in your build directory, nothing happens. And if you …
> Create the .prm.tex files from all .prm files.

- doc/sphinx/conf.py
- doc/sphinx/user/methods/index.md
- doc/sphinx/user/methods/nonlinear-stokes-solvers.md
This is a replacement to #4204, which adds a section to the manual about choosing nonlinear solvers. It is not ready yet, but it is a test to see how the new documentation work.
> Add nonlinear solver manual section

- cookbooks/shell_simple_2d/shell_simple_2d
This was probably accidentally merged during the cookbook conversion.
> Remove stray symbolic link

- Jenkinsfile
The pdf manual doesn't build anymore and maybe we don't need to run the
tester then.
> [ci] disable building pdf manual
