geodynamics/aspect

doc/modules/main.h, doc/options.dox, include/aspect/boundary_composition/box.h, include/aspect/boundary_composition/initial_composition.h, include/aspect/boundary_composition/interface.h, include/aspect/boundary_composition/spherical_constant.h, include/aspect/introspection.h, include/aspect/particle/output.h, include/aspect/simulator.h, source/simulator/helper_functions.cc
- add doxygen search engine
- add missing @params
- fix layout of list
- improve some documentation
=> Doxygen fixes

doc/modules/changes.h, include/aspect/postprocess/mass_flux_statistics.h, source/postprocess/mass_flux_statistics.cc, tests/mass_flux_statistics.prm, tests/mass_flux_statistics/screen-output, tests/mass_flux_statistics/statistics
@bangerth: You are faster in merging than I can prepare and upload my branches :-).
This is actually the work during which I found the previous bug.
=> Add mass flux statistics and test.

source/postprocess/dynamic_topography.cc, source/postprocess/visualization/dynamic_topography.cc
- simplify code
- suppress warnings about uninitialized variables
=> clean up dynamic topography plugins

include/aspect/global.h, source/particle/integrator.cc
- Tensor fixes
- deprecation of multithread_info
=> fixes for deal 8.3

doc/manual/manual.tex, doc/modules/changes.h, source/main.cc, source/utilities.cc, tests/CMakeLists.txt, tests/dash-dash.cc, tests/dash-dash.prm, tests/dash-dash/screen-output
I couldn't figure out a way to test this with MPI but there is a test for the
non-parallel case and I verified manually that it works with MPI.
=> Implement calling ASPECT in a way that reads input from stdin.

include/aspect/global.h, source/utilities.cc
Note that astyle 2.05.1 seems to be broken for many files, so I am using
2.04.
=> astyle formatting

doc/manual/manual.tex
I simply failed to adjust the paths to the pictures are copy-pasting
from the figure above.
=> Use correct path to pictures.

include/aspect/velocity_boundary_conditions/gplates.h, source/velocity_boundary_conditions/gplates.cc
This cleans up some things I saw while reading through #312. The gplates plugin needs some more rework at a later time, but this is something that @ebredow needs for her thesis, so I will help her with that during the hackathon.
=> Fix compiler warnings.

include/aspect/introspection.h, include/aspect/parameters.h, include/aspect/simulator.h, include/aspect/simulator_access.h, source/simulator/core.cc, source/simulator/introspection.cc, source/simulator/parameters.cc
- put Parameters in a separate .h/.cc
- Introspection is initialized from Parameters
- simplify Introspection construction
=> Extract Parameters and improve Introspection construction

include/aspect/plugins.h, source/adiabatic_conditions/interface.cc, source/boundary_composition/box.cc, source/boundary_composition/interface.cc, source/boundary_composition/spherical_constant.cc, source/boundary_temperature/ascii_data.cc, source/boundary_temperature/box.cc, source/boundary_temperature/interface.cc, source/boundary_temperature/spherical_constant.cc, source/compositional_initial_conditions/interface.cc, source/geometry_model/interface.cc, source/gravity_model/interface.cc, source/heating_model/interface.cc, source/initial_conditions/interface.cc, source/material_model/interface.cc, source/postprocess/visualization/internal_heating.cc, source/simulator/assembly.cc, source/simulator/checkpoint_restart.cc, source/simulator/initial_conditions.cc, source/velocity_boundary_conditions/gplates.cc, source/velocity_boundary_conditions/interface.cc
=> Fix a sizable number of warnings.

doc/manual/manual.tex
This is a first version that tries to address #324. Let me know about your opinion. We can easily add commands at the end for different package managers or extend it to subsubsections for different operating systems.
=> Add subsection about required packages

include/aspect/compat.h, include/aspect/global.h, include/aspect/simulator.h, source/postprocess/composition_statistics.cc, source/postprocess/topography.cc, source/postprocess/velocity_boundary_statistics.cc, source/simulator/helper_functions.cc, source/simulator/nullspace.cc
- introduce compatibility functions
- use deal.ii functions if available (from today!)
=> use MPI::min

doc/astyle.rc
- mention required astyle version
- remove options commented out
- add some comments
=> clean up astyle file

source/material_model/table.cc
Max modified table.cc to include a more helpful error message.
=> Added a more helpful set of error messages to table.cc

source/postprocess/visualization.cc
=> improve the error message

include/aspect/simulator_access.h, source/initial_conditions/adiabatic.cc, source/initial_conditions/solidus.cc, source/initial_conditions/spherical_shell.cc, source/postprocess/basic_statistics.cc, source/postprocess/table_velocity_statistics.cc, source/simulator/simulator_access.cc
As just discussed, let's see if this triggers any assertions in the testsuite.
=> Add assertions

doc/manual/manual.tex
Just a little information which I missed during the ASPECT installation.
=> Added a useful remark in the ASPECT installation section of the manual.

source/material_model/table.cc
Changed "Not in range" to something that gave a little more feedback.
=> Fixed error messages in table.cc in material model

source/simulator/core.cc
Bug involving the calculation of global volume with a free surface.  This should be computed after making sure the mesh is properly redistributed, not before.
=> Move volume calculation so it does not run afoul of a messed-up mesh

source/global.cc
Opened for comments / suggestions
=> Added new physical and planetary constants

include/aspect/material_model/interface.h, source/material_model/interface.cc
This will be useful with Bob and Jacky's compositing material model.
=> Separate reading parameters from creating the material model object.

source/postprocess/visualization.cc
Improvement to exception message in visualization.cc
=> Improve visualization error message.

include/aspect/material_model/interface.h, source/material_model/interface.cc
This is going to be useful to Bob and Jacky's upcoming material model composers.
=> Provide a way to query the names of valid material models.

source/boundary_composition/spherical_constant.cc, source/material_model/simple.cc, source/material_model/simple_compressible.cc
Fixed things Shangxin found in the manual to show him how to fix the manual and make a pull request.
=> Fixed things in documentation

README.md
=> remove manual.pdf

doc/modules/changes.h, include/aspect/global.h, source/global.cc
Global physical and planetary constants for Earth and Mars, including docstrings with references
=> Updated global constants

include/aspect/global.h, source/global.cc
Earth core, mantle and planetary masses added on request of I. Rose.
=> added masses relevant to Earth, minor restructuring of namespaces

source/postprocess/table_heat_flux_statistics.cc
Fix compile error due to incorrect test as in #358
=> Use has_boundary_temperature

doc/manual/manual.tex, doc/modules/changes.h, include/aspect/simulator.h, include/aspect/simulator_access.h, include/aspect/simulator_signals.h, source/simulator/core.cc, source/simulator/parameters.cc, source/simulator/simulator_access.cc, source/simulator/simulator_signals.cc, tests/signals.cc, tests/signals.prm, tests/signals/screen-output, tests/signals_connect.cc, tests/signals_connect.prm, tests/signals_connect/screen-output, tests/signals_post_constraints.cc, tests/signals_post_constraints.prm, tests/signals_post_constraints/screen-output, tests/signals_post_constraints/statistics
Documentation is still missing. Feedback nevertheless welcome!
=> Add signals

include/aspect/material_model/simple_compressible.h, source/material_model/simple_compressible.cc
=> Updated simple compressible model from compatibility mode

include/aspect/utilities.h, source/postprocess/visualization/seismic_anomalies.cc, source/simulator/helper_functions.cc
Also sprinkle in some assertions.
=> move extract_composition_values_at_q_point to utilities

include/aspect/material_model/simple_compressible.h, source/material_model/simple_compressible.cc
The previous two merges crossed wires.
=> Make compile again.

doc/modules/changes.h, include/aspect/material_model/diffusion_dislocation.h, source/material_model/diffusion_dislocation.cc, tests/diffusion_dislocation.prm, tests/diffusion_dislocation/screen-output, tests/diffusion_dislocation/statistics
Opened for comments/suggestions...
=> New generic diffusion-dislocation creep model

doc/manual/manual.tex, include/aspect/simulator_signals.h, source/simulator/parameters.cc, source/simulator/simulator_signals.cc, tests/signals.cc
@jperryhouts -- this is for you.
=> Also pass the dimension in which ASPECT will be run to the signals.

doc/manual/manual.tex
Boilerplate for acknowledging CIG
=> Update to Acknowledgement

benchmark/burstedde/burstedde.prm, benchmark/inclusion/adaptive.prm, benchmark/inclusion/global.prm.base, benchmark/solcx/solcx.prm, benchmark/solkz/solkz.prm, benchmark/tangurnis/code/tangurnis.cc
Fix floating point exceptions in the benchmark folder
=> fix benchmarks

doc/manual/cookbooks/crustal_deformation/crustal_model_2D_part1.prm.out, doc/manual/cookbooks/crustal_deformation/crustal_model_2D_part2.prm.out, doc/manual/cookbooks/crustal_deformation/crustal_model_2D_part3.prm.out, doc/manual/cookbooks/crustal_deformation/crustal_model_3D_part1.prm.out
These were forgotten in the addition of Cedric's cookbook (#477).
=> Add some files.

cookbooks/gplates-3d.prm
This is essentially the same parameter file as gplates-2d, but in 3D as described in the manual.
=> Add gplates-3d cookbook parameter file

data/initial-conditions/ascii-data/test/shell_2d.txt, doc/modules/changes.h, include/aspect/geometry_model/chunk.h, source/boundary_composition/spherical_constant.cc, source/boundary_temperature/spherical_constant.cc, source/geometry_model/chunk.cc, source/initial_conditions/harmonic_perturbation.cc, source/initial_conditions/spherical_shell.cc, source/utilities.cc, tests/chunk-ascii-initial-temperature.prm, tests/chunk-ascii-initial-temperature/screen-output, tests/chunk-ascii-initial-temperature/statistics, tests/chunk-conditions.prm, tests/chunk-conditions/screen-output, tests/chunk-conditions/statistics, tests/chunk-first-time-step-2d.prm, tests/chunk-first-time-step-2d/screen-output, tests/chunk-first-time-step-2d/statistics, tests/chunk-first-time-step-3d.prm, tests/chunk-first-time-step-3d/screen-output, tests/chunk-first-time-step-3d/statistics
Initial temperature and boundary conditions from spherical shell geometry updated to include chunk geometry.
Dependent on Pull request #466.
=> Chunk conditions

source/simulator/core.cc
Compute initial Stokes residual in the same way as for iterated IMPES
=> Iterated stokes 2

include/aspect/material_model/interface.h
Almost not worth a whole commit for this but I keep coming across it and it keeps bugging me.
=> very small comment typo

source/simulator/assembly.cc, tests/artificial_postprocess.cc, tests/artificial_postprocess.prm, tests/artificial_postprocess/screen-output, tests/artificial_postprocess/statistics
Attempting to fix a bug
@tjhei should I rename block_idx (see below)? Or was the code correct as is here?
Wait for test results before merge.
=> block_index --> base_element in assembly.cc

doc/modules/changes.h
=> Added line to changes.h about compositional vectors postprocessor.

source/simulator/parameters.cc
Move zlib requirement check to a sensible position (it will never
trigger in declare_parameters).
=> move zlib check

doc/modules/changes.h
=> The new entry to changes.h for the averaging

include/aspect/material_model/composition_reaction.h, source/material_model/composition_reaction.cc, tests/composition_reaction_iterated_IMPES.cc
=> Converted composition reaction materal model to modern interface

doc/modules/changes.h
=> New entry for SAVANI in change.h

doc/modules/changes.h, include/aspect/geometry_model/ellipsoidal_chunk.h, include/aspect/simulator_signals.h, source/geometry_model/ellipsoidal_chunk.cc, source/simulator/solver.cc
- dump to file output/solver_history.txt if the solver fails
- add a signal/slot to access solver history data even if solver
succeeds
- add test
=> Solver history

include/aspect/material_model/depth_dependent.h, source/material_model/depth_dependent.cc
- replace Assert with AssertThrow for user input
- formatting
=> cleanup depth_dependent material model

doc/manual/manual.tex
Gerry Puckett kindly pointed this out.
=> Fix misspelled name 'Rayleigh'.

doc/manual/manual.tex
- use \aspect{}
- clarification regarding directory for "cmake ."
=> manual: minor edits

include/aspect/compat.h, source/geometry_model/ellipsoidal_chunk.cc, source/simulator/nullspace.cc, source/velocity_boundary_conditions/gplates.cc
- deprecation warnings (Tensor changes in deal 8.4)
- unused parameters
=> avoid warnings

doc/manual/cookbooks/free_surface/freesurface.part.prm, doc/manual/cookbooks/free_surface/freesurface.part.prm.out, doc/manual/cookbooks/shell_simple_3d/part2.part.prm, doc/manual/cookbooks/shell_simple_3d/part2.part.prm.out, doc/manual/parameters.tex
- fix two bugs in .prm files for the manual
- update parameters.tex
=> Manual references

doc/modules/changes.h, source/simulator/checkpoint_restart.cc
This adds checkpointing to free surface computations, addressing #614.
I attempted to add a checkpointing test, but I think I was running into the same issue as in #616, so was having difficulty getting complete reproducibility. I have not included it at the moment, but am open to suggestions.
=> Free surface resume

include/aspect/plugins.h, source/boundary_composition/interface.cc, source/boundary_temperature/interface.cc, source/geometry_model/interface.cc, source/gravity_model/interface.cc, source/heating_model/interface.cc, source/initial_conditions/interface.cc, source/material_model/interface.cc, source/prescribed_stokes_solution/interface.cc
=> Give default parameters acceptable values, even if unspecified.

include/aspect/geometry_model/box.h, include/aspect/geometry_model/chunk.h, include/aspect/geometry_model/ellipsoidal_chunk.h, include/aspect/geometry_model/interface.h, include/aspect/geometry_model/sphere.h, include/aspect/geometry_model/spherical_shell.h, include/aspect/geometry_model/two_merged_boxes.h
=> Document more clearly what we mean by 'depth' in the geometry models.

doc/modules/changes.h
It seems github did not see this conflict between #672 and #411, when I merged Anne's PR. Anyway, this should fix it.
=> Fix changes.h

doc/manual/manual.tex
=> Shrink some figures that are overly large.

include/aspect/particle/generator/ascii_file.h, include/aspect/particle/generator/interface.h, include/aspect/particle/generator/uniform_box.h, include/aspect/particle/generator/uniform_radial.h, include/aspect/particle/integrator/interface.h, include/aspect/particle/interpolator/interface.h, include/aspect/particle/output/interface.h, include/aspect/particle/property/interface.h, source/particle/generator/ascii_file.cc, source/particle/generator/interface.cc, source/particle/generator/uniform_box.cc, source/particle/generator/uniform_radial.cc, source/particle/integrator/interface.cc, source/particle/interpolator/interface.cc, source/particle/output/interface.cc, source/particle/property/interface.cc
Forgot to add these when making the pull request for particles.
=> Add virtual particle property destructor

benchmark/burstedde/burstedde.cc, benchmark/inclusion/inclusion.cc, doc/modules/changes.h, include/aspect/velocity_boundary_conditions/ascii_data.h, include/aspect/velocity_boundary_conditions/function.h, include/aspect/velocity_boundary_conditions/gplates.h, include/aspect/velocity_boundary_conditions/interface.h, include/aspect/velocity_boundary_conditions/zero_velocity.h, source/simulator/core.cc, source/velocity_boundary_conditions/ascii_data.cc, source/velocity_boundary_conditions/function.cc, source/velocity_boundary_conditions/gplates.cc, source/velocity_boundary_conditions/interface.cc, source/velocity_boundary_conditions/zero_velocity.cc, tests/burstedde.cc, tests/inclusion_2.cc, tests/prescribed_velocity_boundary.cc, tests/prescribed_velocity_boundary.prm, tests/prescribed_velocity_boundary/screen-output
This pull request adds the boundary indicator to the velocity boundary conditions.
=> Add the boundary indicator to the velocity boundary conditions.

CMakeLists.txt, benchmark/burstedde/CMakeLists.txt, benchmark/crameri_et_al/case_1/CMakeLists.txt, benchmark/davies_et_al/case-2.3-plugin/CMakeLists.txt, benchmark/inclusion/CMakeLists.txt, benchmark/solcx/CMakeLists.txt, benchmark/solkz/CMakeLists.txt, benchmark/tangurnis/code/CMakeLists.txt, cmake/AspectConfig.cmake.in, cookbooks/free-surface-with-crust/plugin/CMakeLists.txt, cookbooks/prescribed_velocity/CMakeLists.txt, doc/manual/manual.tex, doc/plugin-CMakeLists.txt
- nicer error message ASPECT is not found
- add copyright notices
- create symbolic link to ASPECT in plugin directory
=> Plugin cmake improvements

source/particle/integrator/euler.cc, source/particle/integrator/rk_2.cc, source/particle/integrator/rk_4.cc
This should close #692, though I can not check, because I do not see the warnings here. @tjhei, do you want to check, or should we just wait for the tests and merge?
=> Fix some warnings

include/aspect/mesh_refinement/particle_density.h, source/mesh_refinement/particle_density.cc
Extend the description of a plugin. Pre-approved by #697.
=> Extend description

include/aspect/simulator_access.h, source/simulator/simulator_access.cc
This just adds a few functions to SimulatorAccess that I needed for separate work but that might also be useful elsewhere -- so it put them into a pull request of their own.
=> Add several functions to SimulatorAccess.

include/aspect/material_model/interface.h, source/material_model/interface.cc, tests/additional_outputs.cc, tests/additional_outputs.prm, tests/additional_outputs/screen-output
Add a structure that makes it possible to add new quantities to the MaterialModelOutputs.
=> Additional material outputs

doc/modules/changes.h, include/aspect/postprocess/command.h, source/postprocess/command.cc, tests/command_postprocessor.prm, tests/command_postprocessor/log.txt, tests/command_postprocessor/screen-output, tests/command_postprocessor/statistics
I think this is handy. I have a python script for generating simple figures based on the output, and this plugin allows me to automatically run that script at the end of each timestep. It could also be used for all kinds of other stuff (progress notifications, etc)
One question: I remember there being a mechanism for forcing the order of plugins. Is that the case, and how could I use it to force this plugin to run last?
=> Postprocessor for executing shell commands.

include/aspect/velocity_boundary_conditions/gplates.h, source/velocity_boundary_conditions/gplates.cc
=> Use static_cast<int> inside each call to std::abs() in gplates.cc

include/aspect/global.h
This is a totally pointless commit other than for the fact that it makes the code slightly easier to read.
=> Indent #include statements inside #ifdef...#endif.

include/aspect/assembly.h, include/aspect/simulator.h, include/aspect/simulator_signals.h, source/simulator/assembly.cc, source/simulator/core.cc, tests/additional_outputs_02.cc, tests/additional_outputs_02.prm, tests/additional_outputs_02/screen-output
- add a signal set_assemblers
- add AssemblerBase::create_additional_material_model_outputs
- add test
=> introduce create_additional_outputs

doc/modules/changes.h
Documents addition of dG from #661.
=> Update changes.h to mention addition of dG implementation for advection systems

include/aspect/simulator.h, include/aspect/simulator_signals.h
This is an attempt to atone for my slowness in reviewing #751 and addresses
what I would have commented on had I reviewed it in a reasonable time.
=> Update a couple of comments and other stylistic issues.

include/aspect/utilities.h, source/utilities.cc
- move band_matrix into .cc
- improve documentation
- remove unused variables
=> cleanup of spline class

include/aspect/assembly.h, include/aspect/simulator.h, source/heating_model/constant_heating.cc, source/heating_model/function.cc, source/heating_model/interface.cc, source/heating_model/radioactive_decay.cc, source/simulator/assembly.cc
This is a further step towards #733. I am not exactly finished yet, this is mostly to show the idea and let the tester have a look at it. In particular the face terms are not touched yet, I will need to change the function for that (another PR incoming over the next days).
=> Modularize advection assembly

source/postprocess/tracers.cc, tests/composition_passive_tracers/screen-output, tests/particle_load_balancing_repartition/screen-output, tests/particle_output_none/screen-output
=> Make the screen output of the tracer postprocessor look like all other postprocessors.

source/postprocess/depth_average.cc
It's always a bad idea to have code twice.
=> Avoid duplication of some code.

doc/manual/manual.tex
Also provide a reference to one of the subsections that was written after the
original reference was put in place.
=> Clarify the grammar of a statement in the manual.

doc/modules/changes.h, include/aspect/utilities.h, source/utilities.cc
I will need this for a follow-up patch. There, I will also have a test that
exercises this new function.
=> Add a function Utilities::orthogonal_vectors().

include/aspect/particle/world.h, source/particle/world.cc, source/postprocess/tracers.cc
These are just minor cleanups to #805. @gassmoeller ?
=> Minor cleanups

CMakeLists.txt
very convenient and stolen from deal.II
=> introduce "make indent"

source/simulator/assembly.cc
=> skip face assembly loop if not needed

doc/update_parameters.sh, source/initial_conditions/adiabatic_boundary.cc
- fix doxygen compilation
- replace ASPECT_SOURCE_DIR using util function
=> minor adiabatic boundary fixes

cookbooks/finite_strain/finite_strain.cc
This diff came up when I ran indent on my machine. Maybe the tester doesn't check /cookbooks/ correctly? Who knows.
=> fix astyle from #860

doc/manual/cookbooks/finite_strain/finite_strain.cc
=> fix astyle formatting

source/simulator/core.cc, tests/free_surface_adaptive_blob/screen-output, tests/free_surface_adaptive_blob_petsc/screen-output, tests/minimum_refinement_function_time_dependent/log.txt, tests/minimum_refinement_function_time_dependent/screen-output, tests/periodic_box_mpi10/screen-output
=> fix wrong reporting of number of grid levels

doc/manual/manual.tex
Fix units in a formula. While there, also mark up units in the formula as upright text.
=> Fix manual

doc/manual/manual.tex
=> Document nonzero boundary conditions for compositional fields.

source/particle/property/function.cc, source/particle/property/initial_composition.cc, source/particle/property/pT_path.cc, source/particle/property/position.cc, source/particle/property/velocity.cc
Remove some unnecessary newlines that Wolfgang noticed during reviewing #856 also in other particle property plugins.
=> Remove unnecessary newlines

doc/modules/to-1.4.0.h
=> Update changelog for assembler modularization

doc/manual/manual.tex
=> break long lines in .cc listings in manual

doc/modules/changes.h, source/postprocess/visualization.cc
This should close #802 and #964. Please wait for the tests and let me take another look after the tester finished, I have not tested this at all so far (but it is the same logic that is used for the particles).
=> Run visualization in initial refinement if requested

source/simulator/checkpoint_restart.cc
This helps track down what exactly it is that doesn't work.
=> Also output error codein calls to system().

doc/manual/manual.tex
=> Add name to manual

include/aspect/simulator_signals.h
=> Update wrong documentation of a signal.

doc/modules/changes.h
Documents changes made in #991
=> Update changes.h for removing deprecated functions.

doc/modules/changes.h, include/aspect/free_surface.h, source/simulator/assembly.cc, source/simulator/checkpoint_restart.cc, source/simulator/core.cc, source/simulator/free_surface.cc, source/simulator/parameters.cc, source/simulator/simulator_access.cc
=> Rename files to be more consistent with the rest of the files in ASPECT.

cookbooks/inner_core_convection/inner_core_assembly.cc
Add a file that was missing in the previous pull request.
=> add missing file

source/simulator/parameters.cc
I don't think a default of 2 makes a lot of sense.
=> set default number of adaptive cycles to 0

include/aspect/initial_conditions/S40RTS_perturbation.h, include/aspect/initial_conditions/SAVANI_perturbation.h, source/initial_conditions/S40RTS_perturbation.cc, source/initial_conditions/SAVANI_perturbation.cc
-rename 'datadirectory' to 'data_directory'
-add '/' to the end of a user-specified data directory if one is not there
=> fix S40RTS and SAVANI data directory parameter

include/aspect/material_model/visco_plastic.h, source/material_model/visco_plastic.cc, tests/visco_plastic_yield.prm, tests/visco_plastic_yield/screen-output
Include a stress limiter rheology option in the visco_plastic material model.  Updates include a switch option to use the Drucker Prager or stress limiter option and documentation for the stress limiter option.
=> Stress limiter rheology

source/simulator/core.cc
=> Use MappingQ1 when appropriate.

doc/manual/cookbooks/benchmarks/solitary_wave/solitary_wave.prm.out, doc/manual/cookbooks/inner_core_convection/inner_core_traction.part.1.prm.out, doc/manual/cookbooks/inner_core_convection/inner_core_traction.part.2.prm.out, doc/manual/empty.prm, doc/manual/parameters.tex, doc/update_parameters.sh
For easier review: look at the last commit separately. We should also merge #1022 first, because this edits to it will change this output.
I had to switch to a direct solver for empty.prm that is used to generate the default output because the iterative solver doesn't converge. While I could investigate why it stopped working, it will probably requiring us to set many other options...
=> Update parameters for manual

include/aspect/utilities.h, source/material_model/diffusion_dislocation.cc, source/material_model/multicomponent.cc, source/material_model/visco_plastic.cc
Fix to issue #528 by adding a utility to create a vector of length N by either copying a given vec of length N or duplicating a single provided value N times. Commentary on implementation, error format/message would be welcome.
Currently only the double type is offered.
=> Introduce a function possibly_extend_to_N

cookbooks/prescribed_velocity/prescribed_velocity.cc, doc/manual/manual.tex
=> Some manual updates.

source/main.cc, tests/prmbackslash_2.prm
=> Use Deal.II line continuation

include/aspect/material_model/steinberger.h, include/aspect/utilities.h, source/initial_conditions/S40RTS_perturbation.cc, source/initial_conditions/SAVANI_perturbation.cc, source/initial_conditions/adiabatic_boundary.cc, source/initial_conditions/solidus.cc, source/main.cc, source/material_model/depth_dependent.cc, source/material_model/steinberger.cc, source/particle/generator/ascii_file.cc, source/utilities.cc, source/velocity_boundary_conditions/gplates.cc
Adds the function suggested in #666.
=> Add a function expand_ASPECT_SOURCE_DIR

include/aspect/utilities.h, source/initial_conditions/S40RTS_perturbation.cc, source/initial_conditions/SAVANI_perturbation.cc, source/initial_conditions/harmonic_perturbation.cc, source/mesh_refinement/maximum_refinement_function.cc, source/mesh_refinement/minimum_refinement_function.cc, source/particle/generator/uniform_radial.cc, source/utilities.cc, source/velocity_boundary_conditions/gplates.cc, tests/coordinate_transformation.cc
This pull request adds ellipsoid functions to utilities, and changes the names of the spherical functions to be able to make a better distinction between the spherical and ellipsoidal functions. #798
=> Add ellipsoid functions to utilities

doc/manual/manual.tex, doc/modules/changes.h
=> Provide updates on continuation lines in .prm files.

doc/modules/groups.h
Add doxygen group and description for initial topography framework. 
@anne-glerum #1080 #1063
=> Add doxygen group and description for initial topography framework.

doc/modules/changes.h, include/aspect/global.h, include/aspect/postprocess/memory_statistics.h, include/aspect/simulator.h, include/aspect/simulator_access.h, source/global.cc, source/postprocess/memory_statistics.cc, source/simulator/helper_functions.cc, source/simulator/simulator_access.cc, tests/memory_statistics_1.prm, tests/memory_statistics_1/screen-output
Addresses #1052 
@tjhei would you be able to give some feedback on this very rough setup? Obviously lots more stats to add and tidying up of the description etc.
Outputs to both the statistics file and screen output. 
I can either add matrix stats a la #1053 in this, or add it to the same postprocessor/different postprocessor later.
=> Initial mockup of memory stats postprocessor

source/material_model/averaging.cc
=> Fix the Averaging::evaluate function

doc/manual/manual.tex
Add Menno Fraters to contributors on manual.
=> Add Menno Fraters to contributors on manual.

doc/manual/manual.tex
Follow-up to #1087. As discussed, we don't want to provide a bibtex entry for the website.
@ljhwang -- correct?
=> Remove bibtex entry for the website, as previously discussed.

doc/manual/manual.tex
=> some fixes to convection box cookbook

source/material_model/diffusion_dislocation.cc, source/material_model/morency_doin.cc, source/material_model/visco_plastic.cc
Noticed while reviewing #1129.
=> Make the way we describe the units of the specific heat more uniform.

source/postprocess/dynamic_topography.cc, source/postprocess/visualization/dynamic_topography.cc
=> Improve latex formatting of two .prm entries.

source/simulator/core.cc
=> Make Advection-only consistent with other schemes

source/simulator/initial_conditions.cc
Fixes to #1141. This is dependent on Deal.II merging dealii/dealii#2858 for the conservative velocity field tests.
In order to use the initial condition interfaces as if they were given by dealii::Function objects, an additional class was added for each which does the necessary translation.
A possible farther improvement from the current state would be to modify the current adapter function to only require one call for interpolating the composition initial conditions.
=> Use VectorTools::interpolate with component mask for interpolation

include/aspect/simulator.h, source/simulator/assembly.cc, source/simulator/helper_functions.cc, source/simulator/melt.cc
This patch is aimed at addressing issue #755 . It's ready for review.
=> Introduce AdvectionField::scalar_extractor (fix issue 755)

source/simulator/parameters.cc
=> Add some more documentation.

include/aspect/geometry_model/box.h, include/aspect/geometry_model/chunk.h, include/aspect/geometry_model/ellipsoidal_chunk.h, include/aspect/geometry_model/interface.h, include/aspect/geometry_model/sphere.h, include/aspect/geometry_model/spherical_shell.h, include/aspect/geometry_model/two_merged_boxes.h, source/geometry_model/box.cc, source/geometry_model/chunk.cc, source/geometry_model/ellipsoidal_chunk.cc, source/geometry_model/interface.cc, source/geometry_model/sphere.cc, source/geometry_model/spherical_shell.cc, source/geometry_model/two_merged_boxes.cc, tests/plugin.cc
As suggested in #1044, a function that checks whether a given point falls within the boundaries specified in the input file. @jdannberg is this what you had in mind?
=> Add function to check whether a point is in the user-defined domain

source/postprocess/topography.cc
=> Add origin height to reference height

tests/CMakeLists.txt
=> create test output subdirectories if necessary

doc/modules/changes.h, source/postprocess/point_values.cc, tests/point_value_03.prm, tests/point_value_03/point_values.txt, tests/point_value_03/screen-output
This should fix #1170. I have not tried to run the testsuite on my poor laptop. Let us
see what Timo's tester reports.
=> Use mapping for point values.

source/particle/property/initial_composition.cc
This Assert should have been in there from the beginning, otherwise things go horribly wrong :smile:.
=> Add Assert

source/particle/property/interface.cc
=> Add check that correct number of properties are mapped onto late particles

doc/manual/cookbooks/composition-active-tracers/composition.part.prm, doc/manual/cookbooks/composition-active-tracers/tracers.part.prm, doc/manual/manual.tex
In particular, I'd like for @gassmoeller to take a look at whether I explained
the part about interpolating properties to fields correctly.
In reference to #1198.
=> Reword the tracer section in the manual somewhat.

source/geometry_model/ellipsoidal_chunk.cc
Fix representative point ellipsoidal chunk, and add a bit of documentation on the phi_theta_d variable. #1202
=> Fix representative point ellipsoidal chunk, and add documetation

include/aspect/simulator.h, source/simulator/helper_functions.cc
=> Make denormalize_pressure() const.

include/aspect/material_model/composition_reaction.h, include/aspect/material_model/drucker_prager.h, include/aspect/material_model/latent_heat.h, include/aspect/material_model/latent_heat_melt.h, include/aspect/material_model/melt_global.h, include/aspect/material_model/melt_simple.h, include/aspect/material_model/morency_doin.h, include/aspect/material_model/simple_compressible.h, include/aspect/material_model/steinberger.h, tests/burstedde.cc, tests/inclusion_2.cc, tests/prescribed_velocity_boundary.cc, tests/solcx.cc, tests/solkz.cc, tests/tangurnis.cc
I exclude simple.h since it is already fixed there by #375.
=> Fix a typo.

source/simulator/assembly.cc, source/simulator/melt.cc
While working on #1250, I noticed that for simple 3D geometries the calls to `component_to_system_index` in the advection assembly take up to 30% of the total advection assembly time. This is surprising, but it is because different from `system_to_component_index` - which just looks up a value in a vector - `component_to_system_index` performs an `std::find` and `std::distance` over the list of all elements in the finite element system, which is significantly slower.
The main change in this PR is the exchange of multiple calls to `component_to_system_index` (advection_dofs_per_cell times per quadrature point) to one call of `system_to_component_index` (dofs_per_cell times per quadrature point) in the loops that precompute the shape values and gradients. Although there are similarly many …
=> Speed up advection assembly

source/particle/world.cc
This PR utilizes the improvements of dealii/dealii#3289 to make particle transfer faster. The change itself is small, but it will require every user that uses deal.II 8.5.pre to update to a recent development version, not sure if we should wait for a while until merging this?
=> Speedup cell id transport

include/aspect/material_model/visco_plastic.h, source/material_model/visco_plastic.cc
Fix error in the grain-size exponent term for diffusion creep
=> Fix sign of grain size exponent term in visco_plastic material model

include/aspect/parameters.h
A leftover from the Hackathon 2015, I think.
=> Remove unused parameter

doc/manual/manual.tex
This section had become a bit outdated.
=> Update the 'Future plans' section.

include/aspect/heating_model/adiabatic_heating.h, include/aspect/heating_model/interface.h, source/heating_model/adiabatic_heating.cc, source/heating_model/interface.cc, source/simulator/simulator_access.cc
Another part of #1275 that can be merged separately.
=> Add find_heating_model function to Manager

include/aspect/assembly.h, source/simulator/assembly.cc
=> Cleanup unused variables

include/aspect/particle/particle.h, include/aspect/particle/property/interface.h, include/aspect/particle/property_pool.h, include/aspect/particle/world.h, source/particle/output/ascii.cc, source/particle/output/hdf5.cc, source/particle/particle.cc, source/particle/property/interface.cc, source/particle/property_pool.cc, source/particle/world.cc
This is a simplified version of #1301 that is just moving functionality around to prepare for the release. #1301 requires more benchmarking before it can be merged.
=> Basic property pool implementation

doc/manual/manual.tex
=> Appropriately list what should be refernced in the manual.

doc/manual/manual.tex
=> Describe particle output file structure.

doc/modules/changes.h, include/aspect/global.h, source/main.cc
=> Support --version.

source/particle/particle.cc
=> fix bug in particle assignment

doc/modules/changes.h, source/main.cc
That's about the level of intellectual work I'm capable at the end of a long day flying
from Europe back to the US.
Closes #1340.
=> Support --help.

include/aspect/utilities.h, source/postprocess/heat_flux_densities.cc, source/postprocess/heat_flux_statistics.cc, source/postprocess/mass_flux_statistics.cc, source/postprocess/velocity_boundary_statistics.cc, source/utilities.cc
=> factor out parenthesize_if_nonempty

include/aspect/utilities.h, source/heating_model/interface.cc, source/mesh_refinement/interface.cc, source/particle/property/interface.cc, source/particle/world.cc, source/postprocess/depth_average.cc, source/postprocess/interface.cc, source/postprocess/visualization.cc, source/postprocess/visualization/material_properties.cc, source/postprocess/visualization/melt.cc, source/simulator/parameters.cc, source/termination_criteria/interface.cc, source/utilities.cc, tests/ellipsoidal_chunk_coordinate_parallel.prm, tests/ellipsoidal_chunk_noncoordinate_parallel.prm
This should fix #1349. I made a test for one of the plugins to test the new function, I guess we do not need one for every plugin that does the check.
=> Add check for uniqueness of list parameters

tests/visualization_unique_list.prm, tests/visualization_unique_list/screen-output
Follow-up to #1352. I forgot to add the test I mentioned.
=> Add forgotten test

tests/visualization_unique_list/screen-output
Hopefully fixes #1353. To my defense: The test worked before I addressed the comments in #1352 :smile:. I guess this only shows (again) that no PR is so trivial that one can skip waiting for the tester.
=> Fix test output

source/gravity_model/function.cc, source/initial_conditions/function.cc
compiling without cxx11 failed for me
=> add missing include files

tests/visco_plastic.prm, tests/visco_plastic/screen-output, tests/visco_plastic_complex.prm, tests/visco_plastic_complex/screen-output, tests/visco_plastic_yield.prm, tests/visco_plastic_yield/screen-output, tests/visco_plastic_yield_strain_weakening.prm, tests/visco_plastic_yield_strain_weakening/screen-output
Pull request to simplify the visco_plastic material model test suite. The current test input files are unnecessarily complicated, as they were originally designed to also provide a template for continental extension.  The new test suite should be much easier to debug and modify in the future if necessary.
=> Update visco_plastic material model test suite

doc/manual/manual.tex
=> remove incorrect uses of the term Boussinesq Approximation in the manual

cookbooks/inner_core_convection/inner_core_assembly.cc
The conversion to only assembling Stokes DoFs was not done for this
example (but the copy in tests/ is correct).
=> Fix crash in inner core example

doc/manual/manual.tex
=> Describe what exactly we mean when we consider 2d models.

source/main.cc
This PR simplifies the command line argument parsing and allows generating an xml schema. This schema will (at some point) be used with the parameter GUI program to allow editing of .prm files.
=> print xml parameters and command line parsing rework

doc/manual/manual.tex, doc/release-tasklist
This should have happened before the release already, so also update the release
tasklist.
=> Update the current release in the manual.

doc/manual/manual.tex
now it is the same as https://aspect.dealii.org/publications.html
=> fix bib entry for the manual

include/aspect/heating_model/latent_heat.h, include/aspect/heating_model/shear_heating.h, source/heating_model/latent_heat.cc, source/heating_model/shear_heating.cc
No need to keep these around. Fixes #1415.
=> Remove empty subsections

source/simulator/parameters.cc
Prompted by a question on the mailing list.
=> Better document a couple of parameters.

doc/modules/changes/20170423_gassmoeller, include/aspect/initial_conditions/interface.h, include/aspect/simulator.h, include/aspect/simulator_access.h, source/boundary_temperature/initial_temperature.cc, source/initial_conditions/interface.cc, source/particle/property/pT_path.cc, source/simulator/core.cc, source/simulator/initial_conditions.cc, source/simulator/parameters.cc, source/simulator/simulator_access.cc, tests/initial_temperature_list.prm, tests/initial_temperature_list/screen-output, tests/initial_temperature_list/statistics
Very preliminary and not working. Do not bother to review. @jaustermann feel free to take a look and continue if you feel like it. I will talk to you before continuing working on it (at the earliest tomorrow).
=> List of initial conditions

source/postprocess/depth_average.cc, source/postprocess/visualization.cc, source/simulator/core.cc
Found while reading through #1436.
=> Minor text corrections.

include/aspect/boundary_fluid_pressure/density.h, include/aspect/boundary_fluid_pressure/interface.h
Accidentally introduced in one of #1452, #1451, or most likely #1449.
=> Fix BoundaryFluidPressuresssss

doc/manual/manual.tex
@egpuckett requested this, and he is entirely correct in this.
=> Add E. Gerry Puckett as an author on the manual.

source/initial_temperature/solidus.cc
Fixes typo of lithosphere in description comments of solidus.cc
=> typo in adiabatic.cc

include/aspect/simulator.h
This adds some much-needed documentation to the `denormalize_pressure()` function ( @MFraters might like this). Follow-up to #1495 and #1502.
Fixes #1229.
=> Add some documentation.

source/simulator/core.cc
=> Check that no other boundary conditions are set for periodic boundaries

include/aspect/utilities.h, source/utilities.cc
This adds the function to compute the spd factor for the newton solver, so it can be used at various places throughout the code.
=> add spd factor to utilities.

source/simulator/solver.cc
This also isn't done in the other places where we solve linear systems.
Supersedes #1534.
=> Don't limit the number of iterations.

source/geometry_model/ellipsoidal_chunk.cc
This incorporates suggestions from #1497.
=> Update documentation slightly.

benchmarks/hollow_sphere/CMakeLists.txt, benchmarks/hollow_sphere/hollow_sphere.cc, benchmarks/hollow_sphere/hollow_sphere.prm
I present here a new family of analytical flow solutions to the incompressible Stokes equation in a spherical shell. The velocity is tangential to both inner and outer boundaries, the viscosity is radial and of power-law type, and the solution has been designed so that the expressions for velocity, pressure, and body force are simple polynomials and therefore simple to implement in (geodynamics) codes.
=> analytical Stokes benchmark for 3D hollow sphere

include/aspect/newton.h, source/simulator/newton.cc
a follow up to #1410, addressing the comments there.
=> Newton merge 1

include/aspect/newton.h, source/simulator/newton.cc
This is a follow-up to #1499. @mfraters -- any opinions?
=> Several cleanups for the Newton implementation.

include/aspect/geometry_model/interface.h, source/geometry_model/interface.cc
@tjhei @bangerth @gassmoeller @mbweller
=> framework for the canonical/natural coordinates of geometry models

source/simulator/initial_conditions.cc
Sample output was posted in the issue #1565
=> Time Particle Interpolation

include/aspect/utilities.h, source/utilities.cc
Somehow with pull request #1514 the added function of #1508 got removed. I am still not entirely sure what happened, but this pull request should bring that function back.
=> Bring back the spd_function.

tests/visco_plastic_complex.prm, tests/visco_plastic_complex/screen-output, tests/visco_plastic_yield_strain_weakening.prm, tests/visco_plastic_yield_strain_weakening/screen-output
=> Update visco_plastic tests to account for finite strain invariant tracking within visco_plastic material model

benchmarks/annulus/annulus.cc, benchmarks/burstedde/burstedde.cc, benchmarks/hollow_sphere/hollow_sphere.cc, benchmarks/inclusion/inclusion.cc, benchmarks/solkz/solkz.h, benchmarks/tangurnis/code/tangurnis.cc, cookbooks/finite_strain/finite_strain.cc, source/mesh_refinement/velocity.cc, source/postprocess/dynamic_topography.cc, source/postprocess/geoid.cc, source/postprocess/mass_flux_statistics.cc, source/postprocess/velocity_boundary_statistics.cc, source/postprocess/visualization/dynamic_topography.cc, tests/burstedde.cc, tests/burstedde_stokes_rhs.cc, tests/inclusion_2.cc, tests/melt_compressible_advection.cc, tests/melt_force_vector.cc, tests/melt_material_4.cc, tests/melt_transport_adaptive.cc, tests/melt_transport_compressible.cc, tests/melt_transport_convergence_simple.cc, tests/melt_transport_convergence_test.cc, tests/prescribed_velocity_boundary.cc, tests/simple_shear.cc, tests/solcx.cc, tests/solkz.cc, tests/tangurnis.cc
=> use this->introspection().polynomial_degree.velocities  when refer to the degree of velocity polynomial basis

source/simulator/newton.cc
update the constructor arguments and instantiate the functions.
=> Fix newton.cc

doc/manual/manual.tex, source/simulator/parameters.cc
This pull request improves the formulation description of several places in the manual following the discussion with Rene. @gassmoeller
=> Improve the formulation description of several places in the manual

cookbooks/crustal_model_2D.prm
Added line: set Maximum number of expensive Stokes solver steps = 5000, to prevent the cookbook from crashing.
=> Fix crustal model 2d cookbook.

include/aspect/utilities.h
Documentation to enum following 
Document Utilities::Coordinates::CoordinateSystem #1631
=> enum documentation

source/simulator/solver.cc
This can be unified and some lines at the top and bottom of the code
blocks for the two solver types can be pulled out. This, however,
requires to write the code as
if (direct_solver)
...
else
...
instead of the current way of using
if (direct_solver)
{
...
return;
}
...
=> Recognize that the direct and iterative solvers have some common code.

source/particle/output/vtu.cc, source/particle/world.cc, source/postprocess/visualization.cc
This PR removes ifdef-ed code for deal.II 8.4.0, which we no longer support.
=> Remove deal.II 8.4.0 compatibility

tests/geoid.prm
Using Matt's new spherical coordinates input to set the single degree 2 order 0 spherical harmonic temperature field, making the test prm file more readable. @gassmoeller  @bangerth @mbweller
=> new test geoid prm file using Matt's spherical coordinates input

include/aspect/assembly.h, source/simulator/assembly.cc
To address issue #1640 
Added a new function extract_stokes_dof_indices for type 
internal::As…sembly::CopyData::StokesSystem
=> Added a new function extract_stokes_dof_indices 

include/aspect/assembly.h, source/simulator/assembly.cc
This is a follow-up to #1656 by @yinghe616. I'm just moving stuff around.
=> Simplify code a bit. Make a function argument more general.

doc/manual/parameters.tex, source/material_model/melt_global.cc
malting may not be what was intended in the melting section. Fixed
=> small typo fix in melt_global.cc and parameters.tex

source/initial_temperature/S40RTS_perturbation.cc, source/initial_temperature/SAVANI_perturbation.cc
typos in manual's SAVANI description.
=> Fix several typos in the manual 

benchmarks/inclusion/inclusion.h
=> Removed interface compatibility.

include/aspect/material_model/drucker_prager.h, source/material_model/drucker_prager.cc
In /material_model/drucker_prager
=> Remove ic drucker prager

source/main.cc
#1693 
Output:
```
$ ./aspect --version
-----------------------------------------------------------------------------
-- This is ASPECT, the Advanced Solver for Problems in Earth's ConvecTion.
--     . version 2.0.0-pre
--     . running in DEBUG mode
--     . running with 1 MPI process
--     . using Trilinos
-----------------------------------------------------------------------------
Version information of underlying libraries:
. deal.II:    8.5.0	   . git SHA1 short revision:    007eaa5
. Trilinos:   12.4.2
. p4est:      1.1.0
```
=> Clean deal.II git short rev output

include/aspect/parameters.h, source/simulator/assembly.cc, source/simulator/parameters.cc
I think I have put enough warnings in the description ;)
=> Make AMG parameters available.

tests/prescribed_velocity_boundary.cc, tests/tangurnis.cc
In /tests/tangurnis
and /tests/prescribed_velocity_boundary
=> Remove ic tests

benchmarks/hollow_sphere/hollow_sphere.cc
=> Remove interface compatibility hollow sphere

docker/jupyter/Dockerfile, docker/jupyter/Makefile, docker/jupyter/README.md, docker/jupyter/demo.ipynb, docker/jupyter/jupyter_notebook_config.py, docker/jupyter/mplimporthook.py, docker/jupyter/start-notebook.sh, docker/jupyter/start.sh
My push to dockerhub is still running, but you should be able to just do ``make test`` as soon as that is done without us having to merge this branch first.
=> Docker container for Jupyter notebooks

doc/modules/changes/20170516_1_mfraters, tests/simple_nonlinear.cc, tests/simple_nonlinear.prm, tests/simple_nonlinear/screen-output
=> Newton merge 3, part 1: Add newton simple nonlinear material

include/aspect/material_model/interface.h, source/material_model/interface.cc, source/postprocess/visualization/density.cc, source/postprocess/visualization/friction_heating.cc, source/postprocess/visualization/heat_flux_map.cc, source/postprocess/visualization/heating.cc, source/postprocess/visualization/material_properties.cc, source/postprocess/visualization/maximum_horizontal_compressive_stress.cc, source/postprocess/visualization/melt.cc, source/postprocess/visualization/named_additional_outputs.cc, source/postprocess/visualization/seismic_anomalies.cc, source/postprocess/visualization/shear_stress.cc, source/postprocess/visualization/spd_factor.cc, source/postprocess/visualization/specific_heat.cc, source/postprocess/visualization/stress.cc, source/postprocess/visualization/thermal_conductivity.cc, source/postprocess/visualization/thermal_diffusivity.cc, source/postprocess/visualization/thermal_expansivity.cc, source/postprocess/visualization/vertical_heat_flux.cc, source/postprocess/visualization/viscosity.cc
Factor out another big chunk of `MaterialModelInputs` initialization into a constructor.
=> Add DataPostprocessor flavor of MaterialModelInputs constructor.

source/material_model/drucker_prager.cc
This came up as an issue once before, and there was some confusion about it this week, so I added some extra comments to explain how we compute the effective strain rate.
=> Add clarification on strain rate invariant definition

tests/simple_nonlinear.cc, tests/simple_nonlinear/screen-output
=> Fix typos.

benchmarks/annulus/annulus.cc
Also qualify things with std:: as appropriate.
=> Ensure that arithmetic is done in floating point arithmetic.

doc/modules/changes/20170519_gassmoeller, include/aspect/initial_composition/porosity.h, source/initial_composition/porosity.cc, tests/adiabatic_conditions_composition_function/statistics, tests/initial_porosity.prm, tests/initial_porosity/screen-output, tests/initial_porosity/statistics
See changes entry. This is useful for melt models with pre-existing melt.
=> Add plugin and test

include/aspect/material_model/dynamic_friction.h, source/material_model/dynamic_friction.cc, tests/dynamic_friction.prm, tests/dynamic_friction/screen-output
Material model combining multicomponent , drucker prager and using strain rate dependent coefficient of friction.
=> Added dynamic friction material model.

include/aspect/material_model/interface.h, source/material_model/interface.cc
Addresses #1538.
Can not be merged before solkz ( #1700 ) branch is merged.
=> Remove class interface compatibility

doc/aspect-gui
This change to the aspect-gui script keeps the original filename around that was used to start the aspect-gui. Together with dealii/parameter_gui#16 this makes the workflow of opening a file and saving a modified version of it more convenient.
=> Update aspect-gui script

docker/jupyter/Dockerfile
=> add missing package to jupyter docker container

source/postprocess/geoid.cc
In trying to educate myself about #1760.
=> Minor doc update.

source/main.cc
=> Treat floating point exceptions (SIGFPE) like SIGABRT.

source/material_model/dynamic_friction.cc
Address issues #1773 and #1774. A limit for the minimum viscosity is also applied.
=> Fixes and minor updates to dynamic friction

doc/modules/changes/20170509_jperryhouts
As requested in the comments on #1527 
Sorry I didn't get to this earlier. I had been ignoring all my github emails during the hackathon. Just finally getting around to catching up.
=> Add changelog entry for nearest-neighbor particle interpolator

doc/manual/plugin_graph.dot, doc/update_parameters.sh
Also clean up the update_parameters.sh script slightly, which I am hijacking for
my purpose here. Related to #1787.
=> Create plugin graph automatically.

doc/manual/manual.tex
=> Use the plugin graph in the manual.

source/simulator/helper_functions.cc
See @tjhei's request in #1777. In reference to #1667.
=> Explicitly use neato layout for the plugin graph.

tests/write_plugin_graph.cc, tests/write_plugin_graph.prm, tests/write_plugin_graph/screen-output
This adds a test for #1777
Maybe this is not worth merging as is, because the output will break every time a new plugin is added, so we should add the feature to only output selected plugins first?
=> add write_plugin_graph test

include/aspect/simulator.h, source/simulator/assembly.cc, source/simulator/core.cc
This pull request reworks the assembly set_assemblers() for the Newton solver. It can probably be greatly improved upon to also support melt, and we need to look how to support all the different kinds of compressibilities.
=> [WIP] Newton merge 4: Picking up the pieces with set assembler

doc/manual/manual.tex
Something I noticed while working on #1844. The future plan was fulfilled probably 5 years ago, and I updated the list of maintainers in the same order as on the title page.
=> Update future plans and maintainers

CONTRIBUTING.md
=> Remove mailing list advice

doc/manual/manual.tex
I added and edited a couple of things while educating myself about the heating models that @jdannberg describes in #1854. The first commit is really just a couple of text updates. The second commits removes a paragraph -- see the commit message for the rationale.
=> Update heating model docs

doc/manual/manual.bib, doc/manual/manual.tex
I am updating homepage and deal.II website too...
=> update reference and how to cite

benchmarks/inclusion/compositional_fields/inclusion_compositional_fields.h
Update the compositional field based inclusion benchmark similarly to PR #1884.
=> Update material model of compositional field inclusion benchmark

ReadMe.html, index.html
This mirrors the changes I made in the svn repo.
=> [www] Update names and email addresses.

source/simulator/initial_conditions.cc
- cleanup melt variable handling
- only interpolate the pressure component
=> fix and cleanup compute_initial_pressure_field()

CONTRIBUTING.md, README.md, doc/manual/manual.tex
This PR updates all links to the website in our repository and the manual.
=> Update website information

doc/manual/citing_aspect.bib
This file is manually exported from the mendeley ASPECT group and
updated regularly. It is used to generate
https://aspect.geodynamics.org/publications.html
=> add citing_aspect.bib

include/aspect/utilities.h
Also make it clearer while there.
=> Fix grammar of a function's documentation.

doc/modules/changes/20170913_jdannberg, include/aspect/melt.h, source/simulator/assembly.cc, source/simulator/melt.cc, tests/melt_and_traction.prm, tests/melt_and_traction/screen-output, tests/melt_and_traction/statistics
This pull request allows models with melt migration to also use traction boundary conditions, which was not possible before.
=> make melt and boundary traction work together

doc/modules/changes/20170920_gassmoeller, include/aspect/particle/integrator/interface.h, include/aspect/particle/integrator/rk_2.h, include/aspect/particle/integrator/rk_4.h, include/aspect/particle/particle.h, include/aspect/particle/particle_accessor.h, include/aspect/particle/particle_handler.h, include/aspect/particle/property/interface.h, include/aspect/particle/world.h, include/aspect/simulator.h, source/particle/integrator/interface.cc, source/particle/integrator/rk_2.cc, source/particle/integrator/rk_4.cc, source/particle/interpolator/cell_average.cc, source/particle/particle.cc, source/particle/particle_accessor.cc, source/particle/particle_handler.cc, source/particle/property/interface.cc, source/particle/world.cc, source/postprocess/particles.cc
This is work in progress and related to #1897. I moved most of the generic particle functionality into the particle handler class, but there is still a bug inside the serialization / transfer / deserialization of particles. I would already appreciate a review, since most stuff should be in its final state, I just need to find the problem.
=> Improve particle handler

include/aspect/simulator.h, source/simulator/core.cc
=> Change shared pointer of melt in simulator_access to unique pointer.

source/simulator/core.cc
Fix for the Newton switch tolerance, which wasn't working properly before.
=> Fix for the Newton switch tolerance

doc/modules/changes/20171019_gassmoeller, include/aspect/postprocess/visualization.h, source/postprocess/visualization.cc, tests/graphical_output_hdf5/solution.xdmf
Follow up to #1958. Also adds a changelog entry to let people, who used the hdf5 output before, know.
=> Make filtering hdf5 output an input parameter

doc/modules/changes/20171021_hlokavarapu, include/aspect/particle/interpolator/harmonic_average.h, source/particle/interpolator/harmonic_average.cc, tests/particle_interpolator_harmonic_average_solkz.cc, tests/particle_interpolator_harmonic_average_solkz.prm, tests/particle_interpolator_harmonic_average_solkz/screen-output, tests/particle_interpolator_harmonic_average_solkz/statistics
I have implemented a harmonic averaging scheme and added a test case based on SolKz were I am interpolating both density and viscosity.  The code is ready for an initial review @gassmoeller .
=> Add harmonic average particle interpolation scheme

source/simulator/melt.cc
While working on #1976 I noticed that `MeltHandler<dim>::compute_melt_variables` took a significant amount of the compute time of the "Solve Stokes" timer section. In fact for `melt_transport_compressible_iterative` it takes about as much time as the Stokes solver itself, although it is simply a postprocessing step to compute the other variables out of the solution. When I looked into the function I found a number of things to optimize. The new version of the function reduces expensive calls to the fe_values object and the gravity model (the function object sometimes used inside is slow). The most intrusive change is that the `u_f` system is now only assembled and distributed for the `u_f` degrees of freedom instead of the whole system. We do this already for all the other equations, and …
=> Optimize compute melt variables

tests/viz_plugin_dependency.cc
with deal.II master, closes #1991
=> fix tests/viz_plugin_dependency

source/postprocess/stokes_residual.cc
This should resolve the remaining issues of #1989.
=> Fix cheap solver history

source/geometry_model/ellipsoidal_chunk.cc
=> remove compiler warning

include/aspect/compat.h
This will be useful in a follow up PR, and also in other places.
=> Implement make_unique

.zenodo.json
As discussed with @ljhwang . This will fill the author information in zenodo whenever we do a release.
=> add zenodo json file

include/aspect/simulator.h, source/simulator/core.cc
=> Update the description of the system preconditioner matrix.

CMakeLists.txt
=> Do not install .h.in files

benchmarks/buiter_et_al_2008_jgr/figure_6_1e20.prm, benchmarks/finite_strain/pure_shear.prm, benchmarks/finite_strain/simple_shear.prm, benchmarks/onset-of-convection/convection-box-base.prm, benchmarks/operator_splitting/advection_reaction/advection_reaction.base.prm, benchmarks/shear_bands/magmatic_shear_bands.prm, benchmarks/shear_bands/shear_bands.prm, benchmarks/solitary_wave/solitary_wave.prm, cookbooks/continental_extension.prm, cookbooks/finite_strain/finite_strain.prm, cookbooks/global_melt.prm, cookbooks/global_no_melt.prm, cookbooks/morency_doin_2004/morency_doin.prm, cookbooks/shell_3d_postprocess.prm, doc/manual/cookbooks/benchmarks/solitary_wave/solitary_wave.prm, doc/manual/cookbooks/global_melt/global_melt.prm, doc/manual/cookbooks/global_melt/global_no_melt.prm
This is the part of #2054 that is independent of the removal of the postprocessors. Since #2054 was already approved, I will just wait for the tester and then merge.
=> Update parameter files

source/simulator/assembly.cc, source/simulator/checkpoint_restart.cc, source/simulator/core.cc, source/simulator/free_surface.cc, source/simulator/initial_conditions.cc, source/simulator/solver.cc
=> Use scoped timers.

include/aspect/newton.h, include/aspect/utilities.h, source/simulator/assemblers/newton_stokes.cc, source/simulator/newton.cc, source/utilities.cc
This pull request makes the SPD safety factor available as an input parameter.
=> Make SPD safety factor available as a parameter.

include/aspect/newton.h, source/simulator/assemblers/newton_stokes.cc
Although in the output the correct stabilization appeared, it was not correctly applied. Somehow this bug slipped into #2006. This should fix it (I have tested it now, and am in the process of making tests for the stabilization).
=> fix | bug in newton solver stablization.

tests/visco_plastic_derivatives.cc
=> fix visco-plastic derivative

source/material_model/visco_plastic.cc
Addresses #2123. 
@sibiaoliu - Does this clarify the prefactor term? If more documentation is needed, let me know!
=> Update documentation of viscous prefactors in visco_plastic

benchmarks/spiegelman_et_al_2016_gcubed/CMakeLists.txt, benchmarks/spiegelman_et_al_2016_gcubed/spiegelman_material.cc
This is needed to implement some of the tests, and will serve as a start including the Spiegelman 2016 benchmark into ASPECT.
=> Add spiegelman material model to benchmark section.

source/simulator/assemblers/advection.cc, source/simulator/assembly.cc, tests/discontinuous_composition_serial_periodic_amr.prm, tests/discontinuous_composition_serial_periodic_amr/screen-output, tests/discontinuous_composition_serial_periodic_amr/statistics
Supersedes #1823 including all comments. I also included a test and an assert that prevents the parallel case (was not able to quickly find how to fix it).
=> Fix dg periodic amr

benchmarks/spiegelman_et_al_2016_gcubed/spiegelman_material.cc
This cleans up the new Spiegelman benchmark material.
=> Cleanup spiegelman benchmark.

doc/update_prm_files_to_2.0.0.sed
I broke this in #2054. The update script now works again.
=> Add forgotten subsection

tests/update_script.cc, tests/update_script.prm, tests/update_script/screen-output, tests/update_script/statistics
Adds the test requested in #2144.
=> Update script test

header.include, index.html
We have the CIG tutorial recorded and it's on youtube, but I think so far nobody found it...
=> add links to new tutorials and recorded tutorials

source/main.cc
Something I noticed during #2130. Currently, it is really hard to read through main() and figure out what is happening. It is well documented, but the function is just too long. This PR moves some code from main() into a helper function and refactors the rest to reduce complexity. This is now at a state in which I can read through main() without getting confused.
=> Refactor main()

include/aspect/geometry_model/chunk.h, include/aspect/geometry_model/ellipsoidal_chunk.h, source/geometry_model/chunk.cc, source/geometry_model/ellipsoidal_chunk.cc
Implemented clone() method in chunk and ellipsoidal_chunk geometries (they are now pure virtual in the parent class)
=> Implemented clone() method in chunk and ellipsoidal_chunk geometries

source/geometry_model/ellipsoidal_chunk.cc
Supposedly introduced in #1941.
=> Fix unused warning

benchmarks/solitary_wave/solitary_wave.cc, cookbooks/mid_ocean_ridge.prm
Some files have not been updated by the update script so far, and they keep getting in my way, while working on #2163 and #2157. Fix those files by updating them.
=> Run update script

source/material_model/simple.cc
The current formulas are just very long and prone to run past the end
of the screen. Break them in a more sensible and readable way.
=> Make some expressions simpler to read.

include/aspect/material_model/interface.h
It's not a worthy contribution to the current release, but I do try to keep
up with what's happening...
Follow-up to #2182.
=> Fix a grammar mistake.

include/aspect/boundary_traction/ascii_data.h, include/aspect/boundary_traction/function.h, include/aspect/lateral_averaging.h, include/aspect/postprocess/boundary_densities.h, include/aspect/postprocess/boundary_pressures.h, include/aspect/postprocess/visualization/geoid.h, include/aspect/postprocess/visualization/thermal_diffusivity.h, include/aspect/postprocess/visualization/vertical_heat_flux.h, source/initial_temperature/adiabatic_boundary.cc, source/particle/generator/ascii_file.cc, source/termination_criteria/end_step.cc
(I will run the copyright script next)
=> fix some inconsistent copyright formatting

CMakeLists.txt, cmake/write_config.cmake
this doesn't need to go into 2.0, but it also won't hurt, I believe.
=> add additional info to detailed.log

source/mesh_refinement/composition.cc, source/mesh_refinement/temperature.cc, source/mesh_refinement/velocity.cc
=> Better document the 'temperature' and 'velocity' refinement criteria.

doc/manual/manual.bib, doc/manual/manual.tex
=> update reference to zenodo

include/aspect/mesh_refinement/interface.h, include/aspect/simulator_access.h, source/simulator/simulator_access.cc
=> Add way to access mesh refinement strategies

Jenkinsfile
@naliboff email address was wrong, and so the tester did not automatically trigger. Fixed now.
=> Fix email address for tester

doc/manual/manual.bib
=> fix manual.bib formatting

cite.html
=> unify bibtex entries

doc/manual/manual.tex
=> fix \text issues, specify image extensions

doc/Makefile
=> fix glob for changes.h in Makefile

doc/manual/manual.tex
=> Break a long sentence to make it easier to read.

doc/manual/manual.tex
This is just a suggestion, I don't think we ever discussed what the main points are when writing a cookbook, but I just thought we should have some general guidelines we can point people to in case they want to contribute a cookbook (e.g. at the hackathon).
=> add some guidelines on how to write a cookbook

doc/manual/manual.tex
=> manual: switch bibstyle to shorten first names

doc/manual/manual.tex
see #2309
I want this for the 2.0.1 manual so we can deeplink to sections.
=> [2.0.1] cherry-pick #2309

include/aspect/simulator_access.h
In response to issue #2256 and in addition to Wolfgang's correction #2313
=> Fix grammar mistake in simulator_access.h

doc/manual/manual.tex
=> Added dealii FunctionParser link and function names, and if-statement example

include/aspect/global.h, include/aspect/simulator_signals.h, source/simulator/assembly.cc, source/simulator/core.cc, source/simulator/helper_functions.cc, source/simulator/initial_conditions.cc, source/simulator/nullspace.cc, source/simulator/solver.cc
=> Avoid a deprecation warning for ConstraintMatrix.

.gitattributes
- also remove zenodo/jenkins files
- include filter so people can build doxygen
=> releases: update ignored files

include/aspect/material_model/viscoelastic.h, source/material_model/viscoelastic.cc
=> Use interface volume fraction function in the visco elastic material model

doc/modules/changes/20180619_myhill, source/postprocess/depth_average.cc
- make doxygen compile again
- do not use "and"
- use an ifdef instead
=> improve gnuplot PR #2320

include/aspect/boundary_temperature/dynamic_core.h
=> Use correct sentences. Also don't repeat the information from the reference.

source/particle/world.cc, tests/particle_free_surface.prm, tests/particle_free_surface/screen-output
Picks #2358 into the 2.0.1 release branch.
=> Disable combining particle with free surface

source/material_model/grain_size.cc, source/material_model/interface.cc, source/material_model/visco_plastic.cc, source/material_model/viscoelastic.cc, source/particle/output/hdf5.cc, source/particle/property/composition.cc, source/particle/property/initial_composition.cc, source/particle/property/pT_path.cc, source/postprocess/geoid.cc, source/postprocess/rotation_statistics.cc, source/postprocess/visualization.cc, source/postprocess/visualization/adiabat.cc, source/postprocess/visualization/melt.cc, source/postprocess/visualization/shear_stress.cc, source/postprocess/visualization/stress.cc, source/simulator/introspection.cc, source/termination_criteria/interface.cc
=> c++11: use emplace_back

doc/release-tasklist
Added release notes for 2.0.1 with descriptions for all the fixed bugs.
=> Add release notes for 2.0.1

source/geometry_model/box.cc
=> avoid clang warning about array access

include/aspect/simulator/assemblers/interface.h, source/simulator/assemblers/interface.cc, source/simulator/assemblers/stokes.cc, source/simulator/assembly.cc
=> Added a function, reinit, in assembler/interface.h 

include/aspect/utilities.h, source/utilities.cc
Functionality to setup initial conditions, for example temperature based on distance to a ridge.
=> Add distance_to_line function and use it for distance_to_polygon

README.md
Added license badge to readme file.
=> Update readme file to add License badget

source/main.cc
That's because the dimension is the first thing we read from an input file. Specifically,
pay attention with Windows-style line endings. The rest is explained in the comments.
Fixes #2367. I did check all possible mistakes by hand, but I don't know how to add a test 
that uses Windows line endings and that I can add to the test suite -- nor how to reliably
catch the resulting error.
=> Be extra careful when parsing the dimension in an input file.

cookbooks/global_melt.prm, cookbooks/global_no_melt.prm, cookbooks/morency_doin_2004/morency_doin.prm, cookbooks/prescribed_velocity/circle.prm
all cookbook output should now go in "output-[cookbook name]"
=> Use consistent naming convention for cookbook output directories

source/main.cc
fixes #2406
```
/home/dealii/jenkins/workspace/aspect_master-E2LGBV7TXCDSE4TFSDUSL7EULM3J3UXVDF7HPXGMHNZ7M2DF7ICQ/source/main.cc:171:1: warning: control reaches end of non-void function [-Wreturn-type]
```
=> Fix compile warning

include/aspect/initial_temperature/S40RTS_perturbation.h, source/initial_temperature/S40RTS_perturbation.cc
Add function get_Vs to S40RTS_perturbation.cc to allow output of Vs data at all positions
=> Add function to output Vs data from S40RTS_perturbation.cc

doc/manual/manual.tex
=> manual: rename section

source/simulator/introspection.cc
=> Use common number of empty lines between functions.

benchmarks/solitary_wave/solitary_wave.cc, doc/modules/changes/20180623_niday, include/aspect/geometry_model/interface.h, include/aspect/utilities.h, source/boundary_composition/function.cc, source/boundary_temperature/function.cc, source/boundary_traction/function.cc, source/boundary_velocity/function.cc, source/geometry_model/interface.cc, source/initial_composition/function.cc, source/initial_temperature/function.cc, source/material_model/depth_dependent.cc, source/mesh_refinement/maximum_refinement_function.cc, source/mesh_refinement/minimum_refinement_function.cc, source/postprocess/heat_flux_densities.cc, source/postprocess/heat_flux_statistics.cc, source/postprocess/mass_flux_statistics.cc, source/postprocess/velocity_boundary_statistics.cc, source/postprocess/visualization.cc, source/utilities.cc
Addresses #1632.
Also fixes a typo in a comment in `utilities.h`.
=> Add convert_cartesian_to_other_coordinates function

include/aspect/geometry_model/ellipsoidal_chunk.h, source/geometry_model/ellipsoidal_chunk.cc
Moved set/clear_manifold_ids into .cc to address issue #2402.
=> Move the definition of the function into the header in ellipsoidal chunk.

doc/manual/parameters.tex
As far as I know, ASPECT won't run in four dimensions. Updated the manual accordingly.
=> ASPECT does not run in 4D (yet)

source/initial_temperature/ascii_profile.cc
=> Add include to make things compile again

include/aspect/boundary_composition/interface.h
=> Fix placement of DEAL_II_DEPRECATE tag.

benchmarks/buiter_et_al_2008_jgr/figure_6_1e20.prm
2279 Fixed indentation error noticed by Timo in Buiter benchmark.
=> 2279 indent prm

include/aspect/geometry_model/ellipsoidal_chunk.h
Also ensure that Sarah's first initial is properly abbreviated.
=> Relocate a comment.

source/simulator/assemblers/newton_stokes.cc
=> fix newton assembly performance 2

source/material_model/perplex_lookup.cc
=> avoid unused parameter warning

source/material_model/perplex_lookup.cc
=> check multithreading in PerpleXLookup MaterialModel

doc/manual/manual.tex
This addresses the remaining points in #2109. 
I only added a short paragraph on color scales, I think if we want to recommend specific color scales for specific output quantities, this has to be a longer discussion (and is probably a separate issue).
=> extend the section on cookbooks in the manual

doc/modules/changes/20180626_mfraters
Follow up to #2381, #2465 and #2470.
=> write change log entry for the Newton solver assembly performace improvements

doc/manual/manual.tex
Addresses #2504.
I don't know whether this is sufficient to be added as a contributor to the manual - I'm happy to take my name off if not!
=> added thermodynamic self-consistency section to the manual

doc/manual/manual.tex, source/material_model/diffusion_dislocation.cc
prompted by a comment in #2527
=> documentation: use \ast not *

doc/manual/manual.bib, doc/manual/manual.tex
Updates two references in manual:
- my paper on the hollow sphere benchmark is out.
- our paper on the annulus benchmark is submitted.
=> amend 2 references in manual

unit_tests/first.cc
This test confirms the suspicision about the fact that if() will
evaluate the then and the else branch, which can lead to floating point
exceptions. Check that the ternary operator works.
=> test: function parser and if()

Jenkinsfile.k8s
@tjesser-ucdavis-edu and I are working on a CIG jenkins server that uses kubernetes. Unfortunately, we have not yet found a way to write a Jenkinsfile that works for kubernetes and docker agents, so for now I copied the existing one and modified it slightly.
=> Add Jenkinsfile for kubernetes Jenkins

include/aspect/utilities.h, source/material_model/multicomponent.cc, source/utilities.cc, unit_tests/parse_map_to_double_array.cc
This was necessary due an overeager merge of #2405 by myself. Thanks to @jdannberg for helping with the changes.
=> Fixup style and messages for #2405

benchmarks/doneahuerta/doneahuerta.cc, doc/manual/manual.tex
This benchmark was added by @cedrict in #2481. I thought it was faster to make
these fixes myself, rather than ask him for another round of changes.
=> Minor updates to the Donea-Huerta benchmark.

doc/manual/manual.tex
This is an update to #2513 while reading through @bobmyhill's addition in an attempt at
learning some thermodynamics.
=> Minor updates to the thermodynamics section of the manual.

doc/manual/manual.tex
...for multicomponent material models.
=> doc: added small section on coefficient averaging

include/aspect/simulator.h, include/aspect/simulator_signals.h, source/geometry_model/box.cc, source/geometry_model/chunk.cc, source/geometry_model/ellipsoidal_chunk.cc, source/geometry_model/spherical_shell.cc, source/geometry_model/two_merged_boxes.cc, source/particle/particle_handler.cc, source/particle/world.cc, source/postprocess/global_statistics.cc, source/postprocess/stokes_residual.cc, source/postprocess/visualization.cc, source/simulator/assembly.cc, source/simulator/core.cc, source/simulator/initial_conditions.cc, source/simulator/melt.cc, source/simulator/solver_schemes.cc
=> replace boost bind by lambdas

source/postprocess/dynamic_topography.cc, source/postprocess/visualization/boundary_indicator.cc, source/postprocess/visualization/geoid.cc, source/postprocess/visualization/heat_flux_map.cc, source/postprocess/visualization/particle_count.cc, source/postprocess/visualization/seismic_anomalies.cc
I am pretty sure that this should work, but didn't want to put it into the
previous patches because it's probably useful to test this one
change separately.
=> Replace the use of a separate index by cell->active_cell_index().

index.html
Just some updates to link to the CIDER tutorial recording and slides on our webpage.
=> Updated CIDER tutorial entries

doc/manual/manual.bib
=> manual: add missing bib entry

CITATION, doc/make_cite_html.py, doc/manual/manual.bib, doc/modules/changes/20180725_tjhei, include/aspect/citation_info.h, source/citation_info.cc, source/global.cc, source/particle/world.cc, source/simulator/core.cc, source/simulator/free_surface.cc, source/simulator/melt.cc, unit_tests/common.h, unit_tests/first.cc
=> Dynamic Citation Thing

source/boundary_velocity/gplates.cc, source/utilities.cc
=> Allow negative scale factor for boundary velocity

citing.html
Layout and color choices on this page do not fit well into the rest of our pages. The commits here get us closer to making this page look (i) nice, (ii) consistent with the remaining pages we have.
This is a follow-up to #2597 and #2597 and #2594.
=> More citing.html cleanups

Jenkinsfile
This is just a suggestion, but I think the approach of using the 'ready to test' label to indicate pull requests that should be tested has worked quite well for the cig jenkins tester (it is essentially equivalent to our old /run-tests command, except it does not immediately trigger a build the first time it is added). I would like to add it to @tjhei's tester too, because this avoids having to manually restart that test run whenever a pull request is updated. Timo would you be fine with this?
=> Use label for jenkins tester

citing.html
Follow-up to #2622, #2597 and #2594.
=> One last cleanup for citing.html.

citing.html
=> www: move note to bottom, green box 100% width

include/aspect/material_model/visco_plastic.h, source/material_model/visco_plastic.cc
This is a response to the features that @mibillen and @naliboff want to add to the ViscoPlastic material model. Before we can make that model any more complicated we need to clean up some things, otherwise it will be impossible to keep track of its features.
Somewhere I broke a test during the refactoring, but I would like to see what the official tester says, and also give @naliboff and @mibillen a chance to comment, before I proceed.
=> Refactor visco plastic

doc/manual/manual.tex, source/postprocess/composition_statistics.cc
We already do this for most of the cases in the manual, but we missed a few in the
manual and one in a .cc file.
=> Mark up the 'dx' in integrals.

source/main.cc
I think the text is ok as is, but I've been looking at something else in this file
and thought I might as well explain this better. In the process, I've also made sure
that the message fits into an 80-character wide terminal.
=> Better explain what kinds of checks run with --validate.

citing.html, database.js
=> www: citing.html: fix escaping

citing.html
=> www: citing.html re-add lost line

doc/make_cite_html.py
- correctly escape umlauts and backslashes
- retain formatting for bibtex as used in manual.bib
used in #2663
=> update script for database.js for citing.html

index.html
=> Remove reference to mailing list from website

include/aspect/simulator.h
@param generates a parameter list
=> fix doxygen formatting

header.include, index.html
=> change mailing list link and contact section

doc/manual/manual.tex
=> Update manual with reference to forum

Jenkinsfile
This allows me to set the label inside jenkins and pair projects and
machines better.
=> Jenkins: remove label

source/simulator/entropy_viscosity.cc
I don't actually know whether this will work, but it seems like the right
thing to do. Let's see if I can get a Puckett Bucket for it :-)
=> Initialize unused vector elements with signaling_nans.

include/aspect/fe_variable_collection.h, source/fe_variable_collection.cc
The first commit only adjusts empty lines. The second one is the one
that's relevant.
=> Update a few pieces of documentation.

source/simulator/core.cc, source/simulator/introspection.cc
Part of using C++11 better, see #2375.
=> Use std::make_shared/unique instead of plain 'new'.

source/simulator/solver_schemes.cc
In relation to the discussion in #2715.
=> Leave a comment.

source/particle/particle_handler.cc, source/particle/property/function.cc, source/particle/world.cc, source/simulator/melt.cc
=> Prefer std::make_shared/unique over plain 'new'.

tests/anisotropic_viscosity.cc, tests/ascii_boundary_member.cc, tests/burstedde_stokes_rhs.cc, tests/latent_heat_enthalpy.cc, tests/melt_introspection.cc, tests/multiple_named_additional_outputs.cc, tests/prescribed_field.cc, tests/prescribed_field_with_diffusion.cc, tests/prescribed_velocity_boundary.cc, tests/signal_fem.cc
In reference to #2375. Also a follow-up to #2730.
=> Replace 'new' by 'make_shared' where possible.

doc/manual/manual.tex, doc/modules/changes/20190117_tjhei, source/main.cc, tests/original_prm.prm, tests/original_prm/original.prm, tests/original_prm/statistics
ASPECT now outputs a file named original.prm in the output directory with the exact content of the parameter it got started with.
=> Output original prm

CMakeLists.txt
- use EXIST instead of ls
- upper case cmake functions
=> world builder cmake cleanup

source/material_model/visco_plastic.cc
Prevents division by zero when viscosity_diffusion is computed.
=> Add assert when the variable temperature_for_viscosity becomes zero.

source/geometry_model/spherical_shell.cc
=> fix SphericalShell::point_is_in_domain

CMakeLists.txt
inspired from the mailing list (make -j 4 release) doesn't work
correctly.
=> Change make debug/release behavior

source/boundary_temperature/dynamic_core.cc
While there, also clean up around it.
=> Fix a memory leak.

include/aspect/mesh_refinement/interface.h, include/aspect/termination_criteria/interface.h, source/mesh_refinement/interface.cc, source/termination_criteria/interface.cc
=> Use std::unique_ptr in mesh ref and termination plugins.

include/aspect/utilities.h, source/utilities.cc
=> Use std::unique_ptr instead of std::shared_ptr in utilities.h/cc.

jabref-template/listrefs.begin.layout, jabref-template/listrefs.end.layout
This adds a javascript-generated bar plot on top of the publication list. Stolen from deal.II and adapted.
Preview:
=> www: publication plot

jabref-template/listrefs.begin.layout
- set smaller plot width
- leave link to instructions
=> www: publication list instructions

include/aspect/postprocess/gravity_point_values.h, source/postprocess/gravity_point_values.cc
- fix wrong type for number of points
- documentation fixes
=> gravity point postprocessor fixes

cmake/write_config.cmake, source/global.cc
- in detailed.log
- and some at runtime
=> print more MPI and deal.II info

source/simulator/core.cc
I think this logic is unnecessary as .reset() is safe to call in any
situation (we do not have any "on destruction" printing enabled).
I can into a problem with clang 6 with gcc's libstdc++ with version 5.4:
uncaught_exceptions() is not declared, but the version is reported as
c++17.
=> remove uncaught exceptions handling

benchmarks/check.sh, benchmarks/layeredflow/CMakeLists.txt, benchmarks/layeredflow/layeredflow.cc, benchmarks/newton_solver_benchmark_set/nonlinear_channel_flow/bash.sh, benchmarks/newton_solver_benchmark_set/nonlinear_channel_flow/bash_itIMPES.sh, benchmarks/newton_solver_benchmark_set/nonlinear_channel_flow/input_t.prm, benchmarks/newton_solver_benchmark_set/nonlinear_channel_flow/input_v.prm, benchmarks/tosi_et_al_2015_gcubed/Tosi_Case1.prm, benchmarks/tosi_et_al_2015_gcubed/Tosi_Case2.prm, benchmarks/tosi_et_al_2015_gcubed/Tosi_Case3.prm, benchmarks/tosi_et_al_2015_gcubed/Tosi_Case4.prm, benchmarks/tosi_et_al_2015_gcubed/Tosi_Case5.prm, benchmarks/tosi_et_al_2015_gcubed/tosi.cc, cookbooks/check.sh
I discovered various errors while running benchmarks. This is the first batch of fixes. It would be good if somebody could review things, as things are a bit suspicious (unused ``div_v`` for example).
=> benchmarks: various fixes

source/simulator/checkpoint_restart.cc
this function got renamed on deal.II master
=> Avoid deprecated prepare_serialization()

benchmarks/layeredflow/layeredflow.cc, benchmarks/shear_bands/shear_bands.cc, benchmarks/time_dependent_annulus/plugin/time_dependent_annulus.h, cmake/write_config.cmake, include/aspect/fe_variable_collection.h, include/aspect/material_model/utilities.h, include/aspect/material_model/visco_plastic.h, include/aspect/material_model/viscoelastic.h, include/aspect/postprocess/topography.h, include/aspect/postprocess/visualization/ISA_rotation_timescale.h, include/aspect/postprocess/visualization/grain_lag_angle.h, include/aspect/postprocess/visualization/temperature_anomaly.h, source/global.cc
- fix indentation in comments
- update copyright years
=> pre-release fixes

.clang-tidy
- enable other checks
- update instructions
see #2878 and #2879
=> update clang-tidy settings

include/aspect/postprocess/interface.h, source/postprocess/interface.cc
Obvious for the most part. What isn't has gotten a couple of lines more comments.
=> Replace std::shared_ptr by std::unique_ptr.

doc/manual/citing_aspect.bib
=> update bib file

doc/manual/manual.tex
The current text says 'common...frequently...frequently' in two successive
sentences.
=> Use smoother language.

doc/modules/to-2.1.0.h
see #2896. I don't see version 2.1.0 in the `doc/release-tasklist`.
=> Add GWB changelog entry.

doc/modules/to-2.1.0.h, doc/release-tasklist
This is a tentative release announcement. I filtered the changelog for changes important to users, and shortened some entries. Let me know if you think anything important is missing.
=> Add release announcement

source/simulator/core.cc, source/simulator/free_surface.cc
This PR is to check if #2779 makes a difference.
=> constraints: periodic before hanging

source/simulator/core.cc
extend on #2780 (and might detect situations where things break)
=> check constraints are consistent

doc/modules/changes/20190502_bangerth2, include/aspect/boundary_temperature/interface.h, source/boundary_temperature/interface.cc
=> Convert more shared_ptr -> unique_ptr.

source/postprocess/particles.cc
Follow up on #2924 removing some more not longer needed checks. Also related to #2803.
=> Remove some more ifdefs

doc/manual/manual.tex
Found while looking for something in the manual with @cedrict.
=> Fix a couple of typos in the manual.

doc/manual/manual.tex
Changes to keep all capitalization of ParaView consistent.
=> Use consistent ParaView capitalization.

doc/manual/manual.tex
In the inner core cookbook explanations: 
- clarifying the self-gravitation (that is not truly self-gravitation)
- added how to compile the shared library
=> Manual changes in inner core cookbook

doc/manual/manual.tex
Stylistic change to one sentence in user manual.
=> Style edit to user manual section 4.7.4

source/postprocess/heat_flux_map.cc
Removed a not longer necessary compatibility fix for deal.II 8.5.
=> Remove deal.II compatibility fix

doc/manual/manual.tex
I corrected earth to Earth in a few places (not everywhere) in the manual
=> Fix manual typo

source/simulator/solver.cc
Fixed old dealii version code in solver.cc
=> Removed a now unnecessary compatibility fix

doc/manual/manual.tex
Went through and proofread/edited text and table/figure captions for the part of the van Keken thermochemical composition benchmark contributed by @trajaona, @Shangxin-Liu and myself from several years ago.
=> Cleaned up text in manual

cookbooks/global_melt.prm
The value in the comment was not the same than the one used in the code.
=> corrections in cookbook global_melt

source/simulator/core.cc
Remove a not longer necessary compatibility fix for deal.ii 8.5.
=> Remove dealii compatibility fix

source/postprocess/stokes_residual.cc
remove a not longer necessary compatibility fix for deal.II 8.5
=> Remove deal.II compatiblity fix

doc/modules/changes/20190522_bangerth, include/aspect/initial_composition/interface.h, source/initial_composition/interface.cc
In reference to #2811 and #2375.
=> Change more std::shared_ptr to std::unique_ptr.

doc/manual/manual.tex
Added a note about reference models to the 'The input shear wave model' paragraph of the '3D convection with an Earth-like initial condition' section
=> Added a note to a section of the manual

source/simulator/lateral_averaging.cc
it was not working with older compiler.
=> do not use std::make_unique

source/boundary_composition/interface.cc, source/boundary_temperature/dynamic_core.cc, source/boundary_temperature/interface.cc, source/boundary_velocity/interface.cc, source/material_model/latent_heat_melt.cc, source/material_model/melt_global.cc, source/material_model/melt_simple.cc, source/mesh_refinement/particle_density.cc, source/mesh_refinement/volume_of_fluid_interface.cc, source/simulator/solver_schemes.cc
void return statements at the end of a function are not necessary.
=> remove unnecessary "return;"

doc/manual/manual.tex
Changed "change of entropy" to "change in entropy" in manual.
=> Manual typo

include/aspect/boundary_composition/interface.h, include/aspect/gravity_model/ascii_data.h, include/aspect/initial_temperature/interface.h, include/aspect/particle/property/interface.h, include/aspect/postprocess/interface.h, include/aspect/postprocess/visualization.h, source/boundary_composition/interface.cc, source/heating_model/adiabatic_heating_of_melt.cc, source/heating_model/shear_heating_with_melt.cc, source/initial_temperature/interface.cc, source/material_model/ascii_reference_profile.cc, source/material_model/composition_reaction.cc, source/material_model/depth_dependent.cc, source/material_model/grain_size.cc, source/material_model/melt_global.cc, source/material_model/melt_simple.cc, source/material_model/steinberger.cc, source/material_model/visco_plastic.cc, source/material_model/viscoelastic.cc, source/particle/property/interface.cc, source/postprocess/visualization.cc, source/postprocess/visualization/seismic_anomalies.cc, source/postprocess/visualization/spd_factor.cc, source/simulator/assemblers/stokes.cc, source/simulator/lateral_averaging.cc, source/simulator/melt.cc, source/simulator/newton.cc, source/volume_of_fluid/handler.cc, unit_tests/additional_outputs.cc
With regards to #2811 and #2375.
I'm sure this is going to fail a bunch of tests, but the tester will reveal which and how many.
=> Convert the majority of the remaining std::shared_ptr to std::unique_ptr

source/utilities.cc
Important things I'm addressing here!
=> Use the Oxford comma :-)

source/simulator/entropy_viscosity.cc
While there, also break some long lines in comments. Follow-up to #2858.
=> Fix the spelling of 'Dirichlet'.

source/simulator/entropy_viscosity.cc
Break some long lines, annotate non-local break/continue statements.
Follow-up to #2858.
=> Minor cleanups.

CMakeLists.txt
=> Clean up a piece of cmake scripts.

source/geometry_model/ellipsoidal_chunk.cc
This PR adds some comments to the ellipsoidal chunk, and rewords some of the error messages.
=> added more doc/comments to ellipsoidal chunk

include/aspect/geometry_model/spherical_shell.h, source/geometry_model/spherical_shell.cc
=> Remove reference to deal.II version 9.0.0.

doc/manual/manual.bib, doc/manual/manual.tex
While there, also reference the Newton paper.
=> Add a note to the benchmark section of the manual.

source/material_model/rheology/constant_viscosity.cc
Sort of urgent: Things don't compile without this for me :-)
=> Add missing include files.

benchmarks/annulus/annulus.cc, benchmarks/burstedde/burstedde.cc, benchmarks/doneahuerta/doneahuerta.cc, benchmarks/hollow_sphere/hollow_sphere.cc, benchmarks/inclusion/inclusion.h, benchmarks/layeredflow/layeredflow.cc, benchmarks/operator_splitting/advection_reaction/advection_reaction.cc, benchmarks/operator_splitting/exponential_decay/exponential_decay.cc, benchmarks/solcx/solcx.h, tests/burstedde_stokes_rhs.cc, tests/prescribed_velocity_boundary.cc, tests/q1_q1.cc
In reference to #2811 and #2375.
Follow-up to #3010.
=> Replace using std::shared_ptr in tests and benchmarks.

include/aspect/simulator.h, source/simulator/core.cc, source/simulator/simulator_access.cc
In #2972, @tjhei asked for a variable to be renamed but then merged without waiting for this to happen. This PR does the renaming.
=> Rename a variable.

benchmarks/check.sh, benchmarks/hollow_sphere/hollow_sphere.cc, benchmarks/inclusion/inclusion.h, tests/spectral_comparison.prm
- fix a few warnings and errors in the benchmark folder
- make geoid-spectral-comparison run in a reasonable time
=> /benchmark/ fixes

doc/manual/manual.tex
=> Use the \degree symbol for degrees in the manual.

Jenkinsfile, Jenkinsfile.cig
- replace tab with spaces
- reindent
This is a little bit more ugly, but at least automatic (in vs code by
formatting as javascript)
=> re-indent Jenkinsfile

source/simulator/helper_functions.cc
=> cleanup: introduce a new variable

include/aspect/postprocess/visualization.h, source/postprocess/visualization.cc
The patch looks complicated, but really does just three things: 
* It groups a bunch of member variables of the viz postprocessor class into a structure
* It makes a couple of member functions work on the members of this structure (obtained via a reference argument) instead of the former member variables of the surrounding class
* Create a member variable of this structure.
I do this because it will, in the next step, allow me to create a second one of these member variables of struct type so that I can deal with both cell and face output.
=> Further refactor the viz postprocessor.

doc/parameter_view/parameters.css
show a + in front of expandable things and a - if it is expanded.
=> Parameter view: + / -

source/geometry_model/box.cc, source/geometry_model/two_merged_boxes.cc
This is a follow-up to #2669, using the technique of #2972.
@MFraters -- you might be interested in this.
=> Use a clearer way to check whether everything has been initialized.

benchmarks/check.sh, cookbooks/check.sh
also cookbooks/check.sh while I am here...
=> benchmarks/check.sh: skip original.prm

doc/parameter_view/parameters.js, doc/parameter_view/parameters.xsl
add a text box that filters parameters when pressing return inside it.
=> parameter view: implement filtering

README.md
part of #3065, which need to be discussed first.
=> [www] remove references to mendeley [WIP]

include/aspect/material_model/drucker_prager.h, source/material_model/drucker_prager.cc
This is based on #3036 (and I will rebase after that is merged). 
The pull request uses the new equation of state in the Drucker-Prager material model.
=> equation of state in drucker prager

benchmarks/check.sh, cookbooks/check.sh
=> Better document a shell function.

doc/manual/manual.tex
Clarify the instructions on how to configure a plugin (after helping a
user today).
=> manual: improve cmake plugin help

doc/manual/manual.tex
Last pull request for a long day.
=> Fix a typo in the manual.

doc/manual/manual.tex
=> Use a systematic way to print large or small numbers via latex.

doc/manual/manual.tex
=> Avoid using scientific notation for numbers in the manual.

source/material_model/visco_plastic.cc
found the problem in and needed this for #3102.
=> fix visco plastic get timestep number problem.

doc/modules/changes/20190530_jeanniot
Just adding a change log for the custom spherical shell.
=> add change log for custom spherical shell

include/aspect/geometry_model/sphere.h, source/geometry_model/sphere.cc
=> Remove deal.II version check from sphere geometry model

doc/modules/changes/20190524_bremner, doc/modules/changes/20190531_bremner
Added changelog files for the pull-requests made during the hackathon.
=> additions to the changelog

doc/manual/manual.tex
=> manual: fix two mistakes

source/simulator/solver.cc, source/simulator/stokes_matrix_free.cc
This is a correction for https://github.com/geodynamics/aspect/pull/2987. The previous way to get the initial solution and tolerance for the GMRES solve was 1) incorrect for time dependent and 2) ugly. I cleaned it up a bit.
=> Correction for initial guess/tol in GMRES solve

doc/modules/changes/20190530_jeanniot
@bangerth Dear Wolfgang, that was very clumsy from me to not list out your name in this new feature (#3097), which could have not been possible without you! Also thank you for your time for explaining to Marie and I some core subtleties and intricacies of ASPECT and dealii.  
My apologies for this oversight :)
=> add Wolfgang to the list of authors in the custom spherical shell changes log

include/aspect/postprocess/visualization/strain_rate_tensor.h, source/material_model/interface.cc, source/postprocess/heat_flux_map.cc, source/postprocess/visualization/ISA_rotation_timescale.cc, source/postprocess/visualization/grain_lag_angle.cc, source/postprocess/visualization/strain_rate_tensor.cc, source/simulator/newton.cc
=> Remove compatibility code

Jenkinsfile, Jenkinsfile.cig
- make files more similar
- lead sh section with a comment (displayed while running)
=> [CI]: unify and comment files

doc/manual/manual.bib, source/simulator/newton.cc, source/simulator/parameters.cc, source/volume_of_fluid/handler.cc
* [ X] I have followed the instructions for indenting my code according to ASPECT's code style as described in the last paragraph of the ['Making ASPECT better'](../CONTRIBUTING.md#making-aspect-better) section of CONTRIBUTING.md.
=> Fix spaces, reference and spelling

benchmarks/tosi_et_al_2015_gcubed/tosi.cc
Although I can't reproduce the error reported in  #3076 on my Macbook, this should fix it. Viscosity was being computed even though strain rate was set to size zero in the calling AdiabaticConditions to flag that viscosity wasn't needed. @tjhei could you test it on your machine?
=> Fix Tosi Case 4 benchmark

include/aspect/volume_of_fluid/assembly.h, source/volume_of_fluid/assembler.cc
Really minor stuff.
Related to #835.
=> Minor cleanups while looking at something VoF related.

source/simulator/assembly.cc
Just the simplification of some logic I saw when reviewing something else. Not sure if I disentangled this correctly, but the tester will tell.
=> Simplify some logic

doc/manual/manual.bib
We're not referencing this paper at the moment, but we will be at one point in the future and I had just copy-pasted the bibtex entry.
@egpuckett -- FYI
=> Add the VoF paper to the list of references in the manual.

source/mesh_refinement/volume_of_fluid_interface.cc
this confused me when looking at #3174
=> extend a comment

source/particle/interpolator/bilinear_least_squares.cc
I changed the name of variable position to particle_position so that it would not be confused with positions. I did this change to the suggestion of @egpuckett after we both had to double check that a variable called position was not part of positions.
[X] I have read the guidelines in our [CONTRIBUTING.md](../CONTRIBUTING.md) document.
[X] I have followed the [instructions for indenting my code](../CONTRIBUTING.md#making-aspect-better).
[X] I have tested my new feature locally to ensure it is correct.
=> Clarifying variable name in Bilinear Least Squares

doc/manual/citing_aspect.bib
=> Add a thesis using ASPECT.

header.include, index.html
I couldn't test this, because the header doesn't show up in my browser, so let me know if you think any of this won't work.
=> add some information on the 2.1 release that was missing on the website

doc/modules/changes/20190912_naliboff, include/aspect/material_model/rheology/strain_dependent.h, include/aspect/material_model/visco_plastic.h, source/material_model/rheology/strain_dependent.cc, source/material_model/visco_plastic.cc
This PR moves code related to tracking of finite strain and strain softening behavior from the `ViscoPlastic` material model to a new model `StrainDependent` in the `Rheology` class. By and large, very little code had to be modified during the transfer. Looking through the existing code I see lots of room for improvement, but I think that should be done in follow-up pull requests.
All the relevant tests pass on my local machine with the current changes, but we'll see what the tester says.
=> Add a strain dependent rheology model

Jenkinsfile.cig, contrib/ci/Dockerfile
I though it would be useful to test how well the tests actually cover the code. This is a work in progress.
=> add coverage testing.

doc/modules/changes/20190919_glerum, include/aspect/material_model/rheology/diffusion_creep.h, include/aspect/material_model/rheology/dislocation_creep.h, include/aspect/material_model/visco_plastic.h, source/material_model/rheology/diffusion_creep.cc, source/material_model/rheology/dislocation_creep.cc, source/material_model/visco_plastic.cc
This PR creates two new Rheology models for viscous creep and just entails moving code related to diffusion and dislocation to the respective Rheology models. For now it just removes code from visco_plastic. 
Question: I've made diffusion and dislocation creep a separate Rheology model, because I figured it would be easiest to for example refactor `diffusion_dislocation.cc` as well. However, one Rheology model called e.g. `viscous_creep` that includes the compositing of diffusion and dislocation also makes sense to me. What are your preferences @naliboff , @jdannberg ?
=> Factor out diffusion and dislocation creep

doc/manual/manual.tex
I can't believe we didn't find this earlier...
=> remove reference to Texas A&M from the manual

citing.html, database.js
add entry from #3243 to citing database. We should merge that one first...
=> www: add matrix-free

doc/modules/changes/20191005_clevenger, include/aspect/stokes_matrix_free.h, source/simulator/solver_schemes.cc, source/simulator/stokes_matrix_free.cc, tests/shell_2d_gmg.prm.dealii_9.2, tests/shell_2d_gmg/screen-output
- this is currently only written for 2d
- 3d requires some copy&paste and testing and will be a separate PR
- requires a development version of deal.II
=> GMG: implement no normal flux for 2d spherical and shells

source/simulator/checkpoint_restart.cc
=> fix checkpoint/resume for deal.II >=9.1

doc/manual/citing_aspect.bib
Since we are all adding recent publications, here are a few more :smile:
=> Add ASPECT publications

include/aspect/material_model/interface.h
=> more c++ override

doc/manual/citing_aspect.bib
Fixes #3296, Fixes #3295.
Thanks @ljhwang for the references!
=> Add new publications

doc/manual/parameters.tex, doc/parameter_view/parameters.xml, include/aspect/material_model/rheology/drucker_prager.h
- document a parameter
- update parameters.tex
=> Maintenance Dec 2019

doc/manual/citing_aspect.bib, include/aspect/initial_composition/world_builder.h, include/aspect/initial_temperature/world_builder.h, source/initial_composition/world_builder.cc, source/initial_temperature/world_builder.cc, source/simulator/newton.cc
The citing info was missing my phd thesis and my papers which cite aspect, so I added them. I also added a CitationInfo for the Newton solver and world builder. @tjhei Did I do this correctly?
=> Add newton and gwb citations

doc/manual/citing_aspect.bib, include/aspect/material_model/visco_plastic.h, source/material_model/visco_plastic.cc, source/postprocess/visualization/named_additional_outputs.cc
- added reference
- removed unused parameter
- moved AssertThrow to before looping over checked parameter
=> Add ref, remove unused parameter

source/simulator/stokes_matrix_free.cc
=> fix deprecation warning with deal.II master

source/simulator/stokes_matrix_free.cc
=> account timing for matrix-free build Stokes preconditioner

source/simulator/solver_schemes.cc
Follow-up to #3323 for the Stokes solution. There is just one new line the rest is indentation change.
=> Report interpolate Stokes solution timing

source/simulator/solver_schemes.cc
part of #3322, now down to 12% unaccounted.
=> report prescribed advection field timer

benchmarks/inclusion/inclusion.h, source/postprocess/global_statistics.cc
These should not break anything except output, but it doesn't hurt to fix this.
=> small 64bit fixes

.github/PULL_REQUEST_TEMPLATE.md
=> fix URLs in PR template

include/aspect/simulator.h, source/simulator/solver_schemes.cc
This is one of the first step towards the goal set in #3102. It puts the most of the newton solver scheme code in a seperate function.
=> Refactor newton solver scheme.

CMakeLists.txt
based on discussion in #3338 as we are currently not able to compile and
not testing this configuration.
=> disable PETSc for now

doc/modules/changes/20200124_tjhei
changelog entry for #3347.
Also see #3338
=> add petsc removal changelog entry

include/aspect/postprocess/visualization/spherical_velocity_components.h, source/postprocess/visualization/spherical_velocity_components.cc
This feature was missing so we implemented it. 
* [X ] I have read the guidelines in our [CONTRIBUTING.md](../CONTRIBUTING.md) document.
* [ X] I have followed the [instructions for indenting my code](../CONTRIBUTING.md#making-aspect-better).
* [X ] I have tested my new feature locally to ensure it is correct.
* [ NA] I have [created a testcase](http://www.math.clemson.edu/~heister/manual.pdf#sec%3Awriting_tests) for the new feature/benchmark in the [tests/](../tests/) directory.
=> new postprocessor to compute spherical components of velocity field

citing.html
We will need to manually modify this url, otherwise the browser uses an
old cached version.
=> www: update database.js tag to force loading new file

doc/manual/citing_aspect.bib
=> Fix bib entry category

include/aspect/simulator/assemblers/interface.h, source/mesh_refinement/volume_of_fluid_interface.cc, source/particle/world.cc, source/simulator/assemblers/advection.cc, source/simulator/assemblers/interface.cc, source/simulator/core.cc, source/simulator/entropy_viscosity.cc, source/volume_of_fluid/assembler.cc, source/volume_of_fluid/reconstruct.cc
This PR fixes a bunch of deprecation warnings with deal.II master and gcc 9.2.1.
I tested that everything runs with the most recent deal.II and the tester will take care of 9.1.1.
=> Fix deprecation warnings

doc/modules/changes/20200225_tjhei, source/postprocess/visualization.cc
=> fix hdf5 output after restart

source/simulator/helper_functions.cc
First step towards addressing the issue mentioned yesterday on the forum by @maxrudolph . This just simplifies the logic a bit and will allow me, in the next step, access more member variables of the main class in the place where we actually do the writing.
=> Simplify the logic of do_output_statistics.

include/aspect/particle/property/interface.h, source/particle/property/interface.cc, unit_tests/particles.cc
=> Add particle plugin existence and order checks

source/particle/interpolator/bilinear_least_squares.cc
=> Fix up a comment that is awkwardly worded.

doc/modules/changes/20200226_bangerth, include/aspect/simulator.h, source/simulator/checkpoint_restart.cc, source/simulator/core.cc, source/simulator/helper_functions.cc
Following yesterday's discussion on the forum regarding the problem @maxrudolph saw.
/rebuild
=> Only update the statistics file if possible, rather than writing it anew.

source/simulator/core.cc
=> enumerate all switch cases

contrib/opendap/OPeNDAP.md, source/utilities.cc
=> libdap related cleanup

source/global.cc
see https://github.com/dealii/dealii/pull/9688
=> avoid deal.II deprecation of n_array_elements

source/simulator/stokes_matrix_free.cc
This change was recently merged in deal.II (dealii/dealii#9688).
=> Fix deprecation warning

include/aspect/material_model/interface.h, include/aspect/parameters.h, source/material_model/interface.cc, source/simulator/assemblers/newton_stokes.cc, source/simulator/assemblers/stokes.cc, source/simulator/assembly.cc, source/simulator/core.cc, source/simulator/helper_functions.cc, source/simulator/parameters.cc, tests/prescribed_dilation.cc, tests/prescribed_dilation.prm, tests/prescribed_dilation/screen-output, tests/prescribed_dilation_newton.cc, tests/prescribed_dilation_newton.prm, tests/prescribed_dilation_newton/screen-output
This PR supersedes #3119. Written with help from @naliboff and @cedrict.
This implements a new material model additional output to add a "forced plastic dilation" (basically prescribing a compressibility R with div u = R).
=> Prescribed plastic dilation

include/aspect/fe_variable_collection.h, include/aspect/simulator/assemblers/interface.h, include/aspect/volume_of_fluid/assembly.h, source/fe_variable_collection.cc, source/simulator/assemblers/interface.cc, source/utilities.cc
fix various issues reported by clang 10.
=> clang 10 fixes

source/simulator/nullspace.cc, source/simulator/solver.cc, source/volume_of_fluid/solver.cc
to make ASPECT compile with deal.II master again.
=> remove deprecated deal.II pointer_matrix include

source/main.cc, source/particle/generator/probability_density_function.cc, source/particle/generator/quadrature_points.cc, source/particle/generator/reference_cell.cc, source/particle/world.cc, source/postprocess/dynamic_topography.cc, source/postprocess/geoid.cc, source/postprocess/heat_flux_map.cc, source/postprocess/particles.cc, source/postprocess/topography.cc, source/postprocess/visualization.cc, source/simulator/checkpoint_restart.cc, source/simulator/helper_functions.cc, source/utilities.cc
relatively boring PR adding a check for the return values of MPI commands.
=> check MPI return values

source/mesh_deformation/interface.cc, source/simulator/stokes_matrix_free.cc
This seems to be a recent deal.II change for the development version
=> add missing deal.II header

doc/parameter_view/parameters.js, doc/parameter_view/parameters.xsl
- scroll first filtered item into view when searching
- allow "&s=" url to enable sharing links with filter applied
- add a "link" url that updates with search output
- reformat .js file
=> Parameter view: search url

citing.html
Companion PR to #3474. Are these the only changes necessary for the www branch?
=> Add website checkbox for projected density approximation

benchmarks/compressibility_formulations/README.md, doc/make_cite_html.py, doc/manual/citing_aspect.bib, doc/manual/manual.bib, source/simulator/assembly.cc
Adding a reference to our recently published paper in GJI. Did I understand correctly what I have to do to add it to the list of citable papers? Follow-up PR for the www branch to come in a minute.
=> Add citation for latest paper

citing.html, database.js
=> www: update js database

source/boundary_velocity/gplates.cc, tests/burnman_seismic_test/screen-output, tests/burnman_test/screen-output, tests/depth_dependent_initialize_base_model/screen-output, tests/gplates_1_3/screen-output, tests/gplates_1_4/screen-output, tests/gplates_3d/screen-output, tests/gplates_rotation/screen-output, tests/latent_heat_viscosity/screen-output
Related to Felipe's problem on the mailing list.
/rebuild
=> Make error message clearer.

include/aspect/material_model/interface.h, source/material_model/interface.cc, tests/sol_kz_2_project_q1_only_visc.cc, tests/sol_kz_2_project_q1_only_visc.prm, tests/sol_kz_2_project_q1_only_visc/screen-output, tests/sol_kz_2_project_q1_only_visc/statistics
Discussed in https://github.com/geodynamics/aspect/pull/3495. Simply adds "project to Q1 only viscosity" averaging scheme. I added a test which uses solkz.
=> add project to Q1 only viscosity averaging

unit_tests/utilities.cc
=> add unittest for Utilities::AsciiDataLookup

include/aspect/initial_temperature/adiabatic_boundary.h
=> Fix compiler warning

source/heating_model/adiabatic_heating_of_melt.cc
=> fixing a small typo in documentation

doc/manual/manual.tex, include/aspect/utilities.h
- missing bib reference
- missing parameter documentation
=> fix two small doc issues

doc/manual/parameters.tex, doc/parameter_view/parameters.xml
=> maintenance June 2020

source/postprocess/point_values.cc
The point values postprocessor wrote the same file from all MPI ranks
potentially overwriting the results. Fix this.
part of #3521
=> point values postprocessor only on rank 0

cookbooks/free-surface-with-crust/free-surface-with-crust.prm, doc/manual/cookbooks/free_surface/doc/freesurface.part.prm, doc/manual/manual.tex
- add missing "Mesh deformation" subsection
- fix .part.prm in the manual
- fix description in manual for free-surface.prm
=> fix free-surface-with-crust

include/aspect/postprocess/visualization/geoid.h
=> fix geoid warning

benchmarks/buiter_et_al_2008_jgr/figure_6_1e20.prm, benchmarks/buiter_et_al_2016_jsg/exp_1.prm, benchmarks/buiter_et_al_2016_jsg/exp_2_high_resolution.prm, benchmarks/crameri_et_al/case_1/crameri_benchmark_1.cc, benchmarks/solitary_wave/solitary_wave.cc, benchmarks/tosi_et_al_2015_gcubed/tosi.cc, benchmarks/yamauchi_takei_2016_anelasticity/anelasticity_temperature.cc, cookbooks/prescribed_velocity/prescribed_velocity.cc
fix various warnings and errors in cookbooks and benchmarks
=> fix benchmarks and cookbooks problems

source/postprocess/gravity_point_values.cc
=> gravity_point_values: only write on rank 0

source/simulator/helper_functions.cc, source/simulator/solver_schemes.cc, tests/nonlinear_channel_flow_tractions_Newton_Stokes_no_line_search.cc, tests/nonlinear_channel_flow_tractions_Newton_Stokes_no_line_search.prm, tests/nonlinear_channel_flow_tractions_Newton_Stokes_no_line_search/screen-output, tests/nonlinear_channel_flow_velocities_Newton_Stokes_no_derivative.prm, tests/nonlinear_channel_flow_velocities_Newton_Stokes_no_line_search.cc, tests/nonlinear_channel_flow_velocities_Newton_Stokes_no_line_search.prm, tests/nonlinear_channel_flow_velocities_Newton_Stokes_no_line_search/screen-output
This pull request is to see if the Newton/defect correction solver can be optimized in some ways.  Although there was a discussion in #3112, with my recent tests (with deal.ii master) it already seems faster when doing the same test, but I think there still is room for improvment. This is a work in progress.
=> add more tests for reference and start optimizing.

doc/manual/citing_aspect.bib
Add citation for Naliboff et al., 2020.
=> Add citation

doc/make_cite_html.py, doc/manual/manual.bib, source/postprocess/geoid.cc, source/postprocess/visualization/geoid.cc
- add bib entry
- rename key to "geoid" from "Geoid"
see #3527
=> support geoid dynamic citation

citing.html, database.js
=> www: support geoid dynamic citation

benchmarks/check.mk
Ensures #3535 is fixed by #3183.
=> Add Spiegelman newton solver benchmark check

citing.html, database.js
=> www: enable Newton and WorldBuilder

benchmarks/viscosity_grooves/CMakeLists.txt, benchmarks/viscosity_grooves/viscosity_grooves.cc
re added two missing files that mysteriously disappeared off the original PR.
=> adding the two missing files of the viscosity_grooves benchmark

doc/release-tasklist
This is a draft. Suggestions welcome.
=> add 2.2 announcement

benchmarks/check.mk, benchmarks/viscosity_grooves/CMakeLists.txt, benchmarks/viscosity_grooves/viscosity_grooves.cc
- use double numbers
- update copyright years
- use compute_global_error
- enable in automatic check
followup to #3568
=> update viscosity_grooves benchmark

index.html
=> www: tabs2spaces

doc/make_cite_html.py, doc/manual/manual.bib
- update zenodo/figshare links in bib file
- update citing.html database with new entries
=> update citing.html and bib entries

citing.html, database.js
=> www: update database

doc/modules/changes/20200701_haoyuanli, include/aspect/material_model/equation_of_state/interface.h, include/aspect/material_model/utilities.h, source/material_model/equation_of_state/interface.cc, source/material_model/utilities.cc, source/material_model/visco_plastic.cc
This is the second step of implementing phase transitions to the material model. I added a phase_average_value function to utilities.cc calculate parameters of compositions from the parameters of phases using the gamma function. On top of that, I changed the implementation of function phase_average_equation_of_state_outputs in interfaces.cc.
As @gassmoeller has addressed before, we should not call this phase_average_value function if there is no phase on a composition. That's what I have taken care of in this PR. Although I haven't included the viscosity part of it, which I intend to deal with in …
=> phase transition: average phase value

CMakeLists.txt
=> disable world builder in cmake UNITY_BUILD

contrib/utilities/indent
=> fix indent script

include/aspect/particle/property/interface.h
=> Fix the name of a replacement function.

Jenkinsfile, Jenkinsfile.cig
- increase build time to 45min
- make CIG and Timo's tester do the same stuff
=> CI: Jenkinsfile make the same

contrib/utilities/indent
not very important, but useful when run in a CI environment
=> indent script: return failure

doc/manual/manual.tex
=> manual: update installation instructions to deal.II 9.2

include/aspect/particle/property/integrated_strain.h
Addresses the warning reported in #3633.
/rebuild
=> Address a warning.

.github/workflows/linux.yml
I realized that we should error out when we find warnings.
=> github actions: enable -Werror

include/aspect/particle/property/composition.h, include/aspect/particle/property/integrated_strain_invariant.h, include/aspect/particle/property/melt_particle.h, include/aspect/particle/property/pT_path.h, include/aspect/particle/property/position.h, include/aspect/particle/property/velocity.h, include/aspect/particle/property/viscoplastic_strain_invariants.h
=> add missing override for particle properties

include/aspect/material_model/interface.h, source/material_model/interface.cc, source/simulator/assembly.cc
=> Remove deprecated MaterialModelInputs::cell

source/material_model/interface.cc
=> remove stray preprocessor command

source/geometry_model/chunk.cc
This appeared as a link error in #3646 in the test natural_coordinates_conversion
=> add missing instantiation

source/geometry_model/spherical_shell.cc, source/simulator/checkpoint_restart.cc
A pull request created during git tutorial. Removes an outdated compatibility fix.
=> removed a now unnecessary compatibility fix for DEAL-II version

Jenkinsfile
=> Jenkins: run testers with -O1

source/boundary_velocity/gplates.cc
This pull request aims to address the issue  #3599 .
=> Added documentation for points in 3D case.

source/postprocess/memory_statistics.cc
Removed unnecessary compatibility fix - this was mostly a test for Kiran and Antoniette to figure out the git extension in VS code
=> Removed a now unnecessary compatibility fix (KA)

doc/manual/manual.bib
Pointed out by @ljhwang in #3695.
Fixes #3695.
=> Remove a couple of completely unrelated publications.

source/simulator/assemblers/newton_stokes.cc
splitting up pull request #3701 part 1. This just simplifies the logic of how the extra terms in the rhs are assembled.
=> Simplify newton stokes rhs additional terms logic.

source/simulator/stokes_matrix_free.cc
- fix typo
- remove useless prm code
- remove collect_sizes() that is done automatically.
=> some small matrix free cleanup

doc/modules/changes/20200806_haoyuanli, include/aspect/material_model/rheology/diffusion_creep.h, include/aspect/material_model/rheology/dislocation_creep.h, include/aspect/material_model/visco_plastic.h, source/material_model/rheology/diffusion_creep.cc, source/material_model/rheology/dislocation_creep.cc, source/material_model/visco_plastic.cc, tests/visco_plastic_phases_viscosity.prm, tests/visco_plastic_phases_viscosity/screen-output, tests/visco_plastic_phases_viscosity/statistics
Hi Rene,
@gassmoeller 
I have finished most of this pull request, to calculate viscosity on phases. I have changed the parse function and the compute_viscosity function in the two 'creep.cc' file. And I also changed the interface in the 'calculate_isostrain_viscosities' function in order to have 'phase_function_values' as an entry. I have added a new test, 'visco_plastic_phases_viscosity', where I used this new pull request.
I have also fixed the related part in ViscoPlasticStrainInvariant<dim>::update_particle_property with the interface there. However, in order to do that, I have to define three …
=> Calculate viscosity on phases

contrib/opendap/prm_files/aspect_url_test.prm, source/utilities.cc
=> Fixed the url link and the LIBDAP environment variable
