geodynamics/aspect

- source/geometry_model/spherical_shell.cc
- source/gravity_model/radial.cc
- source/heating_model/radioactive_decay.cc
- source/initial_temperature/continental_geotherm.cc
- source/material_model/diffusion_dislocation.cc
- source/material_model/drucker_prager.cc
- source/material_model/dynamic_friction.cc
- source/material_model/equation_of_state/multicomponent_compressible.cc
- source/material_model/equation_of_state/multicomponent_incompressible.cc
- source/material_model/multicomponent.cc
- source/material_model/multicomponent_compressible.cc
- source/material_model/rheology/constant_viscosity_prefactors.cc
- source/material_model/rheology/diffusion_creep.cc
- source/material_model/rheology/dislocation_creep.cc
- source/material_model/rheology/drucker_prager.cc
- source/material_model/rheology/strain_dependent.cc
- source/material_model/steinberger.cc
- source/material_model/visco_plastic.cc
- source/material_model/viscoelastic.cc
- source/simulator/parameters.cc
Found while looking at #3682. Might make for a nice PR for someone new to reviewing to actually look at!
> Fix formatting of a few doc strings.

- source/postprocess/visualization.cc
Periods are important parts of sentences too!
> Fix grammar of error messages.

- contrib/world_builder/source/features/interface.cc
- contrib/world_builder/source/features/mantle_layer.cc
- contrib/world_builder/source/features/mantle_layer_models/grains/uniform.cc
> fix error in world builder for unity build

- doc/modules/changes/20200804_gassmoeller
- include/aspect/simulator_signals.h
- source/simulator/solver_schemes.cc
- tests/nonlinear_solver_history.cc
- tests/nonlinear_solver_history.prm
- tests/nonlinear_solver_history/screen-output
- tests/nonlinear_solver_history/statistics
This is mostly here for testing purposes and for showing this to @jdannberg and @tjhei for the time stepping discussion. I will update the PR for the other solver schemes and see if any tests change (they should not).
> Add post nonlinear solver signal

- source/postprocess/geoid.cc
Seen while reviewing #3776. There are more things to improve in there, but I do not want to create conflicts with 3776.
> Refactor some code in Geoid postprocessor

- source/simulator/solver_schemes.cc
- tests/prescribed_dilation_newton/screen-output
splitting up pull request #3701 part 2. This prevents rebuilding matrices when not needed.
> Optimize the newton solver scheme rebuild flags.

- include/aspect/time_stepping/conduction_time_step.h
- include/aspect/time_stepping/convection_time_step.h
- include/aspect/time_stepping/interface.h
- source/time_stepping/conduction_time_step.cc
- source/time_stepping/convection_time_step.cc
- source/time_stepping/interface.cc
- introduce plugin architecture for time stepping
- move convection/conduction into their own plugins
Part 2 of N for #3549
> TimeStepping: introduce plugins

- source/boundary_traction/initial_lithostatic_pressure.cc
Just expanding some documentation :)
> Extend documentation BT initial lithostatic pressure on coordinates.

- source/boundary_traction/initial_lithostatic_pressure.cc
I was too quick with merging #3786 and only realized that I had missed a missing whitespace once I had hit the merge button. Fixed hereby -- @MFraters, FYI.
> Fix a whitespace problem.

- include/aspect/particle/interpolator/bilinear_least_squares.h
- source/particle/interpolator/bilinear_least_squares.cc
> Update class documentation.

- source/initial_temperature/lithosphere_mask.cc
> typo in lithosphere_mask description

- CONTRIBUTING.md
> Minor updates to CONTRIBUTING.md.

- AUTHORS
@anne-glerum @naliboff @MFraters -- any of you want to do the honors?
> Update the AUTHORS file.

- doc/manual/manual.tex
Corrected a couple of typos in the manual.
> corrected manual typos

- source/boundary_temperature/constant.cc
- source/boundary_temperature/two_merged_boxes.cc
- source/boundary_velocity/interface.cc
- source/geometry_model/interface.cc
- source/initial_temperature/interface.cc
- source/mesh_deformation/free_surface.cc
- source/mesh_deformation/function.cc
- source/mesh_deformation/interface.cc
- source/mesh_refinement/interface.cc
- source/particle/generator/reference_cell.cc
- source/particle/interpolator/cell_average.cc
- source/particle/interpolator/harmonic_average.cc
- source/particle/property/interface.cc
- source/particle/world.cc
- source/postprocess/depth_average.cc
- source/postprocess/heat_flux_statistics.cc
- source/postprocess/interface.cc
- source/postprocess/mass_flux_statistics.cc
- source/postprocess/particles.cc
- source/postprocess/point_values.cc
- source/postprocess/velocity_boundary_statistics.cc
- source/postprocess/visualization.cc
- source/simulator/core.cc
- source/simulator/helper_functions.cc
- source/simulator/parameters.cc
- source/termination_criteria/interface.cc
- source/volume_of_fluid/handler.cc
Addresses a number of those places that could benefit from #3774 . Required some wicked perl magic + more manual labor than I wanted this to be :-)
I've put thought into whether to capture the variables by-value or by-reference. I've generally chosen references if it's not a scalar, but by value if it's an integer of some type.
> Use range-based for loops in a variety of places.

- include/aspect/adiabatic_conditions/compute_profile.h
- include/aspect/boundary_temperature/dynamic_core.h
- include/aspect/geometry_model/ellipsoidal_chunk.h
- include/aspect/geometry_model/initial_topography_model/interface.h
- include/aspect/geometry_model/two_merged_boxes.h
- include/aspect/material_model/grain_size.h
- include/aspect/material_model/interface.h
- include/aspect/material_model/rheology/diffusion_creep.h
- include/aspect/material_model/rheology/dislocation_creep.h
- include/aspect/material_model/utilities.h
- include/aspect/material_model/visco_plastic.h
- include/aspect/material_model/viscoelastic.h
- include/aspect/particle/generator/interface.h
- include/aspect/particle/interpolator/bilinear_least_squares.h
- include/aspect/postprocess/gravity_point_values.h
- include/aspect/postprocess/load_balance_statistics.h
- include/aspect/postprocess/particles.h
- include/aspect/postprocess/visualization/temperature_anomaly.h
- include/aspect/stokes_matrix_free.h
- include/aspect/time_stepping/interface.h
- include/aspect/volume_of_fluid/handler.h
- source/material_model/rheology/elasticity.cc
- source/particle/generator/probability_density_function.cc
- source/particle/property/elastic_stress.cc
- source/postprocess/visualization/temperature_anomaly.cc
- source/simulator/assemblers/newton_stokes.cc
The last of my typo commits for this year. 
This PR fixes typos in the deepest level of cc files in source, and also in the header files in include/aspect.
> fixed typos in deep source and header files

- doc/manual/manual.tex
This required playing with some spacing on the front page, but I think the latex code easier to read this way as well.
@MFraters @naliboff @anne-glerum I've used the email addressed I usually use for you in the manual. If you want something different, please speak up!
> List Menno, Anne, John as maintainers in the manual.

- CMakeLists.txt
Really no big deal, but might as well try to be uniform.
> Make cmake command UPPERCASE.

- source/particle/interpolator/bilinear_least_squares.cc
I changed the bilinear least squares particle interpolator so that it doesn't solve the normal equations as referenced in #3390 by @egpuckett but instead uses deal.ii's QR decomposition as suggested. Also removed the comment about bilinear only working in 2D, as it has now been implemented in 3D, since #3224.
> Qr bilinear interpolation

- cookbooks/van-keken-vof/doc/main.part.prm
- cookbooks/van-keken-vof/doc/variation.part.prm
- cookbooks/van-keken-vof/van-keken-vof.prm
- source/volume_of_fluid/handler.cc
- tests/vof_circle_1.prm
- tests/vof_circle_amr.prm
- tests/vof_circle_mpi.prm
- tests/vof_circle_mpi_amr.prm
- tests/vof_composition_init.prm
- tests/vof_linear.prm
- tests/vof_linear_2f.prm
- tests/vof_linear_amr.prm
- tests/vof_linear_amr_mpi.prm
- tests/vof_linear_periodic.prm
- tests/vof_linear_periodic_amr.prm
- tests/vof_mpi_amr_no_dof.prm
This PR corrects a volume of fluid parameter typo:
Volume of fluid intialization type -> Volume of fluid initialization type
> corrected vof parameter typo

- doc/manual/manual.tex
Mentioned in https://github.com/geodynamics/aspect/pull/3798#discussion_r479693148
> Fix a couple of funny uses of \si.

- source/postprocess/velocity_boundary_statistics.cc
Fixed grammar in the comment, which was found in the review of another PR #3851.
> Modified documentation for a typo.

- doc/Makefile
> aspect.tag: use https url

- doc/manual/manual.bib
bibtex complains on my computer
> manual: fix bib entry

- include/aspect/postprocess/boundary_velocity_residual_statistics.h
- source/postprocess/boundary_velocity_residual_statistics.cc
I saw a few places in #3851 that could be improved.
> minor code cleanup in boundary velocity residual

- source/simulator/core.cc
While there, also improve spacing of an asterisk.
Follow-up to #3855.
> Improve placement of parentheses.

- benchmarks/nsinker/nsinker.cc
> Add to the documentation of a function.

- benchmarks/diffusion_of_hill/analytical_topography.cc
- source/mesh_deformation/diffusion.cc
- source/mesh_deformation/interface.cc
Follow up to #3407 with a few cosmetic improvements.
> Minor improvements to surface diffusion

- Jenkinsfile
- Jenkinsfile.cig
Given the list of high quality PRs by @bobmyhill this should have happened a while ago :-). Just making his (and our) life a bit easier by letting the CI run automatically on his PRs.
> Update trusted CI users

- index.html
> www: scale big logo to 100% width

- doc/manual/citing_aspect.bib
Adds a recent ASPECT publication to the website publication list.
> adding Assanelli et al to publications

- include/aspect/time_stepping/function.h
- include/aspect/time_stepping/repeat_on_cutback.h
> remove virtual when using override

- include/aspect/material_model/steinberger.h
- source/material_model/steinberger.cc
A small change which I suggested during the review of pull request #3895.
> rename Steinberger material model variable.

- AUTHORS.md
- README.md
This PR updates the developer and maintainer lists in the README file. Are their other similar lists that should be updated?
Also, can someone with the right website permissions (@gassmoeller, @tjhei?) provide @bobmyhill the correct settings for merging PRs, running tester, etc?
> Update README maintainer and developer lists

- doc/manual/manual.tex
Following up on a conversation we had this morning on the ASPECT call. How do people feel about some text of this kind?
> Discuss choices of approximate models better in the manual.

- source/particle/world.cc
Since dealii/dealii#10858 was merged we should now be using the deal.II functionality to copy particle handlers. All the functionality that was written in this function (including ghost particle exchange) happens inside deal.II now. I checked that all tests still run with the most recent deal.II.
> Use deal.II particle copy

- benchmarks/davies_et_al/case-2.3-plugin/VoT.cc
- benchmarks/newton_solver_benchmark_set/spiegelman_et_al_2016/drucker_prager_compositions.cc
- benchmarks/nonlinear_channel_flow/simple_nonlinear.cc
- cookbooks/free_surface_with_crust/plugin/simpler_with_crust.cc
- cookbooks/morency_doin_2004/morency_doin.cc
- source/material_model/equation_of_state/linearized_incompressible.cc
> Spell out double constants in ParameterHandler

- source/mesh_deformation/interface.cc
I am not sure if this code is tested right now and if it works
correctly, but writing into invalid memory can't be good.
> fix incorrect initial surface topography

- source/utilities.cc
Quick pull request to change how data is handled (and checked) from the requested url
> Urlreader fix

- source/simulator/nullspace.cc
In preparation for a new nullspace removal option (remove only surface net rotation), this PR refactors the existing function `remove_net_angular_momentum`. 
No changes in tests should happen.
> Refactor nullspace removal

- include/aspect/mesh_deformation/interface.h
- source/mesh_deformation/interface.cc
- source/simulator/core.cc
- tests/free_surface_timestep_repeat.prm
- tests/free_surface_timestep_repeat/screen-output
- tests/free_surface_timestep_repeat/statistics
We forgot to undo mesh deformation when we repeat a timestep. Fix that.
> implement timestep repeating with mesh deformation

- doc/modules/changes/20201105_bobmyhill
- doc/modules/changes/20201119_naliboff
Repeat #3917 for PRs that were in progress at the time.
> Remove superfluous <li> in changelog

- tests/CMakeLists.txt
document timeout based on @bangerth 's comment in  https://github.com/geodynamics/aspect/pull/3944#issuecomment-759497805
related to #3605
> document timeout in test system

- source/structured_data.cc
This doesn't currently compile for me without the `#include` statement.
/rebuild
> Add missing #include file.

- doc/manual/cookbooks/overview/doc/gmg-average.part.prm
- doc/manual/cookbooks/overview/doc/gmg-enable.part.prm
- doc/manual/manual.bib
- doc/manual/manual.tex
as discussed during the Q&A today.
> manual: add GMG section

- source/boundary_velocity/function.cc
- source/simulator/parameters.cc
> Better describe the years vs seconds issue.

- source/postprocess/volume_of_fluid_statistics.cc
Specifically, avoid a loop over an array of one element :-) I suspect that that is copy-pasted from elsewhere.
/rebuild
> Small clean-ups in the VoF postprocessor.

- source/simulator/assembly.cc
- tests/particle_periodic_boundaries_dc.prm
- tests/particle_periodic_boundaries_dc/screen-output
- tests/particle_periodic_boundaries_dc/statistics
> allow discontinuous particle interpolation for periodic BC

- doc/manual/citing_aspect.bib
First publication of 2021!
Adds Craig Withers master's thesis to the publication list.
> Add Withers thesis to publications

- doc/manual/manual.tex
Trying to address one user's feedback in the developer workshop survey.
> Better explain where to find information about parameters.

- README.md
as discussed during the call today.
> add link to future plans

- doc/manual/citing_aspect.bib
Add two publication to the citations list: Barrionuevo et al. 2021 and Bredow and Steinberger 2021.
> Adding 2 publications Barrioneuvo and Bredow

- doc/manual/citing_aspect.bib
This hopefully adds these publications cleanly this time. 
Previous commit was closed due to the number of errors introduced in the process of responding to the eagle eye comments. Here is your (or my) second chance.
> Adding 4 publications properly this time

- include/aspect/material_model/visco_plastic.h
- source/material_model/rheology/drucker_prager.cc
- source/material_model/visco_plastic.cc
Just reading through code today...
/rebuild
> Style changes.

- source/mesh_deformation/diffusion.cc
- source/mesh_deformation/free_surface.cc
> Avoid the use of a couple of functions that were just deprecated in deal.II

- source/main.cc
hopefully fixes #4017 for @maxrudolph
> add missing header file

- doc/manual/manual.tex
> Improvements to the van Keken benchmark section of the manual.

- doc/manual/citing_aspect.bib
Updates Heckenbach et al. 2021 such that citation is now complete.
Adds one new citation, Faccenna et al. 2021
> Add one new citation, Faccenna, and update Heckenbach

- source/particle/property/viscoplastic_strain_invariants.cc
> Adjust some code to our usual style.

- README.md
> add dependency info to readme

- include/aspect/particle/interpolator/bilinear_least_squares.h
- source/particle/interpolator/bilinear_least_squares.cc
- tests/particle_interpolator_bilinear_3d_add_particles.prm
- tests/particle_interpolator_bilinear_3d_add_particles/screen-output
- tests/particle_interpolator_bilinear_3d_add_particles/statistics
@kchotalia: @jdannberg told me you had still problems with the bilinear least squares interpolator running out of particles to interpolate from. Please give this branch a try, it should make your problem nearly impossible to trigger. If this works this is a solution that I we should apply to other particle interpolators as well. I will update this PR if this works.
> Add a fallback interpolator to bilinear least squares

- source/simulator/checkpoint_restart.cc
- source/simulator/core.cc
> Avoid a deprecated version of MappingQCache::initialize().

- include/aspect/postprocess/particles.h
- include/aspect/postprocess/visualization.h
- include/aspect/simulator.h
- source/postprocess/particles.cc
- source/postprocess/visualization.cc
- source/simulator/core.cc
- source/simulator/helper_functions.cc
Use std::thread instead since the deal.II class is deprecated.
/rebuild
> Avoid the use of Threads::Thread.

- source/material_model/compositing.cc
Following up on a conversation I had with @paddyball today.
/rebuild
> Add an explanatory sentence to the 'compositing' material model.

- source/material_model/melt_global.cc
Fix to make aspect compile with deal.II dev
> Update FEFieldFunction templates

- source/material_model/interface.cc
> Add a missing assertion.

- cookbooks/bunge_et_al_mantle_convection/bunge_et_al.prm
- cookbooks/bunge_et_al_mantle_convection/visc_depth_a.txt
- cookbooks/bunge_et_al_mantle_convection/visc_depth_b.txt
- cookbooks/bunge_et_al_mantle_convection/visc_depth_c.txt
- cookbooks/bunge_et_al_mantle_convection/visc_depth_d.txt
fix:
1. missing slash (Ascii data file                                                                                       </home/heister/aspect-git/cookbooks/bunge_et_al_mantle_convectionvisc_depth_a.txt>
not found!
2. add POINTS header to viscosity files, reported as
Could not successfully read in the file header of the ascii data file
3. add column information to parse column names / count correctly
> fix bunge cookbook

- source/simulator/nullspace.cc
> Improve a comment.

- source/material_model/interface.cc
Just a write-up of what a function does.
> Better document what the projection actually does.

- source/postprocess/particles.cc
No functional changes, just pulling stuff into or out of blocks. Probably easiest to read with `?w=1`.
/rebuild
> Small logic cleanups.

- include/aspect/structured_data.h
- source/structured_data.cc
If we're unsure about #4086, let me at least get the underlying cleanups out of the way. No functional changes here, just reorganization of code, individually packaged into three commits.
/rebuild
> Cherry pick the cleanups in #4086

- include/aspect/structured_data.h
- source/structured_data.cc
- tests/rheology_scaled_profile.cc
This was the conclusion of #4051. These functions are not used in ASPECT itself, but in some (external?) plugins. I renamed it in the one test that used it.
/rebuild
> Rename a couple of functions.

- source/particle/property/interface.cc
- source/simulator/initial_conditions.cc
This fixes an issue with weird MPI error messages we saw in our group, and should also fix #4028. Catching the exception and showing it's error message is sufficient to illustrate the real problem instead of the fake errors that result from MPI calls in destructors of objects further up in the callstack. I necessary we could also additionally call MPI_Abort, but at least for my problems this worked nicely already. @sac-bsa: Could you give this branch a try and see if your errors in #4028 look better now?
> Catch exceptions to show message before abort

- source/particle/interpolator/cell_average.cc
- source/particle/interpolator/harmonic_average.cc
- source/particle/interpolator/nearest_neighbor.cc
Clarify the behavior of property interpolators when the given cell is empty.
> Update the comments on the empty cells functionality for particle interpolators

- source/main.cc
- source/simulator/assembly.cc
This removes and old PETSC option.
> Remove a PETSC option

- source/mesh_deformation/interface.cc
> Removed a deprecated option (5x)

- source/mesh_deformation/free_surface.cc
* [ x] I have read the guidelines in our [CONTRIBUTING.md](../blob/master/CONTRIBUTING.md) document.
* [x ] I have followed the [instructions for indenting my code](../blob/master/CONTRIBUTING.md#making-aspect-better).
> removed PETSC option

- cookbooks/crustal_deformation/crustal_model_2D.prm
> [2.3] take over #4119

- source/simulator/helper_functions.cc
> [2.3] take over  #4118 

- source/simulator/core.cc
This removes an old PETSC option
> Remove unused PETSC option

- doc/manual/citing_aspect.bib
Cedric and I contributed the ASPECT benchmark results in this thesis. The subduction cookbook I've written is based on that benchmark.
> Add reference Quinquis thesis

- source/simulator/stokes_matrix_free.cc
`gather_evaluate()`  is equivalent to calling `read_dof_values()` followed by `evaluate()`, but might internally use some additional optimizations.
`integrate_scatter()` is equivalent to calling `integrate()` followed by `distribute_local_to_global()`, but might internally use some additional optimizations. 
passed all the tests with gmg. @tjhei
> Update some matrix-free functions

- source/simulator/melt.cc
This removes an old PETSC option.
> Removed a PETSC option

- include/aspect/termination_criteria/steady_rms_velocity.h
- include/aspect/termination_criteria/steady_temperature.h
- source/termination_criteria/steady_temperature.cc
- unit_tests/termination_criteria.cc
There is no need to have this function declared in the .h file and exported from the object file.
/rebuild
> Make a function purely internal to a .cc file.

- source/utilities.cc
This is what's left over from #4085.
/rebuild
> Add a missing space.

- source/simulator/nullspace.cc
> removed a deprecated option in source/simulator/nullspace.cc

- include/aspect/mesh_deformation/interface.h
- include/aspect/postprocess/particles.h
- include/aspect/simulator_access.h
- include/aspect/utilities.h
- source/global.cc
- source/mesh_refinement/volume_of_fluid_interface.cc
- source/particle/generator/quadrature_points.cc
- source/particle/generator/reference_cell.cc
- source/simulator/assemblers/advection.cc
- source/utilities.cc
Fix the leftovers from our last years starter PRs. This does not conflict with this years PRs, because this year we removed the PETSc ifdefs.
> Remove deal.II compatibility code

- tests/poiseuille_2d_pressure_bc_gmg.prm
- tests/poiseuille_2d_pressure_bc_gmg/screen-output
- tests/poiseuille_2d_pressure_bc_gmg/statistics
> test: traction bc with GMG

- source/simulator/assemblers/newton_stokes.cc
> Fix a typo in two places.

- source/main.cc
- source/postprocess/matrix_statistics.cc
removes ASPECT_USE_PETSC clause.
> removed ASPECT_PETSC

- source/boundary_composition/interface.cc
- source/boundary_temperature/constant.cc
- source/boundary_temperature/interface.cc
- source/boundary_velocity/interface.cc
- source/mesh_deformation/diffusion.cc
- source/mesh_deformation/interface.cc
- source/simulator/parameters.cc
> Make an error message easier to read.

- include/aspect/geometry_model/chunk.h
- source/geometry_model/chunk.cc
Improve some things that came up in #978 for the chunk as well.
> Improve comments and simplify chunk

- include/aspect/material_model/steinberger.h
- include/aspect/material_model/utilities.h
- source/material_model/steinberger.cc
- source/material_model/utilities.cc
This addresses @gassmoeller's comments on #4160.
> more cleanup in steinberger model

- include/aspect/material_model/equation_of_state/multicomponent_incompressible.h
- include/aspect/material_model/replace_lithosphere_viscosity.h
- include/aspect/material_model/rheology/composite_visco_plastic.h
- include/aspect/material_model/rheology/diffusion_creep.h
- include/aspect/material_model/rheology/dislocation_creep.h
- include/aspect/material_model/rheology/peierls_creep.h
- include/aspect/material_model/rheology/visco_plastic.h
- include/aspect/material_model/utilities.h
- include/aspect/utilities.h
- source/material_model/diffusion_dislocation.cc
- source/material_model/equation_of_state/multicomponent_incompressible.cc
- source/material_model/rheology/composite_visco_plastic.cc
- source/material_model/rheology/diffusion_creep.cc
- source/material_model/rheology/dislocation_creep.cc
- source/material_model/rheology/peierls_creep.cc
- source/material_model/rheology/visco_plastic.cc
- source/material_model/utilities.cc
- source/material_model/visco_plastic.cc
- source/utilities.cc
- tests/composite_viscous_outputs.cc
- unit_tests/parse_map_to_double_array.cc
> Use std::unique_ptr instead of std::shared_ptr in a number of places.

- contrib/catch/catch.hpp
> fix catch compilation on M1 arm

- doc/manual/manual.tex
I fixed the first line of the annulus benchmark: our paper was rejected. While I was at it I corrected a bunch of units in two of my cookbooks.
> fixing units in manual

- contrib/catch/catch.hpp
based on https://github.com/geodynamics/aspect/pull/4201#pullrequestreview-705728250
> update catch library to 2.13.6

- AUTHORS.md
- README.md
- doc/manual/manual.tex
Added me to the list of maintainers :)
> added Bob and Cedric to the list of maintainers/principal developers

- source/particle/generator/interface.cc
Follow-up to #4212. Necessary to make things compile on my end.
/rebuild
> Fix missing template argument.

- source/simulator/melt.cc
- source/simulator/stokes_matrix_free.cc
> Correct spelling of 'Stokes'.

- source/material_model/rheology/visco_plastic.cc
Based on an observation by @naliboff in https://github.com/geodynamics/aspect/issues/4193#issuecomment-879061394 . I surrounded the whole block by curly braces to limit the scope of the variables I'm touching to convince myself that they are not actually used again further down below in places I had not considered.
/rebuild
> Avoid some viscosity computations when not necessary.

- doc/manual/manual.tex
> Consistently use American English spelling of 'meter'.

- benchmarks/check.mk
> fix check.mk for benchmarks/

- doc/modules/changes/20210709_sliu
- source/simulator/assemblers/newton_stokes.cc
- tests/prescribed_dilation_newton/statistics
- tests/prescribed_dilation_newton_singleadvection.cc
- tests/prescribed_dilation_newton_singleadvection.prm
- tests/prescribed_dilation_newton_singleadvection/screen-output
- tests/prescribed_dilation_newton_singleadvection/statistics
* [1] I have read the guidelines in our [CONTRIBUTING.md](../blob/master/CONTRIBUTING.md) document.
* [1] I have followed the [instructions for indenting my code](../blob/master/CONTRIBUTING.md#making-aspect-better).
* [1] I have tested my new feature locally to ensure it is correct.
> Fix the 'prescribed dilation' in newton_stokes

- source/simulator/core.cc
> fix a typo

- benchmarks/crameri_et_al/case_1/crameri_benchmark_1.prm
- benchmarks/inclusion/adaptive.prm.base
- benchmarks/inclusion/global.prm.base
We are now more strict about boundary conditions, see #4162. Fix a couple of benchmark problems.
> Fix benchmarks/

- source/material_model/diffusion_dislocation.cc
- source/material_model/utilities.cc
- source/material_model/visco_plastic.cc
- source/particle/property/interface.cc
- source/particle/world.cc
We jumped the gun on these places :-)
Related to #4188 .
/rebuild
> Don't use std::make_unique just yet.

- benchmarks/newton_solver_benchmark_set/nonlinear_channel_flow/input_t_gmg.prm
- benchmarks/newton_solver_benchmark_set/nonlinear_channel_flow/input_v_gmg.prm
- benchmarks/newton_solver_benchmark_set/tosi_et_al_2015/input_gmg.prm
- doc/modules/changes/20210715_jiaqi
- include/aspect/stokes_matrix_free.h
- source/simulator/solver_schemes.cc
- source/simulator/stokes_matrix_free.cc
- tests/nonlinear_channel_flow_tractions_Newton_Stokes_GMG.prm
- tests/nonlinear_channel_flow_tractions_Newton_Stokes_GMG/screen-output
- tests/nonlinear_channel_flow_tractions_Newton_Stokes_GMG/statistics
- tests/tosi_benchmark_gmg_newton_solver.prm
- tests/tosi_benchmark_gmg_newton_solver/screen-output
- tests/tosi_benchmark_gmg_newton_solver/statistics
Preliminary support for GMG solver for problems with Newton nonlinear solver.
We currently do not include the Newton terms in the preconditioner, but this is already a strict improvement to before.
> GMG Newton solver

- include/aspect/postprocess/viscous_dissipation_statistics.h
- source/postprocess/viscous_dissipation_statistics.cc
Just some minor follow-up tweaks to #4214.
> Minor refactoring of viscous dissipation statistics

- source/postprocess/composition_statistics.cc
- source/postprocess/gravity_point_values.cc
- source/postprocess/heating_statistics.cc
- source/postprocess/matrix_statistics.cc
- source/postprocess/max_depth_field.cc
- source/postprocess/melt_statistics.cc
- source/postprocess/memory_statistics.cc
- source/postprocess/particle_count_statistics.cc
- source/postprocess/spherical_velocity_statistics.cc
- source/postprocess/temperature_statistics.cc
> Remove some unnecessary include files.

- source/particle/world.cc
- tests/particle_periodic_quarter_shell.prm
- tests/particle_periodic_quarter_shell/particles/particles-00001.0000.vtu
- tests/particle_periodic_quarter_shell/particles/particles-00001.0001.vtu
> [2.3] take over Disable failing particle integration schemes in periodic shells

- include/aspect/global.h
- source/global.cc
- source/main.cc
- source/mesh_deformation/diffusion.cc
- source/mesh_deformation/free_surface.cc
- source/simulator/assembly.cc
- source/volume_of_fluid/solver.cc
> Remove remaining uses of PETSc from the code base.

- source/postprocess/visualization/volume_of_fluid_values.cc
I guess I just can't help myself when I see these places...
/rebuild
> Minor grammar fixes.

- cookbooks/christensen_yuen_phase_function/doc/christensen_yuen_phase_function.tex
- doc/manual/cookbooks/visualizing_phase_diagram/doc/visualizing_phase_diagram.tex
- doc/manual/manual.tex
Mostly follow-ups to #4257. (@lhy11009 FYI)
/rebuild
> Minor edits to the manual.

- source/postprocess/visualization/grain_lag_angle.cc
Like #4284. I had not realized that there was another place.
/rebuild
> Use a proper reference in another place.

- source/simulator/checkpoint_restart.cc
> Don't open the same file on all processes.

- doc/manual/citing_aspect.bib
Add a Nature Communications publication by Moh and John to the list of publications.
> Adding recent publication, Gouiza and Naliboff

- source/postprocess/visualization/spherical_velocity_components.cc
This should fix #4253 (at least it did for me). @cedrict can you give this a try?
> Fix spherical velocity postprocessor

- CMakeLists.txt
> disable precompiled header for Intel compiler

- source/particle/generator/interface.cc
While there, fix problems with an error message: It doesn't actually compute
what we think it computes, and then also outputs the inverse of it.
/rebuild
> Use BoundingBox in the generation of particles.

- source/simulator/stokes_matrix_free.cc
GMG: rm if DEAL_II_VERSION_GTE(9,3,0).
> GMG: rm if DEAL_II_VERSION_GTE(9,3,0)

- benchmarks/diffusion_of_hill/analytical_topography.cc
- include/aspect/compat.h
- include/aspect/material_model/interface.h
- include/aspect/particle/world.h
- source/geometry_model/spherical_shell.cc
- source/material_model/equation_of_state/thermodynamic_table_lookup.cc
- source/material_model/grain_size.cc
- source/material_model/interface.cc
- source/mesh_deformation/diffusion.cc
- source/mesh_deformation/free_surface.cc
- source/particle/generator/interface.cc
- source/particle/world.cc
- source/postprocess/topography.cc
- source/postprocess/visualization/boundary_velocity_residual.cc
- source/postprocess/visualization/dynamic_topography.cc
- source/postprocess/visualization/geoid.cc
- source/postprocess/visualization/heat_flux_map.cc
- source/postprocess/visualization/heating.cc
- source/postprocess/visualization/material_properties.cc
- source/postprocess/visualization/surface_dynamic_topography.cc
- source/simulator/checkpoint_restart.cc
- source/simulator/core.cc
- source/simulator/melt.cc
rm more DEAL_II_VERSION_GTE(9,3,0)
> rm more DEAL_II_VERSION_GTE(9,3,0)

- citing.html
- database.js
> www: update citing database

- include/aspect/compat.h
- unit_tests/additional_outputs.cc
> remove more cxx14::make_unique

- include/aspect/parameters.h
- source/simulator/nullspace.cc
- No functional changes!
- introduce nullspace enums to select more than one option
- remove early return in setup_nullspace_constraints
- improve readability in remove_nullspace
> reorganize nullspace

- source/geometry_model/two_merged_chunks.cc
as reported on the forums.
Other place: https://github.com/geodynamics/aspect/blob/94a83067837e04f97d4d3c787987f43bf8aef327/source/geometry_model/chunk.cc#L935
> remove duplicate ChunkGeometry instantiation

- doc/manual/citing_aspect.bib
An update to one of our references, pulled from: https://mem.lyellcollection.org/content/early/2021/09/08/M56-2020-2.abstract?casa_token=esxQ6dz0_g0AAAAA%3AS_f8sCKk0-qHBleKlVlSkNkOxfIK8ymg3SoTJ-HW17JTRvHankqVN3B94_Um3eZ0FmYhdnwOIfHz
> Update to reference

- doc/modules/changes/20210920_ekendall
- include/aspect/simulator.h
- source/simulator/checkpoint_restart.cc
- source/simulator/core.cc
- source/simulator/helper_functions.cc
> print total wall time after restarts

- include/aspect/simulator.h
- source/simulator/checkpoint_restart.cc
- source/simulator/core.cc
- source/simulator/helper_functions.cc
followups to #4332
- improve comments
- rename variable
> wall time followups

- cookbooks/plume_2D_chunk/plume2D.prm
- tests/melt_visco_plastic.cc
- tests/particle_property_initial_composition_boundary.prm
- tests/visco_plastic_adiabatic_heating_density.prm
Apply our parameter and source file update scripts to eliminate some outdated variables and input parameters.
> Apply update scripts to source and parameter files

- include/aspect/mesh_deformation/interface.h
Fix a few places in `MeshDeformationHandler<dim>::*_matching_mesh_deformation_object` as suggested by @tjhei .
> fix MeshDeformationHandler<dim>::*_matching_mesh_deformation_object

- benchmarks/viscoelastic_stress_build-up/viscoelastic_stress_build-up.prm
- source/geometry_model/ellipsoidal_chunk.cc
- source/material_model/rheology/elasticity.cc
- source/termination_criteria/end_walltime.cc
- tests/ascii_data_layered_initial_composition_2d_box.prm
> Fix some typos

- source/termination_criteria/steady_heat_flux.cc
As discussed on the mailing list.
/rebuild
> Augment the description of the heat flux termination criterion.

- source/particle/world.cc
This PR fixes for an an error message in pre-compiled headers.
* [X ] I have read the guidelines in our [CONTRIBUTING.md](../blob/master/CONTRIBUTING.md) document.
* [X ] I have followed the [instructions for indenting my code](../blob/master/CONTRIBUTING.md#making-aspect-better).
> Fixed an error message for pre-compiled headers.

- include/aspect/stokes_matrix_free.h
- source/simulator/stokes_matrix_free.cc
Add GMG timing options: 
```
subsection Solver parameters
subsection Matrix Free
set Output details = true
set Execute solver timings = true
end
end
```
@tjhei
> GMG timings option

- source/particle/world.cc
After optimizing the particle update routines in previous PRs the memory allocation now shows up as a major cost when profiling the particles (15% of the total update cost in 2D spherical models, likely more in 2d box models, less in 3d spherical). This PR reorganizes the SolutionEvaluators class to work with preallocated vectors. It also avoids the calls to `std::distance` which with the new particle organization inside deal.II are more expensive then simply calling `n_particles_in_cell`. No change in functionality, just refactoring.
> Reduce memory allocations

- source/particle/world.cc
> Remove unnecessary include

- source/mesh_refinement/maximum_refinement_function.cc
- source/mesh_refinement/minimum_refinement_function.cc
- source/mesh_refinement/volume_of_fluid_interface.cc
> Remove a few more uses of GeometryInfo.

- source/geometry_model/ellipsoidal_chunk.cc
- source/geometry_model/spherical_shell.cc
- source/mesh_deformation/diffusion.cc
I broke these out of #4425. These should be uncontroversial, but let's see what we find.
Follow-up to #4424.
/rebuild
> More GeometryInfo stuff.

- source/geometry_model/box.cc
- source/geometry_model/chunk.cc
- source/geometry_model/ellipsoidal_chunk.cc
- source/geometry_model/sphere.cc
- source/geometry_model/spherical_shell.cc
- source/geometry_model/two_merged_boxes.cc
- source/geometry_model/two_merged_chunks.cc
- source/material_model/compositing.cc
- source/postprocess/composition_statistics.cc
- source/postprocess/max_depth_field.cc
- source/simulator/helper_functions.cc
Specifically, use a better way to deal with unspecified array sizes than
sizeof(X)/sizeof(X[0])
/rebuild
> Modernize code a bit in places.

- source/postprocess/mobility_statistics.cc
Avoid uninitialized variables in the mobility_statistics postprocessor. This would work most of the times, but occasionally lead to test failures like in #4431 (at least I think this is the reason). Also improve the code style a bit and avoid unnecessary computations. @elodie-kendall FYI, you need to initialize variables of type `double` otherwise their value is not determined and can be random (or 0 if you are lucky). I missed this during my review.
> Initialize variables in mobility statistics postprocessor

- source/postprocess/heat_flux_map.cc
> Make code in heat_flux_map.cc more efficient.

- source/postprocess/heat_flux_map.cc
I didn't understand the code, so had to read around a bit in it. That usually leads to writing commentary...
/rebuild
> Augment documentation.

- source/postprocess/mobility_statistics.cc
- source/simulator/assemblers/interface.cc
- source/simulator/assembly.cc
- source/volume_of_fluid/assembler.cc
> Remove a few more occurrences of GeometryInfo.

- source/simulator/core.cc
> Add an assertion about cell types.

- source/main.cc
Prompted by the question on the forum in the last few days, I took a look at the code and thought that that might be worthwhile simplifying with the regex machinery that's been part of C++ since C++11.
/rebuild
> Simplify code by using regular expressions.

- source/particle/world.cc
- source/simulator/core.cc
- source/simulator/initial_conditions.cc
- source/simulator/solver_schemes.cc
It's not a descriptive variable name.
/rebuild
> Don't name lambda functions 'lambda'.

- doc/manual/citing_aspect.bib
Adds Lunden et al. 2021 and Lee at al 2021 to the publication list.
> Add 2 new publications to the citations

- doc/manual/manual.tex
Removed my name from the list of contributors, as I'm already in the list of authors.
> removed name from contributors

- include/aspect/material_model/grain_size.h
- include/aspect/material_model/rheology/strain_dependent.h
- source/material_model/grain_size.cc
- source/material_model/rheology/strain_dependent.cc
This is essentially the same PR as #4416 but for a few additional uses of FEValues.
@naliboff: Can you check if this accelerates the Kaus2010 benchmark case?
> Replace FEValues by FEPointEvaluation where useful

- doc/modules/changes/20220126_mfraters
- source/simulator/assemblers/newton_stokes.cc
- tests/Picard_compressible.prm
- tests/Picard_compressible/screen-output
- tests/dc_Picard_compressible.prm
- tests/dc_Picard_compressible/screen-output
Investigating issue #4388 I found that the compressible terms for the Newton (and therefore the defect correction Picard solver) are not added in the correct way. This lead to the solver not converging (even diverging). The test case proveded by @elodie-kendall does not converge for me and the solutions for the first timestep (0) look now identical to me. 
@elodie-kendall, could you check whether this solves the issue for you?
> fix Newton compressible terms.

- doc/manual/citing_aspect.bib
> Adds first publication of the year to the publication list

- include/aspect/stokes_matrix_free.h
- source/simulator/stokes_matrix_free.cc
- tests/nsinker_gmg_idr/screen-output
- tests/poiseuille_2d_pressure_bc_gmg/screen-output
Fix max/min of the evaluated viscosities in `evaluate_material_model()`. @tjhei
> GMG: fix max/min of the evaluated viscosities

- benchmarks/blankenbach/plugin/code.cc
- benchmarks/newton_solver_benchmark_set/spiegelman_et_al_2016/drucker_prager_compositions.cc
- source/boundary_velocity/gplates.cc
- source/global.cc
- source/initial_temperature/lithosphere_mask.cc
- source/main.cc
- source/material_model/equation_of_state/thermodynamic_table_lookup.cc
- source/postprocess/boundary_velocity_residual_statistics.cc
- source/postprocess/depth_average.cc
- source/postprocess/heat_flux_densities.cc
- source/postprocess/mass_flux_statistics.cc
- source/postprocess/point_values.cc
- source/postprocess/rotation_statistics.cc
- source/postprocess/velocity_boundary_statistics.cc
- source/postprocess/velocity_statistics.cc
- source/postprocess/volume_of_fluid_statistics.cc
- source/simulator/core.cc
- source/simulator/helper_functions.cc
- source/simulator/solver_schemes.cc
- source/simulator/stokes_matrix_free.cc
- source/structured_data.cc
- source/utilities.cc
- tests/additional_outputs_03.cc
- tests/artificial_postprocess.cc
- tests/boundary_heatflux_update.cc
- tests/composite_viscous_outputs.cc
- tests/coordinate_transformation.cc
- tests/plugin.cc
- tests/vof_err_calc.h
- unit_tests/common.h
Inspired by https://github.com/dealii/dealii/pull/13339.
/rebuild
> Save a few cycles when outputting only a single char.

- source/utilities.cc
The first commit is just a collection of small cleanups. The second one fixes the issue that we broadcast file sizes as `unsigned int`, but that may be too small and is in fact sometimes as evidenced on the mailing list.
/rebuild
> Cleanup and fix large file issues

- source/particle/world.cc
This PR makes use of the improvements in dealii/dealii#12983 and should only be merged after that PR is merged. It reduces the duplicated computation of the mapping data during particle updates.
> Use precomputed mapping information during particle updates

- source/gravity_model/vertical.cc
As seen during the online demonstration just now.
/rebuild
> Add newlines between functions.

- doc/manual/citing_aspect.bib
Adds latest publication to Science Advances by Craig O'Neill and Sonja Aulbach
> Add new publication by ONeill and Aulbach

- doc/manual/citing_aspect.bib
Follow-up to https://github.com/geodynamics/aspect/pull/4502/files/d481de58c44ab0e6c25249ae8205dbe3ef56ecb4#diff-f3e0817100d729ef8277165d0254a0ac4e8ec69410b5be32826c61750873ed9a
/rebuild
> Fix a UTF8 character.

- include/aspect/simulator/assemblers/interface.h
Breaking this out of the next patch to make that one a bit shorter.
/rebuild
> Cosmetic changes.

- doc/manual/manual.tex
> fixed a typo in a path in cookbook 5.3.4

- source/geometry_model/box.cc
> Update a reference to GeometryInfo.

- source/simulator/parameters.cc
Update Initial global refinement parameter description according to discussion in #4507 .
> Update description Initial global refinement

- tests/free_surface_relaxation.cc
> Replace GeometryInfo in a test .cc file.

- source/simulator/stokes_matrix_free.cc
Probably slipped through under the radar because everyone but me uses unity builds :-)
/rebuild
> Add a necessary header file.

- source/simulator/core.cc
- tests/initial_global_refinement.prm
- tests/initial_global_refinement/screen-output
- tests/initial_global_refinement/statistics
> Do initial global refinement correctly in parallel

- include/aspect/compat.h
Like #4520. The patch that added this one place crossed wires with #4520.
/rebuild
> Test for deal.II >= 9.4 instead of 10.0.

- .github/workflows/linux.yml
- contrib/ci/Dockerfile
- contrib/docker/tester/Dockerfile
Update docker image for Jenkins to 9.3.2
TODO: update github actions once new ubuntu packages are released.
> Switch tester to 9.3.2

- .github/workflows/linux.yml
Follow-up to #4405 to make the tests in #4528 pass.
> Use updated deal.II 9.3.2 container for github actions

- include/aspect/material_model/rheology/friction_models.h
- source/material_model/rheology/friction_models.cc
- source/material_model/rheology/visco_plastic.cc
- tests/visco_plastic_friction_function.prm
- tests/visco_plastic_friction_function/screen-output
This is a follow-up on PR #4357. It adds the option to specify friction angles as functions of space and time per composition in the input file. 
I put a little test case into the tests folder to show @elodie-kendall how to use this functionality. If this could be useful as an aspect test, let me know, otherwise I will remove it.
> Move dynamic friction into a friction rheology add function for friction

- source/mesh_deformation/free_surface.cc
- source/mesh_deformation/interface.cc
- source/mesh_refinement/composition.cc
- source/mesh_refinement/temperature.cc
- source/postprocess/dynamic_topography.cc
- source/simulator/helper_functions.cc
- source/simulator/initial_conditions.cc
- source/simulator/nullspace.cc
- source/volume_of_fluid/reconstruct.cc
These objects should always be `const`.
/rebuild
> Make quadrature objects 'const'.

- source/mesh_refinement/composition.cc
- source/mesh_refinement/temperature.cc
- source/mesh_refinement/velocity.cc
- source/particle/generator/quadrature_points.cc
- source/postprocess/spherical_velocity_statistics.cc
- source/simulator/entropy_viscosity.cc
- source/simulator/helper_functions.cc
- source/simulator/nullspace.cc
- source/termination_criteria/steady_rms_velocity.cc
- source/termination_criteria/steady_temperature.cc
Follow-up to #4536 and #4544.
/rebuild
> Use centralized quadrature formulas.

- cookbooks/global_melt/doc/global_melt.prm
- cookbooks/global_melt/global_melt.prm
- doc/Makefile
- include/aspect/utilities.h
- source/material_model/grain_size.cc
- source/material_model/rheology/strain_dependent.cc
- source/material_model/steinberger.cc
- source/mesh_refinement/isosurfaces.cc
- source/simulator/parameters.cc
- tests/spiegelman_fail_test.prm
> Fix a number of typos.

- source/simulator/stokes_matrix_free.cc
Fix https://github.com/geodynamics/aspect/issues/4597
> Disable mesh deformation+GMG for dealii versions older than 9.3.2

- source/postprocess/visualization/compositional_vector.cc
- source/postprocess/visualization/geoid.cc
- source/postprocess/visualization/heating.cc
- source/postprocess/visualization/material_properties.cc
- source/postprocess/visualization/melt.cc
- source/postprocess/visualization/temperature_anomaly.cc
The ever-important patch.
/rebuild
> Add missing empty lines.

- source/postprocess/visualization/strain_rate.cc
> Break awkwardly long lines.

- source/postprocess/visualization/seismic_anomalies.cc
The seismic anomaly viz postprocessors output anomalies as per cent. Make this clearer in the code.
/rebuild
> Make percentage computation clearer.

- doc/sphinx/user/intro.md
my second attempt to create the change to the correct capitalization of deal.II (I now see where I failed previously).
> 2nd attempt at correcting deal.II correction

- doc/sphinx/user/methods/dimensionalize/index.md
Corrects multiples instances of earth vs. Earth for the planet we live on.
> Documentation: Dim or no Dim

- doc/sphinx/user/methods/coefficients/index.md
Corrects multiples instances of earth vs. Earth for the planet we live on.
> Documentation: fix coefficient/index.md 4 Earth

- doc/sphinx/user/intro.md
Fix's grammatical errors in the introduction.
> Fix grammatical errors

- doc/sphinx/user/methods/basic-equations/2d-models.md
I am thinking the ':' is in error so I thought I would take the opportunity to add a few commas as well.
> Documentation: Basic equations 2d-models.md

- source/postprocess/visualization.cc
> Be explicit by marking functions in a derived class as 'virtual'.

- doc/sphinx/user/methods/pressure-static-dyn.md
Fixes and awkward sentence but mostly wanted to capitalize instances of 'E'arth.
> Documentation: Static or Dynamic grammar fixes

- doc/sphinx/user/methods/pressure-norm.md
More Earth's vs. earth.  Perhaps this was a style decision made early on???
> Documentation: Pressure normalization

- doc/sphinx/user/methods/initial-conditions.md
Some more minor punctuation clean up **AND** should the last word really be 'mantle' vs. manual ??? **PLEASE VERIFY.**
> Documentation: Init cond adiabatic

- doc/sphinx/user/methods/numerical-methods.md
Properly punctuates names of libraries. And more Earth's.
> Documentation: Numerical methods - library names

- doc/sphinx/user/methods/approximate-equations/ala.md
> Documentation: ALA - spelling

- doc/sphinx/user/methods/compositional-fields.md
Removes some stray mark-up that does not look like it is being used.
> Documentation: Compositional Fields

- source/postprocess/visualization.cc
> Revert the accidental addition of 'virtual'.

- doc/sphinx/user/methods/freesurface/stabilization.md
Updates the reference to Kaus, Mulhaus, and May (2020) to link to the references.bib entry.
> Documentation: Free surface - insert reference

- doc/sphinx/user/methods/freesurface/arbitrary-le-implementation.md
- doc/sphinx/user/methods/melt-transport.md
- doc/sphinx/user/methods/particles.md
> Some more fixes for the .md documentation.

- doc/sphinx/quickref.md
> Make quickref clearer and more accurate

- doc/sphinx/user/install/docker-container/installing-docker.md
Removes duplicate header and adds a missing comma.
> Documentation: installing Docker

- doc/sphinx/user/install/virtual-machine/installing-vm.md
Adding a comma (and loving the easy ones!)
> Documentation: VM

- doc/sphinx/user/install/docker-container/developing-in-container.md
Corrects a grammatical error.
Does not correct the capitalization of deal.II. A global fix is in the works for that ;) bangerth.
> Documentation: Dev in container

- doc/sphinx/user/install/local-installation/system-prereqs.md
> Documentation: System Prereqs

- doc/sphinx/user/install/local-installation/compiling.md
Adds comma.
Misc typesetting fix.
> Documentation: Compiling ASPECT

- doc/sphinx/environment.yml
- doc/sphinx/requirements.txt
Splitting out #4611. This only contains the changes for setting up the tikz environment.
> Add tikz environment.

- tests/gravity_point_values_spiral_parallel.prm
- tests/gravity_point_values_spiral_parallel/screen-output
- tests/gravity_point_values_spiral_parallel/statistics
In preparation for #4485.
/rebuild
> Add a test for parallel computation of gravity point values.

- doc/sphinx/user/run-aspect/overview.md
I missed that there was a missing note.  This hopefully adds it back in correctly and should have no conflicts.
> Documentation: overview - add note

- doc/sphinx/user/run-aspect/2d-vs-3d.md
Corrects footnotes and adds a link. 
Still needs correct links to sections.
> Documentation: selecting 2d and 3d

- doc/sphinx/user/run-aspect/debug-mode.md
Corrects footnotes and adds a link. 
Still needs correct links to sections.
> Documentation: debug mode

- doc/sphinx/user/run-aspect/visualizing-results/visit.md
Makes the easy updates - footnotes and spelling. The tougher stuff still needs to be done .... figures and section references.
> Documentation: Visit

- doc/sphinx/user/install/local-installation/obtaining.md
Removes a comma this time!
Adds a TODO for @cmills1095 to fix section reference.
> Documentation: Obtaining ASPECT

- .github/workflows/linux.yml
Necessary for #4668. @gassmoeller -- FYI.
Not sure whether rebuilding anything will actually do anything useful here.
> Also require inkscape for the CI.

- Jenkinsfile
With @ljhwang's new role as chief documentation officer (CDO) it would be useful if would not have to mark all of her PRs as ready to test before they run through the testers. This PR does this.
> Add Lorraine to list of trusted testers

- doc/sphinx/user/run-aspect/parameters-overview/compatibility.md
> Documentation: compatability

- doc/sphinx/user/run-aspect/gui/using.md
Insert formatting for figure.  The figure still needs to be placed into the proper directory.
> Documentation: aspect-gui

- doc/sphinx/user/run-aspect/checkpoint-restart.md
Adds note box.
Needs properly referenced links.
> Documentation: checkpoint restart

- contrib/utilities/indent
> Avoid deprecated combination of 'xargs' flags.

- doc/sphinx/user/extending/testing/running-tests.md
- doc/sphinx/user/install/docker-container/developing-in-container.md
- doc/sphinx/user/install/docker-container/running-models.md
- doc/sphinx/user/install/index.md
- doc/sphinx/user/install/local-installation/obtaining.md
- doc/sphinx/user/install/local-installation/using-candi.md
- doc/sphinx/user/install/virtual-machine/running-models.md
- doc/sphinx/user/run-aspect/debug-mode.md
> Installation chapter conversion

- doc/sphinx/conf.py
> Automatically parse VERSION for sphinx documentation

- doc/sphinx/_templates/sidebar-cig.html
- doc/sphinx/conf.py
- doc/sphinx/environment.yml
- doc/sphinx/requirements.txt
I am testing some design improvements here, please do not merge until I am ready.
> Improve Sphinx design

- source/simulator/parameters.cc
> shorten an assert

- doc/sphinx/user/methods/basic-equations/index.md
I should clearly stop for today. I messed this up as part of #4744. I am working towards an error free latex build, so that we can enable that as a test as well.
> Fix minor documentation issues

- benchmarks/solcx/doc/solcx.md
- benchmarks/solkz/doc/solkz.md
I moved the SolKz cookbook, which was supposed to link to the SolCx cookbook, so of course, I had to do that one as well. I stopped myself after adding the label to visualizing_results which SolCx links.
> Doc: Updated SolCx and Solkz benchmark

- doc/modules/changes/20220519_wolfgangbangerth
- doc/modules/changes/20220520_wolfgangbangerth
Adding these for #4637 and #4704 where I had forgotten about it.
/rebuild
> Add two changelog entries for recent patches of mine.

- contrib/utilities/jsontomarkdown.py
- doc/sphinx/parameters/Adiabatic_20conditions_20model.md
- doc/sphinx/parameters/Boundary_20composition_20model.md
- doc/sphinx/parameters/Boundary_20fluid_20pressure_20model.md
- doc/sphinx/parameters/Boundary_20heat_20flux_20model.md
- doc/sphinx/parameters/Boundary_20temperature_20model.md
- doc/sphinx/parameters/Boundary_20traction_20model.md
- doc/sphinx/parameters/Boundary_20velocity_20model.md
- doc/sphinx/parameters/Checkpointing.md
- doc/sphinx/parameters/Compositional_20fields.md
- doc/sphinx/parameters/Discretization.md
- doc/sphinx/parameters/Formulation.md
- doc/sphinx/parameters/Geometry_20model.md
- doc/sphinx/parameters/Gravity_20model.md
- doc/sphinx/parameters/Heating_20model.md
- doc/sphinx/parameters/Initial_20composition_20model.md
- doc/sphinx/parameters/Initial_20temperature_20model.md
- doc/sphinx/parameters/Material_20model.md
- doc/sphinx/parameters/Melt_20settings.md
- doc/sphinx/parameters/Mesh_20deformation.md
- doc/sphinx/parameters/Mesh_20refinement.md
- doc/sphinx/parameters/Nullspace_20removal.md
- doc/sphinx/parameters/Postprocess.md
- doc/sphinx/parameters/Prescribed_20Stokes_20solution.md
- doc/sphinx/parameters/Solver_20parameters.md
- doc/sphinx/parameters/Temperature_20field.md
- doc/sphinx/parameters/Termination_20criteria.md
- doc/sphinx/parameters/Time_20stepping.md
- doc/sphinx/parameters/Volume_20of_20Fluid.md
The bold headers in the sidebar look weird, so let's remove the manual
formatting
> doc: do not make headers bold

- doc/sphinx/user/cookbooks/index.md
There is not a "right" model but only one that describes your problem and does not lead to odd behaviors or crashes.
> Documentation: Cookbooks

- doc/sphinx/user/extending/plugin-types/geometry-models.md
When proofreading this, I noticed that the online version appears out of step with the source file - some changes had already been made. I corrected errors that appeared to still exist. Hopefully this does not create merge conflicts.
> Documentation: geometry models

- doc/sphinx/user/cookbooks/cookbooks-overview.md
In correcting the missing question mark on the questions, I added some clarifying language (I think). Please feel free to edit if I made an error.
> Documentation: Cookbooks how to

- doc/sphinx/user/extending/compatibility.md
Taking the freebie here ... adding a missing comma.
> Documentation: compatibility

- include/aspect/structured_data.h
As pointed out in https://github.com/geodynamics/aspect/pull/4086/files/ca949295c9709ae08a21c5d55ca872437bb9c9f7#diff-31cf6d634c32b66a3f13b0036fad8adb7ef2146feaa5931aff0406fc83461a20 .
/rebuild
> Avoid an #ifdef inside a comment.

- contrib/utilities/jsontomarkdown.py
Just introducing shortcuts so we don't have to write the same expression over and over.
This script is not run automatically anywhere, so the testers will not do much good. But I have verified by hand that the output is the same.
/rebuild
> Simplify code structure in python script slightly.

- doc/sphinx/user/extending/testing/test-properties.md
> Documentation: test properties

- include/aspect/simulator.h
- include/aspect/simulator_access.h
- source/material_model/interface.cc
- source/mesh_deformation/free_surface.cc
- source/simulator/assemblers/advection.cc
- source/simulator/assembly.cc
- source/simulator/melt.cc
- source/simulator/simulator_access.cc
- source/simulator/stokes_matrix_free.cc
> Remove a duplicate function

- doc/sphinx/user/extending/contributing.md
Changes the admonition from a 'note' to 'important' to make it more attention grabbing. Fixes a few other minor errors as well.
> Documentation: contributing

- doc/sphinx/user/extending/future-plans.md
Fixes capitalization (just checking off the easy ones).
> Documentation: future plans

- doc/sphinx/user/benchmarks/benchmark-run.md
> Documentation: running benchmarks

- benchmarks/inclusion/doc/inclusion.md
I split the dual-image figure into two, linked the code references to GitHub, and fixed the citations.
> Documentation: inclusion benchmark

- doc/sphinx/user/benchmarks/benchmark-run.md
This should fix the reference in #4810.
> fix a section reference

- doc/sphinx/environment.yml
> Remove a python package no longer needed.

- tests/crameri_benchmark_1_gmg.cc
- tests/infill_density_flexure.cc
- tests/magnetic_stripes.cc
- tests/melt_track.cc
- tests/particle_property_composition.cc
- tests/rigid_shear_instantaneous.cc
- tests/rigid_shear_time_dependent.cc
- tests/shear_bands.cc
- tests/solitary_wave.cc
- tests/spiegelman_material.cc
- tests/tosi_benchmark.cc
- tests/tosi_benchmark_newton_solver.cc
- tests/tosi_benchmark_newton_solver_full_A.cc
See the discussion in #4801.
/rebuild
> Use #include "..." when using relative paths.

- doc/sphinx/user/run-aspect/visualizing-results/index.md
Fixes broken link and proper spelling of VisIt.
> Documentation: Updating Visualizing results

- doc/manual/citing_aspect.bib
Had this sitting around for quite a long time already (just over a year).
/rebuild
> Add a publication that uses ASPECT.

- doc/sphinx/user/install/docker-container/running-models.md
Clean-up a few punctuation issues.
> Documentation: running models

- doc/sphinx/user/run-aspect/overview.md
Corrects spelling of VisIt and cleans up a few formatting issues.
> Documentation: running aspect overview

- doc/modules/changes/20220524_alarshi
This PR adds changelog entry for PR#3915
> Add change log entry.

- tests/prescribed_field_temperature_max_isotherm.prm
- tests/prescribed_field_temperature_max_isotherm/screen-output
- tests/prescribed_field_temperature_max_isotherm/statistics
- tests/prescribed_temperature_in_field.cc
- tests/prescribed_temperature_in_field.prm
Added a control of the plugin which fixes the temperature within a compositional field. This control also allows the fixing of all temperatures below a user specified maximum value of temperature.
> Add a max temperature constraint in fixed temperature within compositional field plugin

- include/aspect/material_model/interface.h
- source/material_model/interface.cc
- source/material_model/rheology/elasticity.cc
- source/simulator/nullspace.cc
Follow-up to #4248. @anne-glerum what do you think about removing the `force_terms`?
> Follow-up fixes to 4248

- source/particle/world.cc
This should adapt ASPECT to work with the interface changes made in deal.II in dealii/dealii#13835.
Unfortunately so far I can only say that it compiles with deal.II dev, I cannot test if models run, because of the problems with dealii/dealii#13815 (at the moment no ASPECT model can run with a recent deal.II master).
Let's at least see if the 9.3 tester runs successfully, and I want to test this a bit more once I can test deal.II dev.
> [WIP] Fix dealii dev

- source/particle/world.cc
In #4842 I mentioned that the fix compiles, but I could not check the result due to another issue. Well, as usual successfully compiling does not mean successfully running, so here is a first batch of further fixes that make particles work in most ASPECT models with deal.II 9.4 (post dealii/dealii#13835). There is still a problem with tests that combine particles with melt migration (likely caused by the FE_DGP elements for the compaction pressure), but the remaining problems require some additional debugging and this PR is already a strict improvement that fixes most broken tests for deal.II 9.4 so I would like to get this merged separately.
> Follow-up fix to #4842

- source/particle/world.cc
This PR fixes the remaining problems with particles and deal.II 9.4. In short the FEPointEvaluation class in deal.II only supports the fast evaluation for FE_Q and FE_DGQ, but not FE_DGP (internally because FE_DGP does not use a TensorProductPolynomials polynomial space). But FEPointEvaluation requires different constructors and calls to `reinit` when using the new MappingInfo class vs the old internal mapping computation. The only instances where we sometimes use FE_DGP are the pressure, fluid pressure and compaction pressure. Therefore this PR makes sure that we use the correct calls to FEPointEvaluation depending on the exact element that was chosen for p, p_f, and p_c.
> Use slow particle evaluation path for FE_DGP elements

- doc/manual/manual.tex
- doc/sphinx/user/methods/particles.md
> Use straight d/dt instead of partials.

- include/aspect/material_model/interface.h
- include/aspect/material_model/multicomponent.h
- include/aspect/material_model/multicomponent_compressible.h
- include/aspect/material_model/steinberger.h
- include/aspect/material_model/viscoelastic.h
- source/boundary_traction/initial_lithostatic_pressure.cc
- source/material_model/interface.cc
> Do not set strain_rate to size 0 in MaterialModel

- source/material_model/diffusion_dislocation.cc
- source/material_model/drucker_prager.cc
- source/material_model/grain_size.cc
- source/material_model/melt_global.cc
- source/material_model/rheology/elasticity.cc
- source/material_model/rheology/strain_dependent.cc
- source/material_model/rheology/visco_plastic.cc
- source/simulator/melt.cc
- source/simulator/stokes_matrix_free.cc
followup to #4870
(and currently based on #4870)
> Assert strain_rate is finite in many places

- source/particle/property/pT_path.cc
While there also simplify a function returning an array.
/rebuild
> Better document an implementation detail in the pT path particle property.

- include/aspect/simulator_signals.h
> Use more obvious language.

- doc/manual/citing_aspect.bib
Adds a master and phd theses and a new publication.
> Adds several theses and a recent publication

- include/aspect/plugins.h
- source/boundary_traction/ascii_data.cc
- source/geometry_model/two_merged_boxes.cc
- source/material_model/steinberger.cc
- source/simulator/assembly.cc
- source/utilities.cc
Not wrong, but also not useful.
/rebuild
> No need to double up semicolons ;-)

- source/simulator/checkpoint_restart.cc
- source/simulator/helper_functions.cc
- source/simulator/initial_conditions.cc
> Small cosmetic changes.

- .github/workflows/linux.yml
@tjhei: What about this solution to #4897?
Fixes #4897.
> Prevent overwriting artifacts in CI pipeline

- README.md
> fix readme tutorial link

- source/postprocess/visualization.cc
see https://github.com/dealii/dealii/pull/14123
> update enum name for deal.II master

- doc/manual/citing_aspect.bib
> Adds Davies et al to citation list

- cookbooks/bunge_et_al_mantle_convection/doc/bunge_et_al_mantle_convection.md
- cookbooks/van-keken-vof/doc/van-keken-vof.md
Improving a few places in the documentation I saw during reviewing #4844.
> Minor documentation improvements

- doc/manual/citing_aspect.bib
> Fix a couple of bibtex entries.

- include/aspect/plugins.h
> Fix warning: unused variable

- doc/manual/citing_aspect.bib
2 more publications.  2022 is turning into a very productive year!
> Publications by Weerdesteijn et al. and Liu and Yang

- doc/manual/citing_aspect.bib
I also took the liberty of making the last one more uniform in style.
> Add a publication.

- include/aspect/material_model/grain_size.h
- source/material_model/grain_size.cc
* I changed the name of a variable to make it more self-explanatory.
> Grain size

- doc/manual/citing_aspect.bib
Getting caught up by adding 4 recent publications to the citations list.
> Adding recent publications

- include/aspect/particle/property/crystal_preferred_orientation.h
> make rotation matrix in set_rotation_matrix_grains a const ref.

- include/aspect/particle/property/crystal_preferred_orientation.h
resolves issue #4995. I missed updating the documentation of this function when it was changed in the pull request.
> fix cpo doxygen warning.

- benchmarks/onset-of-convection/doc/onset-of-convection.md
- cookbooks/convection-box-particles/doc/convection-box-particles.md
- cookbooks/heat_flow/doc/heat-flow.md
- cookbooks/magnetic_stripes/doc/magnetic_stripes.md
- cookbooks/onset_of_convection/doc/onset_of_convection.md
- cookbooks/platelike-boundary/doc/platelike-boundary.md
- doc/sphinx/references.bib
- doc/sphinx/user/cookbooks/teaching-setups.md
Sphinxifying another subsection. Note I added a couple new references to the bib.
> Docs: Sphinx convert teaching cookbooks

- cookbooks/gplates/doc/gplates.md
- cookbooks/initial-condition-S20RTS/doc/initial-condition-S20RTS.md
- cookbooks/shell_3d_postprocess/doc/shell_3d_postprocess.md
- cookbooks/shell_simple_3d/doc/shell_simple_3d.md
- doc/sphinx/references.bib
A few more geophysics cookbooks cleaned up in Sphinx so we can check them off the list. Going to keep the pull requests a bit smaller to make review less tedious.
Link to Jeroen Ritsema's site in initial-condition-S20RTS seemed to no longer work, is what I replaced it with appropriate?
> Docs: Some Geophysics cookbooks cleanup

- source/material_model/grain_size.cc
I updated the description of some input parameters in grain size model to specify their number of entries.
> Description updates

- doc/manual/citing_aspect.bib
Updates a previous entry and adds 2 more new publications for 2022. 
This brings the total to 24 publications and thesis for the year. Thanks everyone for making this a productive year. Looking forward to seeing all the preprints published in 2023.
> Adds last citations for 2022

- source/simulator/assemblers/newton_stokes.cc
- source/simulator/parameters.cc
> remove deprecation warnings

- cookbooks/composition-reaction/doc/composition-reaction.md
- cookbooks/composition_active/doc/composition_active.md
- cookbooks/composition_active_particles/doc/composition_active_particles.md
- cookbooks/composition_passive/doc/composition_passive.md
- cookbooks/composition_passive_particles/doc/composition_passive_particles.md
> doc: fix broken prm includes

- doc/sphinx/user/methods/nonlinear-stokes-solvers.md
- fix citations
- fix formula formatting
- typos
> doc: nonlinear solver improvements

- include/aspect/structured_data.h
- source/structured_data.cc
Some refactoring of AsciiDataBoundary and AsciiDataInitial to simplify the separation of AsciiDataBoundary into a time-dependent and time-independent part. One more step towards integrating #5025.
> Refactor AsciiDataBoundary

- source/boundary_temperature/dynamic_core.cc
- source/boundary_velocity/gplates.cc
- source/geometry_model/chunk.cc
- source/geometry_model/spherical_shell.cc
- source/particle/generator/uniform_radial.cc
- source/particle/interpolator/quadratic_least_squares.cc
- source/particle/property/crystal_preferred_orientation.cc
- source/postprocess/boundary_velocity_residual_statistics.cc
- source/postprocess/geoid.cc
- source/postprocess/particles.cc
- source/postprocess/viscous_dissipation_statistics.cc
- source/simulator/nullspace.cc
- source/structured_data.cc
- source/utilities.cc
This is the patch corresponding to #5050, just for comments.
/rebuild
> Standardize 2D->2d and 3D->3d in comments.

- include/aspect/stokes_matrix_free.h
- source/simulator/stokes_matrix_free.cc
Remove a class member that can now be a local variable
part 3 of #4793
> GMG: compute diagonal: cleanup

- source/simulator/stokes_matrix_free.cc
- use make_shared
- rename variables
- formatting
> GMG: code cleanup

- source/simulator/solver_schemes.cc
- tests/free_surface_iterated_IMPES/screen-output
- tests/free_surface_iterated_stokes/screen-output
- tests/geoid_freesurface/screen-output
- tests/particle_fast_evaluate_many_compositions/screen-output
- tests/particle_fast_evaluate_multiple_compositions/screen-output
Force rebuilding the preconditioner for problems with constant viscosity that have a free surface.
Fixes #5071
> free surface rebuild preconditioner

- source/postprocess/spherical_velocity_statistics.cc
Since there are spherical geometries as well, it makes sense to me to allow them.
> allow chunk and two merged chunks for spherical velocity statistics.

- source/boundary_traction/initial_lithostatic_pressure.cc
While adapting the plugin, I noticed some redundancy that this PR removes. Tests should not change.
> Simplify the initial lithostatic pressure boundary traction plugin

- source/boundary_traction/initial_lithostatic_pressure.cc
> Remove 0 from parameter name

- CMakeLists.txt
> DebugRelease build: enable precompiled headers

- doc/manual/citing_aspect.bib
This adds publications using ASPECT for February AND also adds a bunch of missed publications. Google scholar does not seem to be doing a good job in finding mentions in AGU publications. And probably does not search supplementary materials.
Also my first foray into visual studio code.  
Let's see what the tester finds ...
> Adds publications for February

- tests/grain_size_growth.prm
I noticed that some units were wrong in the description of one of the tests. This PR fixes this.
> improve documentation

- doc/modules/changes/20220511_haoyuan
- source/material_model/utilities.cc
This rewords some documentation introduced in #4591. Just minor fixes and I didnt want to delay the other PR further.
> Reword some documentation

- doc/sphinx/user/intro.md
Added our new grant number to the list of grants that ASPECT activities are supported by.  
Updated the callout box to the new/current grant number.
> Update grant numbers in intro

- source/simulator/initial_conditions.cc
If an initial condition plugin throws an exception it is usually impossible to recover, because other plugins will attempt MPI communication that the throwing plugin cannot participate in. In a case @alarshi and I were investigating the WorldBuilder would throw an exception that would lead to an MPI deadlock only on very highly refined models (it depends on the resolution).
This PR implements the same solution we already use for postprocessors and particle interpolators to catch the exception, print a useful message and then call MPI_Abort to avoid a deadlock. 
I also wonder if we should somehow generalize this pattern for all plugin calls (not sure how though).
@tjhei: This is what we talked about today.
> MPI_Abort on exception in initial condition

- cookbooks/composition-reaction/doc/composition-reaction.md
- cookbooks/composition_passive/doc/composition_passive.md
This PR just fixes some documentation for two of our cookbooks. It seems not all cookbooks have been completely converted. I will see if I can get through the remaining warnings when generating the documentation over the next weeks. Otherwise these are also nice starter projects for the hackathon.
> Improve documentation of composition-passive and composition-reaction cookbooks

- source/main.cc
> Describe better what happens with QuietException and why.

- include/aspect/initial_temperature/spherical_shell.h
The current version fails to compile on my system with a newer compiler.
> Fix the name of a constructor.

- source/simulator/checkpoint_restart.cc
- source/simulator/core.cc
C++11 allows to simplify things a bit.
> Simplify some code surrounding the use of SolutionTransfer.

- source/postprocess/visualization.cc
> Remove unused option

- source/postprocess/particles.cc
> Removed a deprecated option

- .github/workflows/docker.yml
This puts the description of @gassmoeller in #4969 into a comment.
Closes #4969.
> Document the purpose of a command.

- include/aspect/simulator_signals.h
- source/simulator/simulator_signals.cc
> [2.5] take over extern template #5188

- source/particle/property/integrated_strain.cc
- source/particle/property/integrated_strain_invariant.cc
- source/particle/property/strain_rate.cc
- source/particle/property/viscoplastic_strain_invariants.cc
cherry-pick of #5208
FYI @bangerth
> [2.5] particle ref bug

- doc/manual/citing_aspect.bib
Found a few things to cleanup and one new reference when comparing lists between websites.
> A little clean up and one addition found while reviewing

- source/material_model/utilities.cc
I'm going to use this for demonstrating debugging in a minute. But it's probably useful independently anyway.
> Add a bunch of index checks.

- contrib/utilities/compile_and_update_tests.sh
update a piece of documentation
> Update the name of the official tester image in documentation

- contrib/world_builder/include/delaunator-cpp/delaunator.hpp
- contrib/world_builder/source/world_builder/objects/bezier_curve.cc
- contrib/world_builder/source/world_builder/utilities.cc
- contrib/world_builder/source/world_builder/world.cc
> [2.5] wb warnings

- benchmarks/solubility/doc/solubility.md
- contrib/release/release-tasklist.md
I realized I submitted #5176 before being done with all points in the list. Convert the remaining points to markdown. Also fix one file include in a benchmark.
> Fix some remaining release tasks.

- include/aspect/particle/world.h
- source/particle/world.cc
> [2.5] take over #5251: fix for latest deal.II master: support cell_weight

- doc/modules/changes/20230709_mfraters
- include/aspect/particle/property/crystal_preferred_orientation.h
- include/aspect/postprocess/crystal_preferred_orientation.h
- include/aspect/utilities.h
- source/postprocess/crystal_preferred_orientation.cc
- source/utilities.cc
- unit_tests/utilities.cc
This pull request adds a post-processor to output relevant CPO information.
This implementation is based on #4978, so this should not be merged until that one is. It is ready for review though. 
(point 3 in #3885)
> Add CPO main postprocessor

- benchmarks/solcx/compositional_fields/solcx_compositional_fields.h
- cookbooks/check.mk
> [2.5] take over #5270: more cookbook/benchmark fixes

- doc/modules/changes/20230712_gassmoeller
Forgot to add a changelog entry for #5268.
> Add changelog entry for 5268

- cookbooks/inclusions/doc/inclusions.md
> Mark up two variables as math.

- source/geometry_model/box.cc
- source/geometry_model/chunk.cc
- source/geometry_model/ellipsoidal_chunk.cc
- source/geometry_model/interface.cc
- source/geometry_model/sphere.cc
- source/geometry_model/spherical_shell.cc
- source/geometry_model/two_merged_boxes.cc
- source/geometry_model/two_merged_chunks.cc
> Use a simpler way to return a map.

- benchmarks/solitary_wave/doc/solitary_wave.prm
- benchmarks/solitary_wave/notes.txt
- cookbooks/free_surface/free_surface.prm
- include/aspect/material_model/melt_global.h
- include/aspect/material_model/melt_simple.h
- source/material_model/melt_boukare.cc
- source/material_model/melt_global.cc
- source/material_model/melt_simple.cc
- source/material_model/utilities.cc
- tests/melt_visco_plastic.cc
The former is American English.
> Prefer 'modeling' over 'modelling'.

- benchmarks/yamauchi_takei_2016_anelasticity/doc/yamauchi_takei_2016_anelasticity.md
> Fix Britishism

- contrib/world_builder/CHANGELOG.md
- doc/modules/to-2.4.0.h
- tests/drucker_prager_derivatives_2d.cc
- tests/drucker_prager_derivatives_2d/screen-output
- tests/drucker_prager_derivatives_3d.cc
- tests/drucker_prager_derivatives_3d/screen-output
- tests/simple_nonlinear.cc
- tests/simple_nonlinear/screen-output
- tests/spiegelman_material.cc
- tests/spiegelman_material/screen-output
- tests/visco_plastic_derivatives_2d.cc
- tests/visco_plastic_derivatives_3d.cc
- tests/visco_plastic_derivatives_3d/screen-output
> "where not" -> "were not"

- CONTRIBUTING.md
This is currently only in the wiki, but I think that this should also be in the manual (through contributing.md, see #5295)
> Add astyle installation instruction

- doc/modules/changes/20230713_chameerasilva
Follow up for #5220 extending the changelog entry.
> Extend changelog entry

- include/aspect/simulator.h
- source/simulator/core.cc
- source/simulator/solver_schemes.cc
change `solve_single_advection_iterated_newton_stokes` to `solve_single_advection_and_iterated_newton_stokes` to conform to the other names.
> fix name Newton Stokes function

- source/simulator/solver_schemes.cc
Really not important, but I had it sitting around all day long and might as well flush it out of my queue.
> Use brace initialization of a pair.

- doc/manual/citing_aspect.bib
End of the month update for 3 new publications that cite ASPECT.
> Adding more publications for July 2023

- contrib/release/bump_version.sh
global.h no longer contains version information
> release script: update

- source/material_model/steinberger.cc
This PR now uses `MaterialUtilities::compute_only_composition_fractions` in steinberger.
> Modernise steinberger

- citing.html
- database.js
- update database from make_cite_html script
- add 2.5.0 option
> [www]: citing for 2.5

- Jenkinsfile.osx
- replace master by main
- add exceptions for maintainers
> Jenkins OSX: run on main branch

- source/simulator/helper_functions.cc
Minor refactoring in the function `interpolate_onto_velocity_system`.
> Remove duplicated assert

- source/simulator/nullspace.cc
Some refactoring inside `remove_net_linear_momentum`. Note that the same changes already happened in `compute_net_angular_momentum`, we just forgot to make the same improvements to the linear momentum function.
> Refactor remove_net_linear_momentum

- .readthedocs.yaml
Not sure how it looks like at the moment, but I think it doesn't hurt to build it online as well.
> sphinx doc: enable pdf

- doc/manual/citing_aspect.bib
Updates to citing_aspect.bib for new publications in August.
> Adds publications for August

- README.md
- doc/modules/changes/20230917_tjhei
- doc/modules/main.h
- doc/sphinx/user/intro.md
- source/global.cc
> ASPECT rename

- ReadMe.html
- index.html
Same as #5392, but for the website, also updating the links to the Readme.md.
> Update ASPECT name

- source/mesh_deformation/interface.cc
- source/simulator/stokes_matrix_free.cc
This fixes at least one of the failing tests in https://github.com/geodynamics/aspect/pull/5398. Let's see how many other tests fail, and then I can address those as well.
/rebuild
> Fix some wrong index sets.

- source/initial_composition/entropy_table_lookup.cc
Just a few details I saw when reviewing #5360.
> Minor updates to PR 5360.

- source/simulator/solver.cc
While working on the failing tests in #5398; see also #5405.
Fixes #5406.
> Make a loop over indices more efficient.

- source/simulator/solver.cc
While working on the failing tests in #5398; see also #5405.
> Clean up some details in solve_stokes().

- benchmarks/annulus/plugin/annulus.cc
- benchmarks/burstedde/burstedde.cc
- benchmarks/doneahuerta/doneahuerta.cc
- benchmarks/hollow_sphere/hollow_sphere.cc
- benchmarks/inclusion/inclusion.h
- benchmarks/layeredflow/layeredflow.cc
- benchmarks/solcx/solcx.h
- benchmarks/solitary_wave/solitary_wave.cc
- benchmarks/time_dependent_annulus/plugin/time_dependent_annulus.h
- benchmarks/viscosity_grooves/viscosity_grooves.cc
- source/material_model/grain_size.cc
- source/material_model/rheology/elasticity.cc
- source/material_model/rheology/strain_dependent.cc
- source/mesh_deformation/interface.cc
- source/postprocess/visualization/ISA_rotation_timescale.cc
- source/postprocess/visualization/grain_lag_angle.cc
- source/simulator/introspection.cc
- source/volume_of_fluid/handler.cc
There are better C++ ways these days.
> Avoid bare 'new' operator. Use std::make_unique/shared.

- source/simulator/helper_functions.cc
- source/simulator/solver.cc
- source/simulator/stokes_matrix_free.cc
I *think* that this addresses the remaining two test failures in #5398, following #5405. This fixes #5412. Let's see what the tester says.
I actually quite like this solution. This thing with "views" is how this is supposed to work I believe.
> Use a constraints object of the right size.

- include/aspect/simulator_signals.h
Seen while looking at the stuff mentioned in #5431.
> Augment the documentation of a signal.

- source/geometry_model/interface.cc
As commented on in #4089 this code can be updated using the "new" deal.II function.
> Clean up a string conversion

- contrib/install/local.cfg
- doc/sphinx/user/install/local-installation/using-candi.md
> candi local.cfg: add netcdf

- contrib/utilities/jsontomarkdown.py
- source/material_model/drucker_prager.cc
- source/material_model/melt_simple.cc
- source/mesh_deformation/free_surface.cc
- source/mesh_deformation/interface.cc
- source/simulator/newton.cc
- source/simulator/parameters.cc
This PR fixes documentation issue #5414 to use sphinx commands for citation.
> fix cite using sphinx command.

- contrib/docker/docker_tacc/Dockerfile
> tacc-docker: add netcdf and sundials

- include/aspect/material_model/depth_dependent.h
- source/material_model/depth_dependent.cc
Improvements to the depth dependent material model that I noticed while reviewing #5399. Purely refactoring, should not contain any functional changes.
> Simplify and update depth dependent material model.

- source/initial_temperature/continental_geotherm.cc
- source/material_model/rheology/strain_dependent.cc
- source/material_model/utilities.cc
- source/particle/property/crystal_preferred_orientation.cc
- source/postprocess/crystal_preferred_orientation.cc
- source/postprocess/particles.cc
- source/postprocess/visualization.cc
- source/simulator/core.cc
- source/simulator/solver.cc
- source/volume_of_fluid/handler.cc
- source/volume_of_fluid/solver.cc
- tests/solidus_initial_conditions.cc
This is like dealii/dealii#16037, but for ASPECT to make the tester compile with deal.II dev.
> Add semicolon to asserts that were missing it.

- CMakeLists.txt
- contrib/fastscape/fastscape_rewrite_VTK_with_time.py
- cookbooks/check.mk
- cookbooks/fastscape_eroding_box/doc/README.md
- cookbooks/fastscape_eroding_box/fastscape_eroding_box.prm
- doc/modules/changes/20230301_neuharth
- doc/sphinx/user/cookbooks/simple-setups.md
- include/aspect/config.h.in
- include/aspect/geometry_model/box.h
- include/aspect/mesh_deformation/fastscape.h
- include/aspect/parameters.h
- include/aspect/simulator_access.h
- source/geometry_model/box.cc
- source/material_model/rheology/visco_plastic.cc
- source/mesh_deformation/fastscape.cc
- source/simulator/parameters.cc
- source/simulator/simulator_access.cc
This is an initial pull request for review and discussion of the code. In the future, I plan to squash some of the commits and split the pull request into a few different pieces to hopefully make it easier to merge and a bit less messy. @anne-glerum @naliboff
> Fastscape coupling

- source/mesh_deformation/free_surface.cc
- source/mesh_deformation/interface.cc
- source/simulator/melt.cc
- source/simulator/nullspace.cc
- source/simulator/stokes_matrix_free.cc
The old functions are already deprecated, so at some point or other these changes will have to be made anyway. Make them now that I think of it.
> Use the new interface of AffineConstraints.

- source/geometry_model/spherical_shell.cc
Removing 7 lines of code feels like a win this evening :-)
> Use overloads instead of template specializations.

- source/simulator/stokes_matrix_free.cc
The form we use here is allowed, but not what we use everywhere else. Try to be consistent.
> Use the usual form of lambda functions.

- contrib/docker/tester/local.cfg
> add netcdf to tester docker image

- include/aspect/compat.h
- source/compat.cc
- source/geometry_model/spherical_shell.cc
WIP for now, just wanting to see whether this step will pass the CI checks.
> Create a manifold for the spherical shell that can accommodate an initial topography.

- Jenkinsfile
> Jenkins: enable netcdf

- include/aspect/geometry_model/spherical_shell.h
Nothing of consequence, just the usual stuff I find while looking around code.
> Make a variable 'unsigned'.

- source/geometry_model/spherical_shell.cc
The other geometry models have the corresponding assertion in this place as well, so add it here too. In reference to #5421.
> Add an assertion.

- source/simulator/assembly.cc
I think in the function set_advection_assemblers, a loop and a find over the compositional fields were performed while looping over all fields. I've pulled out one of them and removed the second loop, to avoid setting parameters multiple times. It should just simplify the code, not change the results of the code. 
I also put in one comment, which is actually a question for this PR. It can be removed once answered.
> Remove looping over fields in loop over fields in advection assembly

- include/aspect/boundary_traction/interface.h
Of course, they are also not used.
> Remove declarations of functions that are not implemented.

- doc/manual/citing_aspect.bib
This fixes the remaining comment in #5544, plus an issue of what is a last and what is a first name.
> Fix a bibtex entry.

- source/mesh_deformation/interface.cc
> simplify ghosting of MGTransfer

- include/aspect/geometry_model/spherical_shell.h
- source/geometry_model/spherical_shell.cc
Another necessary step towards #5421 .
> Get most of what's needed for spherical topography in place.

- include/aspect/utilities.h
- source/geometry_model/chunk.cc
Prompted by this exchange: https://github.com/geodynamics/aspect/pull/5560#pullrequestreview-1857522695
> Better document conventions around spherical coordinates.

- doc/modules/changes/20240216_bangerth
#5572 should have included a changelog entry, but I forgot. This adds it.
Related to #5421.
> Add a changelog.

- source/material_model/entropy_model.cc
This pull request fixes a bug in the declaration section of the entropy model. The current entropy model can only handle one cohesion and frictional angle input.
> fix-declarations

- .github/workflows/typos.yml
- .typos.toml
- CONTRIBUTING.md
- benchmarks/buiter_et_al_2016_jsg/exp_1.prm
- benchmarks/shear_bands/plot_hist_and_porosity.py
- cookbooks/grain_size_ridge/doc/grain_size_ridge.md
- cookbooks/inner_core_convection/doc/inner_core_traction.part.1.prm
- cookbooks/inner_core_convection/inner_core_traction.prm
- cookbooks/steinberger/steinberger.prm
- cookbooks/tomography_based_plate_motions/plugins/tomography_based_plate_motions.cc
- cookbooks/tomography_based_plate_motions/plugins/tomography_based_plate_motions.h
- data/material-model/steinberger/visc.m
- doc/modules/changes/20230718_lhy11009
- doc/modules/to-2.5.0.h
- include/aspect/material_model/utilities.h
- include/aspect/mesh_deformation/fastscape.h
- include/aspect/postprocess/crystal_preferred_orientation.h
- include/aspect/simulator.h
- source/mesh_deformation/fastscape.cc
- source/postprocess/crystal_preferred_orientation.cc
- tests/box_simple_log_viscosity_depth_average.prm
- tests/drucker_prager_derivatives_2d.cc
- tests/drucker_prager_derivatives_3d.cc
- tests/entropy_initial_lookup_wb.wb
- tests/particle_periodic_quarter_shell.prm
- tests/particle_periodic_quarter_shell_2.prm
- tests/traction_multiple_model.prm
- tests/vep_chemical_compositions.prm
- tests/visco_plastic_peierls_mei_viscosity_approx.prm
I have added this to the world builder, and it is very helpful there. I thought it might be useful here as well. The tester is very quick, so it should not take up a lot of resources.
> Add typos spell checker.

- doc/modules/changes/20240321_bangerth
> Add a changelog entry for the global topography thing.

- source/simulator/nullspace.cc
While working on something else I found these unnecessary include directives.
> Remove unused include statements

- doc/manual/citing_aspect.bib
Getting caught up on 2024 publications. 3 new ones to add.
Please feel free to edit.
> Adding new publications for 2024

- source/simulator/stokes_matrix_free.cc
@anne-glerum reported a segfault error inside the GMG solver when the Newton terms were enabled. 
I think this patch may fix the reason, but was unable to provoke the error locally on my system (Anne is testing right now). Independent of the result of that test, I think this patch fixes a bug, since `std::vector` does not respect the alignment necessary for `VectorizedArray`. @tjhei does this make sense?
This was introduced in #5580, and was very hard to spot, because it only leads to problems on some runs/vectorization options (whenever the memory allocation is not aligned).
Stacktrace:
```
[bcn1332:145338] *** Process received signal ***
[bcn1332:145338] Signal: Segmentation fault (11)
[bcn1332:145338] Signal code:  (128)
[bcn1332:145338] Failing at address: (nil)
[bcn1332:145338] [ 0] …
```
> Fix alignment problem for VectorizedArray

- contrib/docker/tester/Dockerfile
> docker: fix path to cmake

- source/simulator/core.cc
- source/simulator/stokes_matrix_free.cc
reinit() already calls clear()
> remove redundant AffineConstraints::clear

- source/mesh_deformation/free_surface.cc
- source/simulator/stokes_matrix_free.cc
This PR addresses  #5654. 
@tjhei : I could not find any instances in `core.cc` to change for dealii.9.6 :(
> Add directives for newer dealii in affineconstraints.

- source/utilities.cc
> fix WGS84 warning

- doc/manual/citing_aspect.bib
Getting caught up on adding ASPECT publications.  
Adding 3 new ones!
> Publication catch-up

- doc/modules/changes/20240529_myhill
- include/aspect/material_model/diffusion_dislocation.h
- include/aspect/material_model/rheology/diffusion_dislocation.h
- source/material_model/diffusion_dislocation.cc
- source/material_model/rheology/diffusion_dislocation.cc
This PR creates a new Rheology model called DiffusionDislocation. The rheological calculations are removed from the material model of the same name. The existing tests are sufficient.
> refactored diffusion-dislocation

- include/aspect/utilities.h
- source/utilities.cc
This is a follow-up to #5580 and #5555. It simply corrects and improves the state of the documentation.
@YiminJin FYI.
> Better (and correctly) document the SPD correction factor.

- source/particle/integrator/rk_4.cc
@gassmoeller I tried to look at how easy it would be to re-write this code using Butcher tableaux, and you're right that it's not *entirely* obvious, though probably feasible if we wanted.
> Make the four stages of the RK4 integrator look more similar.

- doc/manual/citing_aspect.bib
The bibtex parser in R Studio complained about a few entries. This cleans up the missing information and the incorrect field.
> bibtex cleanup

- .vscode/extensions.json
This will prompt the user to install any of these extensions when opening the project for the first time.
> add recommended vscode extensions

- .vscode/cmake-variants.yaml
- .vscode/launch.json
- add build variants for DebugRelease, Debug, Release
- add a launch configuration for debugging
> additional vscode settings

- CMakeLists.txt
We made a similar change in deal.II a while ago. The all UPPERCASE situation is just too hard to read.
> Convert cmake commands to lower-case.

- include/aspect/geometry_model/spherical_shell.h
- source/geometry_model/spherical_shell.cc
As discussed this morning. I think this comment adequately describes what we want to happen.
I'll note that I think there is still something wrong, but will address this in a separate PR.
> Better document what a spherical shell with topography does with normal vectors.

- cookbooks/allken_et_al_2012_rift_interaction/doc/allken.md
- cookbooks/burnman/doc/burnman.md
- cookbooks/fastscape_eroding_box/doc/README.md
- cookbooks/finite_strain/doc/finite_strain.md
- cookbooks/free_surface/doc/free_surface.md
- cookbooks/free_surface_with_crust/doc/free_surface_with_crust.md
- cookbooks/geomio/doc/geomio.md
- cookbooks/gplates/doc/gplates.md
- cookbooks/initial-condition-S20RTS/doc/initial-condition-S20RTS.md
- cookbooks/morency_doin_2004/doc/morency_doin_2004.md
- cookbooks/muparser_temperature_example/doc/muparser_temperature_example.md
- cookbooks/prescribed_velocity/doc/prescribed_velocity.md
- cookbooks/prescribed_velocity_ascii_data/doc/prescribed_velocity_ascii_data.md
- cookbooks/shell_simple_2d_smoothing/doc/shell_simple_2d_smoothing.md
- cookbooks/tomography_based_plate_motions/doc/tomography_based_plate_motions.md
- cookbooks/vankeken_subduction/doc/vankeken_subduction.md
Seen while commenting on #5714.
> Use complete sentences.

- source/simulator/solver.cc
- tests/stokes_solver_fail/screen-output
- tests/stokes_solver_fail_cheap/screen-output
This PR factors out the operator approximating S^{-1} from BlockSchurPreconditioner in order to enable the use of other approximations for the inverse schur complement in the future.
> Refactor schur complement inverse operator

- contrib/python/scripts/pyvista_2D_annulus_example.py
This fixes some minor text issues but mostly @naliboff 's name. It is a follow-up to #5711.
@KerrMadeleine FYI.
> Fix some text.

- source/simulator/solver.cc
follow up to #5687:
- move down
- add comments
- move implementation outside class declaration
- rename variables
- reformat comments
> code cleanup schur complement solver

- CMakeLists.txt
fixes #5728
@bangerth @gassmoeller Can one of you think of a better way to handle this?
> skip unity build for two files

- source/simulator/solver.cc
- tests/stokes_solver_fail/screen-output
- tests/stokes_solver_fail_cheap/screen-output
> factor out AInvOperator in Stokes solver

- include/aspect/material_model/rheology/frank_kamenetskii.h
The FK header file now has the correct formula and references a paper with the FK formulation.
Fixes #5730.
> Updated documentation in FK header file

- include/aspect/boundary_composition/interface.h
- include/aspect/boundary_temperature/interface.h
- include/aspect/boundary_velocity/interface.h
- include/aspect/heating_model/interface.h
- include/aspect/initial_composition/interface.h
- include/aspect/initial_temperature/interface.h
- include/aspect/mesh_deformation/interface.h
- include/aspect/mesh_refinement/interface.h
- include/aspect/particle/property/interface.h
- include/aspect/postprocess/interface.h
> grammar: casted -> cast

- doc/modules/changes/20240602_gassmoeller
I forgot to add a changelog entry to #5662.
> Add changelog entry

- source/postprocess/visualization.cc
This silently works around the error in #5727. 
@anne-glerum FYI
> Work around an issue with outputting higher order data on lines.

- include/aspect/introspection.h
- include/aspect/simulator.h
- source/simulator/assembly.cc
- source/simulator/helper_functions.cc
- source/simulator/introspection.cc
- source/simulator/solver_schemes.cc
- unit_tests/introspection.cc
> Compositional field matrix destination

- include/aspect/simulator_signals.h
- source/simulator/helper_functions.cc
- tests/pressure_scaling_signal.cc
- tests/pressure_scaling_signal.prm
- tests/pressure_scaling_signal/screen-output
- tests/pressure_scaling_signal/statistics
> add signal to modify pressure scaling

- benchmarks/shear_bands/shear_bands.cc
- benchmarks/solitary_wave/solitary_wave.cc
- benchmarks/tangurnis/code/tangurnis.cc
- benchmarks/tosi_et_al_2015_gcubed/tosi.cc
- cookbooks/prescribed_velocity/prescribed_velocity.cc
- source/mesh_deformation/interface.cc
- source/postprocess/entropy_viscosity_statistics.cc
- source/postprocess/visualization/grain_lag_angle.cc
> Simplify cell loops

- benchmarks/nsinker/nsinker.cc
> nsinker: set pressure scaling to 1.0

- source/mesh_refinement/composition_threshold.cc
No need to create an FEValues...
part of #5748.
> simplify CompositionThreshold mesh refinement

- doc/sphinx/user/run-aspect/parameters-overview/muparser-format.md
This PR improves the documentation of the Function expression, adding a link to the muparser documentation and a python binding for muparser.
> add to muparser docs

- data/mesh-deformation/ascii-data/spherical_shell_2d.txt
- data/test/gmg/mesh_deformation_spherical_shell_2d.txt
- tests/mesh_deformation_gmg_2d_spherical_shell.prm
- tests/mesh_deformation_gmg_2d_spherical_shell/screen-output
Minor improvements for #5731. I moved the data file into a folder that more closely follows our usual folder layout.
> Move data file to better folder.

- source/simulator/assembly.cc
Follow up to #5528, removing a TODO that was fixed in that PR.
> Remove resolved TODO

- source/material_model/rheology/drucker_prager.cc
* [ x] I have read the guidelines in our [CONTRIBUTING.md](../blob/main/CONTRIBUTING.md) document.
* [x ] I have followed the [instructions for indenting my code](../blob/main/CONTRIBUTING.md#making-aspect-better).
> adding_documentation_to_DP_rheology

- include/aspect/material_model/rheology/diffusion_creep.h
- include/aspect/material_model/rheology/dislocation_creep.h
- include/aspect/material_model/rheology/drucker_prager.h
- include/aspect/material_model/rheology/peierls_creep.h
- source/material_model/rheology/composite_visco_plastic.cc
- source/material_model/rheology/diffusion_creep.cc
- source/material_model/rheology/dislocation_creep.cc
- source/material_model/rheology/drucker_prager.cc
- source/material_model/rheology/peierls_creep.cc
> fix uninitialized variables

- doc/sphinx/user/run-aspect/parameters-overview/muparser-format.md
Updates the pymuparser description to account for the additional function parser.
> updated pymuparser description

- doc/modules/changes/20240605_thieulot
> add changelog of merged cookbook

- doc/sphinx/references.bib
> adding doi's to references_bib

- include/aspect/postprocess/particles.h
- include/aspect/postprocess/visualization.h
- source/postprocess/particles.cc
- source/postprocess/visualization.cc
> Avoid the word 'master' where possible.

- doc/modules/changes/20240605_tjhei
> changelog for removing make test

- source/mesh_refinement/compaction_length.cc
see https://github.com/geodynamics/aspect/pull/5802#discussion_r1628761521
> simplify compaction length refinement

- tests/grain_size_growth_one_cell_particles.prm
- tests/grain_size_growth_one_cell_particles/screen-output
- tests/grain_size_growth_one_cell_particles/statistics
> Add a simple test for grain size growth with particles

- source/simulator/entropy_viscosity.cc
> simplify code

- doc/modules/changes/20240606_mfraters
Changelog entry for #5116 and #5784
> Add changelog entry for CPO elastic symmetry decomposition.

- source/volume_of_fluid/handler.cc
Follow-up to #5837. @tjhei voices his approval verbally.
> Simplify code.

- include/aspect/utilities.h
- source/utilities.cc
- unit_tests/utilities.cc
> string_to_unsigned_int

- include/aspect/boundary_composition/interface.h
- include/aspect/boundary_temperature/interface.h
- include/aspect/boundary_traction/interface.h
- include/aspect/boundary_velocity/interface.h
- include/aspect/heating_model/interface.h
- include/aspect/initial_composition/interface.h
- include/aspect/initial_temperature/interface.h
- include/aspect/mesh_refinement/interface.h
- include/aspect/postprocess/interface.h
- include/aspect/termination_criteria/interface.h
Seen while looking at something related to #5833 .
> No need to fully qualify class SimulatorAccess.

- cookbooks/kinematically_driven_subduction_2d/CMakeLists.txt
- cookbooks/kinematically_driven_subduction_2d/composition_trms_statistics.cc
- cookbooks/kinematically_driven_subduction_2d/composition_trms_statistics.h
- cookbooks/kinematically_driven_subduction_2d/isotherm_depth.h
- cookbooks/kinematically_driven_subduction_2d/trench_location.h
Follow up with minor improvements to #5115.
> Remove double underscores and template text

- unit_tests/utilities.cc
> fix bug in unit_tests/utilities.cc

- cookbooks/kinematically_driven_subduction_2d/doc/Case2a_temperatures.prm
Similar background as #5878, found while working on #5394.
> Do not capitalize subsection

- benchmarks/check.mk
- cookbooks/check.mk
> check.mk: do not run .part.prm files

- benchmarks/nsinker/nsinker_bfbt.prm
- doc/modules/changes/20240606_hoang
- include/aspect/parameters.h
- include/aspect/simulator.h
- include/aspect/simulator/assemblers/interface.h
- source/simulator/assemblers/interface.cc
- source/simulator/assemblers/stokes.cc
- source/simulator/assembly.cc
- source/simulator/core.cc
- source/simulator/parameters.cc
- source/simulator/solver.cc
- tests/nsinker_bfbt.cc
- tests/nsinker_bfbt.prm
- tests/nsinker_bfbt/screen-output
- tests/nsinker_bfbt/statistics
- tests/stokes_solver_fail/screen-output
- tests/stokes_solver_fail_cheap/screen-output
This adds the weighted BFBT preconditioner to ASPECT (currently work in progress).
> Implement BFBT preconditioner

- doc/sphinx/user/extending/benchmarking-run-time.md
Follow-up to #5868 that mentions other ways to measure performance.
> Mention other performance measurement options

- source/adiabatic_conditions/compute_entropy_profile.cc
- source/adiabatic_conditions/compute_profile.cc
- source/initial_temperature/adiabatic.cc
- source/mesh_refinement/slope.cc
> use static_cast

- include/aspect/introspection.h
- source/simulator/introspection.cc
Small update to #5802 to avoid unnecessary copies.
> Return const reference

- contrib/world_builder/CMakeLists.txt
> GWB: Only set -fcolor-diagnostics for cpp compilers

- doc/modules/changes/20240615_mfraters
> Add changelog entry for moving the particle plugin declarations.

- include/aspect/particle/world.h
- source/particle/world.cc
- source/simulator/core.cc
Follow up to #5916. This pull request adds the basic infrastucture to allow for multiple particle world.
> Emplace infrastructure for multiple particle worlds

- include/aspect/boundary_composition/interface.h
- include/aspect/boundary_temperature/interface.h
- include/aspect/initial_composition/interface.h
- include/aspect/initial_temperature/interface.h
- include/aspect/mesh_refinement/interface.h
- include/aspect/particle/property/interface.h
- include/aspect/termination_criteria/interface.h
- include/aspect/time_stepping/interface.h
- source/boundary_composition/interface.cc
- source/boundary_temperature/interface.cc
- source/initial_composition/interface.cc
- source/initial_temperature/interface.cc
- source/mesh_refinement/interface.cc
- source/particle/property/interface.cc
- source/termination_criteria/interface.cc
- source/time_stepping/interface.cc
- tests/find_boundary_composition_model_fail_1/screen-output
- tests/find_mesh_refinement_fail_1/screen-output
> Convert a number of other manager classes to the manager base class.

- .vscode/extensions.json
The new version of https://gitlab.com/vscode_extension/vscode-aspect#visual-studio-extension-for-aspect-parameter-script works quite well...
> recommend ASPECT vscode extension

- CMakeLists.txt
I *think* that's what @tjhei wanted me to do for #5938.
Fixes #5938.
> Name executables aspect-debug, aspect-release.

- source/particle/interface.cc
It turns out #5952 did not work, so let me try again.
> actually fix clang include error

- include/aspect/boundary_composition/interface.h
- include/aspect/boundary_temperature/interface.h
- include/aspect/heating_model/interface.h
- include/aspect/initial_composition/interface.h
- include/aspect/initial_temperature/interface.h
- source/initial_temperature/continental_geotherm.cc
- source/postprocess/heating_statistics.cc
- source/postprocess/visualization/heating.cc
- source/simulator/simulator_access.cc
> Deprecate Manager functions now available through the base class.

- source/boundary_composition/interface.cc
- source/boundary_temperature/interface.cc
- source/heating_model/interface.cc
- source/initial_composition/interface.cc
- source/initial_temperature/interface.cc
- source/mesh_refinement/interface.cc
- source/postprocess/interface.cc
- source/termination_criteria/interface.cc
- source/time_stepping/interface.cc
While looking at stuff for #1775.
> Use emplace_back() over push_back().

- doc/manual/citing_aspect.bib
Adds 3 recent publications to citing_aspect.bib.
> Adds new publications

- source/boundary_temperature/dynamic_core.cc
Also fix grammar and spelling in comments.
> Make some code marginally easier to read.

- source/material_model/rheology/elasticity.cc
This PR improves the description of the elastic `Stabilization time scale factor` to better reflect the implementation taken from Moresi et al. (2003).
> improved documentation of elastic stabilization factor

- doc/manual/citing_aspect.bib
Recently discovered some missing publications.  
Adds a few by @naliboff. Please review full list online and see if anything else obvious is missing.
> Updates some recently discovered missing publications

- doc/manual/citing_aspect.bib
Quick follow up to #5993, which only:
- removes commas at the end of bibtex entries
- unifies the indentation of the file (no indentation seemed the most common)
- replaces all caps words with lower case letters
> Reference list prettyfication

- source/material_model/rheology/composite_visco_plastic.cc
- tests/composite_viscous_outputs_limited.cc
- tests/composite_viscous_outputs_limited.prm
- tests/composite_viscous_outputs_limited/screen-output
The PR fixes the problem identified by @gassmoeller in #6001. The viscosity limiters for the CompositeViscoPlastic rheology now work as intended.
> fix damper stress calculation

- doc/sphinx/user/run-aspect/debug-mode.md
Our documentation tester is failing in this file. This is an attempt to fix the documentation. Dont merge before the testers are happy.
> Fix documentation tester

- source/simulator/parameters.cc
Based on a discussion on the mailing list.
> Document how many seconds there are in a year.

- CMakeLists.txt
- source/particle/property/interface.cc
Also see https://github.com/dealii/dealii/pull/17485/files
> turn on c++ standard library debug checks

- source/postprocess/visualization/strain_rate.cc
- source/postprocess/visualization/strain_rate_tensor.cc
- source/postprocess/visualization/stress.cc
- source/postprocess/visualization/surface_stress.cc
Based on a question on the forum.
> Document the order of tensor components in output files.

- doc/sphinx/user/install/docker-container/installing-docker.md
Add documentation for pulling older ASPECT docker containers.
closes #6036
> add instructions for downloading older docker containers

- include/aspect/parameters.h
- source/postprocess/particles.cc
- source/simulator/core.cc
- source/simulator/initial_conditions.cc
- source/simulator/parameters.cc
This is a work in progress pull request to resolve #5877. It isn't done yet, but feel free to already take a look at it.
> Add input parameter for multiple particle worlds.

- include/aspect/solution_evaluator.h
- source/solution_evaluator.cc
Since #5963 it is not necessary anymore to split SolutionEvaluator into an abstract base class and a templated derived class. This PR merges `SolutionEvaluator` and `SolutionEvaluatorImplementation` into one class. It also improves the documentation of `DynamicFEPointEvaluation`.
> Simplify solution evaluator class

- doc/sphinx/user/extending/plugin-types/geometry-models.md
- doc/sphinx/user/extending/plugin-types/gravity-models.md
- doc/sphinx/user/extending/plugin-types/heating-models.md
- doc/sphinx/user/extending/plugin-types/initial-conditions.md
It's late. I'll take care of the remaining files in that directory in the coming days.
> Update the documentation of plugins (part 1).

- source/mesh_deformation/fastscape.cc
- source/particle/generator/uniform_box.cc
- source/particle/generator/uniform_radial.cc
- source/simulator/core.cc
- source/simulator/helper_functions.cc
> Qualify round() as std::round().

- cookbooks/crustal_deformation/crustal_model_3D.prm
- cookbooks/future/mantle_setup_restart.prm
- cookbooks/future/mantle_setup_start.prm
- cookbooks/kinematically_driven_subduction_2d/kinematically_driven_subduction_2d_case1.prm
- cookbooks/kinematically_driven_subduction_2d/kinematically_driven_subduction_2d_case2a.prm
- cookbooks/kinematically_driven_subduction_2d/kinematically_driven_subduction_2d_case2b.prm
- cookbooks/tomography_based_plate_motions/2D_slice_with_faults_and_cratons.prm
- tests/crustal_model_3D.prm
- tests/crustal_model_3D/screen-output
- tests/crustal_model_3D/statistics
Some small fixes that were necessary to make the following succeed:
```
cd benchmarks && make -f check.mk BUILD=$BUILDDIR -j4
cd cookbooks && make -f check.mk BUILD=$BUILDDIR -j4
```
Part of the release checklist for 3.0.
One item of note is that for the crustal_model_3D cookbook the default material averaging (`project to Q1 viscosity only`) struggles with the GMG solver. More precisely with every subsequent nonlinear iteration the linear solver requires more iterations until it finally does not converge anymore. The problems go away if I switch to harmonic averaging instead.
AMG with `project to Q1 viscosity only` also has some issues (namely that the nonlinear solver doesnt converge to better than 1e-5), but at least the iteration number for the linear solver stays almost constant …
> Fix cookbooks and benchmarks

- contrib/release/release-tasklist.md
Part 1 of #6082 only containing the update of the release tasklist.
> Update release tasklist

- tests/continental_extension_mixed_compositions_particles.prm
- tests/continental_extension_mixed_compositions_particles/screen-output
This is based on a file @naliboff sent to me.
> add test for mixed compositions and particles

- source/particle/manager.cc
> Fix type mismatch.

- doc/modules/changes/20241022_bangerth
- doc/parameter_view/parameters.xml
- doc/sphinx/parameters/global.md
- doc/sphinx/user/run-aspect/run-faster/file-system-io.md
- doc/sphinx/user/run-aspect/run-faster/index.md
- source/simulator/parameters.cc
This is an attempt at making the use of LFS stripe counts a bit easier. Fixes #6035.
@lhy11009 Could you take a look here and potentially give this a try?
> Allow setting LFS stripe count.

- doc/sphinx/user/extending/plugin-types/velocity-bc.md
In this file, we actually talk about both velocity and traction boundary conditions. Reflect that in the heading.
> Fix a section heading.

- doc/sphinx/user/extending/plugin-types/boundary-heat-flux.md
- doc/sphinx/user/extending/plugin-types/index.md
- include/aspect/boundary_heat_flux/interface.h
- source/simulator/assemblers/advection.cc
This whole plugin system was not previously documented.
While there are do a minor clean-up of the place where this is used.
> Document the heat flux plugin system.

- benchmarks/newton_solver_benchmark_set/spiegelman_et_al_2016/drucker_prager_compositions.cc
- tests/time_dependent_temperature_bc.cc
Just a few typos I saw while working on #6160.
> Fix double underscores and typos

- cookbooks/mantle_convection_with_continents_in_annulus/doc/mantle_convection_in_annulus.md
Cherry-pick #6155 to the release branch.
> [3.0] Add warning to cookbook

- contrib/release/release-tasklist.md
Minor change, just in preparation for next years release.
> Update version numbers in release tasklist

- index.html
I was too quick when reviewing #6185, this fixes a typo.
> Fix typo in website news item

- doc/manual/citing_aspect.bib
The first publications for 2025!
Adding a newly discovered older ones.
And fixing one doi error in a previous publication.
> 2025rev january

- .gitignore
Add .DS_store files to the list of ignored git files.
>  Add .DS_Store to the list of ignored files

- doc/manual/citing_aspect.bib
Add publications mentioned in https://github.com/geodynamics/aspect/issues/2831#issuecomment-2651308693.
@ljhwang you may want to add the same on the CIG website?
@tjhei there are a bunch of special characters in the journal name of the last citation, we will have to check how bibtex handles them for the website.
> Add publications to citing_aspect.bib

- doc/manual/citing_aspect.bib
Adds publication as indicated in #2831
> Adds citation Dong et al. #2831

- cookbooks/christensen_yuen_phase_function/christensen_yuen_phase_function.prm
- tests/christensen_yuen_cookbook.prm
- tests/christensen_yuen_cookbook/screen-output
- tests/christensen_yuen_cookbook/statistics
I made an incompatible change in #6214 and now realized there was a cookbook it broke and that I forgot to update. 
I did not notice because this cookbook has no test case, so I added that as well.
> Make christensen yuen cookbook run again

- doc/manual/citing_aspect.bib
Follow-up to #6243 with more recent citations.
> Add two more citations

- include/aspect/particle/property/interface.h
- source/particle/property/interface.cc
- source/simulator/initial_conditions.cc
- tests/particle_multiple_systems_interpolation_fail_1/screen-output
- tests/particle_property_error.prm
- tests/particle_property_error/screen-output
I've been confused by this particular error message so many times, and sometimes it took me a long time to figure out what the problem was. So I thought we should let the user know what exactly is wrong with their input file.
> improve error message for wrong name of mapped particle property

- doc/modules/changes/20250314_jdannberg
- include/aspect/particle/property/composition_reaction.h
- source/particle/property/composition_reaction.cc
- tests/particle_property_composition_reaction.prm
- tests/particle_property_composition_reaction/screen-output
- tests/particle_property_composition_reaction/statistics
- tests/particle_property_composition_reaction_nonlinear.prm
- tests/particle_property_composition_reaction_nonlinear/screen-output
- tests/particle_property_composition_reaction_nonlinear/statistics
> Add composition reaction particle property

- source/material_model/reaction_model/grain_size_evolution.cc
If:
- a material model with grain size evolution is not computing the viscosity -- e.g. because it cannot compute it until the initialization is finished, or because it is not responsible for the viscosity (which is computed by a different material model in the case of composing material models)
- but the material model needs additional material outputs -- e.g. because we use them to compute a prescribed density or temperature in entropy models 
then we have to fill **all** available additional material outputs, because we have no way to distinguish which ones are needed. However, the `ShearHeatingOutputs` can only be computed if the viscosity is available. Because I cannot individually disable the computation of these additional outputs, I have to circumvent this computation to prevent a …
> Avoid a division by zero in grain size evolution in rare cases

- source/main.cc
While debugging a problem reported on the mailing list last week, I realized that we don't get particularly good error messages when failing to read an input file while running in parallel. That's because `ParameterHandler` throws an exception that we catch, print, and then throw something else. We can do better by treating the root process differently, and I think that also makes the code easier to read. In fact, by treating the case of only one process separately, we can improve the situation even more because in that case we do not have to make sure at all that we avoid deadlocks.
> Get better errors when failing to read an input file.

- doc/sphinx/user/install/local-installation/system-prereqs.md
- update to 24.04
- remove some incorrect stuff
> update install prereq documentation

- doc/manual/citing_aspect.bib
> New citation

- tests/spherical_nsinker_bfbt/statistics
> add tests/spherical_nsinker_bfbt/statistics

- doc/manual/citing_aspect.bib
Takes care of the ASPECT publications listed [here](https://github.com/geodynamics/aspect/issues/2831#issuecomment-2883661491).
> Update publications May 2025

- source/mesh_refinement/density.cc
Indented comment in density.cc
> indent comment

- source/postprocess/visualization/seismic_anomalies.cc
> fix a typo in seismic anomaly postprocessor

- source/postprocess/visualization.cc
I have removed the string of parameter names that were depreciated from  line 1301 of the visualization.cc file. We checked for these parameter names on lines 1423-1438 so I removed that process as it referenced names that no longer exist here.
> removed deprecated input options

- source/material_model/equation_of_state/multicomponent_compressible.cc
> Multicomponent compressible Equation of state cleanup

- source/geometry_model/chunk.cc
Following up on a discussion with @alarshi.  I think we convinced ourselves that the previous comments were either misleading or in fact ill-informed.
> Update some commentary in chunk.cc.

- include/aspect/mesh_deformation/fastscape.h
- source/mesh_deformation/fastscape.cc
> Mark input variables of a function as 'const'.

- CMakeLists.txt
No functionality changes, just outputting a bit more information about what is happening.
> Minor clean-up of the FastScape configuration bits.

- source/postprocess/visualization/heating.cc
Replaced an old for loop with a range based on pertaining to the C++11: Use range-based for loops #3774 issue.
Make indent was run.
> implement range-based for loop with index

- source/mesh_deformation/fastscape.cc
@djneu @minerallo Can you take a look at this? Is there a way you could test this in one of your setups where ASPECT runs in parallel, or is there someone I could ask to test this? I don't think there are any FastScape tests in ASPECT.
The key point here is that I am using the following function: https://dealii.org/developer/doxygen/deal.II/classTableBase.html#aefc963afa0c8150ae770eb3de44c587d
> Replicate a data structure across processes using shared memory rather than MPI_Broadcast.

- source/simulator/parameters.cc
Rewriting the list so it will render in the documentation.
> Fix list in Temperature field documentation.

- include/aspect/material_model/rheology/drucker_prager.h
- include/aspect/material_model/rheology/visco_plastic.h
- source/heating_model/shear_heating.cc
- source/material_model/drucker_prager.cc
- source/material_model/entropy_model.cc
- source/material_model/grain_size.cc
- source/material_model/rheology/drucker_prager.cc
- source/material_model/rheology/visco_plastic.cc
- source/material_model/visco_plastic.cc
A WIP to improve the drucker prager rheology interface for future extensions.
> Improve drucker prager interface

- source/particle/interpolator/bilinear_least_squares.cc
Pertaining to issue C++11: Use range-based for loops #3774
Make indent run & build compiled.
> range-based for loop, bilinear_least_squares:81, 208

- source/postprocess/interface.cc
- source/postprocess/visualization.cc
> Convert a couple more loops to range-based format.

- CMakeLists.txt
Really just moving small pieces around and put them into the right places.
> Some more cleanup of CMakeLists.txt.

- include/aspect/boundary_composition/function.h
- include/aspect/boundary_heat_flux/function.h
- include/aspect/boundary_temperature/function.h
- include/aspect/boundary_traction/function.h
- include/aspect/boundary_velocity/function.h
- include/aspect/gravity_model/function.h
- include/aspect/initial_composition/function.h
- include/aspect/initial_temperature/function.h
- source/boundary_composition/function.cc
- source/boundary_heat_flux/function.cc
- source/boundary_temperature/function.cc
- source/boundary_traction/function.cc
- source/boundary_velocity/function.cc
- source/geometry_model/initial_topography_model/function.cc
- source/gravity_model/function.cc
- source/initial_composition/function.cc
- source/initial_temperature/function.cc
@gassmoeller pointed out some formatting issues in the function plugin I added in #6378, so I thought I might as well fix it in the other function plugins as well.
> Some more consistency for function plugins

- .gitignore
* [ x] I have read the guidelines in our [CONTRIBUTING.md](../blob/main/CONTRIBUTING.md) document.
* [ x] I have followed the [instructions for indenting my code](../blob/main/CONTRIBUTING.md#making-aspect-better).
* [ x] I have tested my new feature locally to ensure it is correct.
> ignore all .DS_Store files in all directories

- cmake/AspectConfig.cmake.in
I think this should fix #6450. The description of the problem can be found there.
> Tell plugins where to find WorldBuilder headers.

- source/particle/property/crystal_preferred_orientation.cc
…h with the math operation.
eq4 of Kaminski 2001
is intending to do [outer product](https://en.wikipedia.org/wiki/Outer_product) rather than [cross product](https://en.wikipedia.org/wiki/Cross_product).
I here rename the variable name from `slip_cross_product` to `slip_outer_product` to be consistent with the math operation. Hopefully this helps clarify this part of the code.
> cpo: slip_cross_product --> slip_outer_product

- source/postprocess/sea_level.cc
This can be done more easily with deal.II's facilities.
> Avoid direct MPI calls in the sea level postprocessor.

- CMakeLists.txt
No functional changes. Just working my way through the remaining parts of CMakeLists.txt that I want to clean up.
> Update some commentary in CMakeLists.txt.

- doc/manual/citing_aspect.bib
Using SciX, discovered 2 new publications and 1 that geodynamic.org had but was not listed on aspect.geodynamic.org.
> Found 3 new publications for 2020

- CMakeLists.txt
I think that's more or less the last few changes to sort everything into place.
> Shuffle around the remaining cmake bits not already in their right place.

- source/main.cc
The existing code was unnecessarily complicated. We can with 3 lines what used to take 33.
> Substantially simplify some MPI code.

- doc/sphinx/user/methods/basic-equations/2d-models.md
#6434 points out some inconsistencies in what we actually mean by "2d model". This patch adds a few clarifications to the issue.
@YiminJin @bobmyhill FYI.
> Discuss some more aspects of 2d models.

- doc/manual/citing_aspect.bib
The planetary sciences are still rocking the cool titles.
> Add 4 publications from scix for 2022

- source/particle/integrator/rk_2.cc
> for_loop_range-based_rk_2.cc:83

- source/particle/manager.cc
> for_loop_range-based_manager:436

- source/simulator/parameters.cc
Fix formatting for a few citations in parameters.cc.
> Update citation format for documentation.

- source/particle/integrator/rk_4.cc
> for_loop_range-based_rk_4.cc:93

- source/particle/interpolator/quadratic_least_squares.cc
> for_loop_range-based_quadratic_least.cc:482

- source/mesh_refinement/interface.cc
> for_loop_range-based_interface.cc:64

- source/geometry_model/two_merged_chunks.cc
> Convert one more loop.

- include/aspect/mesh_deformation/fastscape.h
- source/mesh_deformation/fastscape.cc
Duplicate update functions were introduced in fastscape.cc and .h, this pull request merges the two.
> Merge duplicate update functions in fastscape-fortran

- include/aspect/compat.h
I wrote https://github.com/dealii/dealii/pull/18571 because I wanted to use it in the FastScape++ integration (#5323). This PR adds the contents of https://github.com/dealii/dealii/pull/18571 wholesale into the `compat.h` headers.
> Add some compatibility classes.

- doc/modules/changes/20250619_bakerdunn
- include/aspect/postprocess/particle_distribution_statistics.h
- include/aspect/postprocess/particle_pdf.h
- source/postprocess/particle_distribution_statistics.cc
- source/postprocess/particle_pdf.cc
- tests/particle_distribution_statistics.prm
- tests/particle_distribution_statistics/screen-output
- tests/particle_distribution_statistics/statistics
- tests/particle_distribution_statistics_per_particle.prm
- tests/particle_distribution_statistics_per_particle/screen-output
- tests/particle_distribution_statistics_per_particle/statistics
- tests/particle_distribution_statistics_singlecell.prm
- tests/particle_distribution_statistics_singlecell/screen-output
- tests/particle_distribution_statistics_singlecell/statistics
This code isn't properly formatted since I started working on it before getting all the feedback from my previous postprocessor.
The current issue is that when calculating the max and min values of the point density function for every cell, the maximum and minimum are the same. I havent yet been able to figure out why and it might be something obvious. With a bandwith of 1.0 and a uniform function which I am using this is expected but this occurs even with much lower bandwidths and with other kernel functions so I think there must be something wrong in my code.
> Kernel density postprocessor & test case

- doc/manual/citing_aspect.bib
Wow, 7 more publications to add for 2024. 
Can't wait to see the number of ASPECT publications in 2025.
> Adds 7 more publications in 2024 from scix

- include/aspect/material_model/steinberger.h
- source/material_model/steinberger.cc
I realized the viscosity function in the steinberger model had lots of input parameters and was hard to read, so I combined some of them by using material model inputs and outputs.
> Change arguments of viscosity function

- include/aspect/mesh_deformation/fastscape.h
- source/mesh_deformation/fastscape.cc
Follow-up to #6504. @xlia62 FYI.
> Convert an enum to an enum class.

- include/aspect/utilities.h
Not actually anything important, but makes it easier on my scripts.
> Open namespace aspect only once.

- include/aspect/compat.h
- source/compat.cc
> Move compatibility material into namespace aspect.

- source/postprocess/matrix_statistics.cc
Here, we declare a global function (though in an anonymous namespace) where we probably want it in `namespace aspect`.
> Move function into namespace aspect. Also add necessary headers.

- include/aspect/global.h
- source/global.cc
- source/main.cc
That's probably where it should always have been.
> Move print_aspect_header() into namespace aspect.

- source/initial_temperature/world_builder.cc
Also move the `#ifdef` inside the `namespace aspect`.
> Guard only those parts with #ifdef that need to be guarded.

- source/main.cc
There are quite a lot of helper functions in `main.cc` that are all necessary for what we do in `main()`, but not anywhere else in ASPECT. They should all be private in this one file, so move them into an anonymous namespace. This patch is best viewed ignoring whitespace changes.
> Move the global functions in main.cc into an anonymous namespace.

- include/aspect/compat.h
I think this should fix #6582.
> Fix non-matching braces.

- source/mesh_deformation/diffusion.cc
Some of the other files in this directory already do that, just this one doesn't.
> Use the more modern interface to adding constraints.

- source/mesh_deformation/interface.cc
Seen while trying to figure out what's going on for #6589?
> Document a piece of code.

- source/main.cc
> disable floating point exception during finalization

- doc/modules/changes/20250804_heisterbangerth
> Add a changelog entry.

- include/aspect/simulator/solver/block_stokes_preconditioner.h
> small typo fixes
