geodynamics/aspect

doc/sphinx/quickref.md

I changed the reference to heister_aspect_methods2 in pull request https://github.com/geodynamics/aspect/pull/4737 so that reference in quickref will still be compatible now. Replaced the code blocks with md blocks, which is how they should have been formatted in the first place. Added a little blurb about italicized and bold text. And most importantly, put in what we now know about the align environment and operators.

Update quickref: Math directives, text, tidying up

---

cookbooks/burnman/doc/burnman.md
doc/sphinx/quickref.md
doc/sphinx/user/methods/approximate-equations/ala.md
doc/sphinx/user/methods/approximate-equations/ba.md
doc/sphinx/user/methods/approximate-equations/index.md
doc/sphinx/user/methods/approximate-equations/tala.md
doc/sphinx/user/methods/basic-equations/2d-models.md
doc/sphinx/user/methods/basic-equations/adiabatic-heating.md
doc/sphinx/user/methods/basic-equations/bc.md
doc/sphinx/user/methods/basic-equations/index.md
doc/sphinx/user/methods/choosing-a-formulation/adiabatic-profile.md
doc/sphinx/user/methods/coefficients/averaging.md
doc/sphinx/user/methods/coefficients/self-consistency.md
doc/sphinx/user/methods/compositional-fields.md
doc/sphinx/user/methods/constitutive-laws.md
doc/sphinx/user/methods/freesurface/arbitrary-le-implementation.md
doc/sphinx/user/methods/initial-conditions.md
doc/sphinx/user/methods/melt-transport.md
doc/sphinx/user/methods/particles.md
doc/sphinx/user/methods/pressure-static-dyn.md
doc/sphinx/user/run-aspect/run-faster/preconditioner-tolerance.md

The Sphinx `math` directive already includes the functionality of `align`, and while the duplicated math environments do not seem to be a problem for the html generation, it seems to crash the latexpdf build (if we want to build the sphinx documentation as pdf).

Remove duplicate math environments

---

doc/sphinx/user/methods/nullspace-removal.md

Removes extra parens (equations places parens automatically) and fixed the figure referencing.

Documentation: nullspace removal

---

doc/sphinx/conf.py

#4735 broke the edit  button for the documentation, this is an attempt to fix it. Please do not merge until I have checked the live build.

Fix edit button in documentation

---

doc/sphinx/conf.py

The CIG logo has a wrong path at the moment. This was a problem because of different behavior between the local files and the files on readthedocs. Do not merge yet.

Fix CIG logo path

---

doc/sphinx/conf.py

I'm assuming that we use HTML markup for non-ASCII characters?
/rebuild

Avoid latex markup in author list.

---

cookbooks/finite_strain/doc/finite_strain.md
doc/sphinx/user/methods/compositional-fields.md
doc/sphinx/user/methods/dimensionalize/index.md

Some minor edits I noticed: some references weren't correct in early pages of the methods section (which were the first pages I converted, weeks ago, and I didn't have a system down yet)

References fix

---

doc/sphinx/user/methods/nonlinear-stokes-solvers.md

Makes mostly grammatical changes such as placing the punctuation marks on the same line as the equations and a few obvious errors. There is still some fixing that needs to be done on Figures but I will separate it into a separate pull request :).

Documentation: nonlinear Stokes solver

---

doc/modules/changes/20210728_bangerth
include/aspect/structured_data.h
source/structured_data.cc
unit_tests/utilities.cc

This builds on #4083, so the first patch is duplicated from there (but because it's identical, we can still merge this assuming #4083 were merged).
I *believe* this should work, but I don't know for sure and it's late and I'm leaving town tomorrow afternoon until Monday. Let us see what the testers say -- they will at least tell us whether it works with deal.II 9.2. Do any of the testers run 9.3?
The real test would be if (i) we have tests that use ASCII data tables in parallel, and (ii) we check with deal.II 9.3. I don't know whether we have any that satisfy (i). Anyone know for sure?
/rebuild

Enable data sharing across processes

---

doc/sphinx/user/extending/plugin-types/postprocessors.md

Updates a section reference. From the pdf, it looks like this should reference the next section. This should be checked that it was implemented correctly after build.
And, of course, I took the opportunity to add a ",".

Documentation: postprocessors

---

contrib/utilities/jsontomarkdown.py
doc/sphinx/parameters/Adiabatic_20conditions_20model.md
doc/sphinx/parameters/Boundary_20composition_20model.md
doc/sphinx/parameters/Boundary_20fluid_20pressure_20model.md
doc/sphinx/parameters/Boundary_20heat_20flux_20model.md
doc/sphinx/parameters/Boundary_20temperature_20model.md
doc/sphinx/parameters/Boundary_20traction_20model.md
doc/sphinx/parameters/Boundary_20velocity_20model.md
doc/sphinx/parameters/Checkpointing.md
doc/sphinx/parameters/Compositional_20fields.md
doc/sphinx/parameters/Discretization.md
doc/sphinx/parameters/Formulation.md
doc/sphinx/parameters/Geometry_20model.md
doc/sphinx/parameters/Gravity_20model.md
doc/sphinx/parameters/Heating_20model.md
doc/sphinx/parameters/Initial_20composition_20model.md
doc/sphinx/parameters/Initial_20temperature_20model.md
doc/sphinx/parameters/Material_20model.md
doc/sphinx/parameters/Melt_20settings.md
doc/sphinx/parameters/Mesh_20deformation.md
doc/sphinx/parameters/Mesh_20refinement.md
doc/sphinx/parameters/Nullspace_20removal.md
doc/sphinx/parameters/Postprocess.md
doc/sphinx/parameters/Prescribed_20Stokes_20solution.md
doc/sphinx/parameters/Solver_20parameters.md
doc/sphinx/parameters/Temperature_20field.md
doc/sphinx/parameters/Termination_20criteria.md
doc/sphinx/parameters/Time_20stepping.md
doc/sphinx/parameters/Volume_20of_20Fluid.md
doc/sphinx/parameters/global.md

A few improvements to the formatting of the parameter index.
1. Add a label for global parameters (this is referenced already in a few places).
2. Remove the misleading `parameters in section global` heading
3. Rename "global" to "Global parameters"
4. Shorten `Parameters in section ...` to `Subsection: ...`, which is also closer to https://aspect.geodynamics.org/doc/parameter_view/parameters.xml. (It is different from the current manual, but I think it is better).
5. Added spaces around "/" separating subsections to make subsection names more readable.
Let me know in case you want any of them reverted, I think the new format is much easier to read.

Add label to global parameters. Improve formatting.

---

include/aspect/structured_data.h
source/structured_data.cc

Correctly support StructuredData with more than 4 billion data fields. This might not be something easy to encounter as ASCII files would need to be ~20 GB big, but it is not impossible to trigger.

StructuredData: support large indices

---

doc/modules/changes/20220523_jdannberg
include/aspect/material_model/grain_size.h
source/material_model/grain_size.cc

The DislocationViscosityOutputs now also contain the diffusion viscosity in addition to the dislocation viscosity and the boundary area change work fraction. This is useful to compute the ratio of diffusion and dislocation creep in cases where the viscosity is averaged cell-wise, because in these cases this ratio can not be recovered accurately from just the dislocation and effective viscosity.

add diffusion viscosity to DislocationViscosityOutputs

---

doc/sphinx/references.bib

The \texttt and \tt and \textsc tags in references.bib were showing up in our sphinx references page, so I removed them. I don't think these were necessary... right?

Docs: Remove \texttt from references.bib

---

source/simulator/stokes_matrix_free.cc

It seems logical to first fill the material model inputs and then evaluate the material model, as is done in all other places in the code.

Fill additional material model inputs before evaluating material model

---

benchmarks/viscoelastic_beam_modified/20km_opentopbot.prm

The beam described is supposed to be 9x as long as wide. It is also being described as 20km. Neither of which were true. Switching these numbers fixes that.

Fix typo in viscoelastic_beam_modified benchmark

---

doc/sphinx/user/install/docker-container/developing-in-container.md

I *think* that the list of commands in this section is missing the call to `make`. 
/rebuild

Documentation: Fix missing command?

---

source/particle/interpolator/bilinear_least_squares.cc
source/particle/interpolator/quadratic_least_squares.cc

At the moment we assert a very strict tolerance for the new particle limiters (10 epsilon relative to the property boundaries). This works for mappings that are analytically invertible like all of our box geometries and the 2D MappingQ for spherical shells, but at least in 3D MappingQ spherical shell geometries I have observed cases for which we trigger this assert. The MappingQ inversion internally uses a Newton iteration with a tolerance of 1e-12 so we can not expect an accuracy as good as we currently enforce. So far  1e-9 seems to be a good tolerance, at least I have never triggered this so far in my models, which proves the algorithm works as intended, it just cannot be as accurate as we thought due inaccuracies outside of the algorithms control.
@sac-bsa FYI.

Relax particle limiter tolerance a bit

---

include/aspect/mesh_deformation/ascii_data.h
include/aspect/mesh_deformation/diffusion.h
include/aspect/mesh_deformation/free_surface.h
include/aspect/mesh_deformation/function.h
include/aspect/mesh_deformation/interface.h
source/mesh_deformation/ascii_data.cc
source/mesh_deformation/diffusion.cc
source/mesh_deformation/free_surface.cc
source/mesh_deformation/function.cc
source/mesh_deformation/interface.cc
source/simulator/melt.cc
source/simulator/stokes_matrix_free.cc

At the moment, the free surface stabilization can only be applied to the free surface plugin. However, since multiple plugins can deform the surface, it may help to be able to apply the stabilization to any one plugin. For example, when using FastScape to deform the surface in 2D the model gets stability issues at the same timesteps as the free surface in the benchmark from #3317. Applying the stabilization similarly fixes the issue.
Questions:
1. Does it make sense to apply the same stabilization parameter to different problems other than those with a free surface?
2. What would be the best way to implement this? In this pull request, I've transferred the functionality of the stabilization into the mesh deformation handler. This should apply it to all mesh deformation boundaries unless …

Apply free surface stabilization to other mesh deformation plugins

---

.github/workflows/linux.yml

This PR adds an additional tester that compiles ASPECT against deal.II v9.4.0-rc2 (in a docker image I created) and runs the quick tests (we already compile against deal.II master in a separate tester). 
The nice thing about this design is that when we want to transition to 9.4 reference results, we can simply update the test results, and switch the 'ON' and 'OFF' settings below and continue to test if 9.3 still compiles.

Add 9.4 quick tester.

---

include/aspect/heating_model/latent_heat_melt.h
source/postprocess/visualization.cc

Fix the following warnings form Clang compiler:
```
In file included from /home/jiaqi2/aspect/build_clang/CMakeFiles/aspect.dir/Unity/unity_29_cxx.cxx:7:
/home/jiaqi2/aspect/aspect/source/postprocess/visualization.cc:577:36: warning: lambda capture 'this' is not used [-Wunused-lambda-capture]
= std::thread([this,
^
/home/jiaqi2/aspect/aspect/source/postprocess/visualization.cc:944:13: note: in instantiation of function template specialization 'aspect::Postprocess::Visualization<2>::write_data_out_data<dealii::DataOut<2>>' requested here
= write_data_out_data(data_out, cell_output_history,
```
```
In file included from /home/jiaqi2/aspect/build_clang/CMakeFiles/aspect.dir/Unity/unity_7_cxx.cxx:10:
In file included from /home/jiaqi2/aspect/aspect/source/heating_model/latent_heat_melt.cc:22: …
```

Fix Clang warnings

---

contrib/utilities/jsontomarkdown.py
doc/sphinx/parameters/Geometry_20model.md
doc/sphinx/parameters/Initial_20temperature_20model.md
doc/sphinx/parameters/Postprocess.md
doc/sphinx/parameters/Solver_20parameters.md
doc/sphinx/parameters/global.md

Correctly support all special characters in parameter names. Before we
were only handling space (" ") correctly.

json2markdown: mangle/demangle for special characters

---

source/mesh_deformation/interface.cc

Specify correct MaterialProperties to request for the surface
stabilization.
Fixes #4859

mesh deformation: specify correct flags

---

include/aspect/simulator.h
source/simulator/core.cc
source/simulator/helper_functions.cc
tests/global_refine_bug.prm
tests/global_refine_bug/screen-output

Requesting global refinement when running with many MPI ranks often
resulted in cells that we forget to refine.
fixes #4524
also see #4513
also see various forum posts about continental_extension cookbook with
16 MPI ranks and others.
continental_extension:
```
$ grep Number *ranksafter-16-ranks:Number of active cells: 3,200 (on 4 levels)
before-16-ranks:Number of active cells: 3,056 (on 4 levels)
before-16-ranks:Number of degrees of freedom: 103,689 (25,122+3,201+12,561+12,561+12,561+12,561+12,561+12,561)
before-16-ranks:Number of mesh deformation degrees of freedom: 6402
before-8-ranks:Number of active cells: 3,200 (on 4 levels)
before-8-ranks:Number of degrees of freedom: 107,649 (26,082+3,321+13,041+13,041+13,041+13,041+13,041+13,041)
before-8-ranks:Number of mesh deformation degrees …
```

fix global refinement

---

.github/workflows/linux.yml
contrib/docker/tester/Dockerfile
contrib/docker/tester/build.sh
contrib/docker/tester/local.cfg

Update the 9.4 tester to the official release.
I saw a number of tests crashing with 9.4 tester (when I manually run all tests, not just the quick tests), but that is independent of this PR. 
Here is a list for my own later reference, I will try to look though them in the next days (the gmg tests are likely fixed by #4871 or #4862):
289 - free_surface_VE_cylinder_2D_loading_fixed_elastic_dt_gmg (Failed)
310 - global_latent_heat (Failed)
313 - global_refine_amr (Failed)
320 - gmg_mesh_deform_ghost_entries (Failed)
411 - latent_heat_melt_transport (Failed)
421 - mass_reaction_term (Failed)
483 - melting_rate_operator_splitting2 (Failed)
502 - multiple_named_additional_outputs (Failed)
664 - prescribed_field_temperature_max_isotherm (Failed)
665 - prescribed_field_with_diffusion (Failed)
670 …

Use deal.II v9.4 release

---

source/simulator/stokes_matrix_free.cc

This helps a bit with #4862 as far as I understand it. At the moment this does not provide strain_rate to the material model, but requests all properties, which should not be allowed.

Only request needed material properties.

---

source/simulator/assembly.cc

part of #4859
The visco-plastic material model uses the strain_rate when computing reaction terms, but they might not be available leading to floating point exceptions. Work around this for the 2.4 release.
Most notably visible in the test gmg_mesh_deform_adaptive_bug2.

stokes assembler: do not request reaction_terms

---

source/postprocess/pressure_statistics.cc
source/simulator/entropy_viscosity.cc
source/simulator/helper_functions.cc
source/simulator/stokes_matrix_free.cc
source/time_stepping/conduction_time_step.cc
source/time_stepping/convection_time_step.cc

This PR allows it to use the current ASPECT version with the current deal.ii version. Specifically, it updates `QTrapez` to `QTrapezoid`, and takes into account the changes made to the `interpolate_to_mg` function. 
@tjhei Is this something that would be relevant for the release? I wanted to test the current main version on my laptop, but it didn't work with my deal.ii version, so I installed the most recent deal.ii version (rather than the last release, which is probably what I should have done...) and these were the things that didn't work for me.

allow use with currect dealii master version

---

source/simulator/stokes_matrix_free.cc

See https://github.com/geodynamics/aspect/pull/4875/files/7e3b76da4dd76cec4198146b1ef1b3b3b123b595#diff-18214df77d5d823d2bded9d4078820754b6245bde89d9cefa84e75df57e736e1 I believe that this should make the code compatible with both 9.4 and 9.5.
/rebuild

Do not specify a template argument where not necessary.

---

CMakeLists.txt

The current dev branch of the world builder moved the source files of the library to a sub folder of source (see https://github.com/GeodynamicWorldBuilder/WorldBuilder/pull/443). This means that aspect will need to look in a different location if linked to the most resent 0.5.0-pre version of the world builder. This pull request add a check to make sure that it find the correct path. Even though we won't update the world builder for release 2.4.0 of aspect, it might be good to still get this in there before the release.

Fix cmake with newer version of world builder.

---

source/postprocess/visualization.cc

requires https://github.com/dealii/dealii/pull/14110

support parallel intermediate deal.II format

---

.github/workflows/docker.yml
contrib/docker/docker/Dockerfile

This adds an automatic build of the docker image, both for 'main' (after every merged PR) and for new releases (after the publication of the release). I have already set up the secrets with docker hub to make this work, and have tested everything as far as possible in my personal account (see https://hub.docker.com/repository/docker/gassmoeller/aspect/tags?page=1&ordering=last_updated and https://github.com/gassmoeller/aspect/actions).
This contributes to #4841

Add docker image build

---

include/aspect/plugins.h

A companion to #4891.
/rebuild

Minor clean-up in the plugin infrastructure.

---

cookbooks/bunge_et_al_mantle_convection/bunge_et_al.prm
tests/bunge_cookbook.prm
tests/bunge_cookbook/screen-output

fixes
```
An error occurred in line <261> of file
</home/heister/aspect-git/source/material_model/depth_dependent.cc> in
funct
ion
void
aspect::MaterialModel::DepthDependent<dim>::parse_parameters(dealii::ParameterHandler&)
[with int dim = 2]
The violated condition was:
reference_viscosity != std::numeric_limits<double>::max()
Additional information:
You have to set a reference viscosity for the depth dependent model.
```

fix bunge et al cookbook

---

CMakeLists.txt
source/initial_temperature/world_builder.cc

This reworks the world builder config file so that it can fix the deprecation warning and works with the version currently shiped with aspect (0.4.0) and with a reworked version of the config file (https://github.com/GeodynamicWorldBuilder/WorldBuilder/pull/444) for the development branch. This reworked version on the world builder development branch will actually define macro values like WORLD_BUILDER_VERSION_MAJOR. 
Because they where never defined as macros is 0.4.0 (they where defined as a struct), the macro to test is written such that if WORLD_BUILDER_VERSION_MAJOR is not defined, it uses the 0.4.0 branch.
As discussed at todays aspect meeting, this fix (or a fix like this) should become part the the release branch as well. I will wait with merging …

rework world builder config and fix deprecations.

---

benchmarks/entropy_adiabat/plugins/prescribed_temperature.cc
benchmarks/entropy_adiabat/plugins/prescribed_temperature.h
benchmarks/solitary_wave/solitary_wave.cc
include/aspect/adiabatic_conditions/compute_profile.h
include/aspect/boundary_composition/initial_composition.h
include/aspect/boundary_temperature/initial_temperature.h
include/aspect/particle/property/pT_path.h
include/aspect/simulator.h
include/aspect/simulator_access.h
source/adiabatic_conditions/compute_profile.cc
source/boundary_composition/initial_composition.cc
source/boundary_temperature/initial_temperature.cc
source/particle/property/pT_path.cc
source/simulator/checkpoint_restart.cc
source/simulator/core.cc
source/simulator/initial_conditions.cc
source/simulator/simulator_access.cc
tests/prescribed_temperature_in_field.cc

I've tried to break this into individual commits that might be easier to review separately. The first n-1 commits provide the infrastructure and use it, and the last one actually releases the objects when possible.
It is not easy to identify when one can release these objects because we sometimes call `set_initial_temperature_and_compositional_fields ()` multiple times, depending on whether we are still in the initial refinement phase. As a consequence, these objects have to live at least until the last `goto start_time_iteration`, even though we do solve full time steps during that time. That means that I can't release them until after the first full solve, but that might still be worth it.
Let's see what happens with the testers.
/rebuild

Release initial conditions objects when possible.

---

doc/manual/manual.tex

fixes  #4925
This reverts part of #4780 and uses ``import`` instead of ``newclude`` so relative paths work correctly.

fix manual includes

---

.zenodo.json

This is the reason zenodo gave an 'internal server error' when we created the 2.4 release. Sigh.

fix zenodo.json

---

source/simulator/assemblers/advection.cc

As discussed in our meeting on Tuesday it would be helpful if this check would be performed in release mode as well as debug mode. I checked that the assert now triggers in models that have negative density. The change slows down the assembly of the temperature system by a bit less than 0.1%, and this assembly typically makes up less than 15% of the total run time, so I think this is completely acceptable (given how often we had reports about crashing solvers caused by this issue).

Assert density is positive in release mode

---

doc/manual/citing_aspect.bib

Fix a few bibtex entries.

---

include/aspect/initial_composition/world_builder.h
include/aspect/initial_temperature/world_builder.h
include/aspect/simulator.h
include/aspect/simulator_access.h
source/initial_composition/world_builder.cc
source/initial_temperature/world_builder.cc
source/simulator/checkpoint_restart.cc
source/simulator/core.cc
source/simulator/simulator_access.cc

This follows the same approach as taken for the initial conditions objects in #4889.
/rebuild

Release the WorldBuilder object early.

---

cookbooks/van-keken/doc/van-keken.md

Make the preamble to a cookbook section uniformly italics as we usually do. Fix the grammar in a couple of places.

Minor edits to the manual.

---

include/aspect/material_model/rheology/visco_plastic.h
source/material_model/rheology/visco_plastic.cc
source/material_model/visco_plastic.cc

See #4935. Avoid recalculating IsostrainViscosities when filling the PlasticAdditionalOutputs.

Simplify plastic additional outputs

---

cookbooks/continental_extension/doc/continental_extension.md

This PR updates the continental extension cookbook documentation, and supersedes #4734 which was initialized from the wrong repository by accident.

Docs: continental extension cookbook 

---

source/simulator/newton.cc

Update the default value of the Newton maximum Stokes sovler tolerance to a more conservative value, as discussed during the user meeting. The current default value is too loose for most real world applications.

Update the default value of the Newton maximum Stokes sovler tolerance to a more conservative value.

---

source/simulator/stokes_matrix_free.cc

Current deal.II master does not initialize the vector in all cases and we might up using invalid/random data.
fixes #4960

always initialize dst vector in preconditioner

---

include/aspect/particle/property/crystal_preferred_orientation.h
source/particle/property/crystal_preferred_orientation.cc

small fix of cpo get_number_of_grains and get_number_of_minerals functions, making them constant member functions. Needed to get #4980 working.

Fix particle cpo function by making it const.

---

source/main.cc

While looking more into a solution for #4984 I found this wrong code in ASPECT's signal handler. `DEAL_II_USE_CXX11` is no longer set in deal.II, meaning we consistently used the pre C++11 option in ASPECT since deal.II 9.3.0
I have not yet tested if this resolves #4984, but  so far I was unsuccessful to create a test purely in deal.II to create the same deadlock that seems to happen in the ASPECT model (so maybe us messing with the signal_handler is involved).

Remove outdated and wrong option in signal_handler for program termination

---

doc/modules/changes/20221010_gassmoeller
include/aspect/simulator.h
source/simulator/initial_conditions.cc
source/simulator/solver_schemes.cc

Our particle interpolators support interpolating more than one property per call, but the calling side in the Simulator class does not make use of this. Instead we call one interpolation at a time, because it is embedded in a loop over all compositional fields. This is not efficient, but often does not matter much, since interpolation is usually quick. However, @KiralyAgi recently sent me a model with 37(!) particle properties, and there interpolation made up a significant part of the runtime. This change interpolates all properties in one call, and should decrease that cost significantly. @KiralyAgi can you try to take these changes, incorporate them into your branch and maybe report back if it helped your runtime? The change itself should be pretty uncontroversial, the only extra …

Interpolate all particle properties in one operation

---

source/main.cc
tests/advection_solver_fail/screen-output
tests/ascii_data_fail_1/screen-output
tests/ascii_data_fail_2/screen-output
tests/ascii_data_fail_3/screen-output
tests/ascii_data_fail_4/screen-output
tests/cmake/default
tests/composition_names_duplicates/screen-output
tests/fail/screen-output
tests/find_boundary_composition_model_fail_1/screen-output
tests/find_boundary_composition_model_fail_2/screen-output
tests/find_mesh_refinement_fail_1/screen-output
tests/find_postprocess_fail_1/screen-output
tests/find_postprocess_fail_2/screen-output
tests/isosurfaces_simple_box_2D_custom_fieldnames_fail/screen-output
tests/steinberger_lateral_fail/screen-output
tests/stokes_solver_fail/screen-output
tests/stokes_solver_fail_A/screen-output
tests/stokes_solver_fail_S/screen-output
tests/stokes_solver_fail_cheap/screen-output
tests/stokes_solver_fail_gmg/screen-output
tests/time_stepping_fail/screen-output
tests/visualization_unique_list/screen-output

If a subset of processes throw an exception during communication, we can end up in a deadlock when the destructor of `MPI_InitFinalize` is called. `MPI_InitFinalize` checks for uncaught exceptions, but the exception was already correctly caught by the catch block we have in ASPECT. We should call `MPI_Abort`, just like deal.II's step-50 already does (https://github.com/dealii/dealii/blob/aa053f40abf916e6b3acdb843b636b7cd577f0e7/examples/step-50/step-50.cc#L1588).

Call MPI_Abort after handling exception

---

doc/modules/changes/20221206_douglas
include/aspect/initial_temperature/adiabatic.h
source/initial_temperature/adiabatic.cc
tests/adiabatic_plate_function.prm
tests/adiabatic_plate_function/screen-output
tests/adiabatic_plate_function/statistics

Some improvements to #4184. Also add the ability to define plate age as an input function in the parameter file. This is very helpful for simple models of mid-ocean ridges and oceanic plates in general. I am currently preparing a cookbook that makes use of this functionality.
I modified the input parameter introduced in #4184 to allow for the extension to additional age models (I could for example envision a gplates file model, like for the boundary velocity). @naliboff and @danieldouglas92 I know this requires you to rename parameters in your parameter files, do you agree that the new form is more useful and are you ok with the change?

Adiabatic boundary layer age function

---

.github/workflows/linux.yml

I have seen a few failures of the no-unity-build tester lately with errors related to installing apt packages (e.g. https://github.com/geodynamics/aspect/actions/runs/3887199332/jobs/6633184425). This may help.

Always update apt package list before install in tester

---

contrib/docker/tester/Dockerfile

#5016 fixed the build process of the tester docker image, but it did not fix the test run, because the new `cmake` was not in the environment path. I would prefer to run the candi `enable.sh` script to correctly set the environment, but it turns out both Github actions and Jenkins run `sh` as a default shell, but `enable.sh` is a bash script, therefore I set the variables manually for now (also has the advantage of being correct for whatever shell the user of the container is using). 
I have manually build and pushed this image and the new image fixed the cmake error in the test run of #5021.

Add cmake and astyle to environment of test container

---

cookbooks/anisotropic_viscosity/av_material.cc
doc/modules/changes/20230112_dannberg
include/aspect/heating_model/shear_heating.h
include/aspect/material_model/grain_size.h
source/heating_model/shear_heating.cc
source/material_model/grain_size.cc
tests/anisotropic_viscosity.cc

This PR creates a new additional material model output that contains the fraction of work that goes into shear heating. This is useful because the same term is needed both in the material model and in the heating model, and with the new implementation, the shear heating does not have to know about the material model, but each material model could still implement its own model for this term. I have checked that the `DislocationViscosityOutputs`, which were used for that purpose before, are only used in the grain size material model. 
I want to make this change because there are different models for how this work fraction is being computed (some of them including dependencies on solution variables like the temperature), and as a next step I want to implement one of these more complex …

New shear heating output

---

include/aspect/material_model/grain_size.h
source/material_model/grain_size.cc
tests/grain_size_latent_heat.cc

The grain size material model always has been a very expensive material model due to the iterations for composite viscosity and the operator splitting for the grain size evolution (requiring many evaluations of the viscosity per time step of the operator splitting). The model is also pretty old and could use some improvements in code quality. These changes are only a first step in improving the quality of the code (I did not want to start a full rewrite), but they significantly speed up the evaluation of the model.
In a simple test model (with cheap solvers) this PR speeds up the evaluate function by about 3x, which results in an about 2x speedup for the total assembly. The material model can still make up several percent of total model runtime (in my worst case test the material model …

Some optimizations for the grain size material model

---

source/boundary_composition/ascii_data.cc
source/boundary_temperature/ascii_data.cc
source/geometry_model/initial_topography_model/ascii_data.cc
source/mesh_deformation/ascii_data.cc

Something I saw while reviewing #5025. In a number of places we unnecessarily create a temporary `std::set` that is not really needed. This new version does not really change anything in the compiled code (it still needs the std::set internally), but I think the code is shorter and just as easy to read.

Remove unnecessary lines of code

---

source/geometry_model/chunk.cc
source/heating_model/shear_heating.cc
source/particle/property/crystal_preferred_orientation.cc

We have accumulated a few compiler warnings on the main branch (using gcc11), mostly over possibly non-initialized array entries and unused variables. This PR fixed all of them for me and should not change behavior.

Fix compiler warnings gcc11

---

.github/workflows/linux.yml
doc/citations-list.tex
doc/sphinx/references.bib

It turns out that it is easy to add invalid bibtex to
- doc/sphinx/references.bib
- manual/citing_aspect.bib
I am adding a doc/citations-list.tex that generates a pdf with all of the citations above. Because we will soon delete the pdf manual, I am not adding and fixing doc/manual/manual.bib
Add a CI step that fails if invalid characters or any other problem is detected.

automate citations/bibfile check

---

doc/modules/changes/20230122_myhill
include/aspect/material_model/utilities.h
source/material_model/utilities.cc
source/material_model/visco_plastic.cc

This PR adds the functions `n_phases_for_each_composition()` and `n_phases()` to the PhaseFunction class. The `visco_plastic` material model is modified to use these functions.

added n_phase functions to PhaseFunction

---

doc/modules/changes/20230119_bobmyhill
include/aspect/introspection.h
include/aspect/material_model/utilities.h
include/aspect/parameters.h
source/material_model/utilities.cc
source/simulator/introspection.cc
source/simulator/parameters.cc
tests/check_compositional_field_functions.cc
tests/check_compositional_field_functions.prm
tests/check_compositional_field_functions/screen-output

This PR pulls out the new field type introspection functions from #5023.
It also changes the Type "chemical composition" to "chemical component", to avoid confusion with the "Compositional field". 
@tjhei, @MFraters, @naliboff: at the moment the new functions aren't tested. If I incorporate these into Steinberger, is it good to go, or would you like more tests (and if so, where?).

Added field type functions

---

source/material_model/diffusion_dislocation.cc
source/material_model/melt_boukare.cc
source/material_model/rheology/constant_viscosity_prefactors.cc
source/material_model/rheology/elasticity.cc
source/material_model/rheology/frank_kamenetskii.cc
source/material_model/rheology/friction_models.cc
source/material_model/rheology/strain_dependent.cc
source/material_model/rheology/visco_plastic.cc
source/material_model/visco_plastic.cc
source/material_model/viscoelastic.cc

This PR replaces use of the "possibly_extend_from_1_to_N" function with the more flexible "parse_map_to_double_array" in all material models apart from steinberger.
This is a small step towards unifying code functionality across material models.

Increase use of parse_map in material models

---

include/aspect/introspection.h
include/aspect/parameters.h
source/initial_composition/adiabatic_density.cc
source/material_model/steinberger.cc
source/simulator/assemblers/stokes.cc
source/simulator/helper_functions.cc
source/simulator/introspection.cc

It doesn't seem logical to have this enum inside the Parameters class. It also makes the qualified name annoying to read.

move CompositionalFieldDescription outside Parameters class

---

include/aspect/material_model/equation_of_state/interface.h
include/aspect/material_model/equation_of_state/multicomponent_incompressible.h
include/aspect/material_model/rheology/composite_visco_plastic.h
include/aspect/material_model/rheology/diffusion_creep.h
include/aspect/material_model/rheology/dislocation_creep.h
include/aspect/material_model/rheology/drucker_prager.h
include/aspect/material_model/rheology/peierls_creep.h
include/aspect/material_model/rheology/visco_plastic.h
include/aspect/material_model/utilities.h
source/material_model/equation_of_state/interface.cc
source/material_model/rheology/composite_visco_plastic.cc
source/material_model/rheology/diffusion_creep.cc
source/material_model/rheology/dislocation_creep.cc
source/material_model/rheology/drucker_prager.cc
source/material_model/rheology/peierls_creep.cc
source/material_model/rheology/visco_plastic.cc
source/material_model/utilities.cc
tests/composite_viscous_outputs.cc

The utilities function `phase_average_value` takes a vector of [numbers of *phase transitions* per compositional field] as an input argument, but this argument is currently called `n_phases_per_composition`.
The current PR renames the argument to `n_phase_transitions_per_composition`, and also renames all the arguments of functions that make use this function. As far as I can tell, there's only one place in the code where a mistake is currently made based on the name (in `tests/composite_viscous_outputs.cc`). 
This PR also improves the docstrings of several `parse_parameters` functions, which *do* require the number of phases per compositional field rather than the number of phase transitions.
The PR shouldn't change any tests or functionality.

Clarified phase / phase transition arguments and docstrings

---

source/structured_data.cc

Recently, the two_merged_chunks geometry model was added to ASPECT. Unfortunately the ascii data function is not compatible with the two_merged_chunks geometry model in the current version of ASPECT. As I needed this for my research, @anne-glerum helped me some time ago to fix this by sending me the modifications that are incorporated in this pull request.

Ascii data velocity boundary conditions for the chunk_with_lithosphere_boundary_indicators geometry model

---

source/simulator/stokes_matrix_free.cc

`dst` and `ptmp` should have the exact same values at this stage. You set `dst = 0.0` and only write in `dst.block(1)` up to this point. Please correct me if I'm wrong.

Avoid unneccessary copy.

---

include/aspect/utilities.h
source/utilities.cc
unit_tests/parse_map_to_double_array.cc

@bobmyhill what do you think about this modification of parse_map_to_double_array to make #5039 work?
These are the changes I made:
- created a new function inside its own namespace that only takes the input string and a new `Options` struct that contains all the available options. This makes it simpler to extend this in the future if necessary.
- modified the existing `parse_map_to_double_array` to call the new function with all settings set so that the behavior should not change (at least none of the tests does)
- refactored `parse_map_to_double_array` into separate helper functions that do smaller pieces of the work
- added a parameter `list_of_allowed_keys` that can be longer than the existing `list_of_required_keys`.  Every key inside list_of_allowed_keys that is not inside …

Refactor parse_map_to_double_array and add option to ignore keys

---

include/aspect/structured_data.h
source/structured_data.cc
tests/adiabatic_boundary/screen-output
tests/adiabatic_plate_cooling/screen-output
tests/ascii_boundary_member/screen-output
tests/ascii_data_boundary_composition_3d_box/screen-output
tests/ascii_data_boundary_temperature_3d_box/screen-output
tests/ascii_data_boundary_velocity_2d_box/screen-output
tests/ascii_data_boundary_velocity_2d_box_list/screen-output
tests/ascii_data_boundary_velocity_2d_chunk/screen-output
tests/ascii_data_boundary_velocity_2d_shell/screen-output
tests/ascii_data_boundary_velocity_2d_shell_spherical/screen-output
tests/ascii_data_boundary_velocity_3d_box/screen-output
tests/ascii_data_boundary_velocity_3d_chunk/screen-output
tests/ascii_data_boundary_velocity_3d_shell/screen-output
tests/ascii_data_boundary_velocity_3d_shell_spherical/screen-output
tests/ascii_data_boundary_velocity_3d_sphere/screen-output
tests/ascii_data_boundary_velocity_residual_shell/screen-output
tests/box_initial_mesh_deformation_ascii_data/screen-output
tests/box_initial_topography_ascii_data/screen-output
tests/box_initial_topography_ascii_data_moved_origin/screen-output
tests/chunk_initial_topography_ascii_data/screen-output
tests/chunk_initial_topography_ascii_data_3d/screen-output
tests/chunk_initial_topography_ascii_data_3d_colatitude/screen-output
tests/gmg_mesh_deform/screen-output
tests/gmg_velocity_boundary_component/screen-output

The last step to make #5025 work. Add an option to AsciiDataBoundary to not support time dependent boundary conditions. This removes the irrelevant input parameters when a time-dependence of the dataset is not supported or allowed. Also make the class a bit safer to use without time dependence by initializing all time-dependent members to invalid values and reorder a few lines to only be executed when time-dependence is actually switched on.
This PR also fixes a long-standing property of AsciiDataBoundary, which is that even if we specify exactly one file without placeholder for timestep so far the class has issued a warning that it couldnt find the next file and therefore continues with a constant boundary condition. This has annoyed me for a long time, because if one specific file is …

Add option for time constant ascii data boundary

---

source/geometry_model/ellipsoidal_chunk.cc
source/simulator/helper_functions.cc

Small follow-up to #5050. A few more instances of 2D and 3D.
Also I moved some asserts. It is not necessary to check that we are in 3d every time the geometry model / manifold is called for a point. It is sufficient to check once when they are initialized.

Remove unnecessary asserts in ellipsoidal chunk

---

source/simulator/stokes_matrix_free.cc

Share the MatrixFree objects between StokesOperator, ABlockOperator, and SchurcomplementOperator for GMG.
This forces batching and iteration of cells in the same order. We assumed beforehand that they would happen in the same order, but this is not always the case! This fixes a problem that in certain situations wrong CellData (viscosity etc.) was being read leading to slow solver convergence (or no convergence).
This also reduces setup cost and memory consumption and requires less code. Win, win, win!?

GMG: shared MatrixFree objects

---

include/aspect/simulator.h

A student in our group ran into the following error while compiling aspect on a Macbook Pro Intel Core i9 running Ventura 13.1:
```
[ 64%] Building CXX object CMakeFiles/aspect.dir/Unity/unity_42_cxx.cxx.o
In file included from /Users/,,,/aspect-src/aspect/build/CMakeFiles/aspect.dir/Unity/unity_42_cxx.cxx:3:
In file included from /Users/.../aspect-src/aspect/source/volume_of_fluid/handler.cc:23:
In file included from /Users/.../aspect-src/aspect/include/aspect/volume_of_fluid/handler.h:24:
/Users/.../aspect-src/aspect/include/aspect/simulator.h:837:84: error: 'deprecated' attribute cannot be applied to types
void interpolate_particle_properties (const AdvectionField &advection_field) DEAL_II_DEPRECATED;
^
/Applications/deal.II.app/Contents/Resources/Libraries/include/deal.II/base/config.h …
```

Fix deprication issue.

---

.github/workflows/linux.yml

see the warnings for example at the bottom of
https://github.com/geodynamics/aspect/actions/runs/4253790230
indent+documentation:
Node.js 12 actions are deprecated. Please update the following actions to use

CI: switch to checkout v3 to avoid warning

---

include/aspect/boundary_composition/interface.h
include/aspect/boundary_temperature/interface.h
include/aspect/boundary_traction/interface.h
include/aspect/boundary_velocity/interface.h
source/boundary_composition/interface.cc
source/boundary_temperature/interface.cc
source/boundary_traction/interface.cc

We had some left over code from a switch in boundary condition interfaces 5-7 years ago. Except for the boundary traction model all deprecated functions had already been removed from the header files, but the implementations often still included a default implementation of the new interface with an error message (to notify users about the change). All of this is not necessary anymore, so I removed the remaining code. Functionally, nothing should change, because user plugins that did not implement the new interface were already triggering asserts for the past 5 years. The only exception was the boundary traction interface that still worked with the old interface. However, we had only one plugin (incl cookbooks and benchmarks) that implemented the old interface, which I fixed in #5090.
I …

Remove deprecated interface functions for boundary conditions

---

include/aspect/heating_model/interface.h
source/heating_model/interface.cc

One more PR removing deprecated functionality in the style of #5092 and #5091 this time for a function in the heating model interface that was deprecated 8 years ago.

Remove deprecated function from heating model interface

---

data/initial-composition/slab-model/create_slab2_database.py
data/initial-composition/slab-model/shell_3d.txt
doc/modules/changes/20230303_saxena
include/aspect/initial_composition/slab_model.h
source/initial_composition/slab_model.cc
tests/slab2_initial_composition_3d_shell.prm
tests/slab2_initial_composition_3d_shell/screen-output
tests/slab2_initial_composition_3d_shell/statistics

This PR adds an initial composition model that outputs 1 at the locations of the slab2 model (https://www.science.org/doi/10.1126/science.aat4723) and 0 otherwise. 
The slab2 model is input as an ascii boundary datafile with columns representing depths and thickness at the lat/long points on the Earth spaced at 0.05 degrees. This results in an ascii file that is too big to be added with aspect, and therefore a jupyter notebook is added to format the input slab2 model for an aspect input file.
Below is the paraview output from aspect using higher resolution on the test file.

Slab2 model

---

benchmarks/newton_solver_benchmark_set/spiegelman_et_al_2016/drucker_prager_compositions.cc
include/aspect/global.h
source/boundary_traction/initial_lithostatic_pressure.cc
source/boundary_velocity/gplates.cc
source/geometry_model/chunk.cc
source/geometry_model/ellipsoidal_chunk.cc
source/geometry_model/spherical_shell.cc
source/geometry_model/two_merged_chunks.cc
source/initial_temperature/adiabatic.cc
source/initial_temperature/harmonic_perturbation.cc
source/initial_temperature/spherical_shell.cc
source/material_model/drucker_prager.cc
source/material_model/rheology/drucker_prager.cc
source/material_model/rheology/friction_models.cc
source/material_model/rheology/visco_plastic.cc
source/particle/generator/uniform_radial.cc
source/postprocess/geoid.cc
source/postprocess/gravity_point_values.cc
source/utilities.cc
tests/melt_visco_plastic.cc
tests/solidus_initial_conditions.cc
tests/spiegelman_fail_test.cc

We have many places in the code that convert degrees to radians or vice versa. Instead of checking every time if we have used the right conversion, let's just make it a well named constant. This also saves a tiny amount of compute time.

Unify degrees to radians conversions

---

include/aspect/geometry_model/box.h
include/aspect/geometry_model/chunk.h
include/aspect/geometry_model/two_merged_boxes.h
include/aspect/geometry_model/two_merged_chunks.h
source/geometry_model/box.cc
source/geometry_model/chunk.cc
source/geometry_model/two_merged_boxes.cc
source/geometry_model/two_merged_chunks.cc

As seen in #4396 we handle repetition vectors differently in different geometry models. This PR simply unifies the data types and the way we call the deal.II routines. I wanted to get rid of the C-style arrays, but had the choice between std::array and std::vector. std::array in my opinion is the better (more specific) type for this variables, but std::vector is what the deal.II routines expect as input. I decided to go with std::array and convert before calling deal.II, but I am ok either way as long as its uniform across plugins.

Unify handling of repetitions between geometry models.

---

cmake/AspectConfig.cmake.in

- Plugins will configure with debug mode if ASPECT is in DebugRelease mode
- tests with plugins will now set up correctly again

DebugRelease: fix plugin and test setup

---

include/aspect/utilities.h
source/utilities.cc
unit_tests/utilities.cc

This is part of #4979, #4980 and #3885. This pull request splits out a function used in both #4979 and #4980 and uses an optimized algorithm proposed by @gassmoeller in #4980. Once this is merged, both pull request can be simplified by just using this utilities function.

Add matrix random volume weighting utilities function

---

.github/workflows/docker.yml
contrib/docker/docker/Dockerfile
contrib/docker/docker/build.sh
doc/sphinx/user/install/docker-container/installing-docker.md
doc/sphinx/user/install/docker-container/running-models.md

I have build and pushed an experimental docker image for Apple Silicon CPUs on an M1 macbook. The image is available on docker hub as `gassmoeller/aspect:latest-arm64`. I had to modify a few things compared to our regular docker image, because it cannot be based on the deal.II image (at the moment there is no arm64 image for deal.II). However, first tests seemed good, I get performance only about 30% slower than natively compiled. The remaining difference is likely the virtual machine, or the fact that the machine is compiled for linux/arm64 instead of the Mac specific architecture darwin/arm64. For comparison the old ASPECT docker image (geodynamics/aspect), compiled for amd64 and emulated on Mac M1, is about 20X slower compared to natively installed ASPECT on M1.
I would appreciate:
- …

Working Docker ARM64 image.

---

.github/workflows/linux.yml
Jenkinsfile
benchmarks/solitary_wave/solitary_wave.cc

Builds on #5111 and activates building example and cookbook plugins as part of the tester. Let's see what warnings we get.

Test example builds

---

include/aspect/particle/property/cpo_bingham_average.h
source/particle/property/cpo_bingham_average.cc

Adds a particle property plugin to compute the Bingham average for the CPO particle properties.
This implementation is based on https://github.com/geodynamics/aspect/pull/4978, so this should not be merged until that one is. It is ready for review though.
(point 4 in https://github.com/geodynamics/aspect/issues/3885)

Add cpo property Bingham average

---

include/aspect/particle/property/cpo_bingham_average.h
source/particle/property/cpo_bingham_average.cc

A bit of minor cleanup for #4980.
- `virtual` and `override` are redundant. If `override` is used, `virtual` should not be used
- I stored the reference to the CPO property in a unique pointer instead. This allows to initialize it only once, instead of searching for the right property again for every particle
- some minor coding conventions
@MFraters: Could you do a review? Also I have no way to test this. I know it compiles, but can you test if it runs correctly?

Refactor particle property CPO bingham average

---

include/aspect/material_model/interface.h
include/aspect/material_model/melt_boukare.h

Fix a few warnings that appear with the deal.II development tester (see https://github.com/geodynamics/aspect/actions/runs/4492088039/jobs/7901477861).

Fix override instead of virtual warnings

---

.github/workflows/linux.yml

We have seen some test failures on  `linux/no-unity-build` and `linux/indent+documentation` recently (see e.g. #5121 and other recent PRs).
I think this is what happened: Github actions updated their ubuntu 20.04 base image to include cmake 3.26.0 instead of 3.25.3. However, 3.26.0 seems to contain a bug that breaks our CMake system. Kitware has already released 3.26.1 (just 10 days after 3.26.0, they probably found the bug as well), but Github actions has not yet updated their included cmake version (they will soon, see https://github.com/actions/runner-images/issues/7336). I have checked locally that cmake 3.26.0 produces the same error on my system and 3.26.1 works correctly. 
This PR should fix our test failures until the github actions runner is updated.

Use custom cmake version in tester to fix bug

---

include/aspect/utilities.h

- fix typos
- move inline implementations to the bottom of the file
followup to #5094

Utilities: move inline funcs down

---

.github/workflows/docker.yml
contrib/docker/docker_tacc/Dockerfile
contrib/docker/docker_tacc/build.sh
contrib/docker/docker_tacc/instructions.txt

The TACC systems Stampede2 and Frontera support running singularity containers. This is a preliminary Docker image that uses their base images. They run successfully in parallel on Frontera across nodes. I need to do some more testing regarding performance and extend the documentation, but I think this is something we may want to keep around to make installation on Stampede and Frontera trivial (you can put the lines in instructions.txt in any slurm script and it will download and run ASPECT without local installation).

Add Dockerfile for TACC systems Stampede Frontera

---

.github/workflows/linux.yml

This reverts commit e21150601ef1cfe8e9b80769c092c8ca3c4879c2 and PR #5122. The github actions runner should now use a fixed cmake version. Don't merge yet until I have checked the version and removed the unnecessary commit.

Revert tester to standard cmake

---

benchmarks/entropy_adiabat/plugins/entropy_model.cc
benchmarks/solitary_wave/solitary_wave.cc
source/boundary_velocity/gplates.cc
source/initial_temperature/S40RTS_perturbation.cc
source/initial_temperature/SAVANI_perturbation.cc
source/initial_temperature/spherical_shell.cc
source/main.cc
source/material_model/steinberger.cc
tests/original_prm/original.prm

In a similar direction as #5132, but I looked for other instances of ifstream in ASPECT that were executed in parallel. I didnt find much, except for one benchmark and the reading of our main input file. However I found a bunch of header files that are leftovers from when `read_and_distribute_file_content` didnt exist.
Input files are typically small, so it might not matter much, but I think it is nice to always use the same function to read files, and who knows, maybe opening a small file on >100,000 cores will eventually be a problem ;-).

Reduce parallel file input operations

---

CMakeLists.txt
contrib/world_builder/include/world_builder/utilities.h
contrib/world_builder/source/parameters.cc
contrib/world_builder/source/utilities.cc

While preparing for some large-scale runs I noticed that WorldBuilder is opening and reading its input file on every MPI rank. On large clusters this can cause a lot of problems with the file systems. I essentially reimplemented ASPECT's `read_and_distribute_file_content` function for world builder. I know this only fixes the bundled version, I will create a separate PR for the main WorldBuilder repo.
In order to check if MPI is available inside WorldBuilder I used the same compile definition the main world builder app uses. When bundled with ASPECT MPI is always available.
@MFraters: Can you take a look?

Avoid opening world builder file on all MPI processes.

---

benchmarks/blankenbach/plugin/code.cc
benchmarks/diffusion_of_hill/analytical_topography.cc
benchmarks/shear_bands/shear_bands.cc
benchmarks/tangurnis/code/tangurnis.cc
include/aspect/utilities.h
source/postprocess/dynamic_topography.cc
source/postprocess/geoid.cc
source/postprocess/heat_flux_map.cc
source/postprocess/topography.cc
source/utilities.cc

We have a number of places that deal with custom file output, besides the optimized output of visualization files and checkpoints. Many of these places copy the same code (some use outdated or simpler versions). This PR introduces one central function in the Utilities namespace that can deal with one common use case (every process writes some output, it needs to be collected and written to file by process 0).
The benefits of introducing this function are:
- unifies code -> less potential for copy-paste bugs
- we can make improvements and optimizations in one place instead of many (e.g. using MPI-IO or allowing to compress file output)
- the function is already better than many of the previous implementations, because it checks for success when writing and throws exceptions on all …

Introduce utility function for file writing.

---

doc/modules/changes/20230414_gassmoeller
include/aspect/utilities.h
source/boundary_velocity/gplates.cc
source/simulator/checkpoint_restart.cc
source/simulator/parameters.cc
source/structured_data.cc
source/termination_criteria/user_request.cc
source/utilities.cc
tests/ascii_data_fail_4/screen-output

One more PR in the same line as #5132, #5133, and #5134. In many places in the code we check for the existence of a file (on all MPI ranks) only to read it on rank 0 and distribute it via MPI. This makes no sense, as it increases the load on the file system and may even be wrong in case the file is on a local file system that is only accessible for rank 0.
I introduced a new function `Utilities::fexists` that takes the MPI communicator as second argument and only checks for the file existence on rank 0 and distributes the result to all ranks. The distribution is important, because the subsequent file access operation has to be started on all ranks (even if only rank 0 actually reads the file). I left the old version in, because we have a few functions that are only executed on rank 0 …

Reduce duplication when checking for file existence

---

source/particle/world.cc

This should fix the tester failures with a recent deal.II development version. I do not quite understand which change in deal.II triggered this, but I am pretty sure I understand the problem. `FEPointEvaluation::value_type` is either a `Tensor<1,n_components>` or `double` depending on how many components are evaluated by FEPointEvaluation. However, we always accessed the result as `result[j]`, which was wrong. The function `FEPointEvaluation::EvaluatorTypeTraits<dim, n_compositional_fields, double>::write_value` does this correctly (accessing tensors by their component, but simply copying a double if only as single component is available).

Fix access to vectorized results in particle world

---

.github/workflows/docker.yml

#4039 added the TACC docker image, and also included a try to upload the image to ghcr.io instead of docker hub. While the login was successful, the job didnt actually label the image for upload to ghcr.io. This PR represents an extension of that PR in that it:
- actually builds and pushes the TACC docker image to ghcr.io, and
- also uses ghcr.io for the regular docker image
It still also builds the images for docker hub, so existing workflows work as before. I would like to test if the new workflow runs correctly, before discussing if we want to drop Docker hub, or just keep using both.

Push image to ghcr

---

source/particle/world.cc

This is an attempt at fixing #5138. @mibillen I was unsuccessful in reproducing the warning message you showed. I tried with Ubuntu 18.04 which has gcc 7.5.0 as default and all the dependencies identical to your posting, but I still did not see the message.
Could you try if the small changes in this PR fix your warnings?

Fix compiler warnings for certain template instantiations

---

tests/CMakeLists.txt
tests/quick_mpi.prm
tests/world_builder_select_composition.prm
tests/world_builder_simple.prm
tests/world_builder_simple_2d_cartesian_sticky_air.prm

I verified that it enables the same number of tests as before (990 on my machine).
/rebuild

Come up with a better format to indicate that a test requires the WorldBuilder.

---

doc/sphinx/index.md
doc/sphinx/user/extending/compatibility.md
doc/sphinx/user/extending/contributing.md
doc/sphinx/user/extending/index.md
doc/sphinx/user/extending/signals.md
doc/sphinx/user/extending/write-a-cookbook/index.md
doc/sphinx/user/extending/write-a-cookbook/plugins.md
doc/sphinx/user/extending/write-a-cookbook/quickref.md
doc/sphinx/user/methods/choosing-a-formulation/index.md
doc/sphinx/user/methods/index.md
doc/sphinx/user/run-aspect/2d-vs-3d.md
doc/sphinx/user/run-aspect/gui/index.md

This PR addresses two issues with documentation I noticed recently:
1. The introduction of the markdown quickref document has increased the size of some table of content lists considerably. This PR fixes that by removing the rendering of one top level heading, and by restricting some table of content lists to a smaller number of levels (they also look cleaner this way)
2. A lot of our headings in the manual are unnecessarily long, in particular many include the phrase "in ASPECT", which is quite redundant in a documentation about ASPECT. I reworded the worst offenders so that the new table of content side bar looks much cleaner (can be seen in the test build of the documentation of this PR).

Improve ASPECT documentation headings and TOC

---

contrib/utilities/jsontomarkdown.py

In an earlier PR I removed a warning box from the parameter documentation without realizing that it was automatically generated by the script `jsontomarkdown.py`. Remove the automatic message from the script as well.

Remove admonition from markdown script

---

CMakeLists.txt
include/aspect/config.h.in
source/material_model/grain_size.cc
source/utilities.cc
unit_tests/first.cc
unit_tests/utilities.cc

This is a suggested solution to #1824 that installs the data directory and allows the user to override the path of ASPECT_SOURCE_DIR by setting an environment variable. I need this for an installation where the build and source paths are no longer available after installation.
I implemented a first version using a run-time configuration file instead (as suggested in #1824, see first commit in this PR), but that has the disadvantage that it is not always easy to find the configuration file, even if it is installed in the same folder as the executable (e.g. if ASPECT is called from a different directory and the aspect binary is a weak link). Setting an environment variable seems safer.
However, I am not 100% sure about the name the environment variable should have:
- ASPECT_SOURCE_DIR: This …

Install data and allow environment override to ASPECT_SOURCE_DIR

---

cookbooks/shell_simple_2d/doc/shell_simple_2d.md
cookbooks/shell_simple_2d/shell_simple_2d.prm

This fixes #4392, which I encountered by chance as well. I was unable to reproduce the bug at the time of the report, but I think I have found why: The Stokes  solver only crashes if run on a specific number of MPI ranks. With ranks 1,2,4 it crashes, with ranks 8 or higher it runs just fine. I also saw that the final residual during the crashes stagnates very close to the convergence criteria, so it seems it just barely doesnt make it.
Either of these changes fix the cookbook:
- Increasing the solver tolerance to 1e-6
- Using tangential velocity BC at the bottom
- Not using shear heating
- Using the GMG solver
- Using a constant (instead of linear) temperature profile
Based on this, I think the unrealistic setup of this cookbook throws off our pressure scaling (unstable temperature …

Fix simple shell cookbook

---

include/aspect/material_model/interface.h

Fixes a warning with my current compiler.

Mark a function as 'override'.

---

benchmarks/nsinker_spherical_shell/gmg.prm
tests/spherical_nsinker/screen-output
tests/spherical_nsinker/statistics

The nsinker spherical shell benchmark does not converge with the current setting on my machine (just barely, 1e-8 would be converged, it stagnates around 1.8e-8). Increasing the GMRES restart length fixes the issue. The test in a lower resolution converges fine.
Found while preparing for #5145.

Increase GMRES restart for nsinker_spherical_shell

---

include/aspect/initial_composition/porosity.h
source/initial_composition/porosity.cc

The cookbook `future/mantle_setup_start.prm` does not work at the moment, because it accesses the initial temperature manager after it has been discarded. This is because  it uses the boundary composition model `initial composition`, which calls the initial composition manager, however the `porosity` initial composition then accesses `initial temperature`, which has not been stored.
Related to #5145.

Fix late access to initial composition in cookbook

---

source/particle/property/grain_size.cc

Removed a deprecated option for choosing deal-ii version, as aspect now require deal-ii > v9.4

removed a deprecated option

---

source/simulator/core.cc

Remove unused option core

---

.github/workflows/linux.yml
CMakeLists.txt
doc/modules/changes/20230707_gassmoeller

This sets the ASPECT default build type to DebugRelease (just like deal.II). This creates two executables in the build directory. The main reason I think this is more useful because most users will need both executables eventually (debug for testing, release for actually running models) and I keep encountering users that either:
- never run debug mode, because they dont want to recompile before running the actual model
- or dont know that they are running debug mode (because it is the default) and are unaware there is a faster option available.
I hope with this change we can reduce these confusions (at the cost of slower compile time).

Set default build type to DebugRelease

---

include/aspect/simulator_signals.h
source/simulator/simulator_signals.cc

Explain to the compiler that there is an external instantiation of some member variables.

---

source/structured_data.cc

It wasn't clear that you cannot only specify the time step placeholder, even when there is only one boundary used. Very clear overview in the short Issue #4999 . I improved the replace_placeholders function description.

improved parameter description for replace_placeholders function

---

include/aspect/initial_composition/slab_model.h
source/initial_composition/slab_model.cc

We use the object `slab_boundary` in our material model to access `slab_depths` and `slab_thickness`. In order to do this, this PR allows public access for the object.

Make the protected object public to use its functions elsewhere.

---

contrib/release/release-tasklist.md

A suggestion for release notes for the 2.5.0 release.
Related to #5145.

Release notes for 2.5.0

---

source/geometry_model/ellipsoidal_chunk.cc
source/simulator/nullspace.cc

Trigger warning: contains a `goto`.

Improve code readability in small ways in two places.

---

include/aspect/compat.h

This also simplifies a bunch of code.

Replace use of C-style array by std::array.

---

source/particle/property/integrated_strain.cc
source/particle/property/integrated_strain_invariant.cc
source/particle/property/strain_rate.cc
source/particle/property/viscoplastic_strain_invariants.cc

This fix breakage such as this that currently trips up #5207 and #5206:
```
/__w/aspect/aspect/source/particle/property/strain_rate.cc:49:15: error: cannot bind non-const lvalue reference of type 'dealii::ArrayView<double, dealii::MemorySpace::Host>&' to an rvalue of type 'dealii::ArrayView<double, dealii::MemorySpace::Host>'
49 |         auto &data = particle->get_properties();
|               ^~~~
/__w/aspect/aspect/source/particle/property/strain_rate.cc: In instantiation of 'void aspect::Particle::Property::StrainRate<dim>::update_particle_property(unsigned int, const dealii::Vector<double>&, const std::vector<dealii::Tensor<1, dim> >&, typename dealii::Particles::ParticleHandler<dim>::particle_iterator&) const [with int dim = 3; typename …
```

[Urgent] Fix 'main' breakage.

---

doc/sphinx/_templates/navbar_end.html
doc/sphinx/conf.py

The "extra_navbar" option has been removed in newer versions of the sphinx-book-theme and I get warnings about it when building the documentation on my system. Readthedocs seems to be fine for now, but if the new option works on readthedocs we may as well already update to avoid the warnings (which are treated as errors by our settings).
I marked this WIP because I first want to check how this PR looks like on readthedocs.

[WIP] Update cig logo option for sphinx

---

source/particle/interpolator/bilinear_least_squares.cc
source/particle/interpolator/quadratic_least_squares.cc

Like #5208, except that the compiler did allow binding temporaries to a const reference. But just because we can doesn't mean that we should.

Do not bind temporaries to references.

---

source/material_model/viscoelastic.cc
source/simulator/core.cc

See #4985. When a material model does not support elasticity, but elasticity is enabled, Throw a helpful exception.
I left in the AssertThrow in elasticity.cc that checks that `Enable elasticity` is set to true (so it checks the reverse of the new AssertThrow).

Check that material model supports elasticity when it is enabled

---

.readthedocs.yaml
doc/sphinx/_templates/navbar_end.html
doc/sphinx/conf.py

Do not merge yet ;-)
#5216 accidentally removed the title text of the documentation. Reintroduce the title and remove an unnecessary paragraph in the CIG logo navbar.

Fix documentation layout

---

include/aspect/postprocess/particles.h
source/postprocess/particles.cc

Based on comments in #4979. This brings the writer more in line with the writer in visualizer.cc

Change particle postprocessor writer from raw pointers to unique pointers

---

source/postprocess/gravity_point_values.cc

Resolves #4485.
Replaces pow(x,2) and pow(x,3) with multiplication for speedup. Tests from #4687 should apply.

Gravity std::pow() update

---

source/geometry_model/spherical_shell.cc

See also https://github.com/dealii/dealii/issues/15685. I don't think it matters here, but we should simply *always* call that function before `create_triangulation()`.

Make sure cells are consistently ordered.

---

.github/workflows/linux.yml

Run github actions also on branches (important for the releases)

CI: run on branches

---

doc/sphinx/user/install/local-installation/compiling.md
doc/sphinx/user/install/local-installation/documentation.md
doc/sphinx/user/install/local-installation/index.md

We currently have no documentation on how to build the sphinx documentation locally. Add instructions and combine them with the instructions on how to build the doxygen documentation.

Improve the documentation on how to build the manual

---

contrib/release/release-tasklist.md
doc/make_cite_html.py
doc/options.dox

Clean up some leftovers from #5200, in particular some uses of doc/manual/manual.bib, which is now replaced by doc/sphinx/references.bib.

Remove references to manual.bib

---

contrib/world_builder/include/delaunator-cpp/delaunator.hpp
contrib/world_builder/source/world_builder/objects/bezier_curve.cc
contrib/world_builder/source/world_builder/utilities.cc
contrib/world_builder/source/world_builder/world.cc

@bobmyhill and @anne-glerum could you test if this fixes the issue?
@tjhei It would be great to take this over in the release branch

Fix for warnings from world builder.

---

benchmarks/entropy_adiabat/plugins/entropy_advection.cc
doc/modules/changes/20230709_dannberg
include/aspect/simulator/assemblers/interface.h
source/simulator/assembly.cc
source/simulator/entropy_viscosity.cc
source/simulator/melt.cc

It is useful to allow different advection fields to have different assemblers (i.e., we have different advection methods like advection field, diffusion field etc.) and not all of them require all assemblers. In cases where a signal is used to replace assemblers, it may even be necessary to only do that for specific fields and not for all of them. 
This PR makes the advection system assembers a vector of vectors (with each compositional field having their individual vector of advection assemblers). At the moment, all fields still get the same assemblers, to test that this change does not break any functionality. The next step would be to only include the assemblers that are needed in each list (in a separate PR). 
The change in the entropy benchmark shows how this could look like.  
I …

allow a different list of assemblers for each advection field

---

source/main.cc
source/postprocess/depth_average.cc
source/postprocess/particles.cc
source/postprocess/visualization.cc
source/simulator/checkpoint_restart.cc

This is all in places where a function wants a string, we have a string, we ask for its `.c_str()`, which is then converted back to a string. This is not necessary.

Avoid use of taking .c_str() just to convert back to std::string.

---

source/boundary_temperature/dynamic_core.cc
source/postprocess/depth_average.cc
source/postprocess/geoid.cc
source/postprocess/particles.cc
source/postprocess/point_values.cc
source/postprocess/stokes_residual.cc
source/postprocess/visualization.cc
source/simulator/checkpoint_restart.cc
source/simulator/core.cc
source/utilities.cc

`std::[if]stream` used to only take C-style pointers to file names, but since C++11 they are also happy with `std::string` objects. We have the latter, there is no need to extract a C-style pointer.

std::[io]fstream can take file names as std::string.

---

include/aspect/particle/property/crystal_preferred_orientation.h

Override implies virtual and I was asked to remove this in a different pull request as well.

remove virtual from functions with override within cpo particle property

---

include/aspect/initial_composition/world_builder.h
include/aspect/initial_temperature/world_builder.h
include/aspect/particle/integrator/rk_2.h
include/aspect/particle/integrator/rk_4.h
include/aspect/particle/property/cpo_bingham_average.h
include/aspect/particle/property/interface.h
include/aspect/stokes_matrix_free.h
include/aspect/time_stepping/conduction_time_step.h
include/aspect/time_stepping/convection_time_step.h
include/aspect/time_stepping/interface.h
tests/melt_visco_plastic.cc

follow up to #5241. Found a few places outside the cpo plugin which have this.

Remove virtual when there is an override keyword from more functions.

---

doc/modules/changes/20230708_lhy11009
include/aspect/material_model/rheology/peierls_creep.h
source/material_model/rheology/peierls_creep.cc
tests/visco_plastic_peierls_strict_cutoff_test.prm
tests/visco_plastic_peierls_strict_cutoff_test/screen-output
tests/visco_plastic_peierls_strict_cutoff_test/statistics

In the Pull request, I add an option to use the "Cutoff stresses for Peierls creep" as strict cutoffs for the stress in the Peierls rheology. Previously, these values are used to ensure a gradual decreases of the Peierls strain rate towards 0 when the stress approaches 0. However, the values of the calculated Peierls creep viscosity could still be ultra small with the Idrissi 16 rheology at mantle conditions (T = 1673 K, strain rate = ${10}^{-15} s^{-1}$.  By adding this new option, the stress in the Peierls rheology cannot drop pass the cutoff stress anymore, thus reasonalely large values of …

Apply strict cutoff to the Peierls stress

---

contrib/install/local.cfg
doc/sphinx/user/install/local-installation/using-candi.md

Our local installation instructions use the default candi.cfg configuration file, which always tries to install opencascade, petsc and other packages, requiring a lot of time and causing more compilation complications than necessary. In addition it does not enable native optimizations. This PR provides a local.cfg file that  is better suited for ASPECT use and speeds up the GMG solver significantly for most users (many are not aware of the impact of native optimizations). With this file we also have more control over which deal.II version to suggest for users, the default seems to be the development version of deal.II.

Add a default local.cfg for a candi installation

---

benchmarks/entropy_adiabat/entropy_adiabat.prm
include/aspect/introspection.h
source/simulator/parameters.cc

This PR adds entropy as a new field type.

added entropy as optional field type

---

benchmarks/blankenbach/plugin/code.cc
benchmarks/hollow_sphere/hollow_sphere.cc
benchmarks/inclusion/compositional_fields/inclusion_compositional_fields.h
benchmarks/operator_splitting/advection_reaction/advection_reaction.cc
benchmarks/operator_splitting/exponential_decay/exponential_decay.cc
benchmarks/rigid_shear/plugin/rigid_shear.cc
benchmarks/shear_bands/shear_bands.cc
benchmarks/solcx/solcx.h
benchmarks/solitary_wave/solitary_wave.cc
benchmarks/tangurnis/code/tangurnis.cc
benchmarks/time_dependent_annulus/plugin/time_dependent_annulus.h
benchmarks/tosi_et_al_2015_gcubed/tosi.cc
benchmarks/yamauchi_takei_2016_anelasticity/anelasticity_temperature.h
cookbooks/inner_core_convection/inner_core_convection.cc

[2.5] take over #5235

---

source/material_model/visco_plastic.cc

Since #5247, using out.viscosity when it is not set will trigger a signalling NaN. So this TODO that says to check whether the viscosity was requested (and therefore computed) for filling the force and reaction terms outputs by the elastic rheology (lines 305-309) is no longer necessary. Or would we want to AssertThrow it anyway?

Remove todo to assert that viscosity has been requested and computed

---

source/postprocess/boundary_strain_rate_residual_statistics.cc
source/postprocess/visualization/boundary_strain_rate_residual.cc

While there, also add an early-exit to a loop.

Use range-based for loops.

---

doc/modules/changes/20230710_bangerth
source/postprocess/visualization/artificial_viscosity.cc
tests/composition_active_nans.prm
tests/composition_active_nans/screen-output

Do not leave NaN values in output vectors.

---

doc/modules/changes/20230708_bobmyhill
include/aspect/introspection.h
include/aspect/material_model/visco_plastic.h
include/aspect/parameters.h
source/material_model/equation_of_state/multicomponent_incompressible.cc
source/material_model/multicomponent.cc
source/material_model/visco_plastic.cc
source/material_model/viscoelastic.cc
source/simulator/introspection.cc
source/simulator/parameters.cc
source/utilities.cc
tests/check_compositional_field_functions.cc
tests/check_compositional_field_functions/screen-output
tests/check_compositional_field_names/screen-output
tests/viscoelastic_bending_beam.prm

This PR uses the new Field Types parameter in the multicomponent incompressible EoS and derived rheologies (multicomponent, viscoelastic, visco_plastic). The parameters defined by these models can take either:
- the old format - one value per compositional field, regardless of what that field represents, or 
- the new format - one value per compositional field that represents a chemical composition
This means that the changes are backwards compatible for now, although I've added `TODO ASPECT_3` notes in those places where code should (eventually) be removed.
The backwards compatibility does necessitate two additional things:
- a step during parameter parsing where default Field Types are defined in those cases where the user didn't specify them
- a function `prm_substring` that …

Field types for multicomponent incompressible and derived modules

---

benchmarks/tangurnis/code/tangurnis.cc
source/boundary_temperature/dynamic_core.cc
source/material_model/interface.cc
source/mesh_deformation/interface.cc
source/mesh_refinement/compaction_length.cc
source/mesh_refinement/density.cc
source/mesh_refinement/isosurfaces.cc
source/mesh_refinement/thermal_energy_density.cc
source/postprocess/geoid.cc
source/postprocess/gravity_point_values.cc
source/postprocess/heat_flux_map.cc
source/postprocess/mass_flux_statistics.cc
source/postprocess/visualization/ISA_rotation_timescale.cc
source/postprocess/visualization/grain_lag_angle.cc
source/postprocess/visualization/melt.cc
source/postprocess/visualization/seismic_anomalies.cc
source/postprocess/visualization/stress_second_invariant.cc
source/postprocess/visualization/vertical_heat_flux.cc
source/simulator/assemblers/advection.cc
source/simulator/assembly.cc
source/simulator/melt.cc
source/simulator/nullspace.cc
source/simulator/stokes_matrix_free.cc
tests/melt_transport_adaptive.cc
tests/prescribed_temperature_in_field.cc

I ran into more problems in #5239 because the strain rate is not always provided to material models if `additional_outputs` are requested but not `viscosity`. With the advent of material models that may use the strain rate even if no viscosity is requested I think our system of guessing whether we need to compute the strain rate finally breaks down. I would suggest we just always compute the strain rate. It is slightly more expensive, but there is no way for the calling side to figure out which inputs are required by a material model and the current system is very fragile.

Always provide strain rate to material model

---

source/postprocess/visualization/artificial_viscosity_composition.cc
tests/composition_active_nans.prm

Follow-up on #5253. This PR does the same for the artificial viscosity composition postprocessor. We can reuse the same test. 
This addresses #5238.

Follow-up: Do not leave NaN values in output vectors.

---

source/geometry_model/interface.cc
source/particle/generator/interface.cc
source/particle/property/interface.cc
source/simulator/assemblers/interface.cc

The curly brace thing in #5280 seems to have been a real hit. I will give you more of it herein!

Use more curly brace initialization in return statements.

---

source/simulator/parameters.cc

This PR removes some code that tries to guess if a compositional field is of type density (since the same functionality was added in a more general way in #5039) just a few lines below the ones I removed.

remove duplicated code

---

doc/update_parameters.sh

Updates a couple of comment strings in update_parameters.sh.

update description in update_parameters.sh

---

doc/sphinx/user/extending/contributing.md

This unifies the content between the CONTRIBUTING.md file and the contributing section in the manual. Next step is to add some info on how to manually install astyle.

Replace manual contributing conent with CONTRIBUTING.md.

---

include/aspect/utilities.h
source/utilities.cc
unit_tests/utilities.cc

This pull request splits the tensor functions out of #4987 and #5116 and puts it in the utilities function in a new Tensors namespace.

Add elastic utilities

---

tests/compressibility.cc
tests/compressibility_iterated_stokes.cc

I had to compile this test to track down a bug, and it produces compiler warnings. We don't usually see those, unless we use `ctest -V`, but it was easier to fix them than to try to read past a lot of warnings.

Correctly mark functions with 'override'.

---

doc/sphinx/user/extending/write-a-cookbook/manual-section.md

doc: explain cookbooks/check.mk

---

CMakeLists.txt

The message just outputs a path, with a line prefix of only "C" -- it doesn't show anything useful. Let's remove it.
While there, break two long lines.

Remove debug output from CMakeLists.txt.

---

source/utilities.cc

This fixes an issue reported by @anne-glerum. On mac the compiler seems not to be able to make sqrt(2) into a constexpr. So this pull request just makes it into a const. It also changes sqrt(2) it into a deal.ii number as suggested by @gassmoeller  in #4987. Maybe that constexpr would be possible with that again, but I think fixing it quickly should have priority now. We can test that out later.

Fix macos constexpr tensor utilities

---

doc/CMakeLists.txt

Fixes #5304. I left some parts in the file because I didn't know whether we still need them -- specifically, the code to build the plugin graph and a couple of other things that are either useful now to build sphinx documentation, or will at some point once we drive that through cmake as well.

Drop most of doc/CMakeLists.txt.

---

doc/modules/changes/20230713_glerum
include/aspect/boundary_traction/initial_lithostatic_pressure.h
source/boundary_traction/initial_lithostatic_pressure.cc
tests/airy_isostasy_initial_topo.prm
tests/airy_isostasy_initial_topo/screen-output
tests/airy_isostasy_initial_topo/statistics

I've updated the plugin to hopefully deal more self-consistently with initial topography and mesh deformation. The lithostatic pressure profile that is computed at t0 now uses the actual initial topography at the reference point instead of the maximum initial topography. Also, when traction is prescribed on a bottom boundary, the last pressure in the profile is prescribed, instead of using what the geometry model returns as depth to interpolate the pressure profile.

Update initial lithostatic pressure plugin to account for initial topography and mesh deformation.

---

include/aspect/utilities.h
unit_tests/utilities.cc

Split out of the Levi-Cevita function from #4987

Add Levi-Civita tensor to Aspect

---

include/aspect/simulator.h
source/simulator/solver_schemes.cc

We have three functions that can optionally compute something. Whether they do is controlled by a `bool` argument, and the output is put into a pointer variable. This is duplicative: We should just use whether the pointer is non-`nullptr` to control whether or not to compute the optional thing.

Clarify function argument names.

---

benchmarks/check.mk
cookbooks/check.mk

Simplified version of #5319 that only builds all plugins. This would still fix #5259 and make it possible to remove some special rules.

Build all cookbook and benchmark plugins when validating input files.

---

source/material_model/rheology/visco_plastic.cc
source/material_model/visco_plastic.cc
source/simulator/assembly.cc
source/simulator/melt.cc
tests/continental_extension/screen-output
tests/visco_plastic_derivatives_2d.prm
tests/visco_plastic_derivatives_2d/screen-output
tests/visco_plastic_derivatives_3d.prm
tests/visco_plastic_derivatives_3d/screen-output
tests/visco_plastic_yield_strain_weakening_defect_corr_stokes/screen-output

This PR contains three changes that make using the strain rate in material models safer. All of these changes were necessary for #5211.
1. The Stokes assembly currently only provides the strain rate to the material model if the viscosity is requested. However, with complex material models we dont know what other material properties the strain rate may be needed for. For example the visco_plastic and viscoelastic material models also need the viscosity to compute the elastic force terms. 
2. The visco-plastic rheology sometimes has to use a reference strain rate, but the condition for when to use the reference strain rate seems wrong. It needs to use the reference strain rate during the initialization (when timestep_number is undefined), during the first timestep (but only the first …

Be safer and more correct when using strain rate

---

source/material_model/utilities.cc

I heard an was involved in several discussions today about material models that may or may not have background fields and it took a long time to figure out why these vectors had different sizes, so I thought this would be helpful for debugging.

Make error messages more useful

---

include/aspect/utilities.h
source/particle/property/crystal_preferred_orientation.cc
source/utilities.cc
unit_tests/utilities.cc

On @danieldouglas92 's laptop, the Levi-Civita variable introduced by @MFraters yesterday in #5318 leads to a linker error: It complains that there are duplicate copies of the variable in every object file. That's a compiler error: `constexpr` implies `const`, and `const` variables at namespace scope are automatically `static`, i.e. every `.cc` file that `#include`s the header file has its own copy with internal linkage. Apparently, clang does not know that rule.
As verified by @danieldouglas92, the problem can be worked around by explicitly marking the variable as `static`.

Address a clang compiler problem.

---

doc/sphinx/user/install/local-installation/using-candi.md

Add a bit more documentation regarding what happens when running candi and both `local.cfg` and `candi.cfg` are present in the directory.

udpate candi local.cfg documentation

---

source/mesh_deformation/interface.cc

fixes #5347
This is a change that happend in a recent change to deal.II master (https://github.com/dealii/dealii/pull/15793).

fix crash in GMG mesh deformation with deal.II master

---

source/simulator/assemblers/advection.cc

Found while working on #4370.
When assembling advection equations on cell faces that are not on the domain boundary, the material model and heating model are evaluated for the neighbouring cell without setting up the additional material model inputs and outputs. The modifications I made in #4370 to the shear heating plugin require ElasticOutputs, which were thus not created. 
The tests that use DG for composition use either the simple, the SolKz or the Annulus material model, which do not have additional material outputs. So a test with DG and additional outputs would be good to add?
With this PR, all the additional material model input and output is set up.

Create additional inputs and outputs for DG faces neighbouring cells

---

README.md
ReadMe.html
download.html
funding.html
header.include
index.html

This started off as addressing #5312, but I quickly found a lot of places on the website that were outdated in one or the other way. I also found some information that was slightly outdated and already available in better form in the online manual (e.g. on the Download page). Therefore this turned into a general update to the website.
I also noticed that the order of green buttons on the start page seems not optimal (we first give information how to ask questions, before linking to the manual and parameter documentation), and that the order of buttons is different from the order of menu options in the 'Info' dropdown menu. So I reordered them.
Some of these changes are a bit subjective, I am not bound to any. If we want to handle things differently or changes are unclear let me know.

Fix outdated information on website

---

.github/workflows/docker.yml

During the release of v2.5.0 the docker release image was not automatically generated. I believe this is because the wrong `type` was listed as trigger in the workflow. The github documentation states:
```
Note: Workflows are not triggered for the created, edited, or deleted activity types for draft releases. When you create your release through the GitHub browser UI, your release may automatically be saved as a draft.
```
This seems a bit weird, but their own example lists the `published` type to perform actions during releases. There is also `released`, which as far as I understand only happens once when the release is finalized. I think `published` is what we want, because it is also triggered on creating a pre-release or draft release. This way we can test the docker image before …

Fix automatic docker build on release

---

doc/make_cite_html.py
doc/sphinx/references.bib

It turns out somebody renamed the bib entries, which broke the script. Also add 2.5 entries and a forgotten zenodo entry.

fix make_cite_html.py script

---

benchmarks/entropy_adiabat/plugins/entropy_model.cc
benchmarks/entropy_adiabat/plugins/entropy_model.h
include/aspect/material_model/utilities.h
source/material_model/utilities.cc

I opened up this pull request to test and fix some issues in my last pull request (#5334 Add EntropyReader Class). The previous one couldn't compile on the testers, but it could on my up-to-date local version. It also seems to have some strange indents.

EntropyReader Class

---

include/aspect/material_model/rheology/strain_dependent.h
source/material_model/rheology/strain_dependent.cc

This is an optimization of #4336. It makes the following changes:
- Using `FEPointEvaluation` instead of `FEFieldFunction` is much faster
- Only compute the solution values of one field instead of all fields, only at the current location, not at all in.positions
- Do not allocate std::vectors for every evaluation point, which are slow to create
@naliboff: Can you check that I didnt mess up the viscous vs plastic indices? I think I kept all functionality the same, it should just be significantly faster.

Optimize strain dependent rheology

---

source/postprocess/crystal_preferred_orientation.cc

Resized the rotation matrix vector while generating weighted outputs in Crystal preferred orientation postprocessor. Before the fix if the option of generating a weighted CPO was chosen in the input file, a segmentation fault was thrown. This PR looks to fix that
* [X ] I have followed the [instructions for indenting my code](../blob/main/CONTRIBUTING.md#making-aspect-better).
* [ X] I have tested my new feature locally to ensure it is correct.

Resized the rotation matrix vector in the weighted outputs for the CPO postprocessor

---

CONTRIBUTING.md
cookbooks/subduction_initiation/doc/subduction_initiation.md
cookbooks/vankeken_subduction/doc/vankeken_subduction.md
doc/sphinx/parameters/Initial_20composition_20model.md
doc/sphinx/user/cookbooks/geophysical-setups.md

Fix a number of small warnings when building the sphinx documentation. Mostly formatting issues, duplicated labels, forgotten includes.

Fix warnings when building documentation

---

CONTRIBUTING.md
cookbooks/subduction_initiation/doc/subduction_initiation.md

This gets rid of the following type of warnings in the documentation:
- relative links in Contributing.md dont work in sphinx, since it is included into a different file
- follow a style guide for markdown in contributing.md (empty lines around headings and lists)
- fix a table not being properly linked in the subduction initiation cookbook because of a double empty line (sphinx seems a bit picky in this case, double empty lines after figures or tables somehow break them).
@tjhei: This should allow  #5374 to move forward.

Fix documentation warnings

---

.readthedocs.yaml

sphinx doc: treat warnings as errors

---

tests/subduction_initiation_compositional_fields.prm

Follow up to #5329 as per @naliboff's comments. The complication here is that the original cookbook itself includes a basis .prm file and we do not support chain-includes (including a prm file that includes another file). But the test can include the basis file and only add the lines that are specific for this test.

Simplify test by including original prm file

---

source/simulator/stokes_matrix_free.cc

A small optimization: replacing index-based loops to range-based loops.

A small optimization: replacing index-based loops to range-based loops

---

benchmarks/grain_size_pinned_state/grain_size_plunge.ipynb
benchmarks/grain_size_pinned_state/grain_size_plunge.prm

This is a follow-up PR to #5363 that adds documentation. Specifically, it adds a jupyter notebook that computes the analytical solution that the benchmark reproduces.

add notebook for grain size plunge

---

source/particle/interpolator/bilinear_least_squares.cc
source/particle/interpolator/quadratic_least_squares.cc

I occasionally observe crashes with the particle limiter option that claim that the particle limiter did not succeed. I was finally able to track one down in the debugger and it seems that it only happens if the property to interpolate is essentially constant, and the tolerance is just barely exceeded (in my case 2e-9 instead of the 1e-9 tolerance we prescribe). This PR loosens the tolerance a bit (to around 2e-8) and binds it to the accuracy of the floating point number type used, which should hopefully take care of this. 
Also improve the error output.

Loosen tolerance for particle interpolation limiter

---

source/initial_temperature/adiabatic.cc

Without the Assert, this will simply trigger a floating point exception. I thought this would be more helpful for the user.

add a helpful error message

---

cookbooks/global_melt/doc/global_melt.prm
cookbooks/global_melt/doc/global_no_melt.prm
cookbooks/global_melt/global_melt.prm
cookbooks/global_melt/global_no_melt.prm

At the moment, this cookbook crashes on main (after a few time steps). 
This fix is in response to https://community.geodynamics.org/t/problems-with-global-melt-cookbook/3043 and https://community.geodynamics.org/t/unable-to-reproduce-global-melt-cookbook-results-in-the-aspect-manual/3093. 
As mentioned on the forum, I believe this is because of our changes to the artificial diffusion. 
To make the cookbook work again, I
- increased the resolution
- refined the mesh near the top and bottom
- increased the temperature and age of the bottom boundary (we had more conduction before with the old artificial viscosity, so the plumes on the current main are thinner/colder than they used to be, and this makes them hotter again so that there actually is some melting)
- increased the end time
I …

update global melt cookbook

---

source/mesh_deformation/interface.cc
source/simulator/core.cc
source/simulator/stokes_matrix_free.cc

Guarding #if DEAL_II_VERSION_GTE(9,6,0) blocks were added to all "constraints.reinit"

Using constraints with two index sets for dealii-9.6 only.

---

source/simulator/stokes_matrix_free.cc

This adds some asserts to find problems with wrong or poisoned values passed to the gmg solver.

Add asserts to the gmg solver to detect nan's and inf's earlier.

---

cookbooks/prescribed_velocity/prescribed_velocity.cc
cookbooks/prescribed_velocity_ascii_data/prescribed_velocity_ascii_data.cc

When working on a project I noticed that the prescribed velocities within the domain where a multiple of the prescribed value too high, and that the multiple was the number of nonlinear iterations. When using a defect correction Stokes (which includes the Newton Stokes), this should only be added at nonlinear iteration 0.
I am not sure if there is a cleaner way of checking this then what I am currently doing, so I am open to suggestions.

Fix prescribed velocity cookbooks for dc stokes

---

Jenkinsfile

@MFraters it looks like you updated the email you use for your git commits. This updates the configuration of the Jenkins tester to run your PRs without waiting for the ready-to-test label. Are you ok with this change?

Update email for Jenkins tester configuration

---

source/particle/interpolator/harmonic_average.cc

Check that particle properties in neighboring cells are larger than zero before harmonically averaging them. This is already done for the current cell since #5359.

Also add check for harmonic averaging of properties in neighboring cells

---

source/simulator/core.cc

While working on the failing tests in #5398; see also #5405.

Some changes in compute_current_constraints().

---

benchmarks/shear_bands/shear_bands.cc

Fixes #5423. There is a test that runs this benchmark, so the fix is also tested.

Fix a memory leak.

---

source/geometry_model/chunk.cc

There is a comment above this place that explains that we only support two cases. Make this explicit.

Add an assertion.

---

.github/dependabot.yml

Took over the settings from deal.II to get dependabot alerts for outdated github actions. This should keep us more up-to-date with the versions of github actions we use.

Add dependabot settings for github actions

---

.github/workflows/linux.yml

One step closer to move forward with #5367. Add a new tester with 9.5, use 9.5 for indent checking and non-unity build. Does not yet update the reference test results and reference tester, I will do this in a follow-up PR.

Add a new tester with deal.II 9.5

---

source/particle/property/crystal_preferred_orientation.cc

As noted in #3885  and #5361, the cpo code is not ready for use. This adds a clear warning for potential users. Let me know if it also needs to go in other places.

Add warning that CPO plugin in still a work in progress.

---

tests/diffusion.prm
tests/diffusion_velocity.prm
tests/maximum_refinement_function.prm
tests/maximum_refinement_function_cartesian.prm
tests/maximum_refinement_function_spherical.prm
tests/minimum_refinement_function.prm
tests/minimum_refinement_function_cartesian.prm
tests/minimum_refinement_function_spherical.prm
tests/minimum_refinement_function_time_dependent.prm
tests/passive_comp.prm
tests/tangurnis_ba.prm
tests/tangurnis_ba_custom.prm
tests/tangurnis_tala.prm
tests/tangurnis_tala_c.prm
tests/tangurnis_tala_implicit.prm

While working on something else I saw these outdated comments in many of our test prm files. They were created from the parameters.prm output of models, and so they contain all parameter documentation as well. That doesnt matter for most parameters, because their description rarely changes, but the list of available models changes a lot, and if someone starts a new model from one of the test files, we want to avoid having wrong comments in these files. I purely removed the same sort of comment here ("Select one of the following models: ...").

Clean test parameter files of outdated comments

---

contrib/utilities/jsontomarkdown.py
source/boundary_composition/function.cc
source/boundary_heat_flux/function.cc
source/boundary_temperature/function.cc
source/boundary_velocity/function.cc
source/gravity_model/function.cc
source/heating_model/function.cc
source/initial_composition/function.cc
source/initial_temperature/adiabatic.cc
source/initial_temperature/function.cc
source/mesh_deformation/function.cc
source/mesh_refinement/maximum_refinement_function.cc
source/mesh_refinement/minimum_refinement_function.cc
source/particle/generator/probability_density_function.cc
source/particle/property/function.cc
source/prescribed_stokes_solution/function.cc

We use backticks in the parameter documentation for two things:
1. We use it for latex style single quotes `` `Howdy!'``
2. We now use it for sphinx commands like ``{ref}`bla` ``
The jsontomarkdown.py unconditionally replaces all backticks by ``&lsquo;``, which makes 1. render correctly, but obviously breaks 2. Note that PRs like #5285 manually replaced the text in the automatically generated .md files.
Instead, I propose the following:
1. If you want to use backticks to issue sphinx commands, they need to be escaped using ``\`` (which means ``\\`` inside a string in a .cc file).
2. All other backticks will be rendered literally like before

Parameter doc no escape backtick

---

doc/modules/changes/20230802_gassmoeller
include/aspect/boundary_composition/spherical_constant.h
include/aspect/boundary_temperature/spherical_constant.h
source/boundary_composition/spherical_constant.cc
source/boundary_temperature/spherical_constant.cc
tests/gmg_velocity_boundary_2d_box_no_flux.prm
tests/gmg_velocity_boundary_2d_box_no_normal_flux.prm
tests/gmg_velocity_boundary_3d_box_no_flux.prm
tests/gmg_velocity_boundary_3d_box_no_normal_flux.prm
tests/shell_boundary_composition_spherical_constant.prm
tests/shell_boundary_composition_spherical_constant/screen-output

The 'spherical constant' boundary temperature and composition plugins currently does a lot of string comparisons when returning the boundary values, so many that they show up when profiling instantaneous models. The gain for the overall model is not huge, but it is a simple change that makes the plugin more similar to the way the box plugins are written already.
I also removed the `minimal_composition` and `maximal_composition` functions from the boundary composition plugin. I think they were copy-pasted from the temperature plugin, because such functions are not defined in the composition interface, and they are nowhere used.
@jdannberg I know you had looked at these plugins before, can you take a look at this?

Avoid string comparisons in spherical constant boundary temperature plugin

---

include/aspect/particle/world.h

I have no idea whether this is going to make any difference with the issue @ryanstoner1 sees, but thought I'd give this a try on general principle. The order of declarations in the `World` class is first the property manager and then the particle handler. They are destroyed in the opposite order. This seems wrong. So re-order these two variables.

Re-order particle world member variables.

---

include/aspect/structured_data.h
source/structured_data.cc

- Move code from StructuredData::load_file() into load_ascii()
- Add documentation
(netcdf handling not yet included here)
part of #5447

StructuredData: refactor and document

---

benchmarks/solitary_wave/solitary_wave.cc
include/aspect/boundary_velocity/gplates.h
include/aspect/initial_temperature/S40RTS_perturbation.h
include/aspect/material_model/steinberger.h
include/aspect/material_model/utilities.h
include/aspect/parameters.h
include/aspect/structured_data.h
include/aspect/utilities.h
source/boundary_velocity/gplates.cc
source/initial_temperature/S40RTS_perturbation.cc
source/initial_temperature/SAVANI_perturbation.cc
source/material_model/steinberger.cc
source/material_model/utilities.cc
source/postprocess/matrix_statistics.cc
source/simulator/parameters.cc
source/structured_data.cc
source/utilities.cc
tests/solidus_initial_conditions.cc
tests/stokes_solver_fail_A/screen-output
tests/stokes_solver_fail_S/screen-output

This mirrors what we did in deal.II a while ago: in MPI implementations MPI_Comm is a simple value (typically int or pointer) that we should pass by value. Otherwise, returning references of ``get_communicator()`` functions can be complicated to implement.

pass MPI_Comm by const value

---

contrib/docker/docker/Dockerfile

part of #5447
This image installs deal.II from Ubuntu packages, so we can just install the system netcdf and it works (I checked).
@gassmoeller Can you update the image as well? Or is it built automatically?

docker image: add netcdf

---

.readthedocs.yaml

This essentially reverts #5375 for now. I know we want the pdf docs, but I dont have time to fix them right now, and it looks like the online html doc was not properly rebuilt since #5375 was merged (it lists Aug 23 as last updated date).

Disable pdf sphinx documentation for now

---

include/aspect/geometry_model/sphere.h
include/aspect/geometry_model/spherical_shell.h
source/geometry_model/sphere.cc
source/geometry_model/spherical_shell.cc

The Triangulation class copies them anyway when calling set_manifold(), so we need to store a manifold object anywhere in the geometry models.
This patch addresses the `SphericalShell` and `Sphere` models. The `Chunk` model and variations also store manifolds, but in a more intricate way, and I will have to address that in separate pull requests because I think that they way they do that lends itself to complications.
First small part towards #5241.

Do not store manifolds in geometry models.

---

include/aspect/geometry_model/chunk.h
include/aspect/geometry_model/two_merged_chunks.h
source/geometry_model/chunk.cc
source/geometry_model/two_merged_chunks.cc
tests/natural_coordinates_conversion.cc

Both of the chunk geometry variations have a function `set_topography_model()` that is, however, not used anywhere other than in one test where we set a zero topography -- which should not actually do anything useful.
As mentioned in #5467, I would like to get rid of explicitly storing manifolds because this leads to problems: What matters is the state of the manifold object *when we create the triangulation* because the triangulation copies the manifold. Storing a manifold explicitly invites problems when one later modifies the manifold and expects that that affects what the triangulation sees. It's better to get rid of the explicit objects, and removing these functions is one step towards that goa.

Remove a function that is never used.

---

include/aspect/geometry_model/two_merged_boxes.h
include/aspect/geometry_model/two_merged_chunks.h

Specifically, in these two cases, the functions are 'private', so could only possibly be usefully marked 'virtual' if that interface existed in the base class -- but it doesn't. I think it was simply a mistake to mark them as 'virtual' to begin with.

Do not mark functions as 'virtual' if not necessary.

---

source/material_model/entropy_model.cc
source/simulator/helper_functions.cc
tests/entropy_initial_lookup.prm
tests/entropy_initial_lookup/screen-output
tests/entropy_initial_lookup_wb.prm
tests/entropy_initial_lookup_wb/screen-output

The entropy material model requires iterating over advection and Stokes equations (because temperature diffusion is computed split from entropy advection). This was not asserted so far and has let to problems with temperature overshoot in other solver schemes. Also assert that the projected density mass conservation formulation always uses a compressible material model.
@jdannberg, @RanpengLi does this make sense?

Ensure correct solver scheme for PDA

---

include/aspect/geometry_model/chunk.h
include/aspect/geometry_model/two_merged_chunks.h
source/geometry_model/chunk.cc
source/geometry_model/two_merged_chunks.cc

Rather, create it where necessary.
This is a follow-up to #5467 for the `Chunk` geometry. It makes sure that we only create a manifold object in the `create_geometry()` function, from which the `Triangulation` will then copy it. In all of the other places where we require a manifold object, we ask the triangulation for it.

Do not keep around a manifold object in the Chunk class.

---

include/aspect/geometry_model/ellipsoidal_chunk.h
source/geometry_model/ellipsoidal_chunk.cc
tests/ellipsoidal_chunk_geometry.cc

In Chunk, the manifold class is in a namespace 'internal'. Here, it was within the 'EllipsoidalChunkGeometry'. Move it out of the main class and into an 'internal' namespace.
There are no functional changes in this patch, just moving code around.

Make EllipsoidalChunkGeometry look more like Chunk.

---

source/mesh_deformation/interface.cc

This PR simplifies the code to use `std::make_unique` instead of `std::unique_ptr`

code cleanup.

---

.github/workflows/linux.yml
contrib/ci/Dockerfile

Follow up to #5487
Adress part of #5447.
The deal.II 9.4 tester is done, I am rebuilding 9.5 right now, I will retrigger the tests for this PR tomorrow when that is done.

Update tester images with netcdf

---

contrib/docker/tester/Dockerfile

Supports #5484.
Deal.II 9.4 and 9.5 images are already updated. Once this is merged the development image should be rebuild over night.

Add NETCDF_DIR variable to tester image

---

.github/workflows/linux.yml

For a while the github actions tester has not uploaded artifacts of the build to its webpage. I think this might be the reason. Let's see if this fixes it.

Fix tester artifact upload

---

include/aspect/geometry_model/spherical_shell.h
source/geometry_model/spherical_shell.cc

More in relation to #5421.
This patch does two things. It moves the declaration of the `SphericalManifoldWithTopography` class into the `.h` file, and then it gives the `SphericalShell` geometry model a permanent manifold object. This is exactly in line with how the `Chunk` and `TwoMergedChunks` models do things, so the primary purpose of this patch is to make the structure like it is in other classes that already support surface topographies -- doing the same thing the same way in different places in a virtue.

Towards a SphericalShellWithTopography.

---

.github/workflows/linux.yml

#5496 fixed one of the issues with the artifact upload from github actions, however there is a second one. There is a incompatibility between the git versions on the actions runner, and inside our test container that leads to error messages if we try to diff the test results with the reference results (see https://github.com/geodynamics/aspect/actions/runs/6893928842/job/18754607549?pr=5498#step:7:16).
This is an attempt to fix this.

Fix for git incompatibility

---

benchmarks/annulus/doc/annulus.md
benchmarks/annulus/transient/plot_transient_convergence.py
benchmarks/annulus/transient/transient_annulus.prm
benchmarks/rigid_shear/doc/rigid_shear.md
benchmarks/rigid_shear/transient/plot_transient_convergence.py
doc/sphinx/references.bib
tests/annulus_transient.prm
tests/annulus_transient/screen-output

Some updates to the transient versions of the "annulus" and "rigid shear" benchmarks to make them more similar to the versions submitted [here](https://egusphere.copernicus.org/preprints/2023/egusphere-2023-2765/). All of these changes are purely documentation, except for the change to the `IDR(s)` parameter in the annulus benchmark. I noticed that the default value of the `IDR(s)` parameter no longer converges to a linear solver tolerance of 1e-12 for very coarse resolutions. The tolerance plateaus somewhere around 1e-10. By itself that is not a problem, because it is smaller than our default linear Stokes solver tolerance, but this benchmark requires a high precision of the Stokes solution. Setting the parameter to 4 lets the solver converge further. I think we should consider making 4 …

Update particle benchmark documentation

---

include/aspect/compat.h
source/compat.cc

#5474 added a copy of `SphericalManifold` to ASPECT because of the broken interface in deal.II releases. This patch adds `#if` guards on the deal.II version to make sure we know when we can remove these things again.
Related to #5421.

Make sure stuff in compat.h/cc is guarded by a deal.II version.

---

doc/modules/changes/20231128_bangerth
include/aspect/postprocess/visualization.h
include/aspect/postprocess/visualization/ISA_rotation_timescale.h
include/aspect/postprocess/visualization/artificial_viscosity.h
include/aspect/postprocess/visualization/artificial_viscosity_composition.h
include/aspect/postprocess/visualization/boundary_indicator.h
include/aspect/postprocess/visualization/error_indicator.h
include/aspect/postprocess/visualization/grain_lag_angle.h
include/aspect/postprocess/visualization/particle_count.h
include/aspect/postprocess/visualization/seismic_anomalies.h
source/postprocess/visualization.cc
source/postprocess/visualization/ISA_rotation_timescale.cc
source/postprocess/visualization/artificial_viscosity.cc
source/postprocess/visualization/artificial_viscosity_composition.cc
source/postprocess/visualization/boundary_indicator.cc
source/postprocess/visualization/error_indicator.cc
source/postprocess/visualization/grain_lag_angle.cc
source/postprocess/visualization/particle_count.cc
source/postprocess/visualization/seismic_anomalies.cc

Inspired by #5488, these are the only places I could find where we still call `operator new` explicitly. This is, strictly speaking, an incompatible change because it changes the interface of a plugin system. Thoughts?

Avoid the use of raw pointers. Use std::unique_ptr instead.

---

source/geometry_model/chunk.cc
source/geometry_model/two_merged_chunks.cc
source/mesh_deformation/interface.cc

I think this function better expresses what it is we are testing. The `dynamic_cast` we've been using in these places of course has the same effect, but it does not express quite as concisely the question we are asking.

Make better use of Plugins::plugin_type_matches().

---

source/geometry_model/chunk.cc

I thought for a moment that we can omit the call to `GridTools::transform()` if we use a `ZeroTopography`, but that is not in fact true. Might as well describe the code better. Seen while thinking about #5421.

Better describe what a piece of code is doing.

---

.github/workflows/linux.yml

This is a follow-up to #5499, after Wolfgang observed in #5512 that we still get warnings. I didnt notice before that the `generate_reference_output` target already calls git commands. The temporary git config change has to happen, before we can execute any git commands inside the tester container.

Fix tester warning

---

include/aspect/material_model/latent_heat_melt.h
include/aspect/material_model/melt_boukare.h
include/aspect/material_model/melt_global.h
include/aspect/material_model/melt_simple.h
include/aspect/melt.h

I tend to read the list of base classes of a class as from most to least important -- perhaps that's just me, but I was surprised to find cases where we have `SimulatorAccess` in the middle of two material model-related base classes of the melt models.
So sort things. While there, also document the `MeltFractionModel` class a bit better.

Sort the order of base classes.

---

include/aspect/melt.h
source/initial_composition/porosity.cc
source/postprocess/melt_statistics.cc
source/postprocess/visualization/material_properties.cc
source/postprocess/visualization/melt_fraction.cc

`plugin_type_matches()` is intended to check whether a concrete plugin object (provided via a reference to an `Interface<dim>` base class) is in fact of a specific type `TestType`. But we have a few places where we are using this function to check whether a concrete plugin object is in fact *also* derived from a class that is not part of the `Interface<dim>` hierarchy -- i.e., a second base class. This is not what `plugin_type_matches()` was meant to do, and that I would like to rule out in a follow-up patch.
The only place where we so abuse `plugin_type_matches()` is in the melt sub-system. This patch uses the better suited `dynamic_cast` approach (which is internally used in `plugin_type_matches()`) to encode the test we really want.

Avoid the use of plugin_type_matches() where not appropriate.

---

doc/modules/changes/20231207_bangerth
include/aspect/geometry_model/chunk.h
include/aspect/geometry_model/two_merged_chunks.h
source/geometry_model/chunk.cc
source/geometry_model/two_merged_chunks.cc

In working on #5421, I'm looking at the way the existing geometry models with topography access the manifold. In doing so, I came across the fact that the `Chunk` and `TwoMergedChunks` models have a member function `depth_wrt_topo()`, which seems to be a useful question to ask -- but these functions are not used anywhere and we've generally found that (i) functions that are not used or tested accumulate bugs over time, (ii) if they exist in one model, someone might expect them to exist in other models as well where they may be much more difficult to implement.
For these reasons, this patch simply removes this function from the two models in question.

Remove an unused function from two geometry models.

---

include/aspect/postprocess/visualization.h

The meaning of the bool variable `output_undeformed_mesh` was switched in the header file comment.

Fix comment output undeformed mesh

---

include/aspect/mesh_deformation/fastscape.h
source/mesh_deformation/fastscape.cc

Hi all, here are some minor changes to the fastscape plugin to fix some warnings and rename Qtrapez to Qtrapezoid. Also, this adds the flag so the plugin can use the free surface stabilization.
* [x ] I have read the guidelines in our [CONTRIBUTING.md](../blob/main/CONTRIBUTING.md) document.
* [x ] I have followed the [instructions for indenting my code](../blob/main/CONTRIBUTING.md#making-aspect-better).

Fastscape: Rename Qtrapez function, fix some warnings, and add stabilization flag.

---

include/aspect/boundary_traction/initial_lithostatic_pressure.h
source/boundary_traction/initial_lithostatic_pressure.cc

This is a follow-up to #5089. If traction is prescribed on the bottom boundary, we want it to be the same traction all along the boundary according to the deepest pressure calculated at the reference horizontal coordinates. However, when variable initial topography is applied, points whose horizontal coordinates do not coincide with reference point will have a depth that does not equal the deepest depth of the pressure profile. Therefore, with this PR, if non-zero initial topography is applied, and if the bottom boundary is the only boundary with prescribed initial lithostatic pressure tractions, then we directly return the deepest pressure instead of looking up the current point's depth within the pressure profile.

Use the deepest initial lithostatic pressure on the bottom traction boundary

---

include/aspect/boundary_composition/interface.h
include/aspect/boundary_temperature/interface.h
include/aspect/boundary_velocity/interface.h
include/aspect/heating_model/interface.h
include/aspect/initial_composition/interface.h
include/aspect/initial_temperature/interface.h
include/aspect/mesh_deformation/interface.h
include/aspect/mesh_refinement/interface.h
include/aspect/particle/property/interface.h
include/aspect/postprocess/interface.h

This is similar to #5522. We have a bunch of places where you can ask whether a plugin manager has a plugin of a specific type. This will always return `false` if the given type is not in the right class hierarchy (i.e., if it is not derived from `Interface<dim>` in this namespace) and likely represents a programming mistake. This patch only enables the function to be called if the given type is derived from `Interface<dim>`.
In the long run, all of these things will be better implemented by C++20 `requires` clauses. But we can't use that yet.

Restrict the types accepted by has_matching_*() and get_matching_*().

---

include/aspect/boundary_traction/initial_lithostatic_pressure.h
source/boundary_traction/initial_lithostatic_pressure.cc

Small follow-up to #5520. Initalize variable value in correct place, and remove implementation details from variable documentation.

Improve initialization of variable

---

source/material_model/visco_plastic.cc
source/simulator/parameters.cc

According to @bobmyhill, these TODOs were discussed at the 2023 Hackathon and dismissed because they are not backwards compatible.

Remove TODOS that are backwards incompatible

---

source/main.cc

Based on a question on the forum yesterday.

Improve the error message when dlopen fails.

---

include/aspect/geometry_model/spherical_shell.h
source/geometry_model/spherical_shell.cc

This patch does not actually do anything, but it inserts the necessary calls for pushing forward the geometry and pulling it back to most of the places where this is necessary.

Next step towards equipping the sphere with topography.

---

include/aspect/mesh_deformation/interface.h
include/aspect/stokes_matrix_free.h
source/mesh_deformation/interface.cc
source/simulator/stokes_matrix_free.cc

This PR uses the `MGTransferMF` class from deal.ii instead of `MGTransferMatrixFree` to address the #5504.
We get the following error when we use GMG with mesh deformation (test: `gmg_mesh_deform.prm`) using the current master version of deal.ii and this PR:
```
An error occurred in line <970> of file </home/arushi/opt/dealii/include/deal.II/lac/la_parallel_vector.templates.h> in function
void dealii::LinearAlgebra::distributed::Vector<Number, MemorySpace>::compress_start(unsigned int, dealii::VectorOperation::values) [with Number = double; MemorySpace = dealii::MemorySpace::Host]
The violated condition was: 
vector_is_ghosted == false
Additional information: 
Cannot call compress() on a ghosted vector
```

Replace the matrix free class with another.

---

include/aspect/geometry_model/box.h
include/aspect/geometry_model/chunk.h
include/aspect/geometry_model/ellipsoidal_chunk.h
source/geometry_model/box.cc
source/geometry_model/chunk.cc
source/geometry_model/ellipsoidal_chunk.cc
tests/ellipsoidal_chunk_geometry.cc

The goal is to make them all look the same: They all should be handling their manifold objects the same way, for example -- create them in the same places, copy them the same way, have key member variables in the same order, etc.

Clean up some places handling initial topography in geometry models.

---

source/geometry_model/chunk.cc

I had struggled for a while to understand what the prefix `topor` was supposed to mean, until I realized it is `topo_r`. Make this easier to understand by renaming the variable.

Fix the name of a variable.

---

include/aspect/geometry_model/initial_topography_model/interface.h
source/geometry_model/initial_topography_model/ascii_data.cc
source/geometry_model/initial_topography_model/function.cc
source/geometry_model/initial_topography_model/prm_polygon.cc

We did not document very well how the initial topography models are supposed to interact with the geometry models. I think that there is some confusion with regards to coordinate systems, and at least in the `Function` model, we convert between coordinate systems in a place where we ignore a user-settable parameter to choose which coordinate system the user wants to use for the function expression.
This patch adds documentation to explain at least what I *believe* we are currently doing, and asserts that the coordinate transformation mentioned above does what is intended. I'm curious to see whether that survives the test suite.
In reference to #5421 .

Better document and check initial topography models.

---

.github/workflows/linux.yml

We have some unexplained test failures in the `indent` tester in the `compile` stage (see e.g. #5560
).  After some investigation I found this: It looks like the new cmake (3.28.2) version that was included in the github actions runner yesterday broke the compatibility of precompiled headers and unity builds (see discussion [here](https://gitlab.kitware.com/cmake/cmake/-/issues/25650)). cmake 3.28.3 should fix this, but who knows when it will be released and deployed in the actions runner. Therefore this PR tries to circumvent the problem by using the apt packaged version of cmake on the runner (that we install anyway). If this works the tester should now use cmake 3.16 which comes with ubuntu 20.04. We can revert this change later.

Use apt packaged cmake version in tester

---

source/geometry_model/spherical_shell.cc

This patch copies what we do in the `Chunk` model to query the topography to the spherical shell. As mentioned in the previous pull request, I think that there is some confusion about how the implementations of the initial topography models react to points in different coordinates, but that is a matter that needs to be addressed in a separate PR. (That will then also be the point where I can add tests.)
In reference to #5421 .

Implement calling initial topography models from the spherical shell model.

---

contrib/docker/tester/local.cfg

In order for #5367 to require sundials we need to make sure to install it inside the tester image. For some reason I thought I had done this already, but apparently we only added netcdf so far. This PR needs to be merged before we can proceed with #5367.

Add sundials to tester image

---

source/utilities.cc

deal.II has required MPI >=3.0 since before version 9.5, so we do not need this check in ASPECT anymore.
This will remove one of the problems reported in #5569, namely that MPI_VERSION_MAJOR and MPI_VERSION_MINOR is not correctly set on Stampede3 with Intel MPI 21.11 (this PR does not solve the underlying problem, but makes it so that ASPECT never requires that version information).

Remove an unnecessary check

---

CMakeLists.txt
source/global.cc

This adds the world builder to the list of reported dependency version on model start. Output looks like this:
```
-----------------------------------------------------------------------------
--                             This is ASPECT                              --
-- The Advanced Solver for Planetary Evolution, Convection, and Tectonics. --
-----------------------------------------------------------------------------
--     . version 2.6.0-pre (report_world_builder, fec55396d)
--     . using deal.II 9.5.0
--     .       with 32 bit indices and vectorization level 3 (512 bits)
--     . using Trilinos 13.2.0
--     . using p4est 2.3.2
--     . using Geodynamic World Builder 0.6.0 (main, 2d07a63e6)
--     . running in DEBUG mode
--     . running with 1 MPI process …
```

Report World Builder version on model start

---

include/aspect/particle/integrator/euler.h
include/aspect/particle/integrator/interface.h
include/aspect/particle/integrator/rk_2.h
include/aspect/particle/integrator/rk_4.h
source/particle/integrator/euler.cc
source/particle/integrator/interface.cc
source/particle/integrator/rk_2.cc
source/particle/integrator/rk_4.cc
source/particle/world.cc

This is a change to the particle advection algorithm that I wanted to implement for a while. Each particle integrator only needs a subset of the available velocity solutions on the particle location for each integrator step. E.g. the forward euler integrator only needs the old solution to move particles, while RK2 and RK4 sometimes also need particle velocities at other timesteps (depending on their integrator step). This PR implements an interface for the particle integrators to tell the particle world which velocities are needed at the current integrator step. This allows the world to only compute the velocities that are needed. 
Because of all the other operations that are needed for the advection this optimization is not huge (it saves ~5% of the particle advection time), but it is …

Only evaluate particle velocities if needed

---

source/particle/integrator/euler.cc
source/particle/integrator/rk_2.cc
source/particle/integrator/rk_4.cc

This PR makes use of dealii/dealii#16675 to make the access to particle locations more efficient in the particle integrators.

Use new deal.II function to retrieve particle location

---

source/particle/property/crystal_preferred_orientation.cc

As far as I can see these header files are not needed at the moment. They will be needed later when world builder can set initial grain orientations, but we should not require headers that are not used. Fixes #5591.

Remove unnecessary header files.

---

CMakeLists.txt

We incorrectly always only built the debug version of an external GWB version 0.6 or newer if ASPECT was in DebugRelease mode. With https://github.com/GeodynamicWorldBuilder/WorldBuilder/pull/686 we can now configure GWB twice inside the build directory of ASPECT and link to the correct library.

correctly support external GWB in DebugRelease

---

CMakeLists.txt

Newer cmake versions apparently require the attribute here. It is already present a few lines up.

Add required cmake attribute.

---

include/aspect/particle/world.h
source/particle/world.cc

For #4370 , some functionality is copied from world.cc into the particle property elastic_stress.cc. However, this requires including world.cc instead of world.h, as some functions and classes are only declared in world.cc. This PR moves the necessary class and function declaration to world.h. It shouldn't change anything.

Move internal function and class to header file world.h

---

include/aspect/material_model/rheology/visco_plastic.h
source/material_model/rheology/visco_plastic.cc
source/mesh_deformation/fastscape.cc

Since #5542, masks for compositional fields are no longer needed as the compositional field type is used to compute the volume fractions in the viscoelastic and viscoplastic material models. This PR ensures that two fields that can be used in conjunction with FastScape are not of chemical composition type. Originally, they are masked in get_volumetric_composition_mask(). I think that function be removed, but I've kept it in for now.

Check that FS sediment depth and age do not have chemical composition type

---

doc/modules/changes/20240315_gassmoeller
source/postprocess/geoid.cc

The input option 'Include the contributon from dynamic topography' in the geoid postprocessor has been deprecated and not been used for 3 years. Remove the option from the list of declared parameters (it was only left in at the time to not break existing input files).

Remove outdated input option for geoid postprocessor.

---

include/aspect/mesh_deformation/fastscape.h
source/mesh_deformation/fastscape.cc

In #5588 some code was introduced that doesn't compile. I didn't realize because the file in which the changes were made is only compiled if ASPECT links to FastScape. This PR does compile and I checked that the checks throw as expected when linked to FastScape.
This PR also fixes some typos and extens some doc strings about FastScape parameters.

Fix check field type and typos

---

doc/sphinx/parameters/Material_20model.md
source/material_model/diffusion_dislocation.cc
source/material_model/rheology/peierls_creep.cc
tests/visco_plastic_peierls_idrissi_exact.prm
tests/visco_plastic_peierls_mei_exact.prm
tests/visco_plastic_phases_peierls_mei_exact.prm

Following #5338, the default value for the parameter `Peierls strain rate residual tolerance` seemingly doesn't need to be so strict because the residual is now relative to the log of the strain rate. Opening this PR was motivated by models that I was running using the default value that could not converge, but using a value of 1e-10 - 1e-12 converged and produced negligible differences in the solution. Lowering the value should make models with Peierls creep more stable and faster when using the default value.
This PR updates the documentation of this parameter and changes the default value to mirror the changes in diffusion/dislocation merged in #5338.

Update 'Peierls strain rate residual tolerance'

---

include/aspect/material_model/entropy_model.h
source/material_model/entropy_model.cc

I made the current entropy model able to read in multiple lookup table files. This is the first step of making the entropy method able to handle multiple compositions. There is an assert throw for using more than 1 lookup files because the rest of method have not been implemented yet.

make entropy_reader a vector

---

source/simulator/helper_functions.cc

Adds a missing instantiate. Ran into this issue when trying to compile aspect on stampede3. Thanks @tjhei and @gassmoeller for the help in figuring this out!

Add explicit initialization for initialize_current_linearization_point

---

source/simulator/core.cc
source/simulator/stokes_matrix_free.cc
tests/periodic_box_gmg.prm
tests/periodic_box_gmg/screen-output
tests/periodic_box_gmg/statistics

Enable periodic boundary conditions with GMG. Note that the linear solver crashes if we have adaptive refinement across periodic boundaries. This is not that easy to fix, so this will need to happen at a later time. Instead, we detect this situation and error out.

periodic GMG

---

.vscode/cmake_configurations.json

The VS Code build variants do not include "DebugRelease". As a consequence, it would switch the build variant to Debug everytime you invoke cmake inside vscode. Fix this. This also gets rid of some other default variants.

VSCode: build configurations

---

source/simulator/stokes_matrix_free.cc

gcc warns me #5617 creates a copy  `warning: loop variable ‘p’ creates a copy from type ‘const std::pair<std::pair<unsigned int, unsigned int>, unsigned int>’ [-Wrange-loop-construct]`. Probably not very expensive, but fixing the warning anyway.

Fix compiler warnings

---

.github/workflows/typos.yml

#5600 added a typos checker, which is now failing for recent PRs. This is because so far we always use the latest release of the spell checker, which periodically changes its dictionary of typos. I would rather rely on a fixed version of the spell check and occasionally update that version. This is more similar to what we do with astyle, and it will reduce the maintenance effort of constantly fiddling with the configuration of the spell checker to make sure it doesnt flag new things, which are likely just false positives. This also allows us to use the existing Github action, and avoids using a hand-written script for reporting errors, which doesnt seem to work at the moment anyway.
Do not merge this PR, I introduced  a  typo on purpose to test the action.
@MFraters: What was the reason …

Use typos github action

---

source/heating_model/shear_heating.cc

This comment is outdated. Dislocation viscosities and boundary area work fractions were previously in this additional output, but it was reworked in #5021. What exactly happens with these outputs is described below in line 78/79.

Update outdated comment in shear heating plugin

---

source/boundary_heat_flux/function.cc
source/heating_model/adiabatic_heating.cc
source/heating_model/adiabatic_heating_of_melt.cc
source/heating_model/interface.cc
source/heating_model/latent_heat.cc
source/heating_model/latent_heat_melt.cc
source/heating_model/shear_heating.cc
source/heating_model/shear_heating_with_melt.cc
source/material_model/melt_boukare.cc
source/material_model/reactive_fluid_transport.cc
source/simulator/assemblers/newton_stokes.cc
source/simulator/assemblers/stokes.cc
source/simulator/lateral_averaging.cc
source/simulator/melt.cc
source/simulator/newton.cc

`MaterialModelOutputs` and `MaterialModelInputs` have functions to get the number of points it is supposed to be evaluated on. However, I found some old places that do not use that function and instead compute the number locally. This PR unifies the calling of this function in as many places I could find. I also removed a few checks for whether the strain_rate was provided to the material model, because since #5268 it is always provided.

Unify evaluation of number of material points

---

include/aspect/particle/world.h
source/particle/world.cc

These functions were the old (and slow) way to evaluate the solution at particle positions. They were necessary in the past, because FEPointEvaluation did not support all the mappings we use (in particular MappingCartesian) and prior to deal.II 9.4 there was a bug in FEPointEvaluation if evaluation started not a the first component of an FESystem. Both limitations have been fixed for a while and I couldnt think of (or find) any configuration in which we would still need the old code path. I still left an assert in that ensure we will not use the slow path of FEPointEvaluation (which is even slower than the implementation I am removing here). This will make sure that if someone uses an exotic mapping in the future, or other conditions change we at least learn about it.

Remove unused particle code path

---

contrib/install/local.cfg

The changes in .2 are fairly small and we are likely not affected, but it doesn't hurt being on the latest version.

candi local.cfg: use deal.II 9.5.2

---

source/simulator/core.cc

We now require deal.II 9.5, so this check is no longer needed.

Remove an outdated version check.

---

source/utilities.cc

part of  #5656.
As far as I can see, we don't call this function to begin with from anywhere. But if we ever do, make sure it is only in a 3d context.

Ensure we only run the WGS84 code if in 3d.

---

include/aspect/utilities.h
source/material_model/rheology/elasticity.cc
source/particle/property/cpo_elastic_tensor.cc

Something I noticed while reviewing #4370. We have quite a number of places in the code where we create Tensors from arrays or vectors, or unroll Tensors into arrays or vectors. We could simplify this using Tensor constructors, and appropriate `unroll` functions. Such functions are already provided by deal.II for the `Tensor` class, but they dont exist for `SymmetricTensor`. I here created small utility functions for `SymmetricTensor`, but of course it would be nice to use a version inside deal.II. Would that be of interest?
I can extend this PR to simplify a lot of places in ASPECT with the utility functions, but I first wanted to ask for feedback if the current interface is correct and if this is useful overall.

Simplify creating and unrolling symmetric tensors

---

source/material_model/grain_size.cc

There were several places in the grain size material model where we stored the adiabatic pressure in a new variable, even though the pressure that is handed over to these function from evaluate() is already the adiabatic pressure (computed in line 814-818).

Cleanup: remove repeated adiabatic_pressure variables in grain size model

---

include/aspect/material_model/interface.h

This has long passed the stage of being a simple collection of variables, so make it into a `class` whose members are `public`. I might change this later and make some of the things `private`, but that's a later problem to deal with.
astyle is weird in that it indents things without access specifiers by two spaces, but if you add an access specifier such as `public:`, it uses 4 spaces. The *actual* changes here are small, even though the diff looks large.

Make a 'struct' into a 'class'.

---

benchmarks/entropy_adiabat/plugins/entropy_advection.cc
include/aspect/introspection.h
source/material_model/diffusion_dislocation.cc
source/material_model/multicomponent.cc
source/material_model/rheology/friction_models.cc
source/material_model/steinberger.cc
source/material_model/visco_plastic.cc
source/material_model/viscoelastic.cc
source/simulator/introspection.cc

This PR improves the functionality inside the `Introspection` class to retrieve the names or indices of certain field types. In particular it changes:
- some functions now return references instead of copies of vectors, saving on dynamic allocations
- the information returned in a number of functions is now precomputed on model start, which makes returning this information much faster (no more `push_back` into a vector which is then returned by-value)
This PR should allow to retrieve this information quickly even in loops over cells without significant performance penalty.
This should help somewhat with an application in #4370.
@anne-glerum, @jdannberg or @bobmyhill could you take a look at  this PR?

Improve functions to retrieve fields of certain type from introspection

---

source/postprocess/visualization.cc

In .cc files, there is no real reason to use named namespaces for internal stuff.
@anne-glerum This will conflict with #4061. I don't care which patch gets merged first (the other one will have to make a minor change), I just wanted to get this off my hard drive :-)

Use an anonymous namespace instead of a named namespace.

---

contrib/world_builder/CMakeLists.txt

This is fixing applying the fix from https://github.com/GeodynamicWorldBuilder/WorldBuilder/pull/714, which is resolving https://github.com/geodynamics/aspect/pull/5164#issuecomment-2135777435.
It removes the explicit setting of -lc++ and -lstdc++ from the cmake compiler options.

Backporting removing -lc++ and -lstdc++ from world builder cmake.

---

include/aspect/material_model/reactive_fluid_transport.h
source/material_model/reactive_fluid_transport.cc
tests/tian_MORB/screen-output
tests/tian_gabbro/screen-output
tests/tian_peridotite/screen-output
tests/tian_sediment/screen-output

The polynomials used in the Tian parameterization for reactive two phase flow break down above certain pressures for each lithology, and the maximum bound water content becomes infinite. This PR ensures that the polynomial does not break down above these pressures by setting the pressure equal to the pressure just before the break down. An example of how this fix impacts the PT space for gabbro is shown below.
The python script that was used to determine these cutoff pressures can be found in the zip below. 
[Tian_water_content.py.zip](https://github.com/geodynamics/aspect/files/15491255/Tian_water_content.py.zip)

Add cutoff pressures to tian parameterization

---

cookbooks/finite_strain/doc/finite_strain.cc
cookbooks/finite_strain/finite_strain.cc
source/material_model/rheology/strain_dependent.cc
source/particle/property/integrated_strain.cc
tests/simple_shear.cc
tests/simple_shear_output_the_mobility.cc

This PR is similar to #5640, except it only uses the existing unroll functions and constructors of the `Tensor` class to simplify the creation and unrolling of tensors from and into compositional fields.

Use constructor and unroll function for tensors

---

contrib/world_builder/CMakeLists.txt

The same changes as in https://github.com/GeodynamicWorldBuilder/WorldBuilder/pull/715, but applied to the aspect world builder version. Passes all tests there.
Follow up to https://github.com/GeodynamicWorldBuilder/WorldBuilder/pull/714, based on a comments by @tjhei and @bangerth in https://github.com/geodynamics/aspect/pull/5669.
The C++ version is already set globally, so these local c++14 marks should not have an effect. Also added a cmake setting to turn off any compiler extensions, since this reduces the portability of the code.

backport gwb simplify cmake c++ version enforcement.

---

include/aspect/material_model/interface.h
source/heating_model/adiabatic_heating_of_melt.cc
source/heating_model/shear_heating_with_melt.cc

I broke this into 3 individual commits for the reasons mentioned in #5665: the middle commit is basically all whitespace changes, whereas the first and the third together hide the array from the `public` interface.

Make a struct a class, complete with 'public:' specifier.

---

doc/modules/changes/20240530_dannberg
include/aspect/material_model/grain_size.h
source/material_model/grain_size.cc
tests/grain_size_crossed_transition.prm
tests/grain_size_crossed_transition/screen-output
tests/grain_size_crossed_transition/statistics
tests/grain_size_latent_heat.cc

This PR makes the reset of the grain size at phase transitions now only depend on the velocity of the material moving through a transition (and how far away from the transition it is) rather than on a somewhat arbitrary 'transition width' parameter. I am attaching the graphical output of the test case I made below, which clearly shows that the new feature works as intended. 
This also has the advantage that we can use the phase function class from the material model utilities in this material model in the future (to replace the hand-written phase function).

Make reset of grain size at phase transitions only depend on velocity

---

.github/workflows/build_tester_base_image.yml

Usually the deal.II master image for the tester is built daily. However, in the past days we had two times the situation that the image had a bug that would cause all runs with the tester to fail. It was fast to fix these problems, but then we had to wait and live with a broken tester until the image was rebuild at the end of the day. This PR adds the option to trigger the build of a new image manually. It is still built daily by default.

Allow triggering the deal.II master tester image build

---

source/simulator/newton.cc

This is a follow-up to #5671. The description in the parameter documentation does not match what is actually implemented, and I chose to be more vague about the exact formula because I think that it matters more that we convey they idea than the detailed formula.

Better document the SPD safety factor.

---

source/utilities.cc

This is another follow-up to #5671 and @YiminJin 's patches in #5580 (and following #5555).
@YiminJin 's choice of alpha was demonstrably better than what was implemented before, but I can not quite convince myself that it chooses alpha=1 correctly. To wit, the previous condition for alpha=1 was
```
if (a_colon_b < eta * SPD_safety_factor)
return 1.0;
```
But, the whole machinery is only necessary if `a:b < 0`, which is the strain rate weakening case. If the material is strain rate hardening (`a:b>0`), Newton's method should always be ok. But the condition above gets this wrong I believe. It uses the full Newton step *always* for `a:b < 0`, which I think is wrong. Furthermore, it *never* chooses alpha=1 if `a:b` happens to be large, which is the uncritical case.
This patch fixes this, and …

Try a better choice for the SPD factor in Newton's method.

---

doc/modules/changes/20240531_dannberg
include/aspect/material_model/grain_size.h
include/aspect/material_model/utilities.h
source/material_model/grain_size.cc
source/material_model/utilities.cc
tests/grain_size_crossed_transition.prm
tests/grain_size_latent_heat.cc
tests/grain_size_phase_function.prm
tests/grain_size_phase_function/screen-output
tests/grain_size_phase_function/statistics

This pull request changes the grain size material model to use the phase function from the material model utilities rather than implementing its own phase function. This should not change any of the functionality, but it changes how phase transitions have to be specified in the input file (see changelog entry).
Output of the test case is below (in higher resolution)

Cleanup: use PhaseFunction class in grain size material model

---

contrib/world_builder/CMakeLists.txt

I get warnings running cmake that the cmake version still supported by WorldBuilder is too old and will soon be dropped. This patch just increases the minimum required version to the same of ASPECT.

Avoid a warning about cmake backward compatibility.

---

source/particle/property/cpo_elastic_tensor.cc

Following issue #3885 and PR #5116, I added some changes to the cpo elastic tensor to be able to use it:
1. The plugin name is changed from "cpo" to "crystal preferred orientation".
2. In the initialization stage of cpo elastic tensor, the default deformation type is -1. Under this condition computing the voigt average is not implemented yet. I changed to use the olivine stiffness matrix instead of using voigt_average_elastic_tensor.

Change plugin name in cpo elastic tensor and use olivine stiffness matrix in initialization

---

doc/sphinx/user/extending/plugin-types/material-models.md
include/aspect/material_model/interface.h
include/aspect/material_model/utilities.h
source/material_model/interface.cc

fixes warnings introduced in  #5665

fix struct->class MaterialModelOutputs

---

contrib/python/scripts/pyvista_2D_annulus_example.py

Added a visualization script in pyvista that plots spherical annulus models and computes radial and angular velocities and plots them. A sample .prm to use the script on can be generated from the onset-of-convection cookbook and changed in the ways described in the bottom comments of the script. 
* [ X] I have read the guidelines in our [CONTRIBUTING.md](../blob/main/CONTRIBUTING.md) document.
* [X ] I have followed the [instructions for indenting my code](../blob/main/CONTRIBUTING.md#making-aspect-better).
* [X ] I have tested my new feature locally to ensure it is correct.
* [ X] I have [created a testcase](https://aspect-documentation.readthedocs.io/en/latest/user/extending/testing/writing-tests.html) for the new feature/benchmark in the [tests/](../blob/main/tests/) directory.
* [X ] …

Add pyvsita 2D annulus example

---

CMakeLists.txt

(sitting on top of #5709)
part of #5697

always create parameters.json as a post-build step

---

doc/modules/changes/20240601_gassmoeller
include/aspect/parameters.h
include/aspect/utilities.h
source/particle/interpolator/bilinear_least_squares.cc
source/particle/interpolator/quadratic_least_squares.cc
source/simulator/core.cc
source/simulator/parameters.cc
source/simulator/solver.cc
source/utilities.cc
tests/discontinuous_composition_bound_preserving_limiter_selected_fields.prm
tests/discontinuous_composition_bound_preserving_limiter_selected_fields/screen-output
tests/discontinuous_composition_bound_preserving_limiter_selected_fields/statistics

Currently the DG limiter can only be enabled for all compositional fields, or no fields. This PR allows to switch it on selectively for some fields. However, it is not working yet, and I dont see why. At the moment for the attached test it does not seem to limit anything. I will look more into it tomorrow.
@anne-glerum: FYI

Make dg limiter field specific

---

doc/modules/changes/20240601_bangerth
source/postprocess/visualization.cc
tests/parallel_output_group_0/solution/solution-00000.pvtu
tests/parallel_output_group_0/solution/solution-00001.pvtu
tests/parallel_output_group_1/solution/solution-00000.pvtu
tests/parallel_output_group_1/solution/solution-00001.pvtu
tests/parallel_output_group_2/solution/solution-00000.pvtu
tests/parallel_output_group_2/solution/solution-00001.pvtu

We had an ordering problem in that we first create the `.pvtu` file and only then populated fields in the `VtkFlags` structure that is used in determining metadata for the `.pvtu` file. This is easily fixed by moving the code blocks into their correct order. As a result, we now put physical units also into the `.pvtu` file:
```
<?xml version="1.0"?>
<VTKFile type="PUnstructuredGrid" version="0.1" byte_order="LittleEndian">
<PUnstructuredGrid GhostLevel="0">
<PPointData Scalars="scalars">
<PDataArray type="Float32" Name="velocity" NumberOfComponents="3" format="ascii" units="m/year"/>  *********
<PDataArray type="Float32" Name="p" format="ascii" units="Pa"/>                                    *********
<PDataArray type="Float32" Name="T" format="ascii" units="K"/> …
```

Make sure we set flags before we use them to output physical units.

---

CMakeLists.txt

This is a preparatory step for #3448. It breaks the list of source files into the ones that we need for an aspect library, the aspect executable, and the unit tests. Right before we use these, I combine them into the existing variable so as not to step on #5712, but the `TARGET_SRC` library can later easily be removed and replaced by the relevant pieces.

Break TARGET_SRC into different categories.

---

source/mesh_deformation/interface.cc

Clear the user constraints to avoid cycled constraints in certain cases.

GMG mesh displacement: clear user constraints

---

include/aspect/material_model/reactive_fluid_transport.h
source/material_model/reactive_fluid_transport.cc

The compaction viscosity for the reactive fluid transport model has no input parameters to limit its value. This PR simply adds the same functionality used to limit the shear viscosity in other parts of the code to the compaction viscosity.

Add min/max bounds to the compaction viscosity

---

tests/melt_restart.prm

Previously, this test checkpoints every 1 seconds of wall time. This means the test sometimes fails if the tester manages to finish the first timestep in less then one second.

fix brittle test melt_restart

---

include/aspect/material_model/interface.h
source/material_model/interface.cc
source/material_model/rheology/elasticity.cc
source/postprocess/heat_flux_map.cc
source/postprocess/visualization/material_properties.cc
source/simulator/assembly.cc
source/simulator/entropy_viscosity.cc
source/simulator/stokes_matrix_free.cc

This pull request makes sure that the cell-wise averaging of material properties only averages the viscosity if the viscosity is actually computed in the material model (as indicted by `in.requests_property(MaterialModel::MaterialProperties::viscosity)`). Before this change, models with geometric averaging would crash in debug mode in case a material model did not compute the viscosity (for me, this happened with the steinberger model). This is because the viscosity is initialized with NaNs. But the `average_property` function only checks if `values_out.size() == 0` (It has a comment that says: "if an output field has not been filled (because it was not requested), then simply do nothing -- no harm no foul", but that's not what happens in the other parts of the code, the size of …

only average viscosity if the viscosity is computed in the material model

---

source/simulator/parameters.cc
tests/sea_level_postprocessor.prm
tests/sea_level_postprocessor/screen-output
tests/sea_level_postprocessor/statistics
tests/viscous_top_beam.prm

Compositional field types do not have to be specified; if they are not specified, they get the type 'unspecified' and ASPECT tries to deduce their type from their name. A field called ve_stress_xx, for example, will get the type 'stress'. If elasticity is disabled, there is at the moment no special function for fields of the type stress, which would imply this field is actually meant as a chemical composition. However, it now has the type 'stress' and is therefore not taken into account when computing material properties in the viscoelastic and viscoplastic material models. 
This PR throws if
1) Elasticity is disabled, and
2) A field of type 'unspecified' has 'stress' in its name.
It tells the user to explicitly specify the field types in the input file. 
Several tests will fail, as they …

Add Assert for stress type fields without elasticity enabled

---

contrib/python/scripts/pyvista_2d_annulus_example.py

Instead of using python list comprehensions to loop through coordinate points of a mesh object to extract the x,y coordinate points and x,y velocity components, I used the numpy array functionality to transpose the Nxd array into a dxN one (where d is the dimension and N is the number of points in the mesh) and then take the first (x-component) and second (y-component) of that transposed array which results in the same Nx1 array as before, it just looks nicer (and is potentially faster).
The images plotting the phi-component of the velocity are the same and show the before and after of making this change.
* [ X] I have tested my new feature locally to ensure it is correct.

Changed python list comprehensions into numpy array operations

---

tests/CMakeLists.txt

cmake: fix GENERATE_REFERENCE_OUTPUT for failing tests

---

include/aspect/particle/property/elastic_tensor_decomposition.h
source/particle/property/elastic_tensor_decomposition.cc
unit_tests/crystal_preferred_orientation.cc

Last major part of #3885. Adds a property plugin which can use the elastic tensor computed in #4987 to compute actual useful values from it. It requires that plugin to be present, so it is currently rebased on that. 
Since this is the last major component of the CPO plugin set, I am happy to include the integration tests within this pull request, or do that in a follow up pull request. I will include the changelog entry in the pull request where the integration tests are added, so if that is here, that will be here as well.
This pull request is ready for review, but can't be merged until #4987 is merged.

Add cpo elastic tensor decomposition plugin

---

CMakeLists.txt

It isn't quite clear what is different on my system, or why not everyone has this problem.
When you use the copy of WorldBuilder in `contrib/`, we run WorldBuilder's cmake script that creates a `config.h` in the build directory. For some reason, the path to this file is not in the include path passed to my compiler, and I think that's because we never seem to describe that path to cmake. (That's definitely true in the ASPECT `CMakeLists.txt` file. Perhaps we do that in `contrib/world_builder/CMakeLists.txt` but it's unclear to me whether that only applies to the files compiled for the WorldBuilder itself, or also for the ASPECT files. The question is whether `include_directories(...)` called in a subdirectory also affects the include path in directories higher up -- that may even depend …

Make sure the compiler finds worldbuilder/config.h.

---

include/aspect/material_model/rheology/strain_dependent.h
source/material_model/rheology/strain_dependent.cc
source/material_model/rheology/visco_plastic.cc

All other functions in strain_dependent take `j` as last index that determines the compositional field to work on, except for `compute_strain_weakening_factors`. Correct this and also improve the documentation. Technically this is an incompatible change, because the function is public, which is why I deprecated the existing function.

Reorder arguments. Improve documentation.

---

benchmarks/nsinker/nsinker.prm
tests/nsinker/screen-output
tests/nsinker/statistics

nsinker.cc says the benchmark is meant to be as defined in Rudi et al. (2017), which uses Dirichlet 0 boundary conditions. This is also consistent with the boundary conditions implemented for the sinker problem in Clevenger, Heister (2021).

change boundary conditions to dirichlet 0 for nsinker benchmark

---

source/simulator/assembly.cc

Follow-up to #5523 as suggested by @bangerth to test if something breaks when face properties for DG are only set when the FE method is specified for a compositional field. Face assemblers are also only set when FE method is selected.

Only set face properties for advection assemblers when method is fem

---

contrib/world_builder/CMakeLists.txt

A follow up to #5676  and #5669. @bangerth suggested that the -fPIC flags could also be removed. 
The -fPIC flag should be automatically set by cmake, so there is no need to specify it manually.
This is a backport of https://github.com/GeodynamicWorldBuilder/WorldBuilder/pull/736 into aspect.

backport world builder simplify cmake -fPIC

---

doc/sphinx/conf.py
doc/sphinx/index.md
doc/sphinx/user/authors.md
doc/sphinx/user/index.md

This PR addresses #5494  so that we now have authors as a separate page. Currently, the new page is under `user guide` but maybe we want to move it somewhere else (?), open to suggetions.

Add authors in a separate page.

---

include/aspect/heating_model/interface.h
include/aspect/plugins.h
source/heating_model/interface.cc
source/plugins.cc

This would take away some of the repetitiveness of the Interface classes that come
with every single one of our 23 plugin systems.
This PR is only meant as a discussion starter. Does this go in the right direction?
If I carried this through all 23 plugin systems, it would remove a whole bunch
of code where all we do is declare empty functions to define an interface. This
repetitiveness can be avoided.
I'm mindful that having class hierarchies makes it more difficult for newcomers
to really understand an interface because things are no longer spelled out in
one place, but now in the Interface and the InterfaceBase class. It's a debatable
question which consideration (readability vs code size reduction) is the more
important one. Any input would be welcome.
In reference to #1775 as a first …

Create a base class for plugins.

---

CMakeLists.txt
doc/CMakeLists.txt

The cmake script has become a bit of a mess. This patch disentangles it in a substantial way, first finding and dealing with external dependencies, then configuring our own targets, then dealing with how external dependencies impact our own targets, and finally documentation. This is going to be difficult to review -- but almost all of it is really just moving things around.
For me, the cmake output now looks like this, less convoluted:
```
-- ====================================================
-- ============ Configuring ASPECT ====================
-- ====================================================
-- Setting up ASPECT for DebugRelease mode.
-- 
-- ===== Configuring external libraries ===============
-- Found deal.II version 9.6.0-pre at …
```

Disentangle CMakeLists.txt.

---

include/aspect/simulator_signals.h
source/postprocess/visualization.cc
tests/pre_data_out_build_patches.cc
tests/pre_data_out_build_patches.prm
tests/pre_data_out_build_patches/screen-output
tests/pre_data_out_build_patches/statistics

Add a signal that can modify data_out during the creation of visualization output. It can be used to for example select only part of the domain to be outputted.

Add a signal before building patches for visualization output

---

source/particle/property/crystal_preferred_orientation.cc

The previous code gradients[d] works because the indices of velocity or velocity gradient in the vector gradient are at 1 to dim th locations and so doing a for loop from 1 to dim will get the correct results. However, if in the future, someone changed the orders of "struct ComponentIndices" in aspect/include/aspect/introspection.h, then it will be a hidden bug that could be hard to debug.
* [x ] I have read the guidelines in our [CONTRIBUTING.md](../blob/main/CONTRIBUTING.md) document.
* [x ] I have followed the [instructions for indenting my …

update the indexing of vector gradients following the idea of defensive programming (compiled)

---

include/aspect/boundary_traction/interface.h

Remove a member variable that is not used.

---

CMakeLists.txt

More moving around stuff in CMakeLists.txt.

---

contrib/world_builder/source/world_builder/features/continental_plate_models/temperature/linear.cc
contrib/world_builder/source/world_builder/features/mantle_layer_models/temperature/linear.cc
contrib/world_builder/source/world_builder/features/oceanic_plate_models/temperature/linear.cc

This is backporting a fix made in the GWB to prevent a crash when min and max are the same in the linear temperature model. See https://github.com/GeodynamicWorldBuilder/WorldBuilder/pull/704 for more info.
@cedrict

Backport GWB crash fix if min and max are the same.

---

contrib/world_builder/include/doctest/doctest.h

resolves issue https://github.com/GeodynamicWorldBuilder/WorldBuilder/issues/731 in ASPECT. Changing sprintf to snprintf. This was resovled in https://github.com/GeodynamicWorldBuilder/WorldBuilder/pull/704 in the world builder.

Backport world builder sprintf to snprintf

---

cookbooks/tomography_based_plate_motions/plugins/CMakeLists.txt

We missed one file and it produces a warning.

fix a CMake minimum version bump

---

Jenkinsfile

- report why CI failed (copied from OSX)
- if not "ready to test" report pending not failure (no red X)
- abort older builds when starting up (copied from OSX)
- formatting
Not sure if we should wait until the hack is over, to make sure we don't break things.

Jenkins improvements

---

CMakeLists.txt

At the top of CMakeLists.txt, we already disallow in-source builds. We need not care about them further down in the file.

Remove code that supports in-source builds.

---

source/simulator/solver.cc

This fixes #5431. I think it's reasonable to say that "post-solve" is after we've correctly set all solution variables.

Move a signal to after we're actually done solving things.

---

include/aspect/initial_composition/interface.h
include/aspect/initial_temperature/interface.h
include/aspect/particle/property/interface.h
include/aspect/particle/world.h
source/initial_composition/interface.cc
source/initial_temperature/interface.cc
source/particle/property/interface.cc
source/particle/world.cc
source/simulator/core.cc

This is a follow up to #5800. In that PR all plugins inherited the canonical `update` functions from the base class to be called at the beginning of each timestep. However, not all plugin systems actually called this function at the beginning of each timestep. This PR makes sure the function is actually called for all plugin systems (I went through the systems and made sure all call the `update` function).

Call all plugin update functions

---

include/aspect/particle/interpolator/interface.h
source/particle/interpolator/bilinear_least_squares.cc
source/particle/interpolator/cell_average.cc
source/particle/interpolator/harmonic_average.cc
source/particle/interpolator/interface.cc
source/particle/interpolator/nearest_neighbor.cc
source/particle/interpolator/quadratic_least_squares.cc

It used to be possible to call the particle interpolators without knowing which cell the interpolated positions were in (e.g. when creating new particles in random locations without checking the cell first). This led to all particle interpolators having backup code in case the cell is not known. By now however, all calls to particle interpolators provide an actual cell, so it is not necessary to carry this (slow) backup code around.
Also remove a deprecated interface function that was deprecated 6 years ago.

Remove unnecessary check in particle interpolator. Remove deprecated function.

---

Jenkinsfile
contrib/ci/Dockerfile
contrib/ci/build.sh

instead of building an (empty) image based on the image geodynamics/aspect-tester:focal-dealii-9.5-v3
we use it directly.

jenkins: use prebuilt tester image

---

.clang-tidy

- use multiline formatting
- remove some checks we don't want: enum-size, avoid-endl
FYI @gassmoeller

update clang-tidy rules

---

source/material_model/grain_size.cc
tests/grain_size_friction_heating.prm

During the hackathon, we discussed that it might be more accurate to keep the stress constant in the substeps we do for grain size evolution, rather than keeping the strain rate constant. I still think this is true, but only if the grain size reduction small. For large grain size reduction, keeping the stress constant can lead to a runaway effect: We have a large stress, this reduces the grain size by a lot and leads to a lower viscosity. Usually, a lower viscosity would also mean a lower stress, but keeping the stress constant overestimates the grain size reduction. This effect is especially bad at boundaries where we prescribe the velocity (in other words, the strain rate). 
I tested this both with the grain_size_strain test and with an application model similar to the grain)size_ridge …

Add documentation on grain size model

---

.github/workflows/build_dealii_master_clang.yml
contrib/docker/tester-clang/Dockerfile
contrib/docker/tester-clang/build.sh
contrib/docker/tester-clang/local.cfg

- add a clang based Docker image to be used for clang compilation and clang-tidy in the future
- add a workflow to build this image
FYI @gassmoeller

add separate nightly deal.II master Docker script with clang

---

contrib/docker/tester/Dockerfile

Since #5854 we no longer build a derived docker image using Jenkins, so these lines are no longer necessary.

Simplify dockerfile

---

include/aspect/particle/property/cpo_bingham_average.h
include/aspect/particle/property/cpo_elastic_tensor.h
include/aspect/particle/property/crystal_preferred_orientation.h
include/aspect/particle/property/elastic_tensor_decomposition.h
include/aspect/particle/property/interface.h
source/particle/property/cpo_bingham_average.cc
source/particle/property/cpo_elastic_tensor.cc
source/particle/property/crystal_preferred_orientation.cc
source/particle/property/elastic_tensor_decomposition.cc
source/particle/property/interface.cc

We had an outdated particle update interface function, which was deprecated 4 years ago. In order to modernize the update interface as a first step I remove this function in this PR. Unfortunately, I didnt notice during review that the CPO particle plugins use this function (I do not know why we got no deprecation warnings?). Therefore I update the use of the update function in the CPO related particle plugins as well.
The header files contain a lot of copy-pasted documentation, let me know if you want me to remove that.

Remove deprecated particle update function

---

cookbooks/inner_core_convection/inner_core_convection.cc
source/heating_model/constant_heating.cc

Found these, because they confuse the update script in #5394.

Escape backslashes in documentation

---

include/aspect/heating_model/interface.h
include/aspect/plugins.h
include/aspect/postprocess/interface.h
source/heating_model/interface.cc
source/postprocess/interface.cc
tests/find_postprocess_fail_1/screen-output

This is a bit like #1807 in that it provides a base class for the various `Manager` classes. This PR also converts two of the manager class to use the common base class. The remaining ones will follow later.
Observations:
* There isn't quite as much commonality, or at least it's not as easy to refactor.
* A nuisance is that the different `Manager` classes use different names for the same functionality. For example, we have `Postprocessor::Manager<dim>::has_matching_postprocessor()` but `HeatingModels::Manager<dim>::has_matching_heating_model()`. Both do the same, but because they have different names I can't abstract them into the base class (though I have abstracted their *functionality* into the base class).

Provide a base class for plugin manager classes.

---

source/simulator/parameters.cc

This PR adds documentation that the full A block is always used if choosing the GMG solver.

Add to full A documentation

---

benchmarks/annulus/transient/run_all_models.sh
benchmarks/rigid_shear/steady-state/run_all_models.sh
benchmarks/rigid_shear/transient/run_all_models.sh
benchmarks/time_dependent_annulus/transient/run_all_models.sh

Follow up to #5394. These benchmarks scripts were not updated, because I didnt see that they used the subsection in the bash script.

Fix particle benchmark scripts

---

include/aspect/introspection.h
include/aspect/parameters.h
source/simulator/assembly.cc
source/simulator/checkpoint_restart.cc
source/simulator/core.cc
source/simulator/helper_functions.cc
source/simulator/introspection.cc
source/simulator/melt.cc
source/simulator/parameters.cc
source/simulator/solver.cc

This changes the type of ``use_discontinuous_composition_discretization`` to a std::vector<bool> and replaces all usages of this variable. No other new/different functionality.
part of #5748

Introspection: store discontinuous per composition

---

source/postprocess/particles.cc

remove useless std::move

---

.github/workflows/clang.yml
contrib/utilities/run_clang_tidy.sh

- add action to compile with Clang and run clang-tidy
- This action takes close to 2hr to complete, so disable for PRs for now

add clang/clang-tidy Github-Actions workflow

---

contrib/utilities/update_scripts/prm_files/reformat.py

This throws off some Python versions (but not others?)

properly escape backslash

---

include/aspect/particle/interpolator/bilinear_least_squares.h
include/aspect/particle/interpolator/quadratic_least_squares.h
source/particle/interpolator/bilinear_least_squares.cc
source/particle/interpolator/cell_average.cc
source/particle/interpolator/harmonic_average.cc
source/particle/interpolator/nearest_neighbor.cc
source/particle/interpolator/quadratic_least_squares.cc

While thinking about #5880 (which is most likely caused by another reason) I noticed that a lot of the particle interpolator plugins include unnecessary header files. Most of these header have been necessary in the past, but were forgotten when the code was deleted or reworked. I also found one function declaration that is no longer implemented or used (it was moved in #5702)

Remove unnecessary includes from particle interpolators

---

contrib/utilities/update_scripts/prm_files/move_particles.py

The current particle update script in #5394 had a bug that caused it to delete the parameters in the global "Particles" subsection if that subsection already existed (it did not exist in any file before #5394). This mostly means you cannot apply this script again to a file that was already updated without deleting parameters. This PR fixes the problem by detecting if the parameters have already been moved and then skipping the operation.

Fix particle update script

---

source/particle/generator/ascii_file.cc
source/particle/generator/interface.cc
source/particle/generator/probability_density_function.cc
source/particle/generator/random_uniform.cc
source/particle/generator/reference_cell.cc
source/particle/generator/uniform_box.cc
source/particle/generator/uniform_radial.cc
source/particle/integrator/interface.cc
source/particle/integrator/rk_2.cc
source/particle/interpolator/bilinear_least_squares.cc
source/particle/interpolator/cell_average.cc
source/particle/interpolator/harmonic_average.cc
source/particle/interpolator/interface.cc
source/particle/interpolator/nearest_neighbor.cc
source/particle/interpolator/quadratic_least_squares.cc
source/particle/property/cpo_bingham_average.cc
source/particle/property/cpo_elastic_tensor.cc
source/particle/property/crystal_preferred_orientation.cc
source/particle/property/function.cc
source/particle/property/interface.cc
source/particle/property/melt_particle.cc
source/particle/world.cc
unit_tests/crystal_preferred_orientation.cc
unit_tests/particles.cc

Related to #5877. A first step for allowing multiple particle fields, by making the particle plugin path relative instead of absolute.

Move particle plugin declarations to relative path instead of absolulte path.

---

doc/sphinx/user/extending/index.md
doc/sphinx/user/install/docker-container/developing-in-container.md
doc/sphinx/user/install/local-installation/using-candi.md
doc/sphinx/user/run-aspect/debug-mode.md

I found a missing `</span>` when reading about plugins - it looks like `ASPECT` is usually in small-caps but `deal.II` is plain text so I also went through and made `deal.II` plain text everywhere else I found it.

Consistently format 'deal.II' in the manual.

---

include/aspect/simulator_access.h
source/material_model/rheology/strain_dependent.cc
source/mesh_refinement/particle_density.cc
source/particle/interpolator/bilinear_least_squares.cc
source/particle/interpolator/quadratic_least_squares.cc
source/postprocess/load_balance_statistics.cc
source/postprocess/particle_count_statistics.cc
source/postprocess/visualization/particle_count.cc
source/simulator/initial_conditions.cc
source/simulator/simulator_access.cc

There are still a lot of places that get the particle world through a convoluted process through the particles postprocessor. This is not longer necessary, as it is owned by Simulator and available through SimulatorAccess. Clean up the code, which also makes includes unnecessary.

Code cleanup

---

include/aspect/particle/generator/interface.h
include/aspect/particle/integrator/interface.h
include/aspect/particle/interface.h
include/aspect/particle/interpolator/interface.h
include/aspect/particle/property/interface.h
source/particle/interface.cc
source/particle/property/interface.cc
source/particle/world.cc

This pull request adds a ParticleInterfaceBase to set the particle world index in the particle plugins as suggested by @gassmoeller. Let me know if this was what you had in mind.
This pull request is parallel to #5920 and should be able to be review and merged independently.

Add ParticleInterfaceBase to set the particle world index for the particle plugins.

---

include/aspect/simulator.h
include/aspect/simulator_access.h
source/material_model/rheology/strain_dependent.cc
source/mesh_refinement/particle_density.cc
source/particle/integrator/rk_2.cc
source/particle/integrator/rk_4.cc
source/particle/interpolator/bilinear_least_squares.cc
source/particle/interpolator/quadratic_least_squares.cc
source/particle/property/cpo_bingham_average.cc
source/particle/property/cpo_elastic_tensor.cc
source/particle/property/elastic_tensor_decomposition.cc
source/postprocess/crystal_preferred_orientation.cc
source/postprocess/load_balance_statistics.cc
source/postprocess/particle_count_statistics.cc
source/postprocess/particles.cc
source/postprocess/visualization/particle_count.cc
source/simulator/core.cc
source/simulator/initial_conditions.cc
source/simulator/simulator_access.cc
source/simulator/solver_schemes.cc
tests/mesh_deformation_particles.cc
tests/particle_handler_copy.cc
tests/particle_property_post_initialize_function.cc

This is a followup pull request to #5918, getting more infrastructure in place. For now there is only one particle world, but is is now stored in a vector. 
For the next step we would need to think of how to make sure all particle plugins know what world they are in, but I think that should go in a followup pull request.

Add further multiple particle world instrastructure.

---

include/aspect/plugins.h
tests/find_boundary_composition_model_fail_1/screen-output
tests/find_mesh_refinement_fail_1/screen-output
tests/find_postprocess_fail_1/screen-output

This is taken from how `MeshRefinement::Manager::update()` does things. I'm just moving that into the new `Plugins::ManagerBase` class.
Part of #1775.

Harden Plugins::ManagerBase::update() against exceptions.

---

source/simulator/solver.cc

clang rightfully complains that we can not delete these objects with a pointer to base otherwise.

make SchurComplementOperator destructor virtual

---

CMakeLists.txt

The COMMENT part of `add_custom_target` is shown as the message by `make`/`ninja` when a target is being built. Apparently, the string to be shown is evaluated at the time when `add_custom_target` is parsed, not when the target is actually built, and as a consequence cmake generator expressions are not evaluated but shown verbatim.
This leads to awkward screen messages in a case I introduced in one of my previous patches. Instead, show a message like this, which while not perfect is better than the awkward `$<...>` text:
```
[1/1] Creating symlink from aspect.exe.debug to './aspect'
```

Avoid generator expression in custom target COMMENT text.

---

include/aspect/particle/interface.h
include/aspect/particle/property/interface.h
source/particle/interface.cc
source/particle/property/interface.cc

We need to create all plugins inside parse_parameters() before we can set their particle world. Also make sure we initialize this value to be invalid so errors will trigger more reliably.
fixes #5947
FYI @MFraters

fix particle world index in properties

---

doc/modules/changes/20240609_gassmoeller
include/aspect/particle/interpolator/distance_weighted_average.h
source/particle/interpolator/distance_weighted_average.cc
tests/particle_interpolator_distance_weighted_average.prm
tests/particle_interpolator_distance_weighted_average/screen-output
tests/particle_interpolator_distance_weighted_average/statistics
tests/particle_interpolator_distance_weighted_average_adaptive.prm
tests/particle_interpolator_distance_weighted_average_adaptive/screen-output
tests/particle_interpolator_distance_weighted_average_adaptive/statistics

This is not ready for review.
@anne-glerum: This PR adds a new particle interpolator that interpolates between particles based on a distance weighted average (similar to what radial basis functions would do). The interpolator in its current form produces worse errors (though the same convergence rate) as the 'cell average' interpolator. However, it should be smoother and less affected by small particle movements across cell boundaries.
This PR is currently in a very rough state, I only open this to remind myself to finish it after the hackathon.

Add distance weighted particle interpolator

---

include/aspect/boundary_composition/interface.h
include/aspect/boundary_temperature/interface.h
include/aspect/heating_model/interface.h
include/aspect/initial_composition/interface.h
include/aspect/initial_temperature/interface.h
include/aspect/particle/property/interface.h
include/aspect/plugins.h
include/aspect/termination_criteria/interface.h
source/boundary_composition/interface.cc
source/boundary_temperature/interface.cc
source/heating_model/interface.cc
source/initial_composition/interface.cc
source/initial_temperature/interface.cc
source/particle/property/interface.cc
source/termination_criteria/interface.cc

In pursuance of #1775.
This is not particularly pretty. Some of the manager classes store a list of names of the plugins that are active in this manager, but some do not. Some used `std::list<std::string>`, some `std::vector<std::string>`. Some had accessor functions that returned a reference to the object (preserving the type :-( ). 
This patch pushes the member variable down into the base class, but not yet the accessor functions. It is another incremental step, with the remaining steps listed in #1775 and left for the coming days or weeks.

Push the variable that stores the active plugin names down to the base class.

---

source/particle/interface.cc

clang complains:
```
/__w/aspect/aspect/source/particle/interface.cc:29:30: error: use of undeclared identifier 'numbers'; did you mean 'Plugins::numbers'? [clang-diagnostic-error]
```
see https://github.com/geodynamics/aspect/actions/runs/9691837223/job/26744048720#step:4:215

add missing include

---

include/aspect/melt.h
source/simulator/melt.cc

Similar to #5247. I saw this during the review of #5902. We currently have no good way to check if a material model fills the `MeltOutputs`, because they are default constructed (different from other AdditionalMaterialOutputs like `ElasticOutputs`). We should initialize them with signaling NaNs like other optional outputs, which then allows us to check after the call to the material model whether they have been properly filled.

Poison the default constructed values of MeltOutputs

---

CMakeLists.txt

There is still a lot to do, but this keeps moving things around in such a way that it creates some kind of logic order.

Sort more parts of CMakeLists.txt into a rational order.

---

include/aspect/plugins.h

I will need these functions in deprecating whatever all of these `Manager` classes have been implementing on their own so far.
This is the next step for #1775.

Provide functions that can access the elements of the lists stored in ManagerBase.

---

.github/workflows/clang.yml
.github/workflows/linux.yml
contrib/docker/docker/Dockerfile
contrib/docker/docker_tacc/Dockerfile
contrib/docker/tester-clang/Dockerfile
contrib/docker/tester/Dockerfile

It turns out github actions upgraded the resources for the default runners to 4 cpus and 16 GB RAM (https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories). We should make use of this for compiling aspect and for building docker images (precomputing the test results likely already did this, because it doesnt limit the processes ninja uses).

Use 4 processes for github actions

---

.github/workflows/clang.yml

- remove matrix build because it is a single build (this is annoying to look at the logs)
- set the correct concurrency group, so the wrong jobs are no longer cancelled (I think this should work)

clang CI fixes

---

source/initial_composition/interface.cc
source/mesh_refinement/interface.cc
source/termination_criteria/interface.cc
source/time_stepping/interface.cc

The `ManagerBase` class has a `plugin_names` member variable that we should fill (see the bullet point in #1775 for this). Not all current manager classes do that -- some just use a local variable and leave `plugin_names` untouched. This patch makes them use `this->plugin_names` instead.

Use a variable in the base class instead of local ones.

---

include/aspect/plugins.h
source/adiabatic_conditions/interface.cc
source/boundary_composition/interface.cc
source/boundary_fluid_pressure/interface.cc
source/boundary_heat_flux/interface.cc
source/boundary_temperature/interface.cc
source/boundary_traction/interface.cc
source/boundary_velocity/interface.cc
source/geometry_model/initial_topography_model/interface.cc
source/geometry_model/interface.cc
source/gravity_model/interface.cc
source/heating_model/interface.cc
source/initial_composition/interface.cc
source/initial_temperature/interface.cc
source/material_model/interface.cc
source/mesh_deformation/interface.cc
source/mesh_refinement/interface.cc
source/particle/generator/interface.cc
source/particle/integrator/interface.cc
source/particle/interpolator/interface.cc
source/particle/property/interface.cc
source/postprocess/interface.cc
source/postprocess/visualization.cc
source/prescribed_stokes_solution/interface.cc
source/termination_criteria/interface.cc
source/time_stepping/interface.cc

We create these objects 
```
std::tuple
<void *,
void *,
aspect::internal::Plugins::PluginList<Interface<2>>,
aspect::internal::Plugins::PluginList<Interface<3>>> registered_plugins;
```
into which we put stuff that we need to create plugins based on what people put into their `.prm` files. These objects all have 4 entries so that we can index into them with the dimension (dim==0,1,2,3), but of course we do not use the first two entries at all -- the type `void *` is simply a placeholder meant to indicate that nothing in there matters. I think it would be nicer to actually represent that by an empty and otherwise unusable object -- `void*` is understandable to die-hard 1970s C programmers, but perhaps not to our typical user base.
This patch proposes to create an empty class we can use as …

Create a dedicated type to denote something invalid.

---

doc/modules/changes/20240704_myhill
include/aspect/material_model/rheology/diffusion_creep.h
source/material_model/rheology/diffusion_creep.cc

This PR adds grain size as a variable argument to the functions in DiffusionCreep. Each function is overloaded so that old functionality is preserved. 
The old functions call the new functions, using the fixed grain size as input.
The changes in this PR will be useful for composite rheologies and material models where grain size is a variable.

allow variable grain size in diffusion creep

---

source/material_model/rheology/visco_plastic.cc

#4247 introduced the option to use adiabatic pressure instead of full pressure to compute viscous creep viscosities in the visco_plastic rheology. However, this was not carried over to the Frank-Kamanetskii option introduced in #5655. This PR makes it consistent, i.e. the same pressure (either adiabatic or full) is used no matter if diffusion / dislocation / Peierls / Frank-Kamanetskii viscosity is computed.
I also removed the list of creep laws from the parameter description to avoid having to update the list whenever we introduce a new creep law.

Use pressure consistently for viscous creep in visco-plastic

---

source/simulator/checkpoint_restart.cc

Seen while writing deal.II's step-83.

Use std::system instead of ::system.

---

doc/modules/changes/20240717_myhill
include/aspect/material_model/rheology/composite_visco_plastic.h
source/material_model/rheology/composite_visco_plastic.cc
tests/composite_viscous_outputs.cc

This PR adds grain size as an argument to the functions in CompositeViscoplastic. This will facilitate incorporation into material models with grain size evolution.

add grain size to composite viscoplastic

---

include/aspect/material_model/rheology/drucker_prager.h
source/material_model/rheology/drucker_prager.cc

This PR improves the documentation for the Drucker Prager rheology and passes the input parameters by reference. This PR partially addresses comments raised in #5946.

improve docs for drucker prager

---

include/aspect/plugins.h
source/postprocess/interface.cc

Let's see how many places I missed in my previous patches.
Related to #1775.

Test that manager classes fill both base class member variables consistently.

---

source/material_model/rheology/visco_plastic.cc

In the viscoplastic material model, the strain rate can adapted for elastic stresses and is then called `effective_edot_ii` instead of `edot_ii`. `effective_edot_ii` is then used to compute the current cohesion and friction angle and the resulting yield stress. This yield stress is used in the stress limiter case, which however uses `edot_ii` in further calculations. This PR changes `edot_ii` to `effective_edot_ii` in the stress limiter case to be consistent.

Use effective strain rate in viscoplastic stress limiter case as well

---

include/aspect/global.h
source/compat.cc
source/material_model/rheology/strain_dependent.cc
source/particle/world.cc

We are using `boost::container::small_vector` in a small number of places where we know the code path is used a lot  and might impact performance. However, it is a bit clunky to use (long name with namespaces, additional template parameter for the size on the stack), so whenever I review a PR with a `std::vector` in a code path that may or may not be important for performance I have to weigh the time to write the comment and explain how to use `small_vector` against the likelihood it actually affects performance. I suggest to create our own type alias `small_vector` to shorten the name and give it a default size. This way any `std::vector<T>` could theoretically be replaced with `small_vector<T>`, which makes it easier to use myself and to explain in PR reviews. For now I only replaced …

Introduce small vector type alias

---

source/material_model/rheology/composite_visco_plastic.cc

I think this way the initialization is easier to understand (first resize, then initialize all values), the effect is the same.
Embarrassingly for the past two days I was hunting for a bug here that was already fixed in #5990 (my branch wasnt updated). The partial strain rates used to be not initialized and existing values would be included in the strain rates. After finding the bug I rebased and saw it was fixed already (in a PR I reviewed :man_facepalming:). Anyway, both the code before and after this PR is correct (before #5990 it was potentially broken depending on the prior values in `partial_strain_rates`).

Reorder initialization of partial strain rates in composite visco plastic

---

cookbooks/continental_extension/continental_extension.prm
tests/continental_extension/screen-output

Implementation of a simple solution #6002. Although the best fix would be to find the issue why the gmg solver fails, setting it to the amg solver will at least fix the cookbook in the main branch for now.

Switch continental extension to AMG solver.

---

include/aspect/material_model/interface.h
source/material_model/interface.cc
source/material_model/rheology/elasticity.cc

This PR moves the `get_averaging_operation_for_viscosity()` function from `material_model/rheology/elasticity.cc` into `material_model/interface.cc`.
This is a more logical place for the function, and makes it more easily accessible by rheology and material_model modules.
Addresses a single comment here: https://github.com/geodynamics/aspect/pull/5984#discussion_r1713714756

move viscosity averaging function

---

include/aspect/material_model/utilities.h
source/material_model/utilities.cc
source/material_model/visco_plastic.cc

Material models often only want to handle the compositions that correspond to chemical fields (e.g. for computing volume fractions). However, the phase function object was designed to be working with all compositional fields and so material models like visco plastic had to manually convert between all phase transitions and only the ones affecting chemical compositions. This PR moves the relevant functionality into the phase function object, so that in the future other material models can perform the same operations without copying the calculation.
I know this looks like I replaced 15 lines with 87 lines, but I think this will be helpful when using phase functions more widely (I am currently looking at using it for the grain size material model).

Simplify use of phase function for computing volume fractions

---

include/aspect/plugins.h

I made a poster for a conference and noticed that the current color of the interface classes in the plugin graph are hard to read. In dark light the text is barely readable. I suggest to change the color from green to light green (images below). No need to rebuild the graph right away, we can do that when we next update the parameters file.
Old:
New:

Use lighter green color in plugin graph

---

cookbooks/continental_extension/continental_extension.prm

I fixed the units described for a parameter in the continental extension cookbook.

Fix a unit typo in continental_extension_cookbook

---

AUTHORS.md
doc/sphinx/user/authors.md

We had two separate author lists for source code and manual, which is a problem, because I kept forgetting we need to keep the manual authors up to date as well (and they are probably way outdated already). It also lead to us forgetting to mention @cedrict as principal developer in the manual (sorry! you were mentiond in the main AUTHORS.md). To avoid this it would be easier to unify the files and make sure we only have one authors file to keep up to date. I deleted the one in the manual, and replaced it with a symbolic link to the file in the main directory. Let's see if readthedocs picks this up correctly, if not I can keep a separate file in the sphinx directory that just contains an `include` directive.

Unify AUTHORS.md text

---

source/initial_temperature/S40RTS_perturbation.cc
source/initial_temperature/SAVANI_perturbation.cc
source/initial_temperature/patch_on_S40RTS.cc

This PR adds a space between the numeric value and units (km) in the documentation or comments for multiple initial temperature plugins.
* [ X] I have read the guidelines in our [CONTRIBUTING.md](../blob/main/CONTRIBUTING.md) document.

fix units spacing in initial temperature plugins

---

include/aspect/particle/world.h
include/aspect/solution_evaluator.h
source/particle/world.cc
source/solution_evaluator.cc

In order to further reduce the overhead in the particle code I would like to hand over the `SolutionEvaluator` class objects directly to plugins. This is useful, because `SolutionEvaluator` stores the necessary data (solution and/or gradients) internally anyway so handing over a reference to the evaluator reduces the need to copy data around. In addition I can see the class being useful in other contexts as well, it essentially allows to evaluate all solution components in arbitrary positions of a cell in a faster way than `FEValues`. For that it would be useful to not have the class hidden in a namespace `Particle::internal::...`. This PR suggests to move the class into the global `aspect` namespace, but we could also move it into `Utilities` instead. I only moved code around, the only …

Separate solution evaluator from particle code

---

contrib/utilities/jsontomarkdown.py

I am getting a SyntaxWarning about an invalid escape sequence.

jsontomarkdown.py: fix warning

---

include/aspect/introspection.h

C-Arrays can be replaced by `std::array` in most cases, which should also give the benefit of array-bounds checking in debug mode (#6007). Use cases should not be affected as far as I can see.

Avoid a C-style array

---

include/aspect/geometry_model/chunk.h
include/aspect/geometry_model/spherical_shell.h
include/aspect/geometry_model/two_merged_chunks.h
include/aspect/particle/integrator/euler.h
include/aspect/particle/integrator/rk_2.h
include/aspect/particle/integrator/rk_4.h

`static const` members that have the same value independent of run-time parameters may just as well be `constexpr`. In fact the current implementation may be wrong if these header files are included in multiple places (at least @mfraters got a linker error when including the rk_2 header in a user plugin, which was fixed by the change in this PR). As far as I understand without `constexpr` we would actually have to put the definition of the static const members into the source file, or use a `inline static const ...` which is only supported since c++17.

Use constexpr where possible

---

include/aspect/particle/world.h
include/aspect/simulator.h
source/particle/world.cc
source/simulator/core.cc
source/simulator/initial_conditions.cc
source/simulator/simulator_access.cc
source/simulator/solver_schemes.cc

We should be able to store Particle Worlds directly and not inside unique_ptr.

store particle worlds directly

---

source/particle/world.cc
source/simulator/checkpoint_restart.cc
source/simulator/initial_conditions.cc

@mfraters, @tjhei this should check most remaining items off the list of #5877, in particular the interpolation and the load balancing. I think we are now at a stage where we need to add a lot of tests to this PR.
We should also think about a cookbook that illustrates how to use the multiple particle worlds.

Support multiple particle sets

---

doc/sphinx/user/extending/idea-of-plugins.md

Revise the discussion about how plugins work in the documentation.

---

doc/modules/changes/20241009_guo
doc/sphinx/user/run-aspect/parameters-overview/index.md

We should advertise the VS code extension now that the old GUI is retired in #5735.
@zguoch are you ok with us crediting you in the changelog entry?

Mention VS code extension for input file editing

---

doc/sphinx/conf.py
doc/sphinx/index.md
doc/sphinx/user/answers.md
doc/sphinx/user/developer_documentation.md
doc/sphinx/user/extending/future-plans.md
doc/sphinx/user/extending/index.md
doc/sphinx/user/index.md
doc/sphinx/user/methods/index.md

This PR contains small modifications to the structure of the online documentation to make it easier to use, and improve its design a bit. I reduced the visual clutter on the start page and shortened some headings, so that they do not break over two lines in the table of contents. Opinions welcome.
To illustrate the old documentation start page:
And the new start page:

Update table of content of documentation

---

cmake/AspectConfig.cmake.in

This PR is a fix for #6017. The problem was that if we build ASPECT in release only mode and then set up an external library, the user already sets up a target with the original library name (`${_target}`) in the CMakeLists.txt of the plugin. Then the macro in `AspectConfig.cmake.in` would set up another target with name `${_target}.release`, and only for this additional target would it configure the correct include files. But when running `make` the makefile would then try to compile both targets (with the same sources, but only one of them had correctly configured header files).
I changed the macro to now reuse the target name from the user CMakeLists for the release library. If no debug library is compiled, no new target name is necessary (this means the release target has a different …

Fix plugin cmake for release only

---

contrib/utilities/update_all_files.sh
contrib/utilities/update_prm_files.sh
contrib/utilities/update_source_files.sh
source/postprocess/particles.cc
tests/darcy_convection_step.prm
tests/nonlinear_failure_strategy_abort.prm
tests/nonlinear_failure_strategy_cut.prm
tests/original_prm/original.prm
tests/particle_interpolator_distance_weighted_average_adaptive.prm
tests/particle_multiple_worlds_interpolation_fail_1.prm
tests/particle_multiple_worlds_interpolation_fail_2.prm
tests/update_script/screen-output
tests/update_script_2/screen-output
tests/visco_plastic_adiabatic_pressure_in_plasticity.prm

This PR applies the update script and also make the scripts a bit  safer against accidental shell expansion. Together with #5941 this should also close #6006. If I apply the current update script against ASPECT main, no changes exept for the ones in this PR are made.

Apply update script to header, source and prm files.

---

tests/nsinker_bfbt.prm
tests/nsinker_bfbt/screen-output
tests/nsinker_bfbt/statistics

This pull request will add tests for the weighted BFBT preconditioner.
Regarding the existing nsinker_bfbt test, a flag is added to make it use the weighted BFBT preconditioner.

fix test for weighted  BFBT preconditioner

---

source/postprocess/load_balance_statistics.cc
source/postprocess/particles.cc

We are unlikely to have more than 4B particles per cell, but I don't think it makes sense to use the wrong data type here.

use correct type for particle counts

---

source/simulator/assemblers/stokes.cc

The Schur complement is S=BA^{-1}B^T, so if we are trying to approximate S^{-1} the pressure scaling factor should be 1/(pressure_scaling^2). The current implementation in Aspect has a factor of 1/(pressure_scaling^4). This pull request changes it to 1/(pressure_scaling^2).

Change Weighted BFBT preconditioner pressure scaling factor

---

include/aspect/material_model/reactive_fluid_transport.h

Part 3 of #6082. Contains a fix to the doxygen documentation (missing closing group `* @}`), and a number of smaller fixes in the same header file.

Fix doxygen documentation

---

include/aspect/boundary_velocity/ascii_data.h
include/aspect/boundary_velocity/function.h
include/aspect/boundary_velocity/gplates.h
include/aspect/boundary_velocity/zero_velocity.h
include/aspect/lateral_averaging.h
include/aspect/material_model/utilities.h
include/aspect/material_model/visco_plastic.h
include/aspect/particle/generator/ascii_file.h
include/aspect/particle/generator/interface.h
include/aspect/particle/generator/probability_density_function.h
include/aspect/particle/generator/quadrature_points.h
include/aspect/particle/generator/random_uniform.h
include/aspect/particle/generator/reference_cell.h
include/aspect/particle/generator/uniform_box.h
include/aspect/particle/generator/uniform_radial.h
include/aspect/particle/property/interface.h
include/aspect/simulator.h
include/aspect/structured_data.h
include/aspect/utilities.h
source/material_model/utilities.cc
source/material_model/visco_plastic.cc
source/particle/generator/interface.cc
source/particle/property/interface.cc
source/simulator/initial_conditions.cc
source/simulator/lateral_averaging.cc
source/simulator/parameters.cc

Not quite finished, do not review yet, but I need to stop for today and want to see the test results.
I thought 3.0 is a good opportunity to remove deprecated functions and parameters. I made sure to only remove items that were deprecated at least 2 releases (2-3 years) ago or before. There are still some items I cannot remove yet, because we didnt finish the deprecation properly (e.g. forgot to mark the function as deprecated, or left a lot of input files that still use the deprecated options).

Remove deprecated functions

---

index.html

This link seems to be broken, but maybe we dont need it anymore anyway since the pdf manual is out of date by now.

Remove old and broken link on website

---

doc/doxygen-awesome.css
doc/modules/groups.h
doc/options.dox
include/aspect/mesh_deformation/ascii_data.h
include/aspect/mesh_deformation/diffusion.h
include/aspect/mesh_deformation/fastscape.h
include/aspect/mesh_deformation/free_surface.h
include/aspect/mesh_deformation/function.h
include/aspect/mesh_deformation/interface.h

This PR updates the doxygen theme in the same way the deal.II theme was updated in dealii/dealii#17557 to be more mobile friendly and more modern design (also more adaptible to different screen resolutions and more similar to our manual design).
It also fixes a number of doxygen mistakes in the group assignments and group names (https://aspect.geodynamics.org/doc/doxygen/modules.html)
Current site:
New design:

Update doxygen theme

---

doc/modules/changes/20241021_ranpengli
source/adiabatic_conditions/compute_profile.cc
tests/update_script.prm
tests/update_script_2.prm
tests/update_script_2/updated2.prm

Convert year to second in the adiabatic profile function when 'Use years in output instead of seconds = true'

Convert year to second in the adiabatic profile function

---

doc/modules/changes/20241021_gassmoeller
source/particle/generator/probability_density_function.cc
source/particle/generator/random_uniform.cc
tests/particle_generator_probability_default_value.prm
tests/particle_generator_probability_default_value/screen-output
tests/particle_generator_probability_default_value/statistics

Follow-up to #6092 including a changelog entry and one more fix: Previously the default value for the 'probability density function' function expression was 0. This is not a good default, because if the integral of the pdf over the domain is 0 the generator cannot generate particles (and it checks for that and crashes at the moment, thus requiring the user to set a value). This PR changes the default value to 1.0. The nice side effect is that now for all default parameters the 'random uniform' and 'probability density function' generators behave identical. This is expected, because random uniform is just the special case of pdf for a pdf that is constant across the domain.

Fix default value of probability density function particle generator

---

CMakeLists.txt

As part of the testing in #8366 I noticed that I cannot set more than one flag in `ASPECT_ADDITIONAL_CXX_FLAGS`, because of how we incorporate them into the compile flags for world builder. The call to `target_compile_options` expects a cmake list (a semicolon separated string), while the input string from cmake is a space separated string (as one would expect for command line arguments). It looks like the best way to convert this string into a list seems to be the `separate_arguments` command (https://stackoverflow.com/a/22148384).
This is only a problem for the world builder, because for ASPECT itself we append the the additional flags to the `DEAL_II_CXX_FLAGS_DEBUG` and `_RELEASE` strings which will be dealt with by deal.II macros.

Separate additional CXX arguments

---

.github/workflows/linux.yml
CMakeLists.txt
source/material_model/diffusion_dislocation.cc
source/material_model/equation_of_state/multicomponent_compressible.cc
source/material_model/melt_boukare.cc
source/material_model/multicomponent_compressible.cc
source/material_model/utilities.cc
source/mesh_deformation/diffusion.cc
source/mesh_deformation/free_surface.cc
source/mesh_deformation/interface.cc
source/simulator/core.cc
source/simulator/helper_functions.cc
source/simulator/stokes_matrix_free.cc
unit_tests/parse_map_to_double_array.cc

Related to #6106. This PR enables deprecation warnings in the no unity build tester.

Enable deprecation warnings in tester

---

source/simulator/parameters.cc

The current version produces warnings of the kind
```
/ssd/aspect-git2/source/simulator/parameters.cc:1629:53: warning:
‘error_code’ may be used uninitialized [-Wmaybe-uninitialized]
```
on my machine. There is no reason to use the broadcast() function from deal.II that is made for sending complicated objects that need to be packed if we just want to transfer an int. We could use MPI_Bcast() but I don't like manual error checking, which this new overload does (otherwise it is identical to MPI_Bcast here).

change usage of MPI::broadcast

---

CMakeLists.txt
benchmarks/annulus/plugin/annulus.cc
benchmarks/hollow_sphere/hollow_sphere.cc
benchmarks/shear_bands/shear_bands.cc
benchmarks/solitary_wave/solitary_wave.cc
benchmarks/tangurnis/code/tangurnis.cc
cmake/AspectConfig.cmake.in
cookbooks/tomography_based_plate_motions/plugins/tomography_based_plate_motions.cc

This PR fixes #6106. Independent of whether we decide to enable these warnings in deal.II again, I think it would be a good idea to have them enabled for ASPECT. Otherwise our users do not notice if their plugins use deprecated features (this will likely already cause confusion because some of the deprecated features I removed in #6083 and #6084 may not have emitted any warnings with deal.II 9.5 or 9.6).

Enable deprecation warnings when building and in user plugins

---

doc/sphinx/user/extending/plugin-types/temp-bc.md

It used to be the case that we decided which boundaries correspond to which boundary conditions in the geometry model. But that is no longer so -- we do that in the input file. Fix a long-wrong comment in the manual about this.

Remove a comment that's no longer correct.

---

cookbooks/convection-box/tutorial-onset-of-convection/notebooks/tutorial_running.ipynb

This PR fixes the filename in the tutorial notebook for convection box using the updated output files by the `heat_flux` postprocessor, i.e., `heat_flux_bottom.*` and `heat_flx_top.*` instead of `heat_flux.*` as done previously.

Fix the heat flux file name based on udated heat flux postprocessor.

---

benchmarks/solitary_wave/doc/solitary_wave.md
cookbooks/burnman/doc/burnman.md

found while trying to compile a pdf version of the documentation. While the &#x2006; character works as a space in html, it does not in later.

doc: fix a few problems

---

doc/sphinx/user/extending/plugin-types/temp-bc.md

As part of the open point of #1775, I'm going through the documentation files for plugin systems. There is a number that are not documented at the moment, and I'll get there eventually. One of those is boundary conditions for compositional fields. In one of the other files, we are discussing temperature and compositional fields at the same time, so we might as well do the same for compositional fields. This patch does that.

Also document boundary composition plugins.

---

include/aspect/simulator.h
source/simulator/helper_functions.cc
source/simulator/solver.cc
source/simulator/solver_schemes.cc
source/simulator/stokes_matrix_free.cc

Still looking into the reason why #6116 changes test results I noticed a number of things that could be simplified around the newton solver. This PR does:
1. Update documentation that is out of date
2. Simplifies function arguments, in particular I do no longer assume the calling function already happens to have a copy of a vector if the called function needs a copy. If we need a backup copy of a vector in a function, the function should create and destroy that copy. This may cost 1-2 additional vector copies per nonlinear iteration, but it makes the code much easier to understand. I also think because of this complexity there is a bug in `compute_initial_newton_residual` that I will address in a follow up.
This PR should not change any test results, it contains only code style …

Simplify Newton solver function arguments

---

source/simulator/solver_schemes.cc

Still related to #6116 this just removes one level of branching to make the code simpler to read. `solve_stokes` is now always inside the try-catch block, but if `use_Newton_failsafe` is false, we just rethrow the exception immediately in the catch block.

Simplify logic in newton solver

---

include/aspect/simulator.h

This function is not implemented, but apparently no compiler complained so far :-)

Remove unimplemented function

---

source/simulator/solver_schemes.cc

A little more cleanup related to #6116. All of these changes are purely cosmetic, simplifying logic and removing some operations that did nothing.

Further newton code cleanup

---

include/aspect/melt.h
include/aspect/simulator.h
source/simulator/helper_functions.cc
source/simulator/melt.cc
source/simulator/nullspace.cc

Seen while working on #6135. We should keep functions `const` if possible.

Make some functions const

---

doc/modules/changes/20241106_danieldouglas92
source/main.cc
tests/original_wb.prm
tests/original_wb/original.wb
tests/original_wb/statistics

I and others who use the Geodynamic World Builder to run all models find that we occasionally modify a worldbuilder file and/or remove a worldbuilder file accidentally. This leaves the user struggling to remember the exact details of the .wb file when trying to recreate it, and to save future headaches for all ASPECT-GWB users I think it would be very helpful to generate a file called original.wb the same way we generate an original.prm file. This PR implements this functionality!
This is likely important for @MFraters to take a look at :)

Create an original.wb when running ASPECT with the World Builder

---

source/postprocess/depth_average.cc

``ofstream`` always sets ``out`` so it doesn't need to be specified.

remove std::ofstream default arg

---

contrib/release/release-tasklist.md

Preliminary release notes for 3.0.0. Do not merge yet! 
I open this now so @geodynamics/aspect-developers can take a look to:
- check if I forgot major changes
- correct mistakes in author attribution or description of features
- typos or rewording suggestions are welcome. 
This is only the list of the most relevant changes that will be included in the announcement emails and forum post, the full list of changes will be available on the website.

Add release notes

---

tests/burstedde_bfbt.cc
tests/burstedde_bfbt.prm
tests/burstedde_bfbt/screen-output

This pull request adds a test using weighted BFBT (with Stokes solver type = block AMG).

Add Burstedde Weighted BFBT test

---

source/particle/property/cpo_bingham_average.cc

When compiling ASPECT I kept getting an error about an unused variable `p`. This PR fixes the compiler error by removing this variable.

Remove unused variable

---

source/postprocess/visualization.cc

I came across a small typo in the documentation (see below), this PR fixes it :) 
main:
this branch:

Fix extra text block colons.

---

contrib/release/release-tasklist.md
include/aspect/particle/manager.h
source/particle/manager.cc
source/simulator/initial_conditions.cc

Our `clang-tidy` workflow is currently producing some warnings (see https://github.com/geodynamics/aspect/actions?query=branch%3Amain). This PR fixes the warnings by declaring a move constructor `noexcept` and by using range-based for loops in a number of places.

Fix clang tidy warnings

---

source/simulator/solver_schemes.cc

With the changes of #6135 these lines should be unnecessary. `solution` will be set to the correct value inside the function `do_one_defect_correction_Stokes_step` and we do not need to worry about its content outside of that function. If this is correct, no tests should change.

Remove unnecessary lines

---

cookbooks/mantle_convection_with_continents_in_annulus/doc/mantle_convection_in_annulus.md

This cookbook currently seems to not produce the result reported in its documentation as reported by @rhino1999. Add a warning to make users aware of this.
Related to https://community.geodynamics.org/t/no-subduction-when-running-mantle-convection-with-continents-in-an-annulus-cookbook/3691/7.
@cedrict are you ok with this change?
This PR needs to go into the release branch as well.

Add warning to cookbook

---

source/mesh_deformation/diffusion.cc
source/mesh_deformation/free_surface.cc
source/mesh_deformation/interface.cc
source/postprocess/dynamic_topography.cc
source/simulator/assemblers/stokes.cc
source/simulator/melt.cc
source/utilities.cc
source/volume_of_fluid/assembler.cc
source/volume_of_fluid/setup_initial_conditions.cc

This PR is mostly improving code quality, although it could also lead to small performance improvements for a few models.
It does the following things:
- consistently name the loop variable over quadrature points `q` like we do almost everywhere
- pre-compute `JxW` outside of assembly loops over degrees of freedom wherever possible. In many places that just assemble a right hand side (single loop over DoF) this likely doesnt make a difference, but a few places assemble matrices where this change might matter. Also I would just like to establish this as a pattern in as many places as possible so that future copy-paste code will copy the correct pattern
- while doing the `JxW` conversion also change a few places that can pre-compute values of shape functions or other expensive items from …

Unify assembly patterns

---

source/simulator/assemblers/newton_stokes.cc
source/simulator/stokes_matrix_free.cc
tests/spiegelman_fail_test/screen-output

This cherry-picks the most relevant commit of #6159 into the release branch. This is not a change compared to ASPECT 2.5 rather it restores the behavior of ASPECT 2.5 by reverting a part of #5580 (as discussed in #6160).

[3.0] Revert one change of PR #5580

---

include/aspect/material_model/reaction_model/grain_size_evolution.h
include/aspect/material_model/reaction_model/katz2003_mantle_melting.h

Seen while looking through #6161: Rename the include guards of the reaction models to align with the folder structure. While a bit longer we do this consistently for all other plugins system, so we should keep it for the reaction model.

Rename reaction model include guards to align with folders

---

doc/modules/changes/20241201_lhy11009
include/aspect/material_model/utilities.h
source/material_model/grain_size.cc
source/material_model/utilities.cc
source/material_model/visco_plastic.cc
tests/composite_viscous_outputs_phases.cc

Renamed the variable phase_index to phase_transition_index across 
affected functions and structures. The new variable name, phase_transition_index, 
provides a more precise and descriptive representation of its role, 
emphasizing its purpose in indexing phase transitions rather than phases.

Rename phase transition index

---

benchmarks/newton_solver_benchmark_set/nonlinear_channel_flow/input_t.prm
benchmarks/newton_solver_benchmark_set/nonlinear_channel_flow/input_t_gmg.prm
benchmarks/newton_solver_benchmark_set/nonlinear_channel_flow/input_v_gmg.prm
doc/modules/changes/20241204_gassmoeller
doc/sphinx/user/run-aspect/parameters-overview/structure.md
source/main.cc
tests/include_prm_file.prm
tests/include_prm_file/original.prm
tests/include_prm_file/screen-output
tests/include_prm_file/statistics
tests/include_prm_file_recursive.prm
tests/include_prm_file_recursive/original.prm
tests/include_prm_file_recursive/screen-output
tests/include_prm_file_recursive/statistics
tests/original_prm.prm
tests/original_prm/original.prm

This PR addresses issue #6165 and allows to recursively include parameter files on several levels of input files. See there for a motivation and application cases that are now possible.
I also simplified one benchmark to show what is now possible with this change.
It is worth noting that this PR changes one existing behavior: Currently `include` statements in input files are not expanded when we copy the input file into the output directory as `original.prm`, while with this PR they will contain the content of the included files. While this is a change, I actually think the new form is better, because it makes the `original.prm` more independent from the included file (so they continue to work exactly as they were when the output was generated, even if the base file changes).
@MFraters I …

Allow recursive includes in parameter files

---

contrib/docker/docker_tacc/Dockerfile

Our docker image for the TACC systems has been broken for a while: https://github.com/geodynamics/aspect/actions/workflows/docker.yml. 
This PR fixes a few issues to fix the workflow:
- update to a newer base image with a supported ubuntu version
- fix an issue with the GPG key of the intel MPI repo
- update deal.II version
- split stages for compiling deal.II and dependencies (mostly for convenience when debugging the build process)
- disable ASPECT examples
I had to disable the ASPECT examples, because I couldnt get them to compile as part of the general build process. They would always try to use the non MPI compiler and fail with:
```
make[1]: *** [CMakeFiles/Makefile2:1949: benchmarks/diffusion_of_hill/CMakeFiles/analytical_topography.dir/all] Error 2
In file included from …
```

Fix tacc docker image workflow

---

doc/sphinx/conf.py
doc/sphinx/environment.yml

sphinx pdf can not handle svg images without converting them first.
part of #6178

sphinx doc: add plugin for svg conversion

---

include/aspect/boundary_temperature/dynamic_core.h
source/boundary_temperature/dynamic_core.cc

While reviewing #6168 I noticed that the dynamic core boundary temperature plugin could urgently use an update to our current coding style. This PR goes through the header and source file of dynamic_core and fixes a first batch of issues:
- Added a lot of `const` qualifiers to variables and functions
- Fixed whitespace between functions and made some formulas more readable
- Improved the doxygen documentation by referencing input parameters
- Fixed some include files (included more specifically the files that are needed instead of simulator.h)
- Made sure declaration, definition and initialization of variables are closer together
- replace `M_PI` with `numbers::PI` in a bunch of places
No functionality was changed and I tried to avoid changes that could introduce subtle bugs.
There is …

Update code style in dynamic core plugin

---

doc/make_cite_html.py
doc/manual/citing_aspect.bib
doc/sphinx/references.bib

@Shangxin-Liu in reference to your comment in #6166 (see my reply there).

Add benchmark paper reference

---

include/aspect/boundary_temperature/dynamic_core.h
source/boundary_temperature/dynamic_core.cc

Follow up to #6177, this PR does the following:
- Address the comments in #6177 (the variable `n` that was a `double` before was meant to be and also treated like an unsigned int, I checked the original reference)
- Reorder functions in our usual structure (constructor -> initialize/update -> everything else -> declare_parameters -> parse_parameters)
- Added lots of spaces around equal signs and some operators to improve readability
I think I will make at least one additional follow-up, but I will separate the PRs, because this PR should be purely code structure changes while the next one may actually affect results

Update code style in dynamic core 2

---

source/material_model/reaction_model/grain_size_evolution.cc

I think these lines are left from an earlier refactoring. I can't remember what they were supposed to do; it looks like they just multiply something by 1. So this was not actually doing anything, and we removed the functionality of what it did in the past (scaling viscosity in the lower mantle) during the last hack anyway.

remove two unnecessary lines

---

doc/sphinx/conf.py

This PR reintroduces the old manual front page into the pdf version of our documentation. The current online version is available here: https://aspect-documentation.readthedocs.io/_/downloads/en/latest/pdf/ and looks like this:
The way it is set up in this PR looks like this (we can change and discuss how to display all authors):

Reintroduce old manual front page for the pdf manual

---

include/aspect/utilities.h

The doxygen documentation of this namespace and options was not working due to typos in the documentation strings. @jdannberg can you take a look?

Fix some documentation entries for parsing maps

---

doc/modules/changes/20250127_gassmoeller
include/aspect/material_model/simpler.h
include/aspect/material_model/thermal_conductivity/constant.h
include/aspect/material_model/thermal_conductivity/interface.h
source/material_model/simpler.cc
source/material_model/thermal_conductivity/constant.cc
tests/simpler_box.prm

Implement thermal conductivity plugins

---

source/material_model/latent_heat.cc
source/material_model/utilities.cc
tests/latent_heat_enthalpy.cc
tests/material_model_dependencies.cc

This is a rebase of #4394. 
Since I was working on fixing this material model anyway, I thought it would be good to figure out what the problem with this PR was. @gassmoeller said some tests were not working, so I for now this is just to see which tests break.

Fix pressure depth derivative in latent heat material model

---

include/aspect/coordinate_systems.h
include/aspect/material_model/utilities.h
include/aspect/particle/property/elastic_tensor_decomposition.h
include/aspect/structured_data.h
include/aspect/utilities.h
include/aspect/volume_of_fluid/utilities.h

This PR fixes an issue that appeared in #6215: Not all of ASPECT's namespaces named `Utilities` contain a directive `using namespace dealii::Utilities`. This can lead to hard to understand error messages like that `Utilities::MPI:...` cannot be found, even if the ASPECT file in question was not changed at all (e.g. because it was grouped into a different unity build file that contained a new `Utilities` namespace). This PR introduces `using namespace dealii::Utilities` into every file that introduces an `Utility` namespace.

Include utilities namespace wherever necessary

---

include/aspect/material_model/entropy_model.h
include/aspect/material_model/steinberger.h
include/aspect/material_model/thermal_conductivity/tosi_stackhouse.h
source/material_model/entropy_model.cc
source/material_model/steinberger.cc
source/material_model/thermal_conductivity/tosi_stackhouse.cc

This PR is an example of what will be possible when #6211 is merged. Currently the material models `Steinberger` and `Entropy` use the same thermal conductivity model, either constant or a temperature-pressure dependent approximation. In order to do that they duplicate the code incl. declaration and parsing of parameters. In this PR I outsourced all of that to the new thermal conductivity plugins and either use the plugin `Constant` or `TosiStackhouse` depending on user input. Ultimately I want to get to the state where the thermal conductivity plugins form their own plugin system, where the user can select from the input file which plugin to use (ideally for most or all material models).

Use conductivity interface to remove code duplication

---

doc/modules/changes/20250202_gassmoeller
include/aspect/boundary_traction/interface.h
include/aspect/boundary_velocity/interface.h
include/aspect/parameters.h
include/aspect/plugins.h
source/boundary_traction/ascii_data.cc
source/boundary_traction/initial_lithostatic_pressure.cc
source/boundary_traction/interface.cc
source/boundary_velocity/ascii_data.cc
source/boundary_velocity/interface.cc
source/mesh_deformation/free_surface.cc
source/simulator/assemblers/stokes.cc
source/simulator/assembly.cc
source/simulator/core.cc
source/simulator/helper_functions.cc
source/simulator/melt.cc
source/simulator/newton.cc
source/simulator/solver_schemes.cc
source/simulator/stokes_matrix_free.cc
tests/ascii_boundary_member.cc
tests/ascii_boundary_member/screen-output
tests/ascii_data_boundary_velocity_2d_box/screen-output
tests/ascii_data_boundary_velocity_2d_box_time/screen-output
tests/ascii_data_boundary_velocity_2d_chunk/screen-output
tests/ascii_data_boundary_velocity_2d_shell/screen-output
tests/ascii_data_boundary_velocity_2d_shell_spherical/screen-output
tests/ascii_data_boundary_velocity_3d_box/screen-output
tests/ascii_data_boundary_velocity_3d_shell/screen-output
tests/ascii_data_boundary_velocity_3d_shell_spherical/screen-output
tests/ascii_data_boundary_velocity_residual_shell/screen-output

A suggestion for how to finish #1775. This is still work in progress and unfortunately not completely backwards compatible, but at least the incompatibility is only limited to two rarely used functions in the code, not the input file. The traction manager (and the velocity manager once I get to it) need additional information compared to `ManagerBase`, namely which boundary each plugin is responsible for, and which components (of the tensor components xyz). The main change is the type of internal storage container, and the access functions `get_active_boundary_traction_conditions` and `get_active_boundary_traction_names`. Opinions? If we we agree this is a good idea I can continue with the velocity manager.

Derive remaining managers from ManagerBase

---

doc/modules/changes/20250206_francyrad
source/boundary_temperature/dynamic_core.cc
tests/dynamic_core_fully_molten.prm
tests/dynamic_core_fully_molten/screen-output
tests/dynamic_core_fully_molten/statistics
tests/dynamic_core_fully_solid.prm
tests/dynamic_core_fully_solid/screen-output
tests/dynamic_core_fully_solid/statistics

This takes over the fix from #6168 and adds two more fixes for the case of fully molten and fully frozen planetary cores to the dynamic_core boundary temperature plugin.
The fixes are:
- no longer throw an assert in `solve_time_step` if core is fully molten or fully solid
- avoid divide-by-zero in `get_gravity_heating` by moving computation into a region that is only executed if the core is not fully solid
- avoid divide-by-zero in `get_heat_solution` by introducing the same safeguard that already existed in `get_gravity_heating`
It also adds two test cases for a fully molten and fully frozen core. Note that these solution cases are not benchmarked! I.e. this works, but whether it is correct is currently unknown.

Fix dynamic core boundary temperature plugin

---

contrib/utilities/update_scripts/prm_files/move_tian_reaction_model.py
cookbooks/tian_parameterization_kinematic_slab/coupled-two-phase-tian-parameterization-kinematic-slab.prm
doc/modules/changes/20250206_danieldouglas92
include/aspect/material_model/reaction_model/tian2019_solubility.h
include/aspect/material_model/reactive_fluid_transport.h
source/material_model/reaction_model/tian2019_solubility.cc
source/material_model/reactive_fluid_transport.cc
tests/tian_MORB.prm
tests/tian_gabbro.prm
tests/tian_peridotite.prm
tests/tian_sediment.prm

I was looking through the Reactive fluid transport model code and saw how the katz 2003 model is in it's own reaction model. I think I recall at the hackathon that the ultimate goal for this material model was to expand it by creating new reaction models, so I went and refactored the tian approximation into it's own reaction.

Refactor the Tian Approximation in the Reactive Fluid Transport Model

---

doc/sphinx/user/extending/compatibility.md
doc/sphinx/user/run-aspect/parameters-overview/compatibility.md

Just two file paths that are outdated (they are already correct in another place of those two files).

Fix file paths in documentation

---

.github/workflows/linux.yml

github actions: do not use 20.04

---

benchmarks/advection/README.md
benchmarks/advection/doc/advection.md
benchmarks/rayleigh_taylor_instability/README.md
benchmarks/rayleigh_taylor_instability/doc/rayleigh_taylor_instability.md
benchmarks/sinking_block/README.md
benchmarks/sinking_block/doc/sinking_block.md

It looks like readthedocs has upgraded its Sphinx version, which now produces new warnings in our documentation (e.g. in #6235 [here](https://readthedocs.org/projects/aspect-documentation/builds/27241799/)). As far as I can tell this is caused by internal links that specify markdown files with their file ending. The links work with or without file ending, but with the ending there is a warning in the build process (which is interpreted as an error by our CI because of our configuration). Removing the file ending removes the warning and the links still work (checked in both html and pdf).

Fix Sphinx warnings

---

include/aspect/simulator/solver/interface.h
include/aspect/stokes_matrix_free.h
source/simulator/solver.cc
source/simulator/stokes_matrix_free.cc

A follow-up to #6247 that could be used as a basis to also move the direct solver and the AMG solver into their own classes and reduce the bloat of the simulator class a bit.
The final design of the interface class is up for modification and discussion, since none of this is really exposed to the user we should be able to modify the interface class for a while without issues.

Introduce solver interface class

---

source/simulator/stokes_matrix_free.cc

This PR corrects a mistake I made: in function `MatrixFreeStokesOperators::StokesOperator::local_apply()`, the loop for averaging the Newton derivatives were nested in the loop over quadrature points, which is unnecessary. The two loops are separated now.
By the way, I have a question about the Newton method with GMG solver. In the present implementation, the top-left block used in the outer loop of the linear solver is the Jacobian matrix $\boldsymbol J^{uu}$, while the matrix in the inner loop (V-cycle for the cheap solver, preconditioned CG for the expensive solver) is the original $\boldsymbol A$. I do not understand why this implementation provides a moderate convergence rate. It seems that the original author of the GMG solver planned to use the Jacobian in the inner loop, but did …

Reduce redundant computation in StokesOperator::local_apply()

---

include/aspect/particle/property/initial_composition.h

I think the old description was a leftover from copy/pasting it from the function plugin.

update description of initial composition particle property

---

include/aspect/simulator.h
include/aspect/simulator/solver/stokes_direct.h
include/aspect/simulator_access.h
include/aspect/stokes_matrix_free.h
source/simulator/core.cc
source/simulator/simulator_access.cc
source/simulator/solver.cc
source/simulator/solver/stokes_direct.cc
source/simulator/stokes_matrix_free.cc

The next step after #6251 towards making our solvers more modular and reducing the size of the Simulator class. This PR moves the code for the direct solver out of the simulator class and into a new class derived from `Solver::Interface`. To get this to work without making it a friend of Simulator I had to expose a few simulator functions through `SimulatorAccess` which also further reduced the use of simulator in StokesMatrixFree.
This is not ready for review yet! I want to see the test results first and want to do some further refactoring.

Implement direct Stokes solver class

---

include/aspect/material_model/reaction_model/grain_size_evolution.h
source/material_model/reaction_model/grain_size_evolution.cc
tests/grain_size_plunge_varied_step.prm
tests/grain_size_plunge_varied_step/screen-output
tests/grain_size_plunge_varied_step/statistics

This implements one TODO for the grain size evolution model, namely to be able to specify in the input file which initial step size and minimum step size ARKode is to use. This is useful, because in models with slowly changing properties increasing the minimum step size can speed up the model. But more importantly in models with quickly changing grain size the current default parameters sometimes (rarely) do not allow for the solver to converge to the intended accuracy, which leads to warnings. Being able to reduce the minimum step size fixes this issue.
@jdannberg can you take a look?

Add arkode grain size parameters

---

source/postprocess/composition_velocity_statistics.cc
tests/composition_velocity_zero.prm
tests/composition_velocity_zero/screen-output
tests/composition_velocity_zero/statistics
tests/kinematically_driven_subduction_2d_case1/screen-output
tests/kinematically_driven_subduction_2d_case1/statistics
tests/kinematically_driven_subduction_2d_case2a/screen-output
tests/kinematically_driven_subduction_2d_case2a/statistics
tests/kinematically_driven_subduction_2d_case2b/screen-output
tests/kinematically_driven_subduction_2d_case2b/statistics

The composition velocity statistics postprocessor had a few issues where it was possible to provide wrong input in the parameter file without an error message being triggered, resulting in either wrong output or a divide-by-zero. This PR improves this in several places and additionally allows for the input parameter being an empty list (if all the user wants is the average velocity of each compositional field, separately, rather than any combination). 
If a compositional field is zero throughout the model domain, the output for its velocity is now zero rather than NaN (which was what triggered the floating point exception before).

fix issues with area divided by being zero

---

source/material_model/melt_simple.cc
source/material_model/reaction_model/katz2003_mantle_melting.cc

@naliboff I think this should fix the problem from the [forum discussion](https://community.geodynamics.org/t/plastic-strain-in-reactive-fluid-transport-rheology/3996). 
The problem was that the katz 2003 reaction model set the reaction terms to zero for all fields, but it should be the responsibility of the material model to make sure these fields are filled, not the reaction model. Technically, the katz 2003 reaction model does not do anything with the `reaction_terms` at all, it is only concerned with `reaction_rates`. @gassmoeller suggested to simply move this code into the material model. This way, the katz 2003 reaction model will no longer overwrite the eraction terms set by the base model of the reactive fluid transport material model.

fill reaction terms in material model, not reaction model

---

source/postprocess/composition_velocity_statistics.cc

Follow-up to the comment in https://github.com/geodynamics/aspect/pull/6264#discussion_r2025115619. When we omit setting fields, there is always the question "well, what is the value going to be then". Make this clear.
@jdannberg FYI.

Be more explicit when we omit certain operations.

---

include/aspect/heating_model/adiabatic_heating.h
include/aspect/heating_model/adiabatic_heating_of_melt.h
include/aspect/heating_model/compositional_heating.h
include/aspect/heating_model/constant_heating.h
include/aspect/heating_model/function.h
include/aspect/heating_model/interface.h
include/aspect/heating_model/latent_heat.h
include/aspect/heating_model/latent_heat_melt.h
include/aspect/heating_model/radioactive_decay.h
include/aspect/heating_model/shear_heating.h
include/aspect/heating_model/shear_heating_with_melt.h
source/heating_model/adiabatic_heating.cc
source/heating_model/adiabatic_heating_of_melt.cc
source/heating_model/compositional_heating.cc
source/heating_model/constant_heating.cc
source/heating_model/function.cc
source/heating_model/interface.cc
source/heating_model/latent_heat.cc
source/heating_model/latent_heat_melt.cc
source/heating_model/radioactive_decay.cc
source/heating_model/shear_heating.cc
source/heating_model/shear_heating_with_melt.cc
source/material_model/rheology/visco_plastic.cc
source/material_model/visco_plastic.cc
source/simulator/assembly.cc
source/simulator/entropy_viscosity.cc
source/simulator/melt.cc

Some properties in the material model (in this case for me, it was the grain size change) can be expensive to compute. This PR allows the heating models to specify which material model outputs they need, and if the outputs are not required then they won't be filled in the temperature assembly. 
To make this work with user-written plugins, the default implementation is that all material model outputs are required.

add get_required_properties function to heating plugins

---

source/simulator/parameters.cc

I accidentally ran a model where there was a normalized field number was larger than the number of fields. I think we should assert for that, which is what this pull request implements.

Check if normalized fields are smaller then the number of compositional fields.

---

cookbooks/tomography_based_plate_motions/plugins/tomography_based_plate_motions.cc
source/material_model/grain_size.cc
source/material_model/reaction_model/grain_size_evolution.cc
source/postprocess/visualization/material_properties.cc
source/postprocess/visualization/named_additional_outputs.cc
source/simulator/assembly.cc
tests/melt_visco_plastic.cc

This builds on #6267 and #6271 (only the last commit is new) and specifies the required material model outputs in more places, for example in the graphical output where we really ask for all properties separately. 
Breaking tests will tell us which material models do take into account correctly when to compute which properties (i.e. if some properties depend on others which are not computed).

Only ask for required outputs in more places

---

include/aspect/material_model/grain_size.h
source/material_model/grain_size.cc
tests/grain_size_yield_phases.prm
tests/grain_size_yield_phases/screen-output
tests/grain_size_yield_phases/statistics

The implementation of plasticity in the grain size material model currently has minor issues that arise when one tries to use it together with multiple phase transitions and multiple compositions, because the function `drucker_prager_plasticity.compute_drucker_prager_parameters` is called with the number of phases instead of the number of phase transitions that it expects (off by one). This leads to triggered asserts no matter how one sets the input parameters.
I added a test that fails on the main branch and works with this change.
@jdannberg can you take a look?

Fix phases for background material and plasticity in the grain size material model.

---

doc/modules/changes/20250417_gassmoeller
source/material_model/reaction_model/grain_size_evolution.cc
tests/grain_size_crossed_transition_minimum.prm
tests/grain_size_crossed_transition_minimum/screen-output
tests/grain_size_crossed_transition_minimum/statistics

As described in the changelog and discussed with @jdannberg. There was a bug leading to wrong grain sizes if a phase transition would reset the grain size to something close to the minimum grain size (or if the grain size otherwise violated the minimum, while also being reset by the phase transition). The test makes this obvious by resetting to a smaller value than the minimum value, but the bug also occurred if resetting to exactly the minimum grain size. With the fix the grain size reset at phase transitions happens correctly, unless it would violate the minimum grain size, in which case it is reset to the minimum grain size.
I also think the new code is easier to understand.

Fix grain size reset at minimum grain size

---

benchmarks/entropy_adiabat/plugins/entropy_advection.cc
benchmarks/solitary_wave/solitary_wave.cc
include/aspect/advection_field.h
include/aspect/melt.h
include/aspect/simulator.h
include/aspect/simulator/assemblers/interface.h
include/aspect/volume_of_fluid/handler.h
source/mesh_refinement/compaction_length.cc
source/mesh_refinement/composition_gradient.cc
source/simulator/advection_field.cc
source/simulator/assemblers/advection.cc
source/simulator/assemblers/interface.cc
source/simulator/core.cc
source/simulator/helper_functions.cc
source/simulator/melt.cc
source/simulator/simulator_access.cc
source/volume_of_fluid/handler.cc
source/volume_of_fluid/setup_initial_conditions.cc

It was always a bit cumbersome to use the `AdvectionField` struct, because it was a member of the `Simulator` class, even though it is frequently used outside of this class. This PR moves the struct into its own file and makes it independent of the Simulator class. This makes using it more intuitive, and also allows to remove a lot of uses of `include <aspect/simulator.h>`, which only needed the AdvectionField. All existing code should continue to work, because I left a `using ...` directive inside the Simulator class.
As a follow-up I am considering moving all the functions inside `AdvectionField` that take `Introspection<dim` as an argument into the Introspection class. It feels more natural to ask `Introspection`: What is the polynomial degree of this `AdvectionField`, than to ask …

Move AdvectionField out of Simulator into separate file

---

source/simulator/assemblers/stokes.cc
tests/burstedde_bfbt/screen-output
tests/burstedde_bfbt/statistics

This pull request is part of #6280, where we change the pressure scaling factor and Mp_preconditioner in the case that the Weighted BFBT method is used to approximate the Schur Complement. I am opening this separate pull request which only changes the pressure scaling factor in order to test how changing this alone impacts the existing test results.
The Schur Complement is S=BA^{-1}B^T, which has a squared pressure scaling factor from the B and B^T blocks.
S^{-1}_{w-BFBT}=(BC^{-1]B^T)^{-1}(BC^{-1}AD^{-1}B^T)(BD^{-1}B^T)^{-1}.
Then when assembling the BC^{-1}B^T as a pressure Laplace problem with a squared pressure
scaling factor gives us an S^{-1}_{w-BFBT} with a pressure scaling to the power of -2,
which is consistent with S having a pressure scaling to the power of +2.
@tjhei

Change pressure scaling factor for Weighted BFBT.

---

source/simulator/assembly.cc
tests/burstedde_bfbt/statistics
tests/nsinker_bfbt/statistics

Switch the Mp_preconditioner to AMG when using Weighted BFBT to approximate the Schur Complement.

Use AMG for Weighted BFBT

---

include/aspect/boundary_traction/ascii_data.h

Follow-up to #6285 and #6297. @tiannh7: Like I mentioned this code is not wrong in its current form, but we do not usually default initialize variables in this way in ASPECT. Additionaly it is potentially confusing, because it splits the default value of the member variable from the default value of the input parameter (which is set in `declare_parameters`). This could lead to confusion in the future if someone only changes one but not the other.
It is our common pattern to rely on setting the variable values in the `parse_parameters` function and if for some reason we have to initialize them earlier (e.g. in the constructor) we would only set them to invalid values. Since there are no invalid values for a `bool`, I would just leave it uninitialized until the correct value is read from …

Remove a member initialization from header file

---

source/particle/property/crystal_preferred_orientation.cc

When building ASPECT on the cluster using Intel MPI, I encountered errors related to the World Builder construction. The build works fine with OpenMPI, so I chose to disable the World Builder by setting `ASPECT_WITH_WORLD_BUILDER=OFF`. 
This fix only addresses the errors that arise when `ASPECT_WITH_WORLD_BUILDER` is disabled. It resolves issues caused by missing macro definitions in the code when the World Builder feature is turned off. Other parts of the code or functionality are not affected by this change.

Add WorldBuilder macro definition

---

.github/workflows/clang.yml
.github/workflows/linux.yml
.github/workflows/typos.yml

Github deletes workflow results 90 days after the run, which is unfortunate when reviewing old PRs. This PR adds the option to manually trigger our github actions workflows. I hope this avoids having to rebase and force push in order to rerun the workflows.

Allow manual workflow trigger

---

source/mesh_deformation/fastscape.cc

Currently, if we use Fastscape with periodic boundaries for the front and back of the Fastscape domain, the front and back topography show abnormalities. See the topography at the front and back at the top of figure 1. 
We fix this by setting the Stokes velocity on the ghost nodes that is sent to Fastscape _before_ computing the direction of the periodicity from this velocity.  This actually comes down to only moving code. See the results for the same setup in figure 2. 
We will also test the left and right with periodic boundary conditions, but we have opened this pull request to start the discussion with @Djneu (and to practise making a pull request with @anne-glerum).

Fix Fastscape topography for periodic boundary by setting the values of ghost nodes earlier

---

benchmarks/viscosity_grooves/doc/viscosity_grooves.md
doc/sphinx/references.bib

bib: fix fieldstone

---

include/aspect/geometry_model/chunk.h
include/aspect/geometry_model/ellipsoidal_chunk.h
source/geometry_model/chunk.cc
source/geometry_model/ellipsoidal_chunk.cc

It doesn't seem like we are calling the `get_radius()`  function defined in the chunk and ellipsoidal chunk geometry models. This PR removes them. (I did not actually run the tests but only checked using `grep`).

Remove the unused function, get_radius()

---

source/mesh_deformation/fastscape.cc

Using `if constexpr` allows us to simplify some index handling.
@djneu @minerallo FYI

Clean up copying a table somewhat.

---

source/mesh_deformation/fastscape.cc

When returning a potentially large table, use move semantics to avoid the copy that may otherwise be involved.
@djneu @minerallo FYI

Optimize returning a potentially large table.

---

tests/additional_outputs_02.cc
tests/additional_outputs_03.cc
tests/heat_advection_by_melt.cc

When a test fails to compile, the CI infrastructure shows you both the compilation error but also the warnings generated in compiling this file. Many of the ones I frequently see are that certain functions can be marked with `override`. This patch addresses three files with some of these places.

Mark some functions in the test suite with 'override'.

---

include/aspect/material_model/interface.h

I forgot to fix this in #6342. Since we return shared pointers, no one place is now the owner of the object.

Remove a comment that's now no longer correct.

---

source/simulator/parameters.cc

Poking around where we use `Utilities::MPI::broadcast()`, I also found this place. I think the new version is easier to understand because we're only sending around a single scalar value.

Use the more modern version of MPI::broadcast().

---

source/material_model/equation_of_state/multicomponent_incompressible.cc
source/material_model/multicomponent.cc

Add some additional checks for the lists of material properties in models using the incompressible multicomponent equation of state. The equation of state can be used with phase transitions; if the material model calling it does not provide the number of phase transitions, it can still check internally that all lists it reads in have the same number of values. The multicomponent material model uses the incompressible multicomponent equation of state, but no phase transitions. We should therefore add this information to the options used for reading the map (because before this change, one could just provide anything in the list of values without an error being thrown and simply only the first n values would be used).

More error checks for multicomponent material model and equation of state

---

CMakeLists.txt

The library in question is typically a static lib, not a dynamic lib, and so the reference to the `.so` file is not quite correct.

Better error message for fastscape detection.

---

contrib/python/scripts/convert_friction_coeff_into_angles_of_internal_friction.py

Python code to convert friction coefficients into angles of internal friction so these be used as .prm inputs for the Drucker-Prager plasticity.

Convert friction coeff into angles of internal friction

---

doc/modules/changes/20250613_bakerdunn
include/aspect/postprocess/particle_distribution_score.h
source/postprocess/particle_distribution_score.cc
tests/particle_distribution_score.prm
tests/particle_distribution_score/screen-output
tests/particle_distribution_score/statistics
tests/particle_distribution_score_3d.prm
tests/particle_distribution_score_3d/screen-output
tests/particle_distribution_score_3d/statistics

This pull request adds a postprocessor which evaluates the density distribution of particles within each cell using a histogram method. This postprocessor aims to provide a quantitative way to evaluate the degree to which the removal of particles during load balancing leads to gradients of particle density. Evaluating density gradients in this way will make it easier to develop a new algorithm for creating and deleting particles during load balancing in order to avoid unwanted density gradients.

Add Particle histogram postprocessor

---

include/aspect/volume_of_fluid/handler.h

The error messages in #6416 are about the fact that we have explicit specializations of some VoF member functions, but that their existence is not declared before we explicitly instantiate the whole class. If we use separate file compilation, these functions are not visible and so the explicit instantiation just doesn't see them and does nothing about these functions. But if we use the unity build, everything may end up in one file and the compiler complains that you can explicitly specialize a function it has already tried to implicitly instantiate.
The solution is to *declare* the existence of these specializations.

Declare the existence of explicit specializations.

---

CMakeLists.txt

I don't recall why this was necessary, but it seems to work for me. Of course, it's possible that this is due to the specific combination of files CMake chooses on my machine -- let's see what happens on the testers...

No longer exclude volume_of_fluid/handler.cc from the unity builds.

---

CMakeLists.txt

This fixes #6417.
In #6362, I made sure that we also link against libgfortran.so when using Fastscape. This was necessary on my system because FastScape-fortran was linked into a static library that does not record that it depends on libgfortran. But on @xlia62 showed me that on his system, (i) libfastscape is a shared library, and (ii) it is linked against libgfortran.dylib that is located in some non-standard directory. As a consequence, when #6362 added `-lgfortran` to the command line (unnecessarily, because his .dylib already records this dependency), the linker failed because I don't provide a directory to find this library in. He works around this by providing a `-L<path to libgfortran.dylib>` flag explicitly, but that is not necessary.
The solution is to limit the `-lgfortran` …

Only link against gfortran when necessary.

---

tests/CMakeLists.txt

Really just some whitespace issues, plus actually requiring a current ASPECT version.

Minor updates to tests/CMakeLists.txt.

---

CONTRIBUTING.md

Added example astyle usage to docs.
Similar instructions are in the header of `aspect/contrib/utilities/astyle.rc`, but it is helpful to directly include example astyle usage for single files in `CONTRIBUTING.md`.

Add astyle example usage to CONTRIBUTING.md docs

---

CMakeLists.txt

Also arrange text better in the cmake output, by using empty lines.
No functional changes.

Disentangle the bottom of CMakeLists.txt.

---

tests/constant_tidal_heating.prm

This PR is about the addition to constant_tidal_heating test .prm showing the values of analytical calculation and numerical model calculation.
This was suggested to be added from https://github.com/geodynamics/aspect/pull/6350#discussion_r2150371320.
Last time @naliboff saw it, I put different decimal places for analytical and numerical model values.
But I used same decimal places here and values match well!

Adding lines to tidal heating test .prm file

---

doc/modules/changes/20250616_mfraters
include/aspect/postprocess/crystal_preferred_orientation.h
source/postprocess/crystal_preferred_orientation.cc

@Wang-yijun and @KiralyAgi noticed that when restarting a model with cpo, the numbering of the files starts again from zero. This is fixed by adding the serialization code.
@Wang-yijun, I don't know if this also fixes the other restart issue you had, but I could not reproduce it. Could you give it a try and send me your input files if it doesn't work?

Add CPO serialization.

---

doc/modules/changes/20250616_jdannberg
include/aspect/material_model/reaction_model/crust_and_lithosphere_formation.h
include/aspect/particle/property/crust_and_lithosphere_formation.h
source/material_model/reaction_model/crust_and_lithosphere_formation.cc
source/particle/property/crust_and_lithosphere_formation.cc
tests/crustal_formation_particles.prm
tests/crustal_formation_particles/screen-output
tests/crustal_formation_particles/statistics

@gassmoeller I was wondering if the names I have chosen to select this particle property in the input file make sense. I've left a ToDo there in the code as a reminder. 
This is the test case I made:
It shows that material is only converted to basalt and harzburgite in places where the velocity is upward (as defined by the scalar product between the unit vectors in the direction of velocity and inverse gravity being at least 0.5 -- an angle of 30 degrees between them --  as highlighted by the black contours). Within crustal depths, all composition is converted to basalt in that case, and within lithospheric depths the composition of the lithosphere changes linearly from the base of the crust to the base of the lithosphere, reflecting the changing degree of melting. However, within the …

Add a reaction model and particle property that allows for the generation of crust and lithosphere

---

source/particle/property/interface.cc

As pointed out by @gassmoeller in #6469.

check that plugins implement the advection_field_for_boundary_initialization function

---

source/mesh_deformation/fastscape.cc

Small follow-up to #6376. We should allow the sea level function to be defined either in years or in seconds, depending on the input parameter `Use years in output instead of seconds`. We do this for other functions as well.
FYI @xlia62

Allow sea level function defined in seconds

---

include/aspect/mesh_deformation/fastscape.h
include/aspect/mesh_deformation/interface.h
source/mesh_deformation/fastscape.cc
source/mesh_deformation/interface.cc
source/simulator/checkpoint_restart.cc

Hi @gassmoeller @bangerth,
here is the initial commit for rolling the fastscape-fortran restart into the checkpointing system. Thanks @gassmoeller for the help on getting this working through the mesh deformation handler! I've tested this on the cookbook, and it is working with restarts, but it ended up being a bit trickier than I expected so I'm not sure if this is the cleanest way to do it.
One issue was that these variables are all set within the const compute_velocity_constraints function, so I've set them to mutable within the header file. The second is that we save 3 potentially large vectors. At the moment I've set it so we fill these only when creating the checkpoint and keep them clear otherwise. Does this sound like the right way to approach this?

Add fastscape-fortran checkpointing

---

benchmarks/compressibility_formulations/plugins/compressibility_formulations.cc
source/material_model/equation_of_state/multicomponent_compressible.cc
source/material_model/multicomponent_compressible.cc
tests/check_compositional_field_functions.cc
tests/check_compositional_field_names.cc

This struct has been moved to another namespace in #5083. Remove the usage of the deprecated name and instead use the new name. I am surprised our testers do not produce warnings for this.

Remove usage of deprecated name

---

doc/plugin-CMakeLists.txt

@magmaxt missed one file in #6473, but that is easily fixed. This fixes #6437.

Use lower-case spelling in CMakeLists.txt.

---

source/geometry_model/initial_topography_model/ascii_data.cc
source/geometry_model/two_merged_chunks.cc

Currently, the depths in the `merged_chunk` geometry model does not account for the initial_topography. This PR modifies the implementation similar to PR #6374. 
Here is a visualization from a test :
There are no tests using merged chunks with topography, I am not sure if we need one.

Modify the depths in merged chunks to account for initial topo.

---

cookbooks/tomography_based_plate_motions/plugins/tomography_based_plate_motions.cc
cookbooks/tomography_based_plate_motions/plugins/tomography_based_plate_motions.h

Following PR #6439 , this PR adds a function that computes `lithosphere_thickness` for clarity.

Add lithosphere computation as a function.

---

doc/sphinx/user/install/local-installation/fastscape.md
doc/sphinx/user/install/local-installation/index.md
doc/sphinx/user/install/local-installation/obtaining.md

Here is the documentation for installing fastscape-fortran and linking it to ASPECT. I wasn't sure how to check how this would look in the manual so hopefully the formatting is okay! @gassmoeller

Add documentation on installing and linking fastscape-fortran to ASPECT

---

source/mesh_deformation/fastscape.cc

This came in through one of the recent FastScape patches. (@xlia62, @djneu: FYI)

Remove an invalid escape sequence.

---

source/material_model/reaction_model/grain_size_evolution.cc
source/material_model/reaction_model/katz2003_mantle_melting.cc
source/material_model/reaction_model/tian2019_solubility.cc
source/material_model/rheology/ascii_depth_profile.cc
source/material_model/rheology/composite_visco_plastic.cc
source/material_model/rheology/compositional_viscosity_prefactors.cc
source/material_model/rheology/constant_viscosity_prefactors.cc
source/material_model/rheology/diffusion_creep.cc
source/material_model/rheology/diffusion_dislocation.cc
source/material_model/rheology/dislocation_creep.cc
source/material_model/rheology/drucker_prager.cc
source/material_model/rheology/drucker_prager_power.cc
source/material_model/rheology/frank_kamenetskii.cc
source/material_model/rheology/friction_models.cc
source/material_model/rheology/peierls_creep.cc
source/material_model/rheology/strain_dependent.cc

These macros really just instantiate one class, but currently include opening and closing the namespace too. I think we should keep the macros as short as possible, this makes them easier to read and reduces the number of awkward line continuations `\`

Simplify some macros

---

include/aspect/postprocess/crystal_preferred_orientation.h
source/postprocess/crystal_preferred_orientation.cc

The CPO postprocessor plugin stores a copy of the end time. That's bad in itself, since it duplicates information stored elsewhere. But then it also gets it wrong: It compares the duplicated end time against `this->get_time()`, but `this->get_time()` always returns the time in seconds, whereas the plugin converted it into years when years were selected. That can't work.
This patch fixes this by simply not storing the duplicated information.
@MFraters FYI.

Do not store duplicate information. Also, don't mis-use it.

---

include/aspect/utilities.h
source/utilities.cc

Derive VectorFunctionFromVelocityFunctionObject from VectorFunctionFromTensorFunctionObject.

---

CMakeLists.txt
source/simulator/core.cc

#6426 allowed me to treat `volume_of_fluid/handler.cc` like any other file in unity builds and remove its special casing in #6416. I'd like to do the same for `core.cc`, which is the only file that's now being special-cased. This PR removes the special-casing. This works on my system, but let's see what happens with the tester.

No longer special-case core.cc for unity builds.

---

CMakeLists.txt

In #6497, I removed the definition of a variable `UNITY_SEPARATE_FILES`, assuming that it's a CMake-internal variable used in determining what files are to be excluded for unity builds. But it turns out that it's an ASPECT-specific variable that's used further down in the file. This patch removes the *use* of that variable, since it is no longer set.

Remove another vestige of separate unity builds.

---

doc/modules/changes/20250620_gassmoeller
include/aspect/compat.h
source/compat.cc
source/geometry_model/spherical_shell.cc
tests/thin_quarter_shell.prm
tests/thin_quarter_shell/screen-output
tests/thin_quarter_shell/statistics

This fixes a bug @hyunseong96 reported and that was fixed in deal.II in dealii/dealii#18568.
This is not quite ready to merge, I need to find a way to make this work without `if constexpr`, but dont have the time right now. I just wanted to open this to let @hyunseong96  and @Geoniette know about it. The test case tests a spherical shell with a radius of 1561 km and a thickness of 5 km, which now works as expected.

Fix thin 3d quarter shell boundary indicators

---

include/aspect/material_model/utilities.h
include/aspect/plugins.h
include/aspect/utilities.h
source/global.cc

These files all do MPI, and so need that header.

Include <mpi.h> where necessary.

---

include/aspect/simulator.h
source/simulator/simulator_access.cc

These files have functions that return references to `WorldBuilder::World`, but don't have the necessary `#include` to actually declare that class. Because we don't actually do anything with these objects here, it is sufficient to just forward declare the class.

Forward-declare WorldBuilder::World.

---

CMakeLists.txt

Header files and source files are treated differently when creating modules, and so it was convenient to break one cmake variable into two.

Have different cmake variables for header and source files.

---

include/aspect/citation_info.h
source/citation_info.cc

We had a namespace `::CitationInfo`. A better place for it is `aspect::CitationInfo`.

Move material into namespace aspect.

---

include/aspect/material_model/utilities.h
include/aspect/plugins.h
include/aspect/utilities.h
source/global.cc
source/postprocess/matrix_statistics.cc

See the discussion in #6565. This covers all places where we `#include <mpi.h>`.

Do not guard inclusion of <mpi.h> with DEAL_II_WITH_MPI.

---

CMakeLists.txt

We collect which files need to be built using `file(GLOB_RECURSE ...)` which is run at CMake time. As a consequence, when you add a file, it is not automatically picked up to be compiled *unless you call CMake by hand* -- that's because the build system (make or ninja) won't know about the file unless you call CMake. This is why generally the use of `GLOB` has been discouraged to list the source files by hand, and in deal.II for example we list all of them individually and by hand.
Newer CMake versions have introduced the `CONFIGURE_DEPENDS` option, which instructs make or ninja to re-glob the list of files and if it has changed, calls CMake. Use this where we collect our source files -- this way, new files will be automatically picked up, without anyone having to remember to call CMake …

Make sure we re-run cmake when we add files.

---

include/aspect/postprocess/particle_distribution_statistics.h
include/aspect/postprocess/particle_pdf.h
source/postprocess/particle_distribution_statistics.cc
source/postprocess/particle_pdf.cc

This pull request moves all of the code related to generating the point-density function from the ParticleDistributionStatistics postprocessor class to the ParticlePDF class. 
The point of this is so that individual particle managers can instantiate the ParticlePDF class separate from any postprocessors, in order to help with particle load balancing. In order to make it possible for particle managers to use the ParticlePDF class, all of the functions which generate the point-density function have been changed to operate on particle_ranges instead of on entire cells.

Move point density function code from ParticleDistributionStatistics to ParticlePDF

---

include/aspect/simulator.h

The particle handler objects owned by the particle manager class own an observer pointer to our `mapping` and the `triangulation` objects. Unfortunately the particle manager is currently listed higher up in simulator.h than those objects, which means it will be destroyed after the mapping and triangulation have already been destroyed. This can lead to crashes in the destructor, because the observer pointers complain that the object they point to has already been destroyed. I am somewhat confused why I only saw this error today in a test for the first time. But independent of the error, we initialize the particle managers right after the postprocess manager in core.cc:464, so it makes sense to have them in the same order in the header file.
Not sure if this warrants a changelog entry, it …

Ensure particle manager is destroyed before triangulation and mapping

---

cmake/AspectConfig.cmake.in

Force the testsuite to use the deal.II that was used to compile ASPECT and not whatever cmake likes to find.

testsuite: force correct deal.II path

---

source/mesh_deformation/interface.cc
source/simulator/assembly.cc
source/simulator/checkpoint_restart.cc
source/simulator/core.cc
source/simulator/solver/stokes_matrix_free_local_smoothing.cc

deal.II enabled deprecation warnings for deprecations introduced after the 9.6 release. This PR fixes our use of deprecated deal.II features. I havent tested this with deal.II 9.5 yet, we will see if we need to introduce some branches to keep compatibility with 9.5.

Fix deprecation warnings with deal.II >9.7

---

source/initial_composition/world_builder.cc
source/mesh_deformation/fastscape.cc

This change has no effect except that I needed it to build modules. I don't know when we're going to switch to modules, so for the moment the patch is not strictly necessary -- but it probably doesn't hurt either.

Make sure no file is truly empty.

---

source/material_model/reactive_fluid_transport.cc

While looking at #6556 I noticed that the code of the reactive fluid transport model is a bit confusing and in particular would potentially dereference a null pointer (if `out` is a null pointer the old line 89 would dereference it).
I fixed the null pointer dereference, but I still have an open question about the functionality of the function: In the current implementation this function will not do anything if `out` is not provided, even for the options that do not require access to `out`. This seems counterintuitive to the idea of an optional argument, either we should assert that `out` is always provided (if we only want to compute melt fractions if it exists), or we should support the case to compute melt fractions if possible even if `out` is not provided. Making an argument …

Simplify code and avoid dereferencing null pointer

---

doc/modules/changes/20250729_gassmoeller
include/aspect/postprocess/timing_statistics.h
source/postprocess/timing_statistics.cc
tests/timing_statistics.prm
tests/timing_statistics/screen-output

I added a new postprocessor for wall time information. Once I thought of this I was surprised we didnt introduce this years ago. I regret the amount of time I must have wasted reading the timing information (via script) out of the log files and reformatting it for various benchmark projects ...
Unfortunately the test result cannot include the output of the postprocessor as it is run dependent. But to show what it looks like in the statistics file:
```
0 0.000000000000e+00 0.000000000000e+00 4 59 25 50 0 0 0 6 7 7 1.50000000e+03 1.61944444e+03 1.67071068e+03 3.16576847e-02 7.23402504e-03 2.07302931e-02 5.8707e-03 8.1252e-03 3.5802e-03 4.3295e-04 6.4490e-05 3.1395e-04 2.8781e-01 0.0000e+00 1.5699e-02 9.6020e-03 2.3794e-03 9.0064e-03 1.9060e-04 2.8902e-04 
1 1.000000000000e+00 …
```

Added timing statistics postprocessor

---

.github/workflows/linux.yml

Github-Actions: use deal.II 9.6 for nounity and indent+doc tester

---

source/postprocess/particle_distribution_score.cc
tests/particle_distribution_score.prm
tests/particle_distribution_score_3d.prm

This pull request contains one commit which changes the capitalization of the ParticleDistributionScore postprocessor in the ASPECT_REGISTER_POSTPROCESSOR() function to be the same as every other postprocessor.
It was miss-capitalized as "Particle Distribution Score," now it's correctly capitalized as "particle distribution score".

Fix capitalization of ParticleDistributionScore postprocessor

---

source/main.cc
source/simulator/parameters.cc

Inspired by looking at #6626: Creating `std::regex` object is expensive (or at least should be: good implementations compile the regex into a state machine), and so we should be creating them once when they are used repeatedly. This patch pulls the creation of the regexes out of loops.

Re-use rather than re-created std::regex objects.

---

source/simulator/core.cc

Following a discussion on the environmental impact of scientific computing I thought it would be useful to output approximate resource usage information in our screen output. We already report total wall time, which can be approximately converted to total energy use and carbon emissions.
Of course these numbers are rough estimates, 5Wh/CPU hour is relatively optimistic for x86 server CPUs except for the latest generations, and carbon intensity of energy production varies a lot internationally and decreases rapidly in many countries in recent years. Additionally this does not include supply-chain energy use and carbon emission for producing the hardware/buildings/etc. Still I think it may be useful to report, simply to make users aware of the potential impact of their models. For most …

Expand resource usage report at model end to include energy and carbon intensity

---

source/postprocess/current_surface.cc

We are using ``MPI::compute_set_union`` with ``T=std::vector<std::vector<double>>`` but it is only instantiated in deal.II for ints. I am getting a linker error (but only on a branch, not sure why). This should fix it.
see:
https://github.com/geodynamics/aspect/blob/443cedb74086a212ac08256b20530436393f1425/source/postprocess/current_surface.cc#L88

add missing mpi.templates.h include

---

source/boundary_convective_heating/interface.cc

This patch implements the solution suggested in #6686 to ensure that we don't end up in the place mentioned in https://community.geodynamics.org/t/error-when-robin-boundary-condition-is-applied/4302 where an input file did not list any plugins for a plugin manager.
Fixes #6686.

Add assertions.

---

source/postprocess/timing_statistics.cc

Since dealii/dealii#18909 it is not allowed to access the timer information while inside a subsection. The only place where this is relevant for ASPECT is inside the timing statistics postprocessor (which is inside the Postprocessing section).
Fix the postprocessor to leave the subsection before requesting information. Since this is not really relevant and also works for older deal.II versions, I didnt bother limiting this to deal.II 9.8.0.
This fixes a tester failure observed in #6660.

Do not access timer inside subsection
